//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 

namespace UnicodeSrl.ASMN.WebNotificationService.DWH
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_IService", Namespace = "http://schemas.progel.it/WCF/Dwh/SoapEventoOutput/1.0")]
    public interface INotificaADT
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.progel.it/WCF/Dwh/SoapEventoOutput/1.0/IService/ListenData", RequestNamespace = "http://schemas.progel.it/WCF/Dwh/SoapEventoOutput/1.0", ResponseNamespace = "http://schemas.progel.it/WCF/Dwh/SoapEventoOutput/1.0", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        void ListenData([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] SoapEventoType value);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Dwh/SoapEventoOutput/1.0")]
    public partial class SoapEventoType
    {

        private string idMessaggioField;

        private System.DateTime dataSequenzaField;

        private int azioneField;

        private EventoType eventoField;

        private RicoveroType ricoveroField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdMessaggio
        {
            get
            {
                return this.idMessaggioField;
            }
            set
            {
                this.idMessaggioField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataSequenza
        {
            get
            {
                return this.dataSequenzaField;
            }
            set
            {
                this.dataSequenzaField = value;
            }
        }

        /// <remarks/>
        public int Azione
        {
            get
            {
                return this.azioneField;
            }
            set
            {
                this.azioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public EventoType Evento
        {
            get
            {
                return this.eventoField;
            }
            set
            {
                this.eventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public RicoveroType Ricovero
        {
            get
            {
                return this.ricoveroField;
            }
            set
            {
                this.ricoveroField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Dwh/SoapEventoOutput/1.0")]
    public partial class EventoType
    {

        private string idGuidField;

        private string idEsternoField;

        private string aziendaEroganteField;

        private string sistemaEroganteField;

        private PazienteType pazienteField;

        private System.DateTime dataEventoField;

        private string numeroNosologicoField;

        private CodiceDescrizioneType tipoEventoField;

        private AttributoType[] attributiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdGuid
        {
            get
            {
                return this.idGuidField;
            }
            set
            {
                this.idGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdEsterno
        {
            get
            {
                return this.idEsternoField;
            }
            set
            {
                this.idEsternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AziendaErogante
        {
            get
            {
                return this.aziendaEroganteField;
            }
            set
            {
                this.aziendaEroganteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SistemaErogante
        {
            get
            {
                return this.sistemaEroganteField;
            }
            set
            {
                this.sistemaEroganteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PazienteType Paziente
        {
            get
            {
                return this.pazienteField;
            }
            set
            {
                this.pazienteField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataEvento
        {
            get
            {
                return this.dataEventoField;
            }
            set
            {
                this.dataEventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NumeroNosologico
        {
            get
            {
                return this.numeroNosologicoField;
            }
            set
            {
                this.numeroNosologicoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType TipoEvento
        {
            get
            {
                return this.tipoEventoField;
            }
            set
            {
                this.tipoEventoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace = "http://schemas.progel.it/WCF/Dwh/SoapTypesOutput/1.0")]
        public AttributoType[] Attributi
        {
            get
            {
                return this.attributiField;
            }
            set
            {
                this.attributiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Dwh/SoapEventoOutput/1.0")]
    public partial class DiagnosiType
    {

        private string codiceField;

        private string descrizioneField;

        private string descrizioneLiberaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DescrizioneLibera
        {
            get
            {
                return this.descrizioneLiberaField;
            }
            set
            {
                this.descrizioneLiberaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Dwh/SoapEventoOutput/1.0")]
    public partial class RicoveroType
    {

        private string idField;

        private string idEsternoField;

        private System.DateTime dataModificaField;

        private string aziendaEroganteField;

        private string sistemaEroganteField;

        private CodiceDescrizioneType statoField;

        private CodiceDescrizioneType tipoRicoveroField;

        private DiagnosiType diagnosiField;

        private System.DateTime dataAccettazioneField;

        private bool dataAccettazioneFieldSpecified;

        private CodiceDescrizioneType repartoAccettazioneField;

        private System.DateTime dataDimissioneField;

        private bool dataDimissioneFieldSpecified;

        private CodiceDescrizioneType repartoDimissioneField;

        private System.DateTime dataTrasferimentoField;

        private bool dataTrasferimentoFieldSpecified;

        private CodiceDescrizioneType ospedaleField;

        private CodiceDescrizioneType repartoField;

        private CodiceDescrizioneType settoreField;

        private CodiceDescrizioneType lettoField;

        private AttributoType[] attributiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdEsterno
        {
            get
            {
                return this.idEsternoField;
            }
            set
            {
                this.idEsternoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataModifica
        {
            get
            {
                return this.dataModificaField;
            }
            set
            {
                this.dataModificaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AziendaErogante
        {
            get
            {
                return this.aziendaEroganteField;
            }
            set
            {
                this.aziendaEroganteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SistemaErogante
        {
            get
            {
                return this.sistemaEroganteField;
            }
            set
            {
                this.sistemaEroganteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Stato
        {
            get
            {
                return this.statoField;
            }
            set
            {
                this.statoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType TipoRicovero
        {
            get
            {
                return this.tipoRicoveroField;
            }
            set
            {
                this.tipoRicoveroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public DiagnosiType Diagnosi
        {
            get
            {
                return this.diagnosiField;
            }
            set
            {
                this.diagnosiField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataAccettazione
        {
            get
            {
                return this.dataAccettazioneField;
            }
            set
            {
                this.dataAccettazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataAccettazioneSpecified
        {
            get
            {
                return this.dataAccettazioneFieldSpecified;
            }
            set
            {
                this.dataAccettazioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType RepartoAccettazione
        {
            get
            {
                return this.repartoAccettazioneField;
            }
            set
            {
                this.repartoAccettazioneField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataDimissione
        {
            get
            {
                return this.dataDimissioneField;
            }
            set
            {
                this.dataDimissioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataDimissioneSpecified
        {
            get
            {
                return this.dataDimissioneFieldSpecified;
            }
            set
            {
                this.dataDimissioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType RepartoDimissione
        {
            get
            {
                return this.repartoDimissioneField;
            }
            set
            {
                this.repartoDimissioneField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataTrasferimento
        {
            get
            {
                return this.dataTrasferimentoField;
            }
            set
            {
                this.dataTrasferimentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataTrasferimentoSpecified
        {
            get
            {
                return this.dataTrasferimentoFieldSpecified;
            }
            set
            {
                this.dataTrasferimentoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Ospedale
        {
            get
            {
                return this.ospedaleField;
            }
            set
            {
                this.ospedaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Reparto
        {
            get
            {
                return this.repartoField;
            }
            set
            {
                this.repartoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Settore
        {
            get
            {
                return this.settoreField;
            }
            set
            {
                this.settoreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Letto
        {
            get
            {
                return this.lettoField;
            }
            set
            {
                this.lettoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace = "http://schemas.progel.it/WCF/Dwh/SoapTypesOutput/1.0")]
        public AttributoType[] Attributi
        {
            get
            {
                return this.attributiField;
            }
            set
            {
                this.attributiField = value;
            }
        }
    }

}
