//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace UnicodeSrl.ASMN.WebNotificationService.DWH
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_IService", Namespace = "http://schemas.progel.it/WCF/Dwh/SoapRefertoOutput/1.0")]
    public interface INotificaReferti
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.progel.it/WCF/Dwh/SoapRefertoOutput/1.0/IService/ListenData", RequestNamespace = "http://schemas.progel.it/WCF/Dwh/SoapRefertoOutput/1.0", ResponseNamespace = "http://schemas.progel.it/WCF/Dwh/SoapRefertoOutput/1.0", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        void ListenData([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] SoapRefertoType value);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Dwh/SoapRefertoOutput/1.0")]
    public partial class SoapRefertoType
    {

        private string idMessaggioField;

        private System.DateTime dataSequenzaField;

        private int azioneField;

        private RefertoType refertoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdMessaggio
        {
            get
            {
                return this.idMessaggioField;
            }
            set
            {
                this.idMessaggioField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataSequenza
        {
            get
            {
                return this.dataSequenzaField;
            }
            set
            {
                this.dataSequenzaField = value;
            }
        }

        /// <remarks/>
        public int Azione
        {
            get
            {
                return this.azioneField;
            }
            set
            {
                this.azioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public RefertoType Referto
        {
            get
            {
                return this.refertoField;
            }
            set
            {
                this.refertoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Dwh/SoapRefertoOutput/1.0")]
    public partial class RefertoType
    {

        private string idGuidField;

        private string idEsternoField;

        private string aziendaEroganteField;

        private string sistemaEroganteField;

        private CodiceDescrizioneType repartoEroganteField;

        private PazienteType pazienteField;

        private System.DateTime dataRefertoField;

        private bool dataRefertoFieldSpecified;

        private string numeroRefertoField;

        private string numeroNosologicoField;

        private string numeroPrenotazioneField;

        private string idRichiestaOEField;

        private CodiceDescrizioneType repartoRichiedenteField;

        private CodiceDescrizioneType statoRichiestaField;

        private CodiceDescrizioneType tipoRichiestaField;

        private CodiceDescrizioneType prioritaField;

        private string testoRefertoField;

        private CodiceDescrizioneType medicoRefertanteField;

        private AttributoType[] attributiField;

        private PrestazioneType[] prestazioniField;

        private AllegatoType[] allegatiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdGuid
        {
            get
            {
                return this.idGuidField;
            }
            set
            {
                this.idGuidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdEsterno
        {
            get
            {
                return this.idEsternoField;
            }
            set
            {
                this.idEsternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AziendaErogante
        {
            get
            {
                return this.aziendaEroganteField;
            }
            set
            {
                this.aziendaEroganteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SistemaErogante
        {
            get
            {
                return this.sistemaEroganteField;
            }
            set
            {
                this.sistemaEroganteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType RepartoErogante
        {
            get
            {
                return this.repartoEroganteField;
            }
            set
            {
                this.repartoEroganteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PazienteType Paziente
        {
            get
            {
                return this.pazienteField;
            }
            set
            {
                this.pazienteField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataReferto
        {
            get
            {
                return this.dataRefertoField;
            }
            set
            {
                this.dataRefertoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataRefertoSpecified
        {
            get
            {
                return this.dataRefertoFieldSpecified;
            }
            set
            {
                this.dataRefertoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NumeroReferto
        {
            get
            {
                return this.numeroRefertoField;
            }
            set
            {
                this.numeroRefertoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NumeroNosologico
        {
            get
            {
                return this.numeroNosologicoField;
            }
            set
            {
                this.numeroNosologicoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NumeroPrenotazione
        {
            get
            {
                return this.numeroPrenotazioneField;
            }
            set
            {
                this.numeroPrenotazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdRichiestaOE
        {
            get
            {
                return this.idRichiestaOEField;
            }
            set
            {
                this.idRichiestaOEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType RepartoRichiedente
        {
            get
            {
                return this.repartoRichiedenteField;
            }
            set
            {
                this.repartoRichiedenteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType StatoRichiesta
        {
            get
            {
                return this.statoRichiestaField;
            }
            set
            {
                this.statoRichiestaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType TipoRichiesta
        {
            get
            {
                return this.tipoRichiestaField;
            }
            set
            {
                this.tipoRichiestaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Priorita
        {
            get
            {
                return this.prioritaField;
            }
            set
            {
                this.prioritaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TestoReferto
        {
            get
            {
                return this.testoRefertoField;
            }
            set
            {
                this.testoRefertoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType MedicoRefertante
        {
            get
            {
                return this.medicoRefertanteField;
            }
            set
            {
                this.medicoRefertanteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace = "http://schemas.progel.it/WCF/Dwh/SoapTypesOutput/1.0")]
        public AttributoType[] Attributi
        {
            get
            {
                return this.attributiField;
            }
            set
            {
                this.attributiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Prestazione")]
        public PrestazioneType[] Prestazioni
        {
            get
            {
                return this.prestazioniField;
            }
            set
            {
                this.prestazioniField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Allegato")]
        public AllegatoType[] Allegati
        {
            get
            {
                return this.allegatiField;
            }
            set
            {
                this.allegatiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Dwh/SoapRefertoOutput/1.0")]
    public partial class AllegatoType
    {

        private string idEsternoField;

        private string nomeFileField;

        private System.DateTime dataFileField;

        private bool dataFileFieldSpecified;

        private string descrizioneField;

        private int posizioneField;

        private bool posizioneFieldSpecified;

        private CodiceDescrizioneType statoField;

        private string mimeTypeField;

        private byte[] mimeDataField;

        private AttributoType[] attributiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdEsterno
        {
            get
            {
                return this.idEsternoField;
            }
            set
            {
                this.idEsternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NomeFile
        {
            get
            {
                return this.nomeFileField;
            }
            set
            {
                this.nomeFileField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataFile
        {
            get
            {
                return this.dataFileField;
            }
            set
            {
                this.dataFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataFileSpecified
        {
            get
            {
                return this.dataFileFieldSpecified;
            }
            set
            {
                this.dataFileFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }

        /// <remarks/>
        public int Posizione
        {
            get
            {
                return this.posizioneField;
            }
            set
            {
                this.posizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PosizioneSpecified
        {
            get
            {
                return this.posizioneFieldSpecified;
            }
            set
            {
                this.posizioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Stato
        {
            get
            {
                return this.statoField;
            }
            set
            {
                this.statoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", IsNullable = true)]
        public byte[] MimeData
        {
            get
            {
                return this.mimeDataField;
            }
            set
            {
                this.mimeDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace = "http://schemas.progel.it/WCF/Dwh/SoapTypesOutput/1.0")]
        public AttributoType[] Attributi
        {
            get
            {
                return this.attributiField;
            }
            set
            {
                this.attributiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Dwh/SoapRefertoOutput/1.0")]
    public partial class PrestazioneType
    {

        private string idEsternoField;

        private System.DateTime dataErogazioneField;

        private bool dataErogazioneFieldSpecified;

        private CodiceDescrizioneType prestazioneField;

        private int prestazionePosizioneField;

        private bool prestazionePosizioneFieldSpecified;

        private CodiceDescrizioneType sezioneField;

        private int sezionePosizioneField;

        private bool sezionePosizioneFieldSpecified;

        private CodiceDescrizioneType gravitaField;

        private string risultatoField;

        private float risultatoNumericoField;

        private bool risultatoNumericoFieldSpecified;

        private string valoriRiferimentoField;

        private string commentiField;

        private AttributoType[] attributiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdEsterno
        {
            get
            {
                return this.idEsternoField;
            }
            set
            {
                this.idEsternoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataErogazione
        {
            get
            {
                return this.dataErogazioneField;
            }
            set
            {
                this.dataErogazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataErogazioneSpecified
        {
            get
            {
                return this.dataErogazioneFieldSpecified;
            }
            set
            {
                this.dataErogazioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Prestazione
        {
            get
            {
                return this.prestazioneField;
            }
            set
            {
                this.prestazioneField = value;
            }
        }

        /// <remarks/>
        public int PrestazionePosizione
        {
            get
            {
                return this.prestazionePosizioneField;
            }
            set
            {
                this.prestazionePosizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrestazionePosizioneSpecified
        {
            get
            {
                return this.prestazionePosizioneFieldSpecified;
            }
            set
            {
                this.prestazionePosizioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Sezione
        {
            get
            {
                return this.sezioneField;
            }
            set
            {
                this.sezioneField = value;
            }
        }

        /// <remarks/>
        public int SezionePosizione
        {
            get
            {
                return this.sezionePosizioneField;
            }
            set
            {
                this.sezionePosizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SezionePosizioneSpecified
        {
            get
            {
                return this.sezionePosizioneFieldSpecified;
            }
            set
            {
                this.sezionePosizioneFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Gravita
        {
            get
            {
                return this.gravitaField;
            }
            set
            {
                this.gravitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Risultato
        {
            get
            {
                return this.risultatoField;
            }
            set
            {
                this.risultatoField = value;
            }
        }

        /// <remarks/>
        public float RisultatoNumerico
        {
            get
            {
                return this.risultatoNumericoField;
            }
            set
            {
                this.risultatoNumericoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RisultatoNumericoSpecified
        {
            get
            {
                return this.risultatoNumericoFieldSpecified;
            }
            set
            {
                this.risultatoNumericoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ValoriRiferimento
        {
            get
            {
                return this.valoriRiferimentoField;
            }
            set
            {
                this.valoriRiferimentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Commenti
        {
            get
            {
                return this.commentiField;
            }
            set
            {
                this.commentiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace = "http://schemas.progel.it/WCF/Dwh/SoapTypesOutput/1.0")]
        public AttributoType[] Attributi
        {
            get
            {
                return this.attributiField;
            }
            set
            {
                this.attributiField = value;
            }
        }
    }

}
