//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicodeSrl.ScciCore.SvcRefertiDWH {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRefertiDWH.IScciRefertiDWH")]
    public interface IScciRefertiDWH {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRefertiDWH/RicercaRefertiDWH", ReplyAction="http://tempuri.org/IScciRefertiDWH/RicercaRefertiDWHResponse")]
        UnicodeSrl.Scci.DataContracts.RefertoDWH[] RicercaRefertiDWH(string idsac, System.DateTime datainizio, System.DateTime datafine, string tipoevidenzaclinica, string statoevidenzaclinica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRefertiDWH/CaricaRefertoDWH", ReplyAction="http://tempuri.org/IScciRefertiDWH/CaricaRefertoDWHResponse")]
        UnicodeSrl.Scci.DataContracts.AllegatoRefertoDWH[] CaricaRefertoDWH(string idreferto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRefertiDWH/CaricaRefertoDWHDettaglio", ReplyAction="http://tempuri.org/IScciRefertiDWH/CaricaRefertoDWHDettaglioResponse")]
        UnicodeSrl.Scci.DataContracts.RefertoDWHDetailed CaricaRefertoDWHDettaglio(string idreferto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRefertiDWH/RicercaContenutiReferto", ReplyAction="http://tempuri.org/IScciRefertiDWH/RicercaContenutiRefertoResponse")]
        System.Collections.Generic.Dictionary<string, string> RicercaContenutiReferto(string idreferto, UnicodeSrl.Scci.Enums.EnumTipoContenutiReferto tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRefertiDWH/CaricaContenutiDaListaID", ReplyAction="http://tempuri.org/IScciRefertiDWH/CaricaContenutiDaListaIDResponse")]
        string[] CaricaContenutiDaListaID(string idreferto, string[] idcontenuti, UnicodeSrl.Scci.Enums.EnumTipoContenutiReferto tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRefertiDWH/RicercaRefertiDWHTipi", ReplyAction="http://tempuri.org/IScciRefertiDWH/RicercaRefertiDWHTipiResponse")]
        UnicodeSrl.Scci.DataContracts.RefertoDWH[] RicercaRefertiDWHTipi(string idsac, System.DateTime datainizio, System.DateTime datafine, string[] tipievidenzaclinica, string[] statievidenzaclinica);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScciRefertiDWHChannel : UnicodeSrl.ScciCore.SvcRefertiDWH.IScciRefertiDWH, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScciRefertiDWHClient : System.ServiceModel.ClientBase<UnicodeSrl.ScciCore.SvcRefertiDWH.IScciRefertiDWH>, UnicodeSrl.ScciCore.SvcRefertiDWH.IScciRefertiDWH {
        
        public ScciRefertiDWHClient() {
        }
        
        public ScciRefertiDWHClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScciRefertiDWHClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScciRefertiDWHClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScciRefertiDWHClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnicodeSrl.Scci.DataContracts.RefertoDWH[] RicercaRefertiDWH(string idsac, System.DateTime datainizio, System.DateTime datafine, string tipoevidenzaclinica, string statoevidenzaclinica) {
            return base.Channel.RicercaRefertiDWH(idsac, datainizio, datafine, tipoevidenzaclinica, statoevidenzaclinica);
        }
        
        public UnicodeSrl.Scci.DataContracts.AllegatoRefertoDWH[] CaricaRefertoDWH(string idreferto) {
            return base.Channel.CaricaRefertoDWH(idreferto);
        }
        
        public UnicodeSrl.Scci.DataContracts.RefertoDWHDetailed CaricaRefertoDWHDettaglio(string idreferto) {
            return base.Channel.CaricaRefertoDWHDettaglio(idreferto);
        }
        
        public System.Collections.Generic.Dictionary<string, string> RicercaContenutiReferto(string idreferto, UnicodeSrl.Scci.Enums.EnumTipoContenutiReferto tipo) {
            return base.Channel.RicercaContenutiReferto(idreferto, tipo);
        }
        
        public string[] CaricaContenutiDaListaID(string idreferto, string[] idcontenuti, UnicodeSrl.Scci.Enums.EnumTipoContenutiReferto tipo) {
            return base.Channel.CaricaContenutiDaListaID(idreferto, idcontenuti, tipo);
        }
        
        public UnicodeSrl.Scci.DataContracts.RefertoDWH[] RicercaRefertiDWHTipi(string idsac, System.DateTime datainizio, System.DateTime datafine, string[] tipievidenzaclinica, string[] statievidenzaclinica) {
            return base.Channel.RicercaRefertiDWHTipi(idsac, datainizio, datafine, tipievidenzaclinica, statievidenzaclinica);
        }
    }
}
