namespace UnicodeSrl.ScciCore
{
    partial class frmConsegnePazienteCartella
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem3 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem4 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem5 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem6 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem7 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem8 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem9 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmConsegnePazienteCartella));
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTreeViewTipo = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ucEasyTableLayoutPanelFiltroData = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.udteFiltroDA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroDa = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.drFiltro = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.udteFiltroA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroA = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblMostraAnnullati = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.chkMostraAnnullati = new UnicodeSrl.ScciCore.ucEasyCheckEditor();
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ubAdd = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblMostraVistati = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.chkMostraVistati = new UnicodeSrl.ScciCore.ucEasyCheckEditor();
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewTipo)).BeginInit();
            this.ucEasyTableLayoutPanelFiltroData.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chkMostraAnnullati)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chkMostraVistati)).BeginInit();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(784, 24);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 24);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(784, 514);
            this.ultraGroupBox.TabIndex = 9;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 6;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1.010101F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80.80808F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1.010101F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.040404F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 12.12121F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1.010101F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTreeViewTipo, 3, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelFiltroData, 3, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblMostraAnnullati, 4, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.chkMostraAnnullati, 3, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGrid, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubAdd, 3, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblMostraVistati, 4, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.chkMostraVistati, 3, 2);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 7;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 49F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 22F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(778, 508);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 13.56716F;
            this.ucEasyTreeViewTipo.Appearance = appearance1;
            this.ucEasyTreeViewTipo.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTreeViewTipo, 2);
            this.ucEasyTreeViewTipo.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewTipo.HideSelection = false;
            this.ucEasyTreeViewTipo.Location = new System.Drawing.Point(645, 144);
            this.ucEasyTreeViewTipo.Name = "ucEasyTreeViewTipo";
            appearance2.BackColor = System.Drawing.Color.LightYellow;
            appearance2.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance2;
            _override1.SelectedNodeAppearance = appearance2;
            this.ucEasyTreeViewTipo.Override = _override1;
            this.ucEasyTreeViewTipo.Size = new System.Drawing.Size(119, 242);
            this.ucEasyTreeViewTipo.TabIndex = 14;
            this.ucEasyTreeViewTipo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeViewTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeViewTipo.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeViewTipo_AfterCheck);
                                                this.ucEasyTableLayoutPanelFiltroData.ColumnCount = 2;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelFiltroData, 2);
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.udteFiltroDA, 1, 0);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.lblFiltroDa, 0, 0);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.drFiltro, 1, 2);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.udteFiltroA, 1, 1);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.lblFiltroA, 0, 1);
            this.ucEasyTableLayoutPanelFiltroData.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltroData.Location = new System.Drawing.Point(645, 392);
            this.ucEasyTableLayoutPanelFiltroData.Name = "ucEasyTableLayoutPanelFiltroData";
            this.ucEasyTableLayoutPanelFiltroData.RowCount = 3;
            this.ucEasyTableLayoutPanelFiltroData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.ucEasyTableLayoutPanelFiltroData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.ucEasyTableLayoutPanelFiltroData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.ucEasyTableLayoutPanelFiltroData.Size = new System.Drawing.Size(119, 105);
            this.ucEasyTableLayoutPanelFiltroData.TabIndex = 12;
                                                appearance3.FontData.SizeInPoints = 13.56716F;
            this.udteFiltroDA.Appearance = appearance3;
            this.udteFiltroDA.AutoSize = false;
            this.udteFiltroDA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroDA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroDA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance4.FontData.SizeInPoints = 13.56716F;
            this.udteFiltroDA.DropDownAppearance = appearance4;
            this.udteFiltroDA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroDA.Location = new System.Drawing.Point(26, 3);
            this.udteFiltroDA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroDA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroDA.Name = "udteFiltroDA";
            this.udteFiltroDA.Size = new System.Drawing.Size(90, 28);
            this.udteFiltroDA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroDA.TabIndex = 1;
            this.udteFiltroDA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroDA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance5.FontData.SizeInPoints = 13.56716F;
            appearance5.TextVAlignAsString = "Middle";
            this.lblFiltroDa.Appearance = appearance5;
            this.lblFiltroDa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDa.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroDa.Name = "lblFiltroDa";
            this.lblFiltroDa.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroDa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDa.Size = new System.Drawing.Size(17, 28);
            this.lblFiltroDa.TabIndex = 2;
            this.lblFiltroDa.Text = "DA:";
            this.lblFiltroDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance6.FontData.SizeInPoints = 13.56716F;
            this.drFiltro.Appearance = appearance6;
            this.drFiltro.AutoSize = false;
            this.drFiltro.DataEpisodio = new System.DateTime(((long)(0)));
            this.drFiltro.DateFuture = false;
            this.drFiltro.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.drFiltro.DisponibilitaAgende = false;
            this.drFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.drFiltro.Domani = false;
            this.drFiltro.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem1.DisplayText = " ";
            valueListItem2.DataValue = "OGGI";
            valueListItem2.DisplayText = "Oggi";
            valueListItem3.DataValue = "24H";
            valueListItem3.DisplayText = "Ultime 24h";
            valueListItem4.DataValue = "48H";
            valueListItem4.DisplayText = "Ultime 48h";
            valueListItem5.DataValue = "7G";
            valueListItem5.DisplayText = "Ultimi 7gg";
            valueListItem6.DataValue = "30G";
            valueListItem6.DisplayText = "Ultimi 30gg";
            valueListItem7.DataValue = "60G";
            valueListItem7.DisplayText = "Ultimi 60gg";
            valueListItem8.DataValue = "90G";
            valueListItem8.DisplayText = "Ultimi 90gg";
            valueListItem9.DataValue = "6M";
            valueListItem9.DisplayText = "Ultimi 6 mesi";
            this.drFiltro.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2,
            valueListItem3,
            valueListItem4,
            valueListItem5,
            valueListItem6,
            valueListItem7,
            valueListItem8,
            valueListItem9});
            this.drFiltro.Location = new System.Drawing.Point(26, 72);
            this.drFiltro.Name = "drFiltro";
            this.drFiltro.Oggi = true;
            this.drFiltro.PassatoRemoto = false;
            this.drFiltro.Size = new System.Drawing.Size(90, 30);
            this.drFiltro.TabIndex = 0;
            this.drFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.drFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.drFiltro.ValueChanged += new System.EventHandler(this.drFiltro_ValueChanged);
                                                appearance7.FontData.SizeInPoints = 13.56716F;
            this.udteFiltroA.Appearance = appearance7;
            this.udteFiltroA.AutoSize = false;
            this.udteFiltroA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance8.FontData.SizeInPoints = 13.56716F;
            this.udteFiltroA.DropDownAppearance = appearance8;
            this.udteFiltroA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroA.Location = new System.Drawing.Point(26, 37);
            this.udteFiltroA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroA.Name = "udteFiltroA";
            this.udteFiltroA.Size = new System.Drawing.Size(90, 29);
            this.udteFiltroA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroA.TabIndex = 2;
            this.udteFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance9.FontData.SizeInPoints = 13.56716F;
            appearance9.TextVAlignAsString = "Middle";
            this.lblFiltroA.Appearance = appearance9;
            this.lblFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroA.Location = new System.Drawing.Point(3, 37);
            this.lblFiltroA.Name = "lblFiltroA";
            this.lblFiltroA.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroA.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroA.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroA.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroA.Size = new System.Drawing.Size(17, 29);
            this.lblFiltroA.TabIndex = 2;
            this.lblFiltroA.Text = "A:";
            this.lblFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance10.FontData.SizeInPoints = 13.56716F;
            appearance10.TextVAlignAsString = "Middle";
            this.lblMostraAnnullati.Appearance = appearance10;
            this.lblMostraAnnullati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMostraAnnullati.Location = new System.Drawing.Point(676, 114);
            this.lblMostraAnnullati.Name = "lblMostraAnnullati";
            this.lblMostraAnnullati.ShortcutColor = System.Drawing.Color.Black;
            this.lblMostraAnnullati.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblMostraAnnullati.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblMostraAnnullati.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblMostraAnnullati.Size = new System.Drawing.Size(88, 24);
            this.lblMostraAnnullati.TabIndex = 5;
            this.lblMostraAnnullati.Text = "Mostra Annullati";
            this.lblMostraAnnullati.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance11.BackColor = System.Drawing.Color.Transparent;
            appearance11.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance11.ImageBackground")));
            appearance11.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance11.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.chkMostraAnnullati.Appearance = appearance11;
            this.chkMostraAnnullati.BackColor = System.Drawing.Color.Transparent;
            this.chkMostraAnnullati.BackColorInternal = System.Drawing.Color.Transparent;
            this.chkMostraAnnullati.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Borderless;
            appearance12.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance12.ImageBackground")));
            appearance12.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance12.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.chkMostraAnnullati.CheckedAppearance = appearance12;
            this.chkMostraAnnullati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chkMostraAnnullati.Location = new System.Drawing.Point(645, 114);
            this.chkMostraAnnullati.Name = "chkMostraAnnullati";
            this.chkMostraAnnullati.Size = new System.Drawing.Size(25, 24);
            this.chkMostraAnnullati.Style = Infragistics.Win.EditCheckStyle.Button;
            this.chkMostraAnnullati.TabIndex = 4;
            this.chkMostraAnnullati.CheckedValueChanged += new System.EventHandler(this.chkMostraAnnullati_CheckedValueChanged);
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance13.BackColor = System.Drawing.SystemColors.Window;
            appearance13.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance13;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance14.FontData.BoldAsString = "True";
            appearance14.FontData.SizeInPoints = 13.56716F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance14;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance15.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance15.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance15.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance15.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance15;
            appearance16.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance16;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance17.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance17.BackColor2 = System.Drawing.SystemColors.Control;
            appearance17.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance17.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance17;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance18.BackColor = System.Drawing.SystemColors.Window;
            appearance18.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance18;
            appearance19.BackColor = System.Drawing.SystemColors.Highlight;
            appearance19.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance19;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance20.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance20;
            appearance21.BorderColor = System.Drawing.Color.Silver;
            appearance21.FontData.SizeInPoints = 13.56716F;
            appearance21.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance21;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance22.FontData.SizeInPoints = 13.56716F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance22;
            appearance23.BackColor = System.Drawing.SystemColors.Control;
            appearance23.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance23.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance23.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance23.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance23;
            appearance24.FontData.BoldAsString = "True";
            appearance24.FontData.SizeInPoints = 13.56716F;
            appearance24.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance24;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance25.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance25.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance25;
            appearance26.BackColor = System.Drawing.SystemColors.Window;
            appearance26.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance26;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance27.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance27;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(10, 8);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.ucEasyGrid, 5);
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(622, 489);
            this.ucEasyGrid.TabIndex = 0;
            this.ucEasyGrid.Text = "ucEasyGrid1";
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
            this.ucEasyGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucEasyGrid_ClickCell);
                                                appearance28.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance28.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance28.TextHAlignAsString = "Center";
            appearance28.TextVAlignAsString = "Bottom";
            this.ubAdd.Appearance = appearance28;
            this.ubAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ubAdd, 2);
            this.ubAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAdd.Location = new System.Drawing.Point(645, 8);
            this.ubAdd.Name = "ubAdd";
            this.ubAdd.PercImageFill = 0.75F;
            this.ubAdd.ShortcutColor = System.Drawing.Color.Black;
            this.ubAdd.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAdd.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAdd.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAdd.Size = new System.Drawing.Size(119, 70);
            this.ubAdd.TabIndex = 1;
            this.ubAdd.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubAdd.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAdd.Click += new System.EventHandler(this.ubAdd_Click);
                                                appearance29.FontData.SizeInPoints = 13.56716F;
            appearance29.TextVAlignAsString = "Middle";
            this.lblMostraVistati.Appearance = appearance29;
            this.lblMostraVistati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMostraVistati.Location = new System.Drawing.Point(676, 84);
            this.lblMostraVistati.Name = "lblMostraVistati";
            this.lblMostraVistati.ShortcutColor = System.Drawing.Color.Black;
            this.lblMostraVistati.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblMostraVistati.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblMostraVistati.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblMostraVistati.Size = new System.Drawing.Size(88, 24);
            this.lblMostraVistati.TabIndex = 2;
            this.lblMostraVistati.Text = "Mostra Vistati";
            this.lblMostraVistati.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance30.BackColor = System.Drawing.Color.Transparent;
            appearance30.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance30.ImageBackground")));
            appearance30.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance30.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.chkMostraVistati.Appearance = appearance30;
            this.chkMostraVistati.BackColor = System.Drawing.Color.Transparent;
            this.chkMostraVistati.BackColorInternal = System.Drawing.Color.Transparent;
            this.chkMostraVistati.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Borderless;
            appearance31.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance31.ImageBackground")));
            appearance31.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance31.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.chkMostraVistati.CheckedAppearance = appearance31;
            this.chkMostraVistati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chkMostraVistati.Location = new System.Drawing.Point(645, 84);
            this.chkMostraVistati.Name = "chkMostraVistati";
            this.chkMostraVistati.Size = new System.Drawing.Size(25, 24);
            this.chkMostraVistati.Style = Infragistics.Win.EditCheckStyle.Button;
            this.chkMostraVistati.TabIndex = 3;
            this.chkMostraVistati.CheckedValueChanged += new System.EventHandler(this.chkMostraVistati_CheckedValueChanged);
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmConsegnePazienteCartella";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmAlertGenerici";
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmConsegnePazienteCartella_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmConsegnePazienteCartella_PulsanteAvantiClick);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewTipo)).EndInit();
            this.ucEasyTableLayoutPanelFiltroData.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chkMostraAnnullati)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chkMostraVistati)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyGrid ucEasyGrid;
        private ucEasyButton ubAdd;
        private ucEasyLabel lblMostraVistati;
        private ucEasyCheckEditor chkMostraVistati;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private ucEasyLabel lblMostraAnnullati;
        private ucEasyCheckEditor chkMostraAnnullati;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltroData;
        private ucEasyDateTimeEditor udteFiltroDA;
        private ucEasyLabel lblFiltroDa;
        private ucEasyDateRange drFiltro;
        private ucEasyDateTimeEditor udteFiltroA;
        private ucEasyLabel lblFiltroA;
        private ucEasyTreeView ucEasyTreeViewTipo;
    }
}