namespace UnicodeSrl.ScciCore
{
    partial class frmIdentificazioneIterataPaziente
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmIdentificazioneIterataPaziente));
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblCercaPaziente = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblPaziente = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ubNonRilevare = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubRileva = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyGridParametri = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.txtCercaPaziente = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblPV = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyGridEpisodi = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridParametri)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtCercaPaziente)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridEpisodi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.SuspendLayout();
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 5;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 52F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 44F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblCercaPaziente, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblPaziente, 3, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubNonRilevare, 3, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubRileva, 3, 7);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGridParametri, 3, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.txtCercaPaziente, 1, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblPV, 3, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGridEpisodi, 1, 4);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 9;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(778, 508);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 22.54743F;
            appearance1.TextVAlignAsString = "Bottom";
            this.lblCercaPaziente.Appearance = appearance1;
            this.lblCercaPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCercaPaziente.Location = new System.Drawing.Point(10, 8);
            this.lblCercaPaziente.Name = "lblCercaPaziente";
            this.lblCercaPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblCercaPaziente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblCercaPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblCercaPaziente.Size = new System.Drawing.Size(398, 19);
            this.lblCercaPaziente.TabIndex = 0;
            this.lblCercaPaziente.Text = "Identifica Paziente:";
            this.lblCercaPaziente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance2.FontData.SizeInPoints = 22.54743F;
            this.lblPaziente.Appearance = appearance2;
            this.lblPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPaziente.Location = new System.Drawing.Point(429, 8);
            this.lblPaziente.Name = "lblPaziente";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.lblPaziente, 3);
            this.lblPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPaziente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPaziente.Size = new System.Drawing.Size(336, 59);
            this.lblPaziente.TabIndex = 1;
            this.lblPaziente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance3.FontData.SizeInPoints = 22.54743F;
            appearance3.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance3.ImageBackground")));
            appearance3.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance3.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance3.TextHAlignAsString = "Center";
            appearance3.TextVAlignAsString = "Middle";
            this.ubNonRilevare.Appearance = appearance3;
            this.ubNonRilevare.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubNonRilevare.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubNonRilevare.Location = new System.Drawing.Point(429, 402);
            this.ubNonRilevare.Name = "ubNonRilevare";
            this.ubNonRilevare.PercImageFill = 0.75F;
            this.ubNonRilevare.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubNonRilevare.ShortcutKey = System.Windows.Forms.Keys.F2;
            this.ubNonRilevare.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubNonRilevare.Size = new System.Drawing.Size(336, 44);
            this.ubNonRilevare.TabIndex = 3;
            this.ubNonRilevare.TabStop = false;
            this.ubNonRilevare.Text = "NON RILEVARE PARAMETRO";
            this.ubNonRilevare.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ubNonRilevare.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubNonRilevare.Click += new System.EventHandler(this.ubNonRilevare_Click);
            this.ubNonRilevare.Enter += new System.EventHandler(this.controls_Enter);
                                                appearance4.FontData.SizeInPoints = 22.54743F;
            appearance4.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance4.ImageBackground")));
            appearance4.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance4.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance4.TextHAlignAsString = "Center";
            appearance4.TextVAlignAsString = "Middle";
            this.ubRileva.Appearance = appearance4;
            this.ubRileva.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubRileva.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRileva.Location = new System.Drawing.Point(429, 452);
            this.ubRileva.Name = "ubRileva";
            this.ubRileva.PercImageFill = 0.75F;
            this.ubRileva.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubRileva.ShortcutKey = System.Windows.Forms.Keys.F3;
            this.ubRileva.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubRileva.Size = new System.Drawing.Size(336, 44);
            this.ubRileva.TabIndex = 4;
            this.ubRileva.TabStop = false;
            this.ubRileva.Text = "RILEVA PARAMETRO";
            this.ubRileva.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ubRileva.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubRileva.Click += new System.EventHandler(this.ubRileva_Click);
            this.ubRileva.Enter += new System.EventHandler(this.controls_Enter);
                                                this.ucEasyGridParametri.ColonnaRTFResize = "";
            this.ucEasyGridParametri.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridParametri.DisplayLayout.Appearance = appearance5;
            this.ucEasyGridParametri.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridParametri.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance6.FontData.BoldAsString = "True";
            appearance6.FontData.SizeInPoints = 18.31978F;
            this.ucEasyGridParametri.DisplayLayout.CaptionAppearance = appearance6;
            this.ucEasyGridParametri.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance7.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance7.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance7.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance7.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridParametri.DisplayLayout.GroupByBox.Appearance = appearance7;
            appearance8.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridParametri.DisplayLayout.GroupByBox.BandLabelAppearance = appearance8;
            this.ucEasyGridParametri.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridParametri.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridParametri.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance9.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance9.BackColor2 = System.Drawing.SystemColors.Control;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridParametri.DisplayLayout.GroupByBox.PromptAppearance = appearance9;
            this.ucEasyGridParametri.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridParametri.DisplayLayout.MaxRowScrollRegions = 1;
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            appearance10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridParametri.DisplayLayout.Override.ActiveCellAppearance = appearance10;
            appearance11.BackColor = System.Drawing.SystemColors.Highlight;
            appearance11.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridParametri.DisplayLayout.Override.ActiveRowAppearance = appearance11;
            this.ucEasyGridParametri.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridParametri.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridParametri.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridParametri.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridParametri.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridParametri.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridParametri.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance12.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridParametri.DisplayLayout.Override.CardAreaAppearance = appearance12;
            appearance13.BorderColor = System.Drawing.Color.Silver;
            appearance13.FontData.SizeInPoints = 18.31978F;
            appearance13.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridParametri.DisplayLayout.Override.CellAppearance = appearance13;
            this.ucEasyGridParametri.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridParametri.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridParametri.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance14.FontData.SizeInPoints = 18.31978F;
            this.ucEasyGridParametri.DisplayLayout.Override.FilterRowAppearance = appearance14;
            appearance15.BackColor = System.Drawing.SystemColors.Control;
            appearance15.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance15.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance15.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance15.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridParametri.DisplayLayout.Override.GroupByRowAppearance = appearance15;
            appearance16.FontData.BoldAsString = "True";
            appearance16.FontData.SizeInPoints = 18.31978F;
            appearance16.TextHAlignAsString = "Center";
            this.ucEasyGridParametri.DisplayLayout.Override.HeaderAppearance = appearance16;
            this.ucEasyGridParametri.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridParametri.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance17.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance17.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridParametri.DisplayLayout.Override.RowAlternateAppearance = appearance17;
            appearance18.BackColor = System.Drawing.SystemColors.Window;
            appearance18.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridParametri.DisplayLayout.Override.RowAppearance = appearance18;
            this.ucEasyGridParametri.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridParametri.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridParametri.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridParametri.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance19.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridParametri.DisplayLayout.Override.TemplateAddRowAppearance = appearance19;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridParametri.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridParametri.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridParametri.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridParametri.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridParametri.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridParametri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridParametri.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridParametri.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridParametri.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridParametri.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridParametri.Location = new System.Drawing.Point(429, 98);
            this.ucEasyGridParametri.Name = "ucEasyGridParametri";
            this.ucEasyGridParametri.ShowFilterRow = false;
            this.ucEasyGridParametri.ShowGroupByBox = false;
            this.ucEasyGridParametri.Size = new System.Drawing.Size(336, 298);
            this.ucEasyGridParametri.TabIndex = 2;
            this.ucEasyGridParametri.TabStop = false;
            this.ucEasyGridParametri.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridParametri.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridParametri.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridParametri_InitializeLayout);
            this.ucEasyGridParametri.AfterSelectChange += new Infragistics.Win.UltraWinGrid.AfterSelectChangeEventHandler(this.ucEasyGridParametri_AfterSelectChange);
            this.ucEasyGridParametri.Enter += new System.EventHandler(this.controls_Enter);
                                                appearance20.FontData.SizeInPoints = 22.54743F;
            this.txtCercaPaziente.Appearance = appearance20;
            this.txtCercaPaziente.AutoSize = false;
            this.txtCercaPaziente.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtCercaPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCercaPaziente.Location = new System.Drawing.Point(10, 33);
            this.txtCercaPaziente.Name = "txtCercaPaziente";
            this.txtCercaPaziente.Size = new System.Drawing.Size(398, 29);
            this.txtCercaPaziente.TabIndex = 0;
            this.txtCercaPaziente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.txtCercaPaziente.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.txtCercaPaziente.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtCercaPaziente_KeyDown);
                                                appearance21.FontData.SizeInPoints = 18.31978F;
            this.lblPV.Appearance = appearance21;
            this.lblPV.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPV.Location = new System.Drawing.Point(429, 73);
            this.lblPV.Name = "lblPV";
            this.lblPV.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPV.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPV.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPV.Size = new System.Drawing.Size(336, 19);
            this.lblPV.TabIndex = 7;
            this.lblPV.Text = "Elenco PV:";
            this.lblPV.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucEasyGridEpisodi.ColonnaRTFResize = "";
            this.ucEasyGridEpisodi.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            appearance22.BackColor = System.Drawing.SystemColors.Window;
            appearance22.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridEpisodi.DisplayLayout.Appearance = appearance22;
            this.ucEasyGridEpisodi.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridEpisodi.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance23.FontData.BoldAsString = "True";
            this.ucEasyGridEpisodi.DisplayLayout.CaptionAppearance = appearance23;
            this.ucEasyGridEpisodi.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance24.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance24.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance24.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance24.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridEpisodi.DisplayLayout.GroupByBox.Appearance = appearance24;
            appearance25.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridEpisodi.DisplayLayout.GroupByBox.BandLabelAppearance = appearance25;
            this.ucEasyGridEpisodi.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridEpisodi.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridEpisodi.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance26.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance26.BackColor2 = System.Drawing.SystemColors.Control;
            appearance26.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance26.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridEpisodi.DisplayLayout.GroupByBox.PromptAppearance = appearance26;
            this.ucEasyGridEpisodi.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridEpisodi.DisplayLayout.MaxRowScrollRegions = 1;
            appearance27.BackColor = System.Drawing.SystemColors.Window;
            appearance27.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridEpisodi.DisplayLayout.Override.ActiveCellAppearance = appearance27;
            appearance28.BackColor = System.Drawing.SystemColors.Highlight;
            appearance28.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridEpisodi.DisplayLayout.Override.ActiveRowAppearance = appearance28;
            this.ucEasyGridEpisodi.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridEpisodi.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridEpisodi.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridEpisodi.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridEpisodi.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridEpisodi.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridEpisodi.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance29.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridEpisodi.DisplayLayout.Override.CardAreaAppearance = appearance29;
            appearance30.BorderColor = System.Drawing.Color.Silver;
            appearance30.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridEpisodi.DisplayLayout.Override.CellAppearance = appearance30;
            this.ucEasyGridEpisodi.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridEpisodi.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridEpisodi.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance31.BackColor = System.Drawing.SystemColors.Control;
            appearance31.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance31.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance31.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance31.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridEpisodi.DisplayLayout.Override.GroupByRowAppearance = appearance31;
            appearance32.FontData.BoldAsString = "True";
            appearance32.TextHAlignAsString = "Center";
            this.ucEasyGridEpisodi.DisplayLayout.Override.HeaderAppearance = appearance32;
            this.ucEasyGridEpisodi.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridEpisodi.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance33.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance33.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridEpisodi.DisplayLayout.Override.RowAlternateAppearance = appearance33;
            appearance34.BackColor = System.Drawing.SystemColors.Window;
            appearance34.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridEpisodi.DisplayLayout.Override.RowAppearance = appearance34;
            this.ucEasyGridEpisodi.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridEpisodi.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridEpisodi.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridEpisodi.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance35.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridEpisodi.DisplayLayout.Override.TemplateAddRowAppearance = appearance35;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridEpisodi.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGridEpisodi.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridEpisodi.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridEpisodi.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridEpisodi.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridEpisodi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridEpisodi.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridEpisodi.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ucEasyGridEpisodi.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ucEasyGridEpisodi.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ucEasyGridEpisodi.Location = new System.Drawing.Point(10, 73);
            this.ucEasyGridEpisodi.Name = "ucEasyGridEpisodi";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.ucEasyGridEpisodi, 4);
            this.ucEasyGridEpisodi.ShowFilterRow = false;
            this.ucEasyGridEpisodi.ShowGroupByBox = false;
            this.ucEasyGridEpisodi.Size = new System.Drawing.Size(398, 423);
            this.ucEasyGridEpisodi.TabIndex = 1;
            this.ucEasyGridEpisodi.TabStop = false;
            this.ucEasyGridEpisodi.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridEpisodi.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridEpisodi.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridEpisodi_InitializeLayout);
            this.ucEasyGridEpisodi.AfterSelectChange += new Infragistics.Win.UltraWinGrid.AfterSelectChangeEventHandler(this.ucEasyGridEpisodi_AfterSelectChange);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 24);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(784, 514);
            this.ultraGroupBox.TabIndex = 0;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmIdentificazioneIterataPaziente";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmIdentificazioneIterataPaziente";
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmIdentificazioneIterataPaziente_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmIdentificazioneIterataPaziente_PulsanteAvantiClick);
            this.Activated += new System.EventHandler(this.frmIdentificazioneIterataPaziente_Activated);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridParametri)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtCercaPaziente)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridEpisodi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyLabel lblCercaPaziente;
        private ucEasyLabel lblPaziente;
        private ucEasyButton ubNonRilevare;
        private ucEasyButton ubRileva;
        private ucEasyGrid ucEasyGridParametri;
        private ucEasyTextBox txtCercaPaziente;
        private ucEasyLabel lblPV;
        private ucEasyGrid ucEasyGridEpisodi;
    }
}