namespace UnicodeSrl.ScciCore
{
    partial class frmPUOrdineDatiAggiuntivi
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.TableLayoutPanelOrdine = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyLabel1 = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblDataOraProgrammazioneTitolo = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblPrioritaTitolo = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblStatoValidita = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblDataOraProgrammazione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblPriorita = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyGridPrestazioni = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.tlpDatiAggiuntivi = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubCopiaDati = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ehViewer = new System.Windows.Forms.Integration.ElementHost();
            this.ubInoltraOrdine = new UnicodeSrl.ScciCore.ucEasyButton();
            this.UltraPopupControlContainerSegnalibri = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            this.TableLayoutPanelOrdine.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridPrestazioni)).BeginInit();
            this.tlpDatiAggiuntivi.SuspendLayout();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(1122, 30);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 30);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(1122, 656);
            this.ultraGroupBox.TabIndex = 4;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 4;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 68F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.TableLayoutPanelOrdine, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.tlpDatiAggiuntivi, 2, 1);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 3;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(1116, 650);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.TableLayoutPanelOrdine.ColumnCount = 1;
            this.TableLayoutPanelOrdine.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelOrdine.Controls.Add(this.ucEasyLabel1, 0, 4);
            this.TableLayoutPanelOrdine.Controls.Add(this.lblDataOraProgrammazioneTitolo, 0, 2);
            this.TableLayoutPanelOrdine.Controls.Add(this.lblPrioritaTitolo, 0, 0);
            this.TableLayoutPanelOrdine.Controls.Add(this.lblStatoValidita, 0, 5);
            this.TableLayoutPanelOrdine.Controls.Add(this.lblDataOraProgrammazione, 0, 3);
            this.TableLayoutPanelOrdine.Controls.Add(this.lblPriorita, 0, 1);
            this.TableLayoutPanelOrdine.Controls.Add(this.ucEasyGridPrestazioni, 0, 6);
            this.TableLayoutPanelOrdine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelOrdine.Location = new System.Drawing.Point(14, 9);
            this.TableLayoutPanelOrdine.Name = "TableLayoutPanelOrdine";
            this.TableLayoutPanelOrdine.RowCount = 7;
            this.TableLayoutPanelOrdine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanelOrdine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.TableLayoutPanelOrdine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanelOrdine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.TableLayoutPanelOrdine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanelOrdine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanelOrdine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 63F));
            this.TableLayoutPanelOrdine.Size = new System.Drawing.Size(328, 631);
            this.TableLayoutPanelOrdine.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 13.97015F;
            appearance1.TextVAlignAsString = "Middle";
            this.ucEasyLabel1.Appearance = appearance1;
            this.ucEasyLabel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabel1.Location = new System.Drawing.Point(3, 139);
            this.ucEasyLabel1.Name = "ucEasyLabel1";
            this.ucEasyLabel1.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyLabel1.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabel1.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabel1.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabel1.Size = new System.Drawing.Size(322, 25);
            this.ucEasyLabel1.TabIndex = 16;
            this.ucEasyLabel1.Text = "Stato Validità Ordine";
            this.ucEasyLabel1.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance2.FontData.SizeInPoints = 13.97015F;
            appearance2.TextVAlignAsString = "Middle";
            this.lblDataOraProgrammazioneTitolo.Appearance = appearance2;
            this.lblDataOraProgrammazioneTitolo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataOraProgrammazioneTitolo.Location = new System.Drawing.Point(3, 71);
            this.lblDataOraProgrammazioneTitolo.Name = "lblDataOraProgrammazioneTitolo";
            this.lblDataOraProgrammazioneTitolo.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataOraProgrammazioneTitolo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataOraProgrammazioneTitolo.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataOraProgrammazioneTitolo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataOraProgrammazioneTitolo.Size = new System.Drawing.Size(322, 25);
            this.lblDataOraProgrammazioneTitolo.TabIndex = 15;
            this.lblDataOraProgrammazioneTitolo.Text = "Data e Ora Programmazione";
            this.lblDataOraProgrammazioneTitolo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance3.FontData.SizeInPoints = 13.97015F;
            appearance3.TextVAlignAsString = "Middle";
            this.lblPrioritaTitolo.Appearance = appearance3;
            this.lblPrioritaTitolo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPrioritaTitolo.Location = new System.Drawing.Point(3, 3);
            this.lblPrioritaTitolo.Name = "lblPrioritaTitolo";
            this.lblPrioritaTitolo.ShortcutColor = System.Drawing.Color.Black;
            this.lblPrioritaTitolo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPrioritaTitolo.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPrioritaTitolo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPrioritaTitolo.Size = new System.Drawing.Size(322, 25);
            this.lblPrioritaTitolo.TabIndex = 14;
            this.lblPrioritaTitolo.Text = "Priorità";
            this.lblPrioritaTitolo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance4.FontData.SizeInPoints = 20.1791F;
            appearance4.TextVAlignAsString = "Top";
            this.lblStatoValidita.Appearance = appearance4;
            this.lblStatoValidita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStatoValidita.Location = new System.Drawing.Point(3, 170);
            this.lblStatoValidita.Name = "lblStatoValidita";
            this.lblStatoValidita.ShortcutColor = System.Drawing.Color.Black;
            this.lblStatoValidita.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblStatoValidita.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblStatoValidita.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblStatoValidita.Size = new System.Drawing.Size(322, 57);
            this.lblStatoValidita.TabIndex = 13;
            this.lblStatoValidita.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance5.FontData.SizeInPoints = 20.1791F;
            appearance5.TextVAlignAsString = "Middle";
            this.lblDataOraProgrammazione.Appearance = appearance5;
            this.lblDataOraProgrammazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataOraProgrammazione.Location = new System.Drawing.Point(3, 102);
            this.lblDataOraProgrammazione.Name = "lblDataOraProgrammazione";
            this.lblDataOraProgrammazione.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataOraProgrammazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblDataOraProgrammazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataOraProgrammazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataOraProgrammazione.Size = new System.Drawing.Size(322, 31);
            this.lblDataOraProgrammazione.TabIndex = 12;
            this.lblDataOraProgrammazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance6.FontData.SizeInPoints = 20.1791F;
            appearance6.TextVAlignAsString = "Middle";
            this.lblPriorita.Appearance = appearance6;
            this.lblPriorita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPriorita.Location = new System.Drawing.Point(3, 34);
            this.lblPriorita.Name = "lblPriorita";
            this.lblPriorita.ShortcutColor = System.Drawing.Color.Black;
            this.lblPriorita.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblPriorita.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPriorita.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPriorita.Size = new System.Drawing.Size(322, 31);
            this.lblPriorita.TabIndex = 11;
            this.lblPriorita.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucEasyGridPrestazioni.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridPrestazioni.ColonnaRTFResize = "";
            this.ucEasyGridPrestazioni.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridPrestazioni.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            appearance7.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridPrestazioni.DisplayLayout.Appearance = appearance7;
            this.ucEasyGridPrestazioni.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridPrestazioni.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance8.FontData.BoldAsString = "True";
            appearance8.FontData.SizeInPoints = 13.97015F;
            this.ucEasyGridPrestazioni.DisplayLayout.CaptionAppearance = appearance8;
            this.ucEasyGridPrestazioni.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance9.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.Appearance = appearance9;
            appearance10.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.BandLabelAppearance = appearance10;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance11.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance11.BackColor2 = System.Drawing.SystemColors.Control;
            appearance11.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance11.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.PromptAppearance = appearance11;
            this.ucEasyGridPrestazioni.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridPrestazioni.DisplayLayout.MaxRowScrollRegions = 1;
            appearance12.BackColor = System.Drawing.SystemColors.Window;
            appearance12.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.ActiveCellAppearance = appearance12;
            appearance13.BackColor = System.Drawing.SystemColors.Highlight;
            appearance13.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.ActiveRowAppearance = appearance13;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.CardAreaAppearance = appearance14;
            appearance15.BorderColor = System.Drawing.Color.Silver;
            appearance15.FontData.SizeInPoints = 13.97015F;
            appearance15.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.CellAppearance = appearance15;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance16.FontData.SizeInPoints = 13.97015F;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.FilterRowAppearance = appearance16;
            appearance17.BackColor = System.Drawing.SystemColors.Control;
            appearance17.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance17.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance17.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance17.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.GroupByRowAppearance = appearance17;
            appearance18.FontData.BoldAsString = "True";
            appearance18.FontData.SizeInPoints = 13.97015F;
            appearance18.TextHAlignAsString = "Center";
            this.ucEasyGridPrestazioni.DisplayLayout.Override.HeaderAppearance = appearance18;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance19.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance19.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.RowAlternateAppearance = appearance19;
            appearance20.BackColor = System.Drawing.SystemColors.Window;
            appearance20.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.RowAppearance = appearance20;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance21.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.TemplateAddRowAppearance = appearance21;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridPrestazioni.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridPrestazioni.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridPrestazioni.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridPrestazioni.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridPrestazioni.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridPrestazioni.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridPrestazioni.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridPrestazioni.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridPrestazioni.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridPrestazioni.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridPrestazioni.Location = new System.Drawing.Point(3, 233);
            this.ucEasyGridPrestazioni.Name = "ucEasyGridPrestazioni";
            this.ucEasyGridPrestazioni.ShowFilterRow = false;
            this.ucEasyGridPrestazioni.ShowGroupByBox = false;
            this.ucEasyGridPrestazioni.Size = new System.Drawing.Size(322, 395);
            this.ucEasyGridPrestazioni.TabIndex = 10;
            this.ucEasyGridPrestazioni.Text = "ucEasyGrid1";
            this.ucEasyGridPrestazioni.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridPrestazioni.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridPrestazioni_InitializeLayout);
            this.ucEasyGridPrestazioni.AfterRowActivate += new System.EventHandler(this.ucEasyGridPrestazioni_AfterRowActivate);
                                                this.tlpDatiAggiuntivi.ColumnCount = 2;
            this.tlpDatiAggiuntivi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.tlpDatiAggiuntivi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tlpDatiAggiuntivi.Controls.Add(this.ubCopiaDati, 0, 0);
            this.tlpDatiAggiuntivi.Controls.Add(this.ehViewer, 0, 1);
            this.tlpDatiAggiuntivi.Controls.Add(this.ubInoltraOrdine, 0, 2);
            this.tlpDatiAggiuntivi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpDatiAggiuntivi.Location = new System.Drawing.Point(348, 9);
            this.tlpDatiAggiuntivi.Name = "tlpDatiAggiuntivi";
            this.tlpDatiAggiuntivi.RowCount = 3;
            this.tlpDatiAggiuntivi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.tlpDatiAggiuntivi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 84F));
            this.tlpDatiAggiuntivi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.tlpDatiAggiuntivi.Size = new System.Drawing.Size(752, 631);
            this.tlpDatiAggiuntivi.TabIndex = 1;
                                                appearance22.FontData.SizeInPoints = 20.1791F;
            appearance22.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance22.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance22.TextHAlignAsString = "Center";
            appearance22.TextVAlignAsString = "Middle";
            this.ubCopiaDati.Appearance = appearance22;
            this.ubCopiaDati.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.tlpDatiAggiuntivi.SetColumnSpan(this.ubCopiaDati, 2);
            this.ubCopiaDati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCopiaDati.Location = new System.Drawing.Point(3, 3);
            this.ubCopiaDati.Name = "ubCopiaDati";
            this.ubCopiaDati.PercImageFill = 0.75F;
            this.ubCopiaDati.ShortcutColor = System.Drawing.Color.Black;
            this.ubCopiaDati.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubCopiaDati.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubCopiaDati.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubCopiaDati.Size = new System.Drawing.Size(746, 44);
            this.ubCopiaDati.TabIndex = 16;
            this.ubCopiaDati.Text = "COPIA DATI ACCESSORI DA ORDINI PRECEDENTI";
            this.ubCopiaDati.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubCopiaDati.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubCopiaDati.Click += new System.EventHandler(this.ubCopiaDati_Click);
                                                this.tlpDatiAggiuntivi.SetColumnSpan(this.ehViewer, 2);
            this.ehViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ehViewer.Location = new System.Drawing.Point(0, 50);
            this.ehViewer.Margin = new System.Windows.Forms.Padding(0);
            this.ehViewer.Name = "ehViewer";
            this.ehViewer.Size = new System.Drawing.Size(752, 530);
            this.ehViewer.TabIndex = 15;
            this.ehViewer.Text = "elementHost1";
            this.ehViewer.Child = null;
                                                appearance23.FontData.SizeInPoints = 24.83582F;
            appearance23.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance23.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance23.TextHAlignAsString = "Center";
            appearance23.TextVAlignAsString = "Middle";
            this.ubInoltraOrdine.Appearance = appearance23;
            this.ubInoltraOrdine.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.tlpDatiAggiuntivi.SetColumnSpan(this.ubInoltraOrdine, 2);
            this.ubInoltraOrdine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubInoltraOrdine.Location = new System.Drawing.Point(3, 583);
            this.ubInoltraOrdine.Name = "ubInoltraOrdine";
            this.ubInoltraOrdine.PercImageFill = 0.75F;
            this.ubInoltraOrdine.ShortcutColor = System.Drawing.Color.Black;
            this.ubInoltraOrdine.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubInoltraOrdine.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubInoltraOrdine.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubInoltraOrdine.Size = new System.Drawing.Size(746, 45);
            this.ubInoltraOrdine.TabIndex = 14;
            this.ubInoltraOrdine.Text = "INOLTRA ORDINE";
            this.ubInoltraOrdine.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ubInoltraOrdine.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubInoltraOrdine.Click += new System.EventHandler(this.ubInoltraOrdine_Click);
                                                this.UltraPopupControlContainerSegnalibri.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerSegnalibri_Opening);
            this.UltraPopupControlContainerSegnalibri.Opened += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Opened);
            this.UltraPopupControlContainerSegnalibri.Closed += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1122, 716);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmPUOrdineDatiAggiuntivi";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUOrdiniDatiAggiuntivi";
            this.ImmagineClick += new UnicodeSrl.ScciCore.ImmagineTopClickHandler(this.frmPUOrdineDatiAggiuntivi_ImmagineClick);
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUOrdineDatiAggiuntivi_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUOrdineDatiAggiuntivi_PulsanteAvantiClick);
            this.Shown += new System.EventHandler(this.frmPUOrdineDatiAggiuntivi_Shown);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            this.TableLayoutPanelOrdine.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridPrestazioni)).EndInit();
            this.tlpDatiAggiuntivi.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyTableLayoutPanel TableLayoutPanelOrdine;
        private ucEasyGrid ucEasyGridPrestazioni;
        private ucEasyLabel lblPriorita;
        private ucEasyLabel lblDataOraProgrammazione;
        private ucEasyTableLayoutPanel tlpDatiAggiuntivi;
        private ucEasyButton ubInoltraOrdine;
        private ucEasyLabel lblStatoValidita;
        private ucEasyLabel lblDataOraProgrammazioneTitolo;
        private ucEasyLabel lblPrioritaTitolo;
        private ucEasyLabel ucEasyLabel1;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerSegnalibri;
        private System.Windows.Forms.Integration.ElementHost ehViewer;
        private ucEasyButton ubCopiaDati;
        private WpfControls40.ucDcViewer dcv;
    }
}