namespace UnicodeSrl.ScciCore
{
    partial class frmPUOrdineVisualizza
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedRight, new System.Guid("da3cf1ba-ee9e-40cc-921a-8b9307f20bb8"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("68a4770d-aae8-48c2-a428-86aec99aec42"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("da3cf1ba-ee9e-40cc-921a-8b9307f20bb8"), -1);
            this.pnlDatiErogante = new System.Windows.Forms.Panel();
            this.tlpDatiErogante = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyGridDatiErogante = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblTitoloNumeroOrdine = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblNumeroOrdine = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblTitoloDataOraProgrammazione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblDataOraProgrammazione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblTitoloUtenteInoltro = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblTitoloPriorita = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblStatoErogante = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblUtenteInoltro = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblPriorita = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblEroganti = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyGridDatiRichiedente = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyGridPrestazioni = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.lblTitoloStato = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblTitoloOrdine = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ultraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._frmBaseModaleUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._frmBaseModaleUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._frmBaseModaleUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._frmBaseModaleUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._frmBaseModaleAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.pnlDatiErogante.SuspendLayout();
            this.tlpDatiErogante.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridDatiErogante)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridDatiRichiedente)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridPrestazioni)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).BeginInit();
            this._frmBaseModaleAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(1042, 33);
                                                this.pnlDatiErogante.Controls.Add(this.tlpDatiErogante);
            this.pnlDatiErogante.Location = new System.Drawing.Point(0, 18);
            this.pnlDatiErogante.Name = "pnlDatiErogante";
            this.pnlDatiErogante.Size = new System.Drawing.Size(567, 765);
            this.pnlDatiErogante.TabIndex = 5;
                                                this.tlpDatiErogante.BackColor = System.Drawing.Color.Transparent;
            this.tlpDatiErogante.ColumnCount = 3;
            this.tlpDatiErogante.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.tlpDatiErogante.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.tlpDatiErogante.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.tlpDatiErogante.Controls.Add(this.ucEasyGridDatiErogante, 1, 1);
            this.tlpDatiErogante.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpDatiErogante.Location = new System.Drawing.Point(0, 0);
            this.tlpDatiErogante.Name = "tlpDatiErogante";
            this.tlpDatiErogante.RowCount = 3;
            this.tlpDatiErogante.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.tlpDatiErogante.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.tlpDatiErogante.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.tlpDatiErogante.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpDatiErogante.Size = new System.Drawing.Size(567, 765);
            this.tlpDatiErogante.TabIndex = 5;
                                                this.ucEasyGridDatiErogante.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridDatiErogante.ColonnaRTFResize = "";
            this.ucEasyGridDatiErogante.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDatiErogante.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridDatiErogante.DisplayLayout.Appearance = appearance1;
            this.ucEasyGridDatiErogante.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridDatiErogante.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance2.FontData.BoldAsString = "True";
            appearance2.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGridDatiErogante.DisplayLayout.CaptionAppearance = appearance2;
            this.ucEasyGridDatiErogante.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance3.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance3.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance3.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDatiErogante.DisplayLayout.GroupByBox.Appearance = appearance3;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridDatiErogante.DisplayLayout.GroupByBox.BandLabelAppearance = appearance4;
            this.ucEasyGridDatiErogante.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridDatiErogante.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridDatiErogante.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance5.BackColor2 = System.Drawing.SystemColors.Control;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridDatiErogante.DisplayLayout.GroupByBox.PromptAppearance = appearance5;
            this.ucEasyGridDatiErogante.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridDatiErogante.DisplayLayout.MaxRowScrollRegions = 1;
            appearance6.BackColor = System.Drawing.SystemColors.Window;
            appearance6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.ActiveCellAppearance = appearance6;
            appearance7.BackColor = System.Drawing.SystemColors.Highlight;
            appearance7.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.ActiveRowAppearance = appearance7;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.CardAreaAppearance = appearance8;
            appearance9.BorderColor = System.Drawing.Color.Silver;
            appearance9.FontData.SizeInPoints = 22.50746F;
            appearance9.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.CellAppearance = appearance9;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance10.FontData.SizeInPoints = 15.58209F;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.FilterRowAppearance = appearance10;
            appearance11.BackColor = System.Drawing.SystemColors.Control;
            appearance11.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance11.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance11.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance11.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.GroupByRowAppearance = appearance11;
            appearance12.FontData.BoldAsString = "True";
            appearance12.FontData.SizeInPoints = 22.50746F;
            appearance12.TextHAlignAsString = "Center";
            this.ucEasyGridDatiErogante.DisplayLayout.Override.HeaderAppearance = appearance12;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance13.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance13.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.RowAlternateAppearance = appearance13;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.RowAppearance = appearance14;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance15.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridDatiErogante.DisplayLayout.Override.TemplateAddRowAppearance = appearance15;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridDatiErogante.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridDatiErogante.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridDatiErogante.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridDatiErogante.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridDatiErogante.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridDatiErogante.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridDatiErogante.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridDatiErogante.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridDatiErogante.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDatiErogante.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDatiErogante.Location = new System.Drawing.Point(8, 10);
            this.ucEasyGridDatiErogante.Name = "ucEasyGridDatiErogante";
            this.ucEasyGridDatiErogante.ShowFilterRow = false;
            this.ucEasyGridDatiErogante.ShowGroupByBox = false;
            this.ucEasyGridDatiErogante.Size = new System.Drawing.Size(549, 743);
            this.ucEasyGridDatiErogante.TabIndex = 17;
            this.ucEasyGridDatiErogante.Text = "ucEasyGrid1";
            this.ucEasyGridDatiErogante.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridDatiErogante.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiErogante.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridDatiErogante_InitializeLayout);
            this.ucEasyGridDatiErogante.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGridDatiErogante_InitializeRow);
            this.ucEasyGridDatiErogante.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGridDatiErogante_ClickCellButton);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 33);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(1042, 717);
            this.ultraGroupBox.TabIndex = 3;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 5;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTitoloNumeroOrdine, 1, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblNumeroOrdine, 1, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTitoloDataOraProgrammazione, 3, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblDataOraProgrammazione, 3, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTitoloUtenteInoltro, 3, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTitoloPriorita, 1, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblStatoErogante, 3, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblUtenteInoltro, 3, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblPriorita, 1, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblEroganti, 1, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGridDatiRichiedente, 1, 8);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGridPrestazioni, 1, 7);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTitoloStato, 3, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTitoloOrdine, 1, 1);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 10;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 4F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 4F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 4F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 49F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 19F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(1036, 711);
            this.ucEasyTableLayoutPanel.TabIndex = 4;
                                                appearance16.FontData.SizeInPoints = 15.58209F;
            appearance16.TextVAlignAsString = "Bottom";
            this.lblTitoloNumeroOrdine.Appearance = appearance16;
            this.lblTitoloNumeroOrdine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitoloNumeroOrdine.Location = new System.Drawing.Point(13, 80);
            this.lblTitoloNumeroOrdine.Name = "lblTitoloNumeroOrdine";
            this.lblTitoloNumeroOrdine.ShortcutColor = System.Drawing.Color.Black;
            this.lblTitoloNumeroOrdine.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTitoloNumeroOrdine.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTitoloNumeroOrdine.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTitoloNumeroOrdine.Size = new System.Drawing.Size(491, 22);
            this.lblTitoloNumeroOrdine.TabIndex = 26;
            this.lblTitoloNumeroOrdine.Text = "Numero Ordine:";
            this.lblTitoloNumeroOrdine.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance17.FontData.SizeInPoints = 22.50746F;
            appearance17.TextVAlignAsString = "Middle";
            this.lblNumeroOrdine.Appearance = appearance17;
            this.lblNumeroOrdine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNumeroOrdine.Location = new System.Drawing.Point(13, 108);
            this.lblNumeroOrdine.Name = "lblNumeroOrdine";
            this.lblNumeroOrdine.ShortcutColor = System.Drawing.Color.Black;
            this.lblNumeroOrdine.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblNumeroOrdine.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblNumeroOrdine.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblNumeroOrdine.Size = new System.Drawing.Size(491, 36);
            this.lblNumeroOrdine.TabIndex = 25;
            this.lblNumeroOrdine.Text = "Numero Ordine";
            this.lblNumeroOrdine.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance18.FontData.SizeInPoints = 15.58209F;
            appearance18.TextVAlignAsString = "Bottom";
            this.lblTitoloDataOraProgrammazione.Appearance = appearance18;
            this.lblTitoloDataOraProgrammazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitoloDataOraProgrammazione.Location = new System.Drawing.Point(530, 80);
            this.lblTitoloDataOraProgrammazione.Name = "lblTitoloDataOraProgrammazione";
            this.lblTitoloDataOraProgrammazione.ShortcutColor = System.Drawing.Color.Black;
            this.lblTitoloDataOraProgrammazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTitoloDataOraProgrammazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTitoloDataOraProgrammazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTitoloDataOraProgrammazione.Size = new System.Drawing.Size(491, 22);
            this.lblTitoloDataOraProgrammazione.TabIndex = 24;
            this.lblTitoloDataOraProgrammazione.Text = "Data Programmazione:";
            this.lblTitoloDataOraProgrammazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance19.FontData.SizeInPoints = 22.50746F;
            appearance19.TextVAlignAsString = "Middle";
            this.lblDataOraProgrammazione.Appearance = appearance19;
            this.lblDataOraProgrammazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataOraProgrammazione.Location = new System.Drawing.Point(530, 108);
            this.lblDataOraProgrammazione.Name = "lblDataOraProgrammazione";
            this.lblDataOraProgrammazione.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataOraProgrammazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataOraProgrammazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataOraProgrammazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataOraProgrammazione.Size = new System.Drawing.Size(491, 36);
            this.lblDataOraProgrammazione.TabIndex = 23;
            this.lblDataOraProgrammazione.Text = "Data Ora Programmazione";
            this.lblDataOraProgrammazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance20.FontData.SizeInPoints = 15.58209F;
            appearance20.TextVAlignAsString = "Bottom";
            this.lblTitoloUtenteInoltro.Appearance = appearance20;
            this.lblTitoloUtenteInoltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitoloUtenteInoltro.Location = new System.Drawing.Point(530, 150);
            this.lblTitoloUtenteInoltro.Name = "lblTitoloUtenteInoltro";
            this.lblTitoloUtenteInoltro.ShortcutColor = System.Drawing.Color.Black;
            this.lblTitoloUtenteInoltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTitoloUtenteInoltro.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTitoloUtenteInoltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTitoloUtenteInoltro.Size = new System.Drawing.Size(491, 22);
            this.lblTitoloUtenteInoltro.TabIndex = 22;
            this.lblTitoloUtenteInoltro.Text = "Utente - Data Inoltro:";
            this.lblTitoloUtenteInoltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance21.FontData.SizeInPoints = 15.58209F;
            appearance21.TextVAlignAsString = "Bottom";
            this.lblTitoloPriorita.Appearance = appearance21;
            this.lblTitoloPriorita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitoloPriorita.Location = new System.Drawing.Point(13, 150);
            this.lblTitoloPriorita.Name = "lblTitoloPriorita";
            this.lblTitoloPriorita.ShortcutColor = System.Drawing.Color.Black;
            this.lblTitoloPriorita.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTitoloPriorita.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTitoloPriorita.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTitoloPriorita.Size = new System.Drawing.Size(491, 22);
            this.lblTitoloPriorita.TabIndex = 21;
            this.lblTitoloPriorita.Text = "Livello Urgenza:";
            this.lblTitoloPriorita.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance22.FontData.SizeInPoints = 22.50746F;
            appearance22.TextVAlignAsString = "Middle";
            this.lblStatoErogante.Appearance = appearance22;
            this.lblStatoErogante.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStatoErogante.Location = new System.Drawing.Point(530, 38);
            this.lblStatoErogante.Name = "lblStatoErogante";
            this.lblStatoErogante.ShortcutColor = System.Drawing.Color.Black;
            this.lblStatoErogante.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblStatoErogante.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblStatoErogante.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblStatoErogante.Size = new System.Drawing.Size(491, 36);
            this.lblStatoErogante.TabIndex = 20;
            this.lblStatoErogante.Text = "Stato Erogante";
            this.lblStatoErogante.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance23.FontData.SizeInPoints = 22.50746F;
            appearance23.TextVAlignAsString = "Middle";
            this.lblUtenteInoltro.Appearance = appearance23;
            this.lblUtenteInoltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUtenteInoltro.Location = new System.Drawing.Point(530, 178);
            this.lblUtenteInoltro.Name = "lblUtenteInoltro";
            this.lblUtenteInoltro.ShortcutColor = System.Drawing.Color.Black;
            this.lblUtenteInoltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblUtenteInoltro.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblUtenteInoltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblUtenteInoltro.Size = new System.Drawing.Size(491, 36);
            this.lblUtenteInoltro.TabIndex = 19;
            this.lblUtenteInoltro.Text = "Utente Inoltro - Data Ora Inoltro";
            this.lblUtenteInoltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance24.FontData.SizeInPoints = 22.50746F;
            appearance24.TextVAlignAsString = "Middle";
            this.lblPriorita.Appearance = appearance24;
            this.lblPriorita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPriorita.Location = new System.Drawing.Point(13, 178);
            this.lblPriorita.Name = "lblPriorita";
            this.lblPriorita.ShortcutColor = System.Drawing.Color.Black;
            this.lblPriorita.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPriorita.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPriorita.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPriorita.Size = new System.Drawing.Size(491, 36);
            this.lblPriorita.TabIndex = 18;
            this.lblPriorita.Text = "Priorità";
            this.lblPriorita.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance25.FontData.SizeInPoints = 22.50746F;
            appearance25.TextVAlignAsString = "Middle";
            this.lblEroganti.Appearance = appearance25;
            this.lblEroganti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEroganti.Location = new System.Drawing.Point(13, 38);
            this.lblEroganti.Name = "lblEroganti";
            this.lblEroganti.ShortcutColor = System.Drawing.Color.Black;
            this.lblEroganti.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblEroganti.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblEroganti.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblEroganti.Size = new System.Drawing.Size(491, 36);
            this.lblEroganti.TabIndex = 17;
            this.lblEroganti.Text = "Elenco Eroganti";
            this.lblEroganti.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucEasyGridDatiRichiedente.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridDatiRichiedente.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyGridDatiRichiedente, 3);
            this.ucEasyGridDatiRichiedente.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDatiRichiedente.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance26.BackColor = System.Drawing.SystemColors.Window;
            appearance26.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Appearance = appearance26;
            this.ucEasyGridDatiRichiedente.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridDatiRichiedente.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance27.FontData.BoldAsString = "True";
            appearance27.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGridDatiRichiedente.DisplayLayout.CaptionAppearance = appearance27;
            this.ucEasyGridDatiRichiedente.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance28.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance28.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance28.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance28.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDatiRichiedente.DisplayLayout.GroupByBox.Appearance = appearance28;
            appearance29.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridDatiRichiedente.DisplayLayout.GroupByBox.BandLabelAppearance = appearance29;
            this.ucEasyGridDatiRichiedente.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridDatiRichiedente.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridDatiRichiedente.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance30.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance30.BackColor2 = System.Drawing.SystemColors.Control;
            appearance30.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance30.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridDatiRichiedente.DisplayLayout.GroupByBox.PromptAppearance = appearance30;
            this.ucEasyGridDatiRichiedente.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridDatiRichiedente.DisplayLayout.MaxRowScrollRegions = 1;
            appearance31.BackColor = System.Drawing.SystemColors.Window;
            appearance31.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.ActiveCellAppearance = appearance31;
            appearance32.BackColor = System.Drawing.SystemColors.Highlight;
            appearance32.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.ActiveRowAppearance = appearance32;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance33.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.CardAreaAppearance = appearance33;
            appearance34.BorderColor = System.Drawing.Color.Silver;
            appearance34.FontData.SizeInPoints = 22.50746F;
            appearance34.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.CellAppearance = appearance34;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance35.FontData.SizeInPoints = 15.58209F;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.FilterRowAppearance = appearance35;
            appearance36.BackColor = System.Drawing.SystemColors.Control;
            appearance36.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance36.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance36.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance36.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.GroupByRowAppearance = appearance36;
            appearance37.FontData.BoldAsString = "True";
            appearance37.FontData.SizeInPoints = 22.50746F;
            appearance37.TextHAlignAsString = "Center";
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.HeaderAppearance = appearance37;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance38.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance38.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.RowAlternateAppearance = appearance38;
            appearance39.BackColor = System.Drawing.SystemColors.Window;
            appearance39.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.RowAppearance = appearance39;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance40.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridDatiRichiedente.DisplayLayout.Override.TemplateAddRowAppearance = appearance40;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridDatiRichiedente.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGridDatiRichiedente.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridDatiRichiedente.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridDatiRichiedente.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridDatiRichiedente.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridDatiRichiedente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridDatiRichiedente.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridDatiRichiedente.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridDatiRichiedente.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDatiRichiedente.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDatiRichiedente.Location = new System.Drawing.Point(13, 568);
            this.ucEasyGridDatiRichiedente.Name = "ucEasyGridDatiRichiedente";
            this.ucEasyGridDatiRichiedente.ShowFilterRow = false;
            this.ucEasyGridDatiRichiedente.ShowGroupByBox = false;
            this.ucEasyGridDatiRichiedente.Size = new System.Drawing.Size(1008, 129);
            this.ucEasyGridDatiRichiedente.TabIndex = 15;
            this.ucEasyGridDatiRichiedente.Text = "ucEasyGrid1";
            this.ucEasyGridDatiRichiedente.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridDatiRichiedente.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDatiRichiedente.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridDatiRichiedente_InitializeLayout);
                                                this.ucEasyGridPrestazioni.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridPrestazioni.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyGridPrestazioni, 3);
            this.ucEasyGridPrestazioni.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridPrestazioni.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance41.BackColor = System.Drawing.SystemColors.Window;
            appearance41.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridPrestazioni.DisplayLayout.Appearance = appearance41;
            this.ucEasyGridPrestazioni.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridPrestazioni.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance42.FontData.BoldAsString = "True";
            appearance42.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGridPrestazioni.DisplayLayout.CaptionAppearance = appearance42;
            this.ucEasyGridPrestazioni.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance43.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance43.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance43.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance43.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.Appearance = appearance43;
            appearance44.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.BandLabelAppearance = appearance44;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance45.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance45.BackColor2 = System.Drawing.SystemColors.Control;
            appearance45.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance45.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridPrestazioni.DisplayLayout.GroupByBox.PromptAppearance = appearance45;
            this.ucEasyGridPrestazioni.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridPrestazioni.DisplayLayout.MaxRowScrollRegions = 1;
            appearance46.BackColor = System.Drawing.SystemColors.Window;
            appearance46.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.ActiveCellAppearance = appearance46;
            appearance47.BackColor = System.Drawing.SystemColors.Highlight;
            appearance47.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.ActiveRowAppearance = appearance47;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance48.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.CardAreaAppearance = appearance48;
            appearance49.BorderColor = System.Drawing.Color.Silver;
            appearance49.FontData.SizeInPoints = 22.50746F;
            appearance49.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.CellAppearance = appearance49;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance50.FontData.SizeInPoints = 15.58209F;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.FilterRowAppearance = appearance50;
            appearance51.BackColor = System.Drawing.SystemColors.Control;
            appearance51.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance51.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance51.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance51.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.GroupByRowAppearance = appearance51;
            appearance52.FontData.BoldAsString = "True";
            appearance52.FontData.SizeInPoints = 22.50746F;
            appearance52.TextHAlignAsString = "Center";
            this.ucEasyGridPrestazioni.DisplayLayout.Override.HeaderAppearance = appearance52;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance53.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance53.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.RowAlternateAppearance = appearance53;
            appearance54.BackColor = System.Drawing.SystemColors.Window;
            appearance54.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.RowAppearance = appearance54;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance55.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridPrestazioni.DisplayLayout.Override.TemplateAddRowAppearance = appearance55;
            scrollBarLook3.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridPrestazioni.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.ucEasyGridPrestazioni.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridPrestazioni.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridPrestazioni.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridPrestazioni.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridPrestazioni.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridPrestazioni.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridPrestazioni.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridPrestazioni.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridPrestazioni.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridPrestazioni.Location = new System.Drawing.Point(13, 220);
            this.ucEasyGridPrestazioni.Name = "ucEasyGridPrestazioni";
            this.ucEasyGridPrestazioni.ShowFilterRow = false;
            this.ucEasyGridPrestazioni.ShowGroupByBox = false;
            this.ucEasyGridPrestazioni.Size = new System.Drawing.Size(1008, 342);
            this.ucEasyGridPrestazioni.TabIndex = 14;
            this.ucEasyGridPrestazioni.Text = "ucEasyGrid1";
            this.ucEasyGridPrestazioni.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridPrestazioni.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridPrestazioni.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridPrestazioni_InitializeLayout);
                                                appearance56.FontData.SizeInPoints = 15.58209F;
            appearance56.TextVAlignAsString = "Bottom";
            this.lblTitoloStato.Appearance = appearance56;
            this.lblTitoloStato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitoloStato.Location = new System.Drawing.Point(530, 10);
            this.lblTitoloStato.Name = "lblTitoloStato";
            this.lblTitoloStato.ShortcutColor = System.Drawing.Color.Black;
            this.lblTitoloStato.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTitoloStato.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTitoloStato.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTitoloStato.Size = new System.Drawing.Size(491, 22);
            this.lblTitoloStato.TabIndex = 13;
            this.lblTitoloStato.Text = "Stato:";
            this.lblTitoloStato.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance57.FontData.SizeInPoints = 15.58209F;
            appearance57.TextVAlignAsString = "Bottom";
            this.lblTitoloOrdine.Appearance = appearance57;
            this.lblTitoloOrdine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitoloOrdine.Location = new System.Drawing.Point(13, 10);
            this.lblTitoloOrdine.Name = "lblTitoloOrdine";
            this.lblTitoloOrdine.ShortcutColor = System.Drawing.Color.Black;
            this.lblTitoloOrdine.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTitoloOrdine.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTitoloOrdine.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTitoloOrdine.Size = new System.Drawing.Size(491, 22);
            this.lblTitoloOrdine.TabIndex = 12;
            this.lblTitoloOrdine.Text = "Ordine:";
            this.lblTitoloOrdine.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                this.ultraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.ultraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.ultraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.ultraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockAreaPane1.ChildPaneStyle = Infragistics.Win.UltraWinDock.ChildPaneStyle.VerticalSplit;
            dockableControlPane1.Control = this.pnlDatiErogante;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(567, -1);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(421, 239, 554, 426);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "DATI EROGANTE";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(586, 783);
            this.ultraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.ultraDockManager.HostControl = this;
            this.ultraDockManager.ShowCloseButton = false;
            this.ultraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.ultraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.ultraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.ultraDockManager_InitializePane);
                                                this._frmBaseModaleUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._frmBaseModaleUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._frmBaseModaleUnpinnedTabAreaLeft.Name = "_frmBaseModaleUnpinnedTabAreaLeft";
            this._frmBaseModaleUnpinnedTabAreaLeft.Owner = this.ultraDockManager;
            this._frmBaseModaleUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 783);
            this._frmBaseModaleUnpinnedTabAreaLeft.TabIndex = 6;
                                                this._frmBaseModaleUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._frmBaseModaleUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleUnpinnedTabAreaRight.Location = new System.Drawing.Point(1042, 0);
            this._frmBaseModaleUnpinnedTabAreaRight.Name = "_frmBaseModaleUnpinnedTabAreaRight";
            this._frmBaseModaleUnpinnedTabAreaRight.Owner = this.ultraDockManager;
            this._frmBaseModaleUnpinnedTabAreaRight.Size = new System.Drawing.Size(23, 783);
            this._frmBaseModaleUnpinnedTabAreaRight.TabIndex = 7;
                                                this._frmBaseModaleUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._frmBaseModaleUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._frmBaseModaleUnpinnedTabAreaTop.Name = "_frmBaseModaleUnpinnedTabAreaTop";
            this._frmBaseModaleUnpinnedTabAreaTop.Owner = this.ultraDockManager;
            this._frmBaseModaleUnpinnedTabAreaTop.Size = new System.Drawing.Size(1042, 0);
            this._frmBaseModaleUnpinnedTabAreaTop.TabIndex = 8;
                                                this._frmBaseModaleUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._frmBaseModaleUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 783);
            this._frmBaseModaleUnpinnedTabAreaBottom.Name = "_frmBaseModaleUnpinnedTabAreaBottom";
            this._frmBaseModaleUnpinnedTabAreaBottom.Owner = this.ultraDockManager;
            this._frmBaseModaleUnpinnedTabAreaBottom.Size = new System.Drawing.Size(1042, 0);
            this._frmBaseModaleUnpinnedTabAreaBottom.TabIndex = 9;
                                                this._frmBaseModaleAutoHideControl.Controls.Add(this.dockableWindow1);
            this._frmBaseModaleAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleAutoHideControl.Location = new System.Drawing.Point(990, 0);
            this._frmBaseModaleAutoHideControl.Name = "_frmBaseModaleAutoHideControl";
            this._frmBaseModaleAutoHideControl.Owner = this.ultraDockManager;
            this._frmBaseModaleAutoHideControl.Size = new System.Drawing.Size(52, 783);
            this._frmBaseModaleAutoHideControl.TabIndex = 10;
                                                this.dockableWindow1.Controls.Add(this.pnlDatiErogante);
            this.dockableWindow1.Location = new System.Drawing.Point(-10000, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.ultraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(567, 783);
            this.dockableWindow1.TabIndex = 12;
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Right;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(451, 0);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.ultraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(591, 783);
            this.windowDockingArea1.TabIndex = 11;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1065, 783);
            this.Controls.Add(this._frmBaseModaleAutoHideControl);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._frmBaseModaleUnpinnedTabAreaTop);
            this.Controls.Add(this._frmBaseModaleUnpinnedTabAreaBottom);
            this.Controls.Add(this._frmBaseModaleUnpinnedTabAreaLeft);
            this.Controls.Add(this._frmBaseModaleUnpinnedTabAreaRight);
            this.Name = "frmPUOrdineVisualizza";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUOrdineVisualizza";
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUOrdineVisualizza_PulsanteAvantiClick);
            this.Shown += new System.EventHandler(this.frmPUOrdineVisualizza_Shown);
            this.Controls.SetChildIndex(this._frmBaseModaleUnpinnedTabAreaRight, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleUnpinnedTabAreaLeft, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleUnpinnedTabAreaBottom, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleUnpinnedTabAreaTop, 0);
            this.Controls.SetChildIndex(this.windowDockingArea1, 0);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleAutoHideControl, 0);
            this.pnlDatiErogante.ResumeLayout(false);
            this.tlpDatiErogante.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridDatiErogante)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridDatiRichiedente)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridPrestazioni)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).EndInit();
            this._frmBaseModaleAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyLabel lblStatoErogante;
        private ucEasyLabel lblUtenteInoltro;
        private ucEasyLabel lblPriorita;
        private ucEasyLabel lblEroganti;
        private ucEasyGrid ucEasyGridDatiRichiedente;
        private ucEasyGrid ucEasyGridPrestazioni;
        private ucEasyLabel lblTitoloStato;
        private ucEasyLabel lblTitoloOrdine;
        private System.Windows.Forms.Panel pnlDatiErogante;
        private ucEasyTableLayoutPanel tlpDatiErogante;
        private ucEasyGrid ucEasyGridDatiErogante;
        private Infragistics.Win.UltraWinDock.UltraDockManager ultraDockManager;
        private Infragistics.Win.UltraWinDock.AutoHideControl _frmBaseModaleAutoHideControl;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _frmBaseModaleUnpinnedTabAreaLeft;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _frmBaseModaleUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _frmBaseModaleUnpinnedTabAreaBottom;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _frmBaseModaleUnpinnedTabAreaRight;
        private ucEasyLabel lblTitoloPriorita;
        private ucEasyLabel lblTitoloUtenteInoltro;
        private ucEasyLabel lblDataOraProgrammazione;
        private ucEasyLabel lblTitoloDataOraProgrammazione;
        private ucEasyLabel lblNumeroOrdine;
        private ucEasyLabel lblTitoloNumeroOrdine;

    }
}