namespace UnicodeSrl.ScciCore
{
    partial class frmPUTaskInfermieristiciEroga
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblPosologiaEffettiva = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.txtPosologiaEffettiva = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ucEasyTableLayoutPanelDC = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ehViewer = new System.Windows.Forms.Integration.ElementHost();
            this.ucDcViewer = new UnicodeSrl.WpfControls40.ucDcViewer();
            this.ucAnteprimaRtf = new UnicodeSrl.ScciCore.ucAnteprimaRtf();
            this.udteDataErogazione = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblDataErogazione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblNote = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.pbIconaTask = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.lblDataProgrammataInizio = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblTipoTaskInfermieristico = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.txtNote = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.pbObbligatorio = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this.ucEasyTableLayoutPanelBottom = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtPosologiaEffettiva)).BeginInit();
            this.ucEasyTableLayoutPanelDC.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataErogazione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbIconaTask)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNote)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbObbligatorio)).BeginInit();
            this.ucEasyTableLayoutPanelBottom.SuspendLayout();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(784, 24);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 24);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(784, 514);
            this.ultraGroupBox.TabIndex = 9;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 9;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 29F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelDC, 1, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.pbIconaTask, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblDataProgrammataInizio, 1, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTipoTaskInfermieristico, 2, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelBottom, 1, 4);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 6;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 47F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 39F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(778, 508);
            this.ucEasyTableLayoutPanel.TabIndex = 10;
                                                appearance12.FontData.SizeInPoints = 27.9403F;
            this.lblPosologiaEffettiva.Appearance = appearance12;
            this.lblPosologiaEffettiva.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPosologiaEffettiva.Location = new System.Drawing.Point(409, 3);
            this.lblPosologiaEffettiva.Name = "lblPosologiaEffettiva";
            this.ucEasyTableLayoutPanelBottom.SetRowSpan(this.lblPosologiaEffettiva, 2);
            this.lblPosologiaEffettiva.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPosologiaEffettiva.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPosologiaEffettiva.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPosologiaEffettiva.Size = new System.Drawing.Size(107, 72);
            this.lblPosologiaEffettiva.TabIndex = 20;
            this.lblPosologiaEffettiva.Text = "Posologia Effettiva";
            this.lblPosologiaEffettiva.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.lblPosologiaEffettiva.Visible = false;
                                                appearance3.FontData.SizeInPoints = 22.70149F;
            this.txtPosologiaEffettiva.Appearance = appearance3;
            this.txtPosologiaEffettiva.AutoSize = false;
            this.txtPosologiaEffettiva.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtPosologiaEffettiva.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtPosologiaEffettiva.Enabled = false;
            this.txtPosologiaEffettiva.Location = new System.Drawing.Point(522, 3);
            this.txtPosologiaEffettiva.Multiline = true;
            this.txtPosologiaEffettiva.Name = "txtPosologiaEffettiva";
            this.ucEasyTableLayoutPanelBottom.SetRowSpan(this.txtPosologiaEffettiva, 2);
            this.txtPosologiaEffettiva.Size = new System.Drawing.Size(191, 72);
            this.txtPosologiaEffettiva.TabIndex = 8;
            this.txtPosologiaEffettiva.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.txtPosologiaEffettiva.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.txtPosologiaEffettiva.Visible = false;
                                                this.ucEasyTableLayoutPanelDC.ColumnCount = 2;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelDC, 8);
            this.ucEasyTableLayoutPanelDC.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ucEasyTableLayoutPanelDC.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ucEasyTableLayoutPanelDC.Controls.Add(this.ehViewer, 1, 0);
            this.ucEasyTableLayoutPanelDC.Controls.Add(this.ucAnteprimaRtf, 0, 0);
            this.ucEasyTableLayoutPanelDC.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelDC.Location = new System.Drawing.Point(10, 68);
            this.ucEasyTableLayoutPanelDC.Name = "ucEasyTableLayoutPanelDC";
            this.ucEasyTableLayoutPanelDC.RowCount = 1;
            this.ucEasyTableLayoutPanelDC.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelDC.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 232F));
            this.ucEasyTableLayoutPanelDC.Size = new System.Drawing.Size(765, 232);
            this.ucEasyTableLayoutPanelDC.TabIndex = 18;
                                                this.ehViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ehViewer.Location = new System.Drawing.Point(385, 3);
            this.ehViewer.Name = "ehViewer";
            this.ehViewer.Size = new System.Drawing.Size(377, 226);
            this.ehViewer.TabIndex = 14;
            this.ehViewer.Text = "elementHost1";
            this.ehViewer.Child = this.ucDcViewer;
                                                this.ucAnteprimaRtf.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucAnteprimaRtf.Location = new System.Drawing.Point(3, 3);
            this.ucAnteprimaRtf.MovScheda = null;
            this.ucAnteprimaRtf.Name = "ucAnteprimaRtf";
            this.ucAnteprimaRtf.Size = new System.Drawing.Size(376, 226);
            this.ucAnteprimaRtf.TabIndex = 0;
                                                appearance13.FontData.SizeInPoints = 27.9403F;
            appearance13.TextHAlignAsString = "Center";
            this.udteDataErogazione.Appearance = appearance13;
            this.udteDataErogazione.AutoSize = false;
            this.udteDataErogazione.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteDataErogazione.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataErogazione.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance14.FontData.SizeInPoints = 27.9403F;
            this.udteDataErogazione.DropDownAppearance = appearance14;
            this.udteDataErogazione.FormatString = "dd/MM/yyyy HH:mm";
            this.udteDataErogazione.Location = new System.Drawing.Point(168, 3);
            this.udteDataErogazione.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteDataErogazione.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteDataErogazione.Name = "udteDataErogazione";
            this.udteDataErogazione.Size = new System.Drawing.Size(213, 33);
            this.udteDataErogazione.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataErogazione.TabIndex = 7;
            this.udteDataErogazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.udteDataErogazione.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance15.FontData.SizeInPoints = 27.9403F;
            appearance15.TextVAlignAsString = "Middle";
            this.lblDataErogazione.Appearance = appearance15;
            this.ucEasyTableLayoutPanelBottom.SetColumnSpan(this.lblDataErogazione, 2);
            this.lblDataErogazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataErogazione.Location = new System.Drawing.Point(3, 3);
            this.lblDataErogazione.Name = "lblDataErogazione";
            this.lblDataErogazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataErogazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataErogazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataErogazione.Size = new System.Drawing.Size(159, 33);
            this.lblDataErogazione.TabIndex = 6;
            this.lblDataErogazione.Text = "Erogato il:";
            this.lblDataErogazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance16.FontData.SizeInPoints = 27.9403F;
            appearance16.TextVAlignAsString = "Middle";
            this.lblNote.Appearance = appearance16;
            this.ucEasyTableLayoutPanelBottom.SetColumnSpan(this.lblNote, 3);
            this.lblNote.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNote.Location = new System.Drawing.Point(3, 42);
            this.lblNote.Name = "lblNote";
            this.lblNote.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblNote.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblNote.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblNote.Size = new System.Drawing.Size(378, 33);
            this.lblNote.TabIndex = 5;
            this.lblNote.Text = "Note Erogazione:";
            this.lblNote.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                this.pbIconaTask.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pbIconaTask.Location = new System.Drawing.Point(10, 8);
            this.pbIconaTask.Name = "pbIconaTask";
            this.pbIconaTask.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbIconaTask.ShortcutKey = System.Windows.Forms.Keys.None;
            this.pbIconaTask.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbIconaTask.Size = new System.Drawing.Size(71, 24);
            this.pbIconaTask.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbIconaTask.TabIndex = 4;
            this.pbIconaTask.TabStop = false;
                                                appearance10.FontData.SizeInPoints = 27.9403F;
            appearance10.TextVAlignAsString = "Middle";
            this.lblDataProgrammataInizio.Appearance = appearance10;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblDataProgrammataInizio, 6);
            this.lblDataProgrammataInizio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataProgrammataInizio.Location = new System.Drawing.Point(10, 38);
            this.lblDataProgrammataInizio.Name = "lblDataProgrammataInizio";
            this.lblDataProgrammataInizio.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataProgrammataInizio.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataProgrammataInizio.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataProgrammataInizio.Size = new System.Drawing.Size(714, 24);
            this.lblDataProgrammataInizio.TabIndex = 3;
            this.lblDataProgrammataInizio.Text = "Pianificato per: XX/XX/XXXX HH:HH";
            this.lblDataProgrammataInizio.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance11.FontData.SizeInPoints = 27.9403F;
            appearance11.TextVAlignAsString = "Middle";
            this.lblTipoTaskInfermieristico.Appearance = appearance11;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblTipoTaskInfermieristico, 5);
            this.lblTipoTaskInfermieristico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTipoTaskInfermieristico.Location = new System.Drawing.Point(87, 8);
            this.lblTipoTaskInfermieristico.Name = "lblTipoTaskInfermieristico";
            this.lblTipoTaskInfermieristico.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTipoTaskInfermieristico.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTipoTaskInfermieristico.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTipoTaskInfermieristico.Size = new System.Drawing.Size(637, 24);
            this.lblTipoTaskInfermieristico.TabIndex = 2;
            this.lblTipoTaskInfermieristico.Text = "Tipo Task Infermieristico";
            this.lblTipoTaskInfermieristico.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance8.FontData.SizeInPoints = 22.70149F;
            this.txtNote.Appearance = appearance8;
            this.txtNote.AutoSize = false;
            this.ucEasyTableLayoutPanelBottom.SetColumnSpan(this.txtNote, 6);
            this.txtNote.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtNote.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtNote.Location = new System.Drawing.Point(3, 81);
            this.txtNote.Multiline = true;
            this.txtNote.Name = "txtNote";
            this.txtNote.Size = new System.Drawing.Size(710, 114);
            this.txtNote.TabIndex = 9;
            this.txtNote.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.txtNote.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                this.pbObbligatorio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pbObbligatorio.Location = new System.Drawing.Point(719, 3);
            this.pbObbligatorio.Name = "pbObbligatorio";
            this.pbObbligatorio.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbObbligatorio.ShortcutKey = System.Windows.Forms.Keys.None;
            this.pbObbligatorio.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbObbligatorio.Size = new System.Drawing.Size(36, 33);
            this.pbObbligatorio.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbObbligatorio.TabIndex = 21;
            this.pbObbligatorio.TabStop = false;
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this.ucEasyTableLayoutPanelBottom.ColumnCount = 7;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelBottom, 7);
            this.ucEasyTableLayoutPanelBottom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelBottom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanelBottom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 29F));
            this.ucEasyTableLayoutPanelBottom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.ucEasyTableLayoutPanelBottom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelBottom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 26F));
            this.ucEasyTableLayoutPanelBottom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelBottom.Controls.Add(this.txtPosologiaEffettiva, 5, 0);
            this.ucEasyTableLayoutPanelBottom.Controls.Add(this.lblPosologiaEffettiva, 4, 0);
            this.ucEasyTableLayoutPanelBottom.Controls.Add(this.udteDataErogazione, 2, 0);
            this.ucEasyTableLayoutPanelBottom.Controls.Add(this.lblDataErogazione, 0, 0);
            this.ucEasyTableLayoutPanelBottom.Controls.Add(this.txtNote, 0, 2);
            this.ucEasyTableLayoutPanelBottom.Controls.Add(this.pbObbligatorio, 6, 0);
            this.ucEasyTableLayoutPanelBottom.Controls.Add(this.lblNote, 0, 1);
            this.ucEasyTableLayoutPanelBottom.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelBottom.Location = new System.Drawing.Point(7, 303);
            this.ucEasyTableLayoutPanelBottom.Margin = new System.Windows.Forms.Padding(0);
            this.ucEasyTableLayoutPanelBottom.Name = "ucEasyTableLayoutPanelBottom";
            this.ucEasyTableLayoutPanelBottom.RowCount = 3;
            this.ucEasyTableLayoutPanelBottom.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelBottom.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelBottom.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanelBottom.Size = new System.Drawing.Size(758, 198);
            this.ucEasyTableLayoutPanelBottom.TabIndex = 22;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmPUTaskInfermieristiciEroga";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUTaskInfermieristiciEroga";
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUTaskInfermieristiciEroga_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUTaskInfermieristiciEroga_PulsanteAvantiClick);
            this.Shown += new System.EventHandler(this.frmPUTaskInfermieristiciEroga_Shown);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txtPosologiaEffettiva)).EndInit();
            this.ucEasyTableLayoutPanelDC.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteDataErogazione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbIconaTask)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNote)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbObbligatorio)).EndInit();
            this.ucEasyTableLayoutPanelBottom.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyLabel lblDataProgrammataInizio;
        private ucEasyLabel lblTipoTaskInfermieristico;
        private ucEasyPictureBox pbIconaTask;
        private ucEasyLabel lblDataErogazione;
        private ucEasyLabel lblNote;
        private ucEasyDateTimeEditor udteDataErogazione;
        private ucEasyTextBox txtNote;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelDC;
        private System.Windows.Forms.Integration.ElementHost ehViewer;
        private WpfControls40.ucDcViewer ucDcViewer;
        private ucAnteprimaRtf ucAnteprimaRtf;
        private ucEasyTextBox txtPosologiaEffettiva;
        private ucEasyLabel lblPosologiaEffettiva;
        private ucEasyPictureBox pbObbligatorio;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelBottom;

    }
}