namespace UnicodeSrl.ScciCore
{
    partial class frmPUConsegnePazienteCartella
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ehViewer = new System.Windows.Forms.Integration.ElementHost();
            this.ucDcViewer = new UnicodeSrl.WpfControls40.ucDcViewer();
            this.ucEasyTableLayoutPanelRuoli = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ugRuoli = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPanelRuoliAzioni = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubAnnulla = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubNuovo = new UnicodeSrl.ScciCore.ucEasyButton();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            this.ucEasyTableLayoutPanelRuoli.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugRuoli)).BeginInit();
            this.ucEasyTableLayoutPanelRuoliAzioni.SuspendLayout();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(784, 24);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 24);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(784, 514);
            this.ultraGroupBox.TabIndex = 9;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 3;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 96F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ehViewer, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelRuoli, 1, 3);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 5;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 64F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(778, 508);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.ehViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ehViewer.Location = new System.Drawing.Point(18, 13);
            this.ehViewer.Name = "ehViewer";
            this.ehViewer.Size = new System.Drawing.Size(740, 319);
            this.ehViewer.TabIndex = 6;
            this.ehViewer.Text = "elementHost1";
            this.ehViewer.Child = this.ucDcViewer;
                                                this.ucEasyTableLayoutPanelRuoli.ColumnCount = 2;
            this.ucEasyTableLayoutPanelRuoli.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 85F));
            this.ucEasyTableLayoutPanelRuoli.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelRuoli.Controls.Add(this.ugRuoli, 0, 0);
            this.ucEasyTableLayoutPanelRuoli.Controls.Add(this.ucEasyTableLayoutPanelRuoliAzioni, 1, 0);
            this.ucEasyTableLayoutPanelRuoli.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelRuoli.Location = new System.Drawing.Point(18, 348);
            this.ucEasyTableLayoutPanelRuoli.Name = "ucEasyTableLayoutPanelRuoli";
            this.ucEasyTableLayoutPanelRuoli.RowCount = 1;
            this.ucEasyTableLayoutPanelRuoli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelRuoli.Size = new System.Drawing.Size(740, 146);
            this.ucEasyTableLayoutPanelRuoli.TabIndex = 7;
                                                this.ugRuoli.ColonnaRTFControlloContenuto = false;
            this.ugRuoli.ColonnaRTFResize = "";
            this.ugRuoli.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ugRuoli.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugRuoli.DisplayLayout.Appearance = appearance1;
            this.ugRuoli.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ugRuoli.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance2.FontData.SizeInPoints = 19.59702F;
            this.ugRuoli.DisplayLayout.CaptionAppearance = appearance2;
            this.ugRuoli.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance3.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance3.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance3.BorderColor = System.Drawing.SystemColors.Window;
            this.ugRuoli.DisplayLayout.GroupByBox.Appearance = appearance3;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugRuoli.DisplayLayout.GroupByBox.BandLabelAppearance = appearance4;
            this.ugRuoli.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugRuoli.DisplayLayout.GroupByBox.Hidden = true;
            this.ugRuoli.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance5.BackColor2 = System.Drawing.SystemColors.Control;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugRuoli.DisplayLayout.GroupByBox.PromptAppearance = appearance5;
            this.ugRuoli.DisplayLayout.MaxColScrollRegions = 1;
            this.ugRuoli.DisplayLayout.MaxRowScrollRegions = 1;
            appearance6.BackColor = System.Drawing.SystemColors.Window;
            appearance6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugRuoli.DisplayLayout.Override.ActiveCellAppearance = appearance6;
            appearance7.BackColor = System.Drawing.SystemColors.Highlight;
            appearance7.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugRuoli.DisplayLayout.Override.ActiveRowAppearance = appearance7;
            this.ugRuoli.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ugRuoli.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ugRuoli.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ugRuoli.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ugRuoli.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ugRuoli.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugRuoli.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            this.ugRuoli.DisplayLayout.Override.CardAreaAppearance = appearance8;
            appearance9.BorderColor = System.Drawing.Color.Silver;
            appearance9.FontData.SizeInPoints = 19.59702F;
            appearance9.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugRuoli.DisplayLayout.Override.CellAppearance = appearance9;
            this.ugRuoli.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ugRuoli.DisplayLayout.Override.CellPadding = 0;
            this.ugRuoli.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance10.FontData.SizeInPoints = 19.59702F;
            this.ugRuoli.DisplayLayout.Override.FilterRowAppearance = appearance10;
            appearance11.BackColor = System.Drawing.SystemColors.Control;
            appearance11.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance11.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance11.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance11.BorderColor = System.Drawing.SystemColors.Window;
            this.ugRuoli.DisplayLayout.Override.GroupByRowAppearance = appearance11;
            appearance12.FontData.BoldAsString = "True";
            appearance12.FontData.SizeInPoints = 19.59702F;
            appearance12.TextHAlignAsString = "Center";
            this.ugRuoli.DisplayLayout.Override.HeaderAppearance = appearance12;
            this.ugRuoli.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ugRuoli.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance13.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance13.ForeColor = System.Drawing.Color.DarkBlue;
            this.ugRuoli.DisplayLayout.Override.RowAlternateAppearance = appearance13;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            this.ugRuoli.DisplayLayout.Override.RowAppearance = appearance14;
            this.ugRuoli.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ugRuoli.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ugRuoli.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ugRuoli.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance15.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugRuoli.DisplayLayout.Override.TemplateAddRowAppearance = appearance15;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ugRuoli.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ugRuoli.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugRuoli.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugRuoli.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ugRuoli.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugRuoli.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ugRuoli.FattoreRidimensionamentoRTF = 21;
            this.ugRuoli.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ugRuoli.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ugRuoli.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ugRuoli.Location = new System.Drawing.Point(3, 3);
            this.ugRuoli.Name = "ugRuoli";
            this.ugRuoli.ShowFilterRow = false;
            this.ugRuoli.ShowGroupByBox = false;
            this.ugRuoli.Size = new System.Drawing.Size(623, 140);
            this.ugRuoli.TabIndex = 0;
            this.ugRuoli.Text = "Ruoli";
            this.ugRuoli.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ugRuoli.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ugRuoli.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugRuoli_InitializeLayout);
            this.ugRuoli.AfterRowActivate += new System.EventHandler(this.ugRuoli_AfterRowActivate);
                                                this.ucEasyTableLayoutPanelRuoliAzioni.ColumnCount = 1;
            this.ucEasyTableLayoutPanelRuoliAzioni.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelRuoliAzioni.Controls.Add(this.ubAnnulla, 0, 2);
            this.ucEasyTableLayoutPanelRuoliAzioni.Controls.Add(this.ubNuovo, 0, 0);
            this.ucEasyTableLayoutPanelRuoliAzioni.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelRuoliAzioni.Location = new System.Drawing.Point(632, 3);
            this.ucEasyTableLayoutPanelRuoliAzioni.Name = "ucEasyTableLayoutPanelRuoliAzioni";
            this.ucEasyTableLayoutPanelRuoliAzioni.RowCount = 3;
            this.ucEasyTableLayoutPanelRuoliAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.ucEasyTableLayoutPanelRuoliAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.ucEasyTableLayoutPanelRuoliAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.ucEasyTableLayoutPanelRuoliAzioni.Size = new System.Drawing.Size(105, 140);
            this.ucEasyTableLayoutPanelRuoliAzioni.TabIndex = 1;
                                                appearance16.FontData.SizeInPoints = 19.59702F;
            appearance16.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance16.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance16.TextHAlignAsString = "Center";
            appearance16.TextVAlignAsString = "Middle";
            this.ubAnnulla.Appearance = appearance16;
            this.ubAnnulla.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAnnulla.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAnnulla.Location = new System.Drawing.Point(3, 95);
            this.ubAnnulla.Name = "ubAnnulla";
            this.ubAnnulla.PercImageFill = 0.75F;
            this.ubAnnulla.ShortcutColor = System.Drawing.Color.Black;
            this.ubAnnulla.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAnnulla.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAnnulla.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAnnulla.Size = new System.Drawing.Size(99, 42);
            this.ubAnnulla.TabIndex = 22;
            this.ubAnnulla.Text = "Annulla";
            this.ubAnnulla.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubAnnulla.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAnnulla.Click += new System.EventHandler(this.ubAnnulla_Click);
                                                appearance17.FontData.SizeInPoints = 19.59702F;
            appearance17.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance17.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance17.TextHAlignAsString = "Center";
            appearance17.TextVAlignAsString = "Middle";
            this.ubNuovo.Appearance = appearance17;
            this.ubNuovo.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubNuovo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubNuovo.Location = new System.Drawing.Point(3, 3);
            this.ubNuovo.Name = "ubNuovo";
            this.ubNuovo.PercImageFill = 0.75F;
            this.ubNuovo.ShortcutColor = System.Drawing.Color.Black;
            this.ubNuovo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubNuovo.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubNuovo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubNuovo.Size = new System.Drawing.Size(99, 40);
            this.ubNuovo.TabIndex = 21;
            this.ubNuovo.Text = "Nuovo";
            this.ubNuovo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubNuovo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubNuovo.Click += new System.EventHandler(this.ubNuovo_Click);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmPUConsegnePazienteCartella";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUConsegnePazienteCartella";
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUConsegnePazienteCartella_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUConsegnePazienteCartella_PulsanteAvantiClick);
            this.Shown += new System.EventHandler(this.frmPUConsegnePazienteCartella_Shown);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            this.ucEasyTableLayoutPanelRuoli.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ugRuoli)).EndInit();
            this.ucEasyTableLayoutPanelRuoliAzioni.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private System.Windows.Forms.Integration.ElementHost ehViewer;
        private UnicodeSrl.WpfControls40.ucDcViewer ucDcViewer;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelRuoli;
        private ucEasyGrid ugRuoli;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelRuoliAzioni;
        private ucEasyButton ubNuovo;
        private ucEasyButton ubAnnulla;
    }
}