namespace UnicodeSrl.ScciCore
{
    partial class frmPUPrescrizioni
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPUPrescrizioni));
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedRight, new System.Guid("013be4c4-28a8-45ef-91bb-92ee19f3eaa8"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("ade6d105-421a-41c7-a7f3-d678b402f373"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("013be4c4-28a8-45ef-91bb-92ee19f3eaa8"), -1);
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinToolbars.PopupMenuTool popupMenuTool1 = new Infragistics.Win.UltraWinToolbars.PopupMenuTool("PopupMenuTool");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool6 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_EDIT");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool7 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_VALID");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool8 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_SOSPENDI");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool9 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_DEL");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool10 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_COPY");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool1 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_EDIT");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool2 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_VALID");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool3 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_SOSPENDI");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool4 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_DEL");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool5 = new Infragistics.Win.UltraWinToolbars.ButtonTool("BTN_COPY");
            this.pnlFiltro = new System.Windows.Forms.Panel();
            this.ucEasyTableLayoutPanelFiltri = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubApplicaFiltro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyGridFiltroStato = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucAnteprimaRtf = new UnicodeSrl.ScciCore.ucAnteprimaRtf();
            this.ehViewer = new System.Windows.Forms.Integration.ElementHost();
            this.ucDcViewer = new UnicodeSrl.WpfControls40.ucDcViewer();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPanelTempi = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubValidaTutto = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubSospendiTutto = new UnicodeSrl.ScciCore.ucEasyButton();
            this.uchkFiltro = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ubAdd = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblZoomViaSomministrazione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ubZoomViaSomministrazione = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblCodViaSomministrazione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblZoomTipoPrescrizione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblCodTipoPrescrizione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ubZoomTipoPrescrizione = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyTableLayoutPanelDCFiltro = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyCheckEditorDC = new UnicodeSrl.ScciCore.ucEasyCheckEditor();
            this.ucEasyPBStatoContinuazione = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.ucEasyTableLayoutPanelDC = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ultraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._frmBaseModaleUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._frmBaseModaleUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._frmBaseModaleUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._frmBaseModaleUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._frmBaseModaleAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.UltraPopupControlContainerMain = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmBaseModale_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmBaseModale_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmBaseModale_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmBaseModale_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.UltraPopupControlContainerSegnalibri = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.pnlFiltro.SuspendLayout();
            this.ucEasyTableLayoutPanelFiltri.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            this.ucEasyTableLayoutPanelTempi.SuspendLayout();
            this.ucEasyTableLayoutPanelDCFiltro.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyCheckEditorDC)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyPBStatoContinuazione)).BeginInit();
            this.ucEasyTableLayoutPanelDC.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).BeginInit();
            this._frmBaseModaleAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(965, 33);
                                                this.pnlFiltro.Controls.Add(this.ucEasyTableLayoutPanelFiltri);
            this.pnlFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlFiltro.Location = new System.Drawing.Point(0, 18);
            this.pnlFiltro.Name = "pnlFiltro";
            this.pnlFiltro.Size = new System.Drawing.Size(268, 765);
            this.pnlFiltro.TabIndex = 13;
                                                this.ucEasyTableLayoutPanelFiltri.ColumnCount = 3;
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ubApplicaFiltro, 1, 2);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyGridFiltroStato, 1, 1);
            this.ucEasyTableLayoutPanelFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltri.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelFiltri.Name = "ucEasyTableLayoutPanelFiltri";
            this.ucEasyTableLayoutPanelFiltri.RowCount = 4;
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 86F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltri.Size = new System.Drawing.Size(268, 765);
            this.ucEasyTableLayoutPanelFiltri.TabIndex = 2;
                                                appearance1.FontData.SizeInPoints = 27.16418F;
            appearance1.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance1.ImageBackground")));
            appearance1.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance1.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance1.TextHAlignAsString = "Center";
            appearance1.TextVAlignAsString = "Middle";
            this.ubApplicaFiltro.Appearance = appearance1;
            this.ubApplicaFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubApplicaFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltro.Location = new System.Drawing.Point(5, 667);
            this.ubApplicaFiltro.Name = "ubApplicaFiltro";
            this.ubApplicaFiltro.PercImageFill = 0.75F;
            this.ubApplicaFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.ubApplicaFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltro.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltro.Size = new System.Drawing.Size(256, 85);
            this.ubApplicaFiltro.TabIndex = 12;
            this.ubApplicaFiltro.Text = "Applica filtro";
            this.ubApplicaFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltro.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ucEasyGridFiltroStato.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroStato.ColonnaRTFResize = "";
            this.ucEasyGridFiltroStato.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance2.BackColor = System.Drawing.SystemColors.Window;
            appearance2.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroStato.DisplayLayout.Appearance = appearance2;
            this.ucEasyGridFiltroStato.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroStato.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance3.FontData.BoldAsString = "True";
            appearance3.FontData.SizeInPoints = 27.16418F;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionAppearance = appearance3;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance4.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance4.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance4.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Appearance = appearance4;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BandLabelAppearance = appearance5;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance6.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance6.BackColor2 = System.Drawing.SystemColors.Control;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.PromptAppearance = appearance6;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxRowScrollRegions = 1;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            appearance7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveCellAppearance = appearance7;
            appearance8.BackColor = System.Drawing.SystemColors.Highlight;
            appearance8.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveRowAppearance = appearance8;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance9.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CardAreaAppearance = appearance9;
            appearance10.BorderColor = System.Drawing.Color.Silver;
            appearance10.FontData.SizeInPoints = 18.80597F;
            appearance10.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellAppearance = appearance10;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance11.FontData.SizeInPoints = 27.16418F;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.FilterRowAppearance = appearance11;
            appearance12.BackColor = System.Drawing.SystemColors.Control;
            appearance12.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance12.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance12.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance12.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.GroupByRowAppearance = appearance12;
            appearance13.FontData.BoldAsString = "True";
            appearance13.FontData.SizeInPoints = 18.80597F;
            appearance13.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderAppearance = appearance13;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance14.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance14.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAlternateAppearance = appearance14;
            appearance15.BackColor = System.Drawing.SystemColors.Window;
            appearance15.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAppearance = appearance15;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.TemplateAddRowAppearance = appearance16;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroStato.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroStato.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroStato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroStato.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroStato.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridFiltroStato.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridFiltroStato.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.Location = new System.Drawing.Point(5, 10);
            this.ucEasyGridFiltroStato.Name = "ucEasyGridFiltroStato";
            this.ucEasyGridFiltroStato.ShowFilterRow = false;
            this.ucEasyGridFiltroStato.ShowGroupByBox = false;
            this.ucEasyGridFiltroStato.Size = new System.Drawing.Size(256, 651);
            this.ucEasyGridFiltroStato.TabIndex = 10;
            this.ucEasyGridFiltroStato.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroStato.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltroStato_InitializeLayout);
                                                this.ucAnteprimaRtf.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucAnteprimaRtf.Location = new System.Drawing.Point(3, 3);
            this.ucAnteprimaRtf.MovScheda = null;
            this.ucAnteprimaRtf.Name = "ucAnteprimaRtf";
            this.ucAnteprimaRtf.Size = new System.Drawing.Size(402, 279);
            this.ucAnteprimaRtf.TabIndex = 0;
                                                this.ehViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ehViewer.Location = new System.Drawing.Point(411, 3);
            this.ehViewer.Name = "ehViewer";
            this.ehViewer.Size = new System.Drawing.Size(403, 279);
            this.ehViewer.TabIndex = 14;
            this.ehViewer.Text = "elementHost1";
            this.ehViewer.Child = this.ucDcViewer;
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 33);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(965, 717);
            this.ultraGroupBox.TabIndex = 9;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 8;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGrid, 1, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelTempi, 6, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblZoomViaSomministrazione, 4, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubZoomViaSomministrazione, 5, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblCodViaSomministrazione, 4, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblZoomTipoPrescrizione, 1, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblCodTipoPrescrizione, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubZoomTipoPrescrizione, 2, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelDCFiltro, 6, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelDC, 1, 4);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 8;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 41F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(959, 711);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyGrid, 5);
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance17;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance18.FontData.BoldAsString = "True";
            appearance18.FontData.SizeInPoints = 27.16418F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance18;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance19.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance19.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance19.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance19.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance19;
            appearance20.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance20;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance21.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance21.BackColor2 = System.Drawing.SystemColors.Control;
            appearance21.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance21.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance21;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance22.BackColor = System.Drawing.SystemColors.Window;
            appearance22.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance22;
            appearance23.BackColor = System.Drawing.SystemColors.Highlight;
            appearance23.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance23;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance24.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance24;
            appearance25.BorderColor = System.Drawing.Color.Silver;
            appearance25.FontData.SizeInPoints = 18.80597F;
            appearance25.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance25;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance26.FontData.SizeInPoints = 27.16418F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance26;
            appearance27.BackColor = System.Drawing.SystemColors.Control;
            appearance27.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance27.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance27.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance27.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance27;
            appearance28.FontData.BoldAsString = "True";
            appearance28.FontData.SizeInPoints = 18.80597F;
            appearance28.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance28;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance29.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance29.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance29;
            appearance30.BackColor = System.Drawing.SystemColors.Window;
            appearance30.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance30;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance31.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance31;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(22, 413);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(817, 278);
            this.ucEasyGrid.TabIndex = 12;
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
            this.ucEasyGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucEasyGrid_ClickCell);
            this.ucEasyGrid.MouseEnterElement += new Infragistics.Win.UIElementEventHandler(this.ucEasyGrid_MouseEnterElement);
            this.ucEasyGrid.MouseLeaveElement += new Infragistics.Win.UIElementEventHandler(this.ucEasyGrid_MouseLeaveElement);
                                                this.ucEasyTableLayoutPanelTempi.ColumnCount = 1;
            this.ucEasyTableLayoutPanelTempi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelTempi.Controls.Add(this.ubValidaTutto, 0, 3);
            this.ucEasyTableLayoutPanelTempi.Controls.Add(this.ubSospendiTutto, 0, 2);
            this.ucEasyTableLayoutPanelTempi.Controls.Add(this.uchkFiltro, 0, 0);
            this.ucEasyTableLayoutPanelTempi.Controls.Add(this.ubAdd, 0, 1);
            this.ucEasyTableLayoutPanelTempi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelTempi.Location = new System.Drawing.Point(845, 413);
            this.ucEasyTableLayoutPanelTempi.Name = "ucEasyTableLayoutPanelTempi";
            this.ucEasyTableLayoutPanelTempi.RowCount = 4;
            this.ucEasyTableLayoutPanelTempi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelTempi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelTempi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelTempi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelTempi.Size = new System.Drawing.Size(89, 278);
            this.ucEasyTableLayoutPanelTempi.TabIndex = 11;
                                                appearance32.FontData.SizeInPoints = 18.80597F;
            appearance32.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance32.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance32.TextHAlignAsString = "Center";
            appearance32.TextVAlignAsString = "Bottom";
            this.ubValidaTutto.Appearance = appearance32;
            this.ubValidaTutto.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubValidaTutto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubValidaTutto.Location = new System.Drawing.Point(3, 210);
            this.ubValidaTutto.Name = "ubValidaTutto";
            this.ubValidaTutto.PercImageFill = 0.75F;
            this.ubValidaTutto.ShortcutColor = System.Drawing.Color.Black;
            this.ubValidaTutto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubValidaTutto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubValidaTutto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubValidaTutto.Size = new System.Drawing.Size(83, 65);
            this.ubValidaTutto.TabIndex = 7;
            this.ubValidaTutto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubValidaTutto.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubValidaTutto.Click += new System.EventHandler(this.ubValidaTutto_Click);
                                                appearance33.FontData.SizeInPoints = 18.80597F;
            appearance33.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance33.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance33.TextHAlignAsString = "Center";
            appearance33.TextVAlignAsString = "Bottom";
            this.ubSospendiTutto.Appearance = appearance33;
            this.ubSospendiTutto.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubSospendiTutto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubSospendiTutto.Location = new System.Drawing.Point(3, 141);
            this.ubSospendiTutto.Name = "ubSospendiTutto";
            this.ubSospendiTutto.PercImageFill = 0.75F;
            this.ubSospendiTutto.ShortcutColor = System.Drawing.Color.Black;
            this.ubSospendiTutto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubSospendiTutto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubSospendiTutto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubSospendiTutto.Size = new System.Drawing.Size(83, 63);
            this.ubSospendiTutto.TabIndex = 6;
            this.ubSospendiTutto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubSospendiTutto.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubSospendiTutto.Click += new System.EventHandler(this.ubSospendi_Click);
                                                appearance34.FontData.SizeInPoints = 18.80597F;
            appearance34.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance34.ImageBackground")));
            appearance34.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance34.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance34.TextHAlignAsString = "Center";
            appearance34.TextVAlignAsString = "Bottom";
            this.uchkFiltro.Appearance = appearance34;
            this.uchkFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkFiltro.Checked = false;
            this.uchkFiltro.CheckedImage = null;
            this.uchkFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkFiltro.Location = new System.Drawing.Point(3, 3);
            this.uchkFiltro.Name = "uchkFiltro";
            this.uchkFiltro.PercImageFill = 0.75F;
            this.uchkFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.uchkFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.uchkFiltro.ShortcutKey = System.Windows.Forms.Keys.F;
            this.uchkFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkFiltro.Size = new System.Drawing.Size(83, 63);
            this.uchkFiltro.TabIndex = 5;
            this.uchkFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkFiltro.UNCheckedImage = null;
            this.uchkFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uchkFiltro.Click += new System.EventHandler(this.uchkFiltro_Click);
                                                appearance35.FontData.SizeInPoints = 18.80597F;
            appearance35.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance35.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance35.TextHAlignAsString = "Center";
            appearance35.TextVAlignAsString = "Bottom";
            this.ubAdd.Appearance = appearance35;
            this.ubAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAdd.Location = new System.Drawing.Point(3, 72);
            this.ubAdd.Name = "ubAdd";
            this.ubAdd.PercImageFill = 0.75F;
            this.ubAdd.ShortcutColor = System.Drawing.Color.Black;
            this.ubAdd.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubAdd.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAdd.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAdd.Size = new System.Drawing.Size(83, 63);
            this.ubAdd.TabIndex = 4;
            this.ubAdd.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAdd.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAdd.Click += new System.EventHandler(this.ubAdd_Click);
                                                appearance36.FontData.SizeInPoints = 33.43283F;
            appearance36.TextVAlignAsString = "Middle";
            this.lblZoomViaSomministrazione.Appearance = appearance36;
            this.lblZoomViaSomministrazione.BorderStyleOuter = Infragistics.Win.UIElementBorderStyle.Solid;
            this.lblZoomViaSomministrazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblZoomViaSomministrazione.Location = new System.Drawing.Point(443, 52);
            this.lblZoomViaSomministrazione.Name = "lblZoomViaSomministrazione";
            this.lblZoomViaSomministrazione.ShortcutColor = System.Drawing.Color.Black;
            this.lblZoomViaSomministrazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblZoomViaSomministrazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblZoomViaSomministrazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblZoomViaSomministrazione.Size = new System.Drawing.Size(358, 43);
            this.lblZoomViaSomministrazione.TabIndex = 8;
            this.lblZoomViaSomministrazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance37.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance37.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance37.TextHAlignAsString = "Center";
            appearance37.TextVAlignAsString = "Bottom";
            this.ubZoomViaSomministrazione.Appearance = appearance37;
            this.ubZoomViaSomministrazione.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubZoomViaSomministrazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubZoomViaSomministrazione.Location = new System.Drawing.Point(807, 52);
            this.ubZoomViaSomministrazione.Name = "ubZoomViaSomministrazione";
            this.ubZoomViaSomministrazione.PercImageFill = 0.75F;
            this.ubZoomViaSomministrazione.ShortcutColor = System.Drawing.Color.Black;
            this.ubZoomViaSomministrazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubZoomViaSomministrazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubZoomViaSomministrazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubZoomViaSomministrazione.Size = new System.Drawing.Size(32, 43);
            this.ubZoomViaSomministrazione.TabIndex = 7;
            this.ubZoomViaSomministrazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubZoomViaSomministrazione.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubZoomViaSomministrazione.Click += new System.EventHandler(this.ubZoomViaSomministrazione_Click);
                                                appearance38.FontData.SizeInPoints = 27.16418F;
            appearance38.ForeColor = System.Drawing.Color.Red;
            appearance38.TextVAlignAsString = "Middle";
            this.lblCodViaSomministrazione.Appearance = appearance38;
            this.lblCodViaSomministrazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCodViaSomministrazione.Location = new System.Drawing.Point(443, 17);
            this.lblCodViaSomministrazione.Name = "lblCodViaSomministrazione";
            this.lblCodViaSomministrazione.ShortcutColor = System.Drawing.Color.Black;
            this.lblCodViaSomministrazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblCodViaSomministrazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblCodViaSomministrazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblCodViaSomministrazione.Size = new System.Drawing.Size(358, 29);
            this.lblCodViaSomministrazione.TabIndex = 6;
            this.lblCodViaSomministrazione.Text = "Via di Somministrazione";
            this.lblCodViaSomministrazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblCodViaSomministrazione.Visible = false;
                                                appearance39.FontData.SizeInPoints = 33.43283F;
            appearance39.TextVAlignAsString = "Middle";
            this.lblZoomTipoPrescrizione.Appearance = appearance39;
            this.lblZoomTipoPrescrizione.BorderStyleOuter = Infragistics.Win.UIElementBorderStyle.Solid;
            this.lblZoomTipoPrescrizione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblZoomTipoPrescrizione.Location = new System.Drawing.Point(22, 52);
            this.lblZoomTipoPrescrizione.Name = "lblZoomTipoPrescrizione";
            this.lblZoomTipoPrescrizione.ShortcutColor = System.Drawing.Color.Black;
            this.lblZoomTipoPrescrizione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblZoomTipoPrescrizione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblZoomTipoPrescrizione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblZoomTipoPrescrizione.Size = new System.Drawing.Size(358, 43);
            this.lblZoomTipoPrescrizione.TabIndex = 4;
            this.lblZoomTipoPrescrizione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance40.FontData.SizeInPoints = 27.16418F;
            appearance40.ForeColor = System.Drawing.Color.Red;
            appearance40.TextVAlignAsString = "Middle";
            this.lblCodTipoPrescrizione.Appearance = appearance40;
            this.lblCodTipoPrescrizione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCodTipoPrescrizione.Location = new System.Drawing.Point(22, 17);
            this.lblCodTipoPrescrizione.Name = "lblCodTipoPrescrizione";
            this.lblCodTipoPrescrizione.ShortcutColor = System.Drawing.Color.Black;
            this.lblCodTipoPrescrizione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblCodTipoPrescrizione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblCodTipoPrescrizione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblCodTipoPrescrizione.Size = new System.Drawing.Size(358, 29);
            this.lblCodTipoPrescrizione.TabIndex = 1;
            this.lblCodTipoPrescrizione.Text = "Tipo Prescrizione";
            this.lblCodTipoPrescrizione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblCodTipoPrescrizione.Visible = false;
                                                appearance41.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance41.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance41.TextHAlignAsString = "Center";
            appearance41.TextVAlignAsString = "Bottom";
            this.ubZoomTipoPrescrizione.Appearance = appearance41;
            this.ubZoomTipoPrescrizione.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubZoomTipoPrescrizione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubZoomTipoPrescrizione.Location = new System.Drawing.Point(386, 52);
            this.ubZoomTipoPrescrizione.Name = "ubZoomTipoPrescrizione";
            this.ubZoomTipoPrescrizione.PercImageFill = 0.75F;
            this.ubZoomTipoPrescrizione.ShortcutColor = System.Drawing.Color.Black;
            this.ubZoomTipoPrescrizione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubZoomTipoPrescrizione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubZoomTipoPrescrizione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubZoomTipoPrescrizione.Size = new System.Drawing.Size(32, 43);
            this.ubZoomTipoPrescrizione.TabIndex = 5;
            this.ubZoomTipoPrescrizione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubZoomTipoPrescrizione.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubZoomTipoPrescrizione.Click += new System.EventHandler(this.ubZoomTipoPrescrizione_Click);
                                                this.ucEasyTableLayoutPanelDCFiltro.ColumnCount = 1;
            this.ucEasyTableLayoutPanelDCFiltro.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelDCFiltro.Controls.Add(this.ucEasyCheckEditorDC, 0, 0);
            this.ucEasyTableLayoutPanelDCFiltro.Controls.Add(this.ucEasyPBStatoContinuazione, 0, 2);
            this.ucEasyTableLayoutPanelDCFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelDCFiltro.Location = new System.Drawing.Point(845, 108);
            this.ucEasyTableLayoutPanelDCFiltro.Name = "ucEasyTableLayoutPanelDCFiltro";
            this.ucEasyTableLayoutPanelDCFiltro.RowCount = 3;
            this.ucEasyTableLayoutPanelDCFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelDCFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelDCFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelDCFiltro.Size = new System.Drawing.Size(89, 285);
            this.ucEasyTableLayoutPanelDCFiltro.TabIndex = 16;
                                                appearance42.BackColor = System.Drawing.Color.Transparent;
            appearance42.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance42.ImageBackground")));
            appearance42.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance42.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.ucEasyCheckEditorDC.Appearance = appearance42;
            this.ucEasyCheckEditorDC.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyCheckEditorDC.BackColorInternal = System.Drawing.Color.Transparent;
            this.ucEasyCheckEditorDC.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Borderless;
            appearance43.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance43.ImageBackground")));
            appearance43.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance43.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.ucEasyCheckEditorDC.CheckedAppearance = appearance43;
            this.ucEasyCheckEditorDC.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyCheckEditorDC.Location = new System.Drawing.Point(3, 3);
            this.ucEasyCheckEditorDC.Name = "ucEasyCheckEditorDC";
            this.ucEasyCheckEditorDC.Size = new System.Drawing.Size(83, 79);
            this.ucEasyCheckEditorDC.Style = Infragistics.Win.EditCheckStyle.Button;
            this.ucEasyCheckEditorDC.TabIndex = 0;
            this.ucEasyCheckEditorDC.CheckedChanged += new System.EventHandler(this.ucEasyCheckEditorDC_CheckedChanged);
                                                this.ucEasyPBStatoContinuazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyPBStatoContinuazione.Location = new System.Drawing.Point(3, 202);
            this.ucEasyPBStatoContinuazione.Name = "ucEasyPBStatoContinuazione";
            this.ucEasyPBStatoContinuazione.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyPBStatoContinuazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyPBStatoContinuazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyPBStatoContinuazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyPBStatoContinuazione.Size = new System.Drawing.Size(83, 80);
            this.ucEasyPBStatoContinuazione.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.ucEasyPBStatoContinuazione.TabIndex = 1;
            this.ucEasyPBStatoContinuazione.TabStop = false;
                                                this.ucEasyTableLayoutPanelDC.ColumnCount = 2;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelDC, 5);
            this.ucEasyTableLayoutPanelDC.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ucEasyTableLayoutPanelDC.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ucEasyTableLayoutPanelDC.Controls.Add(this.ehViewer, 1, 0);
            this.ucEasyTableLayoutPanelDC.Controls.Add(this.ucAnteprimaRtf, 0, 0);
            this.ucEasyTableLayoutPanelDC.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelDC.Location = new System.Drawing.Point(22, 108);
            this.ucEasyTableLayoutPanelDC.Name = "ucEasyTableLayoutPanelDC";
            this.ucEasyTableLayoutPanelDC.RowCount = 1;
            this.ucEasyTableLayoutPanelDC.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelDC.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 285F));
            this.ucEasyTableLayoutPanelDC.Size = new System.Drawing.Size(817, 285);
            this.ucEasyTableLayoutPanelDC.TabIndex = 17;
                                                this.ultraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.ultraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.ultraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.ultraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Control = this.pnlFiltro;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(268, -1);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(865, 48, 92, 39);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "FILTRO";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(291, 783);
            this.ultraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.ultraDockManager.HostControl = this;
            this.ultraDockManager.ShowCloseButton = false;
            this.ultraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.ultraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.ultraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.ultraDockManager_InitializePane);
                                                this._frmBaseModaleUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._frmBaseModaleUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._frmBaseModaleUnpinnedTabAreaLeft.Name = "_frmBaseModaleUnpinnedTabAreaLeft";
            this._frmBaseModaleUnpinnedTabAreaLeft.Owner = this.ultraDockManager;
            this._frmBaseModaleUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 783);
            this._frmBaseModaleUnpinnedTabAreaLeft.TabIndex = 10;
                                                this._frmBaseModaleUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._frmBaseModaleUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleUnpinnedTabAreaRight.Location = new System.Drawing.Point(965, 0);
            this._frmBaseModaleUnpinnedTabAreaRight.Name = "_frmBaseModaleUnpinnedTabAreaRight";
            this._frmBaseModaleUnpinnedTabAreaRight.Owner = this.ultraDockManager;
            this._frmBaseModaleUnpinnedTabAreaRight.Size = new System.Drawing.Size(23, 783);
            this._frmBaseModaleUnpinnedTabAreaRight.TabIndex = 11;
                                                this._frmBaseModaleUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._frmBaseModaleUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._frmBaseModaleUnpinnedTabAreaTop.Name = "_frmBaseModaleUnpinnedTabAreaTop";
            this._frmBaseModaleUnpinnedTabAreaTop.Owner = this.ultraDockManager;
            this._frmBaseModaleUnpinnedTabAreaTop.Size = new System.Drawing.Size(965, 0);
            this._frmBaseModaleUnpinnedTabAreaTop.TabIndex = 12;
                                                this._frmBaseModaleUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._frmBaseModaleUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 783);
            this._frmBaseModaleUnpinnedTabAreaBottom.Name = "_frmBaseModaleUnpinnedTabAreaBottom";
            this._frmBaseModaleUnpinnedTabAreaBottom.Owner = this.ultraDockManager;
            this._frmBaseModaleUnpinnedTabAreaBottom.Size = new System.Drawing.Size(965, 0);
            this._frmBaseModaleUnpinnedTabAreaBottom.TabIndex = 13;
                                                this._frmBaseModaleAutoHideControl.Controls.Add(this.dockableWindow1);
            this._frmBaseModaleAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._frmBaseModaleAutoHideControl.Location = new System.Drawing.Point(892, 0);
            this._frmBaseModaleAutoHideControl.Name = "_frmBaseModaleAutoHideControl";
            this._frmBaseModaleAutoHideControl.Owner = this.ultraDockManager;
            this._frmBaseModaleAutoHideControl.Size = new System.Drawing.Size(73, 783);
            this._frmBaseModaleAutoHideControl.TabIndex = 14;
                                                this.dockableWindow1.Controls.Add(this.pnlFiltro);
            this.dockableWindow1.Location = new System.Drawing.Point(5, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.ultraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(268, 783);
            this.dockableWindow1.TabIndex = 20;
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Right;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(669, 0);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.ultraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(296, 783);
            this.windowDockingArea1.TabIndex = 15;
                                                this.UltraPopupControlContainerMain.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainerMain.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainerMain.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                appearance44.FontData.SizeInPoints = 20F;
            this.UltraToolbarsManager.Appearance = appearance44;
            this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.DockWithinContainerBaseType = typeof(UnicodeSrl.ScciCore.frmBaseModale);
            this.UltraToolbarsManager.ShowFullMenusDelay = 500;
            popupMenuTool1.SharedPropsInternal.Caption = "PopupMenuTool";
            popupMenuTool1.Tools.AddRange(new Infragistics.Win.UltraWinToolbars.ToolBase[] {
            buttonTool6,
            buttonTool7,
            buttonTool8,
            buttonTool9,
            buttonTool10});
            buttonTool1.SharedPropsInternal.Caption = "Modifica";
            buttonTool2.SharedPropsInternal.Caption = "Valida";
            buttonTool3.SharedPropsInternal.Caption = "Sospendi";
            buttonTool4.SharedPropsInternal.Caption = "Cancella";
            buttonTool5.SharedPropsInternal.Caption = "Copia";
            this.UltraToolbarsManager.Tools.AddRange(new Infragistics.Win.UltraWinToolbars.ToolBase[] {
            popupMenuTool1,
            buttonTool1,
            buttonTool2,
            buttonTool3,
            buttonTool4,
            buttonTool5});
            this.UltraToolbarsManager.UseLargeImagesOnMenu = true;
            this.UltraToolbarsManager.UseLargeImagesOnToolbar = true;
            this.UltraToolbarsManager.ToolClick += new Infragistics.Win.UltraWinToolbars.ToolClickEventHandler(this.UltraToolbarsManager_ToolClick);
                                                this._frmBaseModale_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmBaseModale_Toolbars_Dock_Area_Left.BackColor = System.Drawing.SystemColors.Control;
            this._frmBaseModale_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmBaseModale_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmBaseModale_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._frmBaseModale_Toolbars_Dock_Area_Left.Name = "_frmBaseModale_Toolbars_Dock_Area_Left";
            this._frmBaseModale_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 783);
            this._frmBaseModale_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmBaseModale_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmBaseModale_Toolbars_Dock_Area_Right.BackColor = System.Drawing.SystemColors.Control;
            this._frmBaseModale_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmBaseModale_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmBaseModale_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(988, 0);
            this._frmBaseModale_Toolbars_Dock_Area_Right.Name = "_frmBaseModale_Toolbars_Dock_Area_Right";
            this._frmBaseModale_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 783);
            this._frmBaseModale_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmBaseModale_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmBaseModale_Toolbars_Dock_Area_Top.BackColor = System.Drawing.SystemColors.Control;
            this._frmBaseModale_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmBaseModale_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmBaseModale_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmBaseModale_Toolbars_Dock_Area_Top.Name = "_frmBaseModale_Toolbars_Dock_Area_Top";
            this._frmBaseModale_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(988, 0);
            this._frmBaseModale_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmBaseModale_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmBaseModale_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.SystemColors.Control;
            this._frmBaseModale_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmBaseModale_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmBaseModale_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 783);
            this._frmBaseModale_Toolbars_Dock_Area_Bottom.Name = "_frmBaseModale_Toolbars_Dock_Area_Bottom";
            this._frmBaseModale_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(988, 0);
            this._frmBaseModale_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this.UltraPopupControlContainerSegnalibri.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerSegnalibri_Opening);
            this.UltraPopupControlContainerSegnalibri.Opened += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Opened);
            this.UltraPopupControlContainerSegnalibri.Closed += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(988, 783);
            this.Controls.Add(this._frmBaseModaleAutoHideControl);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._frmBaseModaleUnpinnedTabAreaTop);
            this.Controls.Add(this._frmBaseModaleUnpinnedTabAreaBottom);
            this.Controls.Add(this._frmBaseModaleUnpinnedTabAreaLeft);
            this.Controls.Add(this._frmBaseModaleUnpinnedTabAreaRight);
            this.Controls.Add(this._frmBaseModale_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmBaseModale_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmBaseModale_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmBaseModale_Toolbars_Dock_Area_Top);
            this.Name = "frmPUPrescrizioni";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUPrescrizioni";
            this.ImmagineClick += new UnicodeSrl.ScciCore.ImmagineTopClickHandler(this.frmPUPrescrizioni_ImmagineClick);
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUPrescrizioni_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUPrescrizioni_PulsanteAvantiClick);
            this.Shown += new System.EventHandler(this.frmPUPrescrizioni_Shown);
            this.Controls.SetChildIndex(this._frmBaseModale_Toolbars_Dock_Area_Top, 0);
            this.Controls.SetChildIndex(this._frmBaseModale_Toolbars_Dock_Area_Bottom, 0);
            this.Controls.SetChildIndex(this._frmBaseModale_Toolbars_Dock_Area_Right, 0);
            this.Controls.SetChildIndex(this._frmBaseModale_Toolbars_Dock_Area_Left, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleUnpinnedTabAreaRight, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleUnpinnedTabAreaLeft, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleUnpinnedTabAreaBottom, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleUnpinnedTabAreaTop, 0);
            this.Controls.SetChildIndex(this.windowDockingArea1, 0);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            this.Controls.SetChildIndex(this._frmBaseModaleAutoHideControl, 0);
            this.pnlFiltro.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFiltri.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            this.ucEasyTableLayoutPanelTempi.ResumeLayout(false);
            this.ucEasyTableLayoutPanelDCFiltro.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyCheckEditorDC)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyPBStatoContinuazione)).EndInit();
            this.ucEasyTableLayoutPanelDC.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).EndInit();
            this._frmBaseModaleAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyLabel lblZoomTipoPrescrizione;
        private ucEasyLabel lblCodTipoPrescrizione;
        private ucEasyButton ubZoomTipoPrescrizione;
        private ucEasyButton ubZoomViaSomministrazione;
        private ucEasyLabel lblCodViaSomministrazione;
        private ucEasyLabel lblZoomViaSomministrazione;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelTempi;
        private ucEasyGrid ucEasyGrid;
        private ucEasyButton ubAdd;
        private ucEasyStateButton uchkFiltro;
        private ucEasyButton ubValidaTutto;
        private ucEasyButton ubSospendiTutto;
        private Infragistics.Win.UltraWinDock.UltraDockManager ultraDockManager;
        private Infragistics.Win.UltraWinDock.AutoHideControl _frmBaseModaleAutoHideControl;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _frmBaseModaleUnpinnedTabAreaRight;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _frmBaseModaleUnpinnedTabAreaLeft;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _frmBaseModaleUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _frmBaseModaleUnpinnedTabAreaBottom;
        private System.Windows.Forms.Panel pnlFiltro;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltri;
        private ucEasyButton ubApplicaFiltro;
        private ucEasyGrid ucEasyGridFiltroStato;
        private System.Windows.Forms.Integration.ElementHost ehViewer;
        private WpfControls40.ucDcViewer ucDcViewer;
        private ucAnteprimaRtf ucAnteprimaRtf;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelDCFiltro;
        private ucEasyCheckEditor ucEasyCheckEditorDC;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelDC;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerMain;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmBaseModale_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmBaseModale_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmBaseModale_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmBaseModale_Toolbars_Dock_Area_Top;
        private ucEasyPictureBox ucEasyPBStatoContinuazione;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerSegnalibri;
    }
}