namespace UnicodeSrl.ScciCore
{
    partial class frmPUAperturaCartella
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPUAperturaCartella));
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinStatusBar.UltraStatusPanel ultraStatusPanel1 = new Infragistics.Win.UltraWinStatusBar.UltraStatusPanel();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab2 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucEasyTableLayoutPanelNuovaCartella = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblAttenzione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyTableLayoutPanelNumero = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblAnnoCartella = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utxtNumeroCartella = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblNumeroCartella = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ultraTabPageControl2 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucEasyTableLayoutPanelCollega = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblAttenzioneCollega = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblAnnoCartellaCollega = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ubSelezionaCartellaCollegata = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblCollegaPrecedente = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblCollegaNuova = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.txtCollegaPrecedente = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.txtCollegaNuova = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ultraStatusBar = new Infragistics.Win.UltraWinStatusBar.UltraStatusBar();
            this.lblPaziente = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblConferma = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utcNuovaCartella = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.lblAlertCollegaCartella = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.optCollegaCartella = new UnicodeSrl.ScciCore.ucEasyOptionSet();
            this.ucEasyPictureBoxCollega = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.ultraTabPageControl1.SuspendLayout();
            this.ucEasyTableLayoutPanelNuovaCartella.SuspendLayout();
            this.ucEasyTableLayoutPanelNumero.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.utxtNumeroCartella)).BeginInit();
            this.ultraTabPageControl2.SuspendLayout();
            this.ucEasyTableLayoutPanelCollega.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtCollegaPrecedente)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtCollegaNuova)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraStatusBar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utcNuovaCartella)).BeginInit();
            this.utcNuovaCartella.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.optCollegaCartella)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyPictureBoxCollega)).BeginInit();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.ucEasyTableLayoutPanelNuovaCartella);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(385, 135);
                                                this.ucEasyTableLayoutPanelNuovaCartella.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanelNuovaCartella.ColumnCount = 1;
            this.ucEasyTableLayoutPanelNuovaCartella.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelNuovaCartella.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelNuovaCartella.Controls.Add(this.lblAttenzione, 0, 1);
            this.ucEasyTableLayoutPanelNuovaCartella.Controls.Add(this.ucEasyTableLayoutPanelNumero, 0, 0);
            this.ucEasyTableLayoutPanelNuovaCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelNuovaCartella.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelNuovaCartella.Name = "ucEasyTableLayoutPanelNuovaCartella";
            this.ucEasyTableLayoutPanelNuovaCartella.RowCount = 2;
            this.ucEasyTableLayoutPanelNuovaCartella.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.ucEasyTableLayoutPanelNuovaCartella.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 66F));
            this.ucEasyTableLayoutPanelNuovaCartella.Size = new System.Drawing.Size(385, 135);
            this.ucEasyTableLayoutPanelNuovaCartella.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 20.60976F;
            appearance1.ForeColor = System.Drawing.Color.Red;
            appearance1.TextHAlignAsString = "Center";
            appearance1.TextVAlignAsString = "Middle";
            this.lblAttenzione.Appearance = appearance1;
            this.lblAttenzione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAttenzione.Location = new System.Drawing.Point(3, 48);
            this.lblAttenzione.Name = "lblAttenzione";
            this.lblAttenzione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblAttenzione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblAttenzione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblAttenzione.Size = new System.Drawing.Size(379, 84);
            this.lblAttenzione.TabIndex = 3;
            this.lblAttenzione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucEasyTableLayoutPanelNumero.ColumnCount = 3;
            this.ucEasyTableLayoutPanelNumero.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ucEasyTableLayoutPanelNumero.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelNumero.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelNumero.Controls.Add(this.lblAnnoCartella, 2, 0);
            this.ucEasyTableLayoutPanelNumero.Controls.Add(this.utxtNumeroCartella, 1, 0);
            this.ucEasyTableLayoutPanelNumero.Controls.Add(this.lblNumeroCartella, 0, 0);
            this.ucEasyTableLayoutPanelNumero.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelNumero.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanelNumero.Name = "ucEasyTableLayoutPanelNumero";
            this.ucEasyTableLayoutPanelNumero.RowCount = 1;
            this.ucEasyTableLayoutPanelNumero.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelNumero.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 39F));
            this.ucEasyTableLayoutPanelNumero.Size = new System.Drawing.Size(379, 39);
            this.ucEasyTableLayoutPanelNumero.TabIndex = 2;
                                                appearance2.FontData.SizeInPoints = 38.04878F;
            appearance2.TextHAlignAsString = "Left";
            appearance2.TextVAlignAsString = "Middle";
            this.lblAnnoCartella.Appearance = appearance2;
            this.lblAnnoCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAnnoCartella.Location = new System.Drawing.Point(286, 3);
            this.lblAnnoCartella.Name = "lblAnnoCartella";
            this.lblAnnoCartella.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblAnnoCartella.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblAnnoCartella.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblAnnoCartella.Size = new System.Drawing.Size(90, 33);
            this.lblAnnoCartella.TabIndex = 4;
            this.lblAnnoCartella.Text = "/2013";
            this.lblAnnoCartella.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
                                                appearance3.FontData.SizeInPoints = 38.04878F;
            appearance3.TextHAlignAsString = "Right";
            this.utxtNumeroCartella.Appearance = appearance3;
            this.utxtNumeroCartella.AutoSize = false;
            this.utxtNumeroCartella.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtNumeroCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtNumeroCartella.Location = new System.Drawing.Point(192, 3);
            this.utxtNumeroCartella.Name = "utxtNumeroCartella";
            this.utxtNumeroCartella.Size = new System.Drawing.Size(88, 33);
            this.utxtNumeroCartella.TabIndex = 3;
            this.utxtNumeroCartella.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
            this.utxtNumeroCartella.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance4.FontData.SizeInPoints = 38.04878F;
            appearance4.TextHAlignAsString = "Center";
            appearance4.TextVAlignAsString = "Middle";
            this.lblNumeroCartella.Appearance = appearance4;
            this.lblNumeroCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNumeroCartella.Location = new System.Drawing.Point(3, 3);
            this.lblNumeroCartella.Name = "lblNumeroCartella";
            this.lblNumeroCartella.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblNumeroCartella.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblNumeroCartella.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblNumeroCartella.Size = new System.Drawing.Size(183, 33);
            this.lblNumeroCartella.TabIndex = 1;
            this.lblNumeroCartella.Text = "Numero Cartella:";
            this.lblNumeroCartella.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
                                                this.ultraTabPageControl2.Controls.Add(this.ucEasyTableLayoutPanelCollega);
            this.ultraTabPageControl2.Location = new System.Drawing.Point(0, 0);
            this.ultraTabPageControl2.Name = "ultraTabPageControl2";
            this.ultraTabPageControl2.Size = new System.Drawing.Size(385, 135);
                                                this.ucEasyTableLayoutPanelCollega.ColumnCount = 5;
            this.ucEasyTableLayoutPanelCollega.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelCollega.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelCollega.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 29F));
            this.ucEasyTableLayoutPanelCollega.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 21F));
            this.ucEasyTableLayoutPanelCollega.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelCollega.Controls.Add(this.lblAttenzioneCollega, 1, 3);
            this.ucEasyTableLayoutPanelCollega.Controls.Add(this.lblAnnoCartellaCollega, 3, 2);
            this.ucEasyTableLayoutPanelCollega.Controls.Add(this.ubSelezionaCartellaCollegata, 1, 0);
            this.ucEasyTableLayoutPanelCollega.Controls.Add(this.lblCollegaPrecedente, 1, 1);
            this.ucEasyTableLayoutPanelCollega.Controls.Add(this.lblCollegaNuova, 1, 2);
            this.ucEasyTableLayoutPanelCollega.Controls.Add(this.txtCollegaPrecedente, 2, 1);
            this.ucEasyTableLayoutPanelCollega.Controls.Add(this.txtCollegaNuova, 2, 2);
            this.ucEasyTableLayoutPanelCollega.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelCollega.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelCollega.Name = "ucEasyTableLayoutPanelCollega";
            this.ucEasyTableLayoutPanelCollega.RowCount = 4;
            this.ucEasyTableLayoutPanelCollega.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelCollega.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelCollega.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelCollega.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelCollega.Size = new System.Drawing.Size(385, 135);
            this.ucEasyTableLayoutPanelCollega.TabIndex = 0;
                                                appearance5.FontData.SizeInPoints = 20.60976F;
            appearance5.ForeColor = System.Drawing.Color.Red;
            appearance5.TextHAlignAsString = "Center";
            appearance5.TextVAlignAsString = "Middle";
            this.lblAttenzioneCollega.Appearance = appearance5;
            this.ucEasyTableLayoutPanelCollega.SetColumnSpan(this.lblAttenzioneCollega, 3);
            this.lblAttenzioneCollega.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAttenzioneCollega.Location = new System.Drawing.Point(22, 102);
            this.lblAttenzioneCollega.Name = "lblAttenzioneCollega";
            this.lblAttenzioneCollega.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblAttenzioneCollega.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblAttenzioneCollega.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblAttenzioneCollega.Size = new System.Drawing.Size(339, 30);
            this.lblAttenzioneCollega.TabIndex = 6;
            this.lblAttenzioneCollega.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance6.FontData.SizeInPoints = 38.04878F;
            appearance6.TextHAlignAsString = "Left";
            appearance6.TextVAlignAsString = "Middle";
            this.lblAnnoCartellaCollega.Appearance = appearance6;
            this.lblAnnoCartellaCollega.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAnnoCartellaCollega.Location = new System.Drawing.Point(287, 69);
            this.lblAnnoCartellaCollega.Name = "lblAnnoCartellaCollega";
            this.lblAnnoCartellaCollega.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblAnnoCartellaCollega.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblAnnoCartellaCollega.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblAnnoCartellaCollega.Size = new System.Drawing.Size(74, 27);
            this.lblAnnoCartellaCollega.TabIndex = 5;
            this.lblAnnoCartellaCollega.Text = "/2013";
            this.lblAnnoCartellaCollega.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
                                                appearance7.FontData.SizeInPoints = 38.04878F;
            appearance7.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance7.ImageBackground")));
            appearance7.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance7.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance7.TextHAlignAsString = "Center";
            appearance7.TextVAlignAsString = "Middle";
            this.ubSelezionaCartellaCollegata.Appearance = appearance7;
            this.ubSelezionaCartellaCollegata.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanelCollega.SetColumnSpan(this.ubSelezionaCartellaCollegata, 3);
            this.ubSelezionaCartellaCollegata.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubSelezionaCartellaCollegata.Location = new System.Drawing.Point(22, 3);
            this.ubSelezionaCartellaCollegata.Name = "ubSelezionaCartellaCollegata";
            this.ubSelezionaCartellaCollegata.PercImageFill = 0.75F;
            this.ubSelezionaCartellaCollegata.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubSelezionaCartellaCollegata.ShortcutKey = System.Windows.Forms.Keys.S;
            this.ubSelezionaCartellaCollegata.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubSelezionaCartellaCollegata.Size = new System.Drawing.Size(339, 27);
            this.ubSelezionaCartellaCollegata.TabIndex = 0;
            this.ubSelezionaCartellaCollegata.Text = "Seleziona Cartella";
            this.ubSelezionaCartellaCollegata.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
            this.ubSelezionaCartellaCollegata.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubSelezionaCartellaCollegata.Click += new System.EventHandler(this.ubSelezionaCartellaCollegata_Click);
                                                appearance8.FontData.SizeInPoints = 38.04878F;
            appearance8.TextVAlignAsString = "Middle";
            this.lblCollegaPrecedente.Appearance = appearance8;
            this.lblCollegaPrecedente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCollegaPrecedente.Location = new System.Drawing.Point(22, 36);
            this.lblCollegaPrecedente.Name = "lblCollegaPrecedente";
            this.lblCollegaPrecedente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblCollegaPrecedente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblCollegaPrecedente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblCollegaPrecedente.Size = new System.Drawing.Size(148, 27);
            this.lblCollegaPrecedente.TabIndex = 1;
            this.lblCollegaPrecedente.Text = "Selezionata:";
            this.lblCollegaPrecedente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
                                                appearance9.FontData.SizeInPoints = 38.04878F;
            appearance9.TextVAlignAsString = "Middle";
            this.lblCollegaNuova.Appearance = appearance9;
            this.lblCollegaNuova.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCollegaNuova.Location = new System.Drawing.Point(22, 69);
            this.lblCollegaNuova.Name = "lblCollegaNuova";
            this.lblCollegaNuova.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblCollegaNuova.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblCollegaNuova.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblCollegaNuova.Size = new System.Drawing.Size(148, 27);
            this.lblCollegaNuova.TabIndex = 1;
            this.lblCollegaNuova.Text = "Nuova:";
            this.lblCollegaNuova.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
                                                appearance10.FontData.SizeInPoints = 38.04878F;
            appearance10.TextHAlignAsString = "Right";
            appearance10.TextVAlignAsString = "Middle";
            this.txtCollegaPrecedente.Appearance = appearance10;
            this.txtCollegaPrecedente.AutoSize = false;
            this.ucEasyTableLayoutPanelCollega.SetColumnSpan(this.txtCollegaPrecedente, 2);
            this.txtCollegaPrecedente.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtCollegaPrecedente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCollegaPrecedente.Location = new System.Drawing.Point(176, 36);
            this.txtCollegaPrecedente.Name = "txtCollegaPrecedente";
            this.txtCollegaPrecedente.ReadOnly = true;
            this.txtCollegaPrecedente.Size = new System.Drawing.Size(185, 27);
            this.txtCollegaPrecedente.TabIndex = 4;
            this.txtCollegaPrecedente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
            this.txtCollegaPrecedente.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance11.FontData.SizeInPoints = 38.04878F;
            appearance11.TextHAlignAsString = "Right";
            appearance11.TextVAlignAsString = "Middle";
            this.txtCollegaNuova.Appearance = appearance11;
            this.txtCollegaNuova.AutoSize = false;
            this.txtCollegaNuova.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtCollegaNuova.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCollegaNuova.Location = new System.Drawing.Point(176, 69);
            this.txtCollegaNuova.Name = "txtCollegaNuova";
            this.txtCollegaNuova.ReadOnly = true;
            this.txtCollegaNuova.Size = new System.Drawing.Size(105, 27);
            this.txtCollegaNuova.TabIndex = 4;
            this.txtCollegaNuova.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
            this.txtCollegaNuova.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 24);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(784, 514);
            this.ultraGroupBox.TabIndex = 10;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 5;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 43F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ultraStatusBar, 1, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblPaziente, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblConferma, 1, 0);
            this.ucEasyTableLayoutPanel.Controls.Add(this.utcNuovaCartella, 3, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblAlertCollegaCartella, 2, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.optCollegaCartella, 1, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyPictureBoxCollega, 1, 2);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 6;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(778, 508);
            this.ucEasyTableLayoutPanel.TabIndex = 11;
                                                this.ucEasyTableLayoutPanel.SetColumnSpan(this.ultraStatusBar, 3);
            this.ultraStatusBar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraStatusBar.Location = new System.Drawing.Point(57, 484);
            this.ultraStatusBar.Name = "ultraStatusBar";
            ultraStatusPanel1.Key = "ProgressBar";
            ultraStatusPanel1.ProgressBarInfo.Maximum = 5;
            ultraStatusPanel1.ProgressBarInfo.Style = Infragistics.Win.UltraWinProgressBar.ProgressBarStyle.Continuous;
            ultraStatusPanel1.SizingMode = Infragistics.Win.UltraWinStatusBar.PanelSizingMode.Spring;
            ultraStatusPanel1.Style = Infragistics.Win.UltraWinStatusBar.PanelStyle.Progress;
            this.ultraStatusBar.Panels.AddRange(new Infragistics.Win.UltraWinStatusBar.UltraStatusPanel[] {
            ultraStatusPanel1});
            this.ultraStatusBar.Size = new System.Drawing.Size(661, 21);
            this.ultraStatusBar.TabIndex = 20;
            this.ultraStatusBar.ViewStyle = Infragistics.Win.UltraWinStatusBar.ViewStyle.Office2007;
            this.ultraStatusBar.Visible = false;
                                                appearance12.FontData.SizeInPoints = 44.39024F;
            appearance12.ForeColor = System.Drawing.Color.Red;
            appearance12.TextVAlignAsString = "Middle";
            this.lblPaziente.Appearance = appearance12;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblPaziente, 3);
            this.lblPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPaziente.Location = new System.Drawing.Point(57, 79);
            this.lblPaziente.Name = "lblPaziente";
            this.lblPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPaziente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPaziente.Size = new System.Drawing.Size(661, 187);
            this.lblPaziente.TabIndex = 1;
            this.lblPaziente.Text = "Pinco Pallino ma qual\'è il nome e qual\'è il cognome";
            this.lblPaziente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XXLarge;
                                                appearance13.FontData.SizeInPoints = 38.04878F;
            appearance13.TextHAlignAsString = "Center";
            appearance13.TextVAlignAsString = "Middle";
            this.lblConferma.Appearance = appearance13;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblConferma, 3);
            this.lblConferma.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblConferma.Location = new System.Drawing.Point(57, 3);
            this.lblConferma.Name = "lblConferma";
            this.lblConferma.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblConferma.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblConferma.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblConferma.Size = new System.Drawing.Size(661, 70);
            this.lblConferma.TabIndex = 0;
            this.lblConferma.Text = "Conferma dell\'apertura della Cartella Clinica per il paziente:";
            this.lblConferma.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
                                                this.ucEasyTableLayoutPanel.SetColumnSpan(this.utcNuovaCartella, 2);
            this.utcNuovaCartella.Controls.Add(this.ultraTabSharedControlsPage1);
            this.utcNuovaCartella.Controls.Add(this.ultraTabPageControl1);
            this.utcNuovaCartella.Controls.Add(this.ultraTabPageControl2);
            this.utcNuovaCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utcNuovaCartella.Location = new System.Drawing.Point(390, 343);
            this.utcNuovaCartella.Name = "utcNuovaCartella";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.utcNuovaCartella, 2);
            this.utcNuovaCartella.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.utcNuovaCartella.Size = new System.Drawing.Size(385, 135);
            this.utcNuovaCartella.Style = Infragistics.Win.UltraWinTabControl.UltraTabControlStyle.Wizard;
            this.utcNuovaCartella.TabIndex = 4;
            ultraTab1.Key = "N";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Nuova";
            ultraTab2.Key = "C";
            ultraTab2.TabPage = this.ultraTabPageControl2;
            ultraTab2.Text = "Collega";
            this.utcNuovaCartella.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1,
            ultraTab2});
                                                this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(385, 135);
                                                appearance14.FontData.SizeInPoints = 25.36585F;
            appearance14.TextVAlignAsString = "Middle";
            this.lblAlertCollegaCartella.Appearance = appearance14;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblAlertCollegaCartella, 2);
            this.lblAlertCollegaCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAlertCollegaCartella.Location = new System.Drawing.Point(134, 272);
            this.lblAlertCollegaCartella.Name = "lblAlertCollegaCartella";
            this.lblAlertCollegaCartella.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblAlertCollegaCartella.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblAlertCollegaCartella.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblAlertCollegaCartella.Size = new System.Drawing.Size(584, 65);
            this.lblAlertCollegaCartella.TabIndex = 5;
            this.lblAlertCollegaCartella.Text = "E\' possibile collegare una cartella aperta";
            this.lblAlertCollegaCartella.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.lblAlertCollegaCartella.Visible = false;
                                                appearance15.BackColor = System.Drawing.Color.White;
            appearance15.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.optCollegaCartella.Appearance = appearance15;
            this.optCollegaCartella.BackColor = System.Drawing.Color.White;
            this.optCollegaCartella.BackColorInternal = System.Drawing.Color.White;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.optCollegaCartella, 2);
            this.optCollegaCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.optCollegaCartella.GlyphInfo = new Infragistics.Win.RadioButtonImageGlyphInfo(((System.Drawing.Bitmap)(resources.GetObject("optCollegaCartella.GlyphInfo"))), "Custom radio button glyphs");
            appearance16.BackColor = System.Drawing.Color.White;
            appearance16.FontData.SizeInPoints = 38.04878F;
            this.optCollegaCartella.ItemAppearance = appearance16;
            this.optCollegaCartella.ItemOrigin = new System.Drawing.Point(5, 5);
            this.optCollegaCartella.ItemSpacingHorizontal = 5;
            this.optCollegaCartella.ItemSpacingVertical = 5;
            this.optCollegaCartella.Location = new System.Drawing.Point(57, 343);
            this.optCollegaCartella.Name = "optCollegaCartella";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.optCollegaCartella, 2);
            this.optCollegaCartella.Size = new System.Drawing.Size(327, 135);
            this.optCollegaCartella.TabIndex = 6;
            this.optCollegaCartella.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XLarge;
            this.optCollegaCartella.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.optCollegaCartella.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.optCollegaCartella.Visible = false;
            this.optCollegaCartella.ValueChanged += new System.EventHandler(this.optCollegaCartella_ValueChanged);
                                                this.ucEasyPictureBoxCollega.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyPictureBoxCollega.Location = new System.Drawing.Point(57, 272);
            this.ucEasyPictureBoxCollega.Name = "ucEasyPictureBoxCollega";
            this.ucEasyPictureBoxCollega.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyPictureBoxCollega.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyPictureBoxCollega.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyPictureBoxCollega.Size = new System.Drawing.Size(71, 65);
            this.ucEasyPictureBoxCollega.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.ucEasyPictureBoxCollega.TabIndex = 7;
            this.ucEasyPictureBoxCollega.TabStop = false;
            this.ucEasyPictureBoxCollega.Visible = false;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmPUAperturaCartella";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUAperturaCartella";
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUAperturaCartella_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUAperturaCartella_PulsanteAvantiClick);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            this.ultraTabPageControl1.ResumeLayout(false);
            this.ucEasyTableLayoutPanelNuovaCartella.ResumeLayout(false);
            this.ucEasyTableLayoutPanelNumero.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.utxtNumeroCartella)).EndInit();
            this.ultraTabPageControl2.ResumeLayout(false);
            this.ucEasyTableLayoutPanelCollega.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txtCollegaPrecedente)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtCollegaNuova)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraStatusBar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utcNuovaCartella)).EndInit();
            this.utcNuovaCartella.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.optCollegaCartella)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyPictureBoxCollega)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyLabel lblAttenzione;
        private ucEasyLabel lblPaziente;
        private ucEasyLabel lblConferma;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelNumero;
        private ucEasyLabel lblAnnoCartella;
        private ucEasyTextBox utxtNumeroCartella;
        private ucEasyLabel lblNumeroCartella;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl utcNuovaCartella;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelNuovaCartella;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl2;
        private ucEasyLabel lblAlertCollegaCartella;
        private ucEasyOptionSet optCollegaCartella;
        private ucEasyPictureBox ucEasyPictureBoxCollega;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelCollega;
        private ucEasyButton ubSelezionaCartellaCollegata;
        private ucEasyLabel lblCollegaPrecedente;
        private ucEasyLabel lblCollegaNuova;
        private ucEasyTextBox txtCollegaPrecedente;
        private ucEasyTextBox txtCollegaNuova;
        private Infragistics.Win.UltraWinStatusBar.UltraStatusBar ultraStatusBar;
        private ucEasyLabel lblAnnoCartellaCollega;
        private ucEasyLabel lblAttenzioneCollega;


    }
}