namespace UnicodeSrl.ScciCore
{
    partial class frmPUGestioneAccount
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTableLayoutPanelContatti = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubContattiAdd = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblContattiDes = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.pbContatti = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.UltraGridContatti = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPanelPaziente = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.pbPaziente = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.TableLayoutPanelPaziente = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblCodiceFiscale = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblIndirizzo = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblPaziente = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblPazienteDes = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyTableLayoutPanelAccount = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblStatoMHLogin = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblAccountDes = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.pbAccount = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.TableLayoutPanelAccount = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubStampa = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubPassword = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubStatoMHLogin = new UnicodeSrl.ScciCore.ucEasyButton();
            this.udteDataScadenza = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.utePassword = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.uteUtente = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblScadenza = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblPassword = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblUtente = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyTableLayoutPanelUA = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.UltraGridMovAccessi = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ubUAAdd = new UnicodeSrl.ScciCore.ucEasyButton();
            this.UltraGridUA = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.UltraPopupControlContainerStatoLogin = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.UltraPopupControlContainerLoginUA = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.UltraPopupControlContainerLoginContatti = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            this.ucEasyTableLayoutPanelContatti.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbContatti)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridContatti)).BeginInit();
            this.ucEasyTableLayoutPanelPaziente.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbPaziente)).BeginInit();
            this.TableLayoutPanelPaziente.SuspendLayout();
            this.ucEasyTableLayoutPanelAccount.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbAccount)).BeginInit();
            this.TableLayoutPanelAccount.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataScadenza)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utePassword)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteUtente)).BeginInit();
            this.ucEasyTableLayoutPanelUA.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridMovAccessi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridUA)).BeginInit();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(1008, 31);
                                                this.UltraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 31);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(1008, 667);
            this.UltraGroupBox.TabIndex = 10;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 4;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 52F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 46F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelContatti, 1, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelPaziente, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelAccount, 1, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelUA, 2, 3);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 7;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(1002, 661);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.ucEasyTableLayoutPanelContatti.ColumnCount = 3;
            this.ucEasyTableLayoutPanelContatti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanelContatti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 78F));
            this.ucEasyTableLayoutPanelContatti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelContatti.Controls.Add(this.ubContattiAdd, 2, 0);
            this.ucEasyTableLayoutPanelContatti.Controls.Add(this.lblContattiDes, 0, 0);
            this.ucEasyTableLayoutPanelContatti.Controls.Add(this.pbContatti, 0, 1);
            this.ucEasyTableLayoutPanelContatti.Controls.Add(this.UltraGridContatti, 1, 0);
            this.ucEasyTableLayoutPanelContatti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelContatti.Location = new System.Drawing.Point(13, 431);
            this.ucEasyTableLayoutPanelContatti.Name = "ucEasyTableLayoutPanelContatti";
            this.ucEasyTableLayoutPanelContatti.RowCount = 3;
            this.ucEasyTableLayoutPanelContatti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelContatti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanelContatti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelContatti.Size = new System.Drawing.Size(515, 218);
            this.ucEasyTableLayoutPanelContatti.TabIndex = 2;
                                                appearance1.FontData.SizeInPoints = 15.58209F;
            appearance1.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance1.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance1.TextHAlignAsString = "Center";
            appearance1.TextVAlignAsString = "Bottom";
            this.ubContattiAdd.Appearance = appearance1;
            this.ubContattiAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubContattiAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubContattiAdd.Location = new System.Drawing.Point(465, 3);
            this.ubContattiAdd.Name = "ubContattiAdd";
            this.ubContattiAdd.PercImageFill = 0.75F;
            this.ubContattiAdd.ShortcutColor = System.Drawing.Color.Black;
            this.ubContattiAdd.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubContattiAdd.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubContattiAdd.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubContattiAdd.Size = new System.Drawing.Size(47, 37);
            this.ubContattiAdd.TabIndex = 16;
            this.ubContattiAdd.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubContattiAdd.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubContattiAdd.Click += new System.EventHandler(this.ubContattiAdd_Click);
                                                appearance2.FontData.SizeInPoints = 12.1194F;
            appearance2.TextHAlignAsString = "Center";
            appearance2.TextVAlignAsString = "Middle";
            this.lblContattiDes.Appearance = appearance2;
            this.lblContattiDes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblContattiDes.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblContattiDes.Location = new System.Drawing.Point(3, 3);
            this.lblContattiDes.Name = "lblContattiDes";
            this.lblContattiDes.ShortcutColor = System.Drawing.Color.Black;
            this.lblContattiDes.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblContattiDes.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblContattiDes.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblContattiDes.Size = new System.Drawing.Size(55, 37);
            this.lblContattiDes.TabIndex = 14;
            this.lblContattiDes.Text = "Cellulari";
            this.lblContattiDes.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
                                                this.pbContatti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pbContatti.Location = new System.Drawing.Point(5, 48);
            this.pbContatti.Margin = new System.Windows.Forms.Padding(5);
            this.pbContatti.Name = "pbContatti";
            this.pbContatti.ShortcutColor = System.Drawing.Color.Black;
            this.pbContatti.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbContatti.ShortcutKey = System.Windows.Forms.Keys.None;
            this.pbContatti.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbContatti.Size = new System.Drawing.Size(51, 120);
            this.pbContatti.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbContatti.TabIndex = 13;
            this.pbContatti.TabStop = false;
                                                this.UltraGridContatti.ColonnaRTFControlloContenuto = false;
            this.UltraGridContatti.ColonnaRTFResize = "";
            this.UltraGridContatti.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.UltraGridContatti.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance3.BackColor = System.Drawing.SystemColors.Window;
            appearance3.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridContatti.DisplayLayout.Appearance = appearance3;
            this.UltraGridContatti.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridContatti.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.FontData.SizeInPoints = 22.50746F;
            this.UltraGridContatti.DisplayLayout.CaptionAppearance = appearance4;
            this.UltraGridContatti.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance5.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance5.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance5.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridContatti.DisplayLayout.GroupByBox.Appearance = appearance5;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridContatti.DisplayLayout.GroupByBox.BandLabelAppearance = appearance6;
            this.UltraGridContatti.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridContatti.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridContatti.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance7.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance7.BackColor2 = System.Drawing.SystemColors.Control;
            appearance7.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance7.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridContatti.DisplayLayout.GroupByBox.PromptAppearance = appearance7;
            this.UltraGridContatti.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridContatti.DisplayLayout.MaxRowScrollRegions = 1;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            appearance8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridContatti.DisplayLayout.Override.ActiveCellAppearance = appearance8;
            appearance9.BackColor = System.Drawing.SystemColors.Highlight;
            appearance9.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridContatti.DisplayLayout.Override.ActiveRowAppearance = appearance9;
            this.UltraGridContatti.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridContatti.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridContatti.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridContatti.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridContatti.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridContatti.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridContatti.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridContatti.DisplayLayout.Override.CardAreaAppearance = appearance10;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            appearance11.FontData.SizeInPoints = 22.50746F;
            appearance11.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridContatti.DisplayLayout.Override.CellAppearance = appearance11;
            this.UltraGridContatti.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridContatti.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridContatti.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance12.FontData.SizeInPoints = 22.50746F;
            this.UltraGridContatti.DisplayLayout.Override.FilterRowAppearance = appearance12;
            appearance13.BackColor = System.Drawing.SystemColors.Control;
            appearance13.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance13.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance13.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance13.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridContatti.DisplayLayout.Override.GroupByRowAppearance = appearance13;
            appearance14.FontData.BoldAsString = "True";
            appearance14.FontData.SizeInPoints = 22.50746F;
            appearance14.TextHAlignAsString = "Center";
            this.UltraGridContatti.DisplayLayout.Override.HeaderAppearance = appearance14;
            this.UltraGridContatti.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridContatti.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance15.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance15.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridContatti.DisplayLayout.Override.RowAlternateAppearance = appearance15;
            appearance16.BackColor = System.Drawing.SystemColors.Window;
            appearance16.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridContatti.DisplayLayout.Override.RowAppearance = appearance16;
            this.UltraGridContatti.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridContatti.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridContatti.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridContatti.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance17.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridContatti.DisplayLayout.Override.TemplateAddRowAppearance = appearance17;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridContatti.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.UltraGridContatti.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridContatti.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridContatti.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridContatti.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridContatti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridContatti.FattoreRidimensionamentoRTF = 21;
            this.UltraGridContatti.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.UltraGridContatti.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.UltraGridContatti.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.UltraGridContatti.Location = new System.Drawing.Point(64, 3);
            this.UltraGridContatti.Name = "UltraGridContatti";
            this.ucEasyTableLayoutPanelContatti.SetRowSpan(this.UltraGridContatti, 3);
            this.UltraGridContatti.ShowFilterRow = false;
            this.UltraGridContatti.ShowGroupByBox = false;
            this.UltraGridContatti.Size = new System.Drawing.Size(395, 212);
            this.UltraGridContatti.TabIndex = 15;
            this.UltraGridContatti.Text = "ucEasyGrid1";
            this.UltraGridContatti.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridContatti.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridContatti.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridContatti_InitializeLayout);
            this.UltraGridContatti.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGridContatti_InitializeRow);
            this.UltraGridContatti.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.UltraGridContatti_ClickCellButton);
                                                this.ucEasyTableLayoutPanelPaziente.ColumnCount = 2;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelPaziente, 2);
            this.ucEasyTableLayoutPanelPaziente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelPaziente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 90F));
            this.ucEasyTableLayoutPanelPaziente.Controls.Add(this.pbPaziente, 0, 1);
            this.ucEasyTableLayoutPanelPaziente.Controls.Add(this.TableLayoutPanelPaziente, 1, 1);
            this.ucEasyTableLayoutPanelPaziente.Controls.Add(this.lblPazienteDes, 0, 0);
            this.ucEasyTableLayoutPanelPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelPaziente.Location = new System.Drawing.Point(13, 9);
            this.ucEasyTableLayoutPanelPaziente.Name = "ucEasyTableLayoutPanelPaziente";
            this.ucEasyTableLayoutPanelPaziente.RowCount = 2;
            this.ucEasyTableLayoutPanelPaziente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelPaziente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.ucEasyTableLayoutPanelPaziente.Size = new System.Drawing.Size(975, 126);
            this.ucEasyTableLayoutPanelPaziente.TabIndex = 0;
                                                this.pbPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pbPaziente.Location = new System.Drawing.Point(5, 30);
            this.pbPaziente.Margin = new System.Windows.Forms.Padding(5);
            this.pbPaziente.Name = "pbPaziente";
            this.pbPaziente.ShortcutColor = System.Drawing.Color.Black;
            this.pbPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbPaziente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.pbPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbPaziente.Size = new System.Drawing.Size(87, 91);
            this.pbPaziente.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbPaziente.TabIndex = 12;
            this.pbPaziente.TabStop = false;
                                                this.TableLayoutPanelPaziente.ColumnCount = 2;
            this.TableLayoutPanelPaziente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanelPaziente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 95F));
            this.TableLayoutPanelPaziente.Controls.Add(this.lblCodiceFiscale, 1, 2);
            this.TableLayoutPanelPaziente.Controls.Add(this.lblIndirizzo, 1, 1);
            this.TableLayoutPanelPaziente.Controls.Add(this.lblPaziente, 1, 0);
            this.TableLayoutPanelPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelPaziente.Location = new System.Drawing.Point(97, 25);
            this.TableLayoutPanelPaziente.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanelPaziente.Name = "TableLayoutPanelPaziente";
            this.TableLayoutPanelPaziente.RowCount = 3;
            this.TableLayoutPanelPaziente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.TableLayoutPanelPaziente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.TableLayoutPanelPaziente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.TableLayoutPanelPaziente.Size = new System.Drawing.Size(878, 101);
            this.TableLayoutPanelPaziente.TabIndex = 11;
                                                appearance18.BackColor = System.Drawing.Color.Transparent;
            appearance18.FontData.SizeInPoints = 15.58209F;
            appearance18.TextHAlignAsString = "Left";
            appearance18.TextVAlignAsString = "Middle";
            this.lblCodiceFiscale.Appearance = appearance18;
            this.lblCodiceFiscale.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCodiceFiscale.Location = new System.Drawing.Point(46, 66);
            this.lblCodiceFiscale.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblCodiceFiscale.Name = "lblCodiceFiscale";
            this.lblCodiceFiscale.ShortcutColor = System.Drawing.Color.Black;
            this.lblCodiceFiscale.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblCodiceFiscale.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblCodiceFiscale.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblCodiceFiscale.Size = new System.Drawing.Size(829, 35);
            this.lblCodiceFiscale.TabIndex = 5;
            this.lblCodiceFiscale.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance19.BackColor = System.Drawing.Color.Transparent;
            appearance19.FontData.SizeInPoints = 15.58209F;
            appearance19.TextHAlignAsString = "Left";
            appearance19.TextVAlignAsString = "Middle";
            this.lblIndirizzo.Appearance = appearance19;
            this.lblIndirizzo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblIndirizzo.Location = new System.Drawing.Point(46, 33);
            this.lblIndirizzo.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblIndirizzo.Name = "lblIndirizzo";
            this.lblIndirizzo.ShortcutColor = System.Drawing.Color.Black;
            this.lblIndirizzo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblIndirizzo.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblIndirizzo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblIndirizzo.Size = new System.Drawing.Size(829, 33);
            this.lblIndirizzo.TabIndex = 4;
            this.lblIndirizzo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance20.BackColor = System.Drawing.Color.Transparent;
            appearance20.FontData.BoldAsString = "True";
            appearance20.FontData.SizeInPoints = 22.50746F;
            appearance20.TextHAlignAsString = "Left";
            appearance20.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            appearance20.TextVAlignAsString = "Middle";
            this.lblPaziente.Appearance = appearance20;
            this.lblPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPaziente.Location = new System.Drawing.Point(46, 0);
            this.lblPaziente.Margin = new System.Windows.Forms.Padding(3, 0, 3, 0);
            this.lblPaziente.Name = "lblPaziente";
            this.lblPaziente.ShortcutColor = System.Drawing.Color.Black;
            this.lblPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPaziente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPaziente.Size = new System.Drawing.Size(829, 33);
            this.lblPaziente.TabIndex = 4;
            this.lblPaziente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblPaziente.WrapText = false;
                                                appearance21.FontData.SizeInPoints = 15.58209F;
            appearance21.TextHAlignAsString = "Center";
            appearance21.TextVAlignAsString = "Middle";
            this.lblPazienteDes.Appearance = appearance21;
            this.lblPazienteDes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPazienteDes.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPazienteDes.Location = new System.Drawing.Point(3, 3);
            this.lblPazienteDes.Name = "lblPazienteDes";
            this.lblPazienteDes.ShortcutColor = System.Drawing.Color.Black;
            this.lblPazienteDes.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPazienteDes.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPazienteDes.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPazienteDes.Size = new System.Drawing.Size(91, 19);
            this.lblPazienteDes.TabIndex = 13;
            this.lblPazienteDes.Text = "Paziente";
            this.lblPazienteDes.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                this.ucEasyTableLayoutPanelAccount.ColumnCount = 2;
            this.ucEasyTableLayoutPanelAccount.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanelAccount.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 88F));
            this.ucEasyTableLayoutPanelAccount.Controls.Add(this.lblStatoMHLogin, 0, 2);
            this.ucEasyTableLayoutPanelAccount.Controls.Add(this.lblAccountDes, 0, 0);
            this.ucEasyTableLayoutPanelAccount.Controls.Add(this.pbAccount, 0, 1);
            this.ucEasyTableLayoutPanelAccount.Controls.Add(this.TableLayoutPanelAccount, 1, 0);
            this.ucEasyTableLayoutPanelAccount.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelAccount.Location = new System.Drawing.Point(13, 174);
            this.ucEasyTableLayoutPanelAccount.Name = "ucEasyTableLayoutPanelAccount";
            this.ucEasyTableLayoutPanelAccount.RowCount = 3;
            this.ucEasyTableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelAccount.Size = new System.Drawing.Size(515, 218);
            this.ucEasyTableLayoutPanelAccount.TabIndex = 1;
                                                appearance22.FontData.SizeInPoints = 15.58209F;
            appearance22.TextHAlignAsString = "Center";
            appearance22.TextVAlignAsString = "Middle";
            this.lblStatoMHLogin.Appearance = appearance22;
            this.lblStatoMHLogin.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblStatoMHLogin.Location = new System.Drawing.Point(3, 176);
            this.lblStatoMHLogin.Name = "lblStatoMHLogin";
            this.lblStatoMHLogin.ShortcutColor = System.Drawing.Color.Black;
            this.lblStatoMHLogin.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblStatoMHLogin.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblStatoMHLogin.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblStatoMHLogin.Size = new System.Drawing.Size(55, 39);
            this.lblStatoMHLogin.TabIndex = 15;
            this.lblStatoMHLogin.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance23.FontData.SizeInPoints = 12.1194F;
            appearance23.TextHAlignAsString = "Center";
            appearance23.TextVAlignAsString = "Middle";
            this.lblAccountDes.Appearance = appearance23;
            this.lblAccountDes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAccountDes.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblAccountDes.Location = new System.Drawing.Point(3, 3);
            this.lblAccountDes.Name = "lblAccountDes";
            this.lblAccountDes.ShortcutColor = System.Drawing.Color.Black;
            this.lblAccountDes.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblAccountDes.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblAccountDes.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblAccountDes.Size = new System.Drawing.Size(55, 37);
            this.lblAccountDes.TabIndex = 14;
            this.lblAccountDes.Text = "Account";
            this.lblAccountDes.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
                                                this.pbAccount.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pbAccount.Location = new System.Drawing.Point(5, 48);
            this.pbAccount.Margin = new System.Windows.Forms.Padding(5);
            this.pbAccount.Name = "pbAccount";
            this.pbAccount.ShortcutColor = System.Drawing.Color.Black;
            this.pbAccount.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbAccount.ShortcutKey = System.Windows.Forms.Keys.None;
            this.pbAccount.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbAccount.Size = new System.Drawing.Size(51, 120);
            this.pbAccount.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbAccount.TabIndex = 13;
            this.pbAccount.TabStop = false;
                                                this.TableLayoutPanelAccount.ColumnCount = 2;
            this.TableLayoutPanelAccount.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 90F));
            this.TableLayoutPanelAccount.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanelAccount.Controls.Add(this.ubStampa, 2, 7);
            this.TableLayoutPanelAccount.Controls.Add(this.ubPassword, 1, 4);
            this.TableLayoutPanelAccount.Controls.Add(this.ubStatoMHLogin, 1, 1);
            this.TableLayoutPanelAccount.Controls.Add(this.udteDataScadenza, 0, 7);
            this.TableLayoutPanelAccount.Controls.Add(this.utePassword, 0, 4);
            this.TableLayoutPanelAccount.Controls.Add(this.uteUtente, 0, 1);
            this.TableLayoutPanelAccount.Controls.Add(this.lblScadenza, 0, 6);
            this.TableLayoutPanelAccount.Controls.Add(this.lblPassword, 0, 3);
            this.TableLayoutPanelAccount.Controls.Add(this.lblUtente, 0, 0);
            this.TableLayoutPanelAccount.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelAccount.Location = new System.Drawing.Point(61, 0);
            this.TableLayoutPanelAccount.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanelAccount.Name = "TableLayoutPanelAccount";
            this.TableLayoutPanelAccount.RowCount = 8;
            this.ucEasyTableLayoutPanelAccount.SetRowSpan(this.TableLayoutPanelAccount, 3);
            this.TableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.TableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.TableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanelAccount.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.TableLayoutPanelAccount.Size = new System.Drawing.Size(454, 218);
            this.TableLayoutPanelAccount.TabIndex = 16;
                                                appearance24.FontData.SizeInPoints = 15.58209F;
            appearance24.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance24.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance24.TextHAlignAsString = "Center";
            appearance24.TextVAlignAsString = "Bottom";
            this.ubStampa.Appearance = appearance24;
            this.ubStampa.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubStampa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubStampa.Location = new System.Drawing.Point(411, 172);
            this.ubStampa.Name = "ubStampa";
            this.ubStampa.PercImageFill = 0.75F;
            this.ubStampa.ShortcutColor = System.Drawing.Color.Black;
            this.ubStampa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubStampa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubStampa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubStampa.Size = new System.Drawing.Size(40, 43);
            this.ubStampa.TabIndex = 8;
            this.ubStampa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubStampa.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubStampa.Click += new System.EventHandler(this.ubStampa_Click);
                                                appearance25.FontData.SizeInPoints = 15.58209F;
            appearance25.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance25.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance25.TextHAlignAsString = "Center";
            appearance25.TextVAlignAsString = "Bottom";
            this.ubPassword.Appearance = appearance25;
            this.ubPassword.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubPassword.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubPassword.Location = new System.Drawing.Point(411, 98);
            this.ubPassword.Name = "ubPassword";
            this.ubPassword.PercImageFill = 0.75F;
            this.ubPassword.ShortcutColor = System.Drawing.Color.Black;
            this.ubPassword.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubPassword.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubPassword.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubPassword.Size = new System.Drawing.Size(40, 37);
            this.ubPassword.TabIndex = 7;
            this.ubPassword.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubPassword.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubPassword.Click += new System.EventHandler(this.ubPassword_Click);
                                                appearance26.FontData.SizeInPoints = 15.58209F;
            appearance26.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance26.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance26.TextHAlignAsString = "Center";
            appearance26.TextVAlignAsString = "Bottom";
            this.ubStatoMHLogin.Appearance = appearance26;
            this.ubStatoMHLogin.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubStatoMHLogin.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubStatoMHLogin.Location = new System.Drawing.Point(411, 24);
            this.ubStatoMHLogin.Name = "ubStatoMHLogin";
            this.ubStatoMHLogin.PercImageFill = 0.75F;
            this.ubStatoMHLogin.ShortcutColor = System.Drawing.Color.Black;
            this.ubStatoMHLogin.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubStatoMHLogin.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubStatoMHLogin.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubStatoMHLogin.Size = new System.Drawing.Size(40, 37);
            this.ubStatoMHLogin.TabIndex = 6;
            this.ubStatoMHLogin.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubStatoMHLogin.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubStatoMHLogin.Click += new System.EventHandler(this.ubStatoMHLogin_Click);
                                                appearance27.FontData.SizeInPoints = 27.70149F;
            appearance27.TextHAlignAsString = "Center";
            this.udteDataScadenza.Appearance = appearance27;
            this.udteDataScadenza.AutoSize = false;
            this.udteDataScadenza.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteDataScadenza.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataScadenza.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance28.FontData.SizeInPoints = 27.70149F;
            this.udteDataScadenza.DropDownAppearance = appearance28;
            this.udteDataScadenza.FormatString = "dd/MM/yyyy";
            this.udteDataScadenza.Location = new System.Drawing.Point(3, 172);
            this.udteDataScadenza.MaskInput = "{LOC}dd/mm/yyyy";
            this.udteDataScadenza.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteDataScadenza.Name = "udteDataScadenza";
            this.udteDataScadenza.Size = new System.Drawing.Size(402, 43);
            this.udteDataScadenza.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataScadenza.TabIndex = 5;
            this.udteDataScadenza.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.udteDataScadenza.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance29.FontData.SizeInPoints = 27.70149F;
            this.utePassword.Appearance = appearance29;
            this.utePassword.AutoSize = false;
            this.utePassword.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utePassword.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utePassword.Location = new System.Drawing.Point(3, 98);
            this.utePassword.Name = "utePassword";
            this.utePassword.ReadOnly = true;
            this.utePassword.Size = new System.Drawing.Size(402, 37);
            this.utePassword.TabIndex = 4;
            this.utePassword.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.utePassword.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance30.FontData.SizeInPoints = 27.70149F;
            this.uteUtente.Appearance = appearance30;
            this.uteUtente.AutoSize = false;
            this.uteUtente.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteUtente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteUtente.Location = new System.Drawing.Point(3, 24);
            this.uteUtente.Name = "uteUtente";
            this.uteUtente.ReadOnly = true;
            this.uteUtente.Size = new System.Drawing.Size(402, 37);
            this.uteUtente.TabIndex = 3;
            this.uteUtente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.uteUtente.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance31.FontData.SizeInPoints = 15.58209F;
            appearance31.TextVAlignAsString = "Middle";
            this.lblScadenza.Appearance = appearance31;
            this.lblScadenza.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblScadenza.Location = new System.Drawing.Point(3, 151);
            this.lblScadenza.Name = "lblScadenza";
            this.lblScadenza.ShortcutColor = System.Drawing.Color.Black;
            this.lblScadenza.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblScadenza.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblScadenza.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblScadenza.Size = new System.Drawing.Size(402, 15);
            this.lblScadenza.TabIndex = 2;
            this.lblScadenza.Text = "Scadenza";
            this.lblScadenza.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance32.FontData.SizeInPoints = 15.58209F;
            appearance32.TextVAlignAsString = "Middle";
            this.lblPassword.Appearance = appearance32;
            this.lblPassword.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPassword.Location = new System.Drawing.Point(3, 77);
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.ShortcutColor = System.Drawing.Color.Black;
            this.lblPassword.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblPassword.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblPassword.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblPassword.Size = new System.Drawing.Size(402, 15);
            this.lblPassword.TabIndex = 1;
            this.lblPassword.Text = "Password";
            this.lblPassword.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance33.FontData.SizeInPoints = 15.58209F;
            appearance33.TextVAlignAsString = "Middle";
            this.lblUtente.Appearance = appearance33;
            this.lblUtente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUtente.Location = new System.Drawing.Point(3, 3);
            this.lblUtente.Name = "lblUtente";
            this.lblUtente.ShortcutColor = System.Drawing.Color.Black;
            this.lblUtente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblUtente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblUtente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblUtente.Size = new System.Drawing.Size(402, 15);
            this.lblUtente.TabIndex = 0;
            this.lblUtente.Text = "Utente";
            this.lblUtente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                this.ucEasyTableLayoutPanelUA.ColumnCount = 2;
            this.ucEasyTableLayoutPanelUA.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 90F));
            this.ucEasyTableLayoutPanelUA.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelUA.Controls.Add(this.UltraGridMovAccessi, 0, 3);
            this.ucEasyTableLayoutPanelUA.Controls.Add(this.ubUAAdd, 1, 0);
            this.ucEasyTableLayoutPanelUA.Controls.Add(this.UltraGridUA, 0, 0);
            this.ucEasyTableLayoutPanelUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelUA.Location = new System.Drawing.Point(534, 174);
            this.ucEasyTableLayoutPanelUA.Name = "ucEasyTableLayoutPanelUA";
            this.ucEasyTableLayoutPanelUA.RowCount = 4;
            this.ucEasyTableLayoutPanel.SetRowSpan(this.ucEasyTableLayoutPanelUA, 3);
            this.ucEasyTableLayoutPanelUA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelUA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.ucEasyTableLayoutPanelUA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanelUA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ucEasyTableLayoutPanelUA.Size = new System.Drawing.Size(454, 475);
            this.ucEasyTableLayoutPanelUA.TabIndex = 3;
                                                this.UltraGridMovAccessi.ColonnaRTFControlloContenuto = false;
            this.UltraGridMovAccessi.ColonnaRTFResize = "";
            this.UltraGridMovAccessi.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.UltraGridMovAccessi.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance34.BackColor = System.Drawing.SystemColors.Window;
            appearance34.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridMovAccessi.DisplayLayout.Appearance = appearance34;
            this.UltraGridMovAccessi.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridMovAccessi.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance35.FontData.SizeInPoints = 15.58209F;
            this.UltraGridMovAccessi.DisplayLayout.CaptionAppearance = appearance35;
            appearance36.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance36.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance36.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance36.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridMovAccessi.DisplayLayout.GroupByBox.Appearance = appearance36;
            appearance37.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridMovAccessi.DisplayLayout.GroupByBox.BandLabelAppearance = appearance37;
            this.UltraGridMovAccessi.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridMovAccessi.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridMovAccessi.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance38.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance38.BackColor2 = System.Drawing.SystemColors.Control;
            appearance38.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance38.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridMovAccessi.DisplayLayout.GroupByBox.PromptAppearance = appearance38;
            this.UltraGridMovAccessi.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridMovAccessi.DisplayLayout.MaxRowScrollRegions = 1;
            appearance39.BackColor = System.Drawing.SystemColors.Window;
            appearance39.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridMovAccessi.DisplayLayout.Override.ActiveCellAppearance = appearance39;
            appearance40.BackColor = System.Drawing.SystemColors.Highlight;
            appearance40.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridMovAccessi.DisplayLayout.Override.ActiveRowAppearance = appearance40;
            this.UltraGridMovAccessi.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridMovAccessi.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridMovAccessi.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridMovAccessi.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridMovAccessi.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridMovAccessi.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridMovAccessi.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance41.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridMovAccessi.DisplayLayout.Override.CardAreaAppearance = appearance41;
            appearance42.BorderColor = System.Drawing.Color.Silver;
            appearance42.FontData.SizeInPoints = 22.50746F;
            appearance42.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridMovAccessi.DisplayLayout.Override.CellAppearance = appearance42;
            this.UltraGridMovAccessi.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridMovAccessi.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridMovAccessi.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance43.FontData.SizeInPoints = 15.58209F;
            this.UltraGridMovAccessi.DisplayLayout.Override.FilterRowAppearance = appearance43;
            appearance44.BackColor = System.Drawing.SystemColors.Control;
            appearance44.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance44.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance44.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance44.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridMovAccessi.DisplayLayout.Override.GroupByRowAppearance = appearance44;
            appearance45.FontData.BoldAsString = "True";
            appearance45.FontData.SizeInPoints = 15.58209F;
            appearance45.TextHAlignAsString = "Center";
            this.UltraGridMovAccessi.DisplayLayout.Override.HeaderAppearance = appearance45;
            this.UltraGridMovAccessi.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridMovAccessi.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance46.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance46.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridMovAccessi.DisplayLayout.Override.RowAlternateAppearance = appearance46;
            appearance47.BackColor = System.Drawing.SystemColors.Window;
            appearance47.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridMovAccessi.DisplayLayout.Override.RowAppearance = appearance47;
            this.UltraGridMovAccessi.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridMovAccessi.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridMovAccessi.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridMovAccessi.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance48.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridMovAccessi.DisplayLayout.Override.TemplateAddRowAppearance = appearance48;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridMovAccessi.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.UltraGridMovAccessi.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridMovAccessi.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridMovAccessi.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridMovAccessi.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridMovAccessi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridMovAccessi.FattoreRidimensionamentoRTF = 21;
            this.UltraGridMovAccessi.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridMovAccessi.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridMovAccessi.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridMovAccessi.Location = new System.Drawing.Point(3, 239);
            this.UltraGridMovAccessi.Name = "UltraGridMovAccessi";
            this.UltraGridMovAccessi.ShowFilterRow = false;
            this.UltraGridMovAccessi.ShowGroupByBox = false;
            this.UltraGridMovAccessi.Size = new System.Drawing.Size(402, 233);
            this.UltraGridMovAccessi.TabIndex = 18;
            this.UltraGridMovAccessi.Text = "Accessi";
            this.UltraGridMovAccessi.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridMovAccessi.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridMovAccessi.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridMovAccessi_InitializeLayout);
                                                appearance49.FontData.SizeInPoints = 15.58209F;
            appearance49.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance49.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance49.TextHAlignAsString = "Center";
            appearance49.TextVAlignAsString = "Bottom";
            this.ubUAAdd.Appearance = appearance49;
            this.ubUAAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubUAAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubUAAdd.Location = new System.Drawing.Point(411, 3);
            this.ubUAAdd.Name = "ubUAAdd";
            this.ubUAAdd.PercImageFill = 0.75F;
            this.ubUAAdd.ShortcutColor = System.Drawing.Color.Black;
            this.ubUAAdd.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubUAAdd.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubUAAdd.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubUAAdd.Size = new System.Drawing.Size(40, 41);
            this.ubUAAdd.TabIndex = 17;
            this.ubUAAdd.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubUAAdd.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubUAAdd.Click += new System.EventHandler(this.ubUAAdd_Click);
                                                this.UltraGridUA.ColonnaRTFControlloContenuto = false;
            this.UltraGridUA.ColonnaRTFResize = "";
            this.UltraGridUA.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.UltraGridUA.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance50.BackColor = System.Drawing.SystemColors.Window;
            appearance50.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridUA.DisplayLayout.Appearance = appearance50;
            this.UltraGridUA.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridUA.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance51.FontData.SizeInPoints = 15.58209F;
            this.UltraGridUA.DisplayLayout.CaptionAppearance = appearance51;
            appearance52.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance52.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance52.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance52.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridUA.DisplayLayout.GroupByBox.Appearance = appearance52;
            appearance53.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridUA.DisplayLayout.GroupByBox.BandLabelAppearance = appearance53;
            this.UltraGridUA.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridUA.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridUA.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance54.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance54.BackColor2 = System.Drawing.SystemColors.Control;
            appearance54.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance54.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridUA.DisplayLayout.GroupByBox.PromptAppearance = appearance54;
            this.UltraGridUA.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridUA.DisplayLayout.MaxRowScrollRegions = 1;
            appearance55.BackColor = System.Drawing.SystemColors.Window;
            appearance55.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridUA.DisplayLayout.Override.ActiveCellAppearance = appearance55;
            appearance56.BackColor = System.Drawing.SystemColors.Highlight;
            appearance56.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridUA.DisplayLayout.Override.ActiveRowAppearance = appearance56;
            this.UltraGridUA.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridUA.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridUA.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUA.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUA.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUA.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridUA.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance57.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridUA.DisplayLayout.Override.CardAreaAppearance = appearance57;
            appearance58.BorderColor = System.Drawing.Color.Silver;
            appearance58.FontData.SizeInPoints = 22.50746F;
            appearance58.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridUA.DisplayLayout.Override.CellAppearance = appearance58;
            this.UltraGridUA.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridUA.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridUA.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance59.FontData.SizeInPoints = 15.58209F;
            this.UltraGridUA.DisplayLayout.Override.FilterRowAppearance = appearance59;
            appearance60.BackColor = System.Drawing.SystemColors.Control;
            appearance60.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance60.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance60.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance60.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridUA.DisplayLayout.Override.GroupByRowAppearance = appearance60;
            appearance61.FontData.BoldAsString = "True";
            appearance61.FontData.SizeInPoints = 15.58209F;
            appearance61.TextHAlignAsString = "Center";
            this.UltraGridUA.DisplayLayout.Override.HeaderAppearance = appearance61;
            this.UltraGridUA.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridUA.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance62.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance62.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridUA.DisplayLayout.Override.RowAlternateAppearance = appearance62;
            appearance63.BackColor = System.Drawing.SystemColors.Window;
            appearance63.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridUA.DisplayLayout.Override.RowAppearance = appearance63;
            this.UltraGridUA.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUA.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridUA.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridUA.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance64.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridUA.DisplayLayout.Override.TemplateAddRowAppearance = appearance64;
            scrollBarLook3.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridUA.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.UltraGridUA.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridUA.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridUA.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridUA.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridUA.FattoreRidimensionamentoRTF = 21;
            this.UltraGridUA.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridUA.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridUA.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridUA.Location = new System.Drawing.Point(3, 3);
            this.UltraGridUA.Name = "UltraGridUA";
            this.ucEasyTableLayoutPanelUA.SetRowSpan(this.UltraGridUA, 2);
            this.UltraGridUA.ShowFilterRow = false;
            this.UltraGridUA.ShowGroupByBox = false;
            this.UltraGridUA.Size = new System.Drawing.Size(402, 221);
            this.UltraGridUA.TabIndex = 16;
            this.UltraGridUA.Text = "Strutture";
            this.UltraGridUA.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridUA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUA.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridUA_InitializeLayout);
            this.UltraGridUA.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGridUA_InitializeRow);
            this.UltraGridUA.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.UltraGridUA_ClickCellButton);
                                                this.UltraPopupControlContainerStatoLogin.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerStatoLogin_Opening);
            this.UltraPopupControlContainerStatoLogin.Opened += new System.EventHandler(this.UltraPopupControlContainerStatoLogin_Opened);
            this.UltraPopupControlContainerStatoLogin.Closed += new System.EventHandler(this.UltraPopupControlContainerStatoLogin_Closed);
                                                this.UltraPopupControlContainerLoginUA.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerLoginUA_Opening);
            this.UltraPopupControlContainerLoginUA.Opened += new System.EventHandler(this.UltraPopupControlContainerLoginUA_Opened);
            this.UltraPopupControlContainerLoginUA.Closed += new System.EventHandler(this.UltraPopupControlContainerLoginUA_Closed);
                                                this.UltraPopupControlContainerLoginContatti.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerLoginContatti_Opening);
            this.UltraPopupControlContainerLoginContatti.Opened += new System.EventHandler(this.UltraPopupControlContainerLoginContatti_Opened);
            this.UltraPopupControlContainerLoginContatti.Closed += new System.EventHandler(this.UltraPopupControlContainerLoginContatti_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1008, 729);
            this.Controls.Add(this.UltraGroupBox);
            this.Name = "frmPUGestioneAccount";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUGestioneAccount";
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUGestioneAccount_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUGestioneAccount_PulsanteAvantiClick);
            this.Controls.SetChildIndex(this.UltraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            this.ucEasyTableLayoutPanelContatti.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbContatti)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridContatti)).EndInit();
            this.ucEasyTableLayoutPanelPaziente.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbPaziente)).EndInit();
            this.TableLayoutPanelPaziente.ResumeLayout(false);
            this.ucEasyTableLayoutPanelAccount.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbAccount)).EndInit();
            this.TableLayoutPanelAccount.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteDataScadenza)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utePassword)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteUtente)).EndInit();
            this.ucEasyTableLayoutPanelUA.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridMovAccessi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridUA)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelPaziente;
        private ucEasyTableLayoutPanel TableLayoutPanelPaziente;
        private ucEasyLabel lblCodiceFiscale;
        private ucEasyLabel lblIndirizzo;
        private ucEasyLabel lblPaziente;
        private ucEasyPictureBox pbPaziente;
        private ucEasyLabel lblPazienteDes;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelAccount;
        private ucEasyPictureBox pbAccount;
        private ucEasyLabel lblStatoMHLogin;
        private ucEasyLabel lblAccountDes;
        private ucEasyTableLayoutPanel TableLayoutPanelAccount;
        private ucEasyLabel lblUtente;
        private ucEasyLabel lblScadenza;
        private ucEasyLabel lblPassword;
        private ucEasyTextBox uteUtente;
        private ucEasyTextBox utePassword;
        private ucEasyDateTimeEditor udteDataScadenza;
        private ucEasyButton ubStatoMHLogin;
        private ucEasyButton ubPassword;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelContatti;
        private ucEasyLabel lblContattiDes;
        private ucEasyPictureBox pbContatti;
        private ucEasyButton ubContattiAdd;
        private ucEasyGrid UltraGridContatti;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelUA;
        private ucEasyButton ubStampa;
        private ucEasyGrid UltraGridUA;
        private ucEasyButton ubUAAdd;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerStatoLogin;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerLoginUA;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerLoginContatti;
        private ucEasyGrid UltraGridMovAccessi;
    }
}