namespace UnicodeSrl.ScciCore
{
    partial class frmPUEvidenzaClinica
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPUEvidenzaClinica));
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab4 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab5 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab6 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.webBrowser = new System.Windows.Forms.WebBrowser();
            this.ultraTabPageControl2 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ultraTabPageControl3 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblDataReferto = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblDataRefertoValore = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblTipoReferto = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblTipoRefertoValore = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ubPDF = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubGrafico = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyTabControl = new UnicodeSrl.ScciCore.ucEasyTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.uchkVista = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ubOrdini = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubPACS = new UnicodeSrl.ScciCore.ucEasyButton();
            this.UltraPopupControlContainerSegnalibri = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.ultraTabPageControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTabControl)).BeginInit();
            this.ucEasyTabControl.SuspendLayout();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(784, 24);
                                                this.ultraTabPageControl1.Controls.Add(this.webBrowser);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(0, 0);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(709, 425);
                                                this.webBrowser.AllowWebBrowserDrop = false;
            this.webBrowser.Dock = System.Windows.Forms.DockStyle.Fill;
            this.webBrowser.Location = new System.Drawing.Point(0, 0);
            this.webBrowser.MinimumSize = new System.Drawing.Size(20, 20);
            this.webBrowser.Name = "webBrowser";
            this.webBrowser.Size = new System.Drawing.Size(709, 425);
            this.webBrowser.TabIndex = 0;
                                                this.ultraTabPageControl2.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl2.Name = "ultraTabPageControl2";
            this.ultraTabPageControl2.Size = new System.Drawing.Size(709, 427);
                                                this.ultraTabPageControl3.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl3.Name = "ultraTabPageControl3";
            this.ultraTabPageControl3.Size = new System.Drawing.Size(709, 427);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 24);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(784, 514);
            this.ultraGroupBox.TabIndex = 9;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 7;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 27F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 62F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 0.5F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 0.5F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblDataReferto, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblDataRefertoValore, 1, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTipoReferto, 3, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTipoRefertoValore, 3, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubPDF, 5, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubGrafico, 5, 9);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTabControl, 1, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.uchkVista, 5, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubOrdini, 5, 8);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubPACS, 5, 11);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 13;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(778, 508);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 20.37313F;
            appearance1.TextVAlignAsString = "Middle";
            this.lblDataReferto.Appearance = appearance1;
            this.lblDataReferto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataReferto.Location = new System.Drawing.Point(10, 8);
            this.lblDataReferto.Name = "lblDataReferto";
            this.lblDataReferto.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataReferto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataReferto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataReferto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataReferto.Size = new System.Drawing.Size(204, 19);
            this.lblDataReferto.TabIndex = 0;
            this.lblDataReferto.Text = "Data Referto:";
            this.lblDataReferto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance2.FontData.SizeInPoints = 25.07463F;
            appearance2.TextVAlignAsString = "Middle";
            this.lblDataRefertoValore.Appearance = appearance2;
            this.lblDataRefertoValore.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataRefertoValore.Location = new System.Drawing.Point(10, 33);
            this.lblDataRefertoValore.Name = "lblDataRefertoValore";
            this.lblDataRefertoValore.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataRefertoValore.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataRefertoValore.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataRefertoValore.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataRefertoValore.Size = new System.Drawing.Size(204, 24);
            this.lblDataRefertoValore.TabIndex = 0;
            this.lblDataRefertoValore.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance3.FontData.SizeInPoints = 20.37313F;
            appearance3.ForeColor = System.Drawing.Color.Red;
            appearance3.TextVAlignAsString = "Middle";
            this.lblTipoReferto.Appearance = appearance3;
            this.lblTipoReferto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTipoReferto.Location = new System.Drawing.Point(243, 8);
            this.lblTipoReferto.Name = "lblTipoReferto";
            this.lblTipoReferto.ShortcutColor = System.Drawing.Color.Black;
            this.lblTipoReferto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTipoReferto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTipoReferto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTipoReferto.Size = new System.Drawing.Size(476, 19);
            this.lblTipoReferto.TabIndex = 0;
            this.lblTipoReferto.Text = "Tipo Di Referto:";
            this.lblTipoReferto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblTipoReferto.Visible = false;
                                                appearance4.FontData.SizeInPoints = 25.07463F;
            appearance4.TextVAlignAsString = "Middle";
            this.lblTipoRefertoValore.Appearance = appearance4;
            this.lblTipoRefertoValore.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTipoRefertoValore.Location = new System.Drawing.Point(243, 33);
            this.lblTipoRefertoValore.Name = "lblTipoRefertoValore";
            this.lblTipoRefertoValore.ShortcutColor = System.Drawing.Color.Black;
            this.lblTipoRefertoValore.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTipoRefertoValore.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTipoRefertoValore.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTipoRefertoValore.Size = new System.Drawing.Size(476, 24);
            this.lblTipoRefertoValore.TabIndex = 0;
            this.lblTipoRefertoValore.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance5.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance5.ImageBackground")));
            appearance5.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance5.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance5.TextHAlignAsString = "Center";
            appearance5.TextVAlignAsString = "Bottom";
            this.ubPDF.Appearance = appearance5;
            this.ubPDF.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubPDF.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubPDF.Location = new System.Drawing.Point(728, 189);
            this.ubPDF.Name = "ubPDF";
            this.ubPDF.PercImageFill = 0.75F;
            this.ubPDF.ShortcutColor = System.Drawing.Color.Black;
            this.ubPDF.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubPDF.ShortcutKey = System.Windows.Forms.Keys.P;
            this.ubPDF.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubPDF.Size = new System.Drawing.Size(40, 44);
            this.ubPDF.TabIndex = 2;
            this.ubPDF.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubPDF.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubPDF.Click += new System.EventHandler(this.ubPDF_Click);
                                                appearance6.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance6.ImageBackground")));
            appearance6.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance6.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance6.TextHAlignAsString = "Center";
            appearance6.TextVAlignAsString = "Bottom";
            this.ubGrafico.Appearance = appearance6;
            this.ubGrafico.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubGrafico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubGrafico.Location = new System.Drawing.Point(728, 344);
            this.ubGrafico.Name = "ubGrafico";
            this.ubGrafico.PercImageFill = 0.75F;
            this.ubGrafico.ShortcutColor = System.Drawing.Color.Black;
            this.ubGrafico.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubGrafico.ShortcutKey = System.Windows.Forms.Keys.G;
            this.ubGrafico.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubGrafico.Size = new System.Drawing.Size(40, 44);
            this.ubGrafico.TabIndex = 3;
            this.ubGrafico.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubGrafico.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubGrafico.Click += new System.EventHandler(this.ubGrafico_Click);
                                                appearance7.ForeColor = System.Drawing.Color.CornflowerBlue;
            this.ucEasyTabControl.Appearance = appearance7;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTabControl, 3);
            this.ucEasyTabControl.Controls.Add(this.ultraTabSharedControlsPage1);
            this.ucEasyTabControl.Controls.Add(this.ultraTabPageControl1);
            this.ucEasyTabControl.Controls.Add(this.ultraTabPageControl2);
            this.ucEasyTabControl.Controls.Add(this.ultraTabPageControl3);
            this.ucEasyTabControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTabControl.Location = new System.Drawing.Point(10, 68);
            this.ucEasyTabControl.Name = "ucEasyTabControl";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.ucEasyTabControl, 8);
            appearance8.FontData.BoldAsString = "True";
            appearance8.ForeColor = System.Drawing.Color.MidnightBlue;
            this.ucEasyTabControl.SelectedTabAppearance = appearance8;
            this.ucEasyTabControl.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.ucEasyTabControl.Size = new System.Drawing.Size(709, 425);
            this.ucEasyTabControl.Style = Infragistics.Win.UltraWinTabControl.UltraTabControlStyle.Wizard;
            appearance9.FontData.SizeInPoints = 20.37313F;
            this.ucEasyTabControl.TabHeaderAreaAppearance = appearance9;
            this.ucEasyTabControl.TabIndex = 4;
            this.ucEasyTabControl.TabLayoutStyle = Infragistics.Win.UltraWinTabs.TabLayoutStyle.SingleRowSizeToFit;
            ultraTab4.Key = "tabDWH";
            ultraTab4.TabPage = this.ultraTabPageControl1;
            ultraTab4.Text = "";
            ultraTab5.Key = "tabLAB";
            ultraTab5.TabPage = this.ultraTabPageControl2;
            ultraTab5.Text = "";
            ultraTab6.Key = "tabRX";
            ultraTab6.TabPage = this.ultraTabPageControl3;
            ultraTab6.Text = "";
            this.ucEasyTabControl.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab4,
            ultraTab5,
            ultraTab6});
            this.ucEasyTabControl.TabSize = new System.Drawing.Size(0, 45);
            this.ucEasyTabControl.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyTabControl.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTabControl.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(709, 425);
                                                appearance10.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance10.ImageBackground")));
            appearance10.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance10.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance10.TextHAlignAsString = "Center";
            appearance10.TextVAlignAsString = "Bottom";
            this.uchkVista.Appearance = appearance10;
            this.uchkVista.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkVista.Checked = false;
            this.uchkVista.CheckedImage = null;
            this.uchkVista.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkVista.Location = new System.Drawing.Point(728, 68);
            this.uchkVista.Name = "uchkVista";
            this.uchkVista.PercImageFill = 0.75F;
            this.uchkVista.ShortcutColor = System.Drawing.Color.Black;
            this.uchkVista.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkVista.ShortcutKey = System.Windows.Forms.Keys.V;
            this.uchkVista.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkVista.Size = new System.Drawing.Size(40, 44);
            this.uchkVista.TabIndex = 5;
            this.uchkVista.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.uchkVista.UNCheckedImage = null;
            this.uchkVista.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance11.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance11.ImageBackground")));
            appearance11.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance11.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance11.TextHAlignAsString = "Center";
            appearance11.TextVAlignAsString = "Bottom";
            this.ubOrdini.Appearance = appearance11;
            this.ubOrdini.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubOrdini.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubOrdini.Location = new System.Drawing.Point(728, 294);
            this.ubOrdini.Name = "ubOrdini";
            this.ubOrdini.PercImageFill = 0.75F;
            this.ubOrdini.ShortcutColor = System.Drawing.Color.Black;
            this.ubOrdini.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubOrdini.ShortcutKey = System.Windows.Forms.Keys.O;
            this.ubOrdini.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubOrdini.Size = new System.Drawing.Size(40, 44);
            this.ubOrdini.TabIndex = 6;
            this.ubOrdini.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubOrdini.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubOrdini.Click += new System.EventHandler(this.ubOrdini_Click);
                                                appearance12.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance12.ImageBackground")));
            appearance12.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance12.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance12.TextHAlignAsString = "Center";
            appearance12.TextVAlignAsString = "Bottom";
            this.ubPACS.Appearance = appearance12;
            this.ubPACS.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubPACS.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubPACS.Location = new System.Drawing.Point(728, 449);
            this.ubPACS.Name = "ubPACS";
            this.ubPACS.PercImageFill = 0.75F;
            this.ubPACS.ShortcutColor = System.Drawing.Color.Black;
            this.ubPACS.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubPACS.ShortcutKey = System.Windows.Forms.Keys.I;
            this.ubPACS.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubPACS.Size = new System.Drawing.Size(40, 44);
            this.ubPACS.TabIndex = 3;
            this.ubPACS.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubPACS.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubPACS.Visible = false;
            this.ubPACS.Click += new System.EventHandler(this.ubPACS_Click);
                                                this.UltraPopupControlContainerSegnalibri.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerSegnalibri_Opening);
            this.UltraPopupControlContainerSegnalibri.Opened += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Opened);
            this.UltraPopupControlContainerSegnalibri.Closed += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmPUEvidenzaClinica";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUEvidenzaClinica";
            this.ImmagineClick += new UnicodeSrl.ScciCore.ImmagineTopClickHandler(this.frmPUEvidenzaClinica_ImmagineClick);
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUEvidenzaClinica_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUEvidenzaClinica_PulsanteAvantiClick);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmPUEvidenzaClinica_FormClosing);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            this.ultraTabPageControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTabControl)).EndInit();
            this.ucEasyTabControl.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyLabel lblDataReferto;
        private ucEasyLabel lblDataRefertoValore;
        private ucEasyLabel lblTipoReferto;
        private ucEasyLabel lblTipoRefertoValore;
        private ucEasyButton ubPDF;
        private ucEasyButton ubGrafico;
        private ucEasyTabControl ucEasyTabControl;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl2;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl3;
        private System.Windows.Forms.WebBrowser webBrowser;
        private ucEasyStateButton uchkVista;
        private ucEasyButton ubOrdini;
        private ucEasyButton ubPACS;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerSegnalibri;
    }
}