namespace UnicodeSrl.ScciCore
{
    partial class frmPUProtocolloAttivita
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton1 = new Infragistics.Win.UltraWinEditors.EditorButton("Orari");
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPUProtocolloAttivita));
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblDescProtocolloAttivita = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.udteDataOraInizio = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.ucEasyTableLayoutPanelGrid = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblElencoSomministrazioni = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.lblProtocollo = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblManuale = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyCheckEditorManuale = new UnicodeSrl.ScciCore.ucEasyCheckEditor();
            this.lblDataOraInizio = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.UltraPopupControlContainerSegnalibri = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.ultraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataOraInizio)).BeginInit();
            this.ucEasyTableLayoutPanelGrid.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyCheckEditorManuale)).BeginInit();
            this.SuspendLayout();
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 34);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(1182, 745);
            this.ultraGroupBox.TabIndex = 3;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 5;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblDescProtocolloAttivita, 2, 0);
            this.ucEasyTableLayoutPanel.Controls.Add(this.udteDataOraInizio, 2, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelGrid, 1, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblProtocollo, 1, 0);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblManuale, 1, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyCheckEditorManuale, 2, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblDataOraInizio, 1, 2);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 8;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(1176, 739);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 18.31978F;
            appearance1.ForeColor = System.Drawing.Color.Red;
            appearance1.TextVAlignAsString = "Middle";
            this.lblDescProtocolloAttivita.Appearance = appearance1;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblDescProtocolloAttivita, 2);
            this.lblDescProtocolloAttivita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDescProtocolloAttivita.Location = new System.Drawing.Point(366, 3);
            this.lblDescProtocolloAttivita.Name = "lblDescProtocolloAttivita";
            this.lblDescProtocolloAttivita.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDescProtocolloAttivita.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDescProtocolloAttivita.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDescProtocolloAttivita.Size = new System.Drawing.Size(792, 67);
            this.lblDescProtocolloAttivita.TabIndex = 15;
            this.lblDescProtocolloAttivita.Text = "Nome protocollo attività";
            this.lblDescProtocolloAttivita.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance2.FontData.SizeInPoints = 22.54743F;
            appearance2.TextHAlignAsString = "Center";
            this.udteDataOraInizio.Appearance = appearance2;
            this.udteDataOraInizio.AutoSize = false;
            appearance3.TextHAlignAsString = "Center";
            editorButton1.Appearance = appearance3;
            editorButton1.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2007RibbonButton;
            editorButton1.Key = "Orari";
            editorButton1.Text = "H";
            this.udteDataOraInizio.ButtonsRight.Add(editorButton1);
            this.udteDataOraInizio.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteDataOraInizio.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataOraInizio.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance4.FontData.SizeInPoints = 22.54743F;
            this.udteDataOraInizio.DropDownAppearance = appearance4;
            this.udteDataOraInizio.FormatString = "dd/MM/yyyy HH:mm";
            this.udteDataOraInizio.Location = new System.Drawing.Point(366, 83);
            this.udteDataOraInizio.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteDataOraInizio.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteDataOraInizio.Name = "udteDataOraInizio";
            this.udteDataOraInizio.Size = new System.Drawing.Size(346, 53);
            this.udteDataOraInizio.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataOraInizio.TabIndex = 14;
            this.udteDataOraInizio.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.udteDataOraInizio.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.udteDataOraInizio.ValueChanged += new System.EventHandler(this.udteDataOraInizio_ValueChanged);
                                                this.ucEasyTableLayoutPanelGrid.ColumnCount = 1;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelGrid, 3);
            this.ucEasyTableLayoutPanelGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelGrid.Controls.Add(this.lblElencoSomministrazioni, 0, 0);
            this.ucEasyTableLayoutPanelGrid.Controls.Add(this.ucEasyGrid, 0, 1);
            this.ucEasyTableLayoutPanelGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelGrid.Location = new System.Drawing.Point(14, 215);
            this.ucEasyTableLayoutPanelGrid.Name = "ucEasyTableLayoutPanelGrid";
            this.ucEasyTableLayoutPanelGrid.RowCount = 2;
            this.ucEasyTableLayoutPanelGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 85F));
            this.ucEasyTableLayoutPanelGrid.Size = new System.Drawing.Size(1144, 511);
            this.ucEasyTableLayoutPanelGrid.TabIndex = 13;
                                                appearance5.FontData.SizeInPoints = 18.31978F;
            appearance5.TextHAlignAsString = "Center";
            appearance5.TextVAlignAsString = "Middle";
            this.lblElencoSomministrazioni.Appearance = appearance5;
            this.lblElencoSomministrazioni.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblElencoSomministrazioni.Location = new System.Drawing.Point(3, 3);
            this.lblElencoSomministrazioni.Name = "lblElencoSomministrazioni";
            this.lblElencoSomministrazioni.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblElencoSomministrazioni.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblElencoSomministrazioni.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblElencoSomministrazioni.Size = new System.Drawing.Size(1138, 70);
            this.lblElencoSomministrazioni.TabIndex = 3;
            this.lblElencoSomministrazioni.Text = "Elenco task";
            this.lblElencoSomministrazioni.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblElencoSomministrazioni.Visible = false;
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance6.BackColor = System.Drawing.SystemColors.Window;
            appearance6.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance6;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance7.FontData.BoldAsString = "True";
            appearance7.FontData.SizeInPoints = 18.31978F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance7;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance8.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance8.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance8.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance8.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance8;
            appearance9.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance9;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance10.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance10.BackColor2 = System.Drawing.SystemColors.Control;
            appearance10.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance10.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance10;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance11;
            appearance12.BackColor = System.Drawing.SystemColors.Highlight;
            appearance12.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance12;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance13.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance13;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            appearance14.FontData.SizeInPoints = 12.68293F;
            appearance14.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance14;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance15.FontData.SizeInPoints = 18.31978F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance15;
            appearance16.BackColor = System.Drawing.SystemColors.Control;
            appearance16.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance16.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance16.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance16.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance16;
            appearance17.FontData.BoldAsString = "True";
            appearance17.FontData.SizeInPoints = 12.68293F;
            appearance17.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance17;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance18.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance18.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance18;
            appearance19.BackColor = System.Drawing.SystemColors.Window;
            appearance19.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance19;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance20.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance20;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(3, 79);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(1138, 429);
            this.ucEasyGrid.TabIndex = 2;
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
                                                appearance21.FontData.SizeInPoints = 22.54743F;
            appearance21.TextHAlignAsString = "Left";
            appearance21.TextVAlignAsString = "Middle";
            this.lblProtocollo.Appearance = appearance21;
            this.lblProtocollo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblProtocollo.Location = new System.Drawing.Point(11, 0);
            this.lblProtocollo.Margin = new System.Windows.Forms.Padding(0);
            this.lblProtocollo.Name = "lblProtocollo";
            this.lblProtocollo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblProtocollo.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblProtocollo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblProtocollo.Size = new System.Drawing.Size(352, 73);
            this.lblProtocollo.TabIndex = 12;
            this.lblProtocollo.Text = "Protocollo:";
            this.lblProtocollo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance22.FontData.SizeInPoints = 22.54743F;
            appearance22.TextHAlignAsString = "Left";
            appearance22.TextVAlignAsString = "Middle";
            this.lblManuale.Appearance = appearance22;
            this.lblManuale.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblManuale.Location = new System.Drawing.Point(11, 146);
            this.lblManuale.Margin = new System.Windows.Forms.Padding(0);
            this.lblManuale.Name = "lblManuale";
            this.lblManuale.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblManuale.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblManuale.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblManuale.Size = new System.Drawing.Size(352, 59);
            this.lblManuale.TabIndex = 11;
            this.lblManuale.Text = "Manuale:";
            this.lblManuale.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance23.BackColor = System.Drawing.Color.Transparent;
            appearance23.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance23.ImageBackground")));
            appearance23.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance23.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.ucEasyCheckEditorManuale.Appearance = appearance23;
            this.ucEasyCheckEditorManuale.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyCheckEditorManuale.BackColorInternal = System.Drawing.Color.Transparent;
            this.ucEasyCheckEditorManuale.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Borderless;
            appearance24.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance24.ImageBackground")));
            appearance24.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance24.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.ucEasyCheckEditorManuale.CheckedAppearance = appearance24;
            this.ucEasyCheckEditorManuale.Dock = System.Windows.Forms.DockStyle.Left;
            this.ucEasyCheckEditorManuale.Location = new System.Drawing.Point(366, 149);
            this.ucEasyCheckEditorManuale.Name = "ucEasyCheckEditorManuale";
            this.ucEasyCheckEditorManuale.Size = new System.Drawing.Size(83, 53);
            this.ucEasyCheckEditorManuale.Style = Infragistics.Win.EditCheckStyle.Button;
            this.ucEasyCheckEditorManuale.TabIndex = 10;
            this.ucEasyCheckEditorManuale.CheckedChanged += new System.EventHandler(this.ucEasyCheckEditorManuale_CheckedChanged);
                                                appearance25.FontData.SizeInPoints = 22.54743F;
            appearance25.TextHAlignAsString = "Left";
            appearance25.TextVAlignAsString = "Middle";
            this.lblDataOraInizio.Appearance = appearance25;
            this.lblDataOraInizio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataOraInizio.Location = new System.Drawing.Point(11, 80);
            this.lblDataOraInizio.Margin = new System.Windows.Forms.Padding(0);
            this.lblDataOraInizio.Name = "lblDataOraInizio";
            this.lblDataOraInizio.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblDataOraInizio.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataOraInizio.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataOraInizio.Size = new System.Drawing.Size(352, 59);
            this.lblDataOraInizio.TabIndex = 9;
            this.lblDataOraInizio.Text = "Data e Ora Inizio Protocollo: ";
            this.lblDataOraInizio.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                this.UltraPopupControlContainerSegnalibri.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerSegnalibri_Opening);
            this.UltraPopupControlContainerSegnalibri.Opened += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Opened);
            this.UltraPopupControlContainerSegnalibri.Closed += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Closed);
                                                appearance26.BorderColor = System.Drawing.Color.Black;
            this.ultraPopupControlContainer.DropDownResizeHandleAppearance = appearance26;
            this.ultraPopupControlContainer.Opened += new System.EventHandler(this.ultraPopupControlContainer_Opened);
            this.ultraPopupControlContainer.Closed += new System.EventHandler(this.ultraPopupControlContainer_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1182, 813);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmPUProtocolloAttivita";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUProtocolloAttivita";
            this.ImmagineClick += new UnicodeSrl.ScciCore.ImmagineTopClickHandler(this.frmPUTaskInfermieristici_ImmagineClick);
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUTaskInfermieristici_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUTaskInfermieristici_PulsanteAvantiClick);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteDataOraInizio)).EndInit();
            this.ucEasyTableLayoutPanelGrid.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyCheckEditorManuale)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerSegnalibri;
        private ucEasyLabel lblDataOraInizio;
        private ucEasyCheckEditor ucEasyCheckEditorManuale;
        private ucEasyLabel lblManuale;
        private ucEasyLabel lblProtocollo;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelGrid;
        private ucEasyLabel lblElencoSomministrazioni;
        private ucEasyGrid ucEasyGrid;
        private ucEasyDateTimeEditor udteDataOraInizio;
        private ucEasyLabel lblDescProtocolloAttivita;
        private Infragistics.Win.Misc.UltraPopupControlContainer ultraPopupControlContainer;
    }
}