namespace UnicodeSrl.ScciCore
{
    partial class frmPUAllegato
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmPUAllegato));
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton1 = new Infragistics.Win.UltraWinEditors.EditorButton("Sel");
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton2 = new Infragistics.Win.UltraWinEditors.EditorButton("Add");
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.tlpFirmaDigitale = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.uceFirmaDigitale = new UnicodeSrl.ScciCore.ucEasyCheckEditor();
            this.lblFirmaDigitale = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ubScanner = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyLabel2 = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyLabel1 = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utxtFolder = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblZoomTipoAllegato = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.udteDataEvento = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblDataEvento = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ubZoomTipo = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblDocumento = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblTesto = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblNota = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.rtfTesto = new UnicodeSrl.ScciCore.ucRichTextBox();
            this.rtfNota = new UnicodeSrl.ScciCore.ucRichTextBox();
            this.ubDocumento = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubRTFTesto = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubRTFNota = new UnicodeSrl.ScciCore.ucEasyButton();
            this.utxtDocumento = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblInfoRilevazione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.uceCodEntita = new UnicodeSrl.ScciCore.ucEasyComboEditor();
            this.printDialog = new System.Windows.Forms.PrintDialog();
            this.UltraPopupControlContainerSegnalibri = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.UltraPopupControlContainerFolder = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.UltraPopupControlContainerFolderAdd = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            this.tlpFirmaDigitale.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uceFirmaDigitale)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utxtFolder)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataEvento)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utxtDocumento)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uceCodEntita)).BeginInit();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(784, 24);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 24);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(784, 513);
            this.ultraGroupBox.TabIndex = 9;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 6;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 64F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.tlpFirmaDigitale, 3, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubScanner, 4, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyLabel2, 3, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyLabel1, 1, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.utxtFolder, 3, 7);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblZoomTipoAllegato, 3, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.udteDataEvento, 1, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblDataEvento, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubZoomTipo, 4, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblDocumento, 1, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblTesto, 1, 8);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblNota, 1, 11);
            this.ucEasyTableLayoutPanel.Controls.Add(this.rtfTesto, 1, 9);
            this.ucEasyTableLayoutPanel.Controls.Add(this.rtfNota, 1, 12);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubDocumento, 4, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubRTFTesto, 4, 9);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubRTFNota, 4, 12);
            this.ucEasyTableLayoutPanel.Controls.Add(this.utxtDocumento, 1, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblInfoRilevazione, 3, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.uceCodEntita, 1, 7);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 15;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(778, 507);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.tlpFirmaDigitale.ColumnCount = 2;
            this.tlpFirmaDigitale.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 64F));
            this.tlpFirmaDigitale.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpFirmaDigitale.Controls.Add(this.uceFirmaDigitale, 0, 0);
            this.tlpFirmaDigitale.Controls.Add(this.lblFirmaDigitale, 1, 0);
            this.tlpFirmaDigitale.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpFirmaDigitale.Location = new System.Drawing.Point(211, 73);
            this.tlpFirmaDigitale.Name = "tlpFirmaDigitale";
            this.tlpFirmaDigitale.RowCount = 1;
            this.tlpFirmaDigitale.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpFirmaDigitale.Size = new System.Drawing.Size(491, 24);
            this.tlpFirmaDigitale.TabIndex = 22;
                                                appearance1.BackColor = System.Drawing.Color.Transparent;
            appearance1.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance1.ImageBackground")));
            appearance1.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance1.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.uceFirmaDigitale.Appearance = appearance1;
            this.uceFirmaDigitale.BackColor = System.Drawing.Color.Transparent;
            this.uceFirmaDigitale.BackColorInternal = System.Drawing.Color.Transparent;
            this.uceFirmaDigitale.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Borderless;
            appearance2.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance2.ImageBackground")));
            appearance2.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance2.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.uceFirmaDigitale.CheckedAppearance = appearance2;
            this.uceFirmaDigitale.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uceFirmaDigitale.Location = new System.Drawing.Point(3, 3);
            this.uceFirmaDigitale.Name = "uceFirmaDigitale";
            this.uceFirmaDigitale.Size = new System.Drawing.Size(58, 18);
            this.uceFirmaDigitale.Style = Infragistics.Win.EditCheckStyle.Button;
            this.uceFirmaDigitale.TabIndex = 0;
                                                appearance3.FontData.SizeInPoints = 22.50746F;
            appearance3.TextVAlignAsString = "Middle";
            this.lblFirmaDigitale.Appearance = appearance3;
            this.lblFirmaDigitale.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFirmaDigitale.Location = new System.Drawing.Point(67, 3);
            this.lblFirmaDigitale.Name = "lblFirmaDigitale";
            this.lblFirmaDigitale.ShortcutColor = System.Drawing.Color.Black;
            this.lblFirmaDigitale.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFirmaDigitale.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFirmaDigitale.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFirmaDigitale.Size = new System.Drawing.Size(421, 18);
            this.lblFirmaDigitale.TabIndex = 1;
            this.lblFirmaDigitale.Text = "Firma Digitale";
            this.lblFirmaDigitale.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance4.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance4.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance4.TextHAlignAsString = "Center";
            appearance4.TextVAlignAsString = "Bottom";
            this.ubScanner.Appearance = appearance4;
            this.ubScanner.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubScanner.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubScanner.ImageSize = new System.Drawing.Size(40, 40);
            this.ubScanner.Location = new System.Drawing.Point(708, 133);
            this.ubScanner.Name = "ubScanner";
            this.ubScanner.PercImageFill = 0.75F;
            this.ucEasyTableLayoutPanel.SetRowSpan(this.ubScanner, 2);
            this.ubScanner.ShortcutColor = System.Drawing.Color.Black;
            this.ubScanner.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubScanner.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubScanner.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubScanner.Size = new System.Drawing.Size(56, 54);
            this.ubScanner.TabIndex = 18;
            this.ubScanner.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubScanner.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubScanner.Click += new System.EventHandler(this.ubScanner_Click);
                                                appearance5.FontData.SizeInPoints = 22.50746F;
            appearance5.TextVAlignAsString = "Bottom";
            this.ucEasyLabel2.Appearance = appearance5;
            this.ucEasyLabel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabel2.Location = new System.Drawing.Point(211, 133);
            this.ucEasyLabel2.Name = "ucEasyLabel2";
            this.ucEasyLabel2.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyLabel2.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabel2.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabel2.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabel2.Size = new System.Drawing.Size(491, 24);
            this.ucEasyLabel2.TabIndex = 17;
            this.ucEasyLabel2.Text = "Archivia in:";
            this.ucEasyLabel2.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance6.FontData.SizeInPoints = 22.50746F;
            appearance6.TextVAlignAsString = "Bottom";
            this.ucEasyLabel1.Appearance = appearance6;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyLabel1, 2);
            this.ucEasyLabel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabel1.Location = new System.Drawing.Point(10, 133);
            this.ucEasyLabel1.Name = "ucEasyLabel1";
            this.ucEasyLabel1.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyLabel1.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabel1.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabel1.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabel1.Size = new System.Drawing.Size(195, 24);
            this.ucEasyLabel1.TabIndex = 16;
            this.ucEasyLabel1.Text = "Associa a:";
            this.ucEasyLabel1.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance7.FontData.SizeInPoints = 22.50746F;
            this.utxtFolder.Appearance = appearance7;
            this.utxtFolder.AutoSize = false;
            appearance8.FontData.SizeInPoints = 20F;
            appearance8.TextHAlignAsString = "Center";
            editorButton1.Appearance = appearance8;
            editorButton1.Key = "Sel";
            editorButton1.Text = "";
            editorButton1.Width = 40;
            appearance9.FontData.SizeInPoints = 20F;
            appearance9.TextHAlignAsString = "Center";
            editorButton2.Appearance = appearance9;
            editorButton2.Key = "Add";
            editorButton2.Text = "";
            editorButton2.Width = 40;
            this.utxtFolder.ButtonsRight.Add(editorButton1);
            this.utxtFolder.ButtonsRight.Add(editorButton2);
            this.utxtFolder.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtFolder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtFolder.Location = new System.Drawing.Point(211, 163);
            this.utxtFolder.Name = "utxtFolder";
            this.utxtFolder.ReadOnly = true;
            this.utxtFolder.Size = new System.Drawing.Size(491, 24);
            this.utxtFolder.TabIndex = 14;
            this.utxtFolder.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.utxtFolder.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.utxtFolder.EditorButtonClick += new Infragistics.Win.UltraWinEditors.EditorButtonEventHandler(this.utxtFolder_EditorButtonClick);
                                                appearance10.FontData.SizeInPoints = 27.70149F;
            appearance10.TextVAlignAsString = "Middle";
            this.lblZoomTipoAllegato.Appearance = appearance10;
            this.lblZoomTipoAllegato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblZoomTipoAllegato.Location = new System.Drawing.Point(211, 38);
            this.lblZoomTipoAllegato.Name = "lblZoomTipoAllegato";
            this.lblZoomTipoAllegato.ShortcutColor = System.Drawing.Color.Black;
            this.lblZoomTipoAllegato.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblZoomTipoAllegato.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblZoomTipoAllegato.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblZoomTipoAllegato.Size = new System.Drawing.Size(491, 24);
            this.lblZoomTipoAllegato.TabIndex = 8;
            this.lblZoomTipoAllegato.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                appearance11.FontData.SizeInPoints = 27.70149F;
            this.udteDataEvento.Appearance = appearance11;
            this.udteDataEvento.AutoSize = false;
            this.udteDataEvento.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataEvento.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance12.FontData.SizeInPoints = 27.70149F;
            this.udteDataEvento.DropDownAppearance = appearance12;
            this.udteDataEvento.FormatString = "dd/MM/yyyy HH:mm";
            this.udteDataEvento.Location = new System.Drawing.Point(10, 38);
            this.udteDataEvento.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteDataEvento.Name = "udteDataEvento";
            this.udteDataEvento.Size = new System.Drawing.Size(188, 24);
            this.udteDataEvento.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataEvento.TabIndex = 0;
            this.udteDataEvento.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.udteDataEvento.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance13.FontData.SizeInPoints = 22.50746F;
            appearance13.TextVAlignAsString = "Middle";
            this.lblDataEvento.Appearance = appearance13;
            this.lblDataEvento.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataEvento.Location = new System.Drawing.Point(10, 8);
            this.lblDataEvento.Name = "lblDataEvento";
            this.lblDataEvento.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataEvento.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataEvento.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataEvento.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataEvento.Size = new System.Drawing.Size(188, 24);
            this.lblDataEvento.TabIndex = 6;
            this.lblDataEvento.Text = "Data Riferimento:";
            this.lblDataEvento.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance14.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance14.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance14.TextHAlignAsString = "Center";
            appearance14.TextVAlignAsString = "Bottom";
            this.ubZoomTipo.Appearance = appearance14;
            this.ubZoomTipo.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubZoomTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubZoomTipo.Location = new System.Drawing.Point(708, 38);
            this.ubZoomTipo.Name = "ubZoomTipo";
            this.ubZoomTipo.PercImageFill = 0.75F;
            this.ubZoomTipo.ShortcutColor = System.Drawing.Color.Black;
            this.ubZoomTipo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubZoomTipo.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubZoomTipo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubZoomTipo.Size = new System.Drawing.Size(56, 24);
            this.ubZoomTipo.TabIndex = 1;
            this.ubZoomTipo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubZoomTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubZoomTipo.Click += new System.EventHandler(this.ubZoomTipo_Click);
                                                appearance15.FontData.SizeInPoints = 22.50746F;
            appearance15.TextVAlignAsString = "Bottom";
            this.lblDocumento.Appearance = appearance15;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblDocumento, 2);
            this.lblDocumento.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDocumento.Location = new System.Drawing.Point(10, 73);
            this.lblDocumento.Name = "lblDocumento";
            this.lblDocumento.ShortcutColor = System.Drawing.Color.Black;
            this.lblDocumento.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDocumento.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDocumento.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDocumento.Size = new System.Drawing.Size(195, 24);
            this.lblDocumento.TabIndex = 10;
            this.lblDocumento.Text = "Documento:";
            this.lblDocumento.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance16.FontData.SizeInPoints = 22.50746F;
            appearance16.TextVAlignAsString = "Bottom";
            this.lblTesto.Appearance = appearance16;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblTesto, 2);
            this.lblTesto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTesto.Location = new System.Drawing.Point(10, 193);
            this.lblTesto.Name = "lblTesto";
            this.lblTesto.ShortcutColor = System.Drawing.Color.Black;
            this.lblTesto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTesto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTesto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTesto.Size = new System.Drawing.Size(195, 24);
            this.lblTesto.TabIndex = 11;
            this.lblTesto.Text = "Titolo:";
            this.lblTesto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance17.FontData.SizeInPoints = 22.50746F;
            appearance17.TextVAlignAsString = "Bottom";
            this.lblNota.Appearance = appearance17;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblNota, 2);
            this.lblNota.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNota.Location = new System.Drawing.Point(10, 333);
            this.lblNota.Name = "lblNota";
            this.lblNota.ShortcutColor = System.Drawing.Color.Black;
            this.lblNota.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblNota.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblNota.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblNota.Size = new System.Drawing.Size(195, 24);
            this.lblNota.TabIndex = 12;
            this.lblNota.Text = "Nota:";
            this.lblNota.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucEasyTableLayoutPanel.SetColumnSpan(this.rtfTesto, 3);
            this.rtfTesto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rtfTesto.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtfTesto.Location = new System.Drawing.Point(10, 223);
            this.rtfTesto.Name = "rtfTesto";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.rtfTesto, 2);
            this.rtfTesto.Size = new System.Drawing.Size(692, 104);
            this.rtfTesto.TabIndex = 4;
            this.rtfTesto.ViewFont = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtfTesto.ViewReadOnly = false;
            this.rtfTesto.ViewRtf = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\nouicompat\\deflang1040{\\fonttbl{\\f0\\fnil\\fcharset0 " +
    "Tahoma;}}\r\n{\\*\\generator Riched20 6.3.9600}\\viewkind4\\uc1 \r\n\\pard\\f0\\fs17\\par\r\n}" +
    "\r\n";
            this.rtfTesto.ViewShowInsertImage = true;
            this.rtfTesto.ViewShowPlainText = true;
            this.rtfTesto.ViewShowToolbar = true;
            this.rtfTesto.ViewText = "";
            this.rtfTesto.ViewToolbarStyle = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
            this.rtfTesto.ViewUseLargeImages = false;
                                                this.ucEasyTableLayoutPanel.SetColumnSpan(this.rtfNota, 3);
            this.rtfNota.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rtfNota.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtfNota.Location = new System.Drawing.Point(10, 363);
            this.rtfNota.Name = "rtfNota";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.rtfNota, 2);
            this.rtfNota.Size = new System.Drawing.Size(692, 130);
            this.rtfNota.TabIndex = 6;
            this.rtfNota.ViewFont = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.rtfNota.ViewReadOnly = false;
            this.rtfNota.ViewRtf = "{\\rtf1\\ansi\\ansicpg1252\\deff0\\nouicompat\\deflang1040{\\fonttbl{\\f0\\fnil\\fcharset0 " +
    "Tahoma;}}\r\n{\\*\\generator Riched20 6.3.9600}\\viewkind4\\uc1 \r\n\\pard\\f0\\fs17\\par\r\n}" +
    "\r\n";
            this.rtfNota.ViewShowInsertImage = true;
            this.rtfNota.ViewShowPlainText = true;
            this.rtfNota.ViewShowToolbar = true;
            this.rtfNota.ViewText = "";
            this.rtfNota.ViewToolbarStyle = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
            this.rtfNota.ViewUseLargeImages = false;
                                                appearance18.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance18.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance18.TextHAlignAsString = "Center";
            appearance18.TextVAlignAsString = "Bottom";
            this.ubDocumento.Appearance = appearance18;
            this.ubDocumento.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubDocumento.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubDocumento.Location = new System.Drawing.Point(708, 73);
            this.ubDocumento.Name = "ubDocumento";
            this.ubDocumento.PercImageFill = 0.75F;
            this.ucEasyTableLayoutPanel.SetRowSpan(this.ubDocumento, 2);
            this.ubDocumento.ShortcutColor = System.Drawing.Color.Black;
            this.ubDocumento.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubDocumento.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubDocumento.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubDocumento.Size = new System.Drawing.Size(56, 54);
            this.ubDocumento.TabIndex = 3;
            this.ubDocumento.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubDocumento.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubDocumento.Click += new System.EventHandler(this.ubDocumento_Click);
                                                appearance19.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance19.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance19.TextHAlignAsString = "Center";
            appearance19.TextVAlignAsString = "Bottom";
            this.ubRTFTesto.Appearance = appearance19;
            this.ubRTFTesto.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubRTFTesto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRTFTesto.Location = new System.Drawing.Point(708, 223);
            this.ubRTFTesto.Name = "ubRTFTesto";
            this.ubRTFTesto.PercImageFill = 0.75F;
            this.ubRTFTesto.ShortcutColor = System.Drawing.Color.Black;
            this.ubRTFTesto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubRTFTesto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubRTFTesto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubRTFTesto.Size = new System.Drawing.Size(56, 54);
            this.ubRTFTesto.TabIndex = 5;
            this.ubRTFTesto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubRTFTesto.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubRTFTesto.Click += new System.EventHandler(this.ubRTFTesto_Click);
                                                appearance20.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance20.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance20.TextHAlignAsString = "Center";
            appearance20.TextVAlignAsString = "Bottom";
            this.ubRTFNota.Appearance = appearance20;
            this.ubRTFNota.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubRTFNota.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRTFNota.Location = new System.Drawing.Point(708, 363);
            this.ubRTFNota.Name = "ubRTFNota";
            this.ubRTFNota.PercImageFill = 0.75F;
            this.ubRTFNota.ShortcutColor = System.Drawing.Color.Black;
            this.ubRTFNota.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubRTFNota.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubRTFNota.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubRTFNota.Size = new System.Drawing.Size(56, 49);
            this.ubRTFNota.TabIndex = 7;
            this.ubRTFNota.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubRTFNota.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubRTFNota.Click += new System.EventHandler(this.ubRTFNota_Click);
                                                appearance21.FontData.SizeInPoints = 27.70149F;
            this.utxtDocumento.Appearance = appearance21;
            this.utxtDocumento.AutoSize = false;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.utxtDocumento, 3);
            this.utxtDocumento.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtDocumento.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtDocumento.Location = new System.Drawing.Point(10, 103);
            this.utxtDocumento.Name = "utxtDocumento";
            this.utxtDocumento.Size = new System.Drawing.Size(692, 24);
            this.utxtDocumento.TabIndex = 2;
            this.utxtDocumento.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.utxtDocumento.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance22.FontData.SizeInPoints = 15.58209F;
            appearance22.TextHAlignAsString = "Right";
            appearance22.TextVAlignAsString = "Top";
            this.lblInfoRilevazione.Appearance = appearance22;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.lblInfoRilevazione, 2);
            this.lblInfoRilevazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblInfoRilevazione.Location = new System.Drawing.Point(211, 8);
            this.lblInfoRilevazione.Name = "lblInfoRilevazione";
            this.lblInfoRilevazione.ShortcutColor = System.Drawing.Color.Black;
            this.lblInfoRilevazione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblInfoRilevazione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblInfoRilevazione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblInfoRilevazione.Size = new System.Drawing.Size(553, 24);
            this.lblInfoRilevazione.TabIndex = 13;
            this.lblInfoRilevazione.Text = "info rilevazione..";
            this.lblInfoRilevazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance23.FontData.SizeInPoints = 22.50746F;
            this.uceCodEntita.Appearance = appearance23;
            this.uceCodEntita.AutoSize = false;
            this.uceCodEntita.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uceCodEntita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uceCodEntita.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.uceCodEntita.Location = new System.Drawing.Point(10, 163);
            this.uceCodEntita.Name = "uceCodEntita";
            this.uceCodEntita.Size = new System.Drawing.Size(188, 24);
            this.uceCodEntita.TabIndex = 15;
            this.uceCodEntita.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.uceCodEntita.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uceCodEntita.ValueChanged += new System.EventHandler(this.uceCodEntita_ValueChanged);
                                                this.printDialog.UseEXDialog = true;
                                                this.UltraPopupControlContainerSegnalibri.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerSegnalibri_Opening);
            this.UltraPopupControlContainerSegnalibri.Opened += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Opened);
            this.UltraPopupControlContainerSegnalibri.Closed += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Closed);
                                                this.UltraPopupControlContainerFolder.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerFolder_Opening);
            this.UltraPopupControlContainerFolder.Opened += new System.EventHandler(this.UltraPopupControlContainerFolder_Opened);
            this.UltraPopupControlContainerFolder.Closed += new System.EventHandler(this.UltraPopupControlContainerFolder_Closed);
                                                this.UltraPopupControlContainerFolderAdd.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerFolderAdd_Opening);
            this.UltraPopupControlContainerFolderAdd.Opened += new System.EventHandler(this.UltraPopupControlContainerFolderAdd_Opened);
            this.UltraPopupControlContainerFolderAdd.Closed += new System.EventHandler(this.UltraPopupControlContainerFolderAdd_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 561);
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "frmPUAllegato";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmPUAllegato";
            this.ImmagineClick += new UnicodeSrl.ScciCore.ImmagineTopClickHandler(this.frmPUAllegato_ImmagineClick);
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUAllegato_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmPUAllegato_PulsanteAvantiClick);
            this.Controls.SetChildIndex(this.ultraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            this.tlpFirmaDigitale.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.uceFirmaDigitale)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utxtFolder)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataEvento)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utxtDocumento)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uceCodEntita)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyLabel lblZoomTipoAllegato;
        private ucEasyDateTimeEditor udteDataEvento;
        private ucEasyLabel lblDataEvento;
        private ucEasyButton ubZoomTipo;
        private ucEasyLabel lblDocumento;
        private ucEasyLabel lblTesto;
        private ucEasyLabel lblNota;
        private ucRichTextBox rtfTesto;
        private ucRichTextBox rtfNota;
        private ucEasyButton ubDocumento;
        private ucEasyButton ubRTFTesto;
        private ucEasyButton ubRTFNota;
        private ucEasyTextBox utxtDocumento;
        private ucEasyLabel lblInfoRilevazione;
        private System.Windows.Forms.PrintDialog printDialog;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerSegnalibri;
        private ucEasyTextBox utxtFolder;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerFolder;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerFolderAdd;
        private ucEasyComboEditor uceCodEntita;
        private ucEasyLabel ucEasyLabel2;
        private ucEasyLabel ucEasyLabel1;
        private ucEasyButton ubScanner;
        private ucEasyTableLayoutPanel tlpFirmaDigitale;
        private ucEasyCheckEditor uceFirmaDigitale;
        private ucEasyLabel lblFirmaDigitale;
    }
}