namespace UnicodeSrl.ScciCore
{
    partial class frmSelezionaAgendeDisponibilita
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmSelezionaAgendeDisponibilita));
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem3 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem4 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem5 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.TableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.UltraGridDate = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.UltraDayView = new Infragistics.Win.UltraWinSchedule.UltraDayView();
            this.UltraCalendarInfo = new Infragistics.Win.UltraWinSchedule.UltraCalendarInfo(this.components);
            this.UltraCalendarLook = new Infragistics.Win.UltraWinSchedule.UltraCalendarLook(this.components);
            this.ubTrovaDisp = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblAgenda = new UnicodeSrl.ScciCore.ucEasyLabelHeader();
            this.ucEasyTableLayoutPanelTop = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblMinuti = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblFiltroDataA = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblFiltroDataDa = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.udtFiltroDataA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.udtFiltroDataDa = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.ucEasyDateRange = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.ucENEMinuti = new UnicodeSrl.ScciCore.ucEasyNumericEditor();
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.UltraPopupControlContainerSegnalibri = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridDate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraDayView)).BeginInit();
            this.ucEasyTableLayoutPanelTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udtFiltroDataA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udtFiltroDataDa)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyDateRange)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucENEMinuti)).BeginInit();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(1008, 31);
                                                this.UltraGroupBox.Controls.Add(this.TableLayoutPanel);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 31);
            this.UltraGroupBox.Margin = new System.Windows.Forms.Padding(0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(1008, 668);
            this.UltraGroupBox.TabIndex = 1;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.TableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanel.ColumnCount = 5;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 56F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.Controls.Add(this.UltraGridDate, 1, 4);
            this.TableLayoutPanel.Controls.Add(this.UltraDayView, 3, 4);
            this.TableLayoutPanel.Controls.Add(this.ubTrovaDisp, 1, 3);
            this.TableLayoutPanel.Controls.Add(this.lblAgenda, 3, 3);
            this.TableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelTop, 1, 1);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 6;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 83F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(1002, 662);
            this.TableLayoutPanel.TabIndex = 1;
                                                this.UltraGridDate.ColonnaRTFControlloContenuto = false;
            this.UltraGridDate.ColonnaRTFResize = "";
            this.UltraGridDate.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridDate.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridDate.DisplayLayout.Appearance = appearance1;
            this.UltraGridDate.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridDate.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance2.FontData.BoldAsString = "True";
            appearance2.FontData.SizeInPoints = 15.71642F;
            this.UltraGridDate.DisplayLayout.CaptionAppearance = appearance2;
            this.UltraGridDate.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance3.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance3.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance3.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridDate.DisplayLayout.GroupByBox.Appearance = appearance3;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridDate.DisplayLayout.GroupByBox.BandLabelAppearance = appearance4;
            this.UltraGridDate.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridDate.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridDate.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance5.BackColor2 = System.Drawing.SystemColors.Control;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridDate.DisplayLayout.GroupByBox.PromptAppearance = appearance5;
            this.UltraGridDate.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridDate.DisplayLayout.MaxRowScrollRegions = 1;
            appearance6.BackColor = System.Drawing.SystemColors.Window;
            appearance6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridDate.DisplayLayout.Override.ActiveCellAppearance = appearance6;
            appearance7.BackColor = System.Drawing.SystemColors.Highlight;
            appearance7.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridDate.DisplayLayout.Override.ActiveRowAppearance = appearance7;
            this.UltraGridDate.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridDate.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridDate.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDate.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDate.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDate.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridDate.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridDate.DisplayLayout.Override.CardAreaAppearance = appearance8;
            appearance9.BorderColor = System.Drawing.Color.Silver;
            appearance9.FontData.SizeInPoints = 15.71642F;
            appearance9.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridDate.DisplayLayout.Override.CellAppearance = appearance9;
            this.UltraGridDate.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridDate.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridDate.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance10.FontData.SizeInPoints = 15.71642F;
            this.UltraGridDate.DisplayLayout.Override.FilterRowAppearance = appearance10;
            appearance11.BackColor = System.Drawing.SystemColors.Control;
            appearance11.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance11.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance11.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance11.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridDate.DisplayLayout.Override.GroupByRowAppearance = appearance11;
            appearance12.FontData.BoldAsString = "True";
            appearance12.FontData.SizeInPoints = 15.71642F;
            appearance12.TextHAlignAsString = "Center";
            this.UltraGridDate.DisplayLayout.Override.HeaderAppearance = appearance12;
            this.UltraGridDate.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridDate.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance13.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance13.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridDate.DisplayLayout.Override.RowAlternateAppearance = appearance13;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridDate.DisplayLayout.Override.RowAppearance = appearance14;
            this.UltraGridDate.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDate.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridDate.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridDate.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance15.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridDate.DisplayLayout.Override.TemplateAddRowAppearance = appearance15;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridDate.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.UltraGridDate.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridDate.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridDate.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridDate.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridDate.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridDate.FattoreRidimensionamentoRTF = 21;
            this.UltraGridDate.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridDate.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridDate.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridDate.Location = new System.Drawing.Point(13, 106);
            this.UltraGridDate.Name = "UltraGridDate";
            this.UltraGridDate.ShowFilterRow = false;
            this.UltraGridDate.ShowGroupByBox = false;
            this.UltraGridDate.Size = new System.Drawing.Size(394, 543);
            this.UltraGridDate.TabIndex = 0;
            this.UltraGridDate.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridDate.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDate.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridDate_InitializeLayout);
            this.UltraGridDate.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGridDate_InitializeRow);
            this.UltraGridDate.AfterRowActivate += new System.EventHandler(this.UltraGridDate_AfterRowActivate);
                                                this.UltraDayView.CalendarInfo = this.UltraCalendarInfo;
            this.UltraDayView.CalendarLook = this.UltraCalendarLook;
            this.UltraDayView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraDayView.Location = new System.Drawing.Point(433, 106);
            this.UltraDayView.Name = "UltraDayView";
            this.UltraDayView.Size = new System.Drawing.Size(555, 543);
            this.UltraDayView.TabIndex = 0;
            this.UltraDayView.Text = "ultraDayView1";
            this.UltraDayView.Visible = false;
            this.UltraDayView.BeforeTimeSlotSelectionChanged += new Infragistics.Win.UltraWinSchedule.BeforeTimeSlotSelectionChangedEventHandler(this.UltraDayView_BeforeTimeSlotSelectionChanged);
            this.UltraDayView.Click += new System.EventHandler(this.UltraView_Click);
            this.UltraDayView.KeyDown += new System.Windows.Forms.KeyEventHandler(this.UltraDayView_KeyDown);
                                                this.UltraCalendarInfo.DataBindingsForAppointments.BindingContextControl = this;
            this.UltraCalendarInfo.DataBindingsForOwners.BindingContextControl = this;
            this.UltraCalendarInfo.AfterActiveDayChanged += new Infragistics.Win.UltraWinSchedule.AfterActiveDayChangedEventHandler(this.UltraCalendarInfo_AfterActiveDayChanged);
            this.UltraCalendarInfo.AppointmentDataInitialized += new Infragistics.Win.UltraWinSchedule.AppointmentDataInitializedEventHandler(this.UltraCalendarInfo_AppointmentDataInitialized);
            this.UltraCalendarInfo.OwnerDataInitialized += new Infragistics.Win.UltraWinSchedule.OwnerDataInitializedEventHandler(this.UltraCalendarInfo_OwnerDataInitialized);
                                                appearance16.FontData.SizeInPoints = 22.70149F;
            appearance16.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance16.ImageBackground")));
            appearance16.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance16.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance16.TextHAlignAsString = "Center";
            appearance16.TextVAlignAsString = "Middle";
            this.ubTrovaDisp.Appearance = appearance16;
            this.ubTrovaDisp.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubTrovaDisp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubTrovaDisp.Location = new System.Drawing.Point(13, 54);
            this.ubTrovaDisp.Name = "ubTrovaDisp";
            this.ubTrovaDisp.PercImageFill = 0.75F;
            this.ubTrovaDisp.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubTrovaDisp.ShortcutKey = System.Windows.Forms.Keys.D;
            this.ubTrovaDisp.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubTrovaDisp.Size = new System.Drawing.Size(394, 46);
            this.ubTrovaDisp.TabIndex = 1;
            this.ubTrovaDisp.Text = "Trova Disponibilità";
            this.ubTrovaDisp.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubTrovaDisp.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubTrovaDisp.Click += new System.EventHandler(this.ubTrovaDisp_Click);
                                                appearance17.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(217)))), ((int)(((byte)(240)))));
            appearance17.FontData.SizeInPoints = 22.70149F;
            appearance17.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(65)))), ((int)(((byte)(158)))));
            appearance17.TextVAlignAsString = "Middle";
            this.lblAgenda.Appearance = appearance17;
            this.lblAgenda.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAgenda.Location = new System.Drawing.Point(433, 54);
            this.lblAgenda.Name = "lblAgenda";
            this.lblAgenda.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblAgenda.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblAgenda.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblAgenda.Size = new System.Drawing.Size(555, 46);
            this.lblAgenda.TabIndex = 2;
            this.lblAgenda.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucEasyTableLayoutPanelTop.ColumnCount = 7;
            this.TableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelTop, 3);
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 23F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.lblMinuti, 5, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.lblFiltroDataA, 3, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.lblFiltroDataDa, 1, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.udtFiltroDataA, 4, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.udtFiltroDataDa, 2, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyDateRange, 0, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucENEMinuti, 6, 0);
            this.ucEasyTableLayoutPanelTop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelTop.Location = new System.Drawing.Point(13, 9);
            this.ucEasyTableLayoutPanelTop.Name = "ucEasyTableLayoutPanelTop";
            this.ucEasyTableLayoutPanelTop.RowCount = 1;
            this.ucEasyTableLayoutPanelTop.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelTop.Size = new System.Drawing.Size(975, 33);
            this.ucEasyTableLayoutPanelTop.TabIndex = 3;
                                                appearance18.FontData.SizeInPoints = 22.70149F;
            appearance18.TextHAlignAsString = "Right";
            appearance18.TextVAlignAsString = "Middle";
            this.lblMinuti.Appearance = appearance18;
            this.lblMinuti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMinuti.Location = new System.Drawing.Point(654, 3);
            this.lblMinuti.Name = "lblMinuti";
            this.lblMinuti.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblMinuti.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblMinuti.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblMinuti.Size = new System.Drawing.Size(218, 27);
            this.lblMinuti.TabIndex = 13;
            this.lblMinuti.Text = "Minuti:";
            this.lblMinuti.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance19.FontData.SizeInPoints = 22.70149F;
            appearance19.TextHAlignAsString = "Right";
            appearance19.TextVAlignAsString = "Middle";
            this.lblFiltroDataA.Appearance = appearance19;
            this.lblFiltroDataA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDataA.Location = new System.Drawing.Point(431, 3);
            this.lblFiltroDataA.Name = "lblFiltroDataA";
            this.lblFiltroDataA.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDataA.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDataA.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDataA.Size = new System.Drawing.Size(42, 27);
            this.lblFiltroDataA.TabIndex = 12;
            this.lblFiltroDataA.Text = "A:";
            this.lblFiltroDataA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance20.FontData.SizeInPoints = 22.70149F;
            appearance20.TextHAlignAsString = "Right";
            appearance20.TextVAlignAsString = "Middle";
            this.lblFiltroDataDa.Appearance = appearance20;
            this.lblFiltroDataDa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDataDa.Location = new System.Drawing.Point(178, 3);
            this.lblFiltroDataDa.Name = "lblFiltroDataDa";
            this.lblFiltroDataDa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDataDa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDataDa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDataDa.Size = new System.Drawing.Size(72, 27);
            this.lblFiltroDataDa.TabIndex = 11;
            this.lblFiltroDataDa.Text = "Da:";
            this.lblFiltroDataDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance21.FontData.SizeInPoints = 22.70149F;
            this.udtFiltroDataA.Appearance = appearance21;
            this.udtFiltroDataA.AutoSize = false;
            this.udtFiltroDataA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udtFiltroDataA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance22.FontData.SizeInPoints = 22.70149F;
            this.udtFiltroDataA.DropDownAppearance = appearance22;
            this.udtFiltroDataA.FormatString = "dd/MM/yyyy";
            this.udtFiltroDataA.Location = new System.Drawing.Point(479, 3);
            this.udtFiltroDataA.MaskInput = "{LOC}dd/mm/yyyy";
            this.udtFiltroDataA.Name = "udtFiltroDataA";
            this.udtFiltroDataA.Nullable = false;
            this.udtFiltroDataA.Size = new System.Drawing.Size(169, 27);
            this.udtFiltroDataA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udtFiltroDataA.TabIndex = 10;
            this.udtFiltroDataA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.udtFiltroDataA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.udtFiltroDataA.ValueChanged += new System.EventHandler(this.udtFiltroData_ValueChanged);
                                                appearance23.FontData.SizeInPoints = 22.70149F;
            this.udtFiltroDataDa.Appearance = appearance23;
            this.udtFiltroDataDa.AutoSize = false;
            this.udtFiltroDataDa.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udtFiltroDataDa.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance24.FontData.SizeInPoints = 22.70149F;
            this.udtFiltroDataDa.DropDownAppearance = appearance24;
            this.udtFiltroDataDa.FormatString = "dd/MM/yyyy";
            this.udtFiltroDataDa.Location = new System.Drawing.Point(256, 3);
            this.udtFiltroDataDa.MaskInput = "{LOC}dd/mm/yyyy";
            this.udtFiltroDataDa.Name = "udtFiltroDataDa";
            this.udtFiltroDataDa.Nullable = false;
            this.udtFiltroDataDa.Size = new System.Drawing.Size(169, 27);
            this.udtFiltroDataDa.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udtFiltroDataDa.TabIndex = 9;
            this.udtFiltroDataDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.udtFiltroDataDa.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.udtFiltroDataDa.ValueChanged += new System.EventHandler(this.udtFiltroData_ValueChanged);
                                                appearance25.FontData.SizeInPoints = 22.70149F;
            this.ucEasyDateRange.Appearance = appearance25;
            this.ucEasyDateRange.AutoSize = false;
            this.ucEasyDateRange.DataEpisodio = new System.DateTime(((long)(0)));
            this.ucEasyDateRange.DateFuture = false;
            this.ucEasyDateRange.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.ucEasyDateRange.DisponibilitaAgende = true;
            this.ucEasyDateRange.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyDateRange.Domani = false;
            this.ucEasyDateRange.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem1.DisplayText = " ";
            valueListItem2.DataValue = "N1M";
            valueListItem2.DisplayText = "Prossimo Mese";
            valueListItem3.DataValue = "N6M";
            valueListItem3.DisplayText = "Prossimi 6 Mesi";
            valueListItem4.DataValue = "N1Y";
            valueListItem4.DisplayText = "Prossimo Anno";
            valueListItem5.DataValue = "N5Y";
            valueListItem5.DisplayText = "Prossimi 5 Anni";
            this.ucEasyDateRange.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2,
            valueListItem3,
            valueListItem4,
            valueListItem5});
            this.ucEasyDateRange.Location = new System.Drawing.Point(3, 3);
            this.ucEasyDateRange.Name = "ucEasyDateRange";
            this.ucEasyDateRange.Size = new System.Drawing.Size(169, 27);
            this.ucEasyDateRange.TabIndex = 8;
            this.ucEasyDateRange.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyDateRange.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyDateRange.ValueChanged += new System.EventHandler(this.ucEasyDateRange_ValueChanged);
                                                appearance26.FontData.SizeInPoints = 22.70149F;
            this.ucENEMinuti.Appearance = appearance26;
            this.ucENEMinuti.AutoSize = false;
            this.ucENEMinuti.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.ucENEMinuti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucENEMinuti.FormatString = "";
            this.ucENEMinuti.Location = new System.Drawing.Point(878, 3);
            this.ucENEMinuti.MaskInput = "nnnn";
            this.ucENEMinuti.MaxValue = 2880;
            this.ucENEMinuti.MinValue = 0;
            this.ucENEMinuti.Name = "ucENEMinuti";
            this.ucENEMinuti.Size = new System.Drawing.Size(94, 27);
            this.ucENEMinuti.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.ucENEMinuti.SpinIncrement = 5;
            this.ucENEMinuti.TabIndex = 14;
            this.ucENEMinuti.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucENEMinuti.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.UltraPopupControlContainerSegnalibri.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerSegnalibri_Opening);
            this.UltraPopupControlContainerSegnalibri.Opened += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Opened);
            this.UltraPopupControlContainerSegnalibri.Closed += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1008, 730);
            this.Controls.Add(this.UltraGroupBox);
            this.Name = "frmSelezionaAgendeDisponibilita";
            this.PulsanteAvantiTesto = "SELEZIONA";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmSelezionaAgendeDisponibilita";
            this.ImmagineClick += new UnicodeSrl.ScciCore.ImmagineTopClickHandler(this.frmSelezionaTipoAppuntamento_ImmagineClick);
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmSelezionaTipoAppuntamento_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmSelezionaTipoAppuntamento_PulsanteAvantiClick);
            this.Shown += new System.EventHandler(this.frmSelezionaAgendeDisponibilita_Shown);
            this.Controls.SetChildIndex(this.UltraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridDate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraDayView)).EndInit();
            this.ucEasyTableLayoutPanelTop.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udtFiltroDataA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udtFiltroDataDa)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyDateRange)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucENEMinuti)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.UltraWinSchedule.UltraCalendarInfo UltraCalendarInfo;
        private Infragistics.Win.UltraWinSchedule.UltraCalendarLook UltraCalendarLook;
        private ucEasyTableLayoutPanel TableLayoutPanel;
        private Infragistics.Win.UltraWinSchedule.UltraDayView UltraDayView;
        private ucEasyGrid UltraGridDate;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerSegnalibri;
        private ucEasyButton ubTrovaDisp;
        private ucEasyLabelHeader lblAgenda;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelTop;
        private ucEasyDateRange ucEasyDateRange;
        private ucEasyDateTimeEditor udtFiltroDataDa;
        private ucEasyDateTimeEditor udtFiltroDataA;
        private ucEasyLabel lblFiltroDataDa;
        private ucEasyLabel lblMinuti;
        private ucEasyLabel lblFiltroDataA;
        private ucEasyNumericEditor ucENEMinuti;
    }
}