namespace UnicodeSrl.ScciCore
{
    partial class frmSelezionaAgendeAppuntamento
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmSelezionaAgendeAppuntamento));
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.TableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.UltraPanelCalendari = new Infragistics.Win.Misc.UltraPanel();
            this.UltraDayView = new Infragistics.Win.UltraWinSchedule.UltraDayView();
            this.UltraCalendarInfo = new Infragistics.Win.UltraWinSchedule.UltraCalendarInfo(this.components);
            this.UltraCalendarLook = new Infragistics.Win.UltraWinSchedule.UltraCalendarLook(this.components);
            this.UltraMonthViewSingle = new Infragistics.Win.UltraWinSchedule.UltraMonthViewSingle();
            this.UltraWeekView = new Infragistics.Win.UltraWinSchedule.UltraWeekView();
            this.usAgendeLista = new Infragistics.Win.Misc.UltraSplitter();
            this.utcAgendeLista = new UnicodeSrl.ScciCore.ucEasyTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ucEasyTableLayoutPanelLeft = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.UltraGridAgendeAltre = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.utvAgende = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.UltraMonthViewMulti = new Infragistics.Win.UltraWinSchedule.UltraMonthViewMulti();
            this.ucEasyTableLayoutPanelTop = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyButtonOggi = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonGiorno = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonGiornoLav = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonSettimana = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonMese = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonRefresh = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonDisponibilita = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonAvanti = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonIndietro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.UltraPopupControlContainerSegnalibri = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.ucEasyButtonGiornoLav5 = new UnicodeSrl.ScciCore.ucEasyButton();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            this.UltraPanelCalendari.ClientArea.SuspendLayout();
            this.UltraPanelCalendari.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraDayView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraMonthViewSingle)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraWeekView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utcAgendeLista)).BeginInit();
            this.utcAgendeLista.SuspendLayout();
            this.ucEasyTableLayoutPanelLeft.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridAgendeAltre)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utvAgende)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraMonthViewMulti)).BeginInit();
            this.ucEasyTableLayoutPanelTop.SuspendLayout();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(1008, 31);
                                                this.UltraGroupBox.Controls.Add(this.TableLayoutPanel);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 31);
            this.UltraGroupBox.Margin = new System.Windows.Forms.Padding(0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(1008, 668);
            this.UltraGroupBox.TabIndex = 1;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.TableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanel.ColumnCount = 5;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 28F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 68F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.Controls.Add(this.UltraPanelCalendari, 3, 2);
            this.TableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelLeft, 1, 1);
            this.TableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelTop, 3, 1);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 4;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 88F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(1002, 662);
            this.TableLayoutPanel.TabIndex = 1;
                                                                                    this.UltraPanelCalendari.ClientArea.Controls.Add(this.UltraDayView);
            this.UltraPanelCalendari.ClientArea.Controls.Add(this.UltraMonthViewSingle);
            this.UltraPanelCalendari.ClientArea.Controls.Add(this.UltraWeekView);
            this.UltraPanelCalendari.ClientArea.Controls.Add(this.usAgendeLista);
            this.UltraPanelCalendari.ClientArea.Controls.Add(this.utcAgendeLista);
            this.UltraPanelCalendari.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraPanelCalendari.Location = new System.Drawing.Point(313, 75);
            this.UltraPanelCalendari.Name = "UltraPanelCalendari";
            this.UltraPanelCalendari.Size = new System.Drawing.Size(675, 576);
            this.UltraPanelCalendari.TabIndex = 12;
                                                this.UltraDayView.CalendarInfo = this.UltraCalendarInfo;
            this.UltraDayView.CalendarLook = this.UltraCalendarLook;
            this.UltraDayView.Location = new System.Drawing.Point(18, 56);
            this.UltraDayView.Name = "UltraDayView";
            this.UltraDayView.Size = new System.Drawing.Size(467, 342);
            this.UltraDayView.TabIndex = 0;
            this.UltraDayView.Text = "ultraDayView1";
            this.UltraDayView.Visible = false;
            this.UltraDayView.BeforeTimeSlotSelectionChanged += new Infragistics.Win.UltraWinSchedule.BeforeTimeSlotSelectionChangedEventHandler(this.UltraDayView_BeforeTimeSlotSelectionChanged);
            this.UltraDayView.Click += new System.EventHandler(this.UltraView_Click);
            this.UltraDayView.KeyDown += new System.Windows.Forms.KeyEventHandler(this.UltraDayView_KeyDown);
                                                this.UltraCalendarInfo.DataBindingsForAppointments.BindingContextControl = this;
            this.UltraCalendarInfo.DataBindingsForOwners.BindingContextControl = this;
            this.UltraCalendarInfo.AfterActiveDayChanged += new Infragistics.Win.UltraWinSchedule.AfterActiveDayChangedEventHandler(this.UltraCalendarInfo_AfterActiveDayChanged);
            this.UltraCalendarInfo.AppointmentDataInitialized += new Infragistics.Win.UltraWinSchedule.AppointmentDataInitializedEventHandler(this.UltraCalendarInfo_AppointmentDataInitialized);
            this.UltraCalendarInfo.OwnerDataInitialized += new Infragistics.Win.UltraWinSchedule.OwnerDataInitializedEventHandler(this.UltraCalendarInfo_OwnerDataInitialized);
                                                this.UltraMonthViewSingle.CalendarInfo = this.UltraCalendarInfo;
            this.UltraMonthViewSingle.CalendarLook = this.UltraCalendarLook;
            this.UltraMonthViewSingle.Location = new System.Drawing.Point(396, 40);
            this.UltraMonthViewSingle.Name = "UltraMonthViewSingle";
            this.UltraMonthViewSingle.Size = new System.Drawing.Size(163, 214);
            this.UltraMonthViewSingle.TabIndex = 2;
            this.UltraMonthViewSingle.Visible = false;
            this.UltraMonthViewSingle.Click += new System.EventHandler(this.UltraView_Click);
            this.UltraMonthViewSingle.KeyDown += new System.Windows.Forms.KeyEventHandler(this.UltraMonthViewSingle_KeyDown);
                                                this.UltraWeekView.CalendarInfo = this.UltraCalendarInfo;
            this.UltraWeekView.CalendarLook = this.UltraCalendarLook;
            this.UltraWeekView.Location = new System.Drawing.Point(179, 27);
            this.UltraWeekView.Name = "UltraWeekView";
            this.UltraWeekView.Size = new System.Drawing.Size(152, 227);
            this.UltraWeekView.TabIndex = 1;
            this.UltraWeekView.Visible = false;
            this.UltraWeekView.Click += new System.EventHandler(this.UltraView_Click);
            this.UltraWeekView.KeyDown += new System.Windows.Forms.KeyEventHandler(this.UltraWeekView_KeyDown);
                                                this.usAgendeLista.BackColor = System.Drawing.Color.Transparent;
            this.usAgendeLista.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.usAgendeLista.Location = new System.Drawing.Point(0, 265);
            this.usAgendeLista.Name = "usAgendeLista";
            this.usAgendeLista.RestoreExtent = 88;
            this.usAgendeLista.Size = new System.Drawing.Size(675, 11);
            this.usAgendeLista.TabIndex = 4;
                                                appearance1.ForeColor = System.Drawing.Color.CornflowerBlue;
            this.utcAgendeLista.Appearance = appearance1;
            this.utcAgendeLista.Controls.Add(this.ultraTabSharedControlsPage1);
            this.utcAgendeLista.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.utcAgendeLista.Location = new System.Drawing.Point(0, 276);
            this.utcAgendeLista.Name = "utcAgendeLista";
            appearance2.FontData.BoldAsString = "True";
            appearance2.ForeColor = System.Drawing.Color.MidnightBlue;
            this.utcAgendeLista.SelectedTabAppearance = appearance2;
            this.utcAgendeLista.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.utcAgendeLista.Size = new System.Drawing.Size(675, 300);
            appearance3.FontData.SizeInPoints = 15.58209F;
            this.utcAgendeLista.TabHeaderAreaAppearance = appearance3;
            this.utcAgendeLista.TabIndex = 3;
            this.utcAgendeLista.TabLayoutStyle = Infragistics.Win.UltraWinTabs.TabLayoutStyle.SingleRowSizeToFit;
            this.utcAgendeLista.TabSize = new System.Drawing.Size(0, 34);
            this.utcAgendeLista.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.utcAgendeLista.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.utcAgendeLista.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(1, 20);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(673, 279);
                                                this.ucEasyTableLayoutPanelLeft.ColumnCount = 1;
            this.ucEasyTableLayoutPanelLeft.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelLeft.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelLeft.Controls.Add(this.UltraGridAgendeAltre, 0, 2);
            this.ucEasyTableLayoutPanelLeft.Controls.Add(this.utvAgende, 0, 1);
            this.ucEasyTableLayoutPanelLeft.Controls.Add(this.UltraMonthViewMulti, 0, 0);
            this.ucEasyTableLayoutPanelLeft.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelLeft.Location = new System.Drawing.Point(13, 9);
            this.ucEasyTableLayoutPanelLeft.Name = "ucEasyTableLayoutPanelLeft";
            this.ucEasyTableLayoutPanelLeft.RowCount = 3;
            this.TableLayoutPanel.SetRowSpan(this.ucEasyTableLayoutPanelLeft, 2);
            this.ucEasyTableLayoutPanelLeft.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelLeft.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ucEasyTableLayoutPanelLeft.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelLeft.Size = new System.Drawing.Size(274, 642);
            this.ucEasyTableLayoutPanelLeft.TabIndex = 13;
                                                this.UltraGridAgendeAltre.ColonnaRTFControlloContenuto = false;
            this.UltraGridAgendeAltre.ColonnaRTFResize = "";
            this.UltraGridAgendeAltre.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridAgendeAltre.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance4.BackColor = System.Drawing.SystemColors.Window;
            appearance4.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridAgendeAltre.DisplayLayout.Appearance = appearance4;
            this.UltraGridAgendeAltre.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridAgendeAltre.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance5.FontData.BoldAsString = "True";
            this.UltraGridAgendeAltre.DisplayLayout.CaptionAppearance = appearance5;
            this.UltraGridAgendeAltre.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance6.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance6.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance6.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridAgendeAltre.DisplayLayout.GroupByBox.Appearance = appearance6;
            appearance7.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridAgendeAltre.DisplayLayout.GroupByBox.BandLabelAppearance = appearance7;
            this.UltraGridAgendeAltre.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridAgendeAltre.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridAgendeAltre.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance8.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance8.BackColor2 = System.Drawing.SystemColors.Control;
            appearance8.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance8.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridAgendeAltre.DisplayLayout.GroupByBox.PromptAppearance = appearance8;
            this.UltraGridAgendeAltre.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridAgendeAltre.DisplayLayout.MaxRowScrollRegions = 1;
            appearance9.BackColor = System.Drawing.SystemColors.Window;
            appearance9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridAgendeAltre.DisplayLayout.Override.ActiveCellAppearance = appearance9;
            appearance10.BackColor = System.Drawing.SystemColors.Highlight;
            appearance10.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridAgendeAltre.DisplayLayout.Override.ActiveRowAppearance = appearance10;
            this.UltraGridAgendeAltre.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridAgendeAltre.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridAgendeAltre.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridAgendeAltre.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridAgendeAltre.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridAgendeAltre.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridAgendeAltre.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridAgendeAltre.DisplayLayout.Override.CardAreaAppearance = appearance11;
            appearance12.BorderColor = System.Drawing.Color.Silver;
            appearance12.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridAgendeAltre.DisplayLayout.Override.CellAppearance = appearance12;
            this.UltraGridAgendeAltre.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridAgendeAltre.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridAgendeAltre.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance13.BackColor = System.Drawing.SystemColors.Control;
            appearance13.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance13.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance13.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance13.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridAgendeAltre.DisplayLayout.Override.GroupByRowAppearance = appearance13;
            appearance14.FontData.BoldAsString = "True";
            appearance14.TextHAlignAsString = "Center";
            this.UltraGridAgendeAltre.DisplayLayout.Override.HeaderAppearance = appearance14;
            this.UltraGridAgendeAltre.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridAgendeAltre.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance15.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance15.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridAgendeAltre.DisplayLayout.Override.RowAlternateAppearance = appearance15;
            appearance16.BackColor = System.Drawing.SystemColors.Window;
            appearance16.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridAgendeAltre.DisplayLayout.Override.RowAppearance = appearance16;
            this.UltraGridAgendeAltre.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridAgendeAltre.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridAgendeAltre.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridAgendeAltre.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance17.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridAgendeAltre.DisplayLayout.Override.TemplateAddRowAppearance = appearance17;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridAgendeAltre.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.UltraGridAgendeAltre.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridAgendeAltre.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridAgendeAltre.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridAgendeAltre.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridAgendeAltre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridAgendeAltre.FattoreRidimensionamentoRTF = 21;
            this.UltraGridAgendeAltre.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridAgendeAltre.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridAgendeAltre.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridAgendeAltre.Location = new System.Drawing.Point(3, 484);
            this.UltraGridAgendeAltre.Name = "UltraGridAgendeAltre";
            this.UltraGridAgendeAltre.ShowFilterRow = false;
            this.UltraGridAgendeAltre.ShowGroupByBox = false;
            this.UltraGridAgendeAltre.Size = new System.Drawing.Size(268, 155);
            this.UltraGridAgendeAltre.TabIndex = 0;
            this.UltraGridAgendeAltre.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridAgendeAltre.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance18.FontData.SizeInPoints = 22.50746F;
            this.utvAgende.Appearance = appearance18;
            this.utvAgende.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            this.utvAgende.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.utvAgende.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utvAgende.FullRowSelect = true;
            this.utvAgende.HideSelection = false;
            this.utvAgende.LeftImagesSize = new System.Drawing.Size(23, 23);
            this.utvAgende.Location = new System.Drawing.Point(3, 163);
            this.utvAgende.Name = "utvAgende";
            appearance19.BackColor = System.Drawing.Color.LightYellow;
            appearance19.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance19;
            _override1.SelectedNodeAppearance = appearance19;
            this.utvAgende.Override = _override1;
            this.utvAgende.RightImagesSize = new System.Drawing.Size(23, 23);
            this.utvAgende.Size = new System.Drawing.Size(268, 315);
            this.utvAgende.TabIndex = 11;
            this.utvAgende.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.utvAgende.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.utvAgende.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.utvAgende_AfterCheck);
                                                this.UltraMonthViewMulti.BackColor = System.Drawing.SystemColors.Window;
            this.UltraMonthViewMulti.CalendarInfo = this.UltraCalendarInfo;
            this.UltraMonthViewMulti.CalendarLook = this.UltraCalendarLook;
            this.UltraMonthViewMulti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraMonthViewMulti.Location = new System.Drawing.Point(3, 3);
            this.UltraMonthViewMulti.MonthDimensions = new System.Drawing.Size(2, 1);
            this.UltraMonthViewMulti.Name = "UltraMonthViewMulti";
            this.UltraMonthViewMulti.ResizeMode = Infragistics.Win.UltraWinSchedule.ResizeMode.UseMonthDimensions;
            this.UltraMonthViewMulti.Size = new System.Drawing.Size(268, 154);
            this.UltraMonthViewMulti.TabIndex = 3;
            this.UltraMonthViewMulti.BeforeMonthScroll += new Infragistics.Win.UltraWinSchedule.BeforeMonthScrollEventHandler(this.UltraMonthViewMulti_BeforeMonthScroll);
                                                this.ucEasyTableLayoutPanelTop.ColumnCount = 10;
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonGiornoLav5, 2, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonOggi, 0, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonGiorno, 1, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonGiornoLav, 3, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonSettimana, 4, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonMese, 5, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonRefresh, 7, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonDisponibilita, 6, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonAvanti, 9, 0);
            this.ucEasyTableLayoutPanelTop.Controls.Add(this.ucEasyButtonIndietro, 8, 0);
            this.ucEasyTableLayoutPanelTop.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelTop.Location = new System.Drawing.Point(313, 9);
            this.ucEasyTableLayoutPanelTop.Name = "ucEasyTableLayoutPanelTop";
            this.ucEasyTableLayoutPanelTop.RowCount = 1;
            this.ucEasyTableLayoutPanelTop.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelTop.Size = new System.Drawing.Size(675, 60);
            this.ucEasyTableLayoutPanelTop.TabIndex = 14;
                                                appearance21.FontData.SizeInPoints = 12.1194F;
            appearance21.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance21.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance21.TextHAlignAsString = "Center";
            appearance21.TextVAlignAsString = "Bottom";
            this.ucEasyButtonOggi.Appearance = appearance21;
            this.ucEasyButtonOggi.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonOggi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonOggi.Location = new System.Drawing.Point(3, 3);
            this.ucEasyButtonOggi.Name = "ucEasyButtonOggi";
            this.ucEasyButtonOggi.PercImageFill = 0.75F;
            this.ucEasyButtonOggi.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonOggi.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonOggi.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonOggi.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonOggi.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonOggi.TabIndex = 0;
            this.ucEasyButtonOggi.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonOggi.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonOggi.Click += new System.EventHandler(this.ucEasyButtonOggi_Click);
                                                appearance22.FontData.SizeInPoints = 12.1194F;
            appearance22.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance22.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance22.TextHAlignAsString = "Center";
            appearance22.TextVAlignAsString = "Bottom";
            this.ucEasyButtonGiorno.Appearance = appearance22;
            this.ucEasyButtonGiorno.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonGiorno.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonGiorno.Location = new System.Drawing.Point(70, 3);
            this.ucEasyButtonGiorno.Name = "ucEasyButtonGiorno";
            this.ucEasyButtonGiorno.PercImageFill = 0.75F;
            this.ucEasyButtonGiorno.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonGiorno.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonGiorno.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonGiorno.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonGiorno.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonGiorno.TabIndex = 1;
            this.ucEasyButtonGiorno.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonGiorno.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonGiorno.Click += new System.EventHandler(this.ucEasyButtonGiorno_Click);
                                                appearance23.FontData.SizeInPoints = 12.1194F;
            appearance23.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance23.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance23.TextHAlignAsString = "Center";
            appearance23.TextVAlignAsString = "Bottom";
            this.ucEasyButtonGiornoLav.Appearance = appearance23;
            this.ucEasyButtonGiornoLav.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonGiornoLav.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonGiornoLav.Location = new System.Drawing.Point(204, 3);
            this.ucEasyButtonGiornoLav.Name = "ucEasyButtonGiornoLav";
            this.ucEasyButtonGiornoLav.PercImageFill = 0.75F;
            this.ucEasyButtonGiornoLav.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonGiornoLav.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonGiornoLav.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonGiornoLav.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonGiornoLav.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonGiornoLav.TabIndex = 2;
            this.ucEasyButtonGiornoLav.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonGiornoLav.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonGiornoLav.Click += new System.EventHandler(this.ucEasyButtonGiornoLav_Click);
                                                appearance24.FontData.SizeInPoints = 12.1194F;
            appearance24.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance24.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance24.TextHAlignAsString = "Center";
            appearance24.TextVAlignAsString = "Bottom";
            this.ucEasyButtonSettimana.Appearance = appearance24;
            this.ucEasyButtonSettimana.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonSettimana.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonSettimana.Location = new System.Drawing.Point(271, 3);
            this.ucEasyButtonSettimana.Name = "ucEasyButtonSettimana";
            this.ucEasyButtonSettimana.PercImageFill = 0.75F;
            this.ucEasyButtonSettimana.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonSettimana.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonSettimana.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonSettimana.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonSettimana.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonSettimana.TabIndex = 3;
            this.ucEasyButtonSettimana.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonSettimana.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonSettimana.Click += new System.EventHandler(this.ucEasyButtonSettimana_Click);
                                                appearance25.FontData.SizeInPoints = 12.1194F;
            appearance25.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance25.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance25.TextHAlignAsString = "Center";
            appearance25.TextVAlignAsString = "Bottom";
            this.ucEasyButtonMese.Appearance = appearance25;
            this.ucEasyButtonMese.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonMese.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonMese.Location = new System.Drawing.Point(338, 3);
            this.ucEasyButtonMese.Name = "ucEasyButtonMese";
            this.ucEasyButtonMese.PercImageFill = 0.75F;
            this.ucEasyButtonMese.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonMese.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonMese.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonMese.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonMese.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonMese.TabIndex = 4;
            this.ucEasyButtonMese.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonMese.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonMese.Click += new System.EventHandler(this.ucEasyButtonMese_Click);
                                                appearance26.FontData.SizeInPoints = 12.1194F;
            appearance26.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance26.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance26.TextHAlignAsString = "Center";
            appearance26.TextVAlignAsString = "Bottom";
            this.ucEasyButtonRefresh.Appearance = appearance26;
            this.ucEasyButtonRefresh.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonRefresh.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonRefresh.Location = new System.Drawing.Point(472, 3);
            this.ucEasyButtonRefresh.Name = "ucEasyButtonRefresh";
            this.ucEasyButtonRefresh.PercImageFill = 0.75F;
            this.ucEasyButtonRefresh.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonRefresh.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonRefresh.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonRefresh.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonRefresh.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonRefresh.TabIndex = 5;
            this.ucEasyButtonRefresh.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonRefresh.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonRefresh.Click += new System.EventHandler(this.ucEasyButtonRefresh_Click);
                                                appearance27.FontData.SizeInPoints = 12.1194F;
            appearance27.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance27.ImageBackground")));
            appearance27.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance27.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance27.TextHAlignAsString = "Center";
            appearance27.TextVAlignAsString = "Bottom";
            this.ucEasyButtonDisponibilita.Appearance = appearance27;
            this.ucEasyButtonDisponibilita.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonDisponibilita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonDisponibilita.Location = new System.Drawing.Point(405, 3);
            this.ucEasyButtonDisponibilita.Name = "ucEasyButtonDisponibilita";
            this.ucEasyButtonDisponibilita.PercImageFill = 0.75F;
            this.ucEasyButtonDisponibilita.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonDisponibilita.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XXSmall;
            this.ucEasyButtonDisponibilita.ShortcutKey = System.Windows.Forms.Keys.D;
            this.ucEasyButtonDisponibilita.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonDisponibilita.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonDisponibilita.TabIndex = 5;
            this.ucEasyButtonDisponibilita.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonDisponibilita.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonDisponibilita.Click += new System.EventHandler(this.ucEasyButtonDisponibilita_Click);
                                                appearance28.FontData.SizeInPoints = 12.1194F;
            appearance28.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance28.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance28.TextHAlignAsString = "Center";
            appearance28.TextVAlignAsString = "Bottom";
            this.ucEasyButtonAvanti.Appearance = appearance28;
            this.ucEasyButtonAvanti.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonAvanti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonAvanti.Location = new System.Drawing.Point(606, 3);
            this.ucEasyButtonAvanti.Name = "ucEasyButtonAvanti";
            this.ucEasyButtonAvanti.PercImageFill = 0.75F;
            this.ucEasyButtonAvanti.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonAvanti.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonAvanti.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonAvanti.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonAvanti.Size = new System.Drawing.Size(66, 54);
            this.ucEasyButtonAvanti.TabIndex = 5;
            this.ucEasyButtonAvanti.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonAvanti.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonAvanti.Click += new System.EventHandler(this.ucEasyButtonAvanti_Click);
                                                appearance29.FontData.SizeInPoints = 12.1194F;
            appearance29.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance29.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance29.TextHAlignAsString = "Center";
            appearance29.TextVAlignAsString = "Bottom";
            this.ucEasyButtonIndietro.Appearance = appearance29;
            this.ucEasyButtonIndietro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonIndietro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonIndietro.Location = new System.Drawing.Point(539, 3);
            this.ucEasyButtonIndietro.Name = "ucEasyButtonIndietro";
            this.ucEasyButtonIndietro.PercImageFill = 0.75F;
            this.ucEasyButtonIndietro.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonIndietro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonIndietro.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonIndietro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonIndietro.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonIndietro.TabIndex = 5;
            this.ucEasyButtonIndietro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonIndietro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonIndietro.Click += new System.EventHandler(this.ucEasyButtonIndietro_Click);
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.UltraPopupControlContainerSegnalibri.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerSegnalibri_Opening);
            this.UltraPopupControlContainerSegnalibri.Opened += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Opened);
            this.UltraPopupControlContainerSegnalibri.Closed += new System.EventHandler(this.UltraPopupControlContainerSegnalibri_Closed);
                                                appearance20.FontData.SizeInPoints = 12.1194F;
            appearance20.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance20.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance20.TextHAlignAsString = "Center";
            appearance20.TextVAlignAsString = "Bottom";
            this.ucEasyButtonGiornoLav5.Appearance = appearance20;
            this.ucEasyButtonGiornoLav5.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonGiornoLav5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonGiornoLav5.Location = new System.Drawing.Point(137, 3);
            this.ucEasyButtonGiornoLav5.Name = "ucEasyButtonGiornoLav5";
            this.ucEasyButtonGiornoLav5.PercImageFill = 0.75F;
            this.ucEasyButtonGiornoLav5.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyButtonGiornoLav5.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyButtonGiornoLav5.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonGiornoLav5.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonGiornoLav5.Size = new System.Drawing.Size(61, 54);
            this.ucEasyButtonGiornoLav5.TabIndex = 6;
            this.ucEasyButtonGiornoLav5.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonGiornoLav5.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonGiornoLav5.Click += new System.EventHandler(this.ucEasyButtonGiornoLav5_Click);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1008, 730);
            this.Controls.Add(this.UltraGroupBox);
            this.Name = "frmSelezionaAgendeAppuntamento";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmSelezionaTipoAppuntamento";
            this.ImmagineClick += new UnicodeSrl.ScciCore.ImmagineTopClickHandler(this.frmSelezionaTipoAppuntamento_ImmagineClick);
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmSelezionaTipoAppuntamento_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmSelezionaTipoAppuntamento_PulsanteAvantiClick);
            this.Controls.SetChildIndex(this.UltraGroupBox, 0);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            this.UltraPanelCalendari.ClientArea.ResumeLayout(false);
            this.UltraPanelCalendari.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraDayView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraMonthViewSingle)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraWeekView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utcAgendeLista)).EndInit();
            this.utcAgendeLista.ResumeLayout(false);
            this.ucEasyTableLayoutPanelLeft.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridAgendeAltre)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utvAgende)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraMonthViewMulti)).EndInit();
            this.ucEasyTableLayoutPanelTop.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.UltraWinSchedule.UltraCalendarInfo UltraCalendarInfo;
        private Infragistics.Win.UltraWinSchedule.UltraCalendarLook UltraCalendarLook;
        private ucEasyTableLayoutPanel TableLayoutPanel;
        private Infragistics.Win.Misc.UltraPanel UltraPanelCalendari;
        private Infragistics.Win.UltraWinSchedule.UltraMonthViewSingle UltraMonthViewSingle;
        private Infragistics.Win.UltraWinSchedule.UltraWeekView UltraWeekView;
        private Infragistics.Win.UltraWinSchedule.UltraDayView UltraDayView;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelLeft;
        private ucEasyGrid UltraGridAgendeAltre;
        private ucEasyTreeView utvAgende;
        private Infragistics.Win.UltraWinSchedule.UltraMonthViewMulti UltraMonthViewMulti;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelTop;
        private ucEasyButton ucEasyButtonOggi;
        private ucEasyButton ucEasyButtonGiorno;
        private ucEasyButton ucEasyButtonGiornoLav;
        private ucEasyButton ucEasyButtonSettimana;
        private ucEasyButton ucEasyButtonMese;
        private ucEasyButton ucEasyButtonRefresh;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerSegnalibri;
        private ucEasyButton ucEasyButtonDisponibilita;
        private ucEasyButton ucEasyButtonAvanti;
        private ucEasyButton ucEasyButtonIndietro;
        private Infragistics.Win.Misc.UltraSplitter usAgendeLista;
        private ucEasyTabControl utcAgendeLista;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private ucEasyButton ucEasyButtonGiornoLav5;
    }
}