namespace UnicodeSrl.ScciCore
{
    partial class frmSelezionaTipoPrescrizione
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmSelezionaTipoPrescrizione));
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton1 = new Infragistics.Win.UltraWinEditors.EditorButton("Orari");
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override2 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab2 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucEasyTableLayoutPanelDati = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.UltraTree = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ubRicerca = new UnicodeSrl.ScciCore.ucEasyButton();
            this.uteRicerca = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblRicerca = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ultraTabPageControl2 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucEasyTableLayoutPanelProtocolli = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.udteDataOraInizio = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.UltraTreeProtocolli = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.lblDataOraInizio = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyProgressBarProtocolli = new UnicodeSrl.ScciCore.ucEasyProgressBar();
            this.TableLayoutPanelZoom = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTableLayoutImmagine = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.PictureBox = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.UltraTabControl = new UnicodeSrl.ScciCore.ucEasyTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.UltraGroupBoxZoom = new Infragistics.Win.Misc.UltraGroupBox();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.ultraTabPageControl1.SuspendLayout();
            this.ucEasyTableLayoutPanelDati.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTree)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteRicerca)).BeginInit();
            this.ultraTabPageControl2.SuspendLayout();
            this.ucEasyTableLayoutPanelProtocolli.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataOraInizio)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTreeProtocolli)).BeginInit();
            this.TableLayoutPanelZoom.SuspendLayout();
            this.ucEasyTableLayoutImmagine.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).BeginInit();
            this.UltraTabControl.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBoxZoom)).BeginInit();
            this.UltraGroupBoxZoom.SuspendLayout();
            this.SuspendLayout();
                                                this.ucBottomModale.Size = new System.Drawing.Size(784, 24);
                                                this.ultraTabPageControl1.Controls.Add(this.ucEasyTableLayoutPanelDati);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(591, 399);
                                                this.ucEasyTableLayoutPanelDati.ColumnCount = 4;
            this.ucEasyTableLayoutPanelDati.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelDati.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.ucEasyTableLayoutPanelDati.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.ucEasyTableLayoutPanelDati.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 17F));
            this.ucEasyTableLayoutPanelDati.Controls.Add(this.UltraTree, 0, 2);
            this.ucEasyTableLayoutPanelDati.Controls.Add(this.ubRicerca, 3, 0);
            this.ucEasyTableLayoutPanelDati.Controls.Add(this.uteRicerca, 1, 0);
            this.ucEasyTableLayoutPanelDati.Controls.Add(this.lblRicerca, 0, 0);
            this.ucEasyTableLayoutPanelDati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelDati.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelDati.Name = "ucEasyTableLayoutPanelDati";
            this.ucEasyTableLayoutPanelDati.RowCount = 3;
            this.ucEasyTableLayoutPanelDati.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanelDati.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelDati.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 91F));
            this.ucEasyTableLayoutPanelDati.Size = new System.Drawing.Size(591, 399);
            this.ucEasyTableLayoutPanelDati.TabIndex = 13;
                                                appearance1.FontData.SizeInPoints = 27.70149F;
            this.UltraTree.Appearance = appearance1;
            this.UltraTree.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            this.ucEasyTableLayoutPanelDati.SetColumnSpan(this.UltraTree, 4);
            this.UltraTree.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.UltraTree.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraTree.HideSelection = false;
            this.UltraTree.LeftImagesSize = new System.Drawing.Size(28, 28);
            this.UltraTree.Location = new System.Drawing.Point(3, 37);
            this.UltraTree.Name = "UltraTree";
            appearance2.BackColor = System.Drawing.Color.LightYellow;
            appearance2.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance2;
            _override1.SelectedNodeAppearance = appearance2;
            this.UltraTree.Override = _override1;
            this.UltraTree.RightImagesSize = new System.Drawing.Size(28, 28);
            this.UltraTree.Size = new System.Drawing.Size(585, 359);
            this.UltraTree.TabIndex = 21;
            this.UltraTree.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.UltraTree.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraTree.AfterActivate += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.UltraTree_AfterActivate);
                                                appearance3.FontData.SizeInPoints = 22.50746F;
            appearance3.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance3.ImageBackground")));
            appearance3.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance3.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance3.TextHAlignAsString = "Center";
            appearance3.TextVAlignAsString = "Middle";
            this.ubRicerca.Appearance = appearance3;
            this.ubRicerca.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRicerca.Location = new System.Drawing.Point(492, 3);
            this.ubRicerca.Name = "ubRicerca";
            this.ubRicerca.PercImageFill = 0.75F;
            this.ubRicerca.ShortcutColor = System.Drawing.Color.Black;
            this.ubRicerca.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubRicerca.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubRicerca.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubRicerca.Size = new System.Drawing.Size(96, 25);
            this.ubRicerca.TabIndex = 20;
            this.ubRicerca.Text = "Ricerca";
            this.ubRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubRicerca.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubRicerca.Click += new System.EventHandler(this.ubRicerca_Click);
                                                appearance4.FontData.SizeInPoints = 22.50746F;
            this.uteRicerca.Appearance = appearance4;
            this.uteRicerca.AutoSize = false;
            this.uteRicerca.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteRicerca.Location = new System.Drawing.Point(91, 3);
            this.uteRicerca.Name = "uteRicerca";
            this.uteRicerca.Size = new System.Drawing.Size(378, 25);
            this.uteRicerca.TabIndex = 19;
            this.uteRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.uteRicerca.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uteRicerca.KeyDown += new System.Windows.Forms.KeyEventHandler(this.uteRicerca_KeyDown);
                                                appearance5.FontData.SizeInPoints = 22.50746F;
            appearance5.TextVAlignAsString = "Middle";
            this.lblRicerca.Appearance = appearance5;
            this.lblRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRicerca.Location = new System.Drawing.Point(3, 3);
            this.lblRicerca.Name = "lblRicerca";
            this.lblRicerca.ShortcutColor = System.Drawing.Color.Black;
            this.lblRicerca.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblRicerca.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblRicerca.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblRicerca.Size = new System.Drawing.Size(82, 25);
            this.lblRicerca.TabIndex = 18;
            this.lblRicerca.Text = "Cerca";
            this.lblRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ultraTabPageControl2.Controls.Add(this.ucEasyTableLayoutPanelProtocolli);
            this.ultraTabPageControl2.Location = new System.Drawing.Point(1, 51);
            this.ultraTabPageControl2.Name = "ultraTabPageControl2";
            this.ultraTabPageControl2.Size = new System.Drawing.Size(591, 399);
                                                this.ucEasyTableLayoutPanelProtocolli.ColumnCount = 3;
            this.ucEasyTableLayoutPanelProtocolli.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelProtocolli.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelProtocolli.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.ucEasyTableLayoutPanelProtocolli.Controls.Add(this.udteDataOraInizio, 1, 0);
            this.ucEasyTableLayoutPanelProtocolli.Controls.Add(this.UltraTreeProtocolli, 0, 2);
            this.ucEasyTableLayoutPanelProtocolli.Controls.Add(this.lblDataOraInizio, 0, 0);
            this.ucEasyTableLayoutPanelProtocolli.Controls.Add(this.ucEasyProgressBarProtocolli, 0, 3);
            this.ucEasyTableLayoutPanelProtocolli.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelProtocolli.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelProtocolli.Name = "ucEasyTableLayoutPanelProtocolli";
            this.ucEasyTableLayoutPanelProtocolli.RowCount = 4;
            this.ucEasyTableLayoutPanelProtocolli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanelProtocolli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelProtocolli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 85F));
            this.ucEasyTableLayoutPanelProtocolli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanelProtocolli.Size = new System.Drawing.Size(591, 399);
            this.ucEasyTableLayoutPanelProtocolli.TabIndex = 0;
                                                appearance6.FontData.SizeInPoints = 22.50746F;
            appearance6.TextHAlignAsString = "Center";
            this.udteDataOraInizio.Appearance = appearance6;
            this.udteDataOraInizio.AutoSize = false;
            appearance7.TextHAlignAsString = "Center";
            editorButton1.Appearance = appearance7;
            editorButton1.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2007RibbonButton;
            editorButton1.Key = "Orari";
            editorButton1.Text = "H";
            this.udteDataOraInizio.ButtonsRight.Add(editorButton1);
            this.udteDataOraInizio.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteDataOraInizio.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataOraInizio.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance8.FontData.SizeInPoints = 22.50746F;
            this.udteDataOraInizio.DropDownAppearance = appearance8;
            this.udteDataOraInizio.FormatString = "dd/MM/yyyy HH:mm";
            this.udteDataOraInizio.Location = new System.Drawing.Point(150, 3);
            this.udteDataOraInizio.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteDataOraInizio.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteDataOraInizio.Name = "udteDataOraInizio";
            this.udteDataOraInizio.Size = new System.Drawing.Size(171, 25);
            this.udteDataOraInizio.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataOraInizio.TabIndex = 23;
            this.udteDataOraInizio.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.udteDataOraInizio.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.udteDataOraInizio.Value = null;
            this.udteDataOraInizio.EditorButtonClick += new Infragistics.Win.UltraWinEditors.EditorButtonEventHandler(this.udteDataOraInizio_EditorButtonClick);
                                                appearance9.FontData.SizeInPoints = 27.70149F;
            this.UltraTreeProtocolli.Appearance = appearance9;
            this.UltraTreeProtocolli.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            this.ucEasyTableLayoutPanelProtocolli.SetColumnSpan(this.UltraTreeProtocolli, 4);
            this.UltraTreeProtocolli.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.UltraTreeProtocolli.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraTreeProtocolli.HideSelection = false;
            this.UltraTreeProtocolli.LeftImagesSize = new System.Drawing.Size(28, 28);
            this.UltraTreeProtocolli.Location = new System.Drawing.Point(3, 37);
            this.UltraTreeProtocolli.Name = "UltraTreeProtocolli";
            appearance10.BackColor = System.Drawing.Color.LightYellow;
            appearance10.BackColor2 = System.Drawing.Color.Orange;
            _override2.ActiveNodeAppearance = appearance10;
            _override2.SelectedNodeAppearance = appearance10;
            this.UltraTreeProtocolli.Override = _override2;
            this.UltraTreeProtocolli.RightImagesSize = new System.Drawing.Size(28, 28);
            this.UltraTreeProtocolli.Size = new System.Drawing.Size(585, 333);
            this.UltraTreeProtocolli.TabIndex = 22;
            this.UltraTreeProtocolli.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.UltraTreeProtocolli.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraTreeProtocolli.AfterActivate += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.UltraTreeProtocolli_AfterActivate);
                                                appearance11.FontData.SizeInPoints = 22.50746F;
            appearance11.TextVAlignAsString = "Middle";
            this.lblDataOraInizio.Appearance = appearance11;
            this.lblDataOraInizio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataOraInizio.Location = new System.Drawing.Point(0, 0);
            this.lblDataOraInizio.Margin = new System.Windows.Forms.Padding(0);
            this.lblDataOraInizio.Name = "lblDataOraInizio";
            this.lblDataOraInizio.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataOraInizio.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblDataOraInizio.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataOraInizio.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataOraInizio.Size = new System.Drawing.Size(147, 31);
            this.lblDataOraInizio.TabIndex = 10;
            this.lblDataOraInizio.Text = "Data / Ora Iniziale";
            this.lblDataOraInizio.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance12.FontData.SizeInPoints = 15.58209F;
            this.ucEasyProgressBarProtocolli.Appearance = appearance12;
            this.ucEasyTableLayoutPanelProtocolli.SetColumnSpan(this.ucEasyProgressBarProtocolli, 3);
            this.ucEasyProgressBarProtocolli.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyProgressBarProtocolli.Location = new System.Drawing.Point(3, 376);
            this.ucEasyProgressBarProtocolli.Name = "ucEasyProgressBarProtocolli";
            this.ucEasyProgressBarProtocolli.Size = new System.Drawing.Size(585, 20);
            this.ucEasyProgressBarProtocolli.TabIndex = 24;
            this.ucEasyProgressBarProtocolli.Text = "Elaborazione in corso: [Value] / [Maximum]";
            this.ucEasyProgressBarProtocolli.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyProgressBarProtocolli.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyProgressBarProtocolli.Visible = false;
                                                this.TableLayoutPanelZoom.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanelZoom.ColumnCount = 3;
            this.TableLayoutPanelZoom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.TableLayoutPanelZoom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 77F));
            this.TableLayoutPanelZoom.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanelZoom.Controls.Add(this.ucEasyTableLayoutImmagine, 0, 1);
            this.TableLayoutPanelZoom.Controls.Add(this.UltraTabControl, 1, 1);
            this.TableLayoutPanelZoom.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelZoom.Location = new System.Drawing.Point(3, 3);
            this.TableLayoutPanelZoom.Name = "TableLayoutPanelZoom";
            this.TableLayoutPanelZoom.RowCount = 3;
            this.TableLayoutPanelZoom.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanelZoom.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 90F));
            this.TableLayoutPanelZoom.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanelZoom.Size = new System.Drawing.Size(778, 508);
            this.TableLayoutPanelZoom.TabIndex = 0;
                                                this.ucEasyTableLayoutImmagine.ColumnCount = 3;
            this.ucEasyTableLayoutImmagine.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.ucEasyTableLayoutImmagine.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 71.42857F));
            this.ucEasyTableLayoutImmagine.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.ucEasyTableLayoutImmagine.Controls.Add(this.PictureBox, 1, 1);
            this.ucEasyTableLayoutImmagine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutImmagine.Location = new System.Drawing.Point(3, 28);
            this.ucEasyTableLayoutImmagine.Name = "ucEasyTableLayoutImmagine";
            this.ucEasyTableLayoutImmagine.RowCount = 3;
            this.ucEasyTableLayoutImmagine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutImmagine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutImmagine.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutImmagine.Size = new System.Drawing.Size(95, 451);
            this.ucEasyTableLayoutImmagine.TabIndex = 11;
                                                this.PictureBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PictureBox.Location = new System.Drawing.Point(16, 93);
            this.PictureBox.Name = "PictureBox";
            this.PictureBox.ShortcutColor = System.Drawing.Color.Black;
            this.PictureBox.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.PictureBox.ShortcutKey = System.Windows.Forms.Keys.None;
            this.PictureBox.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.PictureBox.Size = new System.Drawing.Size(61, 264);
            this.PictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PictureBox.TabIndex = 0;
            this.PictureBox.TabStop = false;
                                                appearance13.ForeColor = System.Drawing.Color.CornflowerBlue;
            this.UltraTabControl.Appearance = appearance13;
            this.UltraTabControl.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl2);
            this.UltraTabControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraTabControl.Location = new System.Drawing.Point(104, 28);
            this.UltraTabControl.Name = "UltraTabControl";
            appearance14.FontData.BoldAsString = "True";
            appearance14.ForeColor = System.Drawing.Color.MidnightBlue;
            this.UltraTabControl.SelectedTabAppearance = appearance14;
            this.UltraTabControl.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControl.Size = new System.Drawing.Size(593, 451);
            appearance15.FontData.SizeInPoints = 22.50746F;
            this.UltraTabControl.TabHeaderAreaAppearance = appearance15;
            this.UltraTabControl.TabIndex = 13;
            this.UltraTabControl.TabLayoutStyle = Infragistics.Win.UltraWinTabs.TabLayoutStyle.SingleRowSizeToFit;
            ultraTab1.Key = "tab0";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Tipo Terapia";
            ultraTab2.Key = "tab1";
            ultraTab2.TabPage = this.ultraTabPageControl2;
            ultraTab2.Text = "Protocollo Terapia";
            this.UltraTabControl.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1,
            ultraTab2});
            this.UltraTabControl.TabSize = new System.Drawing.Size(0, 50);
            this.UltraTabControl.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.UltraTabControl.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraTabControl.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(591, 399);
                                                this.UltraGroupBoxZoom.Controls.Add(this.TableLayoutPanelZoom);
            this.UltraGroupBoxZoom.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBoxZoom.Location = new System.Drawing.Point(0, 24);
            this.UltraGroupBoxZoom.Margin = new System.Windows.Forms.Padding(0);
            this.UltraGroupBoxZoom.Name = "UltraGroupBoxZoom";
            this.UltraGroupBoxZoom.Size = new System.Drawing.Size(784, 514);
            this.UltraGroupBoxZoom.TabIndex = 10;
            this.UltraGroupBoxZoom.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.UltraGroupBoxZoom);
            this.Name = "frmSelezionaTipoPrescrizione";
            this.PulsanteAvantiVisibile = true;
            this.PulsanteIndietroVisibile = true;
            this.Text = "frmSelezionaTipoPrescrizione";
            this.PulsanteIndietroClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmSelezionaTipoPrescrizione_PulsanteIndietroClick);
            this.PulsanteAvantiClick += new UnicodeSrl.ScciCore.PulsanteBottomClickHandler(this.frmSelezionaTipoPrescrizione_PulsanteAvantiClick);
            this.Controls.SetChildIndex(this.UltraGroupBoxZoom, 0);
            this.ultraTabPageControl1.ResumeLayout(false);
            this.ucEasyTableLayoutPanelDati.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTree)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteRicerca)).EndInit();
            this.ultraTabPageControl2.ResumeLayout(false);
            this.ucEasyTableLayoutPanelProtocolli.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteDataOraInizio)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTreeProtocolli)).EndInit();
            this.TableLayoutPanelZoom.ResumeLayout(false);
            this.ucEasyTableLayoutImmagine.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).EndInit();
            this.UltraTabControl.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBoxZoom)).EndInit();
            this.UltraGroupBoxZoom.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private ucEasyTableLayoutPanel TableLayoutPanelZoom;
        private ucEasyTableLayoutPanel ucEasyTableLayoutImmagine;
        private ucEasyPictureBox PictureBox;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBoxZoom;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private ucEasyTabControl UltraTabControl;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelDati;
        private ucEasyTreeView UltraTree;
        private ucEasyButton ubRicerca;
        private ucEasyTextBox uteRicerca;
        private ucEasyLabel lblRicerca;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl2;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelProtocolli;
        private ucEasyLabel lblDataOraInizio;
        private ucEasyTreeView UltraTreeProtocolli;
        private ucEasyDateTimeEditor udteDataOraInizio;
        private ucEasyProgressBar ucEasyProgressBarProtocolli;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
    }
}