namespace UnicodeSrl.ScciCore
{
    partial class ucAllegati
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucAllegati));
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override2 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab3 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab4 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance65 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedRight, new System.Guid("fd94bfc9-4ec3-4cb4-8c71-34153e8d6ed0"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("f3c96530-fac7-4b72-b128-ad0203550e59"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("fd94bfc9-4ec3-4cb4-8c71-34153e8d6ed0"), -1);
            this.ultraTabPageControl3 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucEasyTableLayoutPanelFolder = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTableLayoutPanelFolderAllegati = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lbAllegati = new UnicodeSrl.ScciCore.ucEasyListBox();
            this.tvFolder = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.pbFormato = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.ubVisualizza = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubSalva = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubCancella = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubModifica = new UnicodeSrl.ScciCore.ucEasyButton();
            this.pbAllegato = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.lblAllegato = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ultraTabPageControl4 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucEasyTableLayoutPanelGriglia = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.pnlFiltro = new System.Windows.Forms.Panel();
            this.ucEasyTableLayoutPanel1 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyGridFiltroUA = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.uchkFiltro = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ubApplicaFiltro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyGridFiltroTipo = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.utxtIDDocumento = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblContenuto = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.tvEntitaAssociate = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTabControlAllegati = new UnicodeSrl.ScciCore.ucEasyTabControl();
            this.ultraTabSharedControlsPage2 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ucEasyTableLayoutPanelAzioni = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubAddFolder = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubAddElettronico = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubAddVirtuale = new UnicodeSrl.ScciCore.ucEasyButton();
            this.UltraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._ucAllegatiUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucAllegatiUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucAllegatiUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucAllegatiUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucAllegatiAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.UltraPopupControlContainerFolderAdd = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.ultraTabPageControl3.SuspendLayout();
            this.ucEasyTableLayoutPanelFolder.SuspendLayout();
            this.ucEasyTableLayoutPanelFolderAllegati.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.lbAllegati)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tvFolder)).BeginInit();
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbFormato)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbAllegato)).BeginInit();
            this.ultraTabPageControl4.SuspendLayout();
            this.ucEasyTableLayoutPanelGriglia.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            this.pnlFiltro.SuspendLayout();
            this.ucEasyTableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroUA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroTipo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utxtIDDocumento)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tvEntitaAssociate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTabControlAllegati)).BeginInit();
            this.ucEasyTabControlAllegati.SuspendLayout();
            this.ucEasyTableLayoutPanelAzioni.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraDockManager)).BeginInit();
            this._ucAllegatiAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            this.SuspendLayout();
                                                this.ultraTabPageControl3.Controls.Add(this.ucEasyTableLayoutPanelFolder);
            this.ultraTabPageControl3.Location = new System.Drawing.Point(1, 35);
            this.ultraTabPageControl3.Name = "ultraTabPageControl3";
            this.ultraTabPageControl3.Size = new System.Drawing.Size(766, 590);
                                                this.ucEasyTableLayoutPanelFolder.ColumnCount = 3;
            this.ucEasyTableLayoutPanelFolder.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFolder.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.ucEasyTableLayoutPanelFolder.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFolder.Controls.Add(this.ucEasyTableLayoutPanelFolderAllegati, 1, 1);
            this.ucEasyTableLayoutPanelFolder.Controls.Add(this.ucEasyTableLayoutPanelFolderAllegatiDettaglio, 1, 2);
            this.ucEasyTableLayoutPanelFolder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFolder.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelFolder.Name = "ucEasyTableLayoutPanelFolder";
            this.ucEasyTableLayoutPanelFolder.RowCount = 4;
            this.ucEasyTableLayoutPanelFolder.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFolder.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.ucEasyTableLayoutPanelFolder.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.ucEasyTableLayoutPanelFolder.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFolder.Size = new System.Drawing.Size(766, 590);
            this.ucEasyTableLayoutPanelFolder.TabIndex = 0;
                                                this.ucEasyTableLayoutPanelFolderAllegati.ColumnCount = 2;
            this.ucEasyTableLayoutPanelFolderAllegati.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFolderAllegati.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.ucEasyTableLayoutPanelFolderAllegati.Controls.Add(this.lbAllegati, 1, 0);
            this.ucEasyTableLayoutPanelFolderAllegati.Controls.Add(this.tvFolder, 0, 0);
            this.ucEasyTableLayoutPanelFolderAllegati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFolderAllegati.Location = new System.Drawing.Point(10, 8);
            this.ucEasyTableLayoutPanelFolderAllegati.Name = "ucEasyTableLayoutPanelFolderAllegati";
            this.ucEasyTableLayoutPanelFolderAllegati.RowCount = 1;
            this.ucEasyTableLayoutPanelFolderAllegati.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelFolderAllegati.Size = new System.Drawing.Size(744, 484);
            this.ucEasyTableLayoutPanelFolderAllegati.TabIndex = 1;
                                                appearance1.FontData.SizeInPoints = 12.1194F;
            this.lbAllegati.Appearance = appearance1;
            this.lbAllegati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lbAllegati.Location = new System.Drawing.Point(226, 3);
            this.lbAllegati.Name = "lbAllegati";
            this.lbAllegati.Size = new System.Drawing.Size(515, 478);
            this.lbAllegati.TabIndex = 0;
            this.lbAllegati.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.lbAllegati.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.lbAllegati.ItemActivated += new Infragistics.Win.UltraWinListView.ItemActivatedEventHandler(this.lbAllegati_ItemActivated);
                                                appearance2.FontData.SizeInPoints = 15.58209F;
            this.tvFolder.Appearance = appearance2;
            this.tvFolder.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            this.tvFolder.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.tvFolder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tvFolder.HideSelection = false;
            this.tvFolder.Location = new System.Drawing.Point(3, 3);
            this.tvFolder.Name = "tvFolder";
            appearance3.BackColor = System.Drawing.Color.LightYellow;
            appearance3.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance3;
            _override1.SelectedNodeAppearance = appearance3;
            this.tvFolder.Override = _override1;
            this.tvFolder.Size = new System.Drawing.Size(217, 478);
            this.tvFolder.TabIndex = 1;
            this.tvFolder.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.tvFolder.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.tvFolder.AfterActivate += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.tvFolder_AfterActivate);
            this.tvFolder.Enter += new System.EventHandler(this.tvFolder_Enter);
                                                this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnCount = 7;
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 75F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 75F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 75F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 75F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 75F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 75F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Controls.Add(this.pbFormato, 1, 0);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Controls.Add(this.ubVisualizza, 6, 0);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Controls.Add(this.ubSalva, 5, 0);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Controls.Add(this.ubCancella, 4, 0);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Controls.Add(this.ubModifica, 3, 0);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Controls.Add(this.pbAllegato, 0, 0);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Controls.Add(this.lblAllegato, 2, 0);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Location = new System.Drawing.Point(10, 498);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Name = "ucEasyTableLayoutPanelFolderAllegatiDettaglio";
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.RowCount = 1;
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.Size = new System.Drawing.Size(744, 84);
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.TabIndex = 2;
                                                this.pbFormato.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbFormato.Location = new System.Drawing.Point(82, 12);
            this.pbFormato.Name = "pbFormato";
            this.pbFormato.ShortcutColor = System.Drawing.Color.Black;
            this.pbFormato.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbFormato.ShortcutKey = System.Windows.Forms.Keys.None;
            this.pbFormato.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbFormato.Size = new System.Drawing.Size(60, 60);
            this.pbFormato.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbFormato.TabIndex = 8;
            this.pbFormato.TabStop = false;
                                                appearance4.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance4.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance4.TextHAlignAsString = "Center";
            appearance4.TextVAlignAsString = "Bottom";
            this.ubVisualizza.Appearance = appearance4;
            this.ubVisualizza.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubVisualizza.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubVisualizza.ImageSize = new System.Drawing.Size(32, 32);
            this.ubVisualizza.Location = new System.Drawing.Point(672, 3);
            this.ubVisualizza.Name = "ubVisualizza";
            this.ubVisualizza.PercImageFill = 0.75F;
            this.ubVisualizza.ShortcutColor = System.Drawing.Color.Black;
            this.ubVisualizza.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubVisualizza.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubVisualizza.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubVisualizza.Size = new System.Drawing.Size(69, 78);
            this.ubVisualizza.TabIndex = 7;
            this.ubVisualizza.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubVisualizza.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubVisualizza.Click += new System.EventHandler(this.ubVisualizza_Click);
                                                appearance5.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance5.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance5.TextHAlignAsString = "Center";
            appearance5.TextVAlignAsString = "Bottom";
            this.ubSalva.Appearance = appearance5;
            this.ubSalva.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubSalva.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubSalva.ImageSize = new System.Drawing.Size(32, 32);
            this.ubSalva.Location = new System.Drawing.Point(597, 3);
            this.ubSalva.Name = "ubSalva";
            this.ubSalva.PercImageFill = 0.75F;
            this.ubSalva.ShortcutColor = System.Drawing.Color.Black;
            this.ubSalva.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubSalva.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubSalva.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubSalva.Size = new System.Drawing.Size(69, 78);
            this.ubSalva.TabIndex = 6;
            this.ubSalva.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubSalva.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubSalva.Click += new System.EventHandler(this.ubSalva_Click);
                                                appearance6.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance6.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance6.TextHAlignAsString = "Center";
            appearance6.TextVAlignAsString = "Bottom";
            this.ubCancella.Appearance = appearance6;
            this.ubCancella.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubCancella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCancella.ImageSize = new System.Drawing.Size(32, 32);
            this.ubCancella.Location = new System.Drawing.Point(522, 3);
            this.ubCancella.Name = "ubCancella";
            this.ubCancella.PercImageFill = 0.75F;
            this.ubCancella.ShortcutColor = System.Drawing.Color.Black;
            this.ubCancella.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubCancella.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubCancella.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubCancella.Size = new System.Drawing.Size(69, 78);
            this.ubCancella.TabIndex = 5;
            this.ubCancella.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubCancella.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubCancella.Click += new System.EventHandler(this.ubCancella_Click);
                                                appearance7.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance7.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance7.TextHAlignAsString = "Center";
            appearance7.TextVAlignAsString = "Bottom";
            this.ubModifica.Appearance = appearance7;
            this.ubModifica.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubModifica.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubModifica.ImageSize = new System.Drawing.Size(32, 32);
            this.ubModifica.Location = new System.Drawing.Point(447, 3);
            this.ubModifica.Name = "ubModifica";
            this.ubModifica.PercImageFill = 0.75F;
            this.ubModifica.ShortcutColor = System.Drawing.Color.Black;
            this.ubModifica.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubModifica.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubModifica.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubModifica.Size = new System.Drawing.Size(69, 78);
            this.ubModifica.TabIndex = 4;
            this.ubModifica.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubModifica.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubModifica.Click += new System.EventHandler(this.ubModifica_Click);
                                                this.pbAllegato.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbAllegato.Location = new System.Drawing.Point(7, 12);
            this.pbAllegato.Name = "pbAllegato";
            this.pbAllegato.ShortcutColor = System.Drawing.Color.Black;
            this.pbAllegato.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbAllegato.ShortcutKey = System.Windows.Forms.Keys.None;
            this.pbAllegato.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbAllegato.Size = new System.Drawing.Size(60, 60);
            this.pbAllegato.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbAllegato.TabIndex = 2;
            this.pbAllegato.TabStop = false;
                                                appearance8.FontData.SizeInPoints = 15.58209F;
            this.lblAllegato.Appearance = appearance8;
            this.lblAllegato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblAllegato.Location = new System.Drawing.Point(153, 3);
            this.lblAllegato.Name = "lblAllegato";
            this.lblAllegato.ShortcutColor = System.Drawing.Color.Black;
            this.lblAllegato.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblAllegato.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblAllegato.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblAllegato.Size = new System.Drawing.Size(288, 78);
            this.lblAllegato.TabIndex = 3;
            this.lblAllegato.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                this.ultraTabPageControl4.Controls.Add(this.ucEasyTableLayoutPanelGriglia);
            this.ultraTabPageControl4.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl4.Name = "ultraTabPageControl4";
            this.ultraTabPageControl4.Size = new System.Drawing.Size(766, 590);
                                                this.ucEasyTableLayoutPanelGriglia.ColumnCount = 3;
            this.ucEasyTableLayoutPanelGriglia.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelGriglia.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.ucEasyTableLayoutPanelGriglia.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelGriglia.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelGriglia.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelGriglia.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelGriglia.Controls.Add(this.ucEasyGrid, 1, 1);
            this.ucEasyTableLayoutPanelGriglia.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelGriglia.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelGriglia.Name = "ucEasyTableLayoutPanelGriglia";
            this.ucEasyTableLayoutPanelGriglia.RowCount = 9;
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 3F));
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanelGriglia.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelGriglia.Size = new System.Drawing.Size(766, 590);
            this.ucEasyTableLayoutPanelGriglia.TabIndex = 0;
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance9.BackColor = System.Drawing.SystemColors.Window;
            appearance9.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance9;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance10.FontData.BoldAsString = "True";
            appearance10.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance10;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance11.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance11.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance11.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance11.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance11;
            appearance12.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance12;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance13.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance13.BackColor2 = System.Drawing.SystemColors.Control;
            appearance13.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance13.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance13;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance14;
            appearance15.BackColor = System.Drawing.SystemColors.Highlight;
            appearance15.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance15;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance16.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance16;
            appearance17.BorderColor = System.Drawing.Color.Silver;
            appearance17.FontData.SizeInPoints = 22.50746F;
            appearance17.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance17;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance18.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance18;
            appearance19.BackColor = System.Drawing.SystemColors.Control;
            appearance19.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance19.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance19.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance19.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance19;
            appearance20.FontData.BoldAsString = "True";
            appearance20.FontData.SizeInPoints = 22.50746F;
            appearance20.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance20;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance21.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance21.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance21;
            appearance22.BackColor = System.Drawing.SystemColors.Window;
            appearance22.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance22;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance23.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance23;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.Location = new System.Drawing.Point(10, 8);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyTableLayoutPanelGriglia.SetRowSpan(this.ucEasyGrid, 7);
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(744, 569);
            this.ucEasyGrid.TabIndex = 0;
            this.ucEasyGrid.Text = "ucEasyGrid1";
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
            this.ucEasyGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucEasyGrid_ClickCell);
                                                this.pnlFiltro.Controls.Add(this.ucEasyTableLayoutPanel1);
            this.pnlFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlFiltro.Location = new System.Drawing.Point(0, 18);
            this.pnlFiltro.Name = "pnlFiltro";
            this.pnlFiltro.Size = new System.Drawing.Size(299, 620);
            this.pnlFiltro.TabIndex = 4;
                                                this.ucEasyTableLayoutPanel1.ColumnCount = 5;
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 47F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 24F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 27F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel1.Controls.Add(this.ucEasyGridFiltroUA, 1, 4);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.uchkFiltro, 3, 1);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.ubApplicaFiltro, 1, 8);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.ucEasyGridFiltroTipo, 1, 5);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.utxtIDDocumento, 1, 7);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.lblContenuto, 1, 6);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.tvEntitaAssociate, 1, 1);
            this.ucEasyTableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanel1.Name = "ucEasyTableLayoutPanel1";
            this.ucEasyTableLayoutPanel1.RowCount = 10;
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 27F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 32F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel1.Size = new System.Drawing.Size(299, 620);
            this.ucEasyTableLayoutPanel1.TabIndex = 1;
                                                this.ucEasyGridFiltroUA.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroUA.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanel1.SetColumnSpan(this.ucEasyGridFiltroUA, 3);
            this.ucEasyGridFiltroUA.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance24.BackColor = System.Drawing.SystemColors.Window;
            appearance24.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroUA.DisplayLayout.Appearance = appearance24;
            this.ucEasyGridFiltroUA.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroUA.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance25.FontData.BoldAsString = "True";
            appearance25.FontData.SizeInPoints = 12.1194F;
            this.ucEasyGridFiltroUA.DisplayLayout.CaptionAppearance = appearance25;
            this.ucEasyGridFiltroUA.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance26.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance26.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance26.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance26.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Appearance = appearance26;
            appearance27.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.BandLabelAppearance = appearance27;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance28.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance28.BackColor2 = System.Drawing.SystemColors.Control;
            appearance28.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance28.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.PromptAppearance = appearance28;
            this.ucEasyGridFiltroUA.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroUA.DisplayLayout.MaxRowScrollRegions = 1;
            appearance29.BackColor = System.Drawing.SystemColors.Window;
            appearance29.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ActiveCellAppearance = appearance29;
            appearance30.BackColor = System.Drawing.SystemColors.Highlight;
            appearance30.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ActiveRowAppearance = appearance30;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance31.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CardAreaAppearance = appearance31;
            appearance32.BorderColor = System.Drawing.Color.Silver;
            appearance32.FontData.SizeInPoints = 15.58209F;
            appearance32.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellAppearance = appearance32;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance33.FontData.SizeInPoints = 12.1194F;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.FilterRowAppearance = appearance33;
            appearance34.BackColor = System.Drawing.SystemColors.Control;
            appearance34.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance34.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance34.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance34.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.GroupByRowAppearance = appearance34;
            appearance35.FontData.BoldAsString = "True";
            appearance35.FontData.SizeInPoints = 12.1194F;
            appearance35.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderAppearance = appearance35;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance36.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance36.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowAlternateAppearance = appearance36;
            appearance37.BackColor = System.Drawing.SystemColors.Window;
            appearance37.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowAppearance = appearance37;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance38.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.TemplateAddRowAppearance = appearance38;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroUA.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroUA.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroUA.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroUA.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyGridFiltroUA.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyGridFiltroUA.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyGridFiltroUA.Location = new System.Drawing.Point(5, 139);
            this.ucEasyGridFiltroUA.Name = "ucEasyGridFiltroUA";
            this.ucEasyGridFiltroUA.ShowFilterRow = false;
            this.ucEasyGridFiltroUA.ShowGroupByBox = false;
            this.ucEasyGridFiltroUA.Size = new System.Drawing.Size(285, 161);
            this.ucEasyGridFiltroUA.TabIndex = 8;
            this.ucEasyGridFiltroUA.Text = "ucEasyGrid1";
            this.ucEasyGridFiltroUA.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroUA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltroUA_InitializeLayout);
                                                appearance39.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance39.ImageBackground")));
            appearance39.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance39.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance39.TextHAlignAsString = "Center";
            appearance39.TextVAlignAsString = "Bottom";
            this.uchkFiltro.Appearance = appearance39;
            this.uchkFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkFiltro.Checked = false;
            this.uchkFiltro.CheckedImage = null;
            this.uchkFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkFiltro.Location = new System.Drawing.Point(216, 9);
            this.uchkFiltro.Name = "uchkFiltro";
            this.uchkFiltro.PercImageFill = 0.75F;
            this.uchkFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.uchkFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkFiltro.ShortcutKey = System.Windows.Forms.Keys.F;
            this.uchkFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkFiltro.Size = new System.Drawing.Size(74, 87);
            this.uchkFiltro.TabIndex = 3;
            this.uchkFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.uchkFiltro.UNCheckedImage = null;
            this.uchkFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uchkFiltro.Click += new System.EventHandler(this.uchkFiltro_Click);
                                                appearance40.FontData.SizeInPoints = 22.50746F;
            appearance40.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance40.ImageBackground")));
            appearance40.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance40.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance40.TextHAlignAsString = "Center";
            appearance40.TextVAlignAsString = "Middle";
            this.ubApplicaFiltro.Appearance = appearance40;
            this.ubApplicaFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanel1.SetColumnSpan(this.ubApplicaFiltro, 3);
            this.ubApplicaFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltro.Location = new System.Drawing.Point(5, 572);
            this.ubApplicaFiltro.Name = "ubApplicaFiltro";
            this.ubApplicaFiltro.PercImageFill = 0.75F;
            this.ubApplicaFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.ubApplicaFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltro.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltro.Size = new System.Drawing.Size(285, 37);
            this.ubApplicaFiltro.TabIndex = 6;
            this.ubApplicaFiltro.Text = "Applica filtro";
            this.ubApplicaFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltro.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ucEasyGridFiltroTipo.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroTipo.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanel1.SetColumnSpan(this.ucEasyGridFiltroTipo, 3);
            this.ucEasyGridFiltroTipo.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroTipo.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance41.BackColor = System.Drawing.SystemColors.Window;
            appearance41.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroTipo.DisplayLayout.Appearance = appearance41;
            this.ucEasyGridFiltroTipo.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroTipo.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance42.FontData.BoldAsString = "True";
            appearance42.FontData.SizeInPoints = 12.1194F;
            this.ucEasyGridFiltroTipo.DisplayLayout.CaptionAppearance = appearance42;
            this.ucEasyGridFiltroTipo.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance43.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance43.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance43.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance43.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Appearance = appearance43;
            appearance44.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.BandLabelAppearance = appearance44;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance45.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance45.BackColor2 = System.Drawing.SystemColors.Control;
            appearance45.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance45.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.PromptAppearance = appearance45;
            this.ucEasyGridFiltroTipo.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroTipo.DisplayLayout.MaxRowScrollRegions = 1;
            appearance46.BackColor = System.Drawing.SystemColors.Window;
            appearance46.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ActiveCellAppearance = appearance46;
            appearance47.BackColor = System.Drawing.SystemColors.Highlight;
            appearance47.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ActiveRowAppearance = appearance47;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance48.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CardAreaAppearance = appearance48;
            appearance49.BorderColor = System.Drawing.Color.Silver;
            appearance49.FontData.SizeInPoints = 15.58209F;
            appearance49.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellAppearance = appearance49;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance50.FontData.SizeInPoints = 12.1194F;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.FilterRowAppearance = appearance50;
            appearance51.BackColor = System.Drawing.SystemColors.Control;
            appearance51.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance51.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance51.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance51.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.GroupByRowAppearance = appearance51;
            appearance52.FontData.BoldAsString = "True";
            appearance52.FontData.SizeInPoints = 12.1194F;
            appearance52.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderAppearance = appearance52;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance53.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance53.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowAlternateAppearance = appearance53;
            appearance54.BackColor = System.Drawing.SystemColors.Window;
            appearance54.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowAppearance = appearance54;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance55.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.TemplateAddRowAppearance = appearance55;
            scrollBarLook3.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroTipo.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroTipo.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroTipo.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroTipo.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyGridFiltroTipo.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyGridFiltroTipo.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyGridFiltroTipo.Location = new System.Drawing.Point(5, 306);
            this.ucEasyGridFiltroTipo.Name = "ucEasyGridFiltroTipo";
            this.ucEasyGridFiltroTipo.ShowFilterRow = false;
            this.ucEasyGridFiltroTipo.ShowGroupByBox = false;
            this.ucEasyGridFiltroTipo.Size = new System.Drawing.Size(285, 192);
            this.ucEasyGridFiltroTipo.TabIndex = 4;
            this.ucEasyGridFiltroTipo.Text = "ucEasyGrid1";
            this.ucEasyGridFiltroTipo.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltroTipo_InitializeLayout);
                                                appearance56.FontData.SizeInPoints = 22.50746F;
            this.utxtIDDocumento.Appearance = appearance56;
            this.utxtIDDocumento.AutoSize = false;
            this.ucEasyTableLayoutPanel1.SetColumnSpan(this.utxtIDDocumento, 3);
            this.utxtIDDocumento.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtIDDocumento.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtIDDocumento.Location = new System.Drawing.Point(5, 535);
            this.utxtIDDocumento.Name = "utxtIDDocumento";
            this.utxtIDDocumento.Size = new System.Drawing.Size(285, 31);
            this.utxtIDDocumento.TabIndex = 5;
            this.utxtIDDocumento.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.utxtIDDocumento.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.utxtIDDocumento.KeyDown += new System.Windows.Forms.KeyEventHandler(this.utxtIDDocumento_KeyDown);
                                                appearance57.FontData.SizeInPoints = 15.58209F;
            appearance57.TextVAlignAsString = "Bottom";
            this.lblContenuto.Appearance = appearance57;
            this.ucEasyTableLayoutPanel1.SetColumnSpan(this.lblContenuto, 3);
            this.lblContenuto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblContenuto.Location = new System.Drawing.Point(5, 504);
            this.lblContenuto.Name = "lblContenuto";
            this.lblContenuto.ShortcutColor = System.Drawing.Color.Black;
            this.lblContenuto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblContenuto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblContenuto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblContenuto.Size = new System.Drawing.Size(285, 25);
            this.lblContenuto.TabIndex = 4;
            this.lblContenuto.Text = "Ricerca Documento";
            this.lblContenuto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance58.FontData.SizeInPoints = 15.58209F;
            this.tvEntitaAssociate.Appearance = appearance58;
            this.tvEntitaAssociate.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            this.ucEasyTableLayoutPanel1.SetColumnSpan(this.tvEntitaAssociate, 2);
            this.tvEntitaAssociate.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.tvEntitaAssociate.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tvEntitaAssociate.HideSelection = false;
            this.tvEntitaAssociate.Location = new System.Drawing.Point(5, 9);
            this.tvEntitaAssociate.Name = "tvEntitaAssociate";
            appearance59.BackColor = System.Drawing.Color.LightYellow;
            appearance59.BackColor2 = System.Drawing.Color.Orange;
            _override2.ActiveNodeAppearance = appearance59;
            _override2.SelectedNodeAppearance = appearance59;
            this.tvEntitaAssociate.Override = _override2;
            this.ucEasyTableLayoutPanel1.SetRowSpan(this.tvEntitaAssociate, 2);
            this.tvEntitaAssociate.Size = new System.Drawing.Size(205, 118);
            this.tvEntitaAssociate.TabIndex = 7;
            this.tvEntitaAssociate.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.tvEntitaAssociate.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.UltraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(857, 638);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.ColumnCount = 2;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 91F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTabControlAllegati, 0, 0);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelAzioni, 1, 0);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 1;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 632F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(851, 632);
            this.ucEasyTableLayoutPanel.TabIndex = 3;
                                                appearance60.ForeColor = System.Drawing.Color.CornflowerBlue;
            this.ucEasyTabControlAllegati.Appearance = appearance60;
            this.ucEasyTabControlAllegati.Controls.Add(this.ultraTabSharedControlsPage2);
            this.ucEasyTabControlAllegati.Controls.Add(this.ultraTabPageControl3);
            this.ucEasyTabControlAllegati.Controls.Add(this.ultraTabPageControl4);
            this.ucEasyTabControlAllegati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTabControlAllegati.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTabControlAllegati.Name = "ucEasyTabControlAllegati";
            appearance61.FontData.BoldAsString = "True";
            appearance61.ForeColor = System.Drawing.Color.MidnightBlue;
            this.ucEasyTabControlAllegati.SelectedTabAppearance = appearance61;
            this.ucEasyTabControlAllegati.SharedControlsPage = this.ultraTabSharedControlsPage2;
            this.ucEasyTabControlAllegati.Size = new System.Drawing.Size(768, 626);
            appearance62.FontData.SizeInPoints = 15.58209F;
            this.ucEasyTabControlAllegati.TabHeaderAreaAppearance = appearance62;
            this.ucEasyTabControlAllegati.TabIndex = 2;
            this.ucEasyTabControlAllegati.TabLayoutStyle = Infragistics.Win.UltraWinTabs.TabLayoutStyle.SingleRowSizeToFit;
            ultraTab3.Key = "Folder";
            ultraTab3.TabPage = this.ultraTabPageControl3;
            ultraTab3.Text = "Folder";
            ultraTab4.Key = "Griglia";
            ultraTab4.TabPage = this.ultraTabPageControl4;
            ultraTab4.Text = "Griglia";
            this.ucEasyTabControlAllegati.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab3,
            ultraTab4});
            this.ucEasyTabControlAllegati.TabSize = new System.Drawing.Size(0, 34);
            this.ucEasyTabControlAllegati.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTabControlAllegati.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTabControlAllegati.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
            this.ucEasyTabControlAllegati.SelectedTabChanged += new Infragistics.Win.UltraWinTabControl.SelectedTabChangedEventHandler(this.ucEasyTabControlAllegati_SelectedTabChanged);
                                                this.ultraTabSharedControlsPage2.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage2.Name = "ultraTabSharedControlsPage2";
            this.ultraTabSharedControlsPage2.Size = new System.Drawing.Size(766, 590);
                                                this.ucEasyTableLayoutPanelAzioni.ColumnCount = 1;
            this.ucEasyTableLayoutPanelAzioni.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelAzioni.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelAzioni.Controls.Add(this.ubAddFolder, 0, 5);
            this.ucEasyTableLayoutPanelAzioni.Controls.Add(this.ubAddElettronico, 0, 1);
            this.ucEasyTableLayoutPanelAzioni.Controls.Add(this.ubAddVirtuale, 0, 3);
            this.ucEasyTableLayoutPanelAzioni.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelAzioni.Location = new System.Drawing.Point(777, 3);
            this.ucEasyTableLayoutPanelAzioni.Name = "ucEasyTableLayoutPanelAzioni";
            this.ucEasyTableLayoutPanelAzioni.RowCount = 8;
            this.ucEasyTableLayoutPanelAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 51F));
            this.ucEasyTableLayoutPanelAzioni.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelAzioni.Size = new System.Drawing.Size(71, 626);
            this.ucEasyTableLayoutPanelAzioni.TabIndex = 3;
                                                appearance63.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance63.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance63.TextHAlignAsString = "Center";
            appearance63.TextVAlignAsString = "Bottom";
            this.ubAddFolder.Appearance = appearance63;
            this.ubAddFolder.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAddFolder.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAddFolder.Location = new System.Drawing.Point(3, 207);
            this.ubAddFolder.Name = "ubAddFolder";
            this.ubAddFolder.PercImageFill = 0.75F;
            this.ubAddFolder.ShortcutColor = System.Drawing.Color.Black;
            this.ubAddFolder.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAddFolder.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAddFolder.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAddFolder.Size = new System.Drawing.Size(65, 87);
            this.ubAddFolder.TabIndex = 3;
            this.ubAddFolder.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubAddFolder.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAddFolder.Click += new System.EventHandler(this.ubAddFolder_Click);
                                                appearance64.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance64.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance64.TextHAlignAsString = "Center";
            appearance64.TextVAlignAsString = "Bottom";
            this.ubAddElettronico.Appearance = appearance64;
            this.ubAddElettronico.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAddElettronico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAddElettronico.Location = new System.Drawing.Point(3, 9);
            this.ubAddElettronico.Name = "ubAddElettronico";
            this.ubAddElettronico.PercImageFill = 0.75F;
            this.ubAddElettronico.ShortcutColor = System.Drawing.Color.Black;
            this.ubAddElettronico.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAddElettronico.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAddElettronico.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAddElettronico.Size = new System.Drawing.Size(65, 87);
            this.ubAddElettronico.TabIndex = 1;
            this.ubAddElettronico.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubAddElettronico.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAddElettronico.Click += new System.EventHandler(this.ubAddElettronico_Click);
                                                appearance65.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance65.ImageBackground")));
            appearance65.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance65.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance65.TextHAlignAsString = "Center";
            appearance65.TextVAlignAsString = "Bottom";
            this.ubAddVirtuale.Appearance = appearance65;
            this.ubAddVirtuale.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAddVirtuale.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAddVirtuale.Location = new System.Drawing.Point(3, 108);
            this.ubAddVirtuale.Name = "ubAddVirtuale";
            this.ubAddVirtuale.PercImageFill = 0.75F;
            this.ubAddVirtuale.ShortcutColor = System.Drawing.Color.Black;
            this.ubAddVirtuale.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAddVirtuale.ShortcutKey = System.Windows.Forms.Keys.V;
            this.ubAddVirtuale.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAddVirtuale.Size = new System.Drawing.Size(65, 87);
            this.ubAddVirtuale.TabIndex = 2;
            this.ubAddVirtuale.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubAddVirtuale.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAddVirtuale.Click += new System.EventHandler(this.ubAddVirtuale_Click);
                                                this.UltraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.UltraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.UltraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.UltraDockManager.CompressUnpinnedTabs = false;
            this.UltraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Control = this.pnlFiltro;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(299, -1);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(676, 209, 138, 140);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Settings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.ShowCaption = Infragistics.Win.DefaultableBoolean.True;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "FILTRO";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(229, 638);
            this.UltraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.UltraDockManager.HostControl = this;
            this.UltraDockManager.ShowCloseButton = false;
            this.UltraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.UltraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.UltraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.UltraDockManager_InitializePane);
                                                this._ucAllegatiUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._ucAllegatiUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAllegatiUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._ucAllegatiUnpinnedTabAreaLeft.Name = "_ucAllegatiUnpinnedTabAreaLeft";
            this._ucAllegatiUnpinnedTabAreaLeft.Owner = this.UltraDockManager;
            this._ucAllegatiUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 638);
            this._ucAllegatiUnpinnedTabAreaLeft.TabIndex = 1;
                                                this._ucAllegatiUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._ucAllegatiUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAllegatiUnpinnedTabAreaRight.Location = new System.Drawing.Point(857, 0);
            this._ucAllegatiUnpinnedTabAreaRight.Name = "_ucAllegatiUnpinnedTabAreaRight";
            this._ucAllegatiUnpinnedTabAreaRight.Owner = this.UltraDockManager;
            this._ucAllegatiUnpinnedTabAreaRight.Size = new System.Drawing.Size(23, 638);
            this._ucAllegatiUnpinnedTabAreaRight.TabIndex = 2;
                                                this._ucAllegatiUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._ucAllegatiUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAllegatiUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._ucAllegatiUnpinnedTabAreaTop.Name = "_ucAllegatiUnpinnedTabAreaTop";
            this._ucAllegatiUnpinnedTabAreaTop.Owner = this.UltraDockManager;
            this._ucAllegatiUnpinnedTabAreaTop.Size = new System.Drawing.Size(857, 0);
            this._ucAllegatiUnpinnedTabAreaTop.TabIndex = 3;
                                                this._ucAllegatiUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._ucAllegatiUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAllegatiUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 638);
            this._ucAllegatiUnpinnedTabAreaBottom.Name = "_ucAllegatiUnpinnedTabAreaBottom";
            this._ucAllegatiUnpinnedTabAreaBottom.Owner = this.UltraDockManager;
            this._ucAllegatiUnpinnedTabAreaBottom.Size = new System.Drawing.Size(857, 0);
            this._ucAllegatiUnpinnedTabAreaBottom.TabIndex = 4;
                                                this._ucAllegatiAutoHideControl.Controls.Add(this.dockableWindow1);
            this._ucAllegatiAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAllegatiAutoHideControl.Location = new System.Drawing.Point(793, 0);
            this._ucAllegatiAutoHideControl.Name = "_ucAllegatiAutoHideControl";
            this._ucAllegatiAutoHideControl.Owner = this.UltraDockManager;
            this._ucAllegatiAutoHideControl.Size = new System.Drawing.Size(64, 638);
            this._ucAllegatiAutoHideControl.TabIndex = 5;
                                                this.dockableWindow1.Controls.Add(this.pnlFiltro);
            this.dockableWindow1.Location = new System.Drawing.Point(-10000, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.UltraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(299, 638);
            this.dockableWindow1.TabIndex = 7;
                                                this.UltraPopupControlContainerFolderAdd.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainerFolderAdd_Opening);
            this.UltraPopupControlContainerFolderAdd.Opened += new System.EventHandler(this.UltraPopupControlContainerFolderAdd_Opened);
            this.UltraPopupControlContainerFolderAdd.Closed += new System.EventHandler(this.UltraPopupControlContainerFolderAdd_Closed);
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Right;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(623, 0);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.UltraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(234, 638);
            this.windowDockingArea1.TabIndex = 6;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this._ucAllegatiAutoHideControl);
            this.Controls.Add(this.UltraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._ucAllegatiUnpinnedTabAreaTop);
            this.Controls.Add(this._ucAllegatiUnpinnedTabAreaBottom);
            this.Controls.Add(this._ucAllegatiUnpinnedTabAreaLeft);
            this.Controls.Add(this._ucAllegatiUnpinnedTabAreaRight);
            this.Name = "ucAllegati";
            this.Size = new System.Drawing.Size(880, 638);
            this.Enter += new System.EventHandler(this.ucAllegati_Enter);
            this.ultraTabPageControl3.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFolder.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFolderAllegati.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.lbAllegati)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tvFolder)).EndInit();
            this.ucEasyTableLayoutPanelFolderAllegatiDettaglio.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbFormato)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbAllegato)).EndInit();
            this.ultraTabPageControl4.ResumeLayout(false);
            this.ucEasyTableLayoutPanelGriglia.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            this.pnlFiltro.ResumeLayout(false);
            this.ucEasyTableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroUA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroTipo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utxtIDDocumento)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tvEntitaAssociate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTabControlAllegati)).EndInit();
            this.ucEasyTabControlAllegati.ResumeLayout(false);
            this.ucEasyTableLayoutPanelAzioni.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraDockManager)).EndInit();
            this._ucAllegatiAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyTabControl ucEasyTabControlAllegati;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage2;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl3;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFolder;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFolderAllegati;
        private ucEasyListBox lbAllegati;
        private ucEasyTreeView tvFolder;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFolderAllegatiDettaglio;
        private ucEasyPictureBox pbFormato;
        private ucEasyButton ubVisualizza;
        private ucEasyButton ubSalva;
        private ucEasyButton ubCancella;
        private ucEasyButton ubModifica;
        private ucEasyPictureBox pbAllegato;
        private ucEasyLabel lblAllegato;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl4;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelGriglia;
        private ucEasyGrid ucEasyGrid;
        private ucEasyGrid ucEasyGridFiltroTipo;
        private ucEasyButton ubApplicaFiltro;
        private ucEasyTextBox utxtIDDocumento;
        private ucEasyLabel lblContenuto;
        private ucEasyStateButton uchkFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelAzioni;
        private ucEasyButton ubAddFolder;
        private ucEasyButton ubAddElettronico;
        private ucEasyButton ubAddVirtuale;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.UltraWinDock.UltraDockManager UltraDockManager;
        private Infragistics.Win.UltraWinDock.AutoHideControl _ucAllegatiAutoHideControl;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucAllegatiUnpinnedTabAreaBottom;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucAllegatiUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucAllegatiUnpinnedTabAreaRight;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucAllegatiUnpinnedTabAreaLeft;
        private System.Windows.Forms.Panel pnlFiltro;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel1;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainerFolderAdd;
        private ucEasyTreeView tvEntitaAssociate;
        private ucEasyGrid ucEasyGridFiltroUA;
    }
}
