namespace UnicodeSrl.ScciCore
{
    partial class ucBancheDati
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedBottom, new System.Guid("7beb4c0c-e21c-4a4d-835e-0fd57ea7ccdb"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("db5521c9-8ba1-419b-a937-b2a01a725e10"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("7beb4c0c-e21c-4a4d-835e-0fd57ea7ccdb"), -1);
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            this.pnlSchede = new System.Windows.Forms.Panel();
            this.tlpSchede = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTreeView = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ucEasyGridCampi = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.lblValore = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyLabel1 = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblSchede = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utxtValore = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ubInserisci = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubBrowse = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblURL = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utxtURL = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ucEasyGridRisorse = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyLabelTitolo = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.paneltlp = new System.Windows.Forms.Panel();
            this.tlpControlli = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ultraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._ucBancheDatiUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucBancheDatiUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucBancheDatiUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucBancheDatiUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucBancheDatiAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.pnlSchede.SuspendLayout();
            this.tlpSchede.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridCampi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utxtValore)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.utxtURL)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridRisorse)).BeginInit();
            this.paneltlp.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).BeginInit();
            this._ucBancheDatiAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            this.SuspendLayout();
                                                this.pnlSchede.Controls.Add(this.tlpSchede);
            this.pnlSchede.Location = new System.Drawing.Point(0, 18);
            this.pnlSchede.Name = "pnlSchede";
            this.pnlSchede.Size = new System.Drawing.Size(878, 296);
            this.pnlSchede.TabIndex = 19;
                                                this.tlpSchede.ColumnCount = 3;
            this.tlpSchede.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tlpSchede.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tlpSchede.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpSchede.Controls.Add(this.ucEasyTreeView, 0, 1);
            this.tlpSchede.Controls.Add(this.ucEasyGridCampi, 1, 1);
            this.tlpSchede.Controls.Add(this.lblValore, 2, 0);
            this.tlpSchede.Controls.Add(this.ucEasyLabel1, 1, 0);
            this.tlpSchede.Controls.Add(this.lblSchede, 0, 0);
            this.tlpSchede.Controls.Add(this.utxtValore, 2, 1);
            this.tlpSchede.Controls.Add(this.ubInserisci, 2, 2);
            this.tlpSchede.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpSchede.Location = new System.Drawing.Point(0, 0);
            this.tlpSchede.Name = "tlpSchede";
            this.tlpSchede.RowCount = 3;
            this.tlpSchede.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.tlpSchede.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 90F));
            this.tlpSchede.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tlpSchede.Size = new System.Drawing.Size(878, 296);
            this.tlpSchede.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 14.14634F;
            this.ucEasyTreeView.Appearance = appearance1;
            this.ucEasyTreeView.BorderStyle = Infragistics.Win.UIElementBorderStyle.None;
            this.ucEasyTreeView.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeView.HideSelection = false;
            this.ucEasyTreeView.Location = new System.Drawing.Point(3, 29);
            this.ucEasyTreeView.Name = "ucEasyTreeView";
            this.tlpSchede.SetRowSpan(this.ucEasyTreeView, 2);
            this.ucEasyTreeView.Scrollable = Infragistics.Win.UltraWinTree.Scrollbar.ShowIfNeeded;
            this.ucEasyTreeView.Size = new System.Drawing.Size(257, 264);
            this.ucEasyTreeView.TabIndex = 23;
            this.ucEasyTreeView.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeView.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeView.AfterActivate += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeView_AfterActivate);
                                                this.ucEasyGridCampi.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridCampi.ColonnaRTFResize = "";
            this.ucEasyGridCampi.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridCampi.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance2.BackColor = System.Drawing.SystemColors.Window;
            appearance2.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridCampi.DisplayLayout.Appearance = appearance2;
            this.ucEasyGridCampi.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridCampi.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance3.FontData.BoldAsString = "True";
            appearance3.FontData.SizeInPoints = 20.43361F;
            this.ucEasyGridCampi.DisplayLayout.CaptionAppearance = appearance3;
            this.ucEasyGridCampi.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance4.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance4.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance4.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridCampi.DisplayLayout.GroupByBox.Appearance = appearance4;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridCampi.DisplayLayout.GroupByBox.BandLabelAppearance = appearance5;
            this.ucEasyGridCampi.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridCampi.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridCampi.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance6.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance6.BackColor2 = System.Drawing.SystemColors.Control;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridCampi.DisplayLayout.GroupByBox.PromptAppearance = appearance6;
            this.ucEasyGridCampi.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridCampi.DisplayLayout.MaxRowScrollRegions = 1;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            appearance7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridCampi.DisplayLayout.Override.ActiveCellAppearance = appearance7;
            appearance8.BackColor = System.Drawing.SystemColors.Highlight;
            appearance8.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridCampi.DisplayLayout.Override.ActiveRowAppearance = appearance8;
            this.ucEasyGridCampi.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridCampi.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridCampi.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridCampi.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridCampi.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridCampi.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridCampi.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance9.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridCampi.DisplayLayout.Override.CardAreaAppearance = appearance9;
            appearance10.BorderColor = System.Drawing.Color.Silver;
            appearance10.FontData.SizeInPoints = 20.43361F;
            appearance10.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridCampi.DisplayLayout.Override.CellAppearance = appearance10;
            this.ucEasyGridCampi.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridCampi.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridCampi.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance11.FontData.SizeInPoints = 20.43361F;
            this.ucEasyGridCampi.DisplayLayout.Override.FilterRowAppearance = appearance11;
            appearance12.BackColor = System.Drawing.SystemColors.Control;
            appearance12.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance12.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance12.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance12.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridCampi.DisplayLayout.Override.GroupByRowAppearance = appearance12;
            appearance13.FontData.BoldAsString = "True";
            appearance13.FontData.SizeInPoints = 20.43361F;
            appearance13.TextHAlignAsString = "Center";
            this.ucEasyGridCampi.DisplayLayout.Override.HeaderAppearance = appearance13;
            this.ucEasyGridCampi.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridCampi.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance14.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance14.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridCampi.DisplayLayout.Override.RowAlternateAppearance = appearance14;
            appearance15.BackColor = System.Drawing.SystemColors.Window;
            appearance15.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridCampi.DisplayLayout.Override.RowAppearance = appearance15;
            this.ucEasyGridCampi.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridCampi.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridCampi.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridCampi.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridCampi.DisplayLayout.Override.TemplateAddRowAppearance = appearance16;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridCampi.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridCampi.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridCampi.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridCampi.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridCampi.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridCampi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridCampi.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridCampi.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridCampi.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridCampi.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridCampi.Location = new System.Drawing.Point(266, 29);
            this.ucEasyGridCampi.Name = "ucEasyGridCampi";
            this.tlpSchede.SetRowSpan(this.ucEasyGridCampi, 2);
            this.ucEasyGridCampi.ShowFilterRow = false;
            this.ucEasyGridCampi.ShowGroupByBox = false;
            this.ucEasyGridCampi.Size = new System.Drawing.Size(169, 264);
            this.ucEasyGridCampi.TabIndex = 22;
            this.ucEasyGridCampi.Text = "ucEasyGrid1";
            this.ucEasyGridCampi.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridCampi.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridCampi.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.EasyGrid_InitializeLayout);
            this.ucEasyGridCampi.AfterRowActivate += new System.EventHandler(this.ucEasyGridCampi_AfterRowActivate);
                                                appearance17.FontData.SizeInPoints = 14.14634F;
            appearance17.TextHAlignAsString = "Center";
            appearance17.TextVAlignAsString = "Middle";
            this.lblValore.Appearance = appearance17;
            this.lblValore.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblValore.Location = new System.Drawing.Point(441, 3);
            this.lblValore.Name = "lblValore";
            this.lblValore.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblValore.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblValore.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblValore.Size = new System.Drawing.Size(434, 20);
            this.lblValore.TabIndex = 21;
            this.lblValore.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance18.FontData.SizeInPoints = 14.14634F;
            appearance18.TextHAlignAsString = "Center";
            appearance18.TextVAlignAsString = "Middle";
            this.ucEasyLabel1.Appearance = appearance18;
            this.ucEasyLabel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabel1.Location = new System.Drawing.Point(266, 3);
            this.ucEasyLabel1.Name = "ucEasyLabel1";
            this.ucEasyLabel1.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabel1.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabel1.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabel1.Size = new System.Drawing.Size(169, 20);
            this.ucEasyLabel1.TabIndex = 20;
            this.ucEasyLabel1.Text = "Campi:";
            this.ucEasyLabel1.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance19.FontData.SizeInPoints = 14.14634F;
            appearance19.TextHAlignAsString = "Center";
            appearance19.TextVAlignAsString = "Middle";
            this.lblSchede.Appearance = appearance19;
            this.lblSchede.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblSchede.Location = new System.Drawing.Point(3, 3);
            this.lblSchede.Name = "lblSchede";
            this.lblSchede.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblSchede.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblSchede.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblSchede.Size = new System.Drawing.Size(257, 20);
            this.lblSchede.TabIndex = 19;
            this.lblSchede.Text = "Schede:";
            this.lblSchede.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance20.FontData.SizeInPoints = 14.14634F;
            appearance20.TextVAlignAsString = "Top";
            this.utxtValore.Appearance = appearance20;
            this.utxtValore.AutoSize = false;
            this.utxtValore.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtValore.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtValore.Location = new System.Drawing.Point(441, 29);
            this.utxtValore.Name = "utxtValore";
            this.utxtValore.Size = new System.Drawing.Size(434, 228);
            this.utxtValore.TabIndex = 18;
            this.utxtValore.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.utxtValore.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance21.FontData.SizeInPoints = 14.14634F;
            appearance21.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance21.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance21.TextHAlignAsString = "Center";
            appearance21.TextVAlignAsString = "Middle";
            this.ubInserisci.Appearance = appearance21;
            this.ubInserisci.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubInserisci.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubInserisci.Location = new System.Drawing.Point(441, 263);
            this.ubInserisci.Name = "ubInserisci";
            this.ubInserisci.PercImageFill = 0.75F;
            this.ubInserisci.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubInserisci.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubInserisci.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubInserisci.Size = new System.Drawing.Size(434, 30);
            this.ubInserisci.TabIndex = 17;
            this.ubInserisci.Text = "Inserisci Valore";
            this.ubInserisci.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubInserisci.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubInserisci.Click += new System.EventHandler(this.ubInserisci_Click);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(878, 601);
            this.ultraGroupBox.TabIndex = 5;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 6;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubBrowse, 4, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblURL, 2, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.utxtURL, 3, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGridRisorse, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyLabelTitolo, 2, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.paneltlp, 2, 2);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 5;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 83F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(872, 595);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance22.FontData.SizeInPoints = 14.14634F;
            appearance22.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance22.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance22.TextHAlignAsString = "Center";
            appearance22.TextVAlignAsString = "Middle";
            this.ubBrowse.Appearance = appearance22;
            this.ubBrowse.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubBrowse.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubBrowse.Location = new System.Drawing.Point(794, 541);
            this.ubBrowse.Name = "ubBrowse";
            this.ubBrowse.PercImageFill = 0.75F;
            this.ubBrowse.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubBrowse.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubBrowse.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubBrowse.Size = new System.Drawing.Size(63, 44);
            this.ubBrowse.TabIndex = 16;
            this.ubBrowse.Text = "Apri";
            this.ubBrowse.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubBrowse.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubBrowse.Click += new System.EventHandler(this.ubBrowse_Click);
                                                appearance23.FontData.SizeInPoints = 14.14634F;
            appearance23.TextHAlignAsString = "Center";
            appearance23.TextVAlignAsString = "Middle";
            this.lblURL.Appearance = appearance23;
            this.lblURL.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblURL.Location = new System.Drawing.Point(185, 541);
            this.lblURL.Name = "lblURL";
            this.lblURL.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblURL.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblURL.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblURL.Size = new System.Drawing.Size(37, 44);
            this.lblURL.TabIndex = 11;
            this.lblURL.Text = "Url:";
            this.lblURL.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance24.FontData.SizeInPoints = 11.00271F;
            this.utxtURL.Appearance = appearance24;
            this.utxtURL.AutoSize = false;
            this.utxtURL.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtURL.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtURL.Location = new System.Drawing.Point(228, 541);
            this.utxtURL.Multiline = true;
            this.utxtURL.Name = "utxtURL";
            this.utxtURL.Size = new System.Drawing.Size(560, 44);
            this.utxtURL.TabIndex = 10;
            this.utxtURL.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.utxtURL.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                this.ucEasyGridRisorse.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridRisorse.ColonnaRTFResize = "";
            this.ucEasyGridRisorse.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridRisorse.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance25.BackColor = System.Drawing.SystemColors.Window;
            appearance25.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridRisorse.DisplayLayout.Appearance = appearance25;
            this.ucEasyGridRisorse.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridRisorse.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance26.FontData.BoldAsString = "True";
            appearance26.FontData.SizeInPoints = 20.43361F;
            this.ucEasyGridRisorse.DisplayLayout.CaptionAppearance = appearance26;
            this.ucEasyGridRisorse.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance27.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance27.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance27.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance27.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridRisorse.DisplayLayout.GroupByBox.Appearance = appearance27;
            appearance28.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridRisorse.DisplayLayout.GroupByBox.BandLabelAppearance = appearance28;
            this.ucEasyGridRisorse.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridRisorse.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridRisorse.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance29.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance29.BackColor2 = System.Drawing.SystemColors.Control;
            appearance29.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance29.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridRisorse.DisplayLayout.GroupByBox.PromptAppearance = appearance29;
            this.ucEasyGridRisorse.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridRisorse.DisplayLayout.MaxRowScrollRegions = 1;
            appearance30.BackColor = System.Drawing.SystemColors.Window;
            appearance30.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridRisorse.DisplayLayout.Override.ActiveCellAppearance = appearance30;
            appearance31.BackColor = System.Drawing.SystemColors.Highlight;
            appearance31.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridRisorse.DisplayLayout.Override.ActiveRowAppearance = appearance31;
            this.ucEasyGridRisorse.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridRisorse.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridRisorse.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridRisorse.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridRisorse.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridRisorse.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridRisorse.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance32.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridRisorse.DisplayLayout.Override.CardAreaAppearance = appearance32;
            appearance33.BorderColor = System.Drawing.Color.Silver;
            appearance33.FontData.SizeInPoints = 20.43361F;
            appearance33.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridRisorse.DisplayLayout.Override.CellAppearance = appearance33;
            this.ucEasyGridRisorse.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridRisorse.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridRisorse.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance34.FontData.SizeInPoints = 20.43361F;
            this.ucEasyGridRisorse.DisplayLayout.Override.FilterRowAppearance = appearance34;
            appearance35.BackColor = System.Drawing.SystemColors.Control;
            appearance35.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance35.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance35.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance35.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridRisorse.DisplayLayout.Override.GroupByRowAppearance = appearance35;
            appearance36.FontData.BoldAsString = "True";
            appearance36.FontData.SizeInPoints = 20.43361F;
            appearance36.TextHAlignAsString = "Center";
            this.ucEasyGridRisorse.DisplayLayout.Override.HeaderAppearance = appearance36;
            this.ucEasyGridRisorse.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridRisorse.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance37.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance37.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridRisorse.DisplayLayout.Override.RowAlternateAppearance = appearance37;
            appearance38.BackColor = System.Drawing.SystemColors.Window;
            appearance38.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridRisorse.DisplayLayout.Override.RowAppearance = appearance38;
            this.ucEasyGridRisorse.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridRisorse.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridRisorse.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridRisorse.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance39.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridRisorse.DisplayLayout.Override.TemplateAddRowAppearance = appearance39;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridRisorse.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGridRisorse.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridRisorse.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridRisorse.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridRisorse.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridRisorse.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridRisorse.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridRisorse.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridRisorse.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridRisorse.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridRisorse.Location = new System.Drawing.Point(11, 8);
            this.ucEasyGridRisorse.Name = "ucEasyGridRisorse";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.ucEasyGridRisorse, 3);
            this.ucEasyGridRisorse.ShowFilterRow = false;
            this.ucEasyGridRisorse.ShowGroupByBox = false;
            this.ucEasyGridRisorse.Size = new System.Drawing.Size(168, 577);
            this.ucEasyGridRisorse.TabIndex = 9;
            this.ucEasyGridRisorse.Text = "ucEasyGrid1";
            this.ucEasyGridRisorse.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridRisorse.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridRisorse.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.EasyGrid_InitializeLayout);
            this.ucEasyGridRisorse.AfterRowActivate += new System.EventHandler(this.ucEasyGridRisorse_AfterRowActivate);
                                                appearance40.FontData.SizeInPoints = 14.14634F;
            appearance40.TextHAlignAsString = "Left";
            appearance40.TextVAlignAsString = "Top";
            this.ucEasyLabelTitolo.Appearance = appearance40;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyLabelTitolo, 3);
            this.ucEasyLabelTitolo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabelTitolo.Location = new System.Drawing.Point(185, 8);
            this.ucEasyLabelTitolo.Name = "ucEasyLabelTitolo";
            this.ucEasyLabelTitolo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabelTitolo.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabelTitolo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabelTitolo.Size = new System.Drawing.Size(672, 75);
            this.ucEasyLabelTitolo.TabIndex = 1;
            this.ucEasyLabelTitolo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                this.paneltlp.AutoScroll = true;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.paneltlp, 3);
            this.paneltlp.Controls.Add(this.tlpControlli);
            this.paneltlp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.paneltlp.Location = new System.Drawing.Point(185, 89);
            this.paneltlp.Name = "paneltlp";
            this.paneltlp.Size = new System.Drawing.Size(672, 446);
            this.paneltlp.TabIndex = 17;
                                                this.tlpControlli.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tlpControlli.ColumnCount = 2;
            this.tlpControlli.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tlpControlli.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.tlpControlli.Location = new System.Drawing.Point(3, 3);
            this.tlpControlli.Name = "tlpControlli";
            this.tlpControlli.RowCount = 1;
            this.tlpControlli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tlpControlli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tlpControlli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tlpControlli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tlpControlli.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tlpControlli.Size = new System.Drawing.Size(666, 30);
            this.tlpControlli.TabIndex = 18;
                                                this.ultraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.ultraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.ultraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.ultraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Control = this.pnlSchede;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(-1, 314);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(375, 233, 200, 100);
            dockableControlPane1.Pinned = false;
            appearance41.FontData.BoldAsString = "True";
            dockableControlPane1.Settings.Appearance = appearance41;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "SCHEDE";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(878, 344);
            dockAreaPane1.TextTab = "";
            this.ultraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.ultraDockManager.HostControl = this;
            this.ultraDockManager.ShowCloseButton = false;
            this.ultraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.ultraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.ultraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.ultraDockManager_InitializePane);
                                                this._ucBancheDatiUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._ucBancheDatiUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucBancheDatiUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._ucBancheDatiUnpinnedTabAreaLeft.Name = "_ucBancheDatiUnpinnedTabAreaLeft";
            this._ucBancheDatiUnpinnedTabAreaLeft.Owner = this.ultraDockManager;
            this._ucBancheDatiUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 624);
            this._ucBancheDatiUnpinnedTabAreaLeft.TabIndex = 6;
                                                this._ucBancheDatiUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._ucBancheDatiUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucBancheDatiUnpinnedTabAreaRight.Location = new System.Drawing.Point(878, 0);
            this._ucBancheDatiUnpinnedTabAreaRight.Name = "_ucBancheDatiUnpinnedTabAreaRight";
            this._ucBancheDatiUnpinnedTabAreaRight.Owner = this.ultraDockManager;
            this._ucBancheDatiUnpinnedTabAreaRight.Size = new System.Drawing.Size(0, 624);
            this._ucBancheDatiUnpinnedTabAreaRight.TabIndex = 7;
                                                this._ucBancheDatiUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._ucBancheDatiUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucBancheDatiUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._ucBancheDatiUnpinnedTabAreaTop.Name = "_ucBancheDatiUnpinnedTabAreaTop";
            this._ucBancheDatiUnpinnedTabAreaTop.Owner = this.ultraDockManager;
            this._ucBancheDatiUnpinnedTabAreaTop.Size = new System.Drawing.Size(878, 0);
            this._ucBancheDatiUnpinnedTabAreaTop.TabIndex = 8;
                                                this._ucBancheDatiUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._ucBancheDatiUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucBancheDatiUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 601);
            this._ucBancheDatiUnpinnedTabAreaBottom.Name = "_ucBancheDatiUnpinnedTabAreaBottom";
            this._ucBancheDatiUnpinnedTabAreaBottom.Owner = this.ultraDockManager;
            this._ucBancheDatiUnpinnedTabAreaBottom.Size = new System.Drawing.Size(878, 23);
            this._ucBancheDatiUnpinnedTabAreaBottom.TabIndex = 9;
                                                this._ucBancheDatiAutoHideControl.Controls.Add(this.dockableWindow1);
            this._ucBancheDatiAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucBancheDatiAutoHideControl.Location = new System.Drawing.Point(0, 282);
            this._ucBancheDatiAutoHideControl.Name = "_ucBancheDatiAutoHideControl";
            this._ucBancheDatiAutoHideControl.Owner = this.ultraDockManager;
            this._ucBancheDatiAutoHideControl.Size = new System.Drawing.Size(878, 319);
            this._ucBancheDatiAutoHideControl.TabIndex = 10;
                                                this.dockableWindow1.Controls.Add(this.pnlSchede);
            this.dockableWindow1.Location = new System.Drawing.Point(0, 5);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.ultraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(878, 314);
            this.dockableWindow1.TabIndex = 12;
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(0, 252);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.ultraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(878, 349);
            this.windowDockingArea1.TabIndex = 11;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._ucBancheDatiAutoHideControl);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._ucBancheDatiUnpinnedTabAreaTop);
            this.Controls.Add(this._ucBancheDatiUnpinnedTabAreaBottom);
            this.Controls.Add(this._ucBancheDatiUnpinnedTabAreaRight);
            this.Controls.Add(this._ucBancheDatiUnpinnedTabAreaLeft);
            this.Name = "ucBancheDati";
            this.Size = new System.Drawing.Size(878, 624);
            this.pnlSchede.ResumeLayout(false);
            this.tlpSchede.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridCampi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utxtValore)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.utxtURL)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridRisorse)).EndInit();
            this.paneltlp.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).EndInit();
            this._ucBancheDatiAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyButton ubBrowse;
        private ucEasyLabel lblURL;
        private ucEasyTextBox utxtURL;
        private ucEasyGrid ucEasyGridRisorse;
        private ucEasyLabel ucEasyLabelTitolo;
        private System.Windows.Forms.Panel paneltlp;
        private ucEasyTableLayoutPanel tlpControlli;
        private Infragistics.Win.UltraWinDock.UltraDockManager ultraDockManager;
        private Infragistics.Win.UltraWinDock.AutoHideControl _ucBancheDatiAutoHideControl;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucBancheDatiUnpinnedTabAreaRight;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucBancheDatiUnpinnedTabAreaLeft;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucBancheDatiUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucBancheDatiUnpinnedTabAreaBottom;
        private System.Windows.Forms.Panel pnlSchede;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private ucEasyTableLayoutPanel tlpSchede;
        private ucEasyButton ubInserisci;
        private ucEasyLabel lblValore;
        private ucEasyLabel ucEasyLabel1;
        private ucEasyLabel lblSchede;
        private ucEasyTextBox utxtValore;
        private ucEasyGrid ucEasyGridCampi;
        private ucEasyTreeView ucEasyTreeView;

    }
}
