namespace UnicodeSrl.ScciCore
{
    partial class ucCartelleInVisioneMenu
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucCartelleInVisioneMenu));
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.tlpMainGrid = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.tlpFiltri = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTreeViewFiltroStatoTrasferimento = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.UltraGridUO = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.UltraGridCartellePaziente = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ubRicerca = new UnicodeSrl.ScciCore.ucEasyButton();
            this.lblRicerca = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.uteRicerca = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ubAzzera = new UnicodeSrl.ScciCore.ucEasyButton();
            this.UltraGridCartelleAmbulatoriali = new UnicodeSrl.ScciCore.ucEasyGrid();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.tlpMainGrid.SuspendLayout();
            this.tlpFiltri.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewFiltroStatoTrasferimento)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridUO)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridCartellePaziente)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteRicerca)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridCartelleAmbulatoriali)).BeginInit();
            this.SuspendLayout();
                                                this.UltraGroupBox.Controls.Add(this.tlpMainGrid);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(968, 600);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.tlpMainGrid.BackColor = System.Drawing.Color.Transparent;
            this.tlpMainGrid.ColumnCount = 4;
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.tlpMainGrid.Controls.Add(this.tlpFiltri, 2, 1);
            this.tlpMainGrid.Controls.Add(this.UltraGridCartellePaziente, 0, 1);
            this.tlpMainGrid.Controls.Add(this.ubRicerca, 2, 0);
            this.tlpMainGrid.Controls.Add(this.lblRicerca, 0, 0);
            this.tlpMainGrid.Controls.Add(this.uteRicerca, 1, 0);
            this.tlpMainGrid.Controls.Add(this.ubAzzera, 3, 0);
            this.tlpMainGrid.Controls.Add(this.UltraGridCartelleAmbulatoriali, 0, 3);
            this.tlpMainGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpMainGrid.Location = new System.Drawing.Point(3, 3);
            this.tlpMainGrid.Name = "tlpMainGrid";
            this.tlpMainGrid.RowCount = 5;
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpMainGrid.Size = new System.Drawing.Size(962, 594);
            this.tlpMainGrid.TabIndex = 0;
                                                this.tlpFiltri.ColumnCount = 1;
            this.tlpMainGrid.SetColumnSpan(this.tlpFiltri, 2);
            this.tlpFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpFiltri.Controls.Add(this.ucEasyTreeViewFiltroStatoTrasferimento, 0, 2);
            this.tlpFiltri.Controls.Add(this.UltraGridUO, 0, 0);
            this.tlpFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpFiltri.Location = new System.Drawing.Point(802, 53);
            this.tlpFiltri.Name = "tlpFiltri";
            this.tlpFiltri.RowCount = 3;
            this.tlpMainGrid.SetRowSpan(this.tlpFiltri, 2);
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 49F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 49F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpFiltri.Size = new System.Drawing.Size(157, 266);
            this.tlpFiltri.TabIndex = 9;
                                                appearance1.FontData.SizeInPoints = 13.56716F;
            this.ucEasyTreeViewFiltroStatoTrasferimento.Appearance = appearance1;
            this.ucEasyTreeViewFiltroStatoTrasferimento.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTreeViewFiltroStatoTrasferimento.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewFiltroStatoTrasferimento.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewFiltroStatoTrasferimento.ExpansionIndicatorSize = new System.Drawing.Size(6, 6);
            this.ucEasyTreeViewFiltroStatoTrasferimento.HideExpansionIndicators = Infragistics.Win.UltraWinTree.HideExpansionIndicators.OnMouseLeave;
            this.ucEasyTreeViewFiltroStatoTrasferimento.HideSelection = false;
            this.ucEasyTreeViewFiltroStatoTrasferimento.ImagePadding = 0;
            this.ucEasyTreeViewFiltroStatoTrasferimento.Indent = 6;
            this.ucEasyTreeViewFiltroStatoTrasferimento.Location = new System.Drawing.Point(3, 138);
            this.ucEasyTreeViewFiltroStatoTrasferimento.Name = "ucEasyTreeViewFiltroStatoTrasferimento";
            appearance2.BackColor = System.Drawing.Color.LightYellow;
            appearance2.BackColor2 = System.Drawing.Color.Orange;
            _override1.SelectedNodeAppearance = appearance2;
            this.ucEasyTreeViewFiltroStatoTrasferimento.Override = _override1;
            this.ucEasyTreeViewFiltroStatoTrasferimento.Size = new System.Drawing.Size(151, 125);
            this.ucEasyTreeViewFiltroStatoTrasferimento.TabIndex = 16;
            this.ucEasyTreeViewFiltroStatoTrasferimento.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeViewFiltroStatoTrasferimento.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeViewFiltroStatoTrasferimento.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeViewFiltroStatoTrasferimento_AfterCheck);
                                                this.UltraGridUO.ColonnaRTFControlloContenuto = false;
            this.UltraGridUO.ColonnaRTFResize = "";
            this.UltraGridUO.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridUO.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance3.BackColor = System.Drawing.SystemColors.Window;
            appearance3.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridUO.DisplayLayout.Appearance = appearance3;
            this.UltraGridUO.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridUO.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.FontData.BoldAsString = "True";
            appearance4.FontData.SizeInPoints = 10.55224F;
            this.UltraGridUO.DisplayLayout.CaptionAppearance = appearance4;
            this.UltraGridUO.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance5.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance5.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance5.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridUO.DisplayLayout.GroupByBox.Appearance = appearance5;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridUO.DisplayLayout.GroupByBox.BandLabelAppearance = appearance6;
            this.UltraGridUO.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridUO.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridUO.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance7.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance7.BackColor2 = System.Drawing.SystemColors.Control;
            appearance7.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance7.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridUO.DisplayLayout.GroupByBox.PromptAppearance = appearance7;
            this.UltraGridUO.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridUO.DisplayLayout.MaxRowScrollRegions = 1;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            appearance8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridUO.DisplayLayout.Override.ActiveCellAppearance = appearance8;
            appearance9.BackColor = System.Drawing.SystemColors.Highlight;
            appearance9.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridUO.DisplayLayout.Override.ActiveRowAppearance = appearance9;
            this.UltraGridUO.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridUO.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridUO.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUO.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUO.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUO.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridUO.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridUO.DisplayLayout.Override.CardAreaAppearance = appearance10;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            appearance11.FontData.SizeInPoints = 10.55224F;
            appearance11.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridUO.DisplayLayout.Override.CellAppearance = appearance11;
            this.UltraGridUO.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridUO.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridUO.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance12.FontData.SizeInPoints = 10.55224F;
            this.UltraGridUO.DisplayLayout.Override.FilterRowAppearance = appearance12;
            appearance13.BackColor = System.Drawing.SystemColors.Control;
            appearance13.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance13.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance13.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance13.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridUO.DisplayLayout.Override.GroupByRowAppearance = appearance13;
            appearance14.FontData.BoldAsString = "True";
            appearance14.FontData.SizeInPoints = 10.55224F;
            appearance14.TextHAlignAsString = "Center";
            this.UltraGridUO.DisplayLayout.Override.HeaderAppearance = appearance14;
            this.UltraGridUO.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridUO.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance15.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance15.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridUO.DisplayLayout.Override.RowAlternateAppearance = appearance15;
            appearance16.BackColor = System.Drawing.SystemColors.Window;
            appearance16.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridUO.DisplayLayout.Override.RowAppearance = appearance16;
            this.UltraGridUO.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUO.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridUO.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridUO.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance17.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridUO.DisplayLayout.Override.TemplateAddRowAppearance = appearance17;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridUO.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.UltraGridUO.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridUO.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridUO.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridUO.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridUO.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridUO.FattoreRidimensionamentoRTF = 21;
            this.UltraGridUO.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridUO.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridUO.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridUO.Location = new System.Drawing.Point(3, 3);
            this.UltraGridUO.Name = "UltraGridUO";
            this.UltraGridUO.ShowFilterRow = false;
            this.UltraGridUO.ShowGroupByBox = false;
            this.UltraGridUO.Size = new System.Drawing.Size(151, 124);
            this.UltraGridUO.TabIndex = 4;
            this.UltraGridUO.Text = "ucEasyGrid1";
            this.UltraGridUO.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridUO.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridUO.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridUO_InitializeLayout);
                                                this.UltraGridCartellePaziente.ColonnaRTFControlloContenuto = false;
            this.UltraGridCartellePaziente.ColonnaRTFResize = "";
            this.tlpMainGrid.SetColumnSpan(this.UltraGridCartellePaziente, 2);
            this.UltraGridCartellePaziente.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridCartellePaziente.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance18.BackColor = System.Drawing.SystemColors.Window;
            appearance18.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridCartellePaziente.DisplayLayout.Appearance = appearance18;
            this.UltraGridCartellePaziente.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridCartellePaziente.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance19.FontData.BoldAsString = "True";
            appearance19.FontData.SizeInPoints = 13.56716F;
            this.UltraGridCartellePaziente.DisplayLayout.CaptionAppearance = appearance19;
            this.UltraGridCartellePaziente.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance20.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance20.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance20.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance20.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridCartellePaziente.DisplayLayout.GroupByBox.Appearance = appearance20;
            appearance21.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridCartellePaziente.DisplayLayout.GroupByBox.BandLabelAppearance = appearance21;
            this.UltraGridCartellePaziente.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridCartellePaziente.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridCartellePaziente.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance22.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance22.BackColor2 = System.Drawing.SystemColors.Control;
            appearance22.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance22.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridCartellePaziente.DisplayLayout.GroupByBox.PromptAppearance = appearance22;
            this.UltraGridCartellePaziente.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridCartellePaziente.DisplayLayout.MaxRowScrollRegions = 1;
            appearance23.BackColor = System.Drawing.SystemColors.Window;
            appearance23.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridCartellePaziente.DisplayLayout.Override.ActiveCellAppearance = appearance23;
            appearance24.BackColor = System.Drawing.SystemColors.Highlight;
            appearance24.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridCartellePaziente.DisplayLayout.Override.ActiveRowAppearance = appearance24;
            this.UltraGridCartellePaziente.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridCartellePaziente.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridCartellePaziente.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartellePaziente.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartellePaziente.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartellePaziente.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridCartellePaziente.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance25.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridCartellePaziente.DisplayLayout.Override.CardAreaAppearance = appearance25;
            appearance26.BorderColor = System.Drawing.Color.Silver;
            appearance26.FontData.SizeInPoints = 10.55224F;
            appearance26.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridCartellePaziente.DisplayLayout.Override.CellAppearance = appearance26;
            this.UltraGridCartellePaziente.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridCartellePaziente.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridCartellePaziente.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance27.FontData.SizeInPoints = 13.56716F;
            this.UltraGridCartellePaziente.DisplayLayout.Override.FilterRowAppearance = appearance27;
            appearance28.BackColor = System.Drawing.SystemColors.Control;
            appearance28.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance28.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance28.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance28.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridCartellePaziente.DisplayLayout.Override.GroupByRowAppearance = appearance28;
            appearance29.FontData.BoldAsString = "True";
            appearance29.FontData.SizeInPoints = 13.56716F;
            appearance29.TextHAlignAsString = "Center";
            this.UltraGridCartellePaziente.DisplayLayout.Override.HeaderAppearance = appearance29;
            this.UltraGridCartellePaziente.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridCartellePaziente.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance30.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance30.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridCartellePaziente.DisplayLayout.Override.RowAlternateAppearance = appearance30;
            appearance31.BackColor = System.Drawing.SystemColors.Window;
            appearance31.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridCartellePaziente.DisplayLayout.Override.RowAppearance = appearance31;
            this.UltraGridCartellePaziente.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartellePaziente.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridCartellePaziente.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridCartellePaziente.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance32.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridCartellePaziente.DisplayLayout.Override.TemplateAddRowAppearance = appearance32;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridCartellePaziente.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.UltraGridCartellePaziente.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridCartellePaziente.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridCartellePaziente.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridCartellePaziente.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridCartellePaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridCartellePaziente.FattoreRidimensionamentoRTF = 21;
            this.UltraGridCartellePaziente.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridCartellePaziente.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridCartellePaziente.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridCartellePaziente.Location = new System.Drawing.Point(3, 53);
            this.UltraGridCartellePaziente.Name = "UltraGridCartellePaziente";
            this.UltraGridCartellePaziente.ShowFilterRow = false;
            this.UltraGridCartellePaziente.ShowGroupByBox = false;
            this.UltraGridCartellePaziente.Size = new System.Drawing.Size(793, 246);
            this.UltraGridCartellePaziente.TabIndex = 8;
            this.UltraGridCartellePaziente.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridCartellePaziente.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartellePaziente.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridCartellePaziente_InitializeLayout);
            this.UltraGridCartellePaziente.AfterRowActivate += new System.EventHandler(this.UltraGridCartellePaziente_AfterRowActivate);
                                                appearance33.FontData.SizeInPoints = 19.59702F;
            appearance33.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance33.ImageBackground")));
            appearance33.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance33.ImageVAlign = Infragistics.Win.VAlign.Top;
            this.ubRicerca.Appearance = appearance33;
            this.ubRicerca.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRicerca.Location = new System.Drawing.Point(799, 3);
            this.ubRicerca.Margin = new System.Windows.Forms.Padding(0, 3, 1, 3);
            this.ubRicerca.Name = "ubRicerca";
            this.ubRicerca.PercImageFill = 0.75F;
            this.ubRicerca.ShortcutColor = System.Drawing.Color.Black;
            this.ubRicerca.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubRicerca.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubRicerca.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubRicerca.Size = new System.Drawing.Size(80, 44);
            this.ubRicerca.TabIndex = 2;
            this.ubRicerca.Text = "Ricerca";
            this.ubRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubRicerca.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubRicerca.WrapText = false;
            this.ubRicerca.Click += new System.EventHandler(this.ubRicerca_Click);
                                                appearance34.FontData.SizeInPoints = 19.59702F;
            appearance34.TextVAlignAsString = "Middle";
            this.lblRicerca.Appearance = appearance34;
            this.lblRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRicerca.Location = new System.Drawing.Point(3, 3);
            this.lblRicerca.Name = "lblRicerca";
            this.lblRicerca.ShortcutColor = System.Drawing.Color.Black;
            this.lblRicerca.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblRicerca.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblRicerca.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblRicerca.Size = new System.Drawing.Size(144, 44);
            this.lblRicerca.TabIndex = 0;
            this.lblRicerca.Text = "Ricerca";
            this.lblRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.uteRicerca.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            appearance35.FontData.SizeInPoints = 13.56716F;
            this.uteRicerca.Appearance = appearance35;
            this.uteRicerca.AutoSize = false;
            this.uteRicerca.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteRicerca.Location = new System.Drawing.Point(153, 9);
            this.uteRicerca.Name = "uteRicerca";
            this.uteRicerca.Size = new System.Drawing.Size(643, 31);
            this.uteRicerca.TabIndex = 1;
            this.uteRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uteRicerca.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uteRicerca.KeyDown += new System.Windows.Forms.KeyEventHandler(this.uteRicerca_KeyDown);
                                                appearance36.FontData.SizeInPoints = 19.59702F;
            appearance36.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance36.ImageVAlign = Infragistics.Win.VAlign.Top;
            this.ubAzzera.Appearance = appearance36;
            this.ubAzzera.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAzzera.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAzzera.Location = new System.Drawing.Point(881, 3);
            this.ubAzzera.Margin = new System.Windows.Forms.Padding(1, 3, 1, 3);
            this.ubAzzera.Name = "ubAzzera";
            this.ubAzzera.PercImageFill = 0.75F;
            this.ubAzzera.ShortcutColor = System.Drawing.Color.Black;
            this.ubAzzera.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAzzera.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAzzera.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAzzera.Size = new System.Drawing.Size(80, 44);
            this.ubAzzera.TabIndex = 3;
            this.ubAzzera.Text = "Azzera";
            this.ubAzzera.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubAzzera.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAzzera.WrapText = false;
            this.ubAzzera.Click += new System.EventHandler(this.ubAzzera_Click);
                                                this.UltraGridCartelleAmbulatoriali.ColonnaRTFControlloContenuto = false;
            this.UltraGridCartelleAmbulatoriali.ColonnaRTFResize = "";
            this.tlpMainGrid.SetColumnSpan(this.UltraGridCartelleAmbulatoriali, 4);
            this.UltraGridCartelleAmbulatoriali.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridCartelleAmbulatoriali.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance37.BackColor = System.Drawing.SystemColors.Window;
            appearance37.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Appearance = appearance37;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance38.FontData.BoldAsString = "True";
            appearance38.FontData.SizeInPoints = 13.56716F;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.CaptionAppearance = appearance38;
            appearance39.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance39.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance39.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance39.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.GroupByBox.Appearance = appearance39;
            appearance40.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.GroupByBox.BandLabelAppearance = appearance40;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance41.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance41.BackColor2 = System.Drawing.SystemColors.Control;
            appearance41.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance41.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.GroupByBox.PromptAppearance = appearance41;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.MaxRowScrollRegions = 1;
            appearance42.BackColor = System.Drawing.SystemColors.Window;
            appearance42.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.ActiveCellAppearance = appearance42;
            appearance43.BackColor = System.Drawing.SystemColors.Highlight;
            appearance43.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.ActiveRowAppearance = appearance43;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance44.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.CardAreaAppearance = appearance44;
            appearance45.BorderColor = System.Drawing.Color.Silver;
            appearance45.FontData.SizeInPoints = 13.56716F;
            appearance45.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.CellAppearance = appearance45;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance46.FontData.SizeInPoints = 13.56716F;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.FilterRowAppearance = appearance46;
            appearance47.BackColor = System.Drawing.SystemColors.Control;
            appearance47.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance47.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance47.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance47.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.GroupByRowAppearance = appearance47;
            appearance48.FontData.BoldAsString = "True";
            appearance48.FontData.SizeInPoints = 13.56716F;
            appearance48.TextHAlignAsString = "Center";
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.HeaderAppearance = appearance48;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance49.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance49.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.RowAlternateAppearance = appearance49;
            appearance50.BackColor = System.Drawing.SystemColors.Window;
            appearance50.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.RowAppearance = appearance50;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance51.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.Override.TemplateAddRowAppearance = appearance51;
            scrollBarLook3.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridCartelleAmbulatoriali.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridCartelleAmbulatoriali.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridCartelleAmbulatoriali.FattoreRidimensionamentoRTF = 21;
            this.UltraGridCartelleAmbulatoriali.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridCartelleAmbulatoriali.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridCartelleAmbulatoriali.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridCartelleAmbulatoriali.Location = new System.Drawing.Point(3, 325);
            this.UltraGridCartelleAmbulatoriali.Name = "UltraGridCartelleAmbulatoriali";
            this.UltraGridCartelleAmbulatoriali.ShowFilterRow = false;
            this.UltraGridCartelleAmbulatoriali.ShowGroupByBox = false;
            this.UltraGridCartelleAmbulatoriali.Size = new System.Drawing.Size(956, 246);
            this.UltraGridCartelleAmbulatoriali.TabIndex = 5;
            this.UltraGridCartelleAmbulatoriali.Text = "UltraGridCartelleAmbulatoriali";
            this.UltraGridCartelleAmbulatoriali.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridCartelleAmbulatoriali.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridCartelleAmbulatoriali.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridCartelleAmbulatoriali_InitializeLayout);
            this.UltraGridCartelleAmbulatoriali.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGridCartelleAmbulatoriali_InitializeRow);
            this.UltraGridCartelleAmbulatoriali.AfterRowActivate += new System.EventHandler(this.UltraGridCartelleAmbulatoriali_AfterRowActivate);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.UltraGroupBox);
            this.Name = "ucCartelleInVisioneMenu";
            this.Size = new System.Drawing.Size(968, 600);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.tlpMainGrid.ResumeLayout(false);
            this.tlpFiltri.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewFiltroStatoTrasferimento)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridUO)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridCartellePaziente)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteRicerca)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridCartelleAmbulatoriali)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private ucEasyTableLayoutPanel tlpMainGrid;
        private ucEasyLabel lblRicerca;
        private ucEasyTextBox uteRicerca;
        private ucEasyButton ubAzzera;
        private ucEasyButton ubRicerca;
        private ucEasyGrid UltraGridCartelleAmbulatoriali;
        internal ucEasyGrid UltraGridCartellePaziente;
        private ucEasyTableLayoutPanel tlpFiltri;
        private ucEasyTreeView ucEasyTreeViewFiltroStatoTrasferimento;
        private ucEasyGrid UltraGridUO;
    }
}
