namespace UnicodeSrl.ScciCore
{
    partial class ucConsulenzeTrasversali
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem10 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem11 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem12 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem13 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem14 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem15 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem16 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem17 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem18 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucConsulenzeTrasversali));
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedRight, new System.Guid("13e5a250-8102-48cd-90da-9bcd165034bd"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("ebf50a39-032d-4ecf-970b-7ba496e8c4d0"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("13e5a250-8102-48cd-90da-9bcd165034bd"), -1);
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            this.pnlFiltro = new System.Windows.Forms.Panel();
            this.ucEasyTableLayoutPanelFiltro1 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyGridFiltroUA = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPanel1 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblFiltroContenuto = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utxtFiltroContenuto = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ucEasyTreeViewFiltroTipo = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ucEasyGridFiltroStato = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPanelFiltro2 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.udteFiltroDA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.udteFiltroA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroDa = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblFiltroA = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.drFiltro = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.ubApplicaFiltro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ultraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucDiarioClinicoPazienteAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.utxtRicerca = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblRicerca = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.pnlFiltro.SuspendLayout();
            this.ucEasyTableLayoutPanelFiltro1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroUA)).BeginInit();
            this.ucEasyTableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.utxtFiltroContenuto)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewFiltroTipo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).BeginInit();
            this.ucEasyTableLayoutPanelFiltro2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).BeginInit();
            this._ucDiarioClinicoPazienteAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.utxtRicerca)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            this.SuspendLayout();
                                                this.pnlFiltro.BackColor = System.Drawing.Color.Transparent;
            this.pnlFiltro.Controls.Add(this.ucEasyTableLayoutPanelFiltro1);
            this.pnlFiltro.Location = new System.Drawing.Point(0, 18);
            this.pnlFiltro.Name = "pnlFiltro";
            this.pnlFiltro.Size = new System.Drawing.Size(787, 606);
            this.pnlFiltro.TabIndex = 5;
                                                this.ucEasyTableLayoutPanelFiltro1.ColumnCount = 9;
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyGridFiltroUA, 5, 1);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTableLayoutPanel1, 1, 4);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTreeViewFiltroTipo, 1, 1);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyGridFiltroStato, 5, 2);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTableLayoutPanelFiltro2, 1, 5);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ubApplicaFiltro, 5, 7);
            this.ucEasyTableLayoutPanelFiltro1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltro1.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelFiltro1.Name = "ucEasyTableLayoutPanelFiltro1";
            this.ucEasyTableLayoutPanelFiltro1.RowCount = 9;
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 38F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 22F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.Size = new System.Drawing.Size(787, 606);
            this.ucEasyTableLayoutPanelFiltro1.TabIndex = 0;
                                                this.ucEasyGridFiltroUA.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroUA.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ucEasyGridFiltroUA, 3);
            this.ucEasyGridFiltroUA.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroUA.DisplayLayout.Appearance = appearance1;
            this.ucEasyGridFiltroUA.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroUA.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance2.FontData.BoldAsString = "True";
            appearance2.FontData.SizeInPoints = 18.80597F;
            this.ucEasyGridFiltroUA.DisplayLayout.CaptionAppearance = appearance2;
            this.ucEasyGridFiltroUA.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance3.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance3.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance3.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Appearance = appearance3;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.BandLabelAppearance = appearance4;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance5.BackColor2 = System.Drawing.SystemColors.Control;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.PromptAppearance = appearance5;
            this.ucEasyGridFiltroUA.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroUA.DisplayLayout.MaxRowScrollRegions = 1;
            appearance6.BackColor = System.Drawing.SystemColors.Window;
            appearance6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ActiveCellAppearance = appearance6;
            appearance7.BackColor = System.Drawing.SystemColors.Highlight;
            appearance7.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ActiveRowAppearance = appearance7;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CardAreaAppearance = appearance8;
            appearance9.BorderColor = System.Drawing.Color.Silver;
            appearance9.FontData.SizeInPoints = 18.80597F;
            appearance9.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellAppearance = appearance9;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance10.FontData.SizeInPoints = 18.80597F;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.FilterRowAppearance = appearance10;
            appearance11.BackColor = System.Drawing.SystemColors.Control;
            appearance11.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance11.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance11.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance11.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.GroupByRowAppearance = appearance11;
            appearance12.FontData.BoldAsString = "True";
            appearance12.FontData.SizeInPoints = 18.80597F;
            appearance12.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderAppearance = appearance12;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance13.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance13.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowAlternateAppearance = appearance13;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowAppearance = appearance14;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance15.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.TemplateAddRowAppearance = appearance15;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroUA.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroUA.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroUA.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroUA.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.Location = new System.Drawing.Point(417, 9);
            this.ucEasyGridFiltroUA.Name = "ucEasyGridFiltroUA";
            this.ucEasyGridFiltroUA.ShowFilterRow = false;
            this.ucEasyGridFiltroUA.ShowGroupByBox = false;
            this.ucEasyGridFiltroUA.Size = new System.Drawing.Size(354, 224);
            this.ucEasyGridFiltroUA.TabIndex = 18;
            this.ucEasyGridFiltroUA.Text = "ucEasyGrid1";
            this.ucEasyGridFiltroUA.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroUA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltroUA_InitializeLayout);
                                                this.ucEasyTableLayoutPanel1.ColumnCount = 1;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ucEasyTableLayoutPanel1, 7);
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.Controls.Add(this.lblFiltroContenuto, 0, 0);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.utxtFiltroContenuto, 0, 1);
            this.ucEasyTableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel1.Location = new System.Drawing.Point(10, 378);
            this.ucEasyTableLayoutPanel1.Name = "ucEasyTableLayoutPanel1";
            this.ucEasyTableLayoutPanel1.RowCount = 2;
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanel1.Size = new System.Drawing.Size(761, 72);
            this.ucEasyTableLayoutPanel1.TabIndex = 17;
                                                appearance16.FontData.SizeInPoints = 18.80597F;
            appearance16.TextVAlignAsString = "Middle";
            this.lblFiltroContenuto.Appearance = appearance16;
            this.lblFiltroContenuto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroContenuto.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroContenuto.Name = "lblFiltroContenuto";
            this.lblFiltroContenuto.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroContenuto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroContenuto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroContenuto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroContenuto.Size = new System.Drawing.Size(755, 22);
            this.lblFiltroContenuto.TabIndex = 2;
            this.lblFiltroContenuto.Text = "CONTENUTO:";
            this.lblFiltroContenuto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance17.FontData.SizeInPoints = 27.16418F;
            this.utxtFiltroContenuto.Appearance = appearance17;
            this.utxtFiltroContenuto.AutoSize = false;
            this.utxtFiltroContenuto.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtFiltroContenuto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtFiltroContenuto.Location = new System.Drawing.Point(3, 31);
            this.utxtFiltroContenuto.Name = "utxtFiltroContenuto";
            this.utxtFiltroContenuto.Size = new System.Drawing.Size(755, 38);
            this.utxtFiltroContenuto.TabIndex = 1;
            this.utxtFiltroContenuto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.utxtFiltroContenuto.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.utxtFiltroContenuto.KeyDown += new System.Windows.Forms.KeyEventHandler(this.utxtFiltroContenuto_KeyDown);
                                                appearance18.FontData.SizeInPoints = 18.80597F;
            this.ucEasyTreeViewFiltroTipo.Appearance = appearance18;
            this.ucEasyTreeViewFiltroTipo.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ucEasyTreeViewFiltroTipo, 3);
            this.ucEasyTreeViewFiltroTipo.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewFiltroTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewFiltroTipo.HideSelection = false;
            this.ucEasyTreeViewFiltroTipo.LeftImagesSize = new System.Drawing.Size(19, 19);
            this.ucEasyTreeViewFiltroTipo.Location = new System.Drawing.Point(10, 9);
            this.ucEasyTreeViewFiltroTipo.Name = "ucEasyTreeViewFiltroTipo";
            appearance19.BackColor = System.Drawing.Color.LightYellow;
            appearance19.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance19;
            _override1.SelectedNodeAppearance = appearance19;
            this.ucEasyTreeViewFiltroTipo.Override = _override1;
            this.ucEasyTreeViewFiltroTipo.RightImagesSize = new System.Drawing.Size(19, 19);
            this.ucEasyTableLayoutPanelFiltro1.SetRowSpan(this.ucEasyTreeViewFiltroTipo, 2);
            this.ucEasyTreeViewFiltroTipo.Size = new System.Drawing.Size(394, 357);
            this.ucEasyTreeViewFiltroTipo.TabIndex = 16;
            this.ucEasyTreeViewFiltroTipo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeViewFiltroTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeViewFiltroTipo.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeViewFiltroTipo_AfterCheck);
                                                this.ucEasyGridFiltroStato.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroStato.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ucEasyGridFiltroStato, 3);
            this.ucEasyGridFiltroStato.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance20.BackColor = System.Drawing.SystemColors.Window;
            appearance20.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroStato.DisplayLayout.Appearance = appearance20;
            this.ucEasyGridFiltroStato.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroStato.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance21.FontData.BoldAsString = "True";
            appearance21.FontData.SizeInPoints = 18.80597F;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionAppearance = appearance21;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance22.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance22.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance22.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance22.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Appearance = appearance22;
            appearance23.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BandLabelAppearance = appearance23;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance24.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance24.BackColor2 = System.Drawing.SystemColors.Control;
            appearance24.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance24.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.PromptAppearance = appearance24;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxRowScrollRegions = 1;
            appearance25.BackColor = System.Drawing.SystemColors.Window;
            appearance25.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveCellAppearance = appearance25;
            appearance26.BackColor = System.Drawing.SystemColors.Highlight;
            appearance26.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveRowAppearance = appearance26;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance27.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CardAreaAppearance = appearance27;
            appearance28.BorderColor = System.Drawing.Color.Silver;
            appearance28.FontData.SizeInPoints = 18.80597F;
            appearance28.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellAppearance = appearance28;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance29.FontData.SizeInPoints = 18.80597F;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.FilterRowAppearance = appearance29;
            appearance30.BackColor = System.Drawing.SystemColors.Control;
            appearance30.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance30.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance30.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance30.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.GroupByRowAppearance = appearance30;
            appearance31.FontData.BoldAsString = "True";
            appearance31.FontData.SizeInPoints = 18.80597F;
            appearance31.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderAppearance = appearance31;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance32.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance32.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAlternateAppearance = appearance32;
            appearance33.BackColor = System.Drawing.SystemColors.Window;
            appearance33.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAppearance = appearance33;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance34.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.TemplateAddRowAppearance = appearance34;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroStato.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroStato.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroStato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroStato.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroStato.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.Location = new System.Drawing.Point(417, 239);
            this.ucEasyGridFiltroStato.Name = "ucEasyGridFiltroStato";
            this.ucEasyGridFiltroStato.ShowFilterRow = false;
            this.ucEasyGridFiltroStato.ShowGroupByBox = false;
            this.ucEasyGridFiltroStato.Size = new System.Drawing.Size(354, 127);
            this.ucEasyGridFiltroStato.TabIndex = 3;
            this.ucEasyGridFiltroStato.Text = "ucEasyGrid1";
            this.ucEasyGridFiltroStato.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroStato.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltro_InitializeLayout);
                                                this.ucEasyTableLayoutPanelFiltro2.ColumnCount = 5;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ucEasyTableLayoutPanelFiltro2, 7);
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.udteFiltroDA, 0, 1);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.udteFiltroA, 2, 1);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.lblFiltroDa, 0, 0);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.lblFiltroA, 2, 0);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.drFiltro, 4, 1);
            this.ucEasyTableLayoutPanelFiltro2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltro2.Location = new System.Drawing.Point(10, 456);
            this.ucEasyTableLayoutPanelFiltro2.Name = "ucEasyTableLayoutPanelFiltro2";
            this.ucEasyTableLayoutPanelFiltro2.RowCount = 2;
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.Size = new System.Drawing.Size(761, 72);
            this.ucEasyTableLayoutPanelFiltro2.TabIndex = 6;
                                                appearance35.FontData.SizeInPoints = 18.80597F;
            this.udteFiltroDA.Appearance = appearance35;
            this.udteFiltroDA.AutoSize = false;
            this.udteFiltroDA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroDA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroDA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance36.FontData.SizeInPoints = 18.80597F;
            this.udteFiltroDA.DropDownAppearance = appearance36;
            this.udteFiltroDA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroDA.Location = new System.Drawing.Point(3, 31);
            this.udteFiltroDA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroDA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroDA.Name = "udteFiltroDA";
            this.udteFiltroDA.Size = new System.Drawing.Size(222, 38);
            this.udteFiltroDA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroDA.TabIndex = 1;
            this.udteFiltroDA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroDA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance37.FontData.SizeInPoints = 18.80597F;
            this.udteFiltroA.Appearance = appearance37;
            this.udteFiltroA.AutoSize = false;
            this.udteFiltroA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance38.FontData.SizeInPoints = 18.80597F;
            this.udteFiltroA.DropDownAppearance = appearance38;
            this.udteFiltroA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroA.Location = new System.Drawing.Point(269, 31);
            this.udteFiltroA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroA.Name = "udteFiltroA";
            this.udteFiltroA.Size = new System.Drawing.Size(222, 38);
            this.udteFiltroA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroA.TabIndex = 2;
            this.udteFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance39.FontData.SizeInPoints = 18.80597F;
            appearance39.TextVAlignAsString = "Middle";
            this.lblFiltroDa.Appearance = appearance39;
            this.lblFiltroDa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDa.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroDa.Name = "lblFiltroDa";
            this.lblFiltroDa.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroDa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDa.Size = new System.Drawing.Size(222, 22);
            this.lblFiltroDa.TabIndex = 2;
            this.lblFiltroDa.Text = "DA:";
            this.lblFiltroDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance40.FontData.SizeInPoints = 18.80597F;
            appearance40.TextVAlignAsString = "Middle";
            this.lblFiltroA.Appearance = appearance40;
            this.lblFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroA.Location = new System.Drawing.Point(269, 3);
            this.lblFiltroA.Name = "lblFiltroA";
            this.lblFiltroA.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroA.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroA.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroA.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroA.Size = new System.Drawing.Size(222, 22);
            this.lblFiltroA.TabIndex = 2;
            this.lblFiltroA.Text = "A:";
            this.lblFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance41.FontData.SizeInPoints = 18.80597F;
            this.drFiltro.Appearance = appearance41;
            this.drFiltro.AutoSize = false;
            this.drFiltro.DataEpisodio = new System.DateTime(((long)(0)));
            this.drFiltro.DateFuture = false;
            this.drFiltro.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.drFiltro.DisponibilitaAgende = false;
            this.drFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.drFiltro.Domani = false;
            this.drFiltro.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem10.DisplayText = " ";
            valueListItem11.DataValue = "OGGI";
            valueListItem11.DisplayText = "Oggi";
            valueListItem12.DataValue = "24H";
            valueListItem12.DisplayText = "Ultime 24h";
            valueListItem13.DataValue = "48H";
            valueListItem13.DisplayText = "Ultime 48h";
            valueListItem14.DataValue = "7G";
            valueListItem14.DisplayText = "Ultimi 7gg";
            valueListItem15.DataValue = "30G";
            valueListItem15.DisplayText = "Ultimi 30gg";
            valueListItem16.DataValue = "60G";
            valueListItem16.DisplayText = "Ultimi 60gg";
            valueListItem17.DataValue = "90G";
            valueListItem17.DisplayText = "Ultimi 90gg";
            valueListItem18.DataValue = "6M";
            valueListItem18.DisplayText = "Ultimi 6 mesi";
            this.drFiltro.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem10,
            valueListItem11,
            valueListItem12,
            valueListItem13,
            valueListItem14,
            valueListItem15,
            valueListItem16,
            valueListItem17,
            valueListItem18});
            this.drFiltro.Location = new System.Drawing.Point(535, 31);
            this.drFiltro.Name = "drFiltro";
            this.drFiltro.Oggi = true;
            this.drFiltro.PassatoRemoto = false;
            this.drFiltro.Size = new System.Drawing.Size(223, 38);
            this.drFiltro.TabIndex = 0;
            this.drFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.drFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.drFiltro.ValueChanged += new System.EventHandler(this.drFiltro_ValueChanged);
                                                appearance42.FontData.SizeInPoints = 27.16418F;
            appearance42.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance42.ImageBackground")));
            appearance42.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance42.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance42.TextHAlignAsString = "Center";
            appearance42.TextVAlignAsString = "Middle";
            this.ubApplicaFiltro.Appearance = appearance42;
            this.ubApplicaFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ubApplicaFiltro, 3);
            this.ubApplicaFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltro.Location = new System.Drawing.Point(417, 540);
            this.ubApplicaFiltro.Name = "ubApplicaFiltro";
            this.ubApplicaFiltro.PercImageFill = 0.75F;
            this.ubApplicaFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.ubApplicaFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltro.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltro.Size = new System.Drawing.Size(354, 54);
            this.ubApplicaFiltro.TabIndex = 7;
            this.ubApplicaFiltro.Text = "Applica Filtro";
            this.ubApplicaFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltro.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ultraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.ultraDockManager.AutoHideDelay = 150;
            this.ultraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.ultraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.ultraDockManager.CompressUnpinnedTabs = false;
            this.ultraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockAreaPane1.ChildPaneStyle = Infragistics.Win.UltraWinDock.ChildPaneStyle.VerticalSplit;
            dockableControlPane1.Control = this.pnlFiltro;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(787, -1);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(423, 384, 200, 100);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Settings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.ShowCaption = Infragistics.Win.DefaultableBoolean.True;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "FILTRO";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(541, 624);
            this.ultraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.ultraDockManager.HostControl = this;
            this.ultraDockManager.ShowCloseButton = false;
            this.ultraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.ultraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.ultraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.ultraDockManager_InitializePane);
                                                this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Name = "_ucDiarioClinicoPazienteUnpinnedTabAreaLeft";
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 624);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.TabIndex = 0;
                                                this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Location = new System.Drawing.Point(855, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Name = "_ucDiarioClinicoPazienteUnpinnedTabAreaRight";
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Size = new System.Drawing.Size(23, 624);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.TabIndex = 1;
                                                this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Name = "_ucDiarioClinicoPazienteUnpinnedTabAreaTop";
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Size = new System.Drawing.Size(855, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.TabIndex = 2;
                                                this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 624);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Name = "_ucDiarioClinicoPazienteUnpinnedTabAreaBottom";
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Size = new System.Drawing.Size(855, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.TabIndex = 3;
                                                this._ucDiarioClinicoPazienteAutoHideControl.Controls.Add(this.dockableWindow1);
            this._ucDiarioClinicoPazienteAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteAutoHideControl.Location = new System.Drawing.Point(783, 0);
            this._ucDiarioClinicoPazienteAutoHideControl.Name = "_ucDiarioClinicoPazienteAutoHideControl";
            this._ucDiarioClinicoPazienteAutoHideControl.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteAutoHideControl.Size = new System.Drawing.Size(72, 624);
            this._ucDiarioClinicoPazienteAutoHideControl.TabIndex = 4;
                                                this.dockableWindow1.Controls.Add(this.pnlFiltro);
            this.dockableWindow1.Location = new System.Drawing.Point(-10000, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.ultraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(787, 624);
            this.dockableWindow1.TabIndex = 8;
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(855, 624);
            this.ultraGroupBox.TabIndex = 7;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.ColumnCount = 6;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 76F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.utxtRicerca, 2, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.lblRicerca, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGrid, 1, 3);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 5;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 90F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(849, 618);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance43.FontData.SizeInPoints = 33.43283F;
            this.utxtRicerca.Appearance = appearance43;
            this.utxtRicerca.AutoSize = false;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.utxtRicerca, 3);
            this.utxtRicerca.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtRicerca.Location = new System.Drawing.Point(109, 6);
            this.utxtRicerca.Margin = new System.Windows.Forms.Padding(0);
            this.utxtRicerca.Name = "utxtRicerca";
            this.utxtRicerca.Size = new System.Drawing.Size(729, 43);
            this.utxtRicerca.TabIndex = 0;
            this.utxtRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.utxtRicerca.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.utxtRicerca.KeyDown += new System.Windows.Forms.KeyEventHandler(this.utxtRicerca_KeyDown);
                                                appearance44.FontData.SizeInPoints = 33.43283F;
            appearance44.TextVAlignAsString = "Middle";
            this.lblRicerca.Appearance = appearance44;
            this.lblRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRicerca.Location = new System.Drawing.Point(8, 6);
            this.lblRicerca.Margin = new System.Windows.Forms.Padding(0);
            this.lblRicerca.Name = "lblRicerca";
            this.lblRicerca.ShortcutColor = System.Drawing.Color.Black;
            this.lblRicerca.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblRicerca.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblRicerca.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblRicerca.Size = new System.Drawing.Size(101, 43);
            this.lblRicerca.TabIndex = 6;
            this.lblRicerca.Text = "Ricerca";
            this.lblRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyGrid, 4);
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance45.BackColor = System.Drawing.SystemColors.Window;
            appearance45.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance45;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance46.FontData.BoldAsString = "True";
            appearance46.FontData.SizeInPoints = 27.16418F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance46;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance47.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance47.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance47.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance47.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance47;
            appearance48.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance48;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance49.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance49.BackColor2 = System.Drawing.SystemColors.Control;
            appearance49.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance49.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance49;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance50.BackColor = System.Drawing.SystemColors.Window;
            appearance50.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance50;
            appearance51.BackColor = System.Drawing.SystemColors.Highlight;
            appearance51.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance51;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance52.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance52;
            appearance53.BorderColor = System.Drawing.Color.Silver;
            appearance53.FontData.SizeInPoints = 18.80597F;
            appearance53.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance53;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance54.FontData.SizeInPoints = 27.16418F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance54;
            appearance55.BackColor = System.Drawing.SystemColors.Control;
            appearance55.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance55.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance55.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance55.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance55;
            appearance56.FontData.BoldAsString = "True";
            appearance56.FontData.SizeInPoints = 18.80597F;
            appearance56.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance56;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance57.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance57.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance57;
            appearance58.BackColor = System.Drawing.SystemColors.Window;
            appearance58.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance58;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance59.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance59;
            scrollBarLook3.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(11, 58);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(824, 550);
            this.ucEasyGrid.TabIndex = 0;
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
            this.ucEasyGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucEasyGrid_ClickCell);
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Right;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(309, 0);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.ultraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(546, 624);
            this.windowDockingArea1.TabIndex = 6;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this._ucDiarioClinicoPazienteAutoHideControl);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._ucDiarioClinicoPazienteUnpinnedTabAreaTop);
            this.Controls.Add(this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom);
            this.Controls.Add(this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft);
            this.Controls.Add(this._ucDiarioClinicoPazienteUnpinnedTabAreaRight);
            this.Name = "ucConsulenzeTrasversali";
            this.Size = new System.Drawing.Size(878, 624);
            this.Enter += new System.EventHandler(this.ucDiarioClinicoPaziente_Enter);
            this.pnlFiltro.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFiltro1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroUA)).EndInit();
            this.ucEasyTableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.utxtFiltroContenuto)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewFiltroTipo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).EndInit();
            this.ucEasyTableLayoutPanelFiltro2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).EndInit();
            this._ucDiarioClinicoPazienteAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.utxtRicerca)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinDock.UltraDockManager ultraDockManager;
        private System.Windows.Forms.Panel pnlFiltro;
        private Infragistics.Win.UltraWinDock.AutoHideControl _ucDiarioClinicoPazienteAutoHideControl;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucDiarioClinicoPazienteUnpinnedTabAreaLeft;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucDiarioClinicoPazienteUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucDiarioClinicoPazienteUnpinnedTabAreaBottom;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucDiarioClinicoPazienteUnpinnedTabAreaRight;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyGrid ucEasyGrid;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltro1;
        private ucEasyGrid ucEasyGridFiltroStato;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltro2;
        private ucEasyDateTimeEditor udteFiltroDA;
        private ucEasyDateTimeEditor udteFiltroA;
        private ucEasyLabel lblFiltroDa;
        private ucEasyLabel lblFiltroA;
        private ucEasyDateRange drFiltro;
        private ucEasyButton ubApplicaFiltro;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private ucEasyTreeView ucEasyTreeViewFiltroTipo;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel1;
        private ucEasyLabel lblFiltroContenuto;
        private ucEasyTextBox utxtFiltroContenuto;
        private ucEasyGrid ucEasyGridFiltroUA;
        private ucEasyLabel lblRicerca;
        private ucEasyTextBox utxtRicerca;
    }
}