namespace UnicodeSrl.ScciCore
{
    partial class ucConsegne
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem3 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem4 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem5 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem6 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem7 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem8 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem9 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucConsegne));
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedRight, new System.Guid("13e5a250-8102-48cd-90da-9bcd165034bd"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("ebf50a39-032d-4ecf-970b-7ba496e8c4d0"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("13e5a250-8102-48cd-90da-9bcd165034bd"), -1);
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            this.pnlFiltro = new System.Windows.Forms.Panel();
            this.ucEasyTableLayoutPanelFiltro1 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTreeViewFiltroTipo = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ucEasyGridFiltroStato = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyGridFiltroUA = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPanelFiltro2 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.udteFiltroDA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.udteFiltroA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroDa = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblFiltroA = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.drFiltro = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.txtFiltroUA = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ubApplicaFiltro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ultraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._ucConsegneUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucConsegneUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucConsegneUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucConsegneUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucConsegneAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPulsanti = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.uchkFiltro = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ubAdd = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.pnlFiltro.SuspendLayout();
            this.ucEasyTableLayoutPanelFiltro1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewFiltroTipo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroUA)).BeginInit();
            this.ucEasyTableLayoutPanelFiltro2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtFiltroUA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).BeginInit();
            this._ucConsegneAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            this.ucEasyTableLayoutPulsanti.SuspendLayout();
            this.SuspendLayout();
                                                this.pnlFiltro.BackColor = System.Drawing.Color.Transparent;
            this.pnlFiltro.Controls.Add(this.ucEasyTableLayoutPanelFiltro1);
            this.pnlFiltro.Location = new System.Drawing.Point(0, 18);
            this.pnlFiltro.Name = "pnlFiltro";
            this.pnlFiltro.Size = new System.Drawing.Size(602, 606);
            this.pnlFiltro.TabIndex = 5;
                                                this.ucEasyTableLayoutPanelFiltro1.ColumnCount = 7;
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTreeViewFiltroTipo, 1, 1);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyGridFiltroStato, 3, 1);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyGridFiltroUA, 5, 1);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTableLayoutPanelFiltro2, 1, 4);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.txtFiltroUA, 5, 2);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ubApplicaFiltro, 3, 6);
            this.ucEasyTableLayoutPanelFiltro1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltro1.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelFiltro1.Name = "ucEasyTableLayoutPanelFiltro1";
            this.ucEasyTableLayoutPanelFiltro1.RowCount = 8;
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 67F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro1.Size = new System.Drawing.Size(602, 606);
            this.ucEasyTableLayoutPanelFiltro1.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 13.56716F;
            this.ucEasyTreeViewFiltroTipo.Appearance = appearance1;
            this.ucEasyTreeViewFiltroTipo.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTreeViewFiltroTipo.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewFiltroTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewFiltroTipo.HideSelection = false;
            this.ucEasyTreeViewFiltroTipo.Location = new System.Drawing.Point(9, 9);
            this.ucEasyTreeViewFiltroTipo.Name = "ucEasyTreeViewFiltroTipo";
            appearance2.BackColor = System.Drawing.Color.LightYellow;
            appearance2.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance2;
            _override1.SelectedNodeAppearance = appearance2;
            this.ucEasyTreeViewFiltroTipo.Override = _override1;
            this.ucEasyTreeViewFiltroTipo.Size = new System.Drawing.Size(186, 400);
            this.ucEasyTreeViewFiltroTipo.TabIndex = 16;
            this.ucEasyTreeViewFiltroTipo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeViewFiltroTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeViewFiltroTipo.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeViewFiltroTipo_AfterCheck);
                                                this.ucEasyGridFiltroStato.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroStato.ColonnaRTFResize = "";
            this.ucEasyGridFiltroStato.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance3.BackColor = System.Drawing.SystemColors.Window;
            appearance3.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroStato.DisplayLayout.Appearance = appearance3;
            this.ucEasyGridFiltroStato.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroStato.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.FontData.BoldAsString = "True";
            appearance4.FontData.SizeInPoints = 13.56716F;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionAppearance = appearance4;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance5.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance5.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance5.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Appearance = appearance5;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BandLabelAppearance = appearance6;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance7.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance7.BackColor2 = System.Drawing.SystemColors.Control;
            appearance7.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance7.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.PromptAppearance = appearance7;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxRowScrollRegions = 1;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            appearance8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveCellAppearance = appearance8;
            appearance9.BackColor = System.Drawing.SystemColors.Highlight;
            appearance9.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveRowAppearance = appearance9;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CardAreaAppearance = appearance10;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            appearance11.FontData.SizeInPoints = 13.56716F;
            appearance11.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellAppearance = appearance11;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance12.FontData.SizeInPoints = 13.56716F;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.FilterRowAppearance = appearance12;
            appearance13.BackColor = System.Drawing.SystemColors.Control;
            appearance13.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance13.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance13.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance13.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.GroupByRowAppearance = appearance13;
            appearance14.FontData.BoldAsString = "True";
            appearance14.FontData.SizeInPoints = 13.56716F;
            appearance14.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderAppearance = appearance14;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance15.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance15.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAlternateAppearance = appearance15;
            appearance16.BackColor = System.Drawing.SystemColors.Window;
            appearance16.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAppearance = appearance16;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance17.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.TemplateAddRowAppearance = appearance17;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroStato.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroStato.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroStato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroStato.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroStato.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.Location = new System.Drawing.Point(207, 9);
            this.ucEasyGridFiltroStato.Name = "ucEasyGridFiltroStato";
            this.ucEasyGridFiltroStato.ShowFilterRow = false;
            this.ucEasyGridFiltroStato.ShowGroupByBox = false;
            this.ucEasyGridFiltroStato.Size = new System.Drawing.Size(186, 400);
            this.ucEasyGridFiltroStato.TabIndex = 3;
            this.ucEasyGridFiltroStato.Text = "ucEasyGrid1";
            this.ucEasyGridFiltroStato.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroStato.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltro_InitializeLayout);
                                                this.ucEasyGridFiltroUA.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroUA.ColonnaRTFResize = "";
            this.ucEasyGridFiltroUA.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance18.BackColor = System.Drawing.SystemColors.Window;
            appearance18.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroUA.DisplayLayout.Appearance = appearance18;
            this.ucEasyGridFiltroUA.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroUA.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance19.FontData.BoldAsString = "True";
            appearance19.FontData.SizeInPoints = 13.56716F;
            this.ucEasyGridFiltroUA.DisplayLayout.CaptionAppearance = appearance19;
            this.ucEasyGridFiltroUA.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance20.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance20.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance20.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance20.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Appearance = appearance20;
            appearance21.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.BandLabelAppearance = appearance21;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance22.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance22.BackColor2 = System.Drawing.SystemColors.Control;
            appearance22.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance22.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroUA.DisplayLayout.GroupByBox.PromptAppearance = appearance22;
            this.ucEasyGridFiltroUA.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroUA.DisplayLayout.MaxRowScrollRegions = 1;
            appearance23.BackColor = System.Drawing.SystemColors.Window;
            appearance23.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ActiveCellAppearance = appearance23;
            appearance24.BackColor = System.Drawing.SystemColors.Highlight;
            appearance24.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ActiveRowAppearance = appearance24;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance25.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CardAreaAppearance = appearance25;
            appearance26.BorderColor = System.Drawing.Color.Silver;
            appearance26.FontData.SizeInPoints = 13.56716F;
            appearance26.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellAppearance = appearance26;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance27.FontData.SizeInPoints = 13.56716F;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.FilterRowAppearance = appearance27;
            appearance28.BackColor = System.Drawing.SystemColors.Control;
            appearance28.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance28.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance28.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance28.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.GroupByRowAppearance = appearance28;
            appearance29.FontData.BoldAsString = "True";
            appearance29.FontData.SizeInPoints = 13.56716F;
            appearance29.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderAppearance = appearance29;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance30.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance30.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowAlternateAppearance = appearance30;
            appearance31.BackColor = System.Drawing.SystemColors.Window;
            appearance31.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowAppearance = appearance31;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance32.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroUA.DisplayLayout.Override.TemplateAddRowAppearance = appearance32;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroUA.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroUA.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroUA.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroUA.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroUA.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUA.Location = new System.Drawing.Point(405, 9);
            this.ucEasyGridFiltroUA.Name = "ucEasyGridFiltroUA";
            this.ucEasyGridFiltroUA.ShowFilterRow = false;
            this.ucEasyGridFiltroUA.ShowGroupByBox = false;
            this.ucEasyGridFiltroUA.Size = new System.Drawing.Size(186, 400);
            this.ucEasyGridFiltroUA.TabIndex = 4;
            this.ucEasyGridFiltroUA.Text = "ucEasyGrid1";
            this.ucEasyGridFiltroUA.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroUA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUA.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltro_InitializeLayout);
                                                this.ucEasyTableLayoutPanelFiltro2.ColumnCount = 5;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ucEasyTableLayoutPanelFiltro2, 5);
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.udteFiltroDA, 0, 1);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.udteFiltroA, 2, 1);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.lblFiltroDa, 0, 0);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.lblFiltroA, 2, 0);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.drFiltro, 4, 1);
            this.ucEasyTableLayoutPanelFiltro2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltro2.Location = new System.Drawing.Point(9, 457);
            this.ucEasyTableLayoutPanelFiltro2.Name = "ucEasyTableLayoutPanelFiltro2";
            this.ucEasyTableLayoutPanelFiltro2.RowCount = 2;
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.Size = new System.Drawing.Size(582, 72);
            this.ucEasyTableLayoutPanelFiltro2.TabIndex = 6;
                                                appearance33.FontData.SizeInPoints = 13.56716F;
            this.udteFiltroDA.Appearance = appearance33;
            this.udteFiltroDA.AutoSize = false;
            this.udteFiltroDA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroDA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroDA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance34.FontData.SizeInPoints = 13.56716F;
            this.udteFiltroDA.DropDownAppearance = appearance34;
            this.udteFiltroDA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroDA.Location = new System.Drawing.Point(3, 31);
            this.udteFiltroDA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroDA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroDA.Name = "udteFiltroDA";
            this.udteFiltroDA.Size = new System.Drawing.Size(168, 38);
            this.udteFiltroDA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroDA.TabIndex = 1;
            this.udteFiltroDA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroDA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance35.FontData.SizeInPoints = 13.56716F;
            this.udteFiltroA.Appearance = appearance35;
            this.udteFiltroA.AutoSize = false;
            this.udteFiltroA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance36.FontData.SizeInPoints = 13.56716F;
            this.udteFiltroA.DropDownAppearance = appearance36;
            this.udteFiltroA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroA.Location = new System.Drawing.Point(206, 31);
            this.udteFiltroA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroA.Name = "udteFiltroA";
            this.udteFiltroA.Size = new System.Drawing.Size(168, 38);
            this.udteFiltroA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroA.TabIndex = 2;
            this.udteFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance37.FontData.SizeInPoints = 13.56716F;
            appearance37.TextVAlignAsString = "Middle";
            this.lblFiltroDa.Appearance = appearance37;
            this.lblFiltroDa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDa.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroDa.Name = "lblFiltroDa";
            this.lblFiltroDa.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroDa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDa.Size = new System.Drawing.Size(168, 22);
            this.lblFiltroDa.TabIndex = 2;
            this.lblFiltroDa.Text = "DA:";
            this.lblFiltroDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance38.FontData.SizeInPoints = 13.56716F;
            appearance38.TextVAlignAsString = "Middle";
            this.lblFiltroA.Appearance = appearance38;
            this.lblFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroA.Location = new System.Drawing.Point(206, 3);
            this.lblFiltroA.Name = "lblFiltroA";
            this.lblFiltroA.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroA.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroA.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroA.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroA.Size = new System.Drawing.Size(168, 22);
            this.lblFiltroA.TabIndex = 2;
            this.lblFiltroA.Text = "A:";
            this.lblFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance39.FontData.SizeInPoints = 13.56716F;
            this.drFiltro.Appearance = appearance39;
            this.drFiltro.AutoSize = false;
            this.drFiltro.DataEpisodio = new System.DateTime(((long)(0)));
            this.drFiltro.DateFuture = false;
            this.drFiltro.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.drFiltro.DisponibilitaAgende = false;
            this.drFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.drFiltro.Domani = false;
            this.drFiltro.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem1.DisplayText = " ";
            valueListItem2.DataValue = "OGGI";
            valueListItem2.DisplayText = "Oggi";
            valueListItem3.DataValue = "24H";
            valueListItem3.DisplayText = "Ultime 24h";
            valueListItem4.DataValue = "48H";
            valueListItem4.DisplayText = "Ultime 48h";
            valueListItem5.DataValue = "7G";
            valueListItem5.DisplayText = "Ultimi 7gg";
            valueListItem6.DataValue = "30G";
            valueListItem6.DisplayText = "Ultimi 30gg";
            valueListItem7.DataValue = "60G";
            valueListItem7.DisplayText = "Ultimi 60gg";
            valueListItem8.DataValue = "90G";
            valueListItem8.DisplayText = "Ultimi 90gg";
            valueListItem9.DataValue = "6M";
            valueListItem9.DisplayText = "Ultimi 6 mesi";
            this.drFiltro.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2,
            valueListItem3,
            valueListItem4,
            valueListItem5,
            valueListItem6,
            valueListItem7,
            valueListItem8,
            valueListItem9});
            this.drFiltro.Location = new System.Drawing.Point(409, 31);
            this.drFiltro.Name = "drFiltro";
            this.drFiltro.Oggi = true;
            this.drFiltro.PassatoRemoto = false;
            this.drFiltro.Size = new System.Drawing.Size(170, 38);
            this.drFiltro.TabIndex = 0;
            this.drFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.drFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.drFiltro.ValueChanged += new System.EventHandler(this.drFiltro_ValueChanged);
                                                appearance40.FontData.SizeInPoints = 13.56716F;
            this.txtFiltroUA.Appearance = appearance40;
            this.txtFiltroUA.AutoSize = false;
            this.txtFiltroUA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtFiltroUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtFiltroUA.Location = new System.Drawing.Point(405, 415);
            this.txtFiltroUA.Name = "txtFiltroUA";
            this.txtFiltroUA.Size = new System.Drawing.Size(186, 30);
            this.txtFiltroUA.TabIndex = 5;
            this.txtFiltroUA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.txtFiltroUA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.txtFiltroUA.ValueChanged += new System.EventHandler(this.txtFiltroUA_ValueChanged);
                                                appearance41.FontData.SizeInPoints = 19.59702F;
            appearance41.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance41.ImageBackground")));
            appearance41.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance41.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance41.TextHAlignAsString = "Center";
            appearance41.TextVAlignAsString = "Middle";
            this.ubApplicaFiltro.Appearance = appearance41;
            this.ubApplicaFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ubApplicaFiltro, 3);
            this.ubApplicaFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltro.Location = new System.Drawing.Point(207, 541);
            this.ubApplicaFiltro.Name = "ubApplicaFiltro";
            this.ubApplicaFiltro.PercImageFill = 0.75F;
            this.ubApplicaFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.ubApplicaFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltro.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltro.Size = new System.Drawing.Size(384, 54);
            this.ubApplicaFiltro.TabIndex = 7;
            this.ubApplicaFiltro.Text = "Applica Filtro";
            this.ubApplicaFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltro.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ultraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.ultraDockManager.AutoHideDelay = 150;
            this.ultraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.ultraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.ultraDockManager.CompressUnpinnedTabs = false;
            this.ultraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockAreaPane1.ChildPaneStyle = Infragistics.Win.UltraWinDock.ChildPaneStyle.VerticalSplit;
            dockableControlPane1.Control = this.pnlFiltro;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(602, -1);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(423, 384, 200, 100);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Settings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.ShowCaption = Infragistics.Win.DefaultableBoolean.True;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "FILTRO";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(625, 624);
            this.ultraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.ultraDockManager.HostControl = this;
            this.ultraDockManager.ShowCloseButton = false;
            this.ultraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.ultraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.ultraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.ultraDockManager_InitializePane);
                                                this._ucConsegneUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._ucConsegneUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucConsegneUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._ucConsegneUnpinnedTabAreaLeft.Name = "_ucConsegneUnpinnedTabAreaLeft";
            this._ucConsegneUnpinnedTabAreaLeft.Owner = this.ultraDockManager;
            this._ucConsegneUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 624);
            this._ucConsegneUnpinnedTabAreaLeft.TabIndex = 0;
                                                this._ucConsegneUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._ucConsegneUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucConsegneUnpinnedTabAreaRight.Location = new System.Drawing.Point(855, 0);
            this._ucConsegneUnpinnedTabAreaRight.Name = "_ucConsegneUnpinnedTabAreaRight";
            this._ucConsegneUnpinnedTabAreaRight.Owner = this.ultraDockManager;
            this._ucConsegneUnpinnedTabAreaRight.Size = new System.Drawing.Size(23, 624);
            this._ucConsegneUnpinnedTabAreaRight.TabIndex = 1;
                                                this._ucConsegneUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._ucConsegneUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucConsegneUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._ucConsegneUnpinnedTabAreaTop.Name = "_ucConsegneUnpinnedTabAreaTop";
            this._ucConsegneUnpinnedTabAreaTop.Owner = this.ultraDockManager;
            this._ucConsegneUnpinnedTabAreaTop.Size = new System.Drawing.Size(855, 0);
            this._ucConsegneUnpinnedTabAreaTop.TabIndex = 2;
                                                this._ucConsegneUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._ucConsegneUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucConsegneUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 624);
            this._ucConsegneUnpinnedTabAreaBottom.Name = "_ucConsegneUnpinnedTabAreaBottom";
            this._ucConsegneUnpinnedTabAreaBottom.Owner = this.ultraDockManager;
            this._ucConsegneUnpinnedTabAreaBottom.Size = new System.Drawing.Size(855, 0);
            this._ucConsegneUnpinnedTabAreaBottom.TabIndex = 3;
                                                this._ucConsegneAutoHideControl.Controls.Add(this.dockableWindow1);
            this._ucConsegneAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucConsegneAutoHideControl.Location = new System.Drawing.Point(808, 0);
            this._ucConsegneAutoHideControl.Name = "_ucConsegneAutoHideControl";
            this._ucConsegneAutoHideControl.Owner = this.ultraDockManager;
            this._ucConsegneAutoHideControl.Size = new System.Drawing.Size(47, 624);
            this._ucConsegneAutoHideControl.TabIndex = 4;
                                                this.dockableWindow1.Controls.Add(this.pnlFiltro);
            this.dockableWindow1.Location = new System.Drawing.Point(5, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.ultraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(602, 624);
            this.dockableWindow1.TabIndex = 8;
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(855, 624);
            this.ultraGroupBox.TabIndex = 7;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.ColumnCount = 5;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 88F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGrid, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPulsanti, 3, 1);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 3;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(849, 618);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance42.BackColor = System.Drawing.SystemColors.Window;
            appearance42.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance42;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance43.FontData.BoldAsString = "True";
            appearance43.FontData.SizeInPoints = 19.59702F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance43;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance44.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance44.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance44.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance44.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance44;
            appearance45.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance45;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance46.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance46.BackColor2 = System.Drawing.SystemColors.Control;
            appearance46.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance46.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance46;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance47.BackColor = System.Drawing.SystemColors.Window;
            appearance47.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance47;
            appearance48.BackColor = System.Drawing.SystemColors.Highlight;
            appearance48.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance48;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance49.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance49;
            appearance50.BorderColor = System.Drawing.Color.Silver;
            appearance50.FontData.SizeInPoints = 13.56716F;
            appearance50.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance50;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance51.FontData.SizeInPoints = 19.59702F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance51;
            appearance52.BackColor = System.Drawing.SystemColors.Control;
            appearance52.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance52.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance52.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance52.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance52;
            appearance53.FontData.BoldAsString = "True";
            appearance53.FontData.SizeInPoints = 13.56716F;
            appearance53.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance53;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance54.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance54.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance54;
            appearance55.BackColor = System.Drawing.SystemColors.Window;
            appearance55.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance55;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance56.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance56;
            scrollBarLook3.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(11, 9);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(741, 599);
            this.ucEasyGrid.TabIndex = 0;
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.AfterRowActivate += new System.EventHandler(this.ucEasyGrid_AfterRowActivate);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
            this.ucEasyGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucEasyGrid_ClickCell);
                                                this.ucEasyTableLayoutPulsanti.ColumnCount = 1;
            this.ucEasyTableLayoutPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.uchkFiltro, 0, 2);
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.ubAdd, 0, 0);
            this.ucEasyTableLayoutPulsanti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPulsanti.Location = new System.Drawing.Point(766, 9);
            this.ucEasyTableLayoutPulsanti.Name = "ucEasyTableLayoutPulsanti";
            this.ucEasyTableLayoutPulsanti.RowCount = 7;
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.ucEasyTableLayoutPulsanti.Size = new System.Drawing.Size(70, 599);
            this.ucEasyTableLayoutPulsanti.TabIndex = 4;
                                                appearance57.FontData.SizeInPoints = 19.59702F;
            appearance57.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance57.ImageBackground")));
            appearance57.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance57.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance57.TextHAlignAsString = "Center";
            appearance57.TextVAlignAsString = "Bottom";
            this.uchkFiltro.Appearance = appearance57;
            this.uchkFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkFiltro.Checked = false;
            this.uchkFiltro.CheckedImage = null;
            this.uchkFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkFiltro.Location = new System.Drawing.Point(3, 133);
            this.uchkFiltro.Name = "uchkFiltro";
            this.uchkFiltro.PercImageFill = 0.75F;
            this.uchkFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.uchkFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkFiltro.ShortcutKey = System.Windows.Forms.Keys.F;
            this.uchkFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkFiltro.Size = new System.Drawing.Size(64, 89);
            this.uchkFiltro.TabIndex = 1;
            this.uchkFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.uchkFiltro.UNCheckedImage = null;
            this.uchkFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uchkFiltro.Click += new System.EventHandler(this.uchkFiltro_Click);
                                                appearance58.FontData.SizeInPoints = 19.59702F;
            appearance58.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance58.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance58.TextHAlignAsString = "Center";
            appearance58.TextVAlignAsString = "Bottom";
            this.ubAdd.Appearance = appearance58;
            this.ubAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAdd.Location = new System.Drawing.Point(3, 3);
            this.ubAdd.Name = "ubAdd";
            this.ubAdd.PercImageFill = 0.75F;
            this.ubAdd.ShortcutColor = System.Drawing.Color.Black;
            this.ubAdd.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAdd.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAdd.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAdd.Size = new System.Drawing.Size(64, 89);
            this.ubAdd.TabIndex = 3;
            this.ubAdd.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubAdd.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAdd.Click += new System.EventHandler(this.ubAdd_Click);
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Right;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(225, 0);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.ultraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(630, 624);
            this.windowDockingArea1.TabIndex = 6;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this._ucConsegneAutoHideControl);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._ucConsegneUnpinnedTabAreaTop);
            this.Controls.Add(this._ucConsegneUnpinnedTabAreaBottom);
            this.Controls.Add(this._ucConsegneUnpinnedTabAreaLeft);
            this.Controls.Add(this._ucConsegneUnpinnedTabAreaRight);
            this.Name = "ucConsegne";
            this.Size = new System.Drawing.Size(878, 624);
            this.Enter += new System.EventHandler(this.ucConsegne_Enter);
            this.pnlFiltro.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFiltro1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewFiltroTipo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroUA)).EndInit();
            this.ucEasyTableLayoutPanelFiltro2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtFiltroUA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).EndInit();
            this._ucConsegneAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            this.ucEasyTableLayoutPulsanti.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinDock.UltraDockManager ultraDockManager;
        private System.Windows.Forms.Panel pnlFiltro;
        private Infragistics.Win.UltraWinDock.AutoHideControl _ucConsegneAutoHideControl;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucConsegneUnpinnedTabAreaLeft;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucConsegneUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucConsegneUnpinnedTabAreaBottom;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucConsegneUnpinnedTabAreaRight;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyButton ubAdd;
        private ucEasyGrid ucEasyGrid;
        private ucEasyStateButton uchkFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltro1;
        private ucEasyGrid ucEasyGridFiltroStato;
        private ucEasyGrid ucEasyGridFiltroUA;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltro2;
        private ucEasyDateTimeEditor udteFiltroDA;
        private ucEasyDateTimeEditor udteFiltroA;
        private ucEasyLabel lblFiltroDa;
        private ucEasyLabel lblFiltroA;
        private ucEasyTextBox txtFiltroUA;
        private ucEasyDateRange drFiltro;
        private ucEasyButton ubApplicaFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPulsanti;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private ucEasyTreeView ucEasyTreeViewFiltroTipo;
    }
}
