namespace UnicodeSrl.ScciCore
{
    partial class ucDiarioClinicoPaziente
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedRight, new System.Guid("13e5a250-8102-48cd-90da-9bcd165034bd"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("ebf50a39-032d-4ecf-970b-7ba496e8c4d0"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("13e5a250-8102-48cd-90da-9bcd165034bd"), -1);
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem3 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem4 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem5 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem6 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem7 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem8 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucDiarioClinicoPaziente));
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            this.pnlFiltro = new System.Windows.Forms.Panel();
            this.ultraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucDiarioClinicoPazienteAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.ucEasyTableLayoutPanelFiltro1 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTableLayoutPanel1 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblFiltroContenuto = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utxtFiltroContenuto = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ucEasyTreeViewFiltroTipo = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ucEasyGridFiltroStato = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyGridFiltroUtente = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPanelFiltro2 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.udteFiltroDA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.udteFiltroA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroDa = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblFiltroA = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.drFiltro = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.txtFiltroUtente = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ubApplicaFiltro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyTableLayoutPulsantiFiltro = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.uchkMedico = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.uchkInfermieristico = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPulsanti = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubValida = new UnicodeSrl.ScciCore.ucEasyButton();
            this.uchkFiltro = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ubAdd = new UnicodeSrl.ScciCore.ucEasyButton();
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.dockableWindow2 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.pnlFiltro.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).BeginInit();
            this._ucDiarioClinicoPazienteAutoHideControl.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanelFiltro1.SuspendLayout();
            this.ucEasyTableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.utxtFiltroContenuto)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewFiltroTipo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroUtente)).BeginInit();
            this.ucEasyTableLayoutPanelFiltro2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtFiltroUtente)).BeginInit();
            this.ucEasyTableLayoutPulsantiFiltro.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            this.ucEasyTableLayoutPulsanti.SuspendLayout();
            this.dockableWindow2.SuspendLayout();
            this.SuspendLayout();
                                                this.pnlFiltro.BackColor = System.Drawing.Color.Transparent;
            this.pnlFiltro.Controls.Add(this.ucEasyTableLayoutPanelFiltro1);
            this.pnlFiltro.Location = new System.Drawing.Point(0, 18);
            this.pnlFiltro.Name = "pnlFiltro";
            this.pnlFiltro.Size = new System.Drawing.Size(787, 606);
            this.pnlFiltro.TabIndex = 5;
                                                this.ultraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.ultraDockManager.AutoHideDelay = 150;
            this.ultraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.ultraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.ultraDockManager.CompressUnpinnedTabs = false;
            this.ultraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockAreaPane1.ChildPaneStyle = Infragistics.Win.UltraWinDock.ChildPaneStyle.VerticalSplit;
            dockableControlPane1.Control = this.pnlFiltro;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(787, -1);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(423, 384, 200, 100);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Settings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.ShowCaption = Infragistics.Win.DefaultableBoolean.True;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "FILTRO";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(720, 624);
            this.ultraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.ultraDockManager.HostControl = this;
            this.ultraDockManager.ShowCloseButton = false;
            this.ultraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.ultraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.ultraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.ultraDockManager_InitializePane);
                                                this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Name = "_ucDiarioClinicoPazienteUnpinnedTabAreaLeft";
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 624);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft.TabIndex = 0;
                                                this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Location = new System.Drawing.Point(855, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Name = "_ucDiarioClinicoPazienteUnpinnedTabAreaRight";
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.Size = new System.Drawing.Size(23, 624);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaRight.TabIndex = 1;
                                                this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Name = "_ucDiarioClinicoPazienteUnpinnedTabAreaTop";
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.Size = new System.Drawing.Size(855, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaTop.TabIndex = 2;
                                                this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 624);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Name = "_ucDiarioClinicoPazienteUnpinnedTabAreaBottom";
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.Size = new System.Drawing.Size(855, 0);
            this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom.TabIndex = 3;
                                                this._ucDiarioClinicoPazienteAutoHideControl.Controls.Add(this.dockableWindow1);
            this._ucDiarioClinicoPazienteAutoHideControl.Controls.Add(this.dockableWindow2);
            this._ucDiarioClinicoPazienteAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucDiarioClinicoPazienteAutoHideControl.Location = new System.Drawing.Point(63, 0);
            this._ucDiarioClinicoPazienteAutoHideControl.Name = "_ucDiarioClinicoPazienteAutoHideControl";
            this._ucDiarioClinicoPazienteAutoHideControl.Owner = this.ultraDockManager;
            this._ucDiarioClinicoPazienteAutoHideControl.Size = new System.Drawing.Size(792, 624);
            this._ucDiarioClinicoPazienteAutoHideControl.TabIndex = 4;
                                                this.dockableWindow1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dockableWindow1.Location = new System.Drawing.Point(5, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.ultraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(787, 624);
            this.dockableWindow1.TabIndex = 8;
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(855, 624);
            this.ultraGroupBox.TabIndex = 7;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.ucEasyTableLayoutPanelFiltro1.ColumnCount = 9;
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelFiltro1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTableLayoutPanel1, 1, 4);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTreeViewFiltroTipo, 3, 1);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyGridFiltroStato, 5, 1);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyGridFiltroUtente, 7, 1);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTableLayoutPanelFiltro2, 1, 5);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.txtFiltroUtente, 7, 2);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ubApplicaFiltro, 5, 7);
            this.ucEasyTableLayoutPanelFiltro1.Controls.Add(this.ucEasyTableLayoutPulsantiFiltro, 1, 1);
            this.ucEasyTableLayoutPanelFiltro1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltro1.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelFiltro1.Name = "ucEasyTableLayoutPanelFiltro1";
            this.ucEasyTableLayoutPanelFiltro1.RowCount = 9;
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 54F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelFiltro1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltro1.Size = new System.Drawing.Size(787, 606);
            this.ucEasyTableLayoutPanelFiltro1.TabIndex = 0;
                                                this.ucEasyTableLayoutPanel1.ColumnCount = 1;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ucEasyTableLayoutPanel1, 7);
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.Controls.Add(this.lblFiltroContenuto, 0, 0);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.utxtFiltroContenuto, 0, 1);
            this.ucEasyTableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel1.Location = new System.Drawing.Point(10, 378);
            this.ucEasyTableLayoutPanel1.Name = "ucEasyTableLayoutPanel1";
            this.ucEasyTableLayoutPanel1.RowCount = 2;
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanel1.Size = new System.Drawing.Size(761, 72);
            this.ucEasyTableLayoutPanel1.TabIndex = 17;
                                                appearance1.FontData.SizeInPoints = 14.26829F;
            appearance1.TextVAlignAsString = "Middle";
            this.lblFiltroContenuto.Appearance = appearance1;
            this.lblFiltroContenuto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroContenuto.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroContenuto.Name = "lblFiltroContenuto";
            this.lblFiltroContenuto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroContenuto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroContenuto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroContenuto.Size = new System.Drawing.Size(755, 22);
            this.lblFiltroContenuto.TabIndex = 2;
            this.lblFiltroContenuto.Text = "CONTENUTO:";
            this.lblFiltroContenuto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance2.FontData.SizeInPoints = 20.60976F;
            this.utxtFiltroContenuto.Appearance = appearance2;
            this.utxtFiltroContenuto.AutoSize = false;
            this.utxtFiltroContenuto.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtFiltroContenuto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtFiltroContenuto.Location = new System.Drawing.Point(3, 31);
            this.utxtFiltroContenuto.Name = "utxtFiltroContenuto";
            this.utxtFiltroContenuto.Size = new System.Drawing.Size(755, 38);
            this.utxtFiltroContenuto.TabIndex = 1;
            this.utxtFiltroContenuto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.utxtFiltroContenuto.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.utxtFiltroContenuto.KeyDown += new System.Windows.Forms.KeyEventHandler(this.utxtFiltroContenuto_KeyDown);
                                                appearance3.FontData.SizeInPoints = 14.26829F;
            this.ucEasyTreeViewFiltroTipo.Appearance = appearance3;
            this.ucEasyTreeViewFiltroTipo.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTreeViewFiltroTipo.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewFiltroTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewFiltroTipo.HideSelection = false;
            this.ucEasyTreeViewFiltroTipo.Location = new System.Drawing.Point(135, 9);
            this.ucEasyTreeViewFiltroTipo.Name = "ucEasyTreeViewFiltroTipo";
            this.ucEasyTreeViewFiltroTipo.Size = new System.Drawing.Size(269, 321);
            this.ucEasyTreeViewFiltroTipo.TabIndex = 16;
            this.ucEasyTreeViewFiltroTipo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeViewFiltroTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeViewFiltroTipo.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeViewFiltroTipo_AfterCheck);
                                                this.ucEasyGridFiltroStato.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroStato.ColonnaRTFResize = "";
            this.ucEasyGridFiltroStato.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance4.BackColor = System.Drawing.SystemColors.Window;
            appearance4.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroStato.DisplayLayout.Appearance = appearance4;
            this.ucEasyGridFiltroStato.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroStato.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance5.FontData.BoldAsString = "True";
            appearance5.FontData.SizeInPoints = 14.26829F;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionAppearance = appearance5;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance6.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance6.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance6.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Appearance = appearance6;
            appearance7.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BandLabelAppearance = appearance7;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance8.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance8.BackColor2 = System.Drawing.SystemColors.Control;
            appearance8.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance8.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.PromptAppearance = appearance8;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxRowScrollRegions = 1;
            appearance9.BackColor = System.Drawing.SystemColors.Window;
            appearance9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveCellAppearance = appearance9;
            appearance10.BackColor = System.Drawing.SystemColors.Highlight;
            appearance10.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveRowAppearance = appearance10;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CardAreaAppearance = appearance11;
            appearance12.BorderColor = System.Drawing.Color.Silver;
            appearance12.FontData.SizeInPoints = 14.26829F;
            appearance12.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellAppearance = appearance12;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance13.FontData.SizeInPoints = 14.26829F;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.FilterRowAppearance = appearance13;
            appearance14.BackColor = System.Drawing.SystemColors.Control;
            appearance14.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance14.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance14.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance14.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.GroupByRowAppearance = appearance14;
            appearance15.FontData.BoldAsString = "True";
            appearance15.FontData.SizeInPoints = 14.26829F;
            appearance15.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderAppearance = appearance15;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance16.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance16.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAlternateAppearance = appearance16;
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAppearance = appearance17;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance18.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.TemplateAddRowAppearance = appearance18;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroStato.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroStato.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroStato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroStato.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroStato.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.Location = new System.Drawing.Point(417, 9);
            this.ucEasyGridFiltroStato.Name = "ucEasyGridFiltroStato";
            this.ucEasyGridFiltroStato.ShowFilterRow = false;
            this.ucEasyGridFiltroStato.ShowGroupByBox = false;
            this.ucEasyGridFiltroStato.Size = new System.Drawing.Size(151, 321);
            this.ucEasyGridFiltroStato.TabIndex = 3;
            this.ucEasyGridFiltroStato.Text = "ucEasyGrid1";
            this.ucEasyGridFiltroStato.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroStato.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltro_InitializeLayout);
                                                this.ucEasyGridFiltroUtente.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroUtente.ColonnaRTFResize = "";
            this.ucEasyGridFiltroUtente.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUtente.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance19.BackColor = System.Drawing.SystemColors.Window;
            appearance19.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroUtente.DisplayLayout.Appearance = appearance19;
            this.ucEasyGridFiltroUtente.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroUtente.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance20.FontData.BoldAsString = "True";
            appearance20.FontData.SizeInPoints = 14.26829F;
            this.ucEasyGridFiltroUtente.DisplayLayout.CaptionAppearance = appearance20;
            this.ucEasyGridFiltroUtente.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance21.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance21.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance21.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance21.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUtente.DisplayLayout.GroupByBox.Appearance = appearance21;
            appearance22.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroUtente.DisplayLayout.GroupByBox.BandLabelAppearance = appearance22;
            this.ucEasyGridFiltroUtente.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroUtente.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroUtente.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance23.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance23.BackColor2 = System.Drawing.SystemColors.Control;
            appearance23.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance23.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroUtente.DisplayLayout.GroupByBox.PromptAppearance = appearance23;
            this.ucEasyGridFiltroUtente.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroUtente.DisplayLayout.MaxRowScrollRegions = 1;
            appearance24.BackColor = System.Drawing.SystemColors.Window;
            appearance24.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.ActiveCellAppearance = appearance24;
            appearance25.BackColor = System.Drawing.SystemColors.Highlight;
            appearance25.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.ActiveRowAppearance = appearance25;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance26.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.CardAreaAppearance = appearance26;
            appearance27.BorderColor = System.Drawing.Color.Silver;
            appearance27.FontData.SizeInPoints = 14.26829F;
            appearance27.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.CellAppearance = appearance27;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance28.FontData.SizeInPoints = 14.26829F;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.FilterRowAppearance = appearance28;
            appearance29.BackColor = System.Drawing.SystemColors.Control;
            appearance29.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance29.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance29.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance29.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.GroupByRowAppearance = appearance29;
            appearance30.FontData.BoldAsString = "True";
            appearance30.FontData.SizeInPoints = 14.26829F;
            appearance30.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.HeaderAppearance = appearance30;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance31.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance31.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.RowAlternateAppearance = appearance31;
            appearance32.BackColor = System.Drawing.SystemColors.Window;
            appearance32.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.RowAppearance = appearance32;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance33.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroUtente.DisplayLayout.Override.TemplateAddRowAppearance = appearance33;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroUtente.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGridFiltroUtente.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroUtente.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroUtente.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroUtente.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroUtente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroUtente.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroUtente.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUtente.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUtente.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroUtente.Location = new System.Drawing.Point(581, 9);
            this.ucEasyGridFiltroUtente.Name = "ucEasyGridFiltroUtente";
            this.ucEasyGridFiltroUtente.ShowFilterRow = false;
            this.ucEasyGridFiltroUtente.ShowGroupByBox = false;
            this.ucEasyGridFiltroUtente.Size = new System.Drawing.Size(190, 321);
            this.ucEasyGridFiltroUtente.TabIndex = 4;
            this.ucEasyGridFiltroUtente.Text = "ucEasyGrid1";
            this.ucEasyGridFiltroUtente.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroUtente.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroUtente.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltro_InitializeLayout);
                                                this.ucEasyTableLayoutPanelFiltro2.ColumnCount = 5;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ucEasyTableLayoutPanelFiltro2, 7);
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelFiltro2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.udteFiltroDA, 0, 1);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.udteFiltroA, 2, 1);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.lblFiltroDa, 0, 0);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.lblFiltroA, 2, 0);
            this.ucEasyTableLayoutPanelFiltro2.Controls.Add(this.drFiltro, 4, 1);
            this.ucEasyTableLayoutPanelFiltro2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltro2.Location = new System.Drawing.Point(10, 456);
            this.ucEasyTableLayoutPanelFiltro2.Name = "ucEasyTableLayoutPanelFiltro2";
            this.ucEasyTableLayoutPanelFiltro2.RowCount = 2;
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltro2.Size = new System.Drawing.Size(761, 72);
            this.ucEasyTableLayoutPanelFiltro2.TabIndex = 6;
                                                appearance34.FontData.SizeInPoints = 14.26829F;
            this.udteFiltroDA.Appearance = appearance34;
            this.udteFiltroDA.AutoSize = false;
            this.udteFiltroDA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroDA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroDA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance35.FontData.SizeInPoints = 14.26829F;
            this.udteFiltroDA.DropDownAppearance = appearance35;
            this.udteFiltroDA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroDA.Location = new System.Drawing.Point(3, 31);
            this.udteFiltroDA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroDA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroDA.Name = "udteFiltroDA";
            this.udteFiltroDA.Size = new System.Drawing.Size(222, 38);
            this.udteFiltroDA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroDA.TabIndex = 1;
            this.udteFiltroDA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroDA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance36.FontData.SizeInPoints = 14.26829F;
            this.udteFiltroA.Appearance = appearance36;
            this.udteFiltroA.AutoSize = false;
            this.udteFiltroA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance37.FontData.SizeInPoints = 14.26829F;
            this.udteFiltroA.DropDownAppearance = appearance37;
            this.udteFiltroA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroA.Location = new System.Drawing.Point(269, 31);
            this.udteFiltroA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroA.Name = "udteFiltroA";
            this.udteFiltroA.Size = new System.Drawing.Size(222, 38);
            this.udteFiltroA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroA.TabIndex = 2;
            this.udteFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance38.FontData.SizeInPoints = 14.26829F;
            appearance38.TextVAlignAsString = "Middle";
            this.lblFiltroDa.Appearance = appearance38;
            this.lblFiltroDa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDa.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroDa.Name = "lblFiltroDa";
            this.lblFiltroDa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDa.Size = new System.Drawing.Size(222, 22);
            this.lblFiltroDa.TabIndex = 2;
            this.lblFiltroDa.Text = "DA:";
            this.lblFiltroDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance39.FontData.SizeInPoints = 14.26829F;
            appearance39.TextVAlignAsString = "Middle";
            this.lblFiltroA.Appearance = appearance39;
            this.lblFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroA.Location = new System.Drawing.Point(269, 3);
            this.lblFiltroA.Name = "lblFiltroA";
            this.lblFiltroA.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroA.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroA.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroA.Size = new System.Drawing.Size(222, 22);
            this.lblFiltroA.TabIndex = 2;
            this.lblFiltroA.Text = "A:";
            this.lblFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance40.FontData.SizeInPoints = 14.26829F;
            this.drFiltro.Appearance = appearance40;
            this.drFiltro.AutoSize = false;
            this.drFiltro.DataEpisodio = new System.DateTime(((long)(0)));
            this.drFiltro.DateFuture = false;
            this.drFiltro.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.drFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.drFiltro.Domani = false;
            this.drFiltro.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem1.DisplayText = " ";
            valueListItem2.DataValue = "24H";
            valueListItem2.DisplayText = "Ultime 24h";
            valueListItem3.DataValue = "48H";
            valueListItem3.DisplayText = "Ultime 48h";
            valueListItem4.DataValue = "7G";
            valueListItem4.DisplayText = "Ultimi 7gg";
            valueListItem5.DataValue = "30G";
            valueListItem5.DisplayText = "Ultimi 30gg";
            valueListItem6.DataValue = "60G";
            valueListItem6.DisplayText = "Ultimi 60gg";
            valueListItem7.DataValue = "90G";
            valueListItem7.DisplayText = "Ultimi 90gg";
            valueListItem8.DataValue = "6M";
            valueListItem8.DisplayText = "Ultimi 6 mesi";
            this.drFiltro.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2,
            valueListItem3,
            valueListItem4,
            valueListItem5,
            valueListItem6,
            valueListItem7,
            valueListItem8});
            this.drFiltro.Location = new System.Drawing.Point(535, 31);
            this.drFiltro.Name = "drFiltro";
            this.drFiltro.Size = new System.Drawing.Size(223, 38);
            this.drFiltro.TabIndex = 0;
            this.drFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.drFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.drFiltro.ValueChanged += new System.EventHandler(this.drFiltro_ValueChanged);
                                                appearance41.FontData.SizeInPoints = 14.26829F;
            this.txtFiltroUtente.Appearance = appearance41;
            this.txtFiltroUtente.AutoSize = false;
            this.txtFiltroUtente.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtFiltroUtente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtFiltroUtente.Location = new System.Drawing.Point(581, 336);
            this.txtFiltroUtente.Name = "txtFiltroUtente";
            this.txtFiltroUtente.Size = new System.Drawing.Size(190, 30);
            this.txtFiltroUtente.TabIndex = 5;
            this.txtFiltroUtente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.txtFiltroUtente.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.txtFiltroUtente.ValueChanged += new System.EventHandler(this.txtFiltroUtente_ValueChanged);
                                                appearance42.FontData.SizeInPoints = 20.60976F;
            appearance42.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance42.ImageBackground")));
            appearance42.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance42.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance42.TextHAlignAsString = "Center";
            appearance42.TextVAlignAsString = "Middle";
            this.ubApplicaFiltro.Appearance = appearance42;
            this.ubApplicaFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanelFiltro1.SetColumnSpan(this.ubApplicaFiltro, 3);
            this.ubApplicaFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltro.Location = new System.Drawing.Point(417, 540);
            this.ubApplicaFiltro.Name = "ubApplicaFiltro";
            this.ubApplicaFiltro.PercImageFill = 0.75F;
            this.ubApplicaFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltro.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltro.Size = new System.Drawing.Size(354, 54);
            this.ubApplicaFiltro.TabIndex = 7;
            this.ubApplicaFiltro.Text = "Applica Filtro";
            this.ubApplicaFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltro.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ucEasyTableLayoutPulsantiFiltro.ColumnCount = 1;
            this.ucEasyTableLayoutPulsantiFiltro.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPulsantiFiltro.Controls.Add(this.uchkMedico, 0, 0);
            this.ucEasyTableLayoutPulsantiFiltro.Controls.Add(this.uchkInfermieristico, 0, 2);
            this.ucEasyTableLayoutPulsantiFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPulsantiFiltro.Location = new System.Drawing.Point(10, 9);
            this.ucEasyTableLayoutPulsantiFiltro.Name = "ucEasyTableLayoutPulsantiFiltro";
            this.ucEasyTableLayoutPulsantiFiltro.RowCount = 5;
            this.ucEasyTableLayoutPulsantiFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPulsantiFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPulsantiFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPulsantiFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPulsantiFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 22F));
            this.ucEasyTableLayoutPulsantiFiltro.Size = new System.Drawing.Size(112, 321);
            this.ucEasyTableLayoutPulsantiFiltro.TabIndex = 8;
                                                appearance43.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(212)))), ((int)(((byte)(138)))));
            appearance43.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(174)))), ((int)(((byte)(86)))));
            appearance43.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance43.BorderAlpha = Infragistics.Win.Alpha.Opaque;
            appearance43.BorderColor = System.Drawing.Color.Black;
            appearance43.FontData.BoldAsString = "True";
            appearance43.FontData.SizeInPoints = 20.60976F;
            appearance43.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance43.ImageBackground")));
            appearance43.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance43.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance43.TextHAlignAsString = "Center";
            appearance43.TextVAlignAsString = "Bottom";
            this.uchkMedico.Appearance = appearance43;
            this.uchkMedico.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkMedico.Checked = true;
            this.uchkMedico.CheckedImage = null;
            this.uchkMedico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkMedico.Location = new System.Drawing.Point(3, 3);
            this.uchkMedico.Name = "uchkMedico";
            this.uchkMedico.PercImageFill = 0.75F;
            this.uchkMedico.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkMedico.ShortcutKey = System.Windows.Forms.Keys.M;
            this.uchkMedico.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkMedico.Size = new System.Drawing.Size(106, 90);
            this.uchkMedico.TabIndex = 0;
            this.uchkMedico.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.uchkMedico.UNCheckedImage = null;
            this.uchkMedico.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance44.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(212)))), ((int)(((byte)(138)))));
            appearance44.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(174)))), ((int)(((byte)(86)))));
            appearance44.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance44.BorderAlpha = Infragistics.Win.Alpha.Opaque;
            appearance44.BorderColor = System.Drawing.Color.Black;
            appearance44.FontData.BoldAsString = "True";
            appearance44.FontData.SizeInPoints = 20.60976F;
            appearance44.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance44.ImageBackground")));
            appearance44.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance44.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance44.TextHAlignAsString = "Center";
            appearance44.TextVAlignAsString = "Bottom";
            this.uchkInfermieristico.Appearance = appearance44;
            this.uchkInfermieristico.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkInfermieristico.Checked = true;
            this.uchkInfermieristico.CheckedImage = null;
            this.uchkInfermieristico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkInfermieristico.Location = new System.Drawing.Point(3, 127);
            this.uchkInfermieristico.Name = "uchkInfermieristico";
            this.uchkInfermieristico.PercImageFill = 0.75F;
            this.uchkInfermieristico.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkInfermieristico.ShortcutKey = System.Windows.Forms.Keys.I;
            this.uchkInfermieristico.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkInfermieristico.Size = new System.Drawing.Size(106, 90);
            this.uchkInfermieristico.TabIndex = 1;
            this.uchkInfermieristico.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.uchkInfermieristico.UNCheckedImage = null;
            this.uchkInfermieristico.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                this.ucEasyTableLayoutPanel.ColumnCount = 5;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 88F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGrid, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPulsanti, 3, 1);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 3;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(849, 618);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance45.BackColor = System.Drawing.SystemColors.Window;
            appearance45.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance45;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance46.FontData.BoldAsString = "True";
            appearance46.FontData.SizeInPoints = 20.60976F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance46;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance47.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance47.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance47.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance47.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance47;
            appearance48.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance48;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance49.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance49.BackColor2 = System.Drawing.SystemColors.Control;
            appearance49.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance49.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance49;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance50.BackColor = System.Drawing.SystemColors.Window;
            appearance50.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance50;
            appearance51.BackColor = System.Drawing.SystemColors.Highlight;
            appearance51.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance51;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance52.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance52;
            appearance53.BorderColor = System.Drawing.Color.Silver;
            appearance53.FontData.SizeInPoints = 14.26829F;
            appearance53.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance53;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance54.FontData.SizeInPoints = 20.60976F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance54;
            appearance55.BackColor = System.Drawing.SystemColors.Control;
            appearance55.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance55.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance55.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance55.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance55;
            appearance56.FontData.BoldAsString = "True";
            appearance56.FontData.SizeInPoints = 14.26829F;
            appearance56.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance56;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance57.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance57.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance57;
            appearance58.BackColor = System.Drawing.SystemColors.Window;
            appearance58.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance58;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance59.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance59;
            scrollBarLook3.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(11, 9);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(741, 599);
            this.ucEasyGrid.TabIndex = 0;
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.AfterRowActivate += new System.EventHandler(this.ucEasyGrid_AfterRowActivate);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
            this.ucEasyGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucEasyGrid_ClickCell);
                                                this.ucEasyTableLayoutPulsanti.ColumnCount = 1;
            this.ucEasyTableLayoutPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.ubValida, 0, 2);
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.uchkFiltro, 0, 4);
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.ubAdd, 0, 0);
            this.ucEasyTableLayoutPulsanti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPulsanti.Location = new System.Drawing.Point(766, 9);
            this.ucEasyTableLayoutPulsanti.Name = "ucEasyTableLayoutPulsanti";
            this.ucEasyTableLayoutPulsanti.RowCount = 7;
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.ucEasyTableLayoutPulsanti.Size = new System.Drawing.Size(70, 599);
            this.ucEasyTableLayoutPulsanti.TabIndex = 4;
                                                appearance60.FontData.SizeInPoints = 20.60976F;
            appearance60.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance60.ImageBackground")));
            appearance60.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance60.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance60.TextHAlignAsString = "Center";
            appearance60.TextVAlignAsString = "Bottom";
            this.ubValida.Appearance = appearance60;
            this.ubValida.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubValida.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubValida.Location = new System.Drawing.Point(3, 133);
            this.ubValida.Name = "ubValida";
            this.ubValida.PercImageFill = 0.75F;
            this.ubValida.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubValida.ShortcutKey = System.Windows.Forms.Keys.V;
            this.ubValida.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubValida.Size = new System.Drawing.Size(64, 89);
            this.ubValida.TabIndex = 2;
            this.ubValida.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubValida.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubValida.Click += new System.EventHandler(this.ubValida_Click);
                                                appearance61.FontData.SizeInPoints = 20.60976F;
            appearance61.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance61.ImageBackground")));
            appearance61.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance61.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance61.TextHAlignAsString = "Center";
            appearance61.TextVAlignAsString = "Bottom";
            this.uchkFiltro.Appearance = appearance61;
            this.uchkFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkFiltro.Checked = false;
            this.uchkFiltro.CheckedImage = null;
            this.uchkFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkFiltro.Location = new System.Drawing.Point(3, 263);
            this.uchkFiltro.Name = "uchkFiltro";
            this.uchkFiltro.PercImageFill = 0.75F;
            this.uchkFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkFiltro.ShortcutKey = System.Windows.Forms.Keys.F;
            this.uchkFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkFiltro.Size = new System.Drawing.Size(64, 89);
            this.uchkFiltro.TabIndex = 1;
            this.uchkFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.uchkFiltro.UNCheckedImage = null;
            this.uchkFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uchkFiltro.Click += new System.EventHandler(this.uchkFiltro_Click);
                                                appearance62.FontData.SizeInPoints = 20.60976F;
            appearance62.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance62.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance62.TextHAlignAsString = "Center";
            appearance62.TextVAlignAsString = "Bottom";
            this.ubAdd.Appearance = appearance62;
            this.ubAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAdd.Location = new System.Drawing.Point(3, 3);
            this.ubAdd.Name = "ubAdd";
            this.ubAdd.PercImageFill = 0.75F;
            this.ubAdd.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAdd.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAdd.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAdd.Size = new System.Drawing.Size(64, 89);
            this.ubAdd.TabIndex = 3;
            this.ubAdd.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubAdd.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAdd.Click += new System.EventHandler(this.ubAdd_Click);
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Right;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(130, 0);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.ultraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(725, 624);
            this.windowDockingArea1.TabIndex = 6;
                                                this.dockableWindow2.Controls.Add(this.pnlFiltro);
            this.dockableWindow2.Location = new System.Drawing.Point(0, 0);
            this.dockableWindow2.Name = "dockableWindow2";
            this.dockableWindow2.Owner = this.ultraDockManager;
            this.dockableWindow2.Size = new System.Drawing.Size(0, 0);
            this.dockableWindow2.TabIndex = 8;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this._ucDiarioClinicoPazienteAutoHideControl);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._ucDiarioClinicoPazienteUnpinnedTabAreaTop);
            this.Controls.Add(this._ucDiarioClinicoPazienteUnpinnedTabAreaBottom);
            this.Controls.Add(this._ucDiarioClinicoPazienteUnpinnedTabAreaLeft);
            this.Controls.Add(this._ucDiarioClinicoPazienteUnpinnedTabAreaRight);
            this.Name = "ucDiarioClinicoPaziente";
            this.Size = new System.Drawing.Size(878, 624);
            this.Enter += new System.EventHandler(this.ucDiarioClinicoPaziente_Enter);
            this.pnlFiltro.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).EndInit();
            this._ucDiarioClinicoPazienteAutoHideControl.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFiltro1.ResumeLayout(false);
            this.ucEasyTableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.utxtFiltroContenuto)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewFiltroTipo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroUtente)).EndInit();
            this.ucEasyTableLayoutPanelFiltro2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtFiltroUtente)).EndInit();
            this.ucEasyTableLayoutPulsantiFiltro.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            this.ucEasyTableLayoutPulsanti.ResumeLayout(false);
            this.dockableWindow2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinDock.UltraDockManager ultraDockManager;
        private System.Windows.Forms.Panel pnlFiltro;
        private Infragistics.Win.UltraWinDock.AutoHideControl _ucDiarioClinicoPazienteAutoHideControl;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucDiarioClinicoPazienteUnpinnedTabAreaLeft;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucDiarioClinicoPazienteUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucDiarioClinicoPazienteUnpinnedTabAreaBottom;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucDiarioClinicoPazienteUnpinnedTabAreaRight;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyButton ubAdd;
        private ucEasyButton ubValida;
        private ucEasyGrid ucEasyGrid;
        private ucEasyStateButton uchkFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltro1;
        private ucEasyStateButton uchkMedico;
        private ucEasyStateButton uchkInfermieristico;
        private ucEasyGrid ucEasyGridFiltroStato;
        private ucEasyGrid ucEasyGridFiltroUtente;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltro2;
        private ucEasyDateTimeEditor udteFiltroDA;
        private ucEasyDateTimeEditor udteFiltroA;
        private ucEasyLabel lblFiltroDa;
        private ucEasyLabel lblFiltroA;
        private ucEasyTextBox txtFiltroUtente;
        private ucEasyDateRange drFiltro;
        private ucEasyButton ubApplicaFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPulsanti;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPulsantiFiltro;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private ucEasyTreeView ucEasyTreeViewFiltroTipo;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel1;
        private ucEasyLabel lblFiltroContenuto;
        private ucEasyTextBox utxtFiltroContenuto;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow2;
    }
}
