namespace UnicodeSrl.ScciCore
{
    partial class ucEasyO2SPDFView
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucEasyO2SPDFView));
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.uchkBookmark = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ubZoomIn = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubZoomOut = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubPageWidth = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubWholePage = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubPagUp = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubPagDown = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubPrint = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubShell = new UnicodeSrl.ScciCore.ucEasyButton();
            this.splitContainerPDF = new System.Windows.Forms.SplitContainer();
            this.pdfBookmarksView = new O2S.Components.PDFView4NET.PDFBookmarksView();
            this.pdfViewer = new O2S.Components.PDFView4NET.PDFPageView();
            this.ubCustomAction = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerPDF)).BeginInit();
            this.splitContainerPDF.Panel1.SuspendLayout();
            this.splitContainerPDF.Panel2.SuspendLayout();
            this.splitContainerPDF.SuspendLayout();
            this.SuspendLayout();
                                                this.ucEasyTableLayoutPanel.ColumnCount = 2;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 91F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.uchkBookmark, 1, 9);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubZoomIn, 1, 0);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubZoomOut, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubPageWidth, 1, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubWholePage, 1, 3);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubPagUp, 1, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubPagDown, 1, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubPrint, 0, 7);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubShell, 1, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.splitContainerPDF, 0, 0);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubCustomAction, 1, 8);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 10;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(815, 541);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 14.10448F;
            appearance1.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance1.ImageBackground")));
            appearance1.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance1.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance1.TextHAlignAsString = "Center";
            appearance1.TextVAlignAsString = "Bottom";
            this.uchkBookmark.Appearance = appearance1;
            this.uchkBookmark.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkBookmark.Checked = false;
            this.uchkBookmark.CheckedImage = null;
            this.uchkBookmark.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkBookmark.Location = new System.Drawing.Point(744, 501);
            this.uchkBookmark.Name = "uchkBookmark";
            this.uchkBookmark.PercImageFill = 0.75F;
            this.uchkBookmark.ShortcutColor = System.Drawing.Color.Black;
            this.uchkBookmark.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.uchkBookmark.ShortcutKey = System.Windows.Forms.Keys.I;
            this.uchkBookmark.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkBookmark.Size = new System.Drawing.Size(68, 37);
            this.uchkBookmark.TabIndex = 11;
            this.uchkBookmark.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkBookmark.UNCheckedImage = null;
            this.uchkBookmark.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uchkBookmark.Click += new System.EventHandler(this.uchkBookmark_Click);
                                                appearance2.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance2.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance2.TextHAlignAsString = "Center";
            appearance2.TextVAlignAsString = "Bottom";
            this.ubZoomIn.Appearance = appearance2;
            this.ubZoomIn.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubZoomIn.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubZoomIn.Location = new System.Drawing.Point(744, 3);
            this.ubZoomIn.Name = "ubZoomIn";
            this.ubZoomIn.PercImageFill = 0.75F;
            this.ubZoomIn.ShortcutColor = System.Drawing.Color.Black;
            this.ubZoomIn.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubZoomIn.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubZoomIn.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubZoomIn.Size = new System.Drawing.Size(68, 53);
            this.ubZoomIn.TabIndex = 1;
            this.ubZoomIn.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubZoomIn.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubZoomIn.Click += new System.EventHandler(this.ubZoomIn_Click);
                                                appearance3.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance3.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance3.TextHAlignAsString = "Center";
            appearance3.TextVAlignAsString = "Bottom";
            this.ubZoomOut.Appearance = appearance3;
            this.ubZoomOut.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubZoomOut.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubZoomOut.Location = new System.Drawing.Point(744, 62);
            this.ubZoomOut.Name = "ubZoomOut";
            this.ubZoomOut.PercImageFill = 0.75F;
            this.ubZoomOut.ShortcutColor = System.Drawing.Color.Black;
            this.ubZoomOut.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubZoomOut.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubZoomOut.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubZoomOut.Size = new System.Drawing.Size(68, 53);
            this.ubZoomOut.TabIndex = 1;
            this.ubZoomOut.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubZoomOut.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubZoomOut.Click += new System.EventHandler(this.ubZoomOut_Click);
                                                appearance4.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance4.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance4.TextHAlignAsString = "Center";
            appearance4.TextVAlignAsString = "Bottom";
            this.ubPageWidth.Appearance = appearance4;
            this.ubPageWidth.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubPageWidth.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubPageWidth.Location = new System.Drawing.Point(744, 121);
            this.ubPageWidth.Name = "ubPageWidth";
            this.ubPageWidth.PercImageFill = 0.75F;
            this.ubPageWidth.ShortcutColor = System.Drawing.Color.Black;
            this.ubPageWidth.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubPageWidth.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubPageWidth.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubPageWidth.Size = new System.Drawing.Size(68, 53);
            this.ubPageWidth.TabIndex = 1;
            this.ubPageWidth.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubPageWidth.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubPageWidth.Click += new System.EventHandler(this.ubPageWidth_Click);
                                                appearance5.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance5.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance5.TextHAlignAsString = "Center";
            appearance5.TextVAlignAsString = "Bottom";
            this.ubWholePage.Appearance = appearance5;
            this.ubWholePage.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubWholePage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubWholePage.Location = new System.Drawing.Point(744, 180);
            this.ubWholePage.Name = "ubWholePage";
            this.ubWholePage.PercImageFill = 0.75F;
            this.ubWholePage.ShortcutColor = System.Drawing.Color.Black;
            this.ubWholePage.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubWholePage.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubWholePage.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubWholePage.Size = new System.Drawing.Size(68, 53);
            this.ubWholePage.TabIndex = 1;
            this.ubWholePage.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubWholePage.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubWholePage.Click += new System.EventHandler(this.ubWholePage_Click);
                                                appearance6.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance6.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance6.TextHAlignAsString = "Center";
            appearance6.TextVAlignAsString = "Bottom";
            this.ubPagUp.Appearance = appearance6;
            this.ubPagUp.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubPagUp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubPagUp.Location = new System.Drawing.Point(744, 239);
            this.ubPagUp.Name = "ubPagUp";
            this.ubPagUp.PercImageFill = 0.75F;
            this.ubPagUp.ShortcutColor = System.Drawing.Color.Black;
            this.ubPagUp.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubPagUp.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubPagUp.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubPagUp.Size = new System.Drawing.Size(68, 53);
            this.ubPagUp.TabIndex = 1;
            this.ubPagUp.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubPagUp.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubPagUp.Click += new System.EventHandler(this.ubPagUp_Click);
                                                appearance7.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance7.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance7.TextHAlignAsString = "Center";
            appearance7.TextVAlignAsString = "Bottom";
            this.ubPagDown.Appearance = appearance7;
            this.ubPagDown.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubPagDown.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubPagDown.Location = new System.Drawing.Point(744, 298);
            this.ubPagDown.Name = "ubPagDown";
            this.ubPagDown.PercImageFill = 0.75F;
            this.ubPagDown.ShortcutColor = System.Drawing.Color.Black;
            this.ubPagDown.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubPagDown.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubPagDown.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubPagDown.Size = new System.Drawing.Size(68, 53);
            this.ubPagDown.TabIndex = 1;
            this.ubPagDown.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubPagDown.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubPagDown.Click += new System.EventHandler(this.ubPagDown_Click);
                                                appearance8.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance8.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance8.TextHAlignAsString = "Center";
            appearance8.TextVAlignAsString = "Bottom";
            this.ubPrint.Appearance = appearance8;
            this.ubPrint.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubPrint.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubPrint.Location = new System.Drawing.Point(744, 416);
            this.ubPrint.Name = "ubPrint";
            this.ubPrint.PercImageFill = 0.75F;
            this.ubPrint.ShortcutColor = System.Drawing.Color.Black;
            this.ubPrint.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubPrint.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubPrint.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubPrint.Size = new System.Drawing.Size(68, 31);
            this.ubPrint.TabIndex = 1;
            this.ubPrint.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubPrint.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubPrint.Click += new System.EventHandler(this.ubPrint_Click);
                                                appearance9.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance9.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance9.TextHAlignAsString = "Center";
            appearance9.TextVAlignAsString = "Bottom";
            this.ubShell.Appearance = appearance9;
            this.ubShell.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubShell.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubShell.Location = new System.Drawing.Point(744, 357);
            this.ubShell.Name = "ubShell";
            this.ubShell.PercImageFill = 0.75F;
            this.ubShell.ShortcutColor = System.Drawing.Color.Black;
            this.ubShell.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubShell.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubShell.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubShell.Size = new System.Drawing.Size(68, 53);
            this.ubShell.TabIndex = 1;
            this.ubShell.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubShell.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubShell.Click += new System.EventHandler(this.ubShell_Click);
                                                this.splitContainerPDF.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerPDF.Location = new System.Drawing.Point(3, 3);
            this.splitContainerPDF.Name = "splitContainerPDF";
                                                this.splitContainerPDF.Panel1.Controls.Add(this.pdfBookmarksView);
            this.splitContainerPDF.Panel1Collapsed = true;
            this.splitContainerPDF.Panel1MinSize = 0;
                                                this.splitContainerPDF.Panel2.Controls.Add(this.pdfViewer);
            this.ucEasyTableLayoutPanel.SetRowSpan(this.splitContainerPDF, 10);
            this.splitContainerPDF.Size = new System.Drawing.Size(735, 535);
            this.splitContainerPDF.SplitterDistance = 168;
            this.splitContainerPDF.SplitterWidth = 6;
            this.splitContainerPDF.TabIndex = 10;
                                                this.pdfBookmarksView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.pdfBookmarksView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pdfBookmarksView.HideSelection = false;
            this.pdfBookmarksView.Location = new System.Drawing.Point(0, 0);
            this.pdfBookmarksView.Name = "pdfBookmarksView";
            this.pdfBookmarksView.PageView = this.pdfViewer;
            this.pdfBookmarksView.ShowNodeToolTips = true;
            this.pdfBookmarksView.Size = new System.Drawing.Size(168, 100);
            this.pdfBookmarksView.TabIndex = 9;
                                                this.pdfViewer.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.pdfViewer.DefaultEllipseAnnotationBorderWidth = 1D;
            this.pdfViewer.DefaultInkAnnotationWidth = 1D;
            this.pdfViewer.DefaultRectangleAnnotationBorderWidth = 1D;
            this.pdfViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pdfViewer.DownscaleLargeImages = false;
            this.pdfViewer.EnableRepeatedKeys = false;
            this.pdfViewer.Location = new System.Drawing.Point(0, 0);
            this.pdfViewer.Name = "pdfViewer";
            this.pdfViewer.PageDisplayLayout = O2S.Components.PDFView4NET.PDFPageDisplayLayout.SinglePage;
            this.pdfViewer.PageNumber = 0;
            this.pdfViewer.RenderingProgressColor = System.Drawing.Color.Empty;
            this.pdfViewer.RequiredFormFieldHighlightColor = System.Drawing.Color.Empty;
            this.pdfViewer.ScrollPosition = new System.Drawing.Point(0, 0);
            this.pdfViewer.Size = new System.Drawing.Size(735, 535);
            this.pdfViewer.SubstituteFonts = null;
            this.pdfViewer.TabIndex = 8;
            this.pdfViewer.WorkMode = O2S.Components.PDFView4NET.UserInteractiveWorkMode.None;
            this.pdfViewer.ZoomMode = O2S.Components.PDFView4NET.PDFZoomMode.FitVisible;
                                                appearance10.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance10.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance10.TextHAlignAsString = "Center";
            appearance10.TextVAlignAsString = "Bottom";
            this.ubCustomAction.Appearance = appearance10;
            this.ubCustomAction.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubCustomAction.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCustomAction.Location = new System.Drawing.Point(744, 453);
            this.ubCustomAction.Name = "ubCustomAction";
            this.ubCustomAction.PercImageFill = 0.75F;
            this.ubCustomAction.ShortcutColor = System.Drawing.Color.Black;
            this.ubCustomAction.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubCustomAction.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubCustomAction.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubCustomAction.Size = new System.Drawing.Size(68, 42);
            this.ubCustomAction.TabIndex = 1;
            this.ubCustomAction.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ubCustomAction.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubCustomAction.Visible = false;
            this.ubCustomAction.Click += new System.EventHandler(this.ubCustomAction_Click);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.ucEasyTableLayoutPanel);
            this.Name = "ucEasyO2SPDFView";
            this.Size = new System.Drawing.Size(815, 541);
            this.VisibleChanged += new System.EventHandler(this.ucEasyO2SPDFView_VisibleChanged);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            this.splitContainerPDF.Panel1.ResumeLayout(false);
            this.splitContainerPDF.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerPDF)).EndInit();
            this.splitContainerPDF.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyButton ubZoomIn;
        private ucEasyButton ubZoomOut;
        private ucEasyButton ubPageWidth;
        private ucEasyButton ubWholePage;
        private ucEasyButton ubPagUp;
        private ucEasyButton ubPagDown;
        private ucEasyButton ubPrint;
        private ucEasyButton ubShell;
        private O2S.Components.PDFView4NET.PDFPageView pdfViewer;
        private O2S.Components.PDFView4NET.PDFBookmarksView pdfBookmarksView;
        private System.Windows.Forms.SplitContainer splitContainerPDF;
        private ucEasyStateButton uchkBookmark;
        private ucEasyButton ubCustomAction;
    }
}
