namespace UnicodeSrl.ScciCore
{
    partial class ucEasyMultiSelect
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.lblCercaSX = new System.Windows.Forms.Label();
            this.lblCercaDX = new System.Windows.Forms.Label();
            this.uteCercaSX = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.uteCercaDX = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.ubInserisci = new Infragistics.Win.Misc.UltraButton();
            this.ubInserisciAll = new Infragistics.Win.Misc.UltraButton();
            this.ubCancellaAll = new Infragistics.Win.Misc.UltraButton();
            this.ubCancella = new Infragistics.Win.Misc.UltraButton();
            this.UltraGridSX = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.UltraGridDX = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteCercaSX)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCercaDX)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridSX)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridDX)).BeginInit();
            this.SuspendLayout();
                                                this.TableLayoutPanel.ColumnCount = 7;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.TableLayoutPanel.Controls.Add(this.lblCercaSX, 0, 7);
            this.TableLayoutPanel.Controls.Add(this.lblCercaDX, 5, 7);
            this.TableLayoutPanel.Controls.Add(this.uteCercaSX, 1, 7);
            this.TableLayoutPanel.Controls.Add(this.uteCercaDX, 6, 7);
            this.TableLayoutPanel.Controls.Add(this.ubInserisci, 3, 0);
            this.TableLayoutPanel.Controls.Add(this.ubInserisciAll, 3, 2);
            this.TableLayoutPanel.Controls.Add(this.ubCancellaAll, 3, 4);
            this.TableLayoutPanel.Controls.Add(this.ubCancella, 3, 6);
            this.TableLayoutPanel.Controls.Add(this.UltraGridSX, 0, 0);
            this.TableLayoutPanel.Controls.Add(this.UltraGridDX, 5, 0);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 8;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(800, 600);
            this.TableLayoutPanel.TabIndex = 1;
                                                this.lblCercaSX.AutoSize = true;
            this.lblCercaSX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCercaSX.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCercaSX.Location = new System.Drawing.Point(3, 565);
            this.lblCercaSX.Name = "lblCercaSX";
            this.lblCercaSX.Size = new System.Drawing.Size(106, 35);
            this.lblCercaSX.TabIndex = 2;
            this.lblCercaSX.Text = "Cerca:";
            this.lblCercaSX.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.lblCercaDX.AutoSize = true;
            this.lblCercaDX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCercaDX.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCercaDX.Location = new System.Drawing.Point(451, 565);
            this.lblCercaDX.Name = "lblCercaDX";
            this.lblCercaDX.Size = new System.Drawing.Size(106, 35);
            this.lblCercaDX.TabIndex = 3;
            this.lblCercaDX.Text = "Cerca:";
            this.lblCercaDX.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.uteCercaSX.AutoSize = false;
            this.uteCercaSX.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteCercaSX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteCercaSX.Location = new System.Drawing.Point(112, 565);
            this.uteCercaSX.Margin = new System.Windows.Forms.Padding(0);
            this.uteCercaSX.Name = "uteCercaSX";
            this.uteCercaSX.Size = new System.Drawing.Size(240, 35);
            this.uteCercaSX.TabIndex = 1;
            this.uteCercaSX.ValueChanged += new System.EventHandler(this.uteCercaSX_ValueChanged);
                                                this.uteCercaDX.AutoSize = false;
            this.uteCercaDX.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteCercaDX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteCercaDX.Location = new System.Drawing.Point(560, 565);
            this.uteCercaDX.Margin = new System.Windows.Forms.Padding(0);
            this.uteCercaDX.Name = "uteCercaDX";
            this.uteCercaDX.Size = new System.Drawing.Size(240, 35);
            this.uteCercaDX.TabIndex = 7;
            this.uteCercaDX.ValueChanged += new System.EventHandler(this.uteCercaDX_ValueChanged);
                                                appearance1.Image = global::UnicodeSrl.ScciCore.Properties.Resources.SpostaDx;
            appearance1.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance1.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance1.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.ubInserisci.Appearance = appearance1;
            this.ubInserisci.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsXPCommandButton;
            this.ubInserisci.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubInserisci.ImageSize = new System.Drawing.Size(64, 64);
            this.ubInserisci.Location = new System.Drawing.Point(363, 3);
            this.ubInserisci.Name = "ubInserisci";
            this.ubInserisci.Size = new System.Drawing.Size(74, 96);
            this.ubInserisci.TabIndex = 2;
            this.ubInserisci.Click += new System.EventHandler(this.ubInserisci_Click);
            this.ubInserisci.Resize += new System.EventHandler(this.ubButton_Resize);
                                                appearance2.Image = global::UnicodeSrl.ScciCore.Properties.Resources.SpostaDxTutto;
            appearance2.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance2.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance2.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.ubInserisciAll.Appearance = appearance2;
            this.ubInserisciAll.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsXPCommandButton;
            this.ubInserisciAll.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubInserisciAll.ImageSize = new System.Drawing.Size(64, 64);
            this.ubInserisciAll.Location = new System.Drawing.Point(363, 144);
            this.ubInserisciAll.Name = "ubInserisciAll";
            this.ubInserisciAll.Size = new System.Drawing.Size(74, 96);
            this.ubInserisciAll.TabIndex = 3;
            this.ubInserisciAll.Click += new System.EventHandler(this.ubInserisciAll_Click);
            this.ubInserisciAll.Resize += new System.EventHandler(this.ubButton_Resize);
                                                appearance3.Image = global::UnicodeSrl.ScciCore.Properties.Resources.SpostaSxTutto;
            appearance3.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance3.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance3.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.ubCancellaAll.Appearance = appearance3;
            this.ubCancellaAll.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsXPCommandButton;
            this.ubCancellaAll.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCancellaAll.ImageSize = new System.Drawing.Size(64, 64);
            this.ubCancellaAll.Location = new System.Drawing.Point(363, 325);
            this.ubCancellaAll.Name = "ubCancellaAll";
            this.ubCancellaAll.Size = new System.Drawing.Size(74, 96);
            this.ubCancellaAll.TabIndex = 4;
            this.ubCancellaAll.Click += new System.EventHandler(this.ubCancellaAll_Click);
            this.ubCancellaAll.Resize += new System.EventHandler(this.ubButton_Resize);
                                                appearance4.Image = global::UnicodeSrl.ScciCore.Properties.Resources.SpostaSx;
            appearance4.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance4.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance4.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.ubCancella.Appearance = appearance4;
            this.ubCancella.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsXPCommandButton;
            this.ubCancella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCancella.ImageSize = new System.Drawing.Size(64, 64);
            this.ubCancella.Location = new System.Drawing.Point(363, 466);
            this.ubCancella.Name = "ubCancella";
            this.ubCancella.Size = new System.Drawing.Size(74, 96);
            this.ubCancella.TabIndex = 5;
            this.ubCancella.Click += new System.EventHandler(this.ubCancella_Click);
            this.ubCancella.Resize += new System.EventHandler(this.ubButton_Resize);
                                                this.UltraGridSX.ColonnaRTFResize = "";
            this.TableLayoutPanel.SetColumnSpan(this.UltraGridSX, 2);
            this.UltraGridSX.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridSX.DisplayLayout.Appearance = appearance5;
            this.UltraGridSX.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridSX.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance6.FontData.BoldAsString = "True";
            this.UltraGridSX.DisplayLayout.CaptionAppearance = appearance6;
            this.UltraGridSX.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance7.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance7.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance7.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance7.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridSX.DisplayLayout.GroupByBox.Appearance = appearance7;
            appearance8.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridSX.DisplayLayout.GroupByBox.BandLabelAppearance = appearance8;
            this.UltraGridSX.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridSX.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridSX.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance9.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance9.BackColor2 = System.Drawing.SystemColors.Control;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridSX.DisplayLayout.GroupByBox.PromptAppearance = appearance9;
            this.UltraGridSX.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridSX.DisplayLayout.MaxRowScrollRegions = 1;
            appearance10.BackColor = System.Drawing.SystemColors.Window;
            appearance10.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridSX.DisplayLayout.Override.ActiveCellAppearance = appearance10;
            appearance11.BackColor = System.Drawing.SystemColors.Highlight;
            appearance11.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridSX.DisplayLayout.Override.ActiveRowAppearance = appearance11;
            this.UltraGridSX.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridSX.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridSX.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSX.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSX.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSX.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridSX.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance12.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridSX.DisplayLayout.Override.CardAreaAppearance = appearance12;
            appearance13.BorderColor = System.Drawing.Color.Silver;
            appearance13.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridSX.DisplayLayout.Override.CellAppearance = appearance13;
            this.UltraGridSX.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridSX.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridSX.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance14.BackColor = System.Drawing.SystemColors.Control;
            appearance14.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance14.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance14.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance14.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridSX.DisplayLayout.Override.GroupByRowAppearance = appearance14;
            appearance15.FontData.BoldAsString = "True";
            appearance15.TextHAlignAsString = "Center";
            this.UltraGridSX.DisplayLayout.Override.HeaderAppearance = appearance15;
            this.UltraGridSX.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridSX.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance16.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance16.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridSX.DisplayLayout.Override.RowAlternateAppearance = appearance16;
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridSX.DisplayLayout.Override.RowAppearance = appearance17;
            this.UltraGridSX.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSX.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridSX.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridSX.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance18.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridSX.DisplayLayout.Override.TemplateAddRowAppearance = appearance18;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridSX.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.UltraGridSX.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridSX.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridSX.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridSX.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridSX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridSX.FattoreRidimensionamentoRTF = 21;
            this.UltraGridSX.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridSX.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridSX.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridSX.Location = new System.Drawing.Point(3, 3);
            this.UltraGridSX.Name = "UltraGridSX";
            this.TableLayoutPanel.SetRowSpan(this.UltraGridSX, 7);
            this.UltraGridSX.ShowFilterRow = false;
            this.UltraGridSX.ShowGroupByBox = false;
            this.UltraGridSX.Size = new System.Drawing.Size(346, 559);
            this.UltraGridSX.TabIndex = 8;
            this.UltraGridSX.Text = "ucEasyGrid1";
            this.UltraGridSX.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridSX.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSX.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridSX_InitializeLayout);
            this.UltraGridSX.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGridSX_InitializeRow);
            this.UltraGridSX.AfterSelectChange += new Infragistics.Win.UltraWinGrid.AfterSelectChangeEventHandler(this.UltraGridSX_AfterSelectChange);
            this.UltraGridSX.DoubleClickRow += new Infragistics.Win.UltraWinGrid.DoubleClickRowEventHandler(this.UltraGridSX_DoubleClickRow);
                                                this.UltraGridDX.ColonnaRTFResize = "";
            this.TableLayoutPanel.SetColumnSpan(this.UltraGridDX, 2);
            this.UltraGridDX.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            appearance19.BackColor = System.Drawing.SystemColors.Window;
            appearance19.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridDX.DisplayLayout.Appearance = appearance19;
            this.UltraGridDX.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridDX.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance20.FontData.BoldAsString = "True";
            this.UltraGridDX.DisplayLayout.CaptionAppearance = appearance20;
            this.UltraGridDX.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance21.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance21.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance21.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance21.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridDX.DisplayLayout.GroupByBox.Appearance = appearance21;
            appearance22.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridDX.DisplayLayout.GroupByBox.BandLabelAppearance = appearance22;
            this.UltraGridDX.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridDX.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridDX.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance23.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance23.BackColor2 = System.Drawing.SystemColors.Control;
            appearance23.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance23.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridDX.DisplayLayout.GroupByBox.PromptAppearance = appearance23;
            this.UltraGridDX.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridDX.DisplayLayout.MaxRowScrollRegions = 1;
            appearance24.BackColor = System.Drawing.SystemColors.Window;
            appearance24.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridDX.DisplayLayout.Override.ActiveCellAppearance = appearance24;
            appearance25.BackColor = System.Drawing.SystemColors.Highlight;
            appearance25.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridDX.DisplayLayout.Override.ActiveRowAppearance = appearance25;
            this.UltraGridDX.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridDX.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridDX.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDX.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDX.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDX.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridDX.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance26.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridDX.DisplayLayout.Override.CardAreaAppearance = appearance26;
            appearance27.BorderColor = System.Drawing.Color.Silver;
            appearance27.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridDX.DisplayLayout.Override.CellAppearance = appearance27;
            this.UltraGridDX.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridDX.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridDX.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance28.BackColor = System.Drawing.SystemColors.Control;
            appearance28.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance28.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance28.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance28.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridDX.DisplayLayout.Override.GroupByRowAppearance = appearance28;
            appearance29.FontData.BoldAsString = "True";
            appearance29.TextHAlignAsString = "Center";
            this.UltraGridDX.DisplayLayout.Override.HeaderAppearance = appearance29;
            this.UltraGridDX.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridDX.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance30.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance30.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridDX.DisplayLayout.Override.RowAlternateAppearance = appearance30;
            appearance31.BackColor = System.Drawing.SystemColors.Window;
            appearance31.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridDX.DisplayLayout.Override.RowAppearance = appearance31;
            this.UltraGridDX.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDX.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridDX.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridDX.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance32.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridDX.DisplayLayout.Override.TemplateAddRowAppearance = appearance32;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridDX.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.UltraGridDX.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridDX.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridDX.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridDX.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridDX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridDX.FattoreRidimensionamentoRTF = 21;
            this.UltraGridDX.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridDX.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridDX.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.UltraGridDX.Location = new System.Drawing.Point(451, 3);
            this.UltraGridDX.Name = "UltraGridDX";
            this.TableLayoutPanel.SetRowSpan(this.UltraGridDX, 7);
            this.UltraGridDX.ShowFilterRow = false;
            this.UltraGridDX.ShowGroupByBox = false;
            this.UltraGridDX.Size = new System.Drawing.Size(346, 559);
            this.UltraGridDX.TabIndex = 9;
            this.UltraGridDX.Text = "ucEasyGrid1";
            this.UltraGridDX.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridDX.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDX.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridDX_InitializeLayout);
            this.UltraGridDX.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGridDX_InitializeRow);
            this.UltraGridDX.AfterSelectChange += new Infragistics.Win.UltraWinGrid.AfterSelectChangeEventHandler(this.UltraGridDX_AfterSelectChange);
            this.UltraGridDX.DoubleClickRow += new Infragistics.Win.UltraWinGrid.DoubleClickRowEventHandler(this.UltraGridDX_DoubleClickRow);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.TableLayoutPanel);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F);
            this.Name = "ucEasyMultiSelect";
            this.Size = new System.Drawing.Size(800, 600);
            this.TableLayoutPanel.ResumeLayout(false);
            this.TableLayoutPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteCercaSX)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCercaDX)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridSX)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridDX)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        internal System.Windows.Forms.Label lblCercaSX;
        internal System.Windows.Forms.Label lblCercaDX;
        internal Infragistics.Win.UltraWinEditors.UltraTextEditor uteCercaSX;
        internal Infragistics.Win.UltraWinEditors.UltraTextEditor uteCercaDX;
        internal Infragistics.Win.Misc.UltraButton ubInserisci;
        internal Infragistics.Win.Misc.UltraButton ubInserisciAll;
        internal Infragistics.Win.Misc.UltraButton ubCancellaAll;
        internal Infragistics.Win.Misc.UltraButton ubCancella;
        private ucEasyGrid UltraGridSX;
        private ucEasyGrid UltraGridDX;
    }
}
