namespace UnicodeSrl.ScciCore
{
    partial class ucEasyPopUpTerapiaRapida
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton1 = new Infragistics.Win.UltraWinEditors.EditorButton("Orari");
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTextBoxPosologia = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ucEasyLabelPosologia = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyLabelPrescrizione = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyDateTimeEditorDataOra = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.ucEasyLabelDataOra = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyButtonConferma = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyButtonCancel = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyTextBoxPrescrizione = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.uceViaSomministrazione = new UnicodeSrl.ScciCore.ucEasyComboEditor();
            this.ucEasyLabelVia = new UnicodeSrl.ScciCore.ucEasyLabel();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTextBoxPosologia)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyDateTimeEditorDataOra)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTextBoxPrescrizione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uceViaSomministrazione)).BeginInit();
            this.SuspendLayout();
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(500, 400);
            this.ultraGroupBox.TabIndex = 0;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.ColumnCount = 3;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyLabelVia, 0, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTextBoxPosologia, 0, 7);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyLabelPosologia, 0, 6);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyLabelPrescrizione, 0, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyDateTimeEditorDataOra, 0, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyLabelDataOra, 0, 0);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyButtonConferma, 2, 9);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyButtonCancel, 0, 9);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTextBoxPrescrizione, 0, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.uceViaSomministrazione, 0, 3);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 10;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(494, 394);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance2.FontData.SizeInPoints = 20F;
            this.ucEasyTextBoxPosologia.Appearance = appearance2;
            this.ucEasyTextBoxPosologia.AutoSize = false;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTextBoxPosologia, 3);
            this.ucEasyTextBoxPosologia.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.ucEasyTextBoxPosologia.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTextBoxPosologia.Location = new System.Drawing.Point(3, 299);
            this.ucEasyTextBoxPosologia.Multiline = true;
            this.ucEasyTextBoxPosologia.Name = "ucEasyTextBoxPosologia";
            this.ucEasyTextBoxPosologia.Scrollbars = System.Windows.Forms.ScrollBars.Vertical;
            this.ucEasyTextBoxPosologia.Size = new System.Drawing.Size(488, 41);
            this.ucEasyTextBoxPosologia.TabIndex = 3;
            this.ucEasyTextBoxPosologia.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ucEasyTextBoxPosologia.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance3.FontData.SizeInPoints = 16.25F;
            appearance3.TextVAlignAsString = "Middle";
            this.ucEasyLabelPosologia.Appearance = appearance3;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyLabelPosologia, 3);
            this.ucEasyLabelPosologia.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabelPosologia.Location = new System.Drawing.Point(3, 268);
            this.ucEasyLabelPosologia.Name = "ucEasyLabelPosologia";
            this.ucEasyLabelPosologia.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabelPosologia.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabelPosologia.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabelPosologia.Size = new System.Drawing.Size(488, 25);
            this.ucEasyLabelPosologia.TabIndex = 5;
            this.ucEasyLabelPosologia.Text = "Posologia:";
            this.ucEasyLabelPosologia.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance4.FontData.SizeInPoints = 16.25F;
            appearance4.TextVAlignAsString = "Middle";
            this.ucEasyLabelPrescrizione.Appearance = appearance4;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyLabelPrescrizione, 3);
            this.ucEasyLabelPrescrizione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabelPrescrizione.Location = new System.Drawing.Point(3, 159);
            this.ucEasyLabelPrescrizione.Name = "ucEasyLabelPrescrizione";
            this.ucEasyLabelPrescrizione.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabelPrescrizione.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabelPrescrizione.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabelPrescrizione.Size = new System.Drawing.Size(488, 25);
            this.ucEasyLabelPrescrizione.TabIndex = 4;
            this.ucEasyLabelPrescrizione.Text = "Prescrizione:";
            this.ucEasyLabelPrescrizione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance5.FontData.SizeInPoints = 20F;
            this.ucEasyDateTimeEditorDataOra.Appearance = appearance5;
            this.ucEasyDateTimeEditorDataOra.AutoSize = false;
            appearance6.TextHAlignAsString = "Center";
            editorButton1.Appearance = appearance6;
            editorButton1.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2007RibbonButton;
            editorButton1.Key = "Orari";
            editorButton1.Text = "H";
            this.ucEasyDateTimeEditorDataOra.ButtonsRight.Add(editorButton1);
            this.ucEasyDateTimeEditorDataOra.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyDateTimeEditorDataOra, 3);
            this.ucEasyDateTimeEditorDataOra.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.ucEasyDateTimeEditorDataOra.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance7.FontData.SizeInPoints = 20F;
            this.ucEasyDateTimeEditorDataOra.DropDownAppearance = appearance7;
            this.ucEasyDateTimeEditorDataOra.FormatString = "dd/MM/yyyy HH:mm";
            this.ucEasyDateTimeEditorDataOra.Location = new System.Drawing.Point(3, 34);
            this.ucEasyDateTimeEditorDataOra.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.ucEasyDateTimeEditorDataOra.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.ucEasyDateTimeEditorDataOra.Name = "ucEasyDateTimeEditorDataOra";
            this.ucEasyDateTimeEditorDataOra.Size = new System.Drawing.Size(488, 41);
            this.ucEasyDateTimeEditorDataOra.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.ucEasyDateTimeEditorDataOra.TabIndex = 0;
            this.ucEasyDateTimeEditorDataOra.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ucEasyDateTimeEditorDataOra.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyDateTimeEditorDataOra.EditorButtonClick += new Infragistics.Win.UltraWinEditors.EditorButtonEventHandler(this.ucEasyDateTimeEditorDataOra_EditorButtonClick);
                                                appearance8.FontData.SizeInPoints = 16.25F;
            appearance8.TextVAlignAsString = "Middle";
            this.ucEasyLabelDataOra.Appearance = appearance8;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyLabelDataOra, 3);
            this.ucEasyLabelDataOra.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabelDataOra.Location = new System.Drawing.Point(3, 3);
            this.ucEasyLabelDataOra.Name = "ucEasyLabelDataOra";
            this.ucEasyLabelDataOra.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabelDataOra.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabelDataOra.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabelDataOra.Size = new System.Drawing.Size(488, 25);
            this.ucEasyLabelDataOra.TabIndex = 5;
            this.ucEasyLabelDataOra.Text = "Data Ora:";
            this.ucEasyLabelDataOra.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance9.FontData.SizeInPoints = 16.25F;
            appearance9.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance9.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance9.TextHAlignAsString = "Center";
            appearance9.TextVAlignAsString = "Middle";
            this.ucEasyButtonConferma.Appearance = appearance9;
            this.ucEasyButtonConferma.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonConferma.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonConferma.Location = new System.Drawing.Point(298, 353);
            this.ucEasyButtonConferma.Name = "ucEasyButtonConferma";
            this.ucEasyButtonConferma.PercImageFill = 0.75F;
            this.ucEasyButtonConferma.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonConferma.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonConferma.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonConferma.Size = new System.Drawing.Size(193, 38);
            this.ucEasyButtonConferma.TabIndex = 5;
            this.ucEasyButtonConferma.Text = "Conferma";
            this.ucEasyButtonConferma.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyButtonConferma.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonConferma.Click += new System.EventHandler(this.ucEasyButtonConferma_Click);
                                                appearance10.FontData.SizeInPoints = 16.25F;
            appearance10.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance10.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance10.TextHAlignAsString = "Center";
            appearance10.TextVAlignAsString = "Middle";
            this.ucEasyButtonCancel.Appearance = appearance10;
            this.ucEasyButtonCancel.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyButtonCancel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyButtonCancel.Location = new System.Drawing.Point(3, 353);
            this.ucEasyButtonCancel.Name = "ucEasyButtonCancel";
            this.ucEasyButtonCancel.PercImageFill = 0.75F;
            this.ucEasyButtonCancel.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyButtonCancel.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyButtonCancel.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyButtonCancel.Size = new System.Drawing.Size(191, 38);
            this.ucEasyButtonCancel.TabIndex = 4;
            this.ucEasyButtonCancel.Text = "Annulla";
            this.ucEasyButtonCancel.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyButtonCancel.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyButtonCancel.Click += new System.EventHandler(this.ucEasyButtonCancel_Click);
                                                appearance11.FontData.SizeInPoints = 20F;
            this.ucEasyTextBoxPrescrizione.Appearance = appearance11;
            this.ucEasyTextBoxPrescrizione.AutoSize = false;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTextBoxPrescrizione, 3);
            this.ucEasyTextBoxPrescrizione.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.ucEasyTextBoxPrescrizione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTextBoxPrescrizione.Location = new System.Drawing.Point(3, 190);
            this.ucEasyTextBoxPrescrizione.Multiline = true;
            this.ucEasyTextBoxPrescrizione.Name = "ucEasyTextBoxPrescrizione";
            this.ucEasyTextBoxPrescrizione.Scrollbars = System.Windows.Forms.ScrollBars.Vertical;
            this.ucEasyTextBoxPrescrizione.Size = new System.Drawing.Size(488, 72);
            this.ucEasyTextBoxPrescrizione.TabIndex = 2;
            this.ucEasyTextBoxPrescrizione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ucEasyTextBoxPrescrizione.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance12.FontData.SizeInPoints = 20F;
            this.uceViaSomministrazione.Appearance = appearance12;
            this.uceViaSomministrazione.AutoSize = false;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.uceViaSomministrazione, 3);
            this.uceViaSomministrazione.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uceViaSomministrazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uceViaSomministrazione.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.uceViaSomministrazione.Location = new System.Drawing.Point(3, 112);
            this.uceViaSomministrazione.Name = "uceViaSomministrazione";
            this.uceViaSomministrazione.Size = new System.Drawing.Size(488, 41);
            this.uceViaSomministrazione.TabIndex = 1;
            this.uceViaSomministrazione.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.uceViaSomministrazione.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance1.FontData.SizeInPoints = 16.25F;
            appearance1.TextVAlignAsString = "Middle";
            this.ucEasyLabelVia.Appearance = appearance1;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyLabelVia, 3);
            this.ucEasyLabelVia.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabelVia.Location = new System.Drawing.Point(3, 81);
            this.ucEasyLabelVia.Name = "ucEasyLabelVia";
            this.ucEasyLabelVia.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabelVia.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabelVia.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabelVia.Size = new System.Drawing.Size(488, 25);
            this.ucEasyLabelVia.TabIndex = 7;
            this.ucEasyLabelVia.Text = "Via di Somministrazione:";
            this.ucEasyLabelVia.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "ucEasyPopUpTerapiaRapida";
            this.Size = new System.Drawing.Size(500, 400);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTextBoxPosologia)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyDateTimeEditorDataOra)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTextBoxPrescrizione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uceViaSomministrazione)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyLabel ucEasyLabelPrescrizione;
        private ucEasyDateTimeEditor ucEasyDateTimeEditorDataOra;
        private ucEasyLabel ucEasyLabelDataOra;
        private ucEasyButton ucEasyButtonConferma;
        private ucEasyButton ucEasyButtonCancel;
        private ucEasyTextBox ucEasyTextBoxPrescrizione;
        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTextBox ucEasyTextBoxPosologia;
        private ucEasyLabel ucEasyLabelPosologia;
        private ucEasyComboEditor uceViaSomministrazione;
        private ucEasyLabel ucEasyLabelVia;
    }
}
