namespace UnicodeSrl.ScciCore
{
    partial class ucMenu
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucMenu));
            Infragistics.Win.UltraWinToolTip.UltraToolTipInfo ultraToolTipInfo1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipInfo("Clicca qua per selezionare un nuovo ruolo", Infragistics.Win.ToolTipImage.Default, "Cambia Ruolo", Infragistics.Win.DefaultableBoolean.Default);
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinToolTip.UltraToolTipInfo ultraToolTipInfo2 = new Infragistics.Win.UltraWinToolTip.UltraToolTipInfo("Ricerca Cartella Paziente per Nosologico, Cognome, Nome, Data di Nascita", Infragistics.Win.ToolTipImage.Default, "Ricerca Paziente", Infragistics.Win.DefaultableBoolean.Default);
            Infragistics.Win.UltraWinToolbars.PopupMenuTool popupMenuTool1 = new Infragistics.Win.UltraWinToolbars.PopupMenuTool("MenuRight");
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this._ucBottom_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._ucBottom_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._ucBottom_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._ucBottom_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.scciTableLayoutPanelMenu = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTableLayoutPanelPulsanti = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubCambiaRuolo = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubCambiaUtente = new UnicodeSrl.ScciCore.ucEasyButton();
            this.scciTableLayoutPanelButtons = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.picLogoBig = new System.Windows.Forms.PictureBox();
            this.picLogoS = new System.Windows.Forms.PictureBox();
            this.elblNEWS = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucNewsMenu = new UnicodeSrl.ScciCore.ucNews();
            this.ucEasyTextBoxNosologico = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ucEasyFlowLayoutPanelButtons = new UnicodeSrl.ScciCore.ucEasyFlowLayoutPanel(this.components);
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.scciTableLayoutPanelMenu.SuspendLayout();
            this.ucEasyTableLayoutPanelPulsanti.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picLogoBig)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.picLogoS)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTextBoxNosologico)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.SuspendLayout();
                                                appearance1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(206)))), ((int)(((byte)(222)))), ((int)(((byte)(240)))));
            this.UltraGroupBox.Appearance = appearance1;
            this.UltraGroupBox.Controls.Add(this.scciTableLayoutPanelMenu);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(600, 450);
            this.UltraGroupBox.TabIndex = 0;
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this._ucBottom_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ucBottom_Toolbars_Dock_Area_Top.BackColor = System.Drawing.SystemColors.Control;
            this._ucBottom_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._ucBottom_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ucBottom_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._ucBottom_Toolbars_Dock_Area_Top.Name = "_ucBottom_Toolbars_Dock_Area_Top";
            this._ucBottom_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(600, 0);
            this._ucBottom_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this._ucBottom_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ucBottom_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.SystemColors.Control;
            this._ucBottom_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._ucBottom_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ucBottom_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 450);
            this._ucBottom_Toolbars_Dock_Area_Bottom.Name = "_ucBottom_Toolbars_Dock_Area_Bottom";
            this._ucBottom_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(600, 0);
            this._ucBottom_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this._ucBottom_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ucBottom_Toolbars_Dock_Area_Left.BackColor = System.Drawing.SystemColors.Control;
            this._ucBottom_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._ucBottom_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ucBottom_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._ucBottom_Toolbars_Dock_Area_Left.Name = "_ucBottom_Toolbars_Dock_Area_Left";
            this._ucBottom_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 450);
            this._ucBottom_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._ucBottom_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ucBottom_Toolbars_Dock_Area_Right.BackColor = System.Drawing.SystemColors.Control;
            this._ucBottom_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._ucBottom_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ucBottom_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(600, 0);
            this._ucBottom_Toolbars_Dock_Area_Right.Name = "_ucBottom_Toolbars_Dock_Area_Right";
            this._ucBottom_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 450);
            this._ucBottom_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                this.scciTableLayoutPanelMenu.BackColor = System.Drawing.Color.Transparent;
            this.scciTableLayoutPanelMenu.ColumnCount = 7;
            this.scciTableLayoutPanelMenu.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.scciTableLayoutPanelMenu.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.scciTableLayoutPanelMenu.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.scciTableLayoutPanelMenu.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.scciTableLayoutPanelMenu.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.scciTableLayoutPanelMenu.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.scciTableLayoutPanelMenu.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.scciTableLayoutPanelMenu.Controls.Add(this.ucEasyTableLayoutPanelPulsanti, 1, 0);
            this.scciTableLayoutPanelMenu.Controls.Add(this.scciTableLayoutPanelButtons, 6, 0);
            this.scciTableLayoutPanelMenu.Controls.Add(this.picLogoBig, 1, 1);
            this.scciTableLayoutPanelMenu.Controls.Add(this.picLogoS, 1, 2);
            this.scciTableLayoutPanelMenu.Controls.Add(this.elblNEWS, 1, 3);
            this.scciTableLayoutPanelMenu.Controls.Add(this.ucNewsMenu, 1, 4);
            this.scciTableLayoutPanelMenu.Controls.Add(this.ucEasyTextBoxNosologico, 4, 5);
            this.scciTableLayoutPanelMenu.Controls.Add(this.ucEasyFlowLayoutPanelButtons, 3, 0);
            this.scciTableLayoutPanelMenu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.scciTableLayoutPanelMenu.Location = new System.Drawing.Point(3, 3);
            this.scciTableLayoutPanelMenu.Name = "scciTableLayoutPanelMenu";
            this.scciTableLayoutPanelMenu.RowCount = 8;
            this.scciTableLayoutPanelMenu.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.scciTableLayoutPanelMenu.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.scciTableLayoutPanelMenu.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.scciTableLayoutPanelMenu.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.scciTableLayoutPanelMenu.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.scciTableLayoutPanelMenu.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.scciTableLayoutPanelMenu.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.scciTableLayoutPanelMenu.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.scciTableLayoutPanelMenu.Size = new System.Drawing.Size(594, 444);
            this.scciTableLayoutPanelMenu.TabIndex = 0;
                                                this.ucEasyTableLayoutPanelPulsanti.ColumnCount = 4;
            this.ucEasyTableLayoutPanelPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.ucEasyTableLayoutPanelPulsanti.Controls.Add(this.ubCambiaRuolo, 0, 1);
            this.ucEasyTableLayoutPanelPulsanti.Controls.Add(this.ubCambiaUtente, 2, 1);
            this.ucEasyTableLayoutPanelPulsanti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelPulsanti.Location = new System.Drawing.Point(14, 3);
            this.ucEasyTableLayoutPanelPulsanti.Name = "ucEasyTableLayoutPanelPulsanti";
            this.ucEasyTableLayoutPanelPulsanti.RowCount = 3;
            this.ucEasyTableLayoutPanelPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.ucEasyTableLayoutPanelPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelPulsanti.Size = new System.Drawing.Size(231, 56);
            this.ucEasyTableLayoutPanelPulsanti.TabIndex = 1;
                                                appearance2.FontData.SizeInPoints = 22.50746F;
            appearance2.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance2.ImageBackground")));
            appearance2.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance2.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance2.TextHAlignAsString = "Center";
            appearance2.TextVAlignAsString = "Middle";
            this.ubCambiaRuolo.Appearance = appearance2;
            this.ubCambiaRuolo.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubCambiaRuolo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCambiaRuolo.Location = new System.Drawing.Point(3, 8);
            this.ubCambiaRuolo.Name = "ubCambiaRuolo";
            this.ubCambiaRuolo.PercImageFill = 0.75F;
            this.ubCambiaRuolo.ShortcutColor = System.Drawing.Color.Black;
            this.ubCambiaRuolo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubCambiaRuolo.ShortcutKey = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.R)));
            this.ubCambiaRuolo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubCambiaRuolo.Size = new System.Drawing.Size(28, 38);
            this.ubCambiaRuolo.TabIndex = 0;
            this.ubCambiaRuolo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            ultraToolTipInfo1.ToolTipText = "Clicca qua per selezionare un nuovo ruolo";
            ultraToolTipInfo1.ToolTipTitle = "Cambia Ruolo";
            this.ultraToolTipManager1.SetUltraToolTip(this.ubCambiaRuolo, ultraToolTipInfo1);
            this.ubCambiaRuolo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubCambiaRuolo.Click += new System.EventHandler(this.ubCambiaRuolo_Click);
                                                appearance3.FontData.SizeInPoints = 22.50746F;
            appearance3.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance3.ImageBackground")));
            appearance3.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance3.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance3.TextHAlignAsString = "Center";
            appearance3.TextVAlignAsString = "Middle";
            this.ubCambiaUtente.Appearance = appearance3;
            this.ubCambiaUtente.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubCambiaUtente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCambiaUtente.Location = new System.Drawing.Point(48, 8);
            this.ubCambiaUtente.Name = "ubCambiaUtente";
            this.ubCambiaUtente.PercImageFill = 0.7F;
            this.ubCambiaUtente.ShortcutColor = System.Drawing.Color.Black;
            this.ubCambiaUtente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubCambiaUtente.ShortcutKey = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.U)));
            this.ubCambiaUtente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubCambiaUtente.Size = new System.Drawing.Size(28, 38);
            this.ubCambiaUtente.TabIndex = 1;
            this.ubCambiaUtente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubCambiaUtente.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubCambiaUtente.Click += new System.EventHandler(this.ubCambiaUtente_Click);
                                                this.scciTableLayoutPanelButtons.ColumnCount = 3;
            this.scciTableLayoutPanelButtons.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.scciTableLayoutPanelButtons.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.scciTableLayoutPanelButtons.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.scciTableLayoutPanelButtons.Dock = System.Windows.Forms.DockStyle.Fill;
            this.scciTableLayoutPanelButtons.Location = new System.Drawing.Point(3, 65);
            this.scciTableLayoutPanelButtons.Name = "scciTableLayoutPanelButtons";
            this.scciTableLayoutPanelButtons.RowCount = 3;
            this.scciTableLayoutPanelButtons.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.scciTableLayoutPanelButtons.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.scciTableLayoutPanelButtons.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.scciTableLayoutPanelButtons.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.scciTableLayoutPanelButtons.Size = new System.Drawing.Size(5, 149);
            this.scciTableLayoutPanelButtons.TabIndex = 2;
                                                this.picLogoBig.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picLogoBig.Location = new System.Drawing.Point(14, 65);
            this.picLogoBig.Name = "picLogoBig";
            this.picLogoBig.Size = new System.Drawing.Size(231, 149);
            this.picLogoBig.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLogoBig.TabIndex = 6;
            this.picLogoBig.TabStop = false;
                                                this.picLogoS.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picLogoS.Location = new System.Drawing.Point(14, 220);
            this.picLogoS.Name = "picLogoS";
            this.picLogoS.Size = new System.Drawing.Size(231, 25);
            this.picLogoS.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLogoS.TabIndex = 7;
            this.picLogoS.TabStop = false;
                                                appearance4.FontData.SizeInPoints = 22.50746F;
            appearance4.TextVAlignAsString = "Middle";
            this.elblNEWS.Appearance = appearance4;
            this.elblNEWS.Dock = System.Windows.Forms.DockStyle.Fill;
            this.elblNEWS.Location = new System.Drawing.Point(12, 249);
            this.elblNEWS.Margin = new System.Windows.Forms.Padding(1);
            this.elblNEWS.Name = "elblNEWS";
            this.elblNEWS.ShortcutColor = System.Drawing.Color.Black;
            this.elblNEWS.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.elblNEWS.ShortcutKey = System.Windows.Forms.Keys.None;
            this.elblNEWS.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.elblNEWS.Size = new System.Drawing.Size(235, 20);
            this.elblNEWS.TabIndex = 8;
            this.elblNEWS.Text = "News";
            this.elblNEWS.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucNewsMenu.BackColor = System.Drawing.Color.Transparent;
            this.ucNewsMenu.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucNewsMenu.Font = new System.Drawing.Font("Calibri", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ucNewsMenu.Location = new System.Drawing.Point(12, 271);
            this.ucNewsMenu.Margin = new System.Windows.Forms.Padding(1);
            this.ucNewsMenu.Name = "ucNewsMenu";
            this.scciTableLayoutPanelMenu.SetRowSpan(this.ucNewsMenu, 3);
            this.ucNewsMenu.Size = new System.Drawing.Size(235, 161);
            this.ucNewsMenu.TabIndex = 9;
            this.ucNewsMenu.VisualizzaRTF = false;
                                                appearance5.FontData.SizeInPoints = 27.70149F;
            appearance5.TextHAlignAsString = "Center";
            this.ucEasyTextBoxNosologico.Appearance = appearance5;
            this.ucEasyTextBoxNosologico.AutoSize = false;
            this.ucEasyTextBoxNosologico.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.ucEasyTextBoxNosologico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTextBoxNosologico.Location = new System.Drawing.Point(315, 384);
            this.ucEasyTextBoxNosologico.Name = "ucEasyTextBoxNosologico";
            this.ucEasyTextBoxNosologico.Size = new System.Drawing.Size(261, 20);
            this.ucEasyTextBoxNosologico.TabIndex = 0;
            this.ucEasyTextBoxNosologico.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            ultraToolTipInfo2.ToolTipText = "Ricerca Cartella Paziente per Nosologico, Cognome, Nome, Data di Nascita";
            ultraToolTipInfo2.ToolTipTitle = "Ricerca Paziente";
            this.ultraToolTipManager1.SetUltraToolTip(this.ucEasyTextBoxNosologico, ultraToolTipInfo2);
            this.ucEasyTextBoxNosologico.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTextBoxNosologico.KeyDown += new System.Windows.Forms.KeyEventHandler(this.ucEasyTextBoxNosologico_KeyDown);
                                                this.ucEasyFlowLayoutPanelButtons.AutoScroll = true;
            this.scciTableLayoutPanelMenu.SetColumnSpan(this.ucEasyFlowLayoutPanelButtons, 4);
            this.ucEasyFlowLayoutPanelButtons.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyFlowLayoutPanelButtons.Location = new System.Drawing.Point(262, 3);
            this.ucEasyFlowLayoutPanelButtons.Name = "ucEasyFlowLayoutPanelButtons";
            this.scciTableLayoutPanelMenu.SetRowSpan(this.ucEasyFlowLayoutPanelButtons, 5);
            this.ucEasyFlowLayoutPanelButtons.Size = new System.Drawing.Size(329, 375);
            this.ucEasyFlowLayoutPanelButtons.TabIndex = 11;
            this.ucEasyFlowLayoutPanelButtons.MouseClick += new System.Windows.Forms.MouseEventHandler(this.ucEasyFlowLayoutPanelButtons_MouseClick);
            this.ucEasyFlowLayoutPanelButtons.MouseEnter += new System.EventHandler(this.ucEasyFlowLayoutPanelButtons_MouseEnter);
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.ShowFullMenusDelay = 500;
            popupMenuTool1.SharedPropsInternal.Caption = "MenuRight";
            this.UltraToolbarsManager.Tools.AddRange(new Infragistics.Win.UltraWinToolbars.ToolBase[] {
            popupMenuTool1});
            this.UltraToolbarsManager.ToolClick += new Infragistics.Win.UltraWinToolbars.ToolClickEventHandler(this.UltraToolbarsManager_ToolClick);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.UltraGroupBox);
            this.Controls.Add(this._ucBottom_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._ucBottom_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._ucBottom_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._ucBottom_Toolbars_Dock_Area_Top);
            this.Name = "ucMenu";
            this.Size = new System.Drawing.Size(600, 450);
            this.Tag = "0";
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.scciTableLayoutPanelMenu.ResumeLayout(false);
            this.ucEasyTableLayoutPanelPulsanti.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picLogoBig)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.picLogoS)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTextBoxNosologico)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private ucEasyTableLayoutPanel scciTableLayoutPanelMenu;
        private ucEasyButton ubCambiaRuolo;
        private ucEasyButton ubCambiaUtente;
        private ucEasyTableLayoutPanel scciTableLayoutPanelButtons;
        private System.Windows.Forms.PictureBox picLogoBig;
        private System.Windows.Forms.PictureBox picLogoS;
        private ucEasyLabel elblNEWS;
        private ucNews ucNewsMenu;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelPulsanti;
        private ucEasyTextBox ucEasyTextBoxNosologico;
        private ucEasyFlowLayoutPanel ucEasyFlowLayoutPanelButtons;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ucBottom_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ucBottom_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ucBottom_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ucBottom_Toolbars_Dock_Area_Top;
    }
}
