namespace UnicodeSrl.ScciCore
{
    partial class ucOrderEntryMonitorTrasversale
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucOrderEntryMonitorTrasversale));
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem3 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem4 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem5 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem6 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem7 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem8 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem9 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedRight, new System.Guid("bc17ea56-03df-489c-b09c-f2a1891b71c0"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("96fc7f95-406b-4dcb-9346-7948ddc6fd82"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("bc17ea56-03df-489c-b09c-f2a1891b71c0"), -1);
            this.pnlFiltro = new System.Windows.Forms.Panel();
            this.ucEasyTableLayoutPanelFiltri = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTreeViewUO = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ubApplicaFiltroPanel = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyGridFiltroTipo = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubApplicaFiltro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyTableLayoutPanelRicerca = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblVisualizzaPaziente = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.txtNosologico = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.chkVisualizzaPaziente = new UnicodeSrl.ScciCore.ucEasyCheckEditor();
            this.lblNosologico = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.txtNome = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblNome = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyTableLayoutPanelFiltroData = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.udteFiltroDA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroDa = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.drFiltro = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.udteFiltroA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroA = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.txtCognome = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.lblCognome = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ultraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucOrderEntryTrasversaleUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucOrderEntryTrasversaleUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucOrderEntryTrasversaleAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.pnlFiltro.SuspendLayout();
            this.ucEasyTableLayoutPanelFiltri.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewUO)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroTipo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            this.ucEasyTableLayoutPanelRicerca.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtNosologico)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chkVisualizzaPaziente)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNome)).BeginInit();
            this.ucEasyTableLayoutPanelFiltroData.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtCognome)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).BeginInit();
            this._ucOrderEntryTrasversaleAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            this.SuspendLayout();
                                                this.pnlFiltro.Controls.Add(this.ucEasyTableLayoutPanelFiltri);
            this.pnlFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlFiltro.Location = new System.Drawing.Point(0, 18);
            this.pnlFiltro.Name = "pnlFiltro";
            this.pnlFiltro.Size = new System.Drawing.Size(268, 746);
            this.pnlFiltro.TabIndex = 6;
                                                this.ucEasyTableLayoutPanelFiltri.ColumnCount = 5;
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyTreeViewUO, 1, 1);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ubApplicaFiltroPanel, 3, 3);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyGridFiltroTipo, 1, 0);
            this.ucEasyTableLayoutPanelFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltri.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelFiltri.Name = "ucEasyTableLayoutPanelFiltri";
            this.ucEasyTableLayoutPanelFiltri.RowCount = 5;
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 41F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 41F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 8F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.Size = new System.Drawing.Size(268, 746);
            this.ucEasyTableLayoutPanelFiltri.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 13.97015F;
            this.ucEasyTreeViewUO.Appearance = appearance1;
            this.ucEasyTreeViewUO.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTableLayoutPanelFiltri.SetColumnSpan(this.ucEasyTreeViewUO, 3);
            this.ucEasyTreeViewUO.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewUO.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewUO.HideSelection = false;
            this.ucEasyTreeViewUO.Location = new System.Drawing.Point(5, 308);
            this.ucEasyTreeViewUO.Name = "ucEasyTreeViewUO";
            appearance2.BackColor = System.Drawing.Color.LightYellow;
            appearance2.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance2;
            _override1.SelectedNodeAppearance = appearance2;
            this.ucEasyTreeViewUO.Override = _override1;
            this.ucEasyTreeViewUO.Size = new System.Drawing.Size(255, 299);
            this.ucEasyTreeViewUO.TabIndex = 22;
            this.ucEasyTreeViewUO.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeViewUO.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance3.FontData.SizeInPoints = 20.1791F;
            appearance3.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance3.ImageBackground")));
            appearance3.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance3.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance3.TextHAlignAsString = "Center";
            appearance3.TextVAlignAsString = "Middle";
            this.ubApplicaFiltroPanel.Appearance = appearance3;
            this.ubApplicaFiltroPanel.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubApplicaFiltroPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltroPanel.Location = new System.Drawing.Point(138, 672);
            this.ubApplicaFiltroPanel.Name = "ubApplicaFiltroPanel";
            this.ubApplicaFiltroPanel.PercImageFill = 0.75F;
            this.ubApplicaFiltroPanel.ShortcutColor = System.Drawing.Color.Black;
            this.ubApplicaFiltroPanel.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltroPanel.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltroPanel.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltroPanel.Size = new System.Drawing.Size(122, 61);
            this.ubApplicaFiltroPanel.TabIndex = 21;
            this.ubApplicaFiltroPanel.Text = "Applica filtro";
            this.ubApplicaFiltroPanel.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltroPanel.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltroPanel.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ucEasyGridFiltroTipo.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroTipo.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanelFiltri.SetColumnSpan(this.ucEasyGridFiltroTipo, 3);
            this.ucEasyGridFiltroTipo.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroTipo.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance4.BackColor = System.Drawing.SystemColors.Window;
            appearance4.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            appearance4.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Centered;
            this.ucEasyGridFiltroTipo.DisplayLayout.Appearance = appearance4;
            this.ucEasyGridFiltroTipo.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroTipo.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance5.FontData.BoldAsString = "True";
            appearance5.FontData.SizeInPoints = 20.1791F;
            this.ucEasyGridFiltroTipo.DisplayLayout.CaptionAppearance = appearance5;
            this.ucEasyGridFiltroTipo.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance6.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance6.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance6.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Appearance = appearance6;
            appearance7.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.BandLabelAppearance = appearance7;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance8.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance8.BackColor2 = System.Drawing.SystemColors.Control;
            appearance8.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance8.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.PromptAppearance = appearance8;
            this.ucEasyGridFiltroTipo.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroTipo.DisplayLayout.MaxRowScrollRegions = 1;
            appearance9.BackColor = System.Drawing.SystemColors.Window;
            appearance9.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ActiveCellAppearance = appearance9;
            appearance10.BackColor = System.Drawing.SystemColors.Highlight;
            appearance10.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ActiveRowAppearance = appearance10;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CardAreaAppearance = appearance11;
            appearance12.BorderColor = System.Drawing.Color.Silver;
            appearance12.FontData.SizeInPoints = 13.97015F;
            appearance12.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellAppearance = appearance12;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance13.FontData.SizeInPoints = 20.1791F;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.FilterRowAppearance = appearance13;
            appearance14.BackColor = System.Drawing.SystemColors.Control;
            appearance14.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance14.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance14.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance14.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.GroupByRowAppearance = appearance14;
            appearance15.FontData.BoldAsString = "True";
            appearance15.FontData.SizeInPoints = 13.97015F;
            appearance15.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderAppearance = appearance15;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance16.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance16.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowAlternateAppearance = appearance16;
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowAppearance = appearance17;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance18.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.TemplateAddRowAppearance = appearance18;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroTipo.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroTipo.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroTipo.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroTipo.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridFiltroTipo.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridFiltroTipo.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroTipo.Location = new System.Drawing.Point(5, 3);
            this.ucEasyGridFiltroTipo.Name = "ucEasyGridFiltroTipo";
            this.ucEasyGridFiltroTipo.ShowFilterRow = false;
            this.ucEasyGridFiltroTipo.ShowGroupByBox = false;
            this.ucEasyGridFiltroTipo.Size = new System.Drawing.Size(255, 299);
            this.ucEasyGridFiltroTipo.TabIndex = 20;
            this.ucEasyGridFiltroTipo.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltroTipo_InitializeLayout);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(841, 764);
            this.ultraGroupBox.TabIndex = 0;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 4;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubApplicaFiltro, 2, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelRicerca, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGrid, 1, 2);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 4;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 18F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(835, 758);
            this.ucEasyTableLayoutPanel.TabIndex = 2;
                                                appearance19.FontData.SizeInPoints = 20.1791F;
            appearance19.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance19.ImageBackground")));
            appearance19.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance19.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance19.TextHAlignAsString = "Center";
            appearance19.TextVAlignAsString = "Middle";
            this.ubApplicaFiltro.Appearance = appearance19;
            this.ubApplicaFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubApplicaFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltro.Location = new System.Drawing.Point(679, 10);
            this.ubApplicaFiltro.Name = "ubApplicaFiltro";
            this.ubApplicaFiltro.PercImageFill = 0.75F;
            this.ubApplicaFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.ubApplicaFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltro.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltro.Size = new System.Drawing.Size(144, 130);
            this.ubApplicaFiltro.TabIndex = 0;
            this.ubApplicaFiltro.Text = "Applica filtro";
            this.ubApplicaFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltro.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ucEasyTableLayoutPanelRicerca.ColumnCount = 4;
            this.ucEasyTableLayoutPanelRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.lblVisualizzaPaziente, 3, 1);
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.txtNosologico, 1, 1);
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.chkVisualizzaPaziente, 2, 1);
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.lblNosologico, 0, 1);
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.txtNome, 3, 0);
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.lblNome, 2, 0);
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.ucEasyTableLayoutPanelFiltroData, 0, 2);
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.txtCognome, 1, 0);
            this.ucEasyTableLayoutPanelRicerca.Controls.Add(this.lblCognome, 0, 0);
            this.ucEasyTableLayoutPanelRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelRicerca.Location = new System.Drawing.Point(11, 10);
            this.ucEasyTableLayoutPanelRicerca.Name = "ucEasyTableLayoutPanelRicerca";
            this.ucEasyTableLayoutPanelRicerca.RowCount = 3;
            this.ucEasyTableLayoutPanelRicerca.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelRicerca.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelRicerca.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelRicerca.Size = new System.Drawing.Size(662, 130);
            this.ucEasyTableLayoutPanelRicerca.TabIndex = 12;
                                                appearance20.FontData.SizeInPoints = 20.1791F;
            appearance20.TextHAlignAsString = "Left";
            appearance20.TextVAlignAsString = "Middle";
            this.lblVisualizzaPaziente.Appearance = appearance20;
            this.lblVisualizzaPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblVisualizzaPaziente.Location = new System.Drawing.Point(399, 42);
            this.lblVisualizzaPaziente.Name = "lblVisualizzaPaziente";
            this.lblVisualizzaPaziente.ShortcutColor = System.Drawing.Color.Black;
            this.lblVisualizzaPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblVisualizzaPaziente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblVisualizzaPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblVisualizzaPaziente.Size = new System.Drawing.Size(260, 33);
            this.lblVisualizzaPaziente.TabIndex = 19;
            this.lblVisualizzaPaziente.Text = "Visualizza per Paziente";
            this.lblVisualizzaPaziente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.lblVisualizzaPaziente.Visible = false;
                                                appearance21.FontData.SizeInPoints = 20.1791F;
            this.txtNosologico.Appearance = appearance21;
            this.txtNosologico.AutoSize = false;
            this.txtNosologico.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtNosologico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtNosologico.Location = new System.Drawing.Point(69, 42);
            this.txtNosologico.Name = "txtNosologico";
            this.txtNosologico.Scrollbars = System.Windows.Forms.ScrollBars.Both;
            this.txtNosologico.Size = new System.Drawing.Size(258, 33);
            this.txtNosologico.TabIndex = 2;
            this.txtNosologico.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.txtNosologico.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                this.chkVisualizzaPaziente.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            appearance22.BackColor = System.Drawing.Color.Transparent;
            appearance22.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance22.ImageBackground")));
            appearance22.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance22.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.chkVisualizzaPaziente.Appearance = appearance22;
            this.chkVisualizzaPaziente.BackColor = System.Drawing.Color.Transparent;
            this.chkVisualizzaPaziente.BackColorInternal = System.Drawing.Color.Transparent;
            this.chkVisualizzaPaziente.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Borderless;
            appearance23.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance23.ImageBackground")));
            appearance23.ImageBackgroundStyle = Infragistics.Win.ImageBackgroundStyle.Stretched;
            appearance23.ThemedElementAlpha = Infragistics.Win.Alpha.Transparent;
            this.chkVisualizzaPaziente.CheckedAppearance = appearance23;
            this.chkVisualizzaPaziente.Location = new System.Drawing.Point(333, 39);
            this.chkVisualizzaPaziente.Margin = new System.Windows.Forms.Padding(0);
            this.chkVisualizzaPaziente.Name = "chkVisualizzaPaziente";
            this.chkVisualizzaPaziente.Size = new System.Drawing.Size(60, 39);
            this.chkVisualizzaPaziente.Style = Infragistics.Win.EditCheckStyle.Button;
            this.chkVisualizzaPaziente.TabIndex = 3;
            this.chkVisualizzaPaziente.Visible = false;
            this.chkVisualizzaPaziente.CheckedChanged += new System.EventHandler(this.chkVisualizzaPaziente_CheckedChanged);
                                                appearance24.FontData.SizeInPoints = 13.97015F;
            appearance24.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance24.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance24.TextVAlignAsString = "Middle";
            this.lblNosologico.Appearance = appearance24;
            this.lblNosologico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNosologico.Location = new System.Drawing.Point(3, 42);
            this.lblNosologico.Name = "lblNosologico";
            this.lblNosologico.ShortcutColor = System.Drawing.Color.Black;
            this.lblNosologico.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblNosologico.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblNosologico.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblNosologico.Size = new System.Drawing.Size(60, 33);
            this.lblNosologico.TabIndex = 12;
            this.lblNosologico.Text = "Nosologico:";
            this.lblNosologico.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance25.FontData.SizeInPoints = 20.1791F;
            this.txtNome.Appearance = appearance25;
            this.txtNome.AutoSize = false;
            this.txtNome.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtNome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtNome.Location = new System.Drawing.Point(399, 3);
            this.txtNome.Name = "txtNome";
            this.txtNome.Scrollbars = System.Windows.Forms.ScrollBars.Both;
            this.txtNome.Size = new System.Drawing.Size(260, 33);
            this.txtNome.TabIndex = 1;
            this.txtNome.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.txtNome.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.txtNome.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtRicerca_KeyDown);
                                                appearance26.FontData.SizeInPoints = 13.97015F;
            appearance26.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance26.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance26.TextVAlignAsString = "Middle";
            this.lblNome.Appearance = appearance26;
            this.lblNome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNome.Location = new System.Drawing.Point(333, 3);
            this.lblNome.Name = "lblNome";
            this.lblNome.ShortcutColor = System.Drawing.Color.Black;
            this.lblNome.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblNome.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblNome.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblNome.Size = new System.Drawing.Size(60, 33);
            this.lblNome.TabIndex = 7;
            this.lblNome.Text = "Nome:";
            this.lblNome.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                this.ucEasyTableLayoutPanelFiltroData.ColumnCount = 5;
            this.ucEasyTableLayoutPanelRicerca.SetColumnSpan(this.ucEasyTableLayoutPanelFiltroData, 4);
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 28F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 7F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 28F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 27F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.udteFiltroDA, 1, 1);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.lblFiltroDa, 0, 1);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.drFiltro, 4, 1);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.udteFiltroA, 3, 1);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.lblFiltroA, 2, 1);
            this.ucEasyTableLayoutPanelFiltroData.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltroData.Location = new System.Drawing.Point(0, 81);
            this.ucEasyTableLayoutPanelFiltroData.Margin = new System.Windows.Forms.Padding(0, 3, 0, 3);
            this.ucEasyTableLayoutPanelFiltroData.Name = "ucEasyTableLayoutPanelFiltroData";
            this.ucEasyTableLayoutPanelFiltroData.RowCount = 3;
            this.ucEasyTableLayoutPanelFiltroData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1.111111F));
            this.ucEasyTableLayoutPanelFiltroData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 97.77777F));
            this.ucEasyTableLayoutPanelFiltroData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1.111111F));
            this.ucEasyTableLayoutPanelFiltroData.Size = new System.Drawing.Size(662, 46);
            this.ucEasyTableLayoutPanelFiltroData.TabIndex = 11;
                                                appearance27.FontData.SizeInPoints = 20.1791F;
            this.udteFiltroDA.Appearance = appearance27;
            this.udteFiltroDA.AutoSize = false;
            this.udteFiltroDA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroDA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroDA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance28.FontData.SizeInPoints = 20.1791F;
            this.udteFiltroDA.DropDownAppearance = appearance28;
            this.udteFiltroDA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroDA.Location = new System.Drawing.Point(69, 3);
            this.udteFiltroDA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroDA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroDA.Name = "udteFiltroDA";
            this.udteFiltroDA.Size = new System.Drawing.Size(179, 38);
            this.udteFiltroDA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroDA.TabIndex = 0;
            this.udteFiltroDA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.udteFiltroDA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance29.FontData.SizeInPoints = 13.97015F;
            appearance29.TextVAlignAsString = "Middle";
            this.lblFiltroDa.Appearance = appearance29;
            this.lblFiltroDa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDa.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroDa.Name = "lblFiltroDa";
            this.lblFiltroDa.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroDa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDa.Size = new System.Drawing.Size(60, 38);
            this.lblFiltroDa.TabIndex = 2;
            this.lblFiltroDa.Text = "DA:";
            this.lblFiltroDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance30.FontData.SizeInPoints = 20.1791F;
            this.drFiltro.Appearance = appearance30;
            this.drFiltro.AutoSize = false;
            this.drFiltro.DataEpisodio = new System.DateTime(((long)(0)));
            this.drFiltro.DateFuture = false;
            this.drFiltro.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.drFiltro.DisponibilitaAgende = false;
            this.drFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.drFiltro.Domani = false;
            this.drFiltro.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem1.DisplayText = " ";
            valueListItem2.DataValue = "OGGI";
            valueListItem2.DisplayText = "Oggi";
            valueListItem3.DataValue = "24H";
            valueListItem3.DisplayText = "Ultime 24h";
            valueListItem4.DataValue = "48H";
            valueListItem4.DisplayText = "Ultime 48h";
            valueListItem5.DataValue = "7G";
            valueListItem5.DisplayText = "Ultimi 7gg";
            valueListItem6.DataValue = "30G";
            valueListItem6.DisplayText = "Ultimi 30gg";
            valueListItem7.DataValue = "60G";
            valueListItem7.DisplayText = "Ultimi 60gg";
            valueListItem8.DataValue = "90G";
            valueListItem8.DisplayText = "Ultimi 90gg";
            valueListItem9.DataValue = "6M";
            valueListItem9.DisplayText = "Ultimi 6 mesi";
            this.drFiltro.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2,
            valueListItem3,
            valueListItem4,
            valueListItem5,
            valueListItem6,
            valueListItem7,
            valueListItem8,
            valueListItem9});
            this.drFiltro.Location = new System.Drawing.Point(485, 3);
            this.drFiltro.Name = "drFiltro";
            this.drFiltro.Oggi = true;
            this.drFiltro.PassatoRemoto = false;
            this.drFiltro.Size = new System.Drawing.Size(174, 38);
            this.drFiltro.TabIndex = 2;
            this.drFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.drFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.drFiltro.ValueChanged += new System.EventHandler(this.drFiltro_ValueChanged);
                                                appearance31.FontData.SizeInPoints = 20.1791F;
            this.udteFiltroA.Appearance = appearance31;
            this.udteFiltroA.AutoSize = false;
            this.udteFiltroA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance32.FontData.SizeInPoints = 20.1791F;
            this.udteFiltroA.DropDownAppearance = appearance32;
            this.udteFiltroA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroA.Location = new System.Drawing.Point(300, 3);
            this.udteFiltroA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroA.Name = "udteFiltroA";
            this.udteFiltroA.Size = new System.Drawing.Size(179, 38);
            this.udteFiltroA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroA.TabIndex = 1;
            this.udteFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.udteFiltroA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance33.FontData.SizeInPoints = 13.97015F;
            appearance33.TextVAlignAsString = "Middle";
            this.lblFiltroA.Appearance = appearance33;
            this.lblFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroA.Location = new System.Drawing.Point(254, 3);
            this.lblFiltroA.Name = "lblFiltroA";
            this.lblFiltroA.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroA.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroA.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroA.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroA.Size = new System.Drawing.Size(40, 38);
            this.lblFiltroA.TabIndex = 2;
            this.lblFiltroA.Text = "A:";
            this.lblFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance34.FontData.SizeInPoints = 20.1791F;
            this.txtCognome.Appearance = appearance34;
            this.txtCognome.AutoSize = false;
            this.txtCognome.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.txtCognome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCognome.Location = new System.Drawing.Point(69, 3);
            this.txtCognome.Name = "txtCognome";
            this.txtCognome.Scrollbars = System.Windows.Forms.ScrollBars.Both;
            this.txtCognome.Size = new System.Drawing.Size(258, 33);
            this.txtCognome.TabIndex = 0;
            this.txtCognome.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.txtCognome.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.txtCognome.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtRicerca_KeyDown);
                                                appearance35.FontData.SizeInPoints = 13.97015F;
            appearance35.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance35.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance35.TextVAlignAsString = "Middle";
            this.lblCognome.Appearance = appearance35;
            this.lblCognome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCognome.Location = new System.Drawing.Point(3, 3);
            this.lblCognome.Name = "lblCognome";
            this.lblCognome.ShortcutColor = System.Drawing.Color.Black;
            this.lblCognome.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblCognome.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblCognome.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblCognome.Size = new System.Drawing.Size(60, 33);
            this.lblCognome.TabIndex = 5;
            this.lblCognome.Text = "Cognome:";
            this.lblCognome.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyGrid, 2);
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance36.BackColor = System.Drawing.SystemColors.Window;
            appearance36.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            appearance36.FontData.SizeInPoints = 20.43361F;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance36;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance37.FontData.BoldAsString = "True";
            appearance37.FontData.SizeInPoints = 20.1791F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance37;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance38.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance38.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance38.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance38.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance38;
            appearance39.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance39;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance40.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance40.BackColor2 = System.Drawing.SystemColors.Control;
            appearance40.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance40.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance40;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance41.BackColor = System.Drawing.SystemColors.Window;
            appearance41.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance41;
            appearance42.BackColor = System.Drawing.SystemColors.Highlight;
            appearance42.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance42;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance43.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance43;
            appearance44.BorderColor = System.Drawing.Color.Silver;
            appearance44.FontData.SizeInPoints = 13.97015F;
            appearance44.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance44;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance45.FontData.SizeInPoints = 20.1791F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance45;
            appearance46.BackColor = System.Drawing.SystemColors.Control;
            appearance46.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance46.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance46.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance46.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance46;
            appearance47.FontData.BoldAsString = "True";
            appearance47.FontData.SizeInPoints = 13.97015F;
            appearance47.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance47;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance48.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance48.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance48;
            appearance49.BackColor = System.Drawing.SystemColors.Window;
            appearance49.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance49;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance50.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance50;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(11, 146);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(812, 600);
            this.ucEasyGrid.TabIndex = 1;
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.AfterRowActivate += new System.EventHandler(this.ucEasyGrid_AfterRowActivate);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
                                                this.ultraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.ultraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.ultraDockManager.CompressUnpinnedTabs = false;
            dockAreaPane1.ChildPaneStyle = Infragistics.Win.UltraWinDock.ChildPaneStyle.VerticalSplit;
            dockableControlPane1.Control = this.pnlFiltro;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(268, -1);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(595, 6, 403, 441);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "FILTRO";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(284, 764);
            this.ultraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.ultraDockManager.HostControl = this;
            this.ultraDockManager.ShowCloseButton = false;
            this.ultraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.ultraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.ultraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.ultraDockManager_InitializePane);
            this.ultraDockManager.BeforeShowFlyout += new Infragistics.Win.UltraWinDock.CancelableControlPaneEventHandler(this.ultraDockManager_BeforeShowFlyout);
                                                this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft.Name = "_ucOrderEntryTrasversaleUnpinnedTabAreaLeft";
            this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft.Owner = this.ultraDockManager;
            this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 764);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft.TabIndex = 1;
                                                this._ucOrderEntryTrasversaleUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._ucOrderEntryTrasversaleUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucOrderEntryTrasversaleUnpinnedTabAreaRight.Location = new System.Drawing.Point(841, 0);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaRight.Name = "_ucOrderEntryTrasversaleUnpinnedTabAreaRight";
            this._ucOrderEntryTrasversaleUnpinnedTabAreaRight.Owner = this.ultraDockManager;
            this._ucOrderEntryTrasversaleUnpinnedTabAreaRight.Size = new System.Drawing.Size(23, 764);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaRight.TabIndex = 2;
                                                this._ucOrderEntryTrasversaleUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._ucOrderEntryTrasversaleUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucOrderEntryTrasversaleUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaTop.Name = "_ucOrderEntryTrasversaleUnpinnedTabAreaTop";
            this._ucOrderEntryTrasversaleUnpinnedTabAreaTop.Owner = this.ultraDockManager;
            this._ucOrderEntryTrasversaleUnpinnedTabAreaTop.Size = new System.Drawing.Size(841, 0);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaTop.TabIndex = 3;
                                                this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 764);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom.Name = "_ucOrderEntryTrasversaleUnpinnedTabAreaBottom";
            this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom.Owner = this.ultraDockManager;
            this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom.Size = new System.Drawing.Size(841, 0);
            this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom.TabIndex = 4;
                                                this._ucOrderEntryTrasversaleAutoHideControl.Controls.Add(this.dockableWindow1);
            this._ucOrderEntryTrasversaleAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucOrderEntryTrasversaleAutoHideControl.Location = new System.Drawing.Point(768, 0);
            this._ucOrderEntryTrasversaleAutoHideControl.Name = "_ucOrderEntryTrasversaleAutoHideControl";
            this._ucOrderEntryTrasversaleAutoHideControl.Owner = this.ultraDockManager;
            this._ucOrderEntryTrasversaleAutoHideControl.Size = new System.Drawing.Size(73, 764);
            this._ucOrderEntryTrasversaleAutoHideControl.TabIndex = 5;
                                                this.dockableWindow1.Controls.Add(this.pnlFiltro);
            this.dockableWindow1.Location = new System.Drawing.Point(5, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.ultraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(268, 764);
            this.dockableWindow1.TabIndex = 8;
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Right;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(552, 0);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.ultraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(289, 764);
            this.windowDockingArea1.TabIndex = 7;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._ucOrderEntryTrasversaleAutoHideControl);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._ucOrderEntryTrasversaleUnpinnedTabAreaTop);
            this.Controls.Add(this._ucOrderEntryTrasversaleUnpinnedTabAreaBottom);
            this.Controls.Add(this._ucOrderEntryTrasversaleUnpinnedTabAreaLeft);
            this.Controls.Add(this._ucOrderEntryTrasversaleUnpinnedTabAreaRight);
            this.Name = "ucOrderEntryMonitorTrasversale";
            this.Size = new System.Drawing.Size(864, 764);
            this.pnlFiltro.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFiltri.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewUO)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroTipo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            this.ucEasyTableLayoutPanelRicerca.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.txtNosologico)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chkVisualizzaPaziente)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtNome)).EndInit();
            this.ucEasyTableLayoutPanelFiltroData.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.txtCognome)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).EndInit();
            this._ucOrderEntryTrasversaleAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyGrid ucEasyGrid;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelRicerca;
        private ucEasyTextBox txtCognome;
        private ucEasyLabel lblCognome;
        private Infragistics.Win.UltraWinDock.UltraDockManager ultraDockManager;
        private Infragistics.Win.UltraWinDock.AutoHideControl _ucOrderEntryTrasversaleAutoHideControl;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucOrderEntryTrasversaleUnpinnedTabAreaBottom;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucOrderEntryTrasversaleUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucOrderEntryTrasversaleUnpinnedTabAreaRight;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucOrderEntryTrasversaleUnpinnedTabAreaLeft;
        private System.Windows.Forms.Panel pnlFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltri;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private ucEasyButton ubApplicaFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltroData;
        private ucEasyDateTimeEditor udteFiltroDA;
        private ucEasyLabel lblFiltroDa;
        private ucEasyDateRange drFiltro;
        private ucEasyDateTimeEditor udteFiltroA;
        private ucEasyLabel lblFiltroA;
        private ucEasyTextBox txtNome;
        private ucEasyLabel lblNome;
        private ucEasyTextBox txtNosologico;
        private ucEasyLabel lblNosologico;
        private ucEasyGrid ucEasyGridFiltroTipo;
        private ucEasyButton ubApplicaFiltroPanel;
        private ucEasyCheckEditor chkVisualizzaPaziente;
        private ucEasyLabel lblVisualizzaPaziente;
        private ucEasyTreeView ucEasyTreeViewUO;
    }
}
