namespace UnicodeSrl.ScciCore
{
    partial class ucParametriVitali
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucParametriVitali));
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem3 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem4 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem11 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem12 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem13 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubApplicaFiltro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyGridFiltroTipo = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPanelFiltro = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.udteFiltroDA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroDa = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.drFiltro = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.udteFiltroA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroA = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyTableLayoutPanelPulsanti = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubAdd = new UnicodeSrl.ScciCore.ucEasyButton();
            this.uchkFiltro = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroTipo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            this.ucEasyTableLayoutPanelFiltro.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).BeginInit();
            this.ucEasyTableLayoutPanelPulsanti.SuspendLayout();
            this.SuspendLayout();
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(878, 624);
            this.ultraGroupBox.TabIndex = 8;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 6;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 79F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ubApplicaFiltro, 3, 5);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGridFiltroTipo, 3, 2);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGrid, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelFiltro, 3, 4);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPanelPulsanti, 3, 1);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 7;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 0.8928571F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 16.07143F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 52.67857F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 0.8928571F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 21.42857F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142857F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 0.8928571F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(872, 618);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 16.25F;
            appearance1.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance1.ImageBackground")));
            appearance1.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance1.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance1.TextHAlignAsString = "Center";
            appearance1.TextVAlignAsString = "Middle";
            this.ubApplicaFiltro.Appearance = appearance1;
            this.ubApplicaFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ubApplicaFiltro, 2);
            this.ubApplicaFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltro.Location = new System.Drawing.Point(707, 569);
            this.ubApplicaFiltro.Name = "ubApplicaFiltro";
            this.ubApplicaFiltro.PercImageFill = 0.75F;
            this.ubApplicaFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltro.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltro.Size = new System.Drawing.Size(150, 38);
            this.ubApplicaFiltro.TabIndex = 9;
            this.ubApplicaFiltro.Text = "Applica filtro";
            this.ubApplicaFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltro.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ucEasyGridFiltroTipo.ColonnaRTFResize = "";
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyGridFiltroTipo, 2);
            this.ucEasyGridFiltroTipo.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroTipo.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance2.BackColor = System.Drawing.SystemColors.Window;
            appearance2.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroTipo.DisplayLayout.Appearance = appearance2;
            this.ucEasyGridFiltroTipo.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroTipo.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance3.FontData.BoldAsString = "True";
            appearance3.FontData.SizeInPoints = 16.25F;
            this.ucEasyGridFiltroTipo.DisplayLayout.CaptionAppearance = appearance3;
            this.ucEasyGridFiltroTipo.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance4.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance4.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance4.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Appearance = appearance4;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.BandLabelAppearance = appearance5;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance6.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance6.BackColor2 = System.Drawing.SystemColors.Control;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroTipo.DisplayLayout.GroupByBox.PromptAppearance = appearance6;
            this.ucEasyGridFiltroTipo.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroTipo.DisplayLayout.MaxRowScrollRegions = 1;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            appearance7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ActiveCellAppearance = appearance7;
            appearance8.BackColor = System.Drawing.SystemColors.Highlight;
            appearance8.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ActiveRowAppearance = appearance8;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance9.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CardAreaAppearance = appearance9;
            appearance10.BorderColor = System.Drawing.Color.Silver;
            appearance10.FontData.SizeInPoints = 11.25F;
            appearance10.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellAppearance = appearance10;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance11.FontData.SizeInPoints = 16.25F;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.FilterRowAppearance = appearance11;
            appearance12.BackColor = System.Drawing.SystemColors.Control;
            appearance12.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance12.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance12.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance12.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.GroupByRowAppearance = appearance12;
            appearance13.FontData.BoldAsString = "True";
            appearance13.FontData.SizeInPoints = 11.25F;
            appearance13.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderAppearance = appearance13;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance14.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance14.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowAlternateAppearance = appearance14;
            appearance15.BackColor = System.Drawing.SystemColors.Window;
            appearance15.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowAppearance = appearance15;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroTipo.DisplayLayout.Override.TemplateAddRowAppearance = appearance16;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroTipo.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroTipo.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroTipo.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroTipo.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroTipo.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridFiltroTipo.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridFiltroTipo.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroTipo.Location = new System.Drawing.Point(707, 107);
            this.ucEasyGridFiltroTipo.Name = "ucEasyGridFiltroTipo";
            this.ucEasyGridFiltroTipo.ShowFilterRow = false;
            this.ucEasyGridFiltroTipo.ShowGroupByBox = false;
            this.ucEasyGridFiltroTipo.Size = new System.Drawing.Size(150, 319);
            this.ucEasyGridFiltroTipo.TabIndex = 8;
            this.ucEasyGridFiltroTipo.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroTipo.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltroTipo_InitializeLayout);
                                                this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance17;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance18.FontData.BoldAsString = "True";
            appearance18.FontData.SizeInPoints = 16.25F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance18;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance19.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance19.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance19.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance19.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance19;
            appearance20.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance20;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance21.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance21.BackColor2 = System.Drawing.SystemColors.Control;
            appearance21.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance21.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance21;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance22.BackColor = System.Drawing.SystemColors.Window;
            appearance22.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance22;
            appearance23.BackColor = System.Drawing.SystemColors.Highlight;
            appearance23.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance23;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance24.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance24;
            appearance25.BorderColor = System.Drawing.Color.Silver;
            appearance25.FontData.SizeInPoints = 11.25F;
            appearance25.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance25;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance26.FontData.SizeInPoints = 16.25F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance26;
            appearance27.BackColor = System.Drawing.SystemColors.Control;
            appearance27.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance27.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance27.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance27.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance27;
            appearance28.FontData.BoldAsString = "True";
            appearance28.FontData.SizeInPoints = 11.25F;
            appearance28.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance28;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance29.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance29.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance29;
            appearance30.BackColor = System.Drawing.SystemColors.Window;
            appearance30.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance30;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance31.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance31;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(11, 8);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyTableLayoutPanel.SetRowSpan(this.ucEasyGrid, 5);
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(682, 599);
            this.ucEasyGrid.TabIndex = 0;
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.AfterRowActivate += new System.EventHandler(this.ucEasyGrid_AfterRowActivate);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
            this.ucEasyGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucEasyGrid_ClickCell);
                                                this.ucEasyTableLayoutPanelFiltro.ColumnCount = 1;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelFiltro, 2);
            this.ucEasyTableLayoutPanelFiltro.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanelFiltro.Controls.Add(this.udteFiltroDA, 0, 1);
            this.ucEasyTableLayoutPanelFiltro.Controls.Add(this.lblFiltroDa, 0, 0);
            this.ucEasyTableLayoutPanelFiltro.Controls.Add(this.drFiltro, 0, 5);
            this.ucEasyTableLayoutPanelFiltro.Controls.Add(this.udteFiltroA, 0, 3);
            this.ucEasyTableLayoutPanelFiltro.Controls.Add(this.lblFiltroA, 0, 2);
            this.ucEasyTableLayoutPanelFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltro.Location = new System.Drawing.Point(707, 437);
            this.ucEasyTableLayoutPanelFiltro.Name = "ucEasyTableLayoutPanelFiltro";
            this.ucEasyTableLayoutPanelFiltro.RowCount = 6;
            this.ucEasyTableLayoutPanelFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 23F));
            this.ucEasyTableLayoutPanelFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.ucEasyTableLayoutPanelFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 23F));
            this.ucEasyTableLayoutPanelFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 5F));
            this.ucEasyTableLayoutPanelFiltro.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 24F));
            this.ucEasyTableLayoutPanelFiltro.Size = new System.Drawing.Size(150, 126);
            this.ucEasyTableLayoutPanelFiltro.TabIndex = 7;
                                                appearance32.FontData.SizeInPoints = 11.25F;
            this.udteFiltroDA.Appearance = appearance32;
            this.udteFiltroDA.AutoSize = false;
            this.udteFiltroDA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroDA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroDA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance33.FontData.SizeInPoints = 11.25F;
            this.udteFiltroDA.DropDownAppearance = appearance33;
            this.udteFiltroDA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroDA.Location = new System.Drawing.Point(3, 21);
            this.udteFiltroDA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroDA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroDA.Name = "udteFiltroDA";
            this.udteFiltroDA.Size = new System.Drawing.Size(144, 21);
            this.udteFiltroDA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroDA.TabIndex = 1;
            this.udteFiltroDA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroDA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance34.FontData.SizeInPoints = 8.75F;
            appearance34.TextVAlignAsString = "Middle";
            this.lblFiltroDa.Appearance = appearance34;
            this.lblFiltroDa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDa.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroDa.Name = "lblFiltroDa";
            this.lblFiltroDa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDa.Size = new System.Drawing.Size(144, 12);
            this.lblFiltroDa.TabIndex = 2;
            this.lblFiltroDa.Text = "DA:";
            this.lblFiltroDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
                                                appearance35.FontData.SizeInPoints = 11.25F;
            this.drFiltro.Appearance = appearance35;
            this.drFiltro.AutoSize = false;
            this.drFiltro.DataEpisodio = new System.DateTime(((long)(0)));
            this.drFiltro.DateFuture = false;
            this.drFiltro.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.drFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.drFiltro.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem1.DisplayText = " ";
            valueListItem2.DataValue = "24H";
            valueListItem2.DisplayText = "Ultime 24h";
            valueListItem3.DataValue = "48H";
            valueListItem3.DisplayText = "Ultime 48h";
            valueListItem4.DataValue = "7G";
            valueListItem4.DisplayText = "Ultimi 7gg";
            valueListItem11.DataValue = "30G";
            valueListItem11.DisplayText = "Ultimi 30gg";
            valueListItem12.DataValue = "60G";
            valueListItem12.DisplayText = "Ultimi 60gg";
            valueListItem13.DataValue = "6M";
            valueListItem13.DisplayText = "Ultimi 6 mesi";
            this.drFiltro.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2,
            valueListItem3,
            valueListItem4,
            valueListItem11,
            valueListItem12,
            valueListItem13});
            this.drFiltro.Location = new System.Drawing.Point(3, 98);
            this.drFiltro.Name = "drFiltro";
            this.drFiltro.Size = new System.Drawing.Size(144, 25);
            this.drFiltro.TabIndex = 0;
            this.drFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.drFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.drFiltro.ValueChanged += new System.EventHandler(this.drFiltro_ValueChanged);
                                                appearance36.FontData.SizeInPoints = 11.25F;
            this.udteFiltroA.Appearance = appearance36;
            this.udteFiltroA.AutoSize = false;
            this.udteFiltroA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance37.FontData.SizeInPoints = 11.25F;
            this.udteFiltroA.DropDownAppearance = appearance37;
            this.udteFiltroA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroA.Location = new System.Drawing.Point(3, 66);
            this.udteFiltroA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroA.Name = "udteFiltroA";
            this.udteFiltroA.Size = new System.Drawing.Size(144, 21);
            this.udteFiltroA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroA.TabIndex = 2;
            this.udteFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.udteFiltroA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance38.FontData.SizeInPoints = 8.75F;
            appearance38.TextVAlignAsString = "Middle";
            this.lblFiltroA.Appearance = appearance38;
            this.lblFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroA.Location = new System.Drawing.Point(3, 48);
            this.lblFiltroA.Name = "lblFiltroA";
            this.lblFiltroA.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroA.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroA.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroA.Size = new System.Drawing.Size(144, 12);
            this.lblFiltroA.TabIndex = 2;
            this.lblFiltroA.Text = "A:";
            this.lblFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
                                                this.ucEasyTableLayoutPanelPulsanti.ColumnCount = 3;
            this.ucEasyTableLayoutPanel.SetColumnSpan(this.ucEasyTableLayoutPanelPulsanti, 2);
            this.ucEasyTableLayoutPanelPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 44.44445F));
            this.ucEasyTableLayoutPanelPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 11.11111F));
            this.ucEasyTableLayoutPanelPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 44.44444F));
            this.ucEasyTableLayoutPanelPulsanti.Controls.Add(this.ubAdd, 0, 0);
            this.ucEasyTableLayoutPanelPulsanti.Controls.Add(this.uchkFiltro, 2, 0);
            this.ucEasyTableLayoutPanelPulsanti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelPulsanti.Location = new System.Drawing.Point(704, 5);
            this.ucEasyTableLayoutPanelPulsanti.Margin = new System.Windows.Forms.Padding(0);
            this.ucEasyTableLayoutPanelPulsanti.Name = "ucEasyTableLayoutPanelPulsanti";
            this.ucEasyTableLayoutPanelPulsanti.RowCount = 2;
            this.ucEasyTableLayoutPanelPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 75F));
            this.ucEasyTableLayoutPanelPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelPulsanti.Size = new System.Drawing.Size(156, 99);
            this.ucEasyTableLayoutPanelPulsanti.TabIndex = 10;
                                                appearance39.FontData.SizeInPoints = 11.25F;
            appearance39.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance39.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance39.TextHAlignAsString = "Center";
            appearance39.TextVAlignAsString = "Bottom";
            this.ubAdd.Appearance = appearance39;
            this.ubAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAdd.Location = new System.Drawing.Point(3, 3);
            this.ubAdd.Name = "ubAdd";
            this.ubAdd.PercImageFill = 0.75F;
            this.ubAdd.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubAdd.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAdd.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAdd.Size = new System.Drawing.Size(63, 68);
            this.ubAdd.TabIndex = 3;
            this.ubAdd.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAdd.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAdd.Click += new System.EventHandler(this.ubAdd_Click);
                                                appearance40.FontData.SizeInPoints = 11.25F;
            appearance40.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance40.ImageBackground")));
            appearance40.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance40.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance40.TextHAlignAsString = "Center";
            appearance40.TextVAlignAsString = "Bottom";
            this.uchkFiltro.Appearance = appearance40;
            this.uchkFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkFiltro.Checked = false;
            this.uchkFiltro.CheckedImage = null;
            this.uchkFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkFiltro.Location = new System.Drawing.Point(89, 3);
            this.uchkFiltro.Name = "uchkFiltro";
            this.uchkFiltro.PercImageFill = 0.75F;
            this.uchkFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.uchkFiltro.ShortcutKey = System.Windows.Forms.Keys.F;
            this.uchkFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkFiltro.Size = new System.Drawing.Size(64, 68);
            this.uchkFiltro.TabIndex = 1;
            this.uchkFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkFiltro.UNCheckedImage = null;
            this.uchkFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uchkFiltro.Click += new System.EventHandler(this.uchkFiltro_Click);
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.ultraGroupBox);
            this.Name = "ucParametriVitali";
            this.Size = new System.Drawing.Size(878, 624);
            this.Enter += new System.EventHandler(this.ucParametriVitali_Enter);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroTipo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            this.ucEasyTableLayoutPanelFiltro.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).EndInit();
            this.ucEasyTableLayoutPanelPulsanti.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyButton ubAdd;
        private ucEasyGrid ucEasyGrid;
        private ucEasyStateButton uchkFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltro;
        private ucEasyDateTimeEditor udteFiltroDA;
        private ucEasyLabel lblFiltroDa;
        private ucEasyDateRange drFiltro;
        private ucEasyDateTimeEditor udteFiltroA;
        private ucEasyLabel lblFiltroA;
        private ucEasyGrid ucEasyGridFiltroTipo;
        private ucEasyButton ubApplicaFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelPulsanti;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
    }
}
