namespace UnicodeSrl.ScciCore
{
    partial class ucPercorsoAmbulatoriale
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucPercorsoAmbulatoriale));
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.tlpMainGrid = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblRicerca = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.tlpFiltri = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.UltraGridSchedePercorsi = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.lblFiltroStato = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyComboEditorFiltriSpeciali = new UnicodeSrl.ScciCore.ucEasyComboEditor();
            this.ucEasyComboEditorFiltroStatoCartella = new UnicodeSrl.ScciCore.ucEasyComboEditor();
            this.tlpPaziente = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyPictureBoxPaziente = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.ucEasyLabelPaziente = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucRtfPaziente = new UnicodeSrl.ScciCore.ucRtf();
            this.pnGrids = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGridRicerca = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.tlpRicerca = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubAzzera = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubRicerca = new UnicodeSrl.ScciCore.ucEasyButton();
            this.uteRicerca = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.tlpMainGrid.SuspendLayout();
            this.tlpFiltri.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridSchedePercorsi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyComboEditorFiltriSpeciali)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyComboEditorFiltroStatoCartella)).BeginInit();
            this.tlpPaziente.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyPictureBoxPaziente)).BeginInit();
            this.pnGrids.ClientArea.SuspendLayout();
            this.pnGrids.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridRicerca)).BeginInit();
            this.tlpRicerca.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteRicerca)).BeginInit();
            this.SuspendLayout();
                                                this.UltraGroupBox.Controls.Add(this.tlpMainGrid);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(968, 600);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.tlpMainGrid.BackColor = System.Drawing.Color.Transparent;
            this.tlpMainGrid.ColumnCount = 3;
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpMainGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpMainGrid.Controls.Add(this.lblRicerca, 0, 0);
            this.tlpMainGrid.Controls.Add(this.tlpFiltri, 2, 1);
            this.tlpMainGrid.Controls.Add(this.tlpPaziente, 0, 2);
            this.tlpMainGrid.Controls.Add(this.pnGrids, 0, 1);
            this.tlpMainGrid.Controls.Add(this.tlpRicerca, 1, 0);
            this.tlpMainGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpMainGrid.Location = new System.Drawing.Point(3, 3);
            this.tlpMainGrid.Name = "tlpMainGrid";
            this.tlpMainGrid.RowCount = 4;
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tlpMainGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpMainGrid.Size = new System.Drawing.Size(962, 594);
            this.tlpMainGrid.TabIndex = 0;
                                                appearance1.FontData.SizeInPoints = 19.59702F;
            appearance1.TextVAlignAsString = "Middle";
            this.lblRicerca.Appearance = appearance1;
            this.lblRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRicerca.Location = new System.Drawing.Point(3, 3);
            this.lblRicerca.Name = "lblRicerca";
            this.lblRicerca.ShortcutColor = System.Drawing.Color.Black;
            this.lblRicerca.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblRicerca.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblRicerca.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblRicerca.Size = new System.Drawing.Size(144, 44);
            this.lblRicerca.TabIndex = 0;
            this.lblRicerca.Text = "Ricerca";
            this.lblRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.tlpFiltri.ColumnCount = 1;
            this.tlpFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpFiltri.Controls.Add(this.UltraGridSchedePercorsi, 0, 0);
            this.tlpFiltri.Controls.Add(this.lblFiltroStato, 0, 2);
            this.tlpFiltri.Controls.Add(this.ucEasyComboEditorFiltriSpeciali, 0, 4);
            this.tlpFiltri.Controls.Add(this.ucEasyComboEditorFiltroStatoCartella, 0, 3);
            this.tlpFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpFiltri.Location = new System.Drawing.Point(802, 53);
            this.tlpFiltri.Name = "tlpFiltri";
            this.tlpFiltri.RowCount = 5;
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 81F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 5.5F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6.5F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpFiltri.Size = new System.Drawing.Size(157, 368);
            this.tlpFiltri.TabIndex = 8;
                                                this.UltraGridSchedePercorsi.ColonnaRTFControlloContenuto = false;
            this.UltraGridSchedePercorsi.ColonnaRTFResize = "";
            this.UltraGridSchedePercorsi.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridSchedePercorsi.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance2.BackColor = System.Drawing.SystemColors.Window;
            appearance2.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridSchedePercorsi.DisplayLayout.Appearance = appearance2;
            this.UltraGridSchedePercorsi.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridSchedePercorsi.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance3.FontData.BoldAsString = "True";
            appearance3.FontData.SizeInPoints = 10.55224F;
            this.UltraGridSchedePercorsi.DisplayLayout.CaptionAppearance = appearance3;
            this.UltraGridSchedePercorsi.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance4.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance4.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance4.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridSchedePercorsi.DisplayLayout.GroupByBox.Appearance = appearance4;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridSchedePercorsi.DisplayLayout.GroupByBox.BandLabelAppearance = appearance5;
            this.UltraGridSchedePercorsi.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridSchedePercorsi.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridSchedePercorsi.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance6.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance6.BackColor2 = System.Drawing.SystemColors.Control;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance6.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridSchedePercorsi.DisplayLayout.GroupByBox.PromptAppearance = appearance6;
            this.UltraGridSchedePercorsi.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridSchedePercorsi.DisplayLayout.MaxRowScrollRegions = 1;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            appearance7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.ActiveCellAppearance = appearance7;
            appearance8.BackColor = System.Drawing.SystemColors.Highlight;
            appearance8.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.ActiveRowAppearance = appearance8;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance9.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.CardAreaAppearance = appearance9;
            appearance10.BorderColor = System.Drawing.Color.Silver;
            appearance10.FontData.SizeInPoints = 10.55224F;
            appearance10.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.CellAppearance = appearance10;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance11.FontData.SizeInPoints = 10.55224F;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.FilterRowAppearance = appearance11;
            appearance12.BackColor = System.Drawing.SystemColors.Control;
            appearance12.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance12.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance12.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance12.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.GroupByRowAppearance = appearance12;
            appearance13.FontData.BoldAsString = "True";
            appearance13.FontData.SizeInPoints = 10.55224F;
            appearance13.TextHAlignAsString = "Center";
            this.UltraGridSchedePercorsi.DisplayLayout.Override.HeaderAppearance = appearance13;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance14.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance14.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.RowAlternateAppearance = appearance14;
            appearance15.BackColor = System.Drawing.SystemColors.Window;
            appearance15.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.RowAppearance = appearance15;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridSchedePercorsi.DisplayLayout.Override.TemplateAddRowAppearance = appearance16;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridSchedePercorsi.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.UltraGridSchedePercorsi.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridSchedePercorsi.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridSchedePercorsi.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridSchedePercorsi.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridSchedePercorsi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridSchedePercorsi.FattoreRidimensionamentoRTF = 21;
            this.UltraGridSchedePercorsi.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridSchedePercorsi.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridSchedePercorsi.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridSchedePercorsi.Location = new System.Drawing.Point(3, 3);
            this.UltraGridSchedePercorsi.Name = "UltraGridSchedePercorsi";
            this.UltraGridSchedePercorsi.ShowFilterRow = false;
            this.UltraGridSchedePercorsi.ShowGroupByBox = false;
            this.UltraGridSchedePercorsi.Size = new System.Drawing.Size(151, 292);
            this.UltraGridSchedePercorsi.TabIndex = 4;
            this.UltraGridSchedePercorsi.Text = "ucEasyGrid1";
            this.UltraGridSchedePercorsi.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridSchedePercorsi.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridSchedePercorsi.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGrid_InitializeLayout);
            this.UltraGridSchedePercorsi.AfterSelectChange += new Infragistics.Win.UltraWinGrid.AfterSelectChangeEventHandler(this.UltraGridSchedePercorsi_AfterSelectChange);
                                                appearance17.FontData.SizeInPoints = 13.56716F;
            appearance17.TextVAlignAsString = "Middle";
            this.lblFiltroStato.Appearance = appearance17;
            this.lblFiltroStato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroStato.Location = new System.Drawing.Point(3, 303);
            this.lblFiltroStato.Margin = new System.Windows.Forms.Padding(3, 2, 2, 2);
            this.lblFiltroStato.Name = "lblFiltroStato";
            this.lblFiltroStato.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroStato.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroStato.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroStato.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroStato.Size = new System.Drawing.Size(152, 16);
            this.lblFiltroStato.TabIndex = 0;
            this.lblFiltroStato.Text = "Stato Cartella:";
            this.lblFiltroStato.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
                                                appearance18.FontData.SizeInPoints = 13.56716F;
            this.ucEasyComboEditorFiltriSpeciali.Appearance = appearance18;
            this.ucEasyComboEditorFiltriSpeciali.AutoSize = false;
            this.ucEasyComboEditorFiltriSpeciali.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.ucEasyComboEditorFiltriSpeciali.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyComboEditorFiltriSpeciali.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ucEasyComboEditorFiltriSpeciali.Location = new System.Drawing.Point(3, 346);
            this.ucEasyComboEditorFiltriSpeciali.Margin = new System.Windows.Forms.Padding(3, 2, 2, 2);
            this.ucEasyComboEditorFiltriSpeciali.Name = "ucEasyComboEditorFiltriSpeciali";
            this.ucEasyComboEditorFiltriSpeciali.Size = new System.Drawing.Size(152, 20);
            this.ucEasyComboEditorFiltriSpeciali.TabIndex = 18;
            this.ucEasyComboEditorFiltriSpeciali.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyComboEditorFiltriSpeciali.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyComboEditorFiltriSpeciali.ValueChanged += new System.EventHandler(this.ucEasyComboEditorFiltriSpeciali_ValueChanged);
                                                appearance19.FontData.SizeInPoints = 13.56716F;
            this.ucEasyComboEditorFiltroStatoCartella.Appearance = appearance19;
            this.ucEasyComboEditorFiltroStatoCartella.AutoSize = false;
            this.ucEasyComboEditorFiltroStatoCartella.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.ucEasyComboEditorFiltroStatoCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyComboEditorFiltroStatoCartella.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.ucEasyComboEditorFiltroStatoCartella.Location = new System.Drawing.Point(3, 323);
            this.ucEasyComboEditorFiltroStatoCartella.Margin = new System.Windows.Forms.Padding(3, 2, 2, 2);
            this.ucEasyComboEditorFiltroStatoCartella.Name = "ucEasyComboEditorFiltroStatoCartella";
            this.ucEasyComboEditorFiltroStatoCartella.Size = new System.Drawing.Size(152, 19);
            this.ucEasyComboEditorFiltroStatoCartella.TabIndex = 17;
            this.ucEasyComboEditorFiltroStatoCartella.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyComboEditorFiltroStatoCartella.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyComboEditorFiltroStatoCartella.ValueChanged += new System.EventHandler(this.ucEasyComboEditorFiltroStatoCartella_ValueChanged);
                                                this.tlpPaziente.ColumnCount = 2;
            this.tlpMainGrid.SetColumnSpan(this.tlpPaziente, 3);
            this.tlpPaziente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tlpPaziente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpPaziente.Controls.Add(this.ucEasyPictureBoxPaziente, 0, 0);
            this.tlpPaziente.Controls.Add(this.ucEasyLabelPaziente, 1, 0);
            this.tlpPaziente.Controls.Add(this.ucRtfPaziente, 1, 1);
            this.tlpPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpPaziente.Location = new System.Drawing.Point(3, 427);
            this.tlpPaziente.Name = "tlpPaziente";
            this.tlpPaziente.RowCount = 2;
            this.tlpPaziente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tlpPaziente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpPaziente.Size = new System.Drawing.Size(956, 144);
            this.tlpPaziente.TabIndex = 9;
                                                this.ucEasyPictureBoxPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyPictureBoxPaziente.Location = new System.Drawing.Point(3, 3);
            this.ucEasyPictureBoxPaziente.Name = "ucEasyPictureBoxPaziente";
            this.tlpPaziente.SetRowSpan(this.ucEasyPictureBoxPaziente, 2);
            this.ucEasyPictureBoxPaziente.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyPictureBoxPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyPictureBoxPaziente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyPictureBoxPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyPictureBoxPaziente.Size = new System.Drawing.Size(144, 138);
            this.ucEasyPictureBoxPaziente.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.ucEasyPictureBoxPaziente.TabIndex = 0;
            this.ucEasyPictureBoxPaziente.TabStop = false;
                                                appearance20.FontData.SizeInPoints = 19.59702F;
            this.ucEasyLabelPaziente.Appearance = appearance20;
            this.ucEasyLabelPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyLabelPaziente.Location = new System.Drawing.Point(153, 3);
            this.ucEasyLabelPaziente.Name = "ucEasyLabelPaziente";
            this.ucEasyLabelPaziente.ShortcutColor = System.Drawing.Color.Black;
            this.ucEasyLabelPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyLabelPaziente.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ucEasyLabelPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ucEasyLabelPaziente.Size = new System.Drawing.Size(800, 29);
            this.ucEasyLabelPaziente.TabIndex = 1;
            this.ucEasyLabelPaziente.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucRtfPaziente.ColonnaRTFResize = "";
            this.ucRtfPaziente.Dati = null;
            this.ucRtfPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucRtfPaziente.FattoreRidimensionamentoRTF = 21;
            this.ucRtfPaziente.Immagine = null;
            this.ucRtfPaziente.Location = new System.Drawing.Point(153, 38);
            this.ucRtfPaziente.Name = "ucRtfPaziente";
            this.ucRtfPaziente.Size = new System.Drawing.Size(800, 103);
            this.ucRtfPaziente.TabIndex = 2;
            this.ucRtfPaziente.Titolo = "";
            this.ucRtfPaziente.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucRtfPaziente_ClickCell);
            this.ucRtfPaziente.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucRtfPaziente_InitializeLayout);
            this.ucRtfPaziente.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucRtfPaziente_InitializeRow);
                                                                                    this.pnGrids.ClientArea.Controls.Add(this.UltraGridRicerca);
            this.tlpMainGrid.SetColumnSpan(this.pnGrids, 2);
            this.pnGrids.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnGrids.Location = new System.Drawing.Point(1, 51);
            this.pnGrids.Margin = new System.Windows.Forms.Padding(1);
            this.pnGrids.Name = "pnGrids";
            this.pnGrids.Size = new System.Drawing.Size(797, 372);
            this.pnGrids.TabIndex = 12;
                                                this.UltraGridRicerca.ColonnaRTFControlloContenuto = false;
            this.UltraGridRicerca.ColonnaRTFResize = "";
            this.UltraGridRicerca.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.UltraGridRicerca.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance21.BackColor = System.Drawing.SystemColors.Window;
            appearance21.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridRicerca.DisplayLayout.Appearance = appearance21;
            this.UltraGridRicerca.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridRicerca.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance22.FontData.BoldAsString = "True";
            appearance22.FontData.SizeInPoints = 13.56716F;
            this.UltraGridRicerca.DisplayLayout.CaptionAppearance = appearance22;
            this.UltraGridRicerca.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance23.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance23.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance23.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance23.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridRicerca.DisplayLayout.GroupByBox.Appearance = appearance23;
            appearance24.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridRicerca.DisplayLayout.GroupByBox.BandLabelAppearance = appearance24;
            this.UltraGridRicerca.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridRicerca.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridRicerca.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance25.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance25.BackColor2 = System.Drawing.SystemColors.Control;
            appearance25.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance25.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridRicerca.DisplayLayout.GroupByBox.PromptAppearance = appearance25;
            this.UltraGridRicerca.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridRicerca.DisplayLayout.MaxRowScrollRegions = 1;
            appearance26.BackColor = System.Drawing.SystemColors.Window;
            appearance26.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridRicerca.DisplayLayout.Override.ActiveCellAppearance = appearance26;
            appearance27.BackColor = System.Drawing.SystemColors.Highlight;
            appearance27.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridRicerca.DisplayLayout.Override.ActiveRowAppearance = appearance27;
            this.UltraGridRicerca.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridRicerca.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridRicerca.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridRicerca.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridRicerca.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridRicerca.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridRicerca.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance28.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridRicerca.DisplayLayout.Override.CardAreaAppearance = appearance28;
            appearance29.BorderColor = System.Drawing.Color.Silver;
            appearance29.FontData.SizeInPoints = 10.55224F;
            appearance29.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridRicerca.DisplayLayout.Override.CellAppearance = appearance29;
            this.UltraGridRicerca.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridRicerca.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridRicerca.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance30.FontData.SizeInPoints = 13.56716F;
            this.UltraGridRicerca.DisplayLayout.Override.FilterRowAppearance = appearance30;
            appearance31.BackColor = System.Drawing.SystemColors.Control;
            appearance31.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance31.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance31.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance31.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridRicerca.DisplayLayout.Override.GroupByRowAppearance = appearance31;
            appearance32.FontData.BoldAsString = "True";
            appearance32.FontData.SizeInPoints = 13.56716F;
            appearance32.TextHAlignAsString = "Center";
            this.UltraGridRicerca.DisplayLayout.Override.HeaderAppearance = appearance32;
            this.UltraGridRicerca.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridRicerca.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance33.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance33.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridRicerca.DisplayLayout.Override.RowAlternateAppearance = appearance33;
            appearance34.BackColor = System.Drawing.SystemColors.Window;
            appearance34.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridRicerca.DisplayLayout.Override.RowAppearance = appearance34;
            this.UltraGridRicerca.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridRicerca.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridRicerca.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridRicerca.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance35.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridRicerca.DisplayLayout.Override.TemplateAddRowAppearance = appearance35;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridRicerca.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.UltraGridRicerca.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridRicerca.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridRicerca.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridRicerca.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridRicerca.FattoreRidimensionamentoRTF = 21;
            this.UltraGridRicerca.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridRicerca.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridRicerca.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.UltraGridRicerca.Location = new System.Drawing.Point(0, 0);
            this.UltraGridRicerca.Name = "UltraGridRicerca";
            this.UltraGridRicerca.ShowFilterRow = false;
            this.UltraGridRicerca.ShowGroupByBox = false;
            this.UltraGridRicerca.Size = new System.Drawing.Size(797, 372);
            this.UltraGridRicerca.TabIndex = 7;
            this.UltraGridRicerca.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridRicerca.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridRicerca.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridRicerca_InitializeLayout);
            this.UltraGridRicerca.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGridRicerca_InitializeRow);
            this.UltraGridRicerca.AfterRowActivate += new System.EventHandler(this.UltraGridRicerca_AfterRowActivate);
                                                this.tlpRicerca.ColumnCount = 3;
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15F));
            this.tlpRicerca.Controls.Add(this.ubAzzera, 2, 0);
            this.tlpRicerca.Controls.Add(this.ubRicerca, 1, 0);
            this.tlpRicerca.Controls.Add(this.uteRicerca, 0, 0);
            this.tlpRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRicerca.Location = new System.Drawing.Point(151, 1);
            this.tlpRicerca.Margin = new System.Windows.Forms.Padding(1);
            this.tlpRicerca.Name = "tlpRicerca";
            this.tlpRicerca.RowCount = 1;
            this.tlpRicerca.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRicerca.Size = new System.Drawing.Size(647, 48);
            this.tlpRicerca.TabIndex = 14;
                                                appearance36.FontData.SizeInPoints = 19.59702F;
            appearance36.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance36.ImageVAlign = Infragistics.Win.VAlign.Top;
            this.ubAzzera.Appearance = appearance36;
            this.ubAzzera.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAzzera.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAzzera.Location = new System.Drawing.Point(550, 3);
            this.ubAzzera.Margin = new System.Windows.Forms.Padding(1, 3, 1, 3);
            this.ubAzzera.Name = "ubAzzera";
            this.ubAzzera.PercImageFill = 0.75F;
            this.ubAzzera.ShortcutColor = System.Drawing.Color.Black;
            this.ubAzzera.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAzzera.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAzzera.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAzzera.Size = new System.Drawing.Size(96, 42);
            this.ubAzzera.TabIndex = 14;
            this.ubAzzera.Text = "Azzera";
            this.ubAzzera.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubAzzera.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAzzera.WrapText = false;
            this.ubAzzera.Click += new System.EventHandler(this.ubAzzera_Click);
                                                appearance37.FontData.SizeInPoints = 19.59702F;
            appearance37.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance37.ImageBackground")));
            appearance37.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance37.ImageVAlign = Infragistics.Win.VAlign.Top;
            this.ubRicerca.Appearance = appearance37;
            this.ubRicerca.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRicerca.Location = new System.Drawing.Point(452, 3);
            this.ubRicerca.Margin = new System.Windows.Forms.Padding(0, 3, 1, 3);
            this.ubRicerca.Name = "ubRicerca";
            this.ubRicerca.PercImageFill = 0.75F;
            this.ubRicerca.ShortcutColor = System.Drawing.Color.Black;
            this.ubRicerca.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubRicerca.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubRicerca.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubRicerca.Size = new System.Drawing.Size(96, 42);
            this.ubRicerca.TabIndex = 13;
            this.ubRicerca.Text = "Ricerca";
            this.ubRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubRicerca.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubRicerca.WrapText = false;
            this.ubRicerca.Click += new System.EventHandler(this.ubRicerca_Click);
                                                appearance38.FontData.SizeInPoints = 13.56716F;
            this.uteRicerca.Appearance = appearance38;
            this.uteRicerca.AutoSize = false;
            this.uteRicerca.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteRicerca.Location = new System.Drawing.Point(3, 3);
            this.uteRicerca.Name = "uteRicerca";
            this.uteRicerca.Size = new System.Drawing.Size(446, 42);
            this.uteRicerca.TabIndex = 2;
            this.uteRicerca.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uteRicerca.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uteRicerca.KeyDown += new System.Windows.Forms.KeyEventHandler(this.uteRicerca_KeyDown);
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.UltraGroupBox);
            this.Name = "ucPercorsoAmbulatoriale";
            this.Size = new System.Drawing.Size(968, 600);
            this.Tag = "1";
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.tlpMainGrid.ResumeLayout(false);
            this.tlpFiltri.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridSchedePercorsi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyComboEditorFiltriSpeciali)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyComboEditorFiltroStatoCartella)).EndInit();
            this.tlpPaziente.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyPictureBoxPaziente)).EndInit();
            this.pnGrids.ClientArea.ResumeLayout(false);
            this.pnGrids.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridRicerca)).EndInit();
            this.tlpRicerca.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.uteRicerca)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private ucEasyTableLayoutPanel tlpMainGrid;
        private ucEasyLabel lblRicerca;
        private ucEasyTableLayoutPanel tlpFiltri;
        internal ucEasyGrid UltraGridRicerca;
        private ucEasyTableLayoutPanel tlpPaziente;
        private ucEasyPictureBox ucEasyPictureBoxPaziente;
        private ucEasyLabel ucEasyLabelPaziente;
        private ucRtf ucRtfPaziente;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private ucEasyGrid UltraGridSchedePercorsi;
        private ucEasyComboEditor ucEasyComboEditorFiltriSpeciali;
        private ucEasyComboEditor ucEasyComboEditorFiltroStatoCartella;
        private ucEasyLabel lblFiltroStato;
        private Infragistics.Win.Misc.UltraPanel pnGrids;
        private ucEasyTableLayoutPanel tlpRicerca;
        private ucEasyButton ubAzzera;
        private ucEasyButton ubRicerca;
        private ucEasyTextBox uteRicerca;
    }
}
