namespace UnicodeSrl.ScciCore
{
    partial class ucSCCIScatterChartGrid
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            Infragistics.UltraChart.Resources.Appearance.PaintElement paintElement1 = new Infragistics.UltraChart.Resources.Appearance.PaintElement();
            Infragistics.UltraChart.Resources.Appearance.TimeAxisAppearance timeAxisAppearance1 = new Infragistics.UltraChart.Resources.Appearance.TimeAxisAppearance();
            Infragistics.UltraChart.Resources.Appearance.GradientEffect gradientEffect1 = new Infragistics.UltraChart.Resources.Appearance.GradientEffect();
            Infragistics.UltraChart.Resources.Appearance.ScatterChartAppearance scatterChartAppearance1 = new Infragistics.UltraChart.Resources.Appearance.ScatterChartAppearance();
            Infragistics.UltraChart.Resources.Appearance.ChartTextAppearance chartTextAppearance1 = new Infragistics.UltraChart.Resources.Appearance.ChartTextAppearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab2 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ultraChart = new Infragistics.Win.UltraWinChart.UltraChart();
            this.ultraTabPageControl2 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucEasyGridDati = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.lblTitolo = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utabcGraficoDati = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ultraTabPageControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraChart)).BeginInit();
            this.ultraTabPageControl2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridDati)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.utabcGraficoDati)).BeginInit();
            this.utabcGraficoDati.SuspendLayout();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.ultraChart);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(0, 0);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(796, 524);
                        this.ultraChart.ChartType = Infragistics.UltraChart.Shared.Styles.ChartType.ScatterChart;
                                                this.ultraChart.Axis.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(220)))));
            paintElement1.ElementType = Infragistics.UltraChart.Shared.Styles.PaintElementType.None;
            paintElement1.Fill = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(248)))), ((int)(((byte)(220)))));
            this.ultraChart.Axis.PE = paintElement1;
            this.ultraChart.Axis.X.Labels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.X.Labels.FontColor = System.Drawing.Color.DimGray;
            this.ultraChart.Axis.X.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
            this.ultraChart.Axis.X.Labels.ItemFormatString = "<DATA_VALUE:00.##>";
            this.ultraChart.Axis.X.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.X.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
            this.ultraChart.Axis.X.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.X.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
            this.ultraChart.Axis.X.Labels.SeriesLabels.FormatString = "";
            this.ultraChart.Axis.X.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
            this.ultraChart.Axis.X.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.X.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
            this.ultraChart.Axis.X.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.X.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.X.LineThickness = 1;
            this.ultraChart.Axis.X.MajorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.X.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
            this.ultraChart.Axis.X.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.X.MajorGridLines.Visible = true;
            this.ultraChart.Axis.X.MinorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.X.MinorGridLines.Color = System.Drawing.Color.LightGray;
            this.ultraChart.Axis.X.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.X.MinorGridLines.Visible = false;
            this.ultraChart.Axis.X.TickmarkInterval = 5D;
            this.ultraChart.Axis.X.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
            timeAxisAppearance1.TimeAxisStyle = Infragistics.UltraChart.Shared.Styles.RulerGenre.Discrete;
            this.ultraChart.Axis.X.TimeAxisStyle = timeAxisAppearance1;
            this.ultraChart.Axis.X.Visible = true;
            this.ultraChart.Axis.X2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.X2.Labels.FontColor = System.Drawing.Color.Gray;
            this.ultraChart.Axis.X2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Far;
            this.ultraChart.Axis.X2.Labels.ItemFormatString = "<DATA_VALUE:00.##>";
            this.ultraChart.Axis.X2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.X2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
            this.ultraChart.Axis.X2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.X2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
            this.ultraChart.Axis.X2.Labels.SeriesLabels.FormatString = "";
            this.ultraChart.Axis.X2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Far;
            this.ultraChart.Axis.X2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.X2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.VerticalLeftFacing;
            this.ultraChart.Axis.X2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.X2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.X2.Labels.Visible = false;
            this.ultraChart.Axis.X2.LineThickness = 1;
            this.ultraChart.Axis.X2.MajorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.X2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
            this.ultraChart.Axis.X2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.X2.MajorGridLines.Visible = true;
            this.ultraChart.Axis.X2.MinorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.X2.MinorGridLines.Color = System.Drawing.Color.LightGray;
            this.ultraChart.Axis.X2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.X2.MinorGridLines.Visible = false;
            this.ultraChart.Axis.X2.TickmarkInterval = 5D;
            this.ultraChart.Axis.X2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
            this.ultraChart.Axis.X2.Visible = false;
            this.ultraChart.Axis.Y.Labels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.Y.Labels.FontColor = System.Drawing.Color.DimGray;
            this.ultraChart.Axis.Y.Labels.HorizontalAlign = System.Drawing.StringAlignment.Far;
            this.ultraChart.Axis.Y.Labels.ItemFormatString = "<DATA_VALUE:00.##>";
            this.ultraChart.Axis.Y.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.Y.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
            this.ultraChart.Axis.Y.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.Y.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
            this.ultraChart.Axis.Y.Labels.SeriesLabels.FormatString = "";
            this.ultraChart.Axis.Y.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Far;
            this.ultraChart.Axis.Y.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.Y.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
            this.ultraChart.Axis.Y.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.Y.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.Y.LineThickness = 1;
            this.ultraChart.Axis.Y.MajorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.Y.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
            this.ultraChart.Axis.Y.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.Y.MajorGridLines.Visible = true;
            this.ultraChart.Axis.Y.MinorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.Y.MinorGridLines.Color = System.Drawing.Color.LightGray;
            this.ultraChart.Axis.Y.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.Y.MinorGridLines.Visible = false;
            this.ultraChart.Axis.Y.TickmarkInterval = 40D;
            this.ultraChart.Axis.Y.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
            this.ultraChart.Axis.Y.Visible = true;
            this.ultraChart.Axis.Y2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.Y2.Labels.FontColor = System.Drawing.Color.Gray;
            this.ultraChart.Axis.Y2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
            this.ultraChart.Axis.Y2.Labels.ItemFormatString = "<DATA_VALUE:00.##>";
            this.ultraChart.Axis.Y2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.Y2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
            this.ultraChart.Axis.Y2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.Y2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
            this.ultraChart.Axis.Y2.Labels.SeriesLabels.FormatString = "";
            this.ultraChart.Axis.Y2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
            this.ultraChart.Axis.Y2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.Y2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
            this.ultraChart.Axis.Y2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.Y2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.Y2.Labels.Visible = false;
            this.ultraChart.Axis.Y2.LineThickness = 1;
            this.ultraChart.Axis.Y2.MajorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.Y2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
            this.ultraChart.Axis.Y2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.Y2.MajorGridLines.Visible = true;
            this.ultraChart.Axis.Y2.MinorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.Y2.MinorGridLines.Color = System.Drawing.Color.LightGray;
            this.ultraChart.Axis.Y2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.Y2.MinorGridLines.Visible = false;
            this.ultraChart.Axis.Y2.TickmarkInterval = 40D;
            this.ultraChart.Axis.Y2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
            this.ultraChart.Axis.Y2.Visible = false;
            this.ultraChart.Axis.Z.Labels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.Z.Labels.FontColor = System.Drawing.Color.DimGray;
            this.ultraChart.Axis.Z.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
            this.ultraChart.Axis.Z.Labels.ItemFormatString = "";
            this.ultraChart.Axis.Z.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.Z.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
            this.ultraChart.Axis.Z.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.Z.Labels.SeriesLabels.FontColor = System.Drawing.Color.DimGray;
            this.ultraChart.Axis.Z.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
            this.ultraChart.Axis.Z.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.Z.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
            this.ultraChart.Axis.Z.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.Z.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.Z.Labels.Visible = false;
            this.ultraChart.Axis.Z.LineThickness = 1;
            this.ultraChart.Axis.Z.MajorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.Z.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
            this.ultraChart.Axis.Z.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.Z.MajorGridLines.Visible = true;
            this.ultraChart.Axis.Z.MinorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.Z.MinorGridLines.Color = System.Drawing.Color.LightGray;
            this.ultraChart.Axis.Z.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.Z.MinorGridLines.Visible = false;
            this.ultraChart.Axis.Z.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
            this.ultraChart.Axis.Z.Visible = false;
            this.ultraChart.Axis.Z2.Labels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.Z2.Labels.FontColor = System.Drawing.Color.Gray;
            this.ultraChart.Axis.Z2.Labels.HorizontalAlign = System.Drawing.StringAlignment.Near;
            this.ultraChart.Axis.Z2.Labels.ItemFormatString = "";
            this.ultraChart.Axis.Z2.Labels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.Z2.Labels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
            this.ultraChart.Axis.Z2.Labels.SeriesLabels.Font = new System.Drawing.Font("Verdana", 7F);
            this.ultraChart.Axis.Z2.Labels.SeriesLabels.FontColor = System.Drawing.Color.Gray;
            this.ultraChart.Axis.Z2.Labels.SeriesLabels.HorizontalAlign = System.Drawing.StringAlignment.Near;
            this.ultraChart.Axis.Z2.Labels.SeriesLabels.Layout.Behavior = Infragistics.UltraChart.Shared.Styles.AxisLabelLayoutBehaviors.Auto;
            this.ultraChart.Axis.Z2.Labels.SeriesLabels.Orientation = Infragistics.UltraChart.Shared.Styles.TextOrientation.Horizontal;
            this.ultraChart.Axis.Z2.Labels.SeriesLabels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.Z2.Labels.VerticalAlign = System.Drawing.StringAlignment.Center;
            this.ultraChart.Axis.Z2.Labels.Visible = false;
            this.ultraChart.Axis.Z2.LineThickness = 1;
            this.ultraChart.Axis.Z2.MajorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.Z2.MajorGridLines.Color = System.Drawing.Color.Gainsboro;
            this.ultraChart.Axis.Z2.MajorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.Z2.MajorGridLines.Visible = true;
            this.ultraChart.Axis.Z2.MinorGridLines.AlphaLevel = ((byte)(255));
            this.ultraChart.Axis.Z2.MinorGridLines.Color = System.Drawing.Color.LightGray;
            this.ultraChart.Axis.Z2.MinorGridLines.DrawStyle = Infragistics.UltraChart.Shared.Styles.LineDrawStyle.Dot;
            this.ultraChart.Axis.Z2.MinorGridLines.Visible = false;
            this.ultraChart.Axis.Z2.TickmarkStyle = Infragistics.UltraChart.Shared.Styles.AxisTickStyle.Smart;
            this.ultraChart.Axis.Z2.Visible = false;
            this.ultraChart.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.ultraChart.ColorModel.AlphaLevel = ((byte)(150));
            this.ultraChart.ColorModel.ColorBegin = System.Drawing.Color.Pink;
            this.ultraChart.ColorModel.ColorEnd = System.Drawing.Color.DarkRed;
            this.ultraChart.ColorModel.ModelStyle = Infragistics.UltraChart.Shared.Styles.ColorModels.CustomLinear;
            this.ultraChart.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraChart.Effects.Effects.Add(gradientEffect1);
            this.ultraChart.Legend.SpanPercentage = 18;
            this.ultraChart.Legend.Visible = true;
            this.ultraChart.Location = new System.Drawing.Point(0, 0);
            this.ultraChart.Name = "ultraChart";
            chartTextAppearance1.ChartTextFont = new System.Drawing.Font("Arial", 7F);
            chartTextAppearance1.ClipText = false;
            chartTextAppearance1.Column = -2;
            chartTextAppearance1.ItemFormatString = "<DATA_VALUE:00.00>";
            chartTextAppearance1.Row = -2;
            chartTextAppearance1.Visible = true;
            scatterChartAppearance1.ChartText.Add(chartTextAppearance1);
            scatterChartAppearance1.ConnectWithLines = true;
            scatterChartAppearance1.Icon = Infragistics.UltraChart.Shared.Styles.SymbolIcon.Square;
            scatterChartAppearance1.LineAppearance.Thickness = 4;
            scatterChartAppearance1.NullHandling = Infragistics.UltraChart.Shared.Styles.NullHandling.DontPlot;
            this.ultraChart.ScatterChart = scatterChartAppearance1;
            this.ultraChart.Size = new System.Drawing.Size(796, 524);
            this.ultraChart.TabIndex = 0;
            this.ultraChart.Tooltips.HighlightFillColor = System.Drawing.Color.DimGray;
            this.ultraChart.Tooltips.HighlightOutlineColor = System.Drawing.Color.DarkGray;
                                                this.ultraTabPageControl2.Controls.Add(this.ucEasyGridDati);
            this.ultraTabPageControl2.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl2.Name = "ultraTabPageControl2";
            this.ultraTabPageControl2.Size = new System.Drawing.Size(796, 527);
                                                this.ucEasyGridDati.ColonnaRTFResize = "";
            this.ucEasyGridDati.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridDati.DisplayLayout.Appearance = appearance1;
            this.ucEasyGridDati.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridDati.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance2.FontData.BoldAsString = "True";
            appearance2.FontData.SizeInPoints = 18F;
            this.ucEasyGridDati.DisplayLayout.CaptionAppearance = appearance2;
            this.ucEasyGridDati.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance3.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance3.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance3.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance3.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDati.DisplayLayout.GroupByBox.Appearance = appearance3;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridDati.DisplayLayout.GroupByBox.BandLabelAppearance = appearance4;
            this.ucEasyGridDati.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridDati.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridDati.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance5.BackColor2 = System.Drawing.SystemColors.Control;
            appearance5.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance5.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridDati.DisplayLayout.GroupByBox.PromptAppearance = appearance5;
            this.ucEasyGridDati.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridDati.DisplayLayout.MaxRowScrollRegions = 1;
            appearance6.BackColor = System.Drawing.SystemColors.Window;
            appearance6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridDati.DisplayLayout.Override.ActiveCellAppearance = appearance6;
            appearance7.BackColor = System.Drawing.SystemColors.Highlight;
            appearance7.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridDati.DisplayLayout.Override.ActiveRowAppearance = appearance7;
            this.ucEasyGridDati.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridDati.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridDati.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDati.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDati.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDati.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridDati.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance8.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDati.DisplayLayout.Override.CardAreaAppearance = appearance8;
            appearance9.BorderColor = System.Drawing.Color.Silver;
            appearance9.FontData.SizeInPoints = 18F;
            appearance9.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridDati.DisplayLayout.Override.CellAppearance = appearance9;
            this.ucEasyGridDati.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridDati.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridDati.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance10.FontData.SizeInPoints = 18F;
            this.ucEasyGridDati.DisplayLayout.Override.FilterRowAppearance = appearance10;
            appearance11.BackColor = System.Drawing.SystemColors.Control;
            appearance11.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance11.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance11.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance11.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridDati.DisplayLayout.Override.GroupByRowAppearance = appearance11;
            appearance12.FontData.BoldAsString = "True";
            appearance12.FontData.SizeInPoints = 18F;
            appearance12.TextHAlignAsString = "Center";
            this.ucEasyGridDati.DisplayLayout.Override.HeaderAppearance = appearance12;
            this.ucEasyGridDati.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridDati.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance13.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance13.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridDati.DisplayLayout.Override.RowAlternateAppearance = appearance13;
            appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridDati.DisplayLayout.Override.RowAppearance = appearance14;
            this.ucEasyGridDati.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDati.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridDati.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridDati.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance15.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridDati.DisplayLayout.Override.TemplateAddRowAppearance = appearance15;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridDati.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridDati.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridDati.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridDati.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridDati.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridDati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridDati.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridDati.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDati.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDati.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridDati.Location = new System.Drawing.Point(0, 0);
            this.ucEasyGridDati.Name = "ucEasyGridDati";
            this.ucEasyGridDati.ShowFilterRow = false;
            this.ucEasyGridDati.ShowGroupByBox = false;
            this.ucEasyGridDati.Size = new System.Drawing.Size(796, 527);
            this.ucEasyGridDati.TabIndex = 0;
            this.ucEasyGridDati.Text = "Dati";
            this.ucEasyGridDati.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridDati.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridDati.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridDati_InitializeLayout);
                                                appearance16.FontData.SizeInPoints = 18F;
            appearance16.TextVAlignAsString = "Bottom";
            this.lblTitolo.Appearance = appearance16;
            this.lblTitolo.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblTitolo.Location = new System.Drawing.Point(0, 0);
            this.lblTitolo.Name = "lblTitolo";
            this.lblTitolo.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblTitolo.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblTitolo.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblTitolo.Size = new System.Drawing.Size(796, 32);
            this.lblTitolo.TabIndex = 0;
            this.lblTitolo.Text = "Titolo";
            this.lblTitolo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.utabcGraficoDati.Controls.Add(this.ultraTabSharedControlsPage1);
            this.utabcGraficoDati.Controls.Add(this.ultraTabPageControl1);
            this.utabcGraficoDati.Controls.Add(this.ultraTabPageControl2);
            this.utabcGraficoDati.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utabcGraficoDati.Location = new System.Drawing.Point(0, 32);
            this.utabcGraficoDati.Name = "utabcGraficoDati";
            this.utabcGraficoDati.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.utabcGraficoDati.Size = new System.Drawing.Size(796, 524);
            this.utabcGraficoDati.Style = Infragistics.Win.UltraWinTabControl.UltraTabControlStyle.Wizard;
            this.utabcGraficoDati.TabIndex = 10;
            ultraTab1.Key = "tabGrafico";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Grafico";
            ultraTab2.Key = "tabDati";
            ultraTab2.TabPage = this.ultraTabPageControl2;
            ultraTab2.Text = "Dati";
            this.utabcGraficoDati.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1,
            ultraTab2});
            this.utabcGraficoDati.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(796, 524);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Transparent;
            this.Controls.Add(this.utabcGraficoDati);
            this.Controls.Add(this.lblTitolo);
            this.Name = "ucSCCIScatterChart";
            this.Size = new System.Drawing.Size(796, 556);
            this.VisibleChanged += new System.EventHandler(this.ucSCCIChart_VisibleChanged);
            this.ultraTabPageControl1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraChart)).EndInit();
            this.ultraTabPageControl2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridDati)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.utabcGraficoDati)).EndInit();
            this.utabcGraficoDati.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private ucEasyLabel lblTitolo;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl utabcGraficoDati;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl2;
        private ucEasyGrid ucEasyGridDati;
        private Infragistics.Win.UltraWinChart.UltraChart ultraChart;
    }
}
