namespace UnicodeSrl.ScciCore
{
    partial class ucWorkListInfermieristica
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override2 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucWorkListInfermieristica));
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem3 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem4 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem5 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem6 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem7 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem8 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedRight, new System.Guid("c669a24c-e20d-407a-a586-526afa94aaec"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("92dda4f1-1506-49c2-a492-16960ee8adf5"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("c669a24c-e20d-407a-a586-526afa94aaec"), -1);
            this.pnlFiltro = new System.Windows.Forms.Panel();
            this.ucEasyTableLayoutPanelFiltri = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTableLayoutPanel1 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.lblFiltroContenuto = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.utxtFiltroContenuto = new UnicodeSrl.ScciCore.ucEasyTextBox();
            this.ucEasyTreeViewTipo = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ucEasyTreeViewVie = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.ubApplicaFiltro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ucEasyTableLayoutPanelFiltroData = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.udteFiltroDA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroDa = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.drFiltro = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.udteFiltroA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblFiltroA = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.ucEasyGridFiltroStato = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyGrid = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.ucEasyTableLayoutPulsanti = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ubSpostaTask = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubAdmin = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubAdd = new UnicodeSrl.ScciCore.ucEasyButton();
            this.uchkFiltro = new UnicodeSrl.ScciCore.ucEasyStateButton();
            this.ucEasyPopUpOrario = new UnicodeSrl.ScciCore.ucEasyPopUpOrario();
            this.ultraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._ucWorkListInfermieristicaUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucWorkListInfermieristicaUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucWorkListInfermieristicaUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucWorkListInfermieristicaUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucWorkListInfermieristicaAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.ultraToolTipManager1 = new Infragistics.Win.UltraWinToolTip.UltraToolTipManager(this.components);
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.ultraPopupControlContainerOra = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.pnlFiltro.SuspendLayout();
            this.ucEasyTableLayoutPanelFiltri.SuspendLayout();
            this.ucEasyTableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.utxtFiltroContenuto)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewTipo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewVie)).BeginInit();
            this.ucEasyTableLayoutPanelFiltroData.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).BeginInit();
            this.ucEasyTableLayoutPulsanti.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).BeginInit();
            this._ucWorkListInfermieristicaAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            this.SuspendLayout();
                                                this.pnlFiltro.Controls.Add(this.ucEasyTableLayoutPanelFiltri);
            this.pnlFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlFiltro.Location = new System.Drawing.Point(0, 18);
            this.pnlFiltro.Name = "pnlFiltro";
            this.pnlFiltro.Size = new System.Drawing.Size(490, 606);
            this.pnlFiltro.TabIndex = 1;
                                                this.ucEasyTableLayoutPanelFiltri.ColumnCount = 5;
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 48F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyTableLayoutPanel1, 1, 2);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyTreeViewTipo, 1, 0);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyTreeViewVie, 3, 1);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ubApplicaFiltro, 2, 4);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyTableLayoutPanelFiltroData, 1, 3);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyGridFiltroStato, 3, 0);
            this.ucEasyTableLayoutPanelFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltri.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelFiltri.Name = "ucEasyTableLayoutPanelFiltri";
            this.ucEasyTableLayoutPanelFiltri.RowCount = 5;
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 39F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 13F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.ucEasyTableLayoutPanelFiltri.Size = new System.Drawing.Size(490, 606);
            this.ucEasyTableLayoutPanelFiltri.TabIndex = 0;
                                                this.ucEasyTableLayoutPanel1.ColumnCount = 1;
            this.ucEasyTableLayoutPanelFiltri.SetColumnSpan(this.ucEasyTableLayoutPanel1, 3);
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.Controls.Add(this.lblFiltroContenuto, 0, 0);
            this.ucEasyTableLayoutPanel1.Controls.Add(this.utxtFiltroContenuto, 0, 1);
            this.ucEasyTableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel1.Location = new System.Drawing.Point(7, 390);
            this.ucEasyTableLayoutPanel1.Name = "ucEasyTableLayoutPanel1";
            this.ucEasyTableLayoutPanel1.RowCount = 2;
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanel1.Size = new System.Drawing.Size(473, 72);
            this.ucEasyTableLayoutPanel1.TabIndex = 15;
                                                appearance1.FontData.SizeInPoints = 22.50746F;
            appearance1.TextVAlignAsString = "Middle";
            this.lblFiltroContenuto.Appearance = appearance1;
            this.lblFiltroContenuto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroContenuto.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroContenuto.Name = "lblFiltroContenuto";
            this.lblFiltroContenuto.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroContenuto.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroContenuto.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroContenuto.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroContenuto.Size = new System.Drawing.Size(467, 22);
            this.lblFiltroContenuto.TabIndex = 2;
            this.lblFiltroContenuto.Text = "CONTENUTO:";
            this.lblFiltroContenuto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance2.FontData.SizeInPoints = 22.50746F;
            this.utxtFiltroContenuto.Appearance = appearance2;
            this.utxtFiltroContenuto.AutoSize = false;
            this.utxtFiltroContenuto.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.utxtFiltroContenuto.Dock = System.Windows.Forms.DockStyle.Fill;
            this.utxtFiltroContenuto.Location = new System.Drawing.Point(3, 31);
            this.utxtFiltroContenuto.Name = "utxtFiltroContenuto";
            this.utxtFiltroContenuto.Size = new System.Drawing.Size(467, 38);
            this.utxtFiltroContenuto.TabIndex = 1;
            this.utxtFiltroContenuto.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.utxtFiltroContenuto.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.utxtFiltroContenuto.KeyDown += new System.Windows.Forms.KeyEventHandler(this.utxtFiltroContenuto_KeyDown);
                                                appearance3.FontData.SizeInPoints = 15.58209F;
            this.ucEasyTreeViewTipo.Appearance = appearance3;
            this.ucEasyTreeViewTipo.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTreeViewTipo.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewTipo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewTipo.HideSelection = false;
            this.ucEasyTreeViewTipo.Location = new System.Drawing.Point(7, 3);
            this.ucEasyTreeViewTipo.Name = "ucEasyTreeViewTipo";
            appearance4.BackColor = System.Drawing.Color.LightYellow;
            appearance4.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance4;
            _override1.SelectedNodeAppearance = appearance4;
            this.ucEasyTreeViewTipo.Override = _override1;
            this.ucEasyTableLayoutPanelFiltri.SetRowSpan(this.ucEasyTreeViewTipo, 2);
            this.ucEasyTreeViewTipo.Size = new System.Drawing.Size(229, 381);
            this.ucEasyTreeViewTipo.TabIndex = 14;
            this.ucEasyTreeViewTipo.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeViewTipo.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeViewTipo.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeView_AfterCheck);
                                                appearance5.FontData.SizeInPoints = 15.58209F;
            this.ucEasyTreeViewVie.Appearance = appearance5;
            this.ucEasyTreeViewVie.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTreeViewVie.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewVie.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewVie.HideSelection = false;
            this.ucEasyTreeViewVie.Location = new System.Drawing.Point(251, 154);
            this.ucEasyTreeViewVie.Name = "ucEasyTreeViewVie";
            appearance6.BackColor = System.Drawing.Color.LightYellow;
            appearance6.BackColor2 = System.Drawing.Color.Orange;
            _override2.ActiveNodeAppearance = appearance6;
            _override2.SelectedNodeAppearance = appearance6;
            this.ucEasyTreeViewVie.Override = _override2;
            this.ucEasyTreeViewVie.Size = new System.Drawing.Size(229, 230);
            this.ucEasyTreeViewVie.TabIndex = 13;
            this.ucEasyTreeViewVie.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyTreeViewVie.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeViewVie.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeView_AfterCheck);
                                                appearance7.FontData.SizeInPoints = 22.50746F;
            appearance7.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance7.ImageBackground")));
            appearance7.ImageHAlign = Infragistics.Win.HAlign.Left;
            appearance7.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance7.TextHAlignAsString = "Center";
            appearance7.TextVAlignAsString = "Middle";
            this.ubApplicaFiltro.Appearance = appearance7;
            this.ubApplicaFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ucEasyTableLayoutPanelFiltri.SetColumnSpan(this.ubApplicaFiltro, 2);
            this.ubApplicaFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubApplicaFiltro.Location = new System.Drawing.Point(242, 546);
            this.ubApplicaFiltro.Name = "ubApplicaFiltro";
            this.ubApplicaFiltro.PercImageFill = 0.75F;
            this.ubApplicaFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.ubApplicaFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubApplicaFiltro.ShortcutKey = System.Windows.Forms.Keys.F5;
            this.ubApplicaFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubApplicaFiltro.Size = new System.Drawing.Size(238, 57);
            this.ubApplicaFiltro.TabIndex = 12;
            this.ubApplicaFiltro.Text = "Applica filtro";
            this.ubApplicaFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ubApplicaFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubApplicaFiltro.Click += new System.EventHandler(this.ubApplicaFiltro_Click);
                                                this.ucEasyTableLayoutPanelFiltroData.ColumnCount = 5;
            this.ucEasyTableLayoutPanelFiltri.SetColumnSpan(this.ucEasyTableLayoutPanelFiltroData, 3);
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.ucEasyTableLayoutPanelFiltroData.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.udteFiltroDA, 0, 1);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.lblFiltroDa, 0, 0);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.drFiltro, 4, 1);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.udteFiltroA, 2, 1);
            this.ucEasyTableLayoutPanelFiltroData.Controls.Add(this.lblFiltroA, 2, 0);
            this.ucEasyTableLayoutPanelFiltroData.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltroData.Location = new System.Drawing.Point(7, 468);
            this.ucEasyTableLayoutPanelFiltroData.Name = "ucEasyTableLayoutPanelFiltroData";
            this.ucEasyTableLayoutPanelFiltroData.RowCount = 2;
            this.ucEasyTableLayoutPanelFiltroData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.ucEasyTableLayoutPanelFiltroData.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.ucEasyTableLayoutPanelFiltroData.Size = new System.Drawing.Size(473, 72);
            this.ucEasyTableLayoutPanelFiltroData.TabIndex = 11;
                                                appearance8.FontData.SizeInPoints = 22.50746F;
            this.udteFiltroDA.Appearance = appearance8;
            this.udteFiltroDA.AutoSize = false;
            this.udteFiltroDA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroDA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroDA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance9.FontData.SizeInPoints = 22.50746F;
            this.udteFiltroDA.DropDownAppearance = appearance9;
            this.udteFiltroDA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroDA.Location = new System.Drawing.Point(3, 31);
            this.udteFiltroDA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroDA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroDA.Name = "udteFiltroDA";
            this.udteFiltroDA.Size = new System.Drawing.Size(135, 38);
            this.udteFiltroDA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroDA.TabIndex = 1;
            this.udteFiltroDA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.udteFiltroDA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance10.FontData.SizeInPoints = 22.50746F;
            appearance10.TextVAlignAsString = "Middle";
            this.lblFiltroDa.Appearance = appearance10;
            this.lblFiltroDa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroDa.Location = new System.Drawing.Point(3, 3);
            this.lblFiltroDa.Name = "lblFiltroDa";
            this.lblFiltroDa.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroDa.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroDa.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroDa.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroDa.Size = new System.Drawing.Size(135, 22);
            this.lblFiltroDa.TabIndex = 2;
            this.lblFiltroDa.Text = "DA:";
            this.lblFiltroDa.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                appearance11.FontData.SizeInPoints = 22.50746F;
            this.drFiltro.Appearance = appearance11;
            this.drFiltro.AutoSize = false;
            this.drFiltro.DataEpisodio = new System.DateTime(((long)(0)));
            this.drFiltro.DateFuture = false;
            this.drFiltro.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.drFiltro.DisponibilitaAgende = false;
            this.drFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.drFiltro.Domani = false;
            this.drFiltro.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem1.DisplayText = " ";
            valueListItem2.DataValue = "24H";
            valueListItem2.DisplayText = "Ultime 24h";
            valueListItem3.DataValue = "48H";
            valueListItem3.DisplayText = "Ultime 48h";
            valueListItem4.DataValue = "7G";
            valueListItem4.DisplayText = "Ultimi 7gg";
            valueListItem5.DataValue = "30G";
            valueListItem5.DisplayText = "Ultimi 30gg";
            valueListItem6.DataValue = "60G";
            valueListItem6.DisplayText = "Ultimi 60gg";
            valueListItem7.DataValue = "90G";
            valueListItem7.DisplayText = "Ultimi 90gg";
            valueListItem8.DataValue = "6M";
            valueListItem8.DisplayText = "Ultimi 6 mesi";
            this.drFiltro.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2,
            valueListItem3,
            valueListItem4,
            valueListItem5,
            valueListItem6,
            valueListItem7,
            valueListItem8});
            this.drFiltro.Location = new System.Drawing.Point(331, 31);
            this.drFiltro.Name = "drFiltro";
            this.drFiltro.PassatoRemoto = false;
            this.drFiltro.Size = new System.Drawing.Size(139, 38);
            this.drFiltro.TabIndex = 0;
            this.drFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.drFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.drFiltro.ValueChanged += new System.EventHandler(this.drFiltro_ValueChanged);
                                                appearance12.FontData.SizeInPoints = 22.50746F;
            this.udteFiltroA.Appearance = appearance12;
            this.udteFiltroA.AutoSize = false;
            this.udteFiltroA.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.udteFiltroA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance13.FontData.SizeInPoints = 22.50746F;
            this.udteFiltroA.DropDownAppearance = appearance13;
            this.udteFiltroA.FormatString = "dd/MM/yyyy HH:mm";
            this.udteFiltroA.Location = new System.Drawing.Point(167, 31);
            this.udteFiltroA.MaskInput = "{LOC}dd/mm/yyyy hh:mm";
            this.udteFiltroA.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.udteFiltroA.Name = "udteFiltroA";
            this.udteFiltroA.Size = new System.Drawing.Size(135, 38);
            this.udteFiltroA.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteFiltroA.TabIndex = 2;
            this.udteFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.udteFiltroA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance14.FontData.SizeInPoints = 22.50746F;
            appearance14.TextVAlignAsString = "Middle";
            this.lblFiltroA.Appearance = appearance14;
            this.lblFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFiltroA.Location = new System.Drawing.Point(167, 3);
            this.lblFiltroA.Name = "lblFiltroA";
            this.lblFiltroA.ShortcutColor = System.Drawing.Color.Black;
            this.lblFiltroA.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblFiltroA.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblFiltroA.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblFiltroA.Size = new System.Drawing.Size(135, 22);
            this.lblFiltroA.TabIndex = 2;
            this.lblFiltroA.Text = "A:";
            this.lblFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
                                                this.ucEasyGridFiltroStato.ColonnaRTFControlloContenuto = false;
            this.ucEasyGridFiltroStato.ColonnaRTFResize = "";
            this.ucEasyGridFiltroStato.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance15.BackColor = System.Drawing.SystemColors.Window;
            appearance15.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGridFiltroStato.DisplayLayout.Appearance = appearance15;
            this.ucEasyGridFiltroStato.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGridFiltroStato.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance16.FontData.BoldAsString = "True";
            appearance16.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionAppearance = appearance16;
            this.ucEasyGridFiltroStato.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance17.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance17.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance17.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance17.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Appearance = appearance17;
            appearance18.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BandLabelAppearance = appearance18;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance19.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance19.BackColor2 = System.Drawing.SystemColors.Control;
            appearance19.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance19.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGridFiltroStato.DisplayLayout.GroupByBox.PromptAppearance = appearance19;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGridFiltroStato.DisplayLayout.MaxRowScrollRegions = 1;
            appearance20.BackColor = System.Drawing.SystemColors.Window;
            appearance20.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveCellAppearance = appearance20;
            appearance21.BackColor = System.Drawing.SystemColors.Highlight;
            appearance21.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ActiveRowAppearance = appearance21;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance22.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CardAreaAppearance = appearance22;
            appearance23.BorderColor = System.Drawing.Color.Silver;
            appearance23.FontData.SizeInPoints = 15.58209F;
            appearance23.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellAppearance = appearance23;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance24.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.FilterRowAppearance = appearance24;
            appearance25.BackColor = System.Drawing.SystemColors.Control;
            appearance25.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance25.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance25.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance25.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.GroupByRowAppearance = appearance25;
            appearance26.FontData.BoldAsString = "True";
            appearance26.FontData.SizeInPoints = 15.58209F;
            appearance26.TextHAlignAsString = "Center";
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderAppearance = appearance26;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance27.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance27.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAlternateAppearance = appearance27;
            appearance28.BackColor = System.Drawing.SystemColors.Window;
            appearance28.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowAppearance = appearance28;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance29.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGridFiltroStato.DisplayLayout.Override.TemplateAddRowAppearance = appearance29;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGridFiltroStato.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGridFiltroStato.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGridFiltroStato.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGridFiltroStato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGridFiltroStato.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGridFiltroStato.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridFiltroStato.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGridFiltroStato.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGridFiltroStato.Location = new System.Drawing.Point(251, 3);
            this.ucEasyGridFiltroStato.Name = "ucEasyGridFiltroStato";
            this.ucEasyGridFiltroStato.ShowFilterRow = false;
            this.ucEasyGridFiltroStato.ShowGroupByBox = false;
            this.ucEasyGridFiltroStato.Size = new System.Drawing.Size(229, 145);
            this.ucEasyGridFiltroStato.TabIndex = 10;
            this.ucEasyGridFiltroStato.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGridFiltroStato.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGridFiltroStato.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGridFiltroStato_InitializeLayout);
                                                this.ultraGroupBox.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(855, 624);
            this.ultraGroupBox.TabIndex = 0;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyTableLayoutPanel.ColumnCount = 5;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 88F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyGrid, 1, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyTableLayoutPulsanti, 3, 1);
            this.ucEasyTableLayoutPanel.Controls.Add(this.ucEasyPopUpOrario, 3, 2);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 3;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 98F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 1F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(849, 618);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.ucEasyGrid.ColonnaRTFControlloContenuto = false;
            this.ucEasyGrid.ColonnaRTFResize = "";
            this.ucEasyGrid.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance30.BackColor = System.Drawing.SystemColors.Window;
            appearance30.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ucEasyGrid.DisplayLayout.Appearance = appearance30;
            this.ucEasyGrid.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ucEasyGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance31.FontData.BoldAsString = "True";
            appearance31.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGrid.DisplayLayout.CaptionAppearance = appearance31;
            this.ucEasyGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance32.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance32.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance32.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance32.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Appearance = appearance32;
            appearance33.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance33;
            this.ucEasyGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Hidden = true;
            this.ucEasyGrid.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance34.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance34.BackColor2 = System.Drawing.SystemColors.Control;
            appearance34.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance34.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ucEasyGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance34;
            this.ucEasyGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.ucEasyGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance35.BackColor = System.Drawing.SystemColors.Window;
            appearance35.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveCellAppearance = appearance35;
            appearance36.BackColor = System.Drawing.SystemColors.Highlight;
            appearance36.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ucEasyGrid.DisplayLayout.Override.ActiveRowAppearance = appearance36;
            this.ucEasyGrid.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ucEasyGrid.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ucEasyGrid.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ucEasyGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance37.BackColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.CardAreaAppearance = appearance37;
            appearance38.BorderColor = System.Drawing.Color.Silver;
            appearance38.FontData.SizeInPoints = 15.58209F;
            appearance38.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ucEasyGrid.DisplayLayout.Override.CellAppearance = appearance38;
            this.ucEasyGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ucEasyGrid.DisplayLayout.Override.CellPadding = 0;
            this.ucEasyGrid.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance39.FontData.SizeInPoints = 22.50746F;
            this.ucEasyGrid.DisplayLayout.Override.FilterRowAppearance = appearance39;
            appearance40.BackColor = System.Drawing.SystemColors.Control;
            appearance40.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance40.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance40.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance40.BorderColor = System.Drawing.SystemColors.Window;
            this.ucEasyGrid.DisplayLayout.Override.GroupByRowAppearance = appearance40;
            appearance41.FontData.BoldAsString = "True";
            appearance41.FontData.SizeInPoints = 15.58209F;
            appearance41.TextHAlignAsString = "Center";
            this.ucEasyGrid.DisplayLayout.Override.HeaderAppearance = appearance41;
            this.ucEasyGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ucEasyGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance42.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance42.ForeColor = System.Drawing.Color.DarkBlue;
            this.ucEasyGrid.DisplayLayout.Override.RowAlternateAppearance = appearance42;
            appearance43.BackColor = System.Drawing.SystemColors.Window;
            appearance43.BorderColor = System.Drawing.Color.Silver;
            this.ucEasyGrid.DisplayLayout.Override.RowAppearance = appearance43;
            this.ucEasyGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ucEasyGrid.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance44.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ucEasyGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance44;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ucEasyGrid.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.ucEasyGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ucEasyGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ucEasyGrid.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ucEasyGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ucEasyGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyGrid.FattoreRidimensionamentoRTF = 21;
            this.ucEasyGrid.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyGrid.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ucEasyGrid.Location = new System.Drawing.Point(11, 9);
            this.ucEasyGrid.Name = "ucEasyGrid";
            this.ucEasyGrid.ShowFilterRow = false;
            this.ucEasyGrid.ShowGroupByBox = false;
            this.ucEasyGrid.Size = new System.Drawing.Size(741, 599);
            this.ucEasyGrid.TabIndex = 0;
            this.ucEasyGrid.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ucEasyGrid.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucEasyGrid_InitializeLayout);
            this.ucEasyGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucEasyGrid_InitializeRow);
            this.ucEasyGrid.AfterRowActivate += new System.EventHandler(this.ucEasyGrid_AfterRowActivate);
            this.ucEasyGrid.ClickCellButton += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.ucEasyGrid_ClickCellButton);
            this.ucEasyGrid.AfterSelectChange += new Infragistics.Win.UltraWinGrid.AfterSelectChangeEventHandler(this.ucEasyGrid_AfterSelectChange);
            this.ucEasyGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ucEasyGrid_ClickCell);
                                                this.ucEasyTableLayoutPulsanti.ColumnCount = 1;
            this.ucEasyTableLayoutPulsanti.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.ubSpostaTask, 0, 4);
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.ubAdmin, 0, 6);
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.ubAdd, 0, 0);
            this.ucEasyTableLayoutPulsanti.Controls.Add(this.uchkFiltro, 0, 2);
            this.ucEasyTableLayoutPulsanti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPulsanti.Location = new System.Drawing.Point(766, 9);
            this.ucEasyTableLayoutPulsanti.Name = "ucEasyTableLayoutPulsanti";
            this.ucEasyTableLayoutPulsanti.RowCount = 8;
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 17F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 17F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 17F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 6F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 17F));
            this.ucEasyTableLayoutPulsanti.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14F));
            this.ucEasyTableLayoutPulsanti.Size = new System.Drawing.Size(70, 599);
            this.ucEasyTableLayoutPulsanti.TabIndex = 4;
                                                appearance45.FontData.SizeInPoints = 15.58209F;
            appearance45.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance45.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance45.TextHAlignAsString = "Center";
            appearance45.TextVAlignAsString = "Bottom";
            this.ubSpostaTask.Appearance = appearance45;
            this.ubSpostaTask.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubSpostaTask.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubSpostaTask.Location = new System.Drawing.Point(3, 275);
            this.ubSpostaTask.Name = "ubSpostaTask";
            this.ubSpostaTask.PercImageFill = 0.75F;
            this.ubSpostaTask.ShortcutColor = System.Drawing.Color.Black;
            this.ubSpostaTask.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubSpostaTask.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubSpostaTask.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubSpostaTask.Size = new System.Drawing.Size(64, 95);
            this.ubSpostaTask.TabIndex = 2;
            this.ubSpostaTask.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubSpostaTask.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubSpostaTask.Click += new System.EventHandler(this.ubSpostaTask_Click);
                                                appearance46.FontData.SizeInPoints = 15.58209F;
            appearance46.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance46.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance46.TextHAlignAsString = "Center";
            appearance46.TextVAlignAsString = "Bottom";
            this.ubAdmin.Appearance = appearance46;
            this.ubAdmin.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAdmin.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAdmin.Location = new System.Drawing.Point(3, 411);
            this.ubAdmin.Name = "ubAdmin";
            this.ubAdmin.PercImageFill = 0.75F;
            this.ubAdmin.ShortcutColor = System.Drawing.Color.Black;
            this.ubAdmin.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubAdmin.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAdmin.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAdmin.Size = new System.Drawing.Size(64, 95);
            this.ubAdmin.TabIndex = 3;
            this.ubAdmin.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAdmin.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAdmin.Click += new System.EventHandler(this.ubAdmin_Click);
                                                appearance47.FontData.SizeInPoints = 15.58209F;
            appearance47.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance47.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance47.TextHAlignAsString = "Center";
            appearance47.TextVAlignAsString = "Bottom";
            this.ubAdd.Appearance = appearance47;
            this.ubAdd.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubAdd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAdd.Location = new System.Drawing.Point(3, 3);
            this.ubAdd.Name = "ubAdd";
            this.ubAdd.PercImageFill = 0.75F;
            this.ubAdd.ShortcutColor = System.Drawing.Color.Black;
            this.ubAdd.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ubAdd.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubAdd.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAdd.Size = new System.Drawing.Size(64, 95);
            this.ubAdd.TabIndex = 0;
            this.ubAdd.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAdd.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAdd.Click += new System.EventHandler(this.ubAdd_Click);
                                                appearance48.FontData.SizeInPoints = 15.58209F;
            appearance48.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance48.ImageBackground")));
            appearance48.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance48.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance48.TextHAlignAsString = "Center";
            appearance48.TextVAlignAsString = "Bottom";
            this.uchkFiltro.Appearance = appearance48;
            this.uchkFiltro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.uchkFiltro.Checked = false;
            this.uchkFiltro.CheckedImage = null;
            this.uchkFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uchkFiltro.Location = new System.Drawing.Point(3, 139);
            this.uchkFiltro.Name = "uchkFiltro";
            this.uchkFiltro.PercImageFill = 0.75F;
            this.uchkFiltro.ShortcutColor = System.Drawing.Color.Black;
            this.uchkFiltro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.uchkFiltro.ShortcutKey = System.Windows.Forms.Keys.F;
            this.uchkFiltro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.uchkFiltro.Size = new System.Drawing.Size(64, 95);
            this.uchkFiltro.TabIndex = 1;
            this.uchkFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.uchkFiltro.UNCheckedImage = null;
            this.uchkFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.uchkFiltro.Click += new System.EventHandler(this.uchkFiltro_Click);
                                                this.ucEasyPopUpOrario.BackColor = System.Drawing.Color.Transparent;
            this.ucEasyPopUpOrario.DataOra = new System.DateTime(2013, 9, 23, 0, 0, 0, 0);
            this.ucEasyPopUpOrario.DataOraDimensioneFont = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ucEasyPopUpOrario.Location = new System.Drawing.Point(766, 614);
            this.ucEasyPopUpOrario.Name = "ucEasyPopUpOrario";
            this.ucEasyPopUpOrario.Note = "";
            this.ucEasyPopUpOrario.Size = new System.Drawing.Size(34, 1);
            this.ucEasyPopUpOrario.TabIndex = 5;
            this.ucEasyPopUpOrario.TestoEtichetta = "Data Ora:";
            this.ucEasyPopUpOrario.TestoEtichettaDimensioneFont = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Medium;
            this.ucEasyPopUpOrario.TestoTextBox = "";
            this.ucEasyPopUpOrario.Visible = false;
            this.ucEasyPopUpOrario.ConfermaClick += new System.EventHandler(this.ucEasyPopUpOrario_ConfermaClick);
            this.ucEasyPopUpOrario.AnnullaClick += new System.EventHandler(this.ucEasyPopUpOrario_AnnullaClick);
                                                this.ultraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.ultraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.ultraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.ultraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockAreaPane1.ChildPaneStyle = Infragistics.Win.UltraWinDock.ChildPaneStyle.VerticalSplit;
            dockableControlPane1.Control = this.pnlFiltro;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(490, -1);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(864, 416, 5, 100);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Settings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Settings.ShowCaption = Infragistics.Win.DefaultableBoolean.True;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "FILTRO";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(414, 624);
            this.ultraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.ultraDockManager.HostControl = this;
            this.ultraDockManager.ShowCloseButton = false;
            this.ultraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.ultraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ultraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.ultraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.ultraDockManager_InitializePane);
                                                this._ucWorkListInfermieristicaUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._ucWorkListInfermieristicaUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucWorkListInfermieristicaUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._ucWorkListInfermieristicaUnpinnedTabAreaLeft.Name = "_ucWorkListInfermieristicaUnpinnedTabAreaLeft";
            this._ucWorkListInfermieristicaUnpinnedTabAreaLeft.Owner = this.ultraDockManager;
            this._ucWorkListInfermieristicaUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 624);
            this._ucWorkListInfermieristicaUnpinnedTabAreaLeft.TabIndex = 10;
                                                this._ucWorkListInfermieristicaUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._ucWorkListInfermieristicaUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucWorkListInfermieristicaUnpinnedTabAreaRight.Location = new System.Drawing.Point(855, 0);
            this._ucWorkListInfermieristicaUnpinnedTabAreaRight.Name = "_ucWorkListInfermieristicaUnpinnedTabAreaRight";
            this._ucWorkListInfermieristicaUnpinnedTabAreaRight.Owner = this.ultraDockManager;
            this._ucWorkListInfermieristicaUnpinnedTabAreaRight.Size = new System.Drawing.Size(23, 624);
            this._ucWorkListInfermieristicaUnpinnedTabAreaRight.TabIndex = 11;
                                                this._ucWorkListInfermieristicaUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._ucWorkListInfermieristicaUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucWorkListInfermieristicaUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._ucWorkListInfermieristicaUnpinnedTabAreaTop.Name = "_ucWorkListInfermieristicaUnpinnedTabAreaTop";
            this._ucWorkListInfermieristicaUnpinnedTabAreaTop.Owner = this.ultraDockManager;
            this._ucWorkListInfermieristicaUnpinnedTabAreaTop.Size = new System.Drawing.Size(855, 0);
            this._ucWorkListInfermieristicaUnpinnedTabAreaTop.TabIndex = 12;
                                                this._ucWorkListInfermieristicaUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._ucWorkListInfermieristicaUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucWorkListInfermieristicaUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 624);
            this._ucWorkListInfermieristicaUnpinnedTabAreaBottom.Name = "_ucWorkListInfermieristicaUnpinnedTabAreaBottom";
            this._ucWorkListInfermieristicaUnpinnedTabAreaBottom.Owner = this.ultraDockManager;
            this._ucWorkListInfermieristicaUnpinnedTabAreaBottom.Size = new System.Drawing.Size(855, 0);
            this._ucWorkListInfermieristicaUnpinnedTabAreaBottom.TabIndex = 13;
                                                this._ucWorkListInfermieristicaAutoHideControl.Controls.Add(this.dockableWindow1);
            this._ucWorkListInfermieristicaAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucWorkListInfermieristicaAutoHideControl.Location = new System.Drawing.Point(800, 0);
            this._ucWorkListInfermieristicaAutoHideControl.Name = "_ucWorkListInfermieristicaAutoHideControl";
            this._ucWorkListInfermieristicaAutoHideControl.Owner = this.ultraDockManager;
            this._ucWorkListInfermieristicaAutoHideControl.Size = new System.Drawing.Size(55, 624);
            this._ucWorkListInfermieristicaAutoHideControl.TabIndex = 14;
                                                this.dockableWindow1.Controls.Add(this.pnlFiltro);
            this.dockableWindow1.Location = new System.Drawing.Point(-10000, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.ultraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(490, 624);
            this.dockableWindow1.TabIndex = 16;
                                                this.ultraToolTipManager1.ContainingControl = this;
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.ultraPopupControlContainerOra.Opening += new System.ComponentModel.CancelEventHandler(this.ultraPopupControlContainerOra_Opening);
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Right;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(436, 0);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.ultraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(419, 624);
            this.windowDockingArea1.TabIndex = 15;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._ucWorkListInfermieristicaAutoHideControl);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._ucWorkListInfermieristicaUnpinnedTabAreaTop);
            this.Controls.Add(this._ucWorkListInfermieristicaUnpinnedTabAreaBottom);
            this.Controls.Add(this._ucWorkListInfermieristicaUnpinnedTabAreaLeft);
            this.Controls.Add(this._ucWorkListInfermieristicaUnpinnedTabAreaRight);
            this.Name = "ucWorkListInfermieristica";
            this.Size = new System.Drawing.Size(878, 624);
            this.Enter += new System.EventHandler(this.ucWorkListInfermieristica_Enter);
            this.pnlFiltro.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFiltri.ResumeLayout(false);
            this.ucEasyTableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.utxtFiltroContenuto)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewTipo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewVie)).EndInit();
            this.ucEasyTableLayoutPanelFiltroData.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGridFiltroStato)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyGrid)).EndInit();
            this.ucEasyTableLayoutPulsanti.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ultraDockManager)).EndInit();
            this._ucWorkListInfermieristicaAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyButton ubAdd;
        private ucEasyGrid ucEasyGrid;
        private ucEasyStateButton uchkFiltro;
        private Infragistics.Win.UltraWinDock.UltraDockManager ultraDockManager;
        private Infragistics.Win.UltraWinDock.AutoHideControl _ucWorkListInfermieristicaAutoHideControl;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucWorkListInfermieristicaUnpinnedTabAreaBottom;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucWorkListInfermieristicaUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucWorkListInfermieristicaUnpinnedTabAreaRight;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucWorkListInfermieristicaUnpinnedTabAreaLeft;
        private System.Windows.Forms.Panel pnlFiltro;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltri;
        private ucEasyGrid ucEasyGridFiltroStato;
        private ucEasyButton ubApplicaFiltro;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltroData;
        private ucEasyDateTimeEditor udteFiltroDA;
        private ucEasyLabel lblFiltroDa;
        private ucEasyDateRange drFiltro;
        private ucEasyDateTimeEditor udteFiltroA;
        private ucEasyLabel lblFiltroA;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPulsanti;
        private Infragistics.Win.UltraWinToolTip.UltraToolTipManager ultraToolTipManager1;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
        private ucEasyPopUpOrario ucEasyPopUpOrario;
        private Infragistics.Win.Misc.UltraPopupControlContainer ultraPopupControlContainerOra;
        private ucEasyButton ubAdmin;
        private ucEasyTreeView ucEasyTreeViewVie;
        private ucEasyButton ubSpostaTask;
        private ucEasyTreeView ucEasyTreeViewTipo;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel1;
        private ucEasyLabel lblFiltroContenuto;
        private ucEasyTextBox utxtFiltroContenuto;
    }
}
