//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSCCI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sac.asmn.net/ws/pazienti.asmx")]
        public string WsSCCI_net_asmn_sac_Pazienti {
            get {
                return ((string)(this["WsSCCI_net_asmn_sac_Pazienti"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dwh-clinico.asmn.net/Ws2/DataAccessTdsV2.asmx")]
        public string WsSCCI_net_asmn_dwhclinico_DataAccessTdsV2 {
            get {
                return ((string)(this["WsSCCI_net_asmn_dwhclinico_DataAccessTdsV2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws-di-dwh.asmn.net/WS-DI-DWH-2/DataAccessV2.asmx")]
        public string WsSCCI_net_asmn_dwhclinicolab_DataAccessV2 {
            get {
                return ((string)(this["WsSCCI_net_asmn_dwhclinicolab_DataAccessV2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ws-di-sac.asmn.net/ws-di-sac-2/consensi.asmx")]
        public string WsSCCI_net_asmn_sacconsensi_Consensi {
            get {
                return ((string)(this["WsSCCI_net_asmn_sacconsensi_Consensi"]));
            }
        }
    }
}
