-- Script di insert tabella: T_SistemiErog
INSERT INTO [T_SistemiErog] ([Codice],[Descrizione])  VALUES('DWH','Data Warehouse')
INSERT INTO [T_SistemiErog] ([Codice],[Descrizione])  VALUES('OE','Order Entry')
INSERT INTO [T_SistemiErog] ([Codice],[Descrizione])  VALUES('SAC','Sac')
INSERT INTO [T_SistemiErog] ([Codice],[Descrizione])  VALUES('SCCI','Cartella Clinica')
INSERT INTO [T_SistemiErog] ([Codice],[Descrizione])  VALUES('SCCIExt','Cartella Clinica : Integrazioni')


-- Script di insert tabella: T_Eventi
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('DWHADT001','Notifica ADT',1,'DWH')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('DWHADT002','Spostamento entità doppia LA',1,'DWH')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('DWHALA001','Notifiche Alert (ALA)',1,'DWH')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('DWHRef001','Notifica Referti',1,'DWH')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('DWHRef002','Notifica Atti SaleOperatori',1,'DWH')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('DWHRef003','Notifica Referti Fenix',1,'DWH')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('OE001','Order Entry, variazioni stato OSU',1,'OE')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('OE002','Order Entry, Richiesta',1,'OE')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('SAC01','Notifiche SAC',1,'SAC')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciAGE01','Nuova Appuntamento in Agenda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciAGE02','Modifica Appuntamento in Agenda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciAGE03','Annulla Appuntamento in Agenda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciAGE04','Cancella Appuntamento in Agenda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALA01','Nuova Alert Allergie Anamnesi',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALA02','Modifica Alert Allergie Anamnesi',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALA03','Annulla Alert Allergie Anamnesi',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALA04','Visualizza Alert Allergie Anamnesi',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALA05','Cancella Alert Allergie Anamnesi',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALA06','Cancella Alert Generico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALG01','Nuova Alert Generico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALG02','Modifica Alert Generico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALG03','Annulla Alert Generico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALG04','Visualizza Alert Generico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALG05','Valida Alert Generico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALL01','Nuova Allegato',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALL02','Modifica Allegato',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALL03','Annulla Allegato',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALL04','Cancella AppAllegatountamento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALS01','Nuovo Allegato Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALS02','Modifica Allegato Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciALS03','Cancella Allegato Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciANA01','Nuovo Paziente (Angrafica)',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciANA02','Modifica Paziente (Anagrafica)',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciANA03','Cancella Paziente (Anagrafica)',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciAPP01','Nuova Appuntamento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciAPP02','Modifica Appuntamento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciAPP03','Annulla Appuntamento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciAPP04','Cancella Appuntamento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAC01','Apri Cartella Ambulatoriale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAC02','Chiudi Cartella Ambulatoriale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAC03','Modifica Cartella Ambulatoriale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAC04','Cancella Cartella Ambulatoriale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAR01','Apri Cartella',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAR02','Chiudi Cartella',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAR03','Modifica Cartella',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAR04','Cancella Cartella',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAR05','Collega Cartelle',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCAR06','Copia Cartella',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCIV01','Inserisci Cartella In Visione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCIV02','Modifica Cartella In Visione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCIV03','Cancella Cartella In Visione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCNS01','Inserisci Consenso',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCNS02','Modifica Consenso',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSG01','Inserisci Consegna',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSG02','Modifica Consegna',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSG03','Cancella Consegna',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSG04','Annulla Consegna',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSP01','Inserisci Consegna Paziente',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSP02','Modifica Consegna Paziente',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSP03','Cancella Consegna Paziente',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSP04','Annulla Consegna Paziente',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSR01','Inserisci Consegna Pazienti Ruoli',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSR02','Modifica Consegna Pazienti Ruoli',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSR03','Cancella Consegna Pazienti Ruoli',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSR04','Annulla Consegna Pazienti Ruoli',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciCSR05','Visto Consegna Pazienti Ruoli',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciDCF01','Nuovo Documento Firmato',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciDCL01','Nuova Voce Diario Clinico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciDCL02','Modifica Voce Diario Clinicio',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciDCL03','Annulla Voce Diario Clinico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciDCL04','Valida Voce Diario Clinico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciDCL05','Cancella Voce Diario Clinico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEPI01','Nuovo Episodio',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEPI02','Modifica Episodio',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEPI03','Annulla Episodio',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEPI04','Cancella Episodio',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEVC01','Nuova Evidenza Cinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEVC02','Modifica Evidenza Cinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEVC03','Annulla Evidenza Cinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEVC04','Visualizza Evidenza Cinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEVC05','Valida Evidenza Clinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEVC06','Cancella Evidenza Clinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEVC07','Inserimento da Importazione, Evidenza Clinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciEXS01','Esportazione Schede su DWH',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('SCCIExtDCL01','Scrittura Diario Clinico',1,'SCCIExt')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('SCCIExtOE01','Scrittura Ordini OE',1,'SCCIExt')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('SCCIExtPVT01','Scrittura Parametro Vitale',1,'SCCIExt')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('SCCIExtWKI01','Scrittura Worklist',1,'SCCIExt')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLA01','Nuovo Matilde@Home Login Accesso',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLC01','Nuovo Matilde@Home Login Contatto',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLC02','Modifica Matilde@Home Login Contatto',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLC03','Cancella Matilde@Home Login Contatto',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLG01','Nuovo Matilde@Home Login',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLG02','Modifica Matilde@Home Login',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLG03','Cancella Matilde@Home Login',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLU01','Nuovo Matilde@Home Login UA',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLU02','Modifica Matilde@Home Login UA',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciHLU03','Cancella Matilde@Home Login UA',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANCE01','Modifica Configurazione CE',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANMOVTRAS02','Modifica Trasferimenti',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCH01','Nuova Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCH02','Modifica Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCH03','Cancella Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCHCOPIA02','Modifica Schede Copia',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCHPADRI02','Modifica Schede Padri',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCHRUOLIAZIONI02','Modifica Scheda Ruoli Azioni',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCHUAENTITA02','Modifica Scheda UA Entità',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCHVER01','Nuova Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCHVER02','Modifica Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANSCHVER03','Cancella Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANTIPOEVC01','Nuovo Tipo Evidenza Clinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANTIPOEVC02','Modifica Tipo Evidenza Clinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciMANTIPOEVC03','Cancella Tipo Evidenza Clinica',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNDB01','Normalizzazione Database per range di date',NULL,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNDB02','Normalizzazione Database per ID Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNTE01','Nuova Nota in Agenda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNTE02','Modifica Nota in Agenda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNTE03','Annulla Nota in Agenda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNTE04','Cancella Nota in Agenda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNTG01','Nuova Nota Generale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNTG02','Modifica Nota Generale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNTG03','Annulla Nota Generale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciNTG04','Cancella Nota Generale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciOE01','Nuova Richiesta OE',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciOE02','Modifica Richiesta OE',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciOE03','Cancella Richiesta OE',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciOE04','Inoltra Richiesta OE',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciOSU01','SCCI: Evento per OE richieste, OSU',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPAZ01','Nuovo Paziente (Movimento)',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPAZ02','Modifica Paziente (Movimento)',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPAZ03','Cancella Paziente (Movimento)',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPIV01','Inserisci Paziente In Visione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPIV02','Modifica Paziente In Visione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPIV03','Cancella Paziente In Visione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPRF01','Nuova Prescrizione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPRF02','Modifica Prescrizione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPRF03','Annulla Prescrizione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPRF04','Cancella Prescrizione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPRF05','Valida Prescrizione',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPRT01','Nuova Prescrizione Testata',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPRT02','Modifica Prescrizione Testata',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPRT03','Cancella Prescrizione Testata',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPVT01','Nuova Parametro Vitale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPVT02','Modifica Parametro Vitale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPVT03','Annulla Parametro Vitale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPVT04','Visualizza Parametro Vitale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPVT05','Cancella Parametro Vitale',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPZS01','Nuovo Paziente Seguito',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPZS02','Modifica Paziente Seguito',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciPZS03','Cancella Paziente Seguito',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciSCH01','Nuova Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciSCH02','Modifica Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciSCH03','Annulla Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciSCH04','Visualizza Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciSCH05','Valida Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciSCH06','Cancella Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciSCH07','Completa Task Infermieristico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciSCH08','Revisione Scheda',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciTRA01','Nuovo Trasferimento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciTRA02','Modifica Trasferimento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciTRA03','Annulla Trasferimento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciTRA04','Cancella Trasferimento',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciWKI01','Nuova Task Infermieristico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciWKI02','Modifica Task Infermieristico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciWKI03','Annulla Task Infermieristico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciWKI04','Trascritto Task Infermieristico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciWKI05','Valida Task Infermieristico',1,'SCCI')
INSERT INTO [T_Eventi] ([Codice],[Descrizione],[Attivo],[CodSistemaErog])  VALUES('ScciWKI06','Cancella Task Infermieristico',1,'SCCI')

