namespace UnicodeSrl.ScciManagement
{
    partial class frmConfigCE
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmConfigCE));
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.lblManuale = new System.Windows.Forms.Label();
            this.lblProdotto = new System.Windows.Forms.Label();
            this.lblFabbricatore = new System.Windows.Forms.Label();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.PicView = new System.Windows.Forms.PictureBox();
            this.frmConfigurazione_Fill_Panel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.UltraTabControl = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ubConferma = new Infragistics.Win.Misc.UltraButton();
            this.ubAnnulla = new Infragistics.Win.Misc.UltraButton();
            this._frmConfigurazione_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmConfigurazione_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmConfigurazione_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmConfigurazione_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.heDescrizioneFabbricatore = new UnicodeSrl.Framework.UI.Controls.UniHtmlEditor();
            this.ucPictureSelectLogoManuale = new UnicodeSrl.ScciCore.ucPictureSelect();
            this.ucPictureSelectLogoProdotto = new UnicodeSrl.ScciCore.ucPictureSelect();
            this.ucPictureSelectLogoFabbricatore = new UnicodeSrl.ScciCore.ucPictureSelect();
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this.heDescrizioneProdotto = new UnicodeSrl.Framework.UI.Controls.UniHtmlEditor();
            this.heDescrizioneManuale = new UnicodeSrl.Framework.UI.Controls.UniHtmlEditor();
            this.ultraTabPageControl1.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PicView)).BeginInit();
            this.frmConfigurazione_Fill_Panel.ClientArea.SuspendLayout();
            this.frmConfigurazione_Fill_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).BeginInit();
            this.UltraTabControl.SuspendLayout();
            this.ultraTabSharedControlsPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.heDescrizioneManuale);
            this.ultraTabPageControl1.Controls.Add(this.heDescrizioneProdotto);
            this.ultraTabPageControl1.Controls.Add(this.heDescrizioneFabbricatore);
            this.ultraTabPageControl1.Controls.Add(this.lblManuale);
            this.ultraTabPageControl1.Controls.Add(this.lblProdotto);
            this.ultraTabPageControl1.Controls.Add(this.ucPictureSelectLogoManuale);
            this.ultraTabPageControl1.Controls.Add(this.ucPictureSelectLogoProdotto);
            this.ultraTabPageControl1.Controls.Add(this.ucPictureSelectLogoFabbricatore);
            this.ultraTabPageControl1.Controls.Add(this.lblFabbricatore);
            this.ultraTabPageControl1.Controls.Add(this.TableLayoutPanel);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(982, 653);
                                                this.lblManuale.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblManuale.Location = new System.Drawing.Point(338, 408);
            this.lblManuale.Name = "lblManuale";
            this.lblManuale.Size = new System.Drawing.Size(630, 20);
            this.lblManuale.TabIndex = 14;
            this.lblManuale.Text = "Manuale";
            this.lblManuale.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                                                this.lblProdotto.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblProdotto.Location = new System.Drawing.Point(338, 210);
            this.lblProdotto.Name = "lblProdotto";
            this.lblProdotto.Size = new System.Drawing.Size(630, 20);
            this.lblProdotto.TabIndex = 12;
            this.lblProdotto.Text = "Prodotto";
            this.lblProdotto.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                                                this.lblFabbricatore.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFabbricatore.Location = new System.Drawing.Point(338, 12);
            this.lblFabbricatore.Name = "lblFabbricatore";
            this.lblFabbricatore.Size = new System.Drawing.Size(630, 20);
            this.lblFabbricatore.TabIndex = 1;
            this.lblFabbricatore.Text = "Fabbricatore";
            this.lblFabbricatore.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                                                this.TableLayoutPanel.ColumnCount = 1;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TableLayoutPanel.Controls.Add(this.PicView, 0, 1);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.TableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(134, 653);
            this.TableLayoutPanel.TabIndex = 0;
                                                this.PicView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PicView.Location = new System.Drawing.Point(3, 265);
            this.PicView.Name = "PicView";
            this.PicView.Size = new System.Drawing.Size(128, 122);
            this.PicView.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PicView.TabIndex = 0;
            this.PicView.TabStop = false;
                                                                                    this.frmConfigurazione_Fill_Panel.ClientArea.Controls.Add(this.UltraGroupBox);
            this.frmConfigurazione_Fill_Panel.Cursor = System.Windows.Forms.Cursors.Default;
            this.frmConfigurazione_Fill_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.frmConfigurazione_Fill_Panel.Location = new System.Drawing.Point(0, 0);
            this.frmConfigurazione_Fill_Panel.Name = "frmConfigurazione_Fill_Panel";
            this.frmConfigurazione_Fill_Panel.Size = new System.Drawing.Size(1008, 729);
            this.frmConfigurazione_Fill_Panel.TabIndex = 0;
                                                this.UltraGroupBox.Controls.Add(this.UltraTabControl);
            this.UltraGroupBox.Controls.Add(this.ubConferma);
            this.UltraGroupBox.Controls.Add(this.ubAnnulla);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(1008, 729);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.UltraTabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.UltraTabControl.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControl.Location = new System.Drawing.Point(12, 12);
            this.UltraTabControl.Name = "UltraTabControl";
            this.UltraTabControl.SharedControls.AddRange(new System.Windows.Forms.Control[] {
            this.TableLayoutPanel});
            this.UltraTabControl.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControl.Size = new System.Drawing.Size(984, 676);
            this.UltraTabControl.TabIndex = 0;
            ultraTab1.Key = "tab1";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "tab1";
            this.UltraTabControl.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1});
            this.UltraTabControl.TabStop = false;
            this.UltraTabControl.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Controls.Add(this.TableLayoutPanel);
            this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(982, 653);
                                                this.ubConferma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubConferma.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubConferma.Location = new System.Drawing.Point(921, 694);
            this.ubConferma.Name = "ubConferma";
            this.ubConferma.Size = new System.Drawing.Size(75, 23);
            this.ubConferma.TabIndex = 2;
            this.ubConferma.Text = "&Conferma";
            this.ubConferma.Click += new System.EventHandler(this.ubConferma_Click);
                                                this.ubAnnulla.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ubAnnulla.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubAnnulla.Location = new System.Drawing.Point(12, 694);
            this.ubAnnulla.Name = "ubAnnulla";
            this.ubAnnulla.Size = new System.Drawing.Size(75, 23);
            this.ubAnnulla.TabIndex = 1;
            this.ubAnnulla.Text = "&Annulla";
            this.ubAnnulla.Click += new System.EventHandler(this.ubAnnulla_Click);
                                                this._frmConfigurazione_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmConfigurazione_Toolbars_Dock_Area_Left.BackColor = System.Drawing.SystemColors.Control;
            this._frmConfigurazione_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmConfigurazione_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmConfigurazione_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._frmConfigurazione_Toolbars_Dock_Area_Left.Name = "_frmConfigurazione_Toolbars_Dock_Area_Left";
            this._frmConfigurazione_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 729);
            this._frmConfigurazione_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmConfigurazione_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmConfigurazione_Toolbars_Dock_Area_Right.BackColor = System.Drawing.SystemColors.Control;
            this._frmConfigurazione_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmConfigurazione_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmConfigurazione_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(1008, 0);
            this._frmConfigurazione_Toolbars_Dock_Area_Right.Name = "_frmConfigurazione_Toolbars_Dock_Area_Right";
            this._frmConfigurazione_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 729);
            this._frmConfigurazione_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmConfigurazione_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmConfigurazione_Toolbars_Dock_Area_Top.BackColor = System.Drawing.SystemColors.Control;
            this._frmConfigurazione_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmConfigurazione_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmConfigurazione_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmConfigurazione_Toolbars_Dock_Area_Top.Name = "_frmConfigurazione_Toolbars_Dock_Area_Top";
            this._frmConfigurazione_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(1008, 0);
            this._frmConfigurazione_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmConfigurazione_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmConfigurazione_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.SystemColors.Control;
            this._frmConfigurazione_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmConfigurazione_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmConfigurazione_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 729);
            this._frmConfigurazione_Toolbars_Dock_Area_Bottom.Name = "_frmConfigurazione_Toolbars_Dock_Area_Bottom";
            this._frmConfigurazione_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(1008, 0);
            this._frmConfigurazione_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this.heDescrizioneFabbricatore.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.heDescrizioneFabbricatore.BodyBackgroundColor = System.Drawing.Color.White;
            this.heDescrizioneFabbricatore.BodyHtml = null;
            this.heDescrizioneFabbricatore.BodyText = null;
            this.heDescrizioneFabbricatore.DocumentText = resources.GetString("heDescrizioneFabbricatore.DocumentText");
            this.heDescrizioneFabbricatore.EditorBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.heDescrizioneFabbricatore.EditorForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.heDescrizioneFabbricatore.FontSize = UnicodeSrl.Framework.UI.Struct.en_UniHtmlFontSize.Three;
            this.heDescrizioneFabbricatore.Html = null;
            this.heDescrizioneFabbricatore.Location = new System.Drawing.Point(338, 35);
            this.heDescrizioneFabbricatore.Name = "heDescrizioneFabbricatore";
            this.heDescrizioneFabbricatore.Size = new System.Drawing.Size(630, 169);
            this.heDescrizioneFabbricatore.TabIndex = 1;
                                                this.ucPictureSelectLogoManuale.BackColor = System.Drawing.Color.Transparent;
            this.ucPictureSelectLogoManuale.Location = new System.Drawing.Point(140, 408);
            this.ucPictureSelectLogoManuale.Name = "ucPictureSelectLogoManuale";
            this.ucPictureSelectLogoManuale.Size = new System.Drawing.Size(192, 192);
            this.ucPictureSelectLogoManuale.TabIndex = 4;
            this.ucPictureSelectLogoManuale.ViewCenterImage = false;
            this.ucPictureSelectLogoManuale.ViewCheckSquareImage = true;
            this.ucPictureSelectLogoManuale.ViewImage = null;
            this.ucPictureSelectLogoManuale.ViewOpenFileDialogFilter = "png files (*.png)|*.png";
            this.ucPictureSelectLogoManuale.ViewSaveFileDialogFilter = "png files (*.png)|*.png|jpg files (*.jpg)|*.jpg|bmp files (*.bmp)|*.bmp";
            this.ucPictureSelectLogoManuale.ViewShowAddImage = true;
            this.ucPictureSelectLogoManuale.ViewShowRemoveImage = true;
            this.ucPictureSelectLogoManuale.ViewShowSaveImage = true;
            this.ucPictureSelectLogoManuale.ViewShowToolbar = true;
            this.ucPictureSelectLogoManuale.ViewToolbarStyle = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
            this.ucPictureSelectLogoManuale.ViewUseLargeImages = false;
            this.ucPictureSelectLogoManuale.ViewZoomFactor = UnicodeSrl.Scci.Enums.enumZoomfactor.zf100;
                                                this.ucPictureSelectLogoProdotto.BackColor = System.Drawing.Color.Transparent;
            this.ucPictureSelectLogoProdotto.Location = new System.Drawing.Point(140, 210);
            this.ucPictureSelectLogoProdotto.Name = "ucPictureSelectLogoProdotto";
            this.ucPictureSelectLogoProdotto.Size = new System.Drawing.Size(192, 192);
            this.ucPictureSelectLogoProdotto.TabIndex = 2;
            this.ucPictureSelectLogoProdotto.ViewCenterImage = false;
            this.ucPictureSelectLogoProdotto.ViewCheckSquareImage = true;
            this.ucPictureSelectLogoProdotto.ViewImage = null;
            this.ucPictureSelectLogoProdotto.ViewOpenFileDialogFilter = "png files (*.png)|*.png";
            this.ucPictureSelectLogoProdotto.ViewSaveFileDialogFilter = "png files (*.png)|*.png|jpg files (*.jpg)|*.jpg|bmp files (*.bmp)|*.bmp";
            this.ucPictureSelectLogoProdotto.ViewShowAddImage = true;
            this.ucPictureSelectLogoProdotto.ViewShowRemoveImage = true;
            this.ucPictureSelectLogoProdotto.ViewShowSaveImage = true;
            this.ucPictureSelectLogoProdotto.ViewShowToolbar = true;
            this.ucPictureSelectLogoProdotto.ViewToolbarStyle = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
            this.ucPictureSelectLogoProdotto.ViewUseLargeImages = false;
            this.ucPictureSelectLogoProdotto.ViewZoomFactor = UnicodeSrl.Scci.Enums.enumZoomfactor.zf100;
                                                this.ucPictureSelectLogoFabbricatore.BackColor = System.Drawing.Color.Transparent;
            this.ucPictureSelectLogoFabbricatore.Location = new System.Drawing.Point(140, 12);
            this.ucPictureSelectLogoFabbricatore.Name = "ucPictureSelectLogoFabbricatore";
            this.ucPictureSelectLogoFabbricatore.Size = new System.Drawing.Size(192, 192);
            this.ucPictureSelectLogoFabbricatore.TabIndex = 0;
            this.ucPictureSelectLogoFabbricatore.ViewCenterImage = false;
            this.ucPictureSelectLogoFabbricatore.ViewCheckSquareImage = true;
            this.ucPictureSelectLogoFabbricatore.ViewImage = null;
            this.ucPictureSelectLogoFabbricatore.ViewOpenFileDialogFilter = "png files (*.png)|*.png";
            this.ucPictureSelectLogoFabbricatore.ViewSaveFileDialogFilter = "png files (*.png)|*.png|jpg files (*.jpg)|*.jpg|bmp files (*.bmp)|*.bmp";
            this.ucPictureSelectLogoFabbricatore.ViewShowAddImage = true;
            this.ucPictureSelectLogoFabbricatore.ViewShowRemoveImage = true;
            this.ucPictureSelectLogoFabbricatore.ViewShowSaveImage = true;
            this.ucPictureSelectLogoFabbricatore.ViewShowToolbar = true;
            this.ucPictureSelectLogoFabbricatore.ViewToolbarStyle = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
            this.ucPictureSelectLogoFabbricatore.ViewUseLargeImages = false;
            this.ucPictureSelectLogoFabbricatore.ViewZoomFactor = UnicodeSrl.Scci.Enums.enumZoomfactor.zf100;
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
                                                this.heDescrizioneProdotto.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.heDescrizioneProdotto.BodyBackgroundColor = System.Drawing.Color.White;
            this.heDescrizioneProdotto.BodyHtml = null;
            this.heDescrizioneProdotto.BodyText = null;
            this.heDescrizioneProdotto.DocumentText = resources.GetString("heDescrizioneProdotto.DocumentText");
            this.heDescrizioneProdotto.EditorBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.heDescrizioneProdotto.EditorForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.heDescrizioneProdotto.FontSize = UnicodeSrl.Framework.UI.Struct.en_UniHtmlFontSize.Three;
            this.heDescrizioneProdotto.Html = null;
            this.heDescrizioneProdotto.Location = new System.Drawing.Point(338, 233);
            this.heDescrizioneProdotto.Name = "heDescrizioneProdotto";
            this.heDescrizioneProdotto.Size = new System.Drawing.Size(630, 169);
            this.heDescrizioneProdotto.TabIndex = 3;
                                                this.heDescrizioneManuale.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.heDescrizioneManuale.BodyBackgroundColor = System.Drawing.Color.White;
            this.heDescrizioneManuale.BodyHtml = null;
            this.heDescrizioneManuale.BodyText = null;
            this.heDescrizioneManuale.DocumentText = resources.GetString("heDescrizioneManuale.DocumentText");
            this.heDescrizioneManuale.EditorBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.heDescrizioneManuale.EditorForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.heDescrizioneManuale.FontSize = UnicodeSrl.Framework.UI.Struct.en_UniHtmlFontSize.Three;
            this.heDescrizioneManuale.Html = null;
            this.heDescrizioneManuale.Location = new System.Drawing.Point(338, 431);
            this.heDescrizioneManuale.Name = "heDescrizioneManuale";
            this.heDescrizioneManuale.Size = new System.Drawing.Size(630, 169);
            this.heDescrizioneManuale.TabIndex = 5;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1008, 729);
            this.Controls.Add(this.frmConfigurazione_Fill_Panel);
            this.Controls.Add(this._frmConfigurazione_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmConfigurazione_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmConfigurazione_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmConfigurazione_Toolbars_Dock_Area_Top);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmConfigCE";
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmConfigurazione";
            this.Shown += new System.EventHandler(this.frmConfigCE_Shown);
            this.ultraTabPageControl1.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PicView)).EndInit();
            this.frmConfigurazione_Fill_Panel.ClientArea.ResumeLayout(false);
            this.frmConfigurazione_Fill_Panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).EndInit();
            this.UltraTabControl.ResumeLayout(false);
            this.ultraTabSharedControlsPage1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.Misc.UltraPanel frmConfigurazione_Fill_Panel;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmConfigurazione_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmConfigurazione_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmConfigurazione_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmConfigurazione_Toolbars_Dock_Area_Top;
        private Infragistics.Win.Misc.UltraButton ubConferma;
        private Infragistics.Win.Misc.UltraButton ubAnnulla;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControl;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        private System.Windows.Forms.Label lblFabbricatore;
        private System.Windows.Forms.PictureBox PicView;
        private ScciCore.ucPictureSelect ucPictureSelectLogoFabbricatore;
        private System.Windows.Forms.Label lblManuale;
        private System.Windows.Forms.Label lblProdotto;
        private ScciCore.ucPictureSelect ucPictureSelectLogoManuale;
        private ScciCore.ucPictureSelect ucPictureSelectLogoProdotto;
        private Framework.UI.Controls.UniHtmlEditor heDescrizioneFabbricatore;
        private Framework.UI.Controls.UniHtmlEditor heDescrizioneManuale;
        private Framework.UI.Controls.UniHtmlEditor heDescrizioneProdotto;
    }
}