namespace UnicodeSrl.ScciManagement
{
    partial class frmDocumentiFirmati
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.TableLayoutPanelEpi = new System.Windows.Forms.TableLayoutPanel();
            this.uceCodEntita = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.udteDataInserimentoF = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.lblDataInserimentoF = new System.Windows.Forms.Label();
            this.lblCodEntita = new System.Windows.Forms.Label();
            this.lblDataInserimentoI = new System.Windows.Forms.Label();
            this.ubRicerca = new Infragistics.Win.Misc.UltraButton();
            this.lblID = new System.Windows.Forms.Label();
            this.uteID = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.udteDataInserimentoI = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this._frmView_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmView_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmView_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmView_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.frmDocumentiFirmati_Fill_Panel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.PicImage = new System.Windows.Forms.PictureBox();
            this.TableLayoutPanelDX = new System.Windows.Forms.TableLayoutPanel();
            this.UltraTabControlFiltri = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.UltraGrid = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.SaveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.lblIDEntita = new System.Windows.Forms.Label();
            this.uteIDEntita = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.ultraTabPageControl1.SuspendLayout();
            this.TableLayoutPanelEpi.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uceCodEntita)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataInserimentoF)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteID)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataInserimentoI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.frmDocumentiFirmati_Fill_Panel.ClientArea.SuspendLayout();
            this.frmDocumentiFirmati_Fill_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).BeginInit();
            this.TableLayoutPanelDX.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControlFiltri)).BeginInit();
            this.UltraTabControlFiltri.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteIDEntita)).BeginInit();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.TableLayoutPanelEpi);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(604, 91);
                                                this.TableLayoutPanelEpi.ColumnCount = 5;
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 74F));
            this.TableLayoutPanelEpi.Controls.Add(this.uteIDEntita, 3, 2);
            this.TableLayoutPanelEpi.Controls.Add(this.lblIDEntita, 2, 2);
            this.TableLayoutPanelEpi.Controls.Add(this.uceCodEntita, 1, 2);
            this.TableLayoutPanelEpi.Controls.Add(this.udteDataInserimentoF, 3, 1);
            this.TableLayoutPanelEpi.Controls.Add(this.lblDataInserimentoF, 2, 1);
            this.TableLayoutPanelEpi.Controls.Add(this.lblCodEntita, 0, 2);
            this.TableLayoutPanelEpi.Controls.Add(this.lblDataInserimentoI, 0, 1);
            this.TableLayoutPanelEpi.Controls.Add(this.ubRicerca, 4, 0);
            this.TableLayoutPanelEpi.Controls.Add(this.lblID, 0, 0);
            this.TableLayoutPanelEpi.Controls.Add(this.uteID, 1, 0);
            this.TableLayoutPanelEpi.Controls.Add(this.udteDataInserimentoI, 1, 1);
            this.TableLayoutPanelEpi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelEpi.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanelEpi.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanelEpi.Name = "TableLayoutPanelEpi";
            this.TableLayoutPanelEpi.RowCount = 3;
            this.TableLayoutPanelEpi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.TableLayoutPanelEpi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.TableLayoutPanelEpi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.TableLayoutPanelEpi.Size = new System.Drawing.Size(604, 91);
            this.TableLayoutPanelEpi.TabIndex = 2;
                                                this.uceCodEntita.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.uceCodEntita.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uceCodEntita.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.uceCodEntita.Location = new System.Drawing.Point(109, 63);
            this.uceCodEntita.Name = "uceCodEntita";
            this.uceCodEntita.Size = new System.Drawing.Size(153, 22);
            this.uceCodEntita.TabIndex = 3;
                                                this.udteDataInserimentoF.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataInserimentoF.Dock = System.Windows.Forms.DockStyle.Fill;
            this.udteDataInserimentoF.Location = new System.Drawing.Point(374, 33);
            this.udteDataInserimentoF.MaskInput = "dd/mm/yyyy";
            this.udteDataInserimentoF.Name = "udteDataInserimentoF";
            this.udteDataInserimentoF.Size = new System.Drawing.Size(153, 22);
            this.udteDataInserimentoF.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataInserimentoF.TabIndex = 2;
                                                this.lblDataInserimentoF.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataInserimentoF.Location = new System.Drawing.Point(268, 30);
            this.lblDataInserimentoF.Name = "lblDataInserimentoF";
            this.lblDataInserimentoF.Size = new System.Drawing.Size(100, 30);
            this.lblDataInserimentoF.TabIndex = 8;
            this.lblDataInserimentoF.Text = "Dt. Inserimento F.";
            this.lblDataInserimentoF.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.lblCodEntita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCodEntita.Location = new System.Drawing.Point(3, 60);
            this.lblCodEntita.Name = "lblCodEntita";
            this.lblCodEntita.Size = new System.Drawing.Size(100, 31);
            this.lblCodEntita.TabIndex = 7;
            this.lblCodEntita.Text = "Codice Entità";
            this.lblCodEntita.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.lblDataInserimentoI.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataInserimentoI.Location = new System.Drawing.Point(3, 30);
            this.lblDataInserimentoI.Name = "lblDataInserimentoI";
            this.lblDataInserimentoI.Size = new System.Drawing.Size(100, 30);
            this.lblDataInserimentoI.TabIndex = 4;
            this.lblDataInserimentoI.Text = "Dt. Inserimento I.";
            this.lblDataInserimentoI.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.ubRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRicerca.Location = new System.Drawing.Point(533, 3);
            this.ubRicerca.Name = "ubRicerca";
            this.TableLayoutPanelEpi.SetRowSpan(this.ubRicerca, 3);
            this.ubRicerca.Size = new System.Drawing.Size(68, 85);
            this.ubRicerca.TabIndex = 4;
            this.ubRicerca.Text = "Ricerca";
            this.ubRicerca.Click += new System.EventHandler(this.ubRicerca_Click);
                                                this.lblID.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblID.Location = new System.Drawing.Point(3, 0);
            this.lblID.Name = "lblID";
            this.lblID.Size = new System.Drawing.Size(100, 30);
            this.lblID.TabIndex = 0;
            this.lblID.Text = "ID Documento";
            this.lblID.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.TableLayoutPanelEpi.SetColumnSpan(this.uteID, 3);
            this.uteID.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteID.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteID.Location = new System.Drawing.Point(109, 3);
            this.uteID.Name = "uteID";
            this.uteID.Size = new System.Drawing.Size(418, 22);
            this.uteID.TabIndex = 0;
                                                this.udteDataInserimentoI.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataInserimentoI.Dock = System.Windows.Forms.DockStyle.Fill;
            this.udteDataInserimentoI.Location = new System.Drawing.Point(109, 33);
            this.udteDataInserimentoI.MaskInput = "dd/mm/yyyy";
            this.udteDataInserimentoI.Name = "udteDataInserimentoI";
            this.udteDataInserimentoI.Size = new System.Drawing.Size(153, 22);
            this.udteDataInserimentoI.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataInserimentoI.TabIndex = 1;
                                                this._frmView_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmView_Toolbars_Dock_Area_Top.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmView_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmView_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmView_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmView_Toolbars_Dock_Area_Top.Name = "_frmView_Toolbars_Dock_Area_Top";
            this._frmView_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(768, 32);
            this._frmView_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
            this.UltraToolbarsManager.FormDisplayStyle = Infragistics.Win.UltraWinToolbars.FormDisplayStyle.RoundedSizable;
            this.UltraToolbarsManager.MdiMergeable = false;
            this.UltraToolbarsManager.RuntimeCustomizationOptions = Infragistics.Win.UltraWinToolbars.RuntimeCustomizationOptions.None;
            this.UltraToolbarsManager.ShowFullMenusDelay = 500;
            this.UltraToolbarsManager.Style = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
                                                this._frmView_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmView_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmView_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmView_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmView_Toolbars_Dock_Area_Bottom.InitialResizeAreaExtent = 8;
            this._frmView_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 515);
            this._frmView_Toolbars_Dock_Area_Bottom.Name = "_frmView_Toolbars_Dock_Area_Bottom";
            this._frmView_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(768, 8);
            this._frmView_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmView_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmView_Toolbars_Dock_Area_Left.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmView_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmView_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmView_Toolbars_Dock_Area_Left.InitialResizeAreaExtent = 8;
            this._frmView_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 32);
            this._frmView_Toolbars_Dock_Area_Left.Name = "_frmView_Toolbars_Dock_Area_Left";
            this._frmView_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(8, 483);
            this._frmView_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmView_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmView_Toolbars_Dock_Area_Right.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmView_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmView_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmView_Toolbars_Dock_Area_Right.InitialResizeAreaExtent = 8;
            this._frmView_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(760, 32);
            this._frmView_Toolbars_Dock_Area_Right.Name = "_frmView_Toolbars_Dock_Area_Right";
            this._frmView_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(8, 483);
            this._frmView_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                                                    this.frmDocumentiFirmati_Fill_Panel.ClientArea.Controls.Add(this.UltraGroupBox);
            this.frmDocumentiFirmati_Fill_Panel.Cursor = System.Windows.Forms.Cursors.Default;
            this.frmDocumentiFirmati_Fill_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.frmDocumentiFirmati_Fill_Panel.Location = new System.Drawing.Point(8, 32);
            this.frmDocumentiFirmati_Fill_Panel.Name = "frmDocumentiFirmati_Fill_Panel";
            this.frmDocumentiFirmati_Fill_Panel.Size = new System.Drawing.Size(752, 483);
            this.frmDocumentiFirmati_Fill_Panel.TabIndex = 0;
                                                this.UltraGroupBox.Controls.Add(this.TableLayoutPanel);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(752, 483);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.TableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanel.ColumnCount = 2;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 134F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.Controls.Add(this.PicImage, 0, 1);
            this.TableLayoutPanel.Controls.Add(this.TableLayoutPanelDX, 1, 0);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.TableLayoutPanel.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(746, 477);
            this.TableLayoutPanel.TabIndex = 0;
                                                this.PicImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PicImage.Location = new System.Drawing.Point(3, 177);
            this.PicImage.Name = "PicImage";
            this.PicImage.Size = new System.Drawing.Size(128, 122);
            this.PicImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PicImage.TabIndex = 0;
            this.PicImage.TabStop = false;
                                                this.TableLayoutPanelDX.ColumnCount = 1;
            this.TableLayoutPanelDX.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelDX.Controls.Add(this.UltraTabControlFiltri, 0, 0);
            this.TableLayoutPanelDX.Controls.Add(this.UltraGrid, 0, 1);
            this.TableLayoutPanelDX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelDX.Location = new System.Drawing.Point(134, 0);
            this.TableLayoutPanelDX.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanelDX.Name = "TableLayoutPanelDX";
            this.TableLayoutPanelDX.RowCount = 2;
            this.TableLayoutPanel.SetRowSpan(this.TableLayoutPanelDX, 3);
            this.TableLayoutPanelDX.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 120F));
            this.TableLayoutPanelDX.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelDX.Size = new System.Drawing.Size(612, 477);
            this.TableLayoutPanelDX.TabIndex = 0;
                                                this.UltraTabControlFiltri.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControlFiltri.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControlFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraTabControlFiltri.Location = new System.Drawing.Point(3, 3);
            this.UltraTabControlFiltri.Name = "UltraTabControlFiltri";
            this.UltraTabControlFiltri.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControlFiltri.Size = new System.Drawing.Size(606, 114);
            this.UltraTabControlFiltri.TabIndex = 0;
            ultraTab1.Key = "Documenti";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Documenti";
            this.UltraTabControlFiltri.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1});
            this.UltraTabControlFiltri.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(604, 91);
                                                appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGrid.DisplayLayout.Appearance = appearance1;
            this.UltraGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance2.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.GroupByBox.Appearance = appearance2;
            appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
            this.UltraGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance4.BackColor2 = System.Drawing.SystemColors.Control;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
            this.UltraGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGrid.DisplayLayout.Override.ActiveCellAppearance = appearance5;
            appearance6.BackColor = System.Drawing.SystemColors.Highlight;
            appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGrid.DisplayLayout.Override.ActiveRowAppearance = appearance6;
            this.UltraGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.Override.CardAreaAppearance = appearance7;
            appearance8.BorderColor = System.Drawing.Color.Silver;
            appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGrid.DisplayLayout.Override.CellAppearance = appearance8;
            this.UltraGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.UltraGrid.DisplayLayout.Override.CellPadding = 0;
            appearance9.BackColor = System.Drawing.SystemColors.Control;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.Override.GroupByRowAppearance = appearance9;
            appearance10.TextHAlignAsString = "Left";
            this.UltraGrid.DisplayLayout.Override.HeaderAppearance = appearance10;
            this.UltraGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.UltraGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            this.UltraGrid.DisplayLayout.Override.RowAppearance = appearance11;
            this.UltraGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance12.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance12;
            this.UltraGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGrid.Location = new System.Drawing.Point(3, 123);
            this.UltraGrid.Name = "UltraGrid";
            this.UltraGrid.Size = new System.Drawing.Size(606, 351);
            this.UltraGrid.TabIndex = 1;
            this.UltraGrid.DoubleClickCell += new Infragistics.Win.UltraWinGrid.DoubleClickCellEventHandler(this.UltraGrid_DoubleClickCell);
                                                this.lblIDEntita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblIDEntita.Location = new System.Drawing.Point(268, 60);
            this.lblIDEntita.Name = "lblIDEntita";
            this.lblIDEntita.Size = new System.Drawing.Size(100, 31);
            this.lblIDEntita.TabIndex = 9;
            this.lblIDEntita.Text = "ID Entità";
            this.lblIDEntita.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.uteIDEntita.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteIDEntita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteIDEntita.Location = new System.Drawing.Point(374, 63);
            this.uteIDEntita.Name = "uteIDEntita";
            this.uteIDEntita.Size = new System.Drawing.Size(153, 22);
            this.uteIDEntita.TabIndex = 4;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(768, 523);
            this.Controls.Add(this.frmDocumentiFirmati_Fill_Panel);
            this.Controls.Add(this._frmView_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmView_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmView_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmView_Toolbars_Dock_Area_Top);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "frmDocumentiFirmati";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmDocumentiFirmati";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmDocumentiFirmati_FormClosing);
            this.ultraTabPageControl1.ResumeLayout(false);
            this.TableLayoutPanelEpi.ResumeLayout(false);
            this.TableLayoutPanelEpi.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uceCodEntita)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataInserimentoF)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteID)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataInserimentoI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.frmDocumentiFirmati_Fill_Panel.ClientArea.ResumeLayout(false);
            this.frmDocumentiFirmati_Fill_Panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).EndInit();
            this.TableLayoutPanelDX.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControlFiltri)).EndInit();
            this.UltraTabControlFiltri.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGrid)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteIDEntita)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.Misc.UltraPanel frmDocumentiFirmati_Fill_Panel;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmView_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmView_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmView_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmView_Toolbars_Dock_Area_Top;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        private System.Windows.Forms.PictureBox PicImage;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanelDX;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControlFiltri;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanelEpi;
        private System.Windows.Forms.Label lblCodEntita;
        private System.Windows.Forms.Label lblDataInserimentoI;
        private Infragistics.Win.Misc.UltraButton ubRicerca;
        private System.Windows.Forms.Label lblID;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteID;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor udteDataInserimentoI;
        private Infragistics.Win.UltraWinGrid.UltraGrid UltraGrid;
        private System.Windows.Forms.Label lblDataInserimentoF;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor udteDataInserimentoF;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor uceCodEntita;
        private System.Windows.Forms.SaveFileDialog SaveFileDialog;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteIDEntita;
        private System.Windows.Forms.Label lblIDEntita;
    }
}