namespace UnicodeSrl.ScciManagement
{
    partial class frmEntitaAllegato
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton1 = new Infragistics.Win.UltraWinEditors.EditorButton("puppa");
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.lblIcona = new System.Windows.Forms.Label();
            this.ucPictureSelectIcona = new UnicodeSrl.ScciCore.ucPictureSelect();
            this.lblColore = new System.Windows.Forms.Label();
            this.ucpColore = new Infragistics.Win.UltraWinEditors.UltraColorPicker();
            this.uteDescrizione = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.uteCodice = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblDescrizione = new System.Windows.Forms.Label();
            this.lblCodice = new System.Windows.Forms.Label();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.PicImage = new System.Windows.Forms.PictureBox();
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmPUView_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUView_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUView_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUView_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.frmEntitaAllegato_Fill_Panel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.UltraTabControl = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ubApplica = new Infragistics.Win.Misc.UltraButton();
            this.ubConferma = new Infragistics.Win.Misc.UltraButton();
            this.ubAnnulla = new Infragistics.Win.Misc.UltraButton();
            this.colorDialog = new System.Windows.Forms.ColorDialog();
            this.SaveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.ultraTabPageControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucpColore)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodice)).BeginInit();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.frmEntitaAllegato_Fill_Panel.ClientArea.SuspendLayout();
            this.frmEntitaAllegato_Fill_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).BeginInit();
            this.UltraTabControl.SuspendLayout();
            this.ultraTabSharedControlsPage1.SuspendLayout();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.lblIcona);
            this.ultraTabPageControl1.Controls.Add(this.ucPictureSelectIcona);
            this.ultraTabPageControl1.Controls.Add(this.lblColore);
            this.ultraTabPageControl1.Controls.Add(this.ucpColore);
            this.ultraTabPageControl1.Controls.Add(this.uteDescrizione);
            this.ultraTabPageControl1.Controls.Add(this.uteCodice);
            this.ultraTabPageControl1.Controls.Add(this.lblDescrizione);
            this.ultraTabPageControl1.Controls.Add(this.lblCodice);
            this.ultraTabPageControl1.Controls.Add(this.TableLayoutPanel);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(770, 526);
                                                this.lblIcona.BackColor = System.Drawing.Color.Transparent;
            this.lblIcona.Location = new System.Drawing.Point(140, 90);
            this.lblIcona.Name = "lblIcona";
            this.lblIcona.Size = new System.Drawing.Size(120, 20);
            this.lblIcona.TabIndex = 7;
            this.lblIcona.Text = "Icona";
                                                this.ucPictureSelectIcona.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ucPictureSelectIcona.BackColor = System.Drawing.Color.Transparent;
            this.ucPictureSelectIcona.Location = new System.Drawing.Point(286, 90);
            this.ucPictureSelectIcona.Name = "ucPictureSelectIcona";
            this.ucPictureSelectIcona.Size = new System.Drawing.Size(474, 433);
            this.ucPictureSelectIcona.TabIndex = 8;
            this.ucPictureSelectIcona.ViewCenterImage = false;
            this.ucPictureSelectIcona.ViewCheckSquareImage = true;
            this.ucPictureSelectIcona.ViewImage = null;
            this.ucPictureSelectIcona.ViewOpenFileDialogFilter = "png files (*.png)|*.png";
            this.ucPictureSelectIcona.ViewSaveFileDialogFilter = "png files (*.png)|*.png|jpg files (*.jpg)|*.jpg|bmp files (*.bmp)|*.bmp";
            this.ucPictureSelectIcona.ViewShowAddImage = true;
            this.ucPictureSelectIcona.ViewShowRemoveImage = true;
            this.ucPictureSelectIcona.ViewShowSaveImage = true;
            this.ucPictureSelectIcona.ViewShowToolbar = true;
            this.ucPictureSelectIcona.ViewToolbarStyle = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
            this.ucPictureSelectIcona.ViewUseLargeImages = false;
            this.ucPictureSelectIcona.ViewZoomFactor = UnicodeSrl.Scci.Enums.enumZoomfactor.zf100;
            this.ucPictureSelectIcona.PictureChange += new UnicodeSrl.ScciCore.ChangeEventHandler(this.ute_ValueChanged);
                                                this.lblColore.BackColor = System.Drawing.Color.Transparent;
            this.lblColore.Location = new System.Drawing.Point(140, 64);
            this.lblColore.Name = "lblColore";
            this.lblColore.Size = new System.Drawing.Size(140, 20);
            this.lblColore.TabIndex = 5;
            this.lblColore.Text = "Colore";
                                                editorButton1.Key = "puppa";
            editorButton1.Text = "...";
            this.ucpColore.ButtonsRight.Add(editorButton1);
            this.ucpColore.DropDownButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Never;
            this.ucpColore.Location = new System.Drawing.Point(286, 63);
            this.ucpColore.Name = "ucpColore";
            this.ucpColore.Size = new System.Drawing.Size(188, 21);
            this.ucpColore.TabIndex = 6;
            this.ucpColore.Text = "Control";
            this.ucpColore.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
            this.ucpColore.EditorButtonClick += new Infragistics.Win.UltraWinEditors.EditorButtonEventHandler(this.ucpColore_EditorButtonClick);
                                                this.uteDescrizione.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.uteDescrizione.Location = new System.Drawing.Point(286, 36);
            this.uteDescrizione.Name = "uteDescrizione";
            this.uteDescrizione.Size = new System.Drawing.Size(474, 21);
            this.uteDescrizione.TabIndex = 4;
            this.uteDescrizione.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.uteCodice.Location = new System.Drawing.Point(286, 8);
            this.uteCodice.Name = "uteCodice";
            this.uteCodice.Size = new System.Drawing.Size(101, 21);
            this.uteCodice.TabIndex = 2;
            this.uteCodice.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.lblDescrizione.BackColor = System.Drawing.Color.Transparent;
            this.lblDescrizione.Location = new System.Drawing.Point(140, 40);
            this.lblDescrizione.Name = "lblDescrizione";
            this.lblDescrizione.Size = new System.Drawing.Size(140, 20);
            this.lblDescrizione.TabIndex = 3;
            this.lblDescrizione.Text = "Descrizione";
                                                this.lblCodice.BackColor = System.Drawing.Color.Transparent;
            this.lblCodice.Location = new System.Drawing.Point(140, 12);
            this.lblCodice.Name = "lblCodice";
            this.lblCodice.Size = new System.Drawing.Size(140, 20);
            this.lblCodice.TabIndex = 1;
            this.lblCodice.Text = "Codice";
                                                this.TableLayoutPanel.ColumnCount = 1;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TableLayoutPanel.Controls.Add(this.PicImage, 0, 1);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.TableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(134, 526);
            this.TableLayoutPanel.TabIndex = 0;
                                                this.PicImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PicImage.Location = new System.Drawing.Point(3, 202);
            this.PicImage.Name = "PicImage";
            this.PicImage.Size = new System.Drawing.Size(128, 122);
            this.PicImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PicImage.TabIndex = 0;
            this.PicImage.TabStop = false;
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
                                                this._frmPUView_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUView_Toolbars_Dock_Area_Top.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUView_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmPUView_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUView_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmPUView_Toolbars_Dock_Area_Top.Name = "_frmPUView_Toolbars_Dock_Area_Top";
            this._frmPUView_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(796, 0);
            this._frmPUView_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmPUView_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUView_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUView_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmPUView_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUView_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 602);
            this._frmPUView_Toolbars_Dock_Area_Bottom.Name = "_frmPUView_Toolbars_Dock_Area_Bottom";
            this._frmPUView_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(796, 0);
            this._frmPUView_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmPUView_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUView_Toolbars_Dock_Area_Left.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUView_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmPUView_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUView_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._frmPUView_Toolbars_Dock_Area_Left.Name = "_frmPUView_Toolbars_Dock_Area_Left";
            this._frmPUView_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 602);
            this._frmPUView_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmPUView_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUView_Toolbars_Dock_Area_Right.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUView_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmPUView_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUView_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(796, 0);
            this._frmPUView_Toolbars_Dock_Area_Right.Name = "_frmPUView_Toolbars_Dock_Area_Right";
            this._frmPUView_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 602);
            this._frmPUView_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                                                    this.frmEntitaAllegato_Fill_Panel.ClientArea.Controls.Add(this.UltraGroupBox);
            this.frmEntitaAllegato_Fill_Panel.Cursor = System.Windows.Forms.Cursors.Default;
            this.frmEntitaAllegato_Fill_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.frmEntitaAllegato_Fill_Panel.Location = new System.Drawing.Point(0, 0);
            this.frmEntitaAllegato_Fill_Panel.Name = "frmEntitaAllegato_Fill_Panel";
            this.frmEntitaAllegato_Fill_Panel.Size = new System.Drawing.Size(796, 602);
            this.frmEntitaAllegato_Fill_Panel.TabIndex = 8;
                                                this.UltraGroupBox.Controls.Add(this.UltraTabControl);
            this.UltraGroupBox.Controls.Add(this.ubApplica);
            this.UltraGroupBox.Controls.Add(this.ubConferma);
            this.UltraGroupBox.Controls.Add(this.ubAnnulla);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(796, 602);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.UltraTabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.UltraTabControl.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControl.Location = new System.Drawing.Point(12, 12);
            this.UltraTabControl.Name = "UltraTabControl";
            this.UltraTabControl.SharedControls.AddRange(new System.Windows.Forms.Control[] {
            this.TableLayoutPanel});
            this.UltraTabControl.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControl.Size = new System.Drawing.Size(772, 549);
            this.UltraTabControl.TabIndex = 0;
            ultraTab1.Key = "tab1";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Allegato Entità";
            this.UltraTabControl.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1});
            this.UltraTabControl.TabStop = false;
            this.UltraTabControl.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Controls.Add(this.TableLayoutPanel);
            this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(770, 526);
                                                this.ubApplica.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.ubApplica.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubApplica.Location = new System.Drawing.Point(350, 567);
            this.ubApplica.Name = "ubApplica";
            this.ubApplica.Size = new System.Drawing.Size(75, 23);
            this.ubApplica.TabIndex = 2;
            this.ubApplica.Text = "Applica";
            this.ubApplica.Click += new System.EventHandler(this.ubApplica_Click);
                                                this.ubConferma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubConferma.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubConferma.Location = new System.Drawing.Point(709, 567);
            this.ubConferma.Name = "ubConferma";
            this.ubConferma.Size = new System.Drawing.Size(75, 23);
            this.ubConferma.TabIndex = 3;
            this.ubConferma.Text = "&Conferma";
            this.ubConferma.Click += new System.EventHandler(this.ubConferma_Click);
                                                this.ubAnnulla.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ubAnnulla.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubAnnulla.Location = new System.Drawing.Point(12, 567);
            this.ubAnnulla.Name = "ubAnnulla";
            this.ubAnnulla.Size = new System.Drawing.Size(75, 23);
            this.ubAnnulla.TabIndex = 1;
            this.ubAnnulla.Text = "&Annulla";
            this.ubAnnulla.Click += new System.EventHandler(this.ubAnnulla_Click);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(796, 602);
            this.Controls.Add(this.frmEntitaAllegato_Fill_Panel);
            this.Controls.Add(this._frmPUView_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmPUView_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmPUView_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmPUView_Toolbars_Dock_Area_Top);
            this.Name = "frmEntitaAllegato";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmEntitaAllegato";
            this.ultraTabPageControl1.ResumeLayout(false);
            this.ultraTabPageControl1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucpColore)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodice)).EndInit();
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.frmEntitaAllegato_Fill_Panel.ClientArea.ResumeLayout(false);
            this.frmEntitaAllegato_Fill_Panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).EndInit();
            this.UltraTabControl.ResumeLayout(false);
            this.ultraTabSharedControlsPage1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUView_Toolbars_Dock_Area_Top;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUView_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUView_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUView_Toolbars_Dock_Area_Right;
        private Infragistics.Win.Misc.UltraPanel frmEntitaAllegato_Fill_Panel;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControl;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        private System.Windows.Forms.PictureBox PicImage;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private System.Windows.Forms.Label lblIcona;
        private ScciCore.ucPictureSelect ucPictureSelectIcona;
        private System.Windows.Forms.Label lblColore;
        private Infragistics.Win.UltraWinEditors.UltraColorPicker ucpColore;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteDescrizione;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteCodice;
        private System.Windows.Forms.Label lblDescrizione;
        private System.Windows.Forms.Label lblCodice;
        private Infragistics.Win.Misc.UltraButton ubApplica;
        private Infragistics.Win.Misc.UltraButton ubConferma;
        private Infragistics.Win.Misc.UltraButton ubAnnulla;
        private System.Windows.Forms.ColorDialog colorDialog;
        private System.Windows.Forms.SaveFileDialog SaveFileDialog;
    }
}