using UnicodeSrl.ScciCore;

namespace UnicodeSrl.ScciManagement
{
    partial class frmModuli
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this.frmModuli_Fill_Panel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.picView = new System.Windows.Forms.PictureBox();
            this.UltraPanel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraTree = new Infragistics.Win.UltraWinTree.UltraTree();
            this.UltraSplitter = new Infragistics.Win.Misc.UltraSplitter();
            this.tlpDX = new System.Windows.Forms.TableLayoutPanel();
            this.UltraGrid = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.uteCercaDX = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblCercaDX = new System.Windows.Forms.Label();
            this.ubChiudi = new Infragistics.Win.Misc.UltraButton();
            this._frmModuli_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmModuli_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmModuli_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmModuli_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.frmModuli_Fill_Panel.ClientArea.SuspendLayout();
            this.frmModuli_Fill_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picView)).BeginInit();
            this.UltraPanel.ClientArea.SuspendLayout();
            this.UltraPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTree)).BeginInit();
            this.tlpDX.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGrid)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCercaDX)).BeginInit();
            this.SuspendLayout();
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
                                                                                    this.frmModuli_Fill_Panel.ClientArea.Controls.Add(this.UltraGroupBox);
            this.frmModuli_Fill_Panel.Cursor = System.Windows.Forms.Cursors.Default;
            this.frmModuli_Fill_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.frmModuli_Fill_Panel.Location = new System.Drawing.Point(0, 0);
            this.frmModuli_Fill_Panel.Name = "frmModuli_Fill_Panel";
            this.frmModuli_Fill_Panel.Size = new System.Drawing.Size(784, 562);
            this.frmModuli_Fill_Panel.TabIndex = 0;
                                                this.UltraGroupBox.Controls.Add(this.TableLayoutPanel);
            this.UltraGroupBox.Controls.Add(this.ubChiudi);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(784, 562);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.TableLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanel.ColumnCount = 2;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 140F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.Controls.Add(this.picView, 0, 1);
            this.TableLayoutPanel.Controls.Add(this.UltraPanel, 1, 0);
            this.TableLayoutPanel.Location = new System.Drawing.Point(6, 12);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(772, 515);
            this.TableLayoutPanel.TabIndex = 2;
                                                this.picView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picView.Location = new System.Drawing.Point(3, 196);
            this.picView.Name = "picView";
            this.picView.Size = new System.Drawing.Size(134, 122);
            this.picView.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picView.TabIndex = 1;
            this.picView.TabStop = false;
                                                                                    this.UltraPanel.ClientArea.Controls.Add(this.UltraTree);
            this.UltraPanel.ClientArea.Controls.Add(this.UltraSplitter);
            this.UltraPanel.ClientArea.Controls.Add(this.tlpDX);
            this.UltraPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraPanel.Location = new System.Drawing.Point(143, 3);
            this.UltraPanel.Name = "UltraPanel";
            this.TableLayoutPanel.SetRowSpan(this.UltraPanel, 3);
            this.UltraPanel.Size = new System.Drawing.Size(626, 509);
            this.UltraPanel.TabIndex = 3;
                                                this.UltraTree.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraTree.Location = new System.Drawing.Point(0, 0);
            this.UltraTree.Name = "UltraTree";
            this.UltraTree.NodeConnectorColor = System.Drawing.SystemColors.ControlDark;
            this.UltraTree.Size = new System.Drawing.Size(291, 509);
            this.UltraTree.TabIndex = 2;
            this.UltraTree.AfterActivate += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.UltraTree_AfterActivate);
            this.UltraTree.DragDrop += new System.Windows.Forms.DragEventHandler(this.UltraTree_DragDrop);
            this.UltraTree.DragOver += new System.Windows.Forms.DragEventHandler(this.UltraTree_DragOver);
            this.UltraTree.MouseMove += new System.Windows.Forms.MouseEventHandler(this.UltraTree_MouseMove);
                                                this.UltraSplitter.BackColor = System.Drawing.Color.Transparent;
            this.UltraSplitter.CollapseUIType = Infragistics.Win.Misc.CollapseUIType.None;
            this.UltraSplitter.Dock = System.Windows.Forms.DockStyle.Right;
            this.UltraSplitter.Location = new System.Drawing.Point(291, 0);
            this.UltraSplitter.Name = "UltraSplitter";
            this.UltraSplitter.RestoreExtent = 154;
            this.UltraSplitter.Size = new System.Drawing.Size(8, 509);
            this.UltraSplitter.TabIndex = 4;
                                                this.tlpDX.ColumnCount = 2;
            this.tlpDX.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tlpDX.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.tlpDX.Controls.Add(this.uteCercaDX, 1, 1);
            this.tlpDX.Controls.Add(this.lblCercaDX, 0, 1);
            this.tlpDX.Controls.Add(this.UltraGrid, 0, 0);
            this.tlpDX.Dock = System.Windows.Forms.DockStyle.Right;
            this.tlpDX.Location = new System.Drawing.Point(299, 0);
            this.tlpDX.Name = "tlpDX";
            this.tlpDX.RowCount = 2;
            this.tlpDX.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpDX.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34F));
            this.tlpDX.Size = new System.Drawing.Size(327, 509);
            this.tlpDX.TabIndex = 4;
                                                this.tlpDX.SetColumnSpan(this.UltraGrid, 2);
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGrid.DisplayLayout.Appearance = appearance1;
            this.UltraGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance2.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.GroupByBox.Appearance = appearance2;
            appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
            this.UltraGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance4.BackColor2 = System.Drawing.SystemColors.Control;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
            this.UltraGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGrid.DisplayLayout.Override.ActiveCellAppearance = appearance5;
            appearance6.BackColor = System.Drawing.SystemColors.Highlight;
            appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGrid.DisplayLayout.Override.ActiveRowAppearance = appearance6;
            this.UltraGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.Override.CardAreaAppearance = appearance7;
            appearance8.BorderColor = System.Drawing.Color.Silver;
            appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGrid.DisplayLayout.Override.CellAppearance = appearance8;
            this.UltraGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.UltraGrid.DisplayLayout.Override.CellPadding = 0;
            appearance9.BackColor = System.Drawing.SystemColors.Control;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.Override.GroupByRowAppearance = appearance9;
            appearance10.TextHAlignAsString = "Left";
            this.UltraGrid.DisplayLayout.Override.HeaderAppearance = appearance10;
            this.UltraGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.UltraGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            this.UltraGrid.DisplayLayout.Override.RowAppearance = appearance11;
            this.UltraGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance12.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance12;
            this.UltraGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGrid.Location = new System.Drawing.Point(2, 2);
            this.UltraGrid.Margin = new System.Windows.Forms.Padding(2);
            this.UltraGrid.Name = "UltraGrid";
            this.UltraGrid.Size = new System.Drawing.Size(323, 471);
            this.UltraGrid.TabIndex = 3;
            this.UltraGrid.Text = "ultraGrid1";
            this.UltraGrid.AfterCellUpdate += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.UltraGrid_AfterCellUpdate);
            this.UltraGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGrid_InitializeLayout);
            this.UltraGrid.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGrid_InitializeRow);
            this.UltraGrid.CellChange += new Infragistics.Win.UltraWinGrid.CellEventHandler(this.UltraGrid_CellChange);
            this.UltraGrid.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.UltraGrid_ClickCell);
                                                this.uteCercaDX.AutoSize = false;
            this.uteCercaDX.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteCercaDX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteCercaDX.Location = new System.Drawing.Point(100, 477);
            this.uteCercaDX.Margin = new System.Windows.Forms.Padding(2);
            this.uteCercaDX.Name = "uteCercaDX";
            this.uteCercaDX.Size = new System.Drawing.Size(225, 30);
            this.uteCercaDX.TabIndex = 8;
            this.uteCercaDX.ValueChanged += new System.EventHandler(this.uteCercaDX_ValueChanged);
                                                this.lblCercaDX.AutoSize = true;
            this.lblCercaDX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCercaDX.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCercaDX.Location = new System.Drawing.Point(2, 477);
            this.lblCercaDX.Margin = new System.Windows.Forms.Padding(2);
            this.lblCercaDX.Name = "lblCercaDX";
            this.lblCercaDX.Size = new System.Drawing.Size(94, 30);
            this.lblCercaDX.TabIndex = 4;
            this.lblCercaDX.Text = "Cerca:";
            this.lblCercaDX.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.ubChiudi.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubChiudi.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubChiudi.Location = new System.Drawing.Point(703, 533);
            this.ubChiudi.Name = "ubChiudi";
            this.ubChiudi.Size = new System.Drawing.Size(75, 23);
            this.ubChiudi.TabIndex = 3;
            this.ubChiudi.Text = "&Chiudi";
            this.ubChiudi.Click += new System.EventHandler(this.ubChiudi_Click);
                                                this._frmModuli_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmModuli_Toolbars_Dock_Area_Left.BackColor = System.Drawing.SystemColors.Control;
            this._frmModuli_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmModuli_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmModuli_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._frmModuli_Toolbars_Dock_Area_Left.Name = "_frmModuli_Toolbars_Dock_Area_Left";
            this._frmModuli_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 562);
            this._frmModuli_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmModuli_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmModuli_Toolbars_Dock_Area_Right.BackColor = System.Drawing.SystemColors.Control;
            this._frmModuli_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmModuli_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmModuli_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(784, 0);
            this._frmModuli_Toolbars_Dock_Area_Right.Name = "_frmModuli_Toolbars_Dock_Area_Right";
            this._frmModuli_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 562);
            this._frmModuli_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmModuli_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmModuli_Toolbars_Dock_Area_Top.BackColor = System.Drawing.SystemColors.Control;
            this._frmModuli_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmModuli_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmModuli_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmModuli_Toolbars_Dock_Area_Top.Name = "_frmModuli_Toolbars_Dock_Area_Top";
            this._frmModuli_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(784, 0);
            this._frmModuli_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmModuli_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmModuli_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.SystemColors.Control;
            this._frmModuli_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmModuli_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmModuli_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 562);
            this._frmModuli_Toolbars_Dock_Area_Bottom.Name = "_frmModuli_Toolbars_Dock_Area_Bottom";
            this._frmModuli_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(784, 0);
            this._frmModuli_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 562);
            this.Controls.Add(this.frmModuli_Fill_Panel);
            this.Controls.Add(this._frmModuli_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmModuli_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmModuli_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmModuli_Toolbars_Dock_Area_Top);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MinimizeBox = false;
            this.Name = "frmModuli";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmModuli";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmModuli_FormClosing);
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.frmModuli_Fill_Panel.ClientArea.ResumeLayout(false);
            this.frmModuli_Fill_Panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picView)).EndInit();
            this.UltraPanel.ClientArea.ResumeLayout(false);
            this.UltraPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTree)).EndInit();
            this.tlpDX.ResumeLayout(false);
            this.tlpDX.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGrid)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCercaDX)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.Misc.UltraPanel frmModuli_Fill_Panel;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmModuli_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmModuli_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmModuli_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmModuli_Toolbars_Dock_Area_Top;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        internal System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        internal System.Windows.Forms.PictureBox picView;
        private Infragistics.Win.UltraWinTree.UltraTree UltraTree;
        internal Infragistics.Win.Misc.UltraButton ubChiudi;
        private Infragistics.Win.Misc.UltraPanel UltraPanel;
        private Infragistics.Win.UltraWinGrid.UltraGrid UltraGrid;
        private Infragistics.Win.Misc.UltraSplitter UltraSplitter;
        private System.Windows.Forms.TableLayoutPanel tlpDX;
        internal System.Windows.Forms.Label lblCercaDX;
        internal Infragistics.Win.UltraWinEditors.UltraTextEditor uteCercaDX;
    }
}