namespace UnicodeSrl.ScciManagement
{
    partial class frmPUSchedeVersioni
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab2 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab5 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab3 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab4 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            this.ultraTabPageControl3 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.TableLayoutPanelDC = new System.Windows.Forms.TableLayoutPanel();
            this.ucDcDesigner = new UnicodeSrl.DatiCliniciUI.UserControls.ucDcDesigner();
            this.TableLayoutPanelComandi = new System.Windows.Forms.TableLayoutPanel();
            this.ubDizionarioQuick = new Infragistics.Win.Misc.UltraButton();
            this.ubCopia = new Infragistics.Win.Misc.UltraButton();
            this.ultraTabPageControl4 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ehViewer = new System.Windows.Forms.Integration.ElementHost();
            this.ucDcViewer = new UnicodeSrl.WpfControls40.ucDcViewer();
            this.ultraTabPageControl5 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.rtbRichTextBox = new ExtendedRichTextBox.RichTextBoxPrintCtrl();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.chkCreaDefault = new System.Windows.Forms.CheckBox();
            this.umeNumerosita = new Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit();
            this.lblNumerosita = new System.Windows.Forms.Label();
            this.udteDtValF = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.udteDtValI = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.lblDtValF = new System.Windows.Forms.Label();
            this.lblDtValI = new System.Windows.Forms.Label();
            this.chkPubblicato = new System.Windows.Forms.CheckBox();
            this.chkFlagAttiva = new System.Windows.Forms.CheckBox();
            this.uteVersione = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblVersione = new System.Windows.Forms.Label();
            this.uteDescrizione = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.uteCodScheda = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblDescrizione = new System.Windows.Forms.Label();
            this.lblCodScheda = new System.Windows.Forms.Label();
            this.ultraTabPageControl2 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.UltraPanelStruttura = new Infragistics.Win.Misc.UltraPanel();
            this.UltraTabControlDatiClinici = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage2 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.PicImage = new System.Windows.Forms.PictureBox();
            this.frmPUSchedeVersioni_Fill_Panel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.UltraTabControl = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ubApplica = new Infragistics.Win.Misc.UltraButton();
            this.ubConferma = new Infragistics.Win.Misc.UltraButton();
            this.ubAnnulla = new Infragistics.Win.Misc.UltraButton();
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.ultraTabPageControl3.SuspendLayout();
            this.TableLayoutPanelDC.SuspendLayout();
            this.TableLayoutPanelComandi.SuspendLayout();
            this.ultraTabPageControl4.SuspendLayout();
            this.ultraTabPageControl5.SuspendLayout();
            this.ultraTabPageControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteDtValF)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDtValI)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteVersione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodScheda)).BeginInit();
            this.ultraTabPageControl2.SuspendLayout();
            this.UltraPanelStruttura.ClientArea.SuspendLayout();
            this.UltraPanelStruttura.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControlDatiClinici)).BeginInit();
            this.UltraTabControlDatiClinici.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).BeginInit();
            this.frmPUSchedeVersioni_Fill_Panel.ClientArea.SuspendLayout();
            this.frmPUSchedeVersioni_Fill_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).BeginInit();
            this.UltraTabControl.SuspendLayout();
            this.ultraTabSharedControlsPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.SuspendLayout();
                                                this.ultraTabPageControl3.Controls.Add(this.TableLayoutPanelDC);
            this.ultraTabPageControl3.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl3.Name = "ultraTabPageControl3";
            this.ultraTabPageControl3.Size = new System.Drawing.Size(846, 713);
                                                this.TableLayoutPanelDC.ColumnCount = 1;
            this.TableLayoutPanelDC.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelDC.Controls.Add(this.ucDcDesigner, 0, 1);
            this.TableLayoutPanelDC.Controls.Add(this.TableLayoutPanelComandi, 0, 0);
            this.TableLayoutPanelDC.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelDC.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanelDC.Name = "TableLayoutPanelDC";
            this.TableLayoutPanelDC.RowCount = 2;
            this.TableLayoutPanelDC.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 36F));
            this.TableLayoutPanelDC.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelDC.Size = new System.Drawing.Size(846, 713);
            this.TableLayoutPanelDC.TabIndex = 1;
                                                this.ucDcDesigner.BackColor = System.Drawing.Color.Transparent;
            this.ucDcDesigner.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucDcDesigner.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ucDcDesigner.Location = new System.Drawing.Point(3, 39);
            this.ucDcDesigner.Name = "ucDcDesigner";
            this.ucDcDesigner.Size = new System.Drawing.Size(840, 671);
            this.ucDcDesigner.TabIndex = 0;
                                                this.TableLayoutPanelComandi.ColumnCount = 3;
            this.TableLayoutPanelComandi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 102F));
            this.TableLayoutPanelComandi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelComandi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 102F));
            this.TableLayoutPanelComandi.Controls.Add(this.ubDizionarioQuick, 2, 0);
            this.TableLayoutPanelComandi.Controls.Add(this.ubCopia, 0, 0);
            this.TableLayoutPanelComandi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelComandi.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanelComandi.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanelComandi.Name = "TableLayoutPanelComandi";
            this.TableLayoutPanelComandi.RowCount = 1;
            this.TableLayoutPanelComandi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelComandi.Size = new System.Drawing.Size(846, 36);
            this.TableLayoutPanelComandi.TabIndex = 4;
                                                this.ubDizionarioQuick.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubDizionarioQuick.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubDizionarioQuick.Location = new System.Drawing.Point(747, 3);
            this.ubDizionarioQuick.Name = "ubDizionarioQuick";
            this.ubDizionarioQuick.Size = new System.Drawing.Size(96, 30);
            this.ubDizionarioQuick.TabIndex = 4;
            this.ubDizionarioQuick.Text = "Dizionario Quick";
            this.ubDizionarioQuick.Click += new System.EventHandler(this.ubDizionarioQuick_Click);
                                                this.ubCopia.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubCopia.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCopia.Location = new System.Drawing.Point(3, 3);
            this.ubCopia.Name = "ubCopia";
            this.ubCopia.Size = new System.Drawing.Size(96, 30);
            this.ubCopia.TabIndex = 3;
            this.ubCopia.Text = "Copia Sezione";
            this.ubCopia.Click += new System.EventHandler(this.ubCopia_Click);
                                                this.ultraTabPageControl4.Controls.Add(this.ehViewer);
            this.ultraTabPageControl4.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl4.Name = "ultraTabPageControl4";
            this.ultraTabPageControl4.Size = new System.Drawing.Size(846, 713);
                                                this.ehViewer.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ehViewer.Location = new System.Drawing.Point(5, 3);
            this.ehViewer.Name = "ehViewer";
            this.ehViewer.Size = new System.Drawing.Size(838, 707);
            this.ehViewer.TabIndex = 0;
            this.ehViewer.Text = "elementHost1";
            this.ehViewer.Child = this.ucDcViewer;
                                                this.ultraTabPageControl5.Controls.Add(this.rtbRichTextBox);
            this.ultraTabPageControl5.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl5.Name = "ultraTabPageControl5";
            this.ultraTabPageControl5.Size = new System.Drawing.Size(846, 713);
                                                this.rtbRichTextBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.rtbRichTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rtbRichTextBox.HideSelection = false;
            this.rtbRichTextBox.Location = new System.Drawing.Point(0, 0);
            this.rtbRichTextBox.Name = "rtbRichTextBox";
            this.rtbRichTextBox.ReadOnly = true;
            this.rtbRichTextBox.Size = new System.Drawing.Size(846, 713);
            this.rtbRichTextBox.TabIndex = 1;
            this.rtbRichTextBox.Text = "";
                                                this.ultraTabPageControl1.Controls.Add(this.chkCreaDefault);
            this.ultraTabPageControl1.Controls.Add(this.umeNumerosita);
            this.ultraTabPageControl1.Controls.Add(this.lblNumerosita);
            this.ultraTabPageControl1.Controls.Add(this.udteDtValF);
            this.ultraTabPageControl1.Controls.Add(this.udteDtValI);
            this.ultraTabPageControl1.Controls.Add(this.lblDtValF);
            this.ultraTabPageControl1.Controls.Add(this.lblDtValI);
            this.ultraTabPageControl1.Controls.Add(this.chkPubblicato);
            this.ultraTabPageControl1.Controls.Add(this.chkFlagAttiva);
            this.ultraTabPageControl1.Controls.Add(this.uteVersione);
            this.ultraTabPageControl1.Controls.Add(this.lblVersione);
            this.ultraTabPageControl1.Controls.Add(this.uteDescrizione);
            this.ultraTabPageControl1.Controls.Add(this.uteCodScheda);
            this.ultraTabPageControl1.Controls.Add(this.lblDescrizione);
            this.ultraTabPageControl1.Controls.Add(this.lblCodScheda);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(982, 736);
                                                this.chkCreaDefault.BackColor = System.Drawing.Color.Transparent;
            this.chkCreaDefault.Location = new System.Drawing.Point(140, 175);
            this.chkCreaDefault.Name = "chkCreaDefault";
            this.chkCreaDefault.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkCreaDefault.Size = new System.Drawing.Size(160, 19);
            this.chkCreaDefault.TabIndex = 7;
            this.chkCreaDefault.Text = "Crea Default";
            this.chkCreaDefault.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkCreaDefault.UseVisualStyleBackColor = false;
            this.chkCreaDefault.Visible = false;
            this.chkCreaDefault.CheckedChanged += new System.EventHandler(this.ute_ValueChanged);
                                                appearance1.TextHAlignAsString = "Right";
            this.umeNumerosita.Appearance = appearance1;
            this.umeNumerosita.EditAs = Infragistics.Win.UltraWinMaskedEdit.EditAsType.Integer;
            this.umeNumerosita.Location = new System.Drawing.Point(286, 200);
            this.umeNumerosita.Name = "umeNumerosita";
            this.umeNumerosita.NonAutoSizeHeight = 20;
            this.umeNumerosita.Size = new System.Drawing.Size(84, 21);
            this.umeNumerosita.TabIndex = 8;
            this.umeNumerosita.Visible = false;
            this.umeNumerosita.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.lblNumerosita.BackColor = System.Drawing.Color.Transparent;
            this.lblNumerosita.Location = new System.Drawing.Point(140, 204);
            this.lblNumerosita.Name = "lblNumerosita";
            this.lblNumerosita.Size = new System.Drawing.Size(129, 20);
            this.lblNumerosita.TabIndex = 19;
            this.lblNumerosita.Text = "Numerosita";
            this.lblNumerosita.Visible = false;
                                                this.udteDtValF.DateTime = new System.DateTime(2013, 1, 1, 0, 0, 0, 0);
            this.udteDtValF.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDtValF.FormatString = "dd/MM/yyyy HH:mm";
            this.udteDtValF.Location = new System.Drawing.Point(286, 145);
            this.udteDtValF.MaskInput = "{date} {time}";
            this.udteDtValF.Name = "udteDtValF";
            this.udteDtValF.Size = new System.Drawing.Size(144, 22);
            this.udteDtValF.TabIndex = 6;
            this.udteDtValF.Value = new System.DateTime(2013, 1, 1, 0, 0, 0, 0);
            this.udteDtValF.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.udteDtValI.DateTime = new System.DateTime(2013, 1, 1, 0, 0, 0, 0);
            this.udteDtValI.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDtValI.FormatString = "dd/MM/yyyy HH:mm";
            this.udteDtValI.Location = new System.Drawing.Point(286, 117);
            this.udteDtValI.MaskInput = "{date} {time}";
            this.udteDtValI.Name = "udteDtValI";
            this.udteDtValI.Size = new System.Drawing.Size(144, 22);
            this.udteDtValI.TabIndex = 5;
            this.udteDtValI.Value = new System.DateTime(2013, 1, 1, 0, 0, 0, 0);
            this.udteDtValI.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.lblDtValF.BackColor = System.Drawing.Color.Transparent;
            this.lblDtValF.Location = new System.Drawing.Point(140, 152);
            this.lblDtValF.Name = "lblDtValF";
            this.lblDtValF.Size = new System.Drawing.Size(140, 20);
            this.lblDtValF.TabIndex = 17;
            this.lblDtValF.Text = "Data Fine Pubblicazione";
                                                this.lblDtValI.BackColor = System.Drawing.Color.Transparent;
            this.lblDtValI.Location = new System.Drawing.Point(140, 121);
            this.lblDtValI.Name = "lblDtValI";
            this.lblDtValI.Size = new System.Drawing.Size(140, 20);
            this.lblDtValI.TabIndex = 15;
            this.lblDtValI.Text = "Data Inizio Pubblicazione";
                                                this.chkPubblicato.BackColor = System.Drawing.Color.Transparent;
            this.chkPubblicato.Location = new System.Drawing.Point(334, 92);
            this.chkPubblicato.Name = "chkPubblicato";
            this.chkPubblicato.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkPubblicato.Size = new System.Drawing.Size(160, 19);
            this.chkPubblicato.TabIndex = 4;
            this.chkPubblicato.Text = "Pubblicato";
            this.chkPubblicato.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkPubblicato.UseVisualStyleBackColor = false;
            this.chkPubblicato.Visible = false;
                                                this.chkFlagAttiva.BackColor = System.Drawing.Color.Transparent;
            this.chkFlagAttiva.Location = new System.Drawing.Point(140, 92);
            this.chkFlagAttiva.Name = "chkFlagAttiva";
            this.chkFlagAttiva.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkFlagAttiva.Size = new System.Drawing.Size(160, 19);
            this.chkFlagAttiva.TabIndex = 3;
            this.chkFlagAttiva.Text = "Attivo";
            this.chkFlagAttiva.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkFlagAttiva.UseVisualStyleBackColor = false;
            this.chkFlagAttiva.CheckedChanged += new System.EventHandler(this.chkFlagAttiva_CheckedChanged);
                                                appearance2.TextHAlignAsString = "Right";
            this.uteVersione.Appearance = appearance2;
            this.uteVersione.Location = new System.Drawing.Point(286, 36);
            this.uteVersione.Name = "uteVersione";
            this.uteVersione.Size = new System.Drawing.Size(208, 22);
            this.uteVersione.TabIndex = 1;
                                                this.lblVersione.BackColor = System.Drawing.Color.Transparent;
            this.lblVersione.Location = new System.Drawing.Point(140, 40);
            this.lblVersione.Name = "lblVersione";
            this.lblVersione.Size = new System.Drawing.Size(140, 20);
            this.lblVersione.TabIndex = 12;
            this.lblVersione.Text = "Versione";
                                                this.uteDescrizione.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.uteDescrizione.Location = new System.Drawing.Point(286, 64);
            this.uteDescrizione.Name = "uteDescrizione";
            this.uteDescrizione.Size = new System.Drawing.Size(686, 22);
            this.uteDescrizione.TabIndex = 2;
            this.uteDescrizione.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.uteCodScheda.Location = new System.Drawing.Point(286, 8);
            this.uteCodScheda.Name = "uteCodScheda";
            this.uteCodScheda.Size = new System.Drawing.Size(208, 22);
            this.uteCodScheda.TabIndex = 0;
            this.uteCodScheda.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.lblDescrizione.BackColor = System.Drawing.Color.Transparent;
            this.lblDescrizione.Location = new System.Drawing.Point(140, 68);
            this.lblDescrizione.Name = "lblDescrizione";
            this.lblDescrizione.Size = new System.Drawing.Size(140, 20);
            this.lblDescrizione.TabIndex = 10;
            this.lblDescrizione.Text = "Descrizione";
                                                this.lblCodScheda.BackColor = System.Drawing.Color.Transparent;
            this.lblCodScheda.Location = new System.Drawing.Point(140, 12);
            this.lblCodScheda.Name = "lblCodScheda";
            this.lblCodScheda.Size = new System.Drawing.Size(140, 20);
            this.lblCodScheda.TabIndex = 9;
            this.lblCodScheda.Text = "Codice Scheda";
                                                this.ultraTabPageControl2.Controls.Add(this.UltraPanelStruttura);
            this.ultraTabPageControl2.Controls.Add(this.TableLayoutPanel);
            this.ultraTabPageControl2.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl2.Name = "ultraTabPageControl2";
            this.ultraTabPageControl2.Size = new System.Drawing.Size(982, 736);
                                                                                    this.UltraPanelStruttura.ClientArea.Controls.Add(this.UltraTabControlDatiClinici);
            this.UltraPanelStruttura.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraPanelStruttura.Location = new System.Drawing.Point(134, 0);
            this.UltraPanelStruttura.Name = "UltraPanelStruttura";
            this.UltraPanelStruttura.Size = new System.Drawing.Size(848, 736);
            this.UltraPanelStruttura.TabIndex = 2;
                                                this.UltraTabControlDatiClinici.Controls.Add(this.ultraTabSharedControlsPage2);
            this.UltraTabControlDatiClinici.Controls.Add(this.ultraTabPageControl3);
            this.UltraTabControlDatiClinici.Controls.Add(this.ultraTabPageControl4);
            this.UltraTabControlDatiClinici.Controls.Add(this.ultraTabPageControl5);
            this.UltraTabControlDatiClinici.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraTabControlDatiClinici.Location = new System.Drawing.Point(0, 0);
            this.UltraTabControlDatiClinici.Name = "UltraTabControlDatiClinici";
            this.UltraTabControlDatiClinici.SharedControlsPage = this.ultraTabSharedControlsPage2;
            this.UltraTabControlDatiClinici.Size = new System.Drawing.Size(848, 736);
            this.UltraTabControlDatiClinici.TabIndex = 1;
            ultraTab1.TabPage = this.ultraTabPageControl3;
            ultraTab1.Text = "Designer";
            ultraTab2.TabPage = this.ultraTabPageControl4;
            ultraTab2.Text = "Viewer";
            ultraTab5.TabPage = this.ultraTabPageControl5;
            ultraTab5.Text = "RTF";
            this.UltraTabControlDatiClinici.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1,
            ultraTab2,
            ultraTab5});
            this.UltraTabControlDatiClinici.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
            this.UltraTabControlDatiClinici.SelectedTabChanged += new Infragistics.Win.UltraWinTabControl.SelectedTabChangedEventHandler(this.UltraTabControlDatiClinici_SelectedTabChanged);
                                                this.ultraTabSharedControlsPage2.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage2.Name = "ultraTabSharedControlsPage2";
            this.ultraTabSharedControlsPage2.Size = new System.Drawing.Size(846, 713);
                                                this.TableLayoutPanel.ColumnCount = 1;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TableLayoutPanel.Controls.Add(this.PicImage, 0, 1);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.TableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(134, 736);
            this.TableLayoutPanel.TabIndex = 1;
                                                this.PicImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PicImage.Location = new System.Drawing.Point(3, 307);
            this.PicImage.Name = "PicImage";
            this.PicImage.Size = new System.Drawing.Size(128, 122);
            this.PicImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PicImage.TabIndex = 0;
            this.PicImage.TabStop = false;
                                                                                    this.frmPUSchedeVersioni_Fill_Panel.ClientArea.Controls.Add(this.UltraGroupBox);
            this.frmPUSchedeVersioni_Fill_Panel.Cursor = System.Windows.Forms.Cursors.Default;
            this.frmPUSchedeVersioni_Fill_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.frmPUSchedeVersioni_Fill_Panel.Location = new System.Drawing.Point(0, 0);
            this.frmPUSchedeVersioni_Fill_Panel.Name = "frmPUSchedeVersioni_Fill_Panel";
            this.frmPUSchedeVersioni_Fill_Panel.Size = new System.Drawing.Size(1008, 812);
            this.frmPUSchedeVersioni_Fill_Panel.TabIndex = 0;
                                                this.UltraGroupBox.Controls.Add(this.UltraTabControl);
            this.UltraGroupBox.Controls.Add(this.ubApplica);
            this.UltraGroupBox.Controls.Add(this.ubConferma);
            this.UltraGroupBox.Controls.Add(this.ubAnnulla);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(1008, 812);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.UltraTabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.UltraTabControl.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl2);
            this.UltraTabControl.Location = new System.Drawing.Point(12, 12);
            this.UltraTabControl.Name = "UltraTabControl";
            this.UltraTabControl.SharedControls.AddRange(new System.Windows.Forms.Control[] {
            this.TableLayoutPanel});
            this.UltraTabControl.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControl.Size = new System.Drawing.Size(984, 759);
            this.UltraTabControl.TabIndex = 0;
            ultraTab3.Key = "tab1";
            ultraTab3.TabPage = this.ultraTabPageControl1;
            ultraTab3.Text = "Anagrafica";
            ultraTab4.Key = "tab2";
            ultraTab4.TabPage = this.ultraTabPageControl2;
            ultraTab4.Text = "Struttura";
            this.UltraTabControl.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab3,
            ultraTab4});
            this.UltraTabControl.TabStop = false;
            this.UltraTabControl.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Controls.Add(this.TableLayoutPanel);
            this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(982, 736);
                                                this.ubApplica.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.ubApplica.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubApplica.Location = new System.Drawing.Point(456, 777);
            this.ubApplica.Name = "ubApplica";
            this.ubApplica.Size = new System.Drawing.Size(75, 23);
            this.ubApplica.TabIndex = 2;
            this.ubApplica.Text = "Applica";
            this.ubApplica.Click += new System.EventHandler(this.ubApplica_Click);
                                                this.ubConferma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubConferma.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubConferma.Location = new System.Drawing.Point(921, 777);
            this.ubConferma.Name = "ubConferma";
            this.ubConferma.Size = new System.Drawing.Size(75, 23);
            this.ubConferma.TabIndex = 3;
            this.ubConferma.Text = "&Conferma";
            this.ubConferma.Click += new System.EventHandler(this.ubConferma_Click);
                                                this.ubAnnulla.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ubAnnulla.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubAnnulla.Location = new System.Drawing.Point(12, 777);
            this.ubAnnulla.Name = "ubAnnulla";
            this.ubAnnulla.Size = new System.Drawing.Size(75, 23);
            this.ubAnnulla.TabIndex = 1;
            this.ubAnnulla.Text = "&Annulla";
            this.ubAnnulla.Click += new System.EventHandler(this.ubAnnulla_Click);
                                                this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left.Name = "_frmPUSchedeVersioni_Toolbars_Dock_Area_Left";
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 812);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
                                                this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(1008, 0);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right.Name = "_frmPUSchedeVersioni_Toolbars_Dock_Area_Right";
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 812);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top.Name = "_frmPUSchedeVersioni_Toolbars_Dock_Area_Top";
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(1008, 0);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 812);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom.Name = "_frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom";
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(1008, 0);
            this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1008, 812);
            this.ControlBox = false;
            this.Controls.Add(this.frmPUSchedeVersioni_Fill_Panel);
            this.Controls.Add(this._frmPUSchedeVersioni_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmPUSchedeVersioni_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmPUSchedeVersioni_Toolbars_Dock_Area_Top);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MinimizeBox = false;
            this.Name = "frmPUSchedeVersioni";
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmPUSchedeVersioni";
            this.ultraTabPageControl3.ResumeLayout(false);
            this.TableLayoutPanelDC.ResumeLayout(false);
            this.TableLayoutPanelComandi.ResumeLayout(false);
            this.ultraTabPageControl4.ResumeLayout(false);
            this.ultraTabPageControl5.ResumeLayout(false);
            this.ultraTabPageControl1.ResumeLayout(false);
            this.ultraTabPageControl1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.udteDtValF)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDtValI)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteVersione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodScheda)).EndInit();
            this.ultraTabPageControl2.ResumeLayout(false);
            this.UltraPanelStruttura.ClientArea.ResumeLayout(false);
            this.UltraPanelStruttura.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControlDatiClinici)).EndInit();
            this.UltraTabControlDatiClinici.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).EndInit();
            this.frmPUSchedeVersioni_Fill_Panel.ClientArea.ResumeLayout(false);
            this.frmPUSchedeVersioni_Fill_Panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).EndInit();
            this.UltraTabControl.ResumeLayout(false);
            this.ultraTabSharedControlsPage1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.Misc.UltraPanel frmPUSchedeVersioni_Fill_Panel;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeVersioni_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeVersioni_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeVersioni_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeVersioni_Toolbars_Dock_Area_Top;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControl;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        private System.Windows.Forms.PictureBox PicImage;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteDescrizione;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteCodScheda;
        private System.Windows.Forms.Label lblDescrizione;
        private System.Windows.Forms.Label lblCodScheda;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl2;
        private Infragistics.Win.Misc.UltraButton ubApplica;
        private Infragistics.Win.Misc.UltraButton ubConferma;
        private Infragistics.Win.Misc.UltraButton ubAnnulla;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteVersione;
        private System.Windows.Forms.Label lblVersione;
        private System.Windows.Forms.CheckBox chkPubblicato;
        private System.Windows.Forms.CheckBox chkFlagAttiva;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor udteDtValF;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor udteDtValI;
        private System.Windows.Forms.Label lblDtValF;
        private System.Windows.Forms.Label lblDtValI;
        private Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit umeNumerosita;
        private System.Windows.Forms.Label lblNumerosita;
        private System.Windows.Forms.CheckBox chkCreaDefault;
        private Infragistics.Win.Misc.UltraPanel UltraPanelStruttura;
        private DatiCliniciUI.UserControls.ucDcDesigner ucDcDesigner;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControlDatiClinici;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage2;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl3;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl4;
        private System.Windows.Forms.Integration.ElementHost ehViewer;
        private WpfControls40.ucDcViewer ucDcViewer;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanelDC;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanelComandi;
        private Infragistics.Win.Misc.UltraButton ubCopia;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl5;
        internal ExtendedRichTextBox.RichTextBoxPrintCtrl rtbRichTextBox;
        private Infragistics.Win.Misc.UltraButton ubDizionarioQuick;
    }
}