namespace UnicodeSrl.ScciManagement
{
    partial class frmPUConfigPC
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton1 = new Infragistics.Win.UltraWinEditors.EditorButton("Zoom");
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            this.ultraGroupBoxForm = new Infragistics.Win.Misc.UltraGroupBox();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.picView = new System.Windows.Forms.PictureBox();
            this.pnlCopiaScheda = new System.Windows.Forms.Panel();
            this.ugbChiamataNumeri = new Infragistics.Win.Misc.UltraGroupBox();
            this.chkApriCartellaChiamata = new System.Windows.Forms.CheckBox();
            this.utxtAgendaChiamataNumeri = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblAgendaChiamataNumeriDes = new System.Windows.Forms.Label();
            this.lblAgendaChiamataNumeri = new System.Windows.Forms.Label();
            this.umeFontCoefficiente = new Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit();
            this.lblFontCoeff = new System.Windows.Forms.Label();
            this.lblRtfZoomInfo = new System.Windows.Forms.Label();
            this.umeRtfZoom = new Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit();
            this.lblRtfZoom = new System.Windows.Forms.Label();
            this.ugbDebug = new Infragistics.Win.Misc.UltraGroupBox();
            this.lblTrace = new System.Windows.Forms.Label();
            this.chkTrace = new System.Windows.Forms.CheckBox();
            this.uteDescrizione = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.uteCodPC = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblDescrizione = new System.Windows.Forms.Label();
            this.lblCodPC = new System.Windows.Forms.Label();
            this.ubConferma = new Infragistics.Win.Misc.UltraButton();
            this.ubAnnulla = new Infragistics.Win.Misc.UltraButton();
            this.ultraToolbarsManagerForm = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmPUConfigPC_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUConfigPC_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUConfigPC_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.ugbIpovedente = new Infragistics.Win.Misc.UltraGroupBox();
            this.chkIpovedente = new System.Windows.Forms.CheckBox();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBoxForm)).BeginInit();
            this.ultraGroupBoxForm.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picView)).BeginInit();
            this.pnlCopiaScheda.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugbChiamataNumeri)).BeginInit();
            this.ugbChiamataNumeri.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.utxtAgendaChiamataNumeri)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugbDebug)).BeginInit();
            this.ugbDebug.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodPC)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraToolbarsManagerForm)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugbIpovedente)).BeginInit();
            this.ugbIpovedente.SuspendLayout();
            this.SuspendLayout();
                                                this.ultraGroupBoxForm.Controls.Add(this.TableLayoutPanel);
            this.ultraGroupBoxForm.Controls.Add(this.ubConferma);
            this.ultraGroupBoxForm.Controls.Add(this.ubAnnulla);
            this.ultraGroupBoxForm.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBoxForm.Location = new System.Drawing.Point(8, 31);
            this.ultraGroupBoxForm.Name = "ultraGroupBoxForm";
            this.ultraGroupBoxForm.Size = new System.Drawing.Size(876, 425);
            this.ultraGroupBoxForm.TabIndex = 0;
            this.ultraGroupBoxForm.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.TableLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanel.ColumnCount = 2;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 140F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.Controls.Add(this.picView, 0, 1);
            this.TableLayoutPanel.Controls.Add(this.pnlCopiaScheda, 1, 0);
            this.TableLayoutPanel.Location = new System.Drawing.Point(6, 6);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(864, 384);
            this.TableLayoutPanel.TabIndex = 7;
                                                this.picView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picView.Location = new System.Drawing.Point(3, 131);
            this.picView.Name = "picView";
            this.picView.Size = new System.Drawing.Size(134, 122);
            this.picView.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picView.TabIndex = 1;
            this.picView.TabStop = false;
                                                this.pnlCopiaScheda.Controls.Add(this.ugbIpovedente);
            this.pnlCopiaScheda.Controls.Add(this.ugbChiamataNumeri);
            this.pnlCopiaScheda.Controls.Add(this.umeFontCoefficiente);
            this.pnlCopiaScheda.Controls.Add(this.lblFontCoeff);
            this.pnlCopiaScheda.Controls.Add(this.lblRtfZoomInfo);
            this.pnlCopiaScheda.Controls.Add(this.umeRtfZoom);
            this.pnlCopiaScheda.Controls.Add(this.lblRtfZoom);
            this.pnlCopiaScheda.Controls.Add(this.ugbDebug);
            this.pnlCopiaScheda.Controls.Add(this.uteDescrizione);
            this.pnlCopiaScheda.Controls.Add(this.uteCodPC);
            this.pnlCopiaScheda.Controls.Add(this.lblDescrizione);
            this.pnlCopiaScheda.Controls.Add(this.lblCodPC);
            this.pnlCopiaScheda.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlCopiaScheda.Location = new System.Drawing.Point(143, 3);
            this.pnlCopiaScheda.Name = "pnlCopiaScheda";
            this.TableLayoutPanel.SetRowSpan(this.pnlCopiaScheda, 3);
            this.pnlCopiaScheda.Size = new System.Drawing.Size(718, 378);
            this.pnlCopiaScheda.TabIndex = 0;
                                                this.ugbChiamataNumeri.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ugbChiamataNumeri.Controls.Add(this.chkApriCartellaChiamata);
            this.ugbChiamataNumeri.Controls.Add(this.utxtAgendaChiamataNumeri);
            this.ugbChiamataNumeri.Controls.Add(this.lblAgendaChiamataNumeriDes);
            this.ugbChiamataNumeri.Controls.Add(this.lblAgendaChiamataNumeri);
            appearance2.FontData.BoldAsString = "True";
            this.ugbChiamataNumeri.HeaderAppearance = appearance2;
            this.ugbChiamataNumeri.Location = new System.Drawing.Point(3, 196);
            this.ugbChiamataNumeri.Name = "ugbChiamataNumeri";
            this.ugbChiamataNumeri.Size = new System.Drawing.Size(712, 87);
            this.ugbChiamataNumeri.TabIndex = 5;
            this.ugbChiamataNumeri.Text = "Chiamata Numeri";
            this.ugbChiamataNumeri.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.chkApriCartellaChiamata.BackColor = System.Drawing.Color.Transparent;
            this.chkApriCartellaChiamata.Location = new System.Drawing.Point(11, 56);
            this.chkApriCartellaChiamata.Name = "chkApriCartellaChiamata";
            this.chkApriCartellaChiamata.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkApriCartellaChiamata.Size = new System.Drawing.Size(151, 19);
            this.chkApriCartellaChiamata.TabIndex = 1;
            this.chkApriCartellaChiamata.Text = "Apri Cartella su Chiamata";
            this.chkApriCartellaChiamata.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkApriCartellaChiamata.UseVisualStyleBackColor = false;
                                                editorButton1.Key = "Zoom";
            editorButton1.Text = "...";
            this.utxtAgendaChiamataNumeri.ButtonsRight.Add(editorButton1);
            this.utxtAgendaChiamataNumeri.Location = new System.Drawing.Point(148, 26);
            this.utxtAgendaChiamataNumeri.Name = "utxtAgendaChiamataNumeri";
            this.utxtAgendaChiamataNumeri.Size = new System.Drawing.Size(146, 22);
            this.utxtAgendaChiamataNumeri.TabIndex = 0;
            this.utxtAgendaChiamataNumeri.ValueChanged += new System.EventHandler(this.utxtAgendaChiamataNumeri_ValueChanged);
            this.utxtAgendaChiamataNumeri.EditorButtonClick += new Infragistics.Win.UltraWinEditors.EditorButtonEventHandler(this.utxtAgendaChiamataNumeri_EditorButtonClick);
                                                this.lblAgendaChiamataNumeriDes.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblAgendaChiamataNumeriDes.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblAgendaChiamataNumeriDes.Location = new System.Drawing.Point(300, 25);
            this.lblAgendaChiamataNumeriDes.Name = "lblAgendaChiamataNumeriDes";
            this.lblAgendaChiamataNumeriDes.Size = new System.Drawing.Size(402, 24);
            this.lblAgendaChiamataNumeriDes.TabIndex = 27;
            this.lblAgendaChiamataNumeriDes.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.lblAgendaChiamataNumeri.AutoSize = true;
            this.lblAgendaChiamataNumeri.BackColor = System.Drawing.Color.Transparent;
            this.lblAgendaChiamataNumeri.Location = new System.Drawing.Point(8, 31);
            this.lblAgendaChiamataNumeri.Name = "lblAgendaChiamataNumeri";
            this.lblAgendaChiamataNumeri.Size = new System.Drawing.Size(99, 13);
            this.lblAgendaChiamataNumeri.TabIndex = 26;
            this.lblAgendaChiamataNumeri.Text = "Agenda Predefinita";
                                                appearance3.TextHAlignAsString = "Right";
            this.umeFontCoefficiente.Appearance = appearance3;
            this.umeFontCoefficiente.EditAs = Infragistics.Win.UltraWinMaskedEdit.EditAsType.Double;
            this.umeFontCoefficiente.Location = new System.Drawing.Point(151, 97);
            this.umeFontCoefficiente.Name = "umeFontCoefficiente";
            this.umeFontCoefficiente.NonAutoSizeHeight = 20;
            this.umeFontCoefficiente.Size = new System.Drawing.Size(88, 21);
            this.umeFontCoefficiente.TabIndex = 3;
                                                this.lblFontCoeff.BackColor = System.Drawing.Color.Transparent;
            this.lblFontCoeff.Location = new System.Drawing.Point(11, 101);
            this.lblFontCoeff.Name = "lblFontCoeff";
            this.lblFontCoeff.Size = new System.Drawing.Size(94, 20);
            this.lblFontCoeff.TabIndex = 24;
            this.lblFontCoeff.Text = "Coefficiente Font";
                                                this.lblRtfZoomInfo.BackColor = System.Drawing.Color.Transparent;
            this.lblRtfZoomInfo.Location = new System.Drawing.Point(245, 74);
            this.lblRtfZoomInfo.Name = "lblRtfZoomInfo";
            this.lblRtfZoomInfo.Size = new System.Drawing.Size(218, 20);
            this.lblRtfZoomInfo.TabIndex = 22;
            this.lblRtfZoomInfo.Text = "(Da 0,10 a 64,00)";
                                                appearance4.TextHAlignAsString = "Right";
            this.umeRtfZoom.Appearance = appearance4;
            this.umeRtfZoom.EditAs = Infragistics.Win.UltraWinMaskedEdit.EditAsType.Double;
            this.umeRtfZoom.Location = new System.Drawing.Point(151, 70);
            this.umeRtfZoom.Name = "umeRtfZoom";
            this.umeRtfZoom.NonAutoSizeHeight = 20;
            this.umeRtfZoom.Size = new System.Drawing.Size(88, 21);
            this.umeRtfZoom.TabIndex = 2;
                                                this.lblRtfZoom.BackColor = System.Drawing.Color.Transparent;
            this.lblRtfZoom.Location = new System.Drawing.Point(11, 74);
            this.lblRtfZoom.Name = "lblRtfZoom";
            this.lblRtfZoom.Size = new System.Drawing.Size(77, 20);
            this.lblRtfZoom.TabIndex = 21;
            this.lblRtfZoom.Text = "Rtf Zoom";
                                                this.ugbDebug.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ugbDebug.Controls.Add(this.lblTrace);
            this.ugbDebug.Controls.Add(this.chkTrace);
            appearance5.FontData.BoldAsString = "True";
            this.ugbDebug.HeaderAppearance = appearance5;
            this.ugbDebug.Location = new System.Drawing.Point(3, 128);
            this.ugbDebug.Name = "ugbDebug";
            this.ugbDebug.Size = new System.Drawing.Size(712, 62);
            this.ugbDebug.TabIndex = 4;
            this.ugbDebug.Text = "Debug";
            this.ugbDebug.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.lblTrace.AutoSize = true;
            this.lblTrace.Location = new System.Drawing.Point(134, 35);
            this.lblTrace.Name = "lblTrace";
            this.lblTrace.Size = new System.Drawing.Size(331, 13);
            this.lblTrace.TabIndex = 10;
            this.lblTrace.Text = "(sulle macchine server questa impostazione NON viene considerata)";
                                                this.chkTrace.BackColor = System.Drawing.Color.Transparent;
            this.chkTrace.Location = new System.Drawing.Point(13, 33);
            this.chkTrace.Name = "chkTrace";
            this.chkTrace.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkTrace.Size = new System.Drawing.Size(106, 19);
            this.chkTrace.TabIndex = 0;
            this.chkTrace.Text = "Abilita Trace";
            this.chkTrace.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkTrace.UseVisualStyleBackColor = false;
                                                this.uteDescrizione.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.uteDescrizione.Location = new System.Drawing.Point(151, 42);
            this.uteDescrizione.Name = "uteDescrizione";
            this.uteDescrizione.Size = new System.Drawing.Size(554, 22);
            this.uteDescrizione.TabIndex = 1;
                                                this.uteCodPC.Location = new System.Drawing.Point(151, 14);
            this.uteCodPC.Name = "uteCodPC";
            this.uteCodPC.Size = new System.Drawing.Size(195, 22);
            this.uteCodPC.TabIndex = 0;
                                                this.lblDescrizione.AutoSize = true;
            this.lblDescrizione.BackColor = System.Drawing.Color.Transparent;
            this.lblDescrizione.Location = new System.Drawing.Point(11, 46);
            this.lblDescrizione.Name = "lblDescrizione";
            this.lblDescrizione.Size = new System.Drawing.Size(61, 13);
            this.lblDescrizione.TabIndex = 14;
            this.lblDescrizione.Text = "Descrizione";
                                                this.lblCodPC.AutoSize = true;
            this.lblCodPC.BackColor = System.Drawing.Color.Transparent;
            this.lblCodPC.Location = new System.Drawing.Point(11, 18);
            this.lblCodPC.Name = "lblCodPC";
            this.lblCodPC.Size = new System.Drawing.Size(50, 13);
            this.lblCodPC.TabIndex = 13;
            this.lblCodPC.Text = "Nome PC";
                                                this.ubConferma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubConferma.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubConferma.Location = new System.Drawing.Point(795, 396);
            this.ubConferma.Name = "ubConferma";
            this.ubConferma.Size = new System.Drawing.Size(75, 23);
            this.ubConferma.TabIndex = 5;
            this.ubConferma.Text = "&Conferma";
            this.ubConferma.Click += new System.EventHandler(this.ubConferma_Click);
                                                this.ubAnnulla.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ubAnnulla.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubAnnulla.Location = new System.Drawing.Point(5, 396);
            this.ubAnnulla.Name = "ubAnnulla";
            this.ubAnnulla.Size = new System.Drawing.Size(75, 23);
            this.ubAnnulla.TabIndex = 4;
            this.ubAnnulla.Text = "&Annulla";
            this.ubAnnulla.Click += new System.EventHandler(this.ubAnnulla_Click);
                                                this.ultraToolbarsManagerForm.DesignerFlags = 0;
            this.ultraToolbarsManagerForm.DockWithinContainer = this;
            this.ultraToolbarsManagerForm.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
            this.ultraToolbarsManagerForm.FormDisplayStyle = Infragistics.Win.UltraWinToolbars.FormDisplayStyle.RoundedSizable;
            this.ultraToolbarsManagerForm.RuntimeCustomizationOptions = Infragistics.Win.UltraWinToolbars.RuntimeCustomizationOptions.None;
            this.ultraToolbarsManagerForm.Style = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2010;
                                                this._frmPUConfigPC_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUConfigPC_Toolbars_Dock_Area_Left.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUConfigPC_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmPUConfigPC_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUConfigPC_Toolbars_Dock_Area_Left.InitialResizeAreaExtent = 8;
            this._frmPUConfigPC_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 31);
            this._frmPUConfigPC_Toolbars_Dock_Area_Left.Name = "_frmPUConfigPC_Toolbars_Dock_Area_Left";
            this._frmPUConfigPC_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(8, 425);
            this._frmPUConfigPC_Toolbars_Dock_Area_Left.ToolbarsManager = this.ultraToolbarsManagerForm;
                                                this._frmPUConfigPC_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUConfigPC_Toolbars_Dock_Area_Right.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUConfigPC_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmPUConfigPC_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUConfigPC_Toolbars_Dock_Area_Right.InitialResizeAreaExtent = 8;
            this._frmPUConfigPC_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(884, 31);
            this._frmPUConfigPC_Toolbars_Dock_Area_Right.Name = "_frmPUConfigPC_Toolbars_Dock_Area_Right";
            this._frmPUConfigPC_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(8, 425);
            this._frmPUConfigPC_Toolbars_Dock_Area_Right.ToolbarsManager = this.ultraToolbarsManagerForm;
                                                this._frmPUConfigPC_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUConfigPC_Toolbars_Dock_Area_Top.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUConfigPC_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmPUConfigPC_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUConfigPC_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmPUConfigPC_Toolbars_Dock_Area_Top.Name = "_frmPUConfigPC_Toolbars_Dock_Area_Top";
            this._frmPUConfigPC_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(892, 31);
            this._frmPUConfigPC_Toolbars_Dock_Area_Top.ToolbarsManager = this.ultraToolbarsManagerForm;
                                                this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.InitialResizeAreaExtent = 8;
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 456);
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.Name = "_frmPUConfigPC_Toolbars_Dock_Area_Bottom";
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(892, 8);
            this._frmPUConfigPC_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.ultraToolbarsManagerForm;
                                                this.ugbIpovedente.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ugbIpovedente.Controls.Add(this.chkIpovedente);
            appearance1.FontData.BoldAsString = "True";
            this.ugbIpovedente.HeaderAppearance = appearance1;
            this.ugbIpovedente.Location = new System.Drawing.Point(3, 288);
            this.ugbIpovedente.Name = "ugbIpovedente";
            this.ugbIpovedente.Size = new System.Drawing.Size(712, 47);
            this.ugbIpovedente.TabIndex = 28;
            this.ugbIpovedente.Text = "Ipovedente";
            this.ugbIpovedente.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.chkIpovedente.BackColor = System.Drawing.Color.Transparent;
            this.chkIpovedente.Location = new System.Drawing.Point(11, 20);
            this.chkIpovedente.Name = "chkIpovedente";
            this.chkIpovedente.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkIpovedente.Size = new System.Drawing.Size(165, 19);
            this.chkIpovedente.TabIndex = 1;
            this.chkIpovedente.Text = "Abilita Sessione Ipovedente";
            this.chkIpovedente.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkIpovedente.UseVisualStyleBackColor = false;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(892, 464);
            this.Controls.Add(this.ultraGroupBoxForm);
            this.Controls.Add(this._frmPUConfigPC_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmPUConfigPC_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmPUConfigPC_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmPUConfigPC_Toolbars_Dock_Area_Top);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "frmPUConfigPC";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmPUConfigPC";
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBoxForm)).EndInit();
            this.ultraGroupBoxForm.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picView)).EndInit();
            this.pnlCopiaScheda.ResumeLayout(false);
            this.pnlCopiaScheda.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugbChiamataNumeri)).EndInit();
            this.ugbChiamataNumeri.ResumeLayout(false);
            this.ugbChiamataNumeri.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.utxtAgendaChiamataNumeri)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugbDebug)).EndInit();
            this.ugbDebug.ResumeLayout(false);
            this.ugbDebug.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodPC)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraToolbarsManagerForm)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugbIpovedente)).EndInit();
            this.ugbIpovedente.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBoxForm;
        private Infragistics.Win.Misc.UltraButton ubConferma;
        private Infragistics.Win.Misc.UltraButton ubAnnulla;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager ultraToolbarsManagerForm;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUConfigPC_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUConfigPC_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUConfigPC_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUConfigPC_Toolbars_Dock_Area_Top;
        internal System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        internal System.Windows.Forms.PictureBox picView;
        private System.Windows.Forms.Panel pnlCopiaScheda;
        private Infragistics.Win.Misc.UltraGroupBox ugbDebug;
        private System.Windows.Forms.Label lblTrace;
        private System.Windows.Forms.CheckBox chkTrace;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteDescrizione;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteCodPC;
        private System.Windows.Forms.Label lblDescrizione;
        private System.Windows.Forms.Label lblCodPC;
        private Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit umeRtfZoom;
        private System.Windows.Forms.Label lblRtfZoom;
        private System.Windows.Forms.Label lblRtfZoomInfo;
        private Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit umeFontCoefficiente;
        private System.Windows.Forms.Label lblFontCoeff;
        private System.Windows.Forms.Label lblAgendaChiamataNumeriDes;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor utxtAgendaChiamataNumeri;
        private System.Windows.Forms.Label lblAgendaChiamataNumeri;
        private Infragistics.Win.Misc.UltraGroupBox ugbChiamataNumeri;
        private System.Windows.Forms.CheckBox chkApriCartellaChiamata;
        private Infragistics.Win.Misc.UltraGroupBox ugbIpovedente;
        private System.Windows.Forms.CheckBox chkIpovedente;
    }
}