namespace UnicodeSrl.ScciManagement
{
    partial class frmPUProtocolliAttivitaTempi
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab4 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.lblDeltaAlle00 = new System.Windows.Forms.Label();
            this.chkDeltaAlle00 = new System.Windows.Forms.CheckBox();
            this.lblDeltaMinuti = new System.Windows.Forms.Label();
            this.umeDeltaMinuti = new Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit();
            this.lblDeltaOre = new System.Windows.Forms.Label();
            this.umeDeltaOre = new Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit();
            this.lblDeltaGiorni = new System.Windows.Forms.Label();
            this.umeDeltaGiorni = new Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit();
            this.uteDescrizione = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.uteCodice = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblDescrizione = new System.Windows.Forms.Label();
            this.lblCodice = new System.Windows.Forms.Label();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.PicImage = new System.Windows.Forms.PictureBox();
            this.ultraTabPageControl4 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucMultiSelectTipoTask = new UnicodeSrl.ScciCore.ucMultiSelect();
            this.UltraToolbarsManagerForm = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.ubApplica = new Infragistics.Win.Misc.UltraButton();
            this.UltraTabControl = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ubConferma = new Infragistics.Win.Misc.UltraButton();
            this.ubAnnulla = new Infragistics.Win.Misc.UltraButton();
            this.ultraTabPageControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodice)).BeginInit();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).BeginInit();
            this.ultraTabPageControl4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManagerForm)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).BeginInit();
            this.UltraTabControl.SuspendLayout();
            this.ultraTabSharedControlsPage1.SuspendLayout();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.lblDeltaAlle00);
            this.ultraTabPageControl1.Controls.Add(this.chkDeltaAlle00);
            this.ultraTabPageControl1.Controls.Add(this.lblDeltaMinuti);
            this.ultraTabPageControl1.Controls.Add(this.umeDeltaMinuti);
            this.ultraTabPageControl1.Controls.Add(this.lblDeltaOre);
            this.ultraTabPageControl1.Controls.Add(this.umeDeltaOre);
            this.ultraTabPageControl1.Controls.Add(this.lblDeltaGiorni);
            this.ultraTabPageControl1.Controls.Add(this.umeDeltaGiorni);
            this.ultraTabPageControl1.Controls.Add(this.uteDescrizione);
            this.ultraTabPageControl1.Controls.Add(this.uteCodice);
            this.ultraTabPageControl1.Controls.Add(this.lblDescrizione);
            this.ultraTabPageControl1.Controls.Add(this.lblCodice);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(694, 475);
                                                this.lblDeltaAlle00.BackColor = System.Drawing.Color.Transparent;
            this.lblDeltaAlle00.Location = new System.Drawing.Point(140, 143);
            this.lblDeltaAlle00.Name = "lblDeltaAlle00";
            this.lblDeltaAlle00.Size = new System.Drawing.Size(129, 20);
            this.lblDeltaAlle00.TabIndex = 11;
            this.lblDeltaAlle00.Text = "Delta allle 00";
                                                this.chkDeltaAlle00.BackColor = System.Drawing.Color.Transparent;
            this.chkDeltaAlle00.Location = new System.Drawing.Point(286, 141);
            this.chkDeltaAlle00.Name = "chkDeltaAlle00";
            this.chkDeltaAlle00.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkDeltaAlle00.Size = new System.Drawing.Size(14, 19);
            this.chkDeltaAlle00.TabIndex = 12;
            this.chkDeltaAlle00.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkDeltaAlle00.UseVisualStyleBackColor = false;
                                                this.lblDeltaMinuti.BackColor = System.Drawing.Color.Transparent;
            this.lblDeltaMinuti.Location = new System.Drawing.Point(140, 118);
            this.lblDeltaMinuti.Name = "lblDeltaMinuti";
            this.lblDeltaMinuti.Size = new System.Drawing.Size(140, 20);
            this.lblDeltaMinuti.TabIndex = 9;
            this.lblDeltaMinuti.Text = "Delta Minuti";
                                                appearance1.TextHAlignAsString = "Right";
            this.umeDeltaMinuti.Appearance = appearance1;
            this.umeDeltaMinuti.EditAs = Infragistics.Win.UltraWinMaskedEdit.EditAsType.UseSpecifiedMask;
            this.umeDeltaMinuti.InputMask = "nnnnn";
            this.umeDeltaMinuti.Location = new System.Drawing.Point(286, 115);
            this.umeDeltaMinuti.Name = "umeDeltaMinuti";
            this.umeDeltaMinuti.NonAutoSizeHeight = 20;
            this.umeDeltaMinuti.Size = new System.Drawing.Size(101, 20);
            this.umeDeltaMinuti.TabIndex = 10;
                                                this.lblDeltaOre.BackColor = System.Drawing.Color.Transparent;
            this.lblDeltaOre.Location = new System.Drawing.Point(140, 92);
            this.lblDeltaOre.Name = "lblDeltaOre";
            this.lblDeltaOre.Size = new System.Drawing.Size(140, 20);
            this.lblDeltaOre.TabIndex = 7;
            this.lblDeltaOre.Text = "Delta Ore";
                                                appearance2.TextHAlignAsString = "Right";
            this.umeDeltaOre.Appearance = appearance2;
            this.umeDeltaOre.EditAs = Infragistics.Win.UltraWinMaskedEdit.EditAsType.UseSpecifiedMask;
            this.umeDeltaOre.InputMask = "nnnnn";
            this.umeDeltaOre.Location = new System.Drawing.Point(286, 89);
            this.umeDeltaOre.Name = "umeDeltaOre";
            this.umeDeltaOre.NonAutoSizeHeight = 20;
            this.umeDeltaOre.Size = new System.Drawing.Size(101, 20);
            this.umeDeltaOre.TabIndex = 8;
                                                this.lblDeltaGiorni.BackColor = System.Drawing.Color.Transparent;
            this.lblDeltaGiorni.Location = new System.Drawing.Point(140, 66);
            this.lblDeltaGiorni.Name = "lblDeltaGiorni";
            this.lblDeltaGiorni.Size = new System.Drawing.Size(140, 20);
            this.lblDeltaGiorni.TabIndex = 5;
            this.lblDeltaGiorni.Text = "Delta Giorni";
                                                appearance3.TextHAlignAsString = "Right";
            this.umeDeltaGiorni.Appearance = appearance3;
            this.umeDeltaGiorni.EditAs = Infragistics.Win.UltraWinMaskedEdit.EditAsType.UseSpecifiedMask;
            this.umeDeltaGiorni.InputMask = "nnnnn";
            this.umeDeltaGiorni.Location = new System.Drawing.Point(286, 63);
            this.umeDeltaGiorni.Name = "umeDeltaGiorni";
            this.umeDeltaGiorni.NonAutoSizeHeight = 20;
            this.umeDeltaGiorni.Size = new System.Drawing.Size(101, 20);
            this.umeDeltaGiorni.TabIndex = 6;
                                                this.uteDescrizione.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.uteDescrizione.Location = new System.Drawing.Point(286, 36);
            this.uteDescrizione.Name = "uteDescrizione";
            this.uteDescrizione.Size = new System.Drawing.Size(398, 21);
            this.uteDescrizione.TabIndex = 4;
            this.uteDescrizione.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.uteCodice.Location = new System.Drawing.Point(286, 8);
            this.uteCodice.Name = "uteCodice";
            this.uteCodice.Size = new System.Drawing.Size(101, 21);
            this.uteCodice.TabIndex = 2;
            this.uteCodice.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.lblDescrizione.BackColor = System.Drawing.Color.Transparent;
            this.lblDescrizione.Location = new System.Drawing.Point(140, 40);
            this.lblDescrizione.Name = "lblDescrizione";
            this.lblDescrizione.Size = new System.Drawing.Size(140, 20);
            this.lblDescrizione.TabIndex = 3;
            this.lblDescrizione.Text = "Descrizione";
                                                this.lblCodice.BackColor = System.Drawing.Color.Transparent;
            this.lblCodice.Location = new System.Drawing.Point(140, 12);
            this.lblCodice.Name = "lblCodice";
            this.lblCodice.Size = new System.Drawing.Size(140, 20);
            this.lblCodice.TabIndex = 1;
            this.lblCodice.Text = "Codice";
                                                this.TableLayoutPanel.ColumnCount = 1;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TableLayoutPanel.Controls.Add(this.PicImage, 0, 1);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.TableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(134, 475);
            this.TableLayoutPanel.TabIndex = 0;
                                                this.PicImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PicImage.Location = new System.Drawing.Point(3, 176);
            this.PicImage.Name = "PicImage";
            this.PicImage.Size = new System.Drawing.Size(128, 122);
            this.PicImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PicImage.TabIndex = 0;
            this.PicImage.TabStop = false;
                                                this.ultraTabPageControl4.Controls.Add(this.ucMultiSelectTipoTask);
            this.ultraTabPageControl4.Controls.Add(this.TableLayoutPanel);
            this.ultraTabPageControl4.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl4.Name = "ultraTabPageControl4";
            this.ultraTabPageControl4.Size = new System.Drawing.Size(694, 475);
                                                this.ucMultiSelectTipoTask.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucMultiSelectTipoTask.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ucMultiSelectTipoTask.GridDXCaption = "";
            this.ucMultiSelectTipoTask.GridDXCaptionColumnKey = "";
            this.ucMultiSelectTipoTask.GridSXCaption = "";
            this.ucMultiSelectTipoTask.GridSXCaptionColumnKey = "";
            this.ucMultiSelectTipoTask.Location = new System.Drawing.Point(134, 0);
            this.ucMultiSelectTipoTask.Name = "ucMultiSelectTipoTask";
            this.ucMultiSelectTipoTask.Size = new System.Drawing.Size(560, 475);
            this.ucMultiSelectTipoTask.TabIndex = 1;
            this.ucMultiSelectTipoTask.ViewDataSetDX = null;
            this.ucMultiSelectTipoTask.ViewDataSetSX = null;
            this.ucMultiSelectTipoTask.ViewDataViewDX = null;
            this.ucMultiSelectTipoTask.ViewDataViewSX = null;
            this.ucMultiSelectTipoTask.ViewShowAll = true;
            this.ucMultiSelectTipoTask.ViewShowFind = true;
            this.ucMultiSelectTipoTask.GridSXInitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucMultiSelect_GridSXInitializeLayout);
            this.ucMultiSelectTipoTask.GridSXInitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucMultiSelect_GridSXInitializeRow);
            this.ucMultiSelectTipoTask.GridDXInitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucMultiSelect_GridDXInitializeLayout);
            this.ucMultiSelectTipoTask.GridDXInitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucMultiSelect_GridDXInitializeRow);
            this.ucMultiSelectTipoTask.GridChange += new UnicodeSrl.ScciCore.ChangeEventHandler(this.ute_ValueChanged);
                                                this.UltraToolbarsManagerForm.DesignerFlags = 0;
            this.UltraToolbarsManagerForm.DockWithinContainer = this;
            this.UltraToolbarsManagerForm.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
            this.UltraToolbarsManagerForm.FormDisplayStyle = Infragistics.Win.UltraWinToolbars.FormDisplayStyle.RoundedSizable;
            this.UltraToolbarsManagerForm.RuntimeCustomizationOptions = Infragistics.Win.UltraWinToolbars.RuntimeCustomizationOptions.None;
            this.UltraToolbarsManagerForm.Style = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
                                                this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.Name = "_frmPUSchedeCopia_Toolbars_Dock_Area_Top";
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(724, 31);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManagerForm;
                                                this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.InitialResizeAreaExtent = 8;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 570);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.Name = "_frmPUSchedeCopia_Toolbars_Dock_Area_Bottom";
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(724, 8);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManagerForm;
                                                this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.InitialResizeAreaExtent = 8;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 31);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.Name = "_frmPUSchedeCopia_Toolbars_Dock_Area_Left";
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(8, 539);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManagerForm;
                                                this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.InitialResizeAreaExtent = 8;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(716, 31);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.Name = "_frmPUSchedeCopia_Toolbars_Dock_Area_Right";
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(8, 539);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManagerForm;
                                                this.UltraGroupBox.Controls.Add(this.ubApplica);
            this.UltraGroupBox.Controls.Add(this.UltraTabControl);
            this.UltraGroupBox.Controls.Add(this.ubConferma);
            this.UltraGroupBox.Controls.Add(this.ubAnnulla);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(8, 31);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(708, 539);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.ubApplica.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.ubApplica.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubApplica.Location = new System.Drawing.Point(304, 510);
            this.ubApplica.Name = "ubApplica";
            this.ubApplica.Size = new System.Drawing.Size(75, 23);
            this.ubApplica.TabIndex = 2;
            this.ubApplica.Text = "Applica";
            this.ubApplica.Click += new System.EventHandler(this.ubApplica_Click);
                                                this.UltraTabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.UltraTabControl.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl4);
            this.UltraTabControl.Location = new System.Drawing.Point(6, 6);
            this.UltraTabControl.Name = "UltraTabControl";
            this.UltraTabControl.SharedControls.AddRange(new System.Windows.Forms.Control[] {
            this.TableLayoutPanel});
            this.UltraTabControl.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControl.Size = new System.Drawing.Size(696, 498);
            this.UltraTabControl.TabIndex = 0;
            ultraTab1.Key = "tab1";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Tempi";
            ultraTab4.Key = "tab2";
            ultraTab4.TabPage = this.ultraTabPageControl4;
            ultraTab4.Text = "Task";
            this.UltraTabControl.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1,
            ultraTab4});
            this.UltraTabControl.TabStop = false;
            this.UltraTabControl.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Controls.Add(this.TableLayoutPanel);
            this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(694, 475);
                                                this.ubConferma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubConferma.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubConferma.Location = new System.Drawing.Point(627, 510);
            this.ubConferma.Name = "ubConferma";
            this.ubConferma.Size = new System.Drawing.Size(75, 23);
            this.ubConferma.TabIndex = 3;
            this.ubConferma.Text = "&Conferma";
            this.ubConferma.Click += new System.EventHandler(this.ubConferma_Click);
                                                this.ubAnnulla.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ubAnnulla.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubAnnulla.Location = new System.Drawing.Point(6, 510);
            this.ubAnnulla.Name = "ubAnnulla";
            this.ubAnnulla.Size = new System.Drawing.Size(75, 23);
            this.ubAnnulla.TabIndex = 1;
            this.ubAnnulla.Text = "&Annulla";
            this.ubAnnulla.Click += new System.EventHandler(this.ubAnnulla_Click);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(724, 578);
            this.ControlBox = false;
            this.Controls.Add(this.UltraGroupBox);
            this.Controls.Add(this._frmPUSchedeCopia_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmPUSchedeCopia_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmPUSchedeCopia_Toolbars_Dock_Area_Top);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmPUProtocolliAttivitaTempi";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmPUProtocolliAttivitaTempi";
            this.ultraTabPageControl1.ResumeLayout(false);
            this.ultraTabPageControl1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodice)).EndInit();
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).EndInit();
            this.ultraTabPageControl4.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManagerForm)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).EndInit();
            this.UltraTabControl.ResumeLayout(false);
            this.ultraTabSharedControlsPage1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManagerForm;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeCopia_Toolbars_Dock_Area_Top;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeCopia_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeCopia_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeCopia_Toolbars_Dock_Area_Right;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.Misc.UltraButton ubConferma;
        private Infragistics.Win.Misc.UltraButton ubAnnulla;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControl;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        private System.Windows.Forms.PictureBox PicImage;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteDescrizione;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteCodice;
        private System.Windows.Forms.Label lblDescrizione;
        private System.Windows.Forms.Label lblCodice;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl4;
        private ScciCore.ucMultiSelect ucMultiSelectTipoTask;
        private Infragistics.Win.Misc.UltraButton ubApplica;
        private System.Windows.Forms.Label lblDeltaGiorni;
        private Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit umeDeltaGiorni;
        private System.Windows.Forms.Label lblDeltaMinuti;
        private Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit umeDeltaMinuti;
        private System.Windows.Forms.Label lblDeltaOre;
        private Infragistics.Win.UltraWinMaskedEdit.UltraMaskedEdit umeDeltaOre;
        private System.Windows.Forms.CheckBox chkDeltaAlle00;
        private System.Windows.Forms.Label lblDeltaAlle00;
    }
}