namespace UnicodeSrl.ScciManagement
{
    partial class frmPUSchedeCopia
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            this.ultraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.picView = new System.Windows.Forms.PictureBox();
            this.pnlCopiaScheda = new System.Windows.Forms.Panel();
            this.ugbCopiaRelazioni = new Infragistics.Win.Misc.UltraGroupBox();
            this.chkCopiaFigli = new System.Windows.Forms.CheckBox();
            this.chkCopiaVersione = new System.Windows.Forms.CheckBox();
            this.chkCopiaUA = new System.Windows.Forms.CheckBox();
            this.chkCopiaPadri = new System.Windows.Forms.CheckBox();
            this.ugVersioni = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.uteDescrizione = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.uteCodice = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblDescrizione = new System.Windows.Forms.Label();
            this.lblCodice = new System.Windows.Forms.Label();
            this.ubConferma = new Infragistics.Win.Misc.UltraButton();
            this.ubAnnulla = new Infragistics.Win.Misc.UltraButton();
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.ultraToolbarsManagerForm = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.chkCopiaSchedeCopia = new System.Windows.Forms.CheckBox();
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).BeginInit();
            this.ultraGroupBox.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picView)).BeginInit();
            this.pnlCopiaScheda.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugbCopiaRelazioni)).BeginInit();
            this.ugbCopiaRelazioni.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugVersioni)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodice)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraToolbarsManagerForm)).BeginInit();
            this.SuspendLayout();
                                                this.ultraGroupBox.Controls.Add(this.TableLayoutPanel);
            this.ultraGroupBox.Controls.Add(this.ubConferma);
            this.ultraGroupBox.Controls.Add(this.ubAnnulla);
            this.ultraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ultraGroupBox.Location = new System.Drawing.Point(8, 32);
            this.ultraGroupBox.Name = "ultraGroupBox";
            this.ultraGroupBox.Size = new System.Drawing.Size(919, 421);
            this.ultraGroupBox.TabIndex = 0;
            this.ultraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.TableLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanel.ColumnCount = 2;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 140F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.Controls.Add(this.picView, 0, 1);
            this.TableLayoutPanel.Controls.Add(this.pnlCopiaScheda, 1, 0);
            this.TableLayoutPanel.Location = new System.Drawing.Point(6, 12);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(905, 374);
            this.TableLayoutPanel.TabIndex = 6;
                                                this.picView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picView.Location = new System.Drawing.Point(3, 126);
            this.picView.Name = "picView";
            this.picView.Size = new System.Drawing.Size(134, 122);
            this.picView.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picView.TabIndex = 1;
            this.picView.TabStop = false;
                                                this.pnlCopiaScheda.Controls.Add(this.ugbCopiaRelazioni);
            this.pnlCopiaScheda.Controls.Add(this.uteDescrizione);
            this.pnlCopiaScheda.Controls.Add(this.uteCodice);
            this.pnlCopiaScheda.Controls.Add(this.lblDescrizione);
            this.pnlCopiaScheda.Controls.Add(this.lblCodice);
            this.pnlCopiaScheda.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlCopiaScheda.Location = new System.Drawing.Point(143, 3);
            this.pnlCopiaScheda.Name = "pnlCopiaScheda";
            this.TableLayoutPanel.SetRowSpan(this.pnlCopiaScheda, 3);
            this.pnlCopiaScheda.Size = new System.Drawing.Size(759, 368);
            this.pnlCopiaScheda.TabIndex = 2;
                                                this.ugbCopiaRelazioni.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ugbCopiaRelazioni.Controls.Add(this.chkCopiaSchedeCopia);
            this.ugbCopiaRelazioni.Controls.Add(this.chkCopiaFigli);
            this.ugbCopiaRelazioni.Controls.Add(this.chkCopiaVersione);
            this.ugbCopiaRelazioni.Controls.Add(this.chkCopiaUA);
            this.ugbCopiaRelazioni.Controls.Add(this.chkCopiaPadri);
            this.ugbCopiaRelazioni.Controls.Add(this.ugVersioni);
            appearance13.FontData.BoldAsString = "True";
            this.ugbCopiaRelazioni.HeaderAppearance = appearance13;
            this.ugbCopiaRelazioni.Location = new System.Drawing.Point(14, 94);
            this.ugbCopiaRelazioni.Name = "ugbCopiaRelazioni";
            this.ugbCopiaRelazioni.Size = new System.Drawing.Size(732, 256);
            this.ugbCopiaRelazioni.TabIndex = 15;
            this.ugbCopiaRelazioni.Text = "Copia Relazioni";
            this.ugbCopiaRelazioni.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.chkCopiaFigli.BackColor = System.Drawing.Color.Transparent;
            this.chkCopiaFigli.Location = new System.Drawing.Point(13, 58);
            this.chkCopiaFigli.Name = "chkCopiaFigli";
            this.chkCopiaFigli.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkCopiaFigli.Size = new System.Drawing.Size(203, 19);
            this.chkCopiaFigli.TabIndex = 11;
            this.chkCopiaFigli.Text = "Copia relazione Schede Figli";
            this.chkCopiaFigli.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkCopiaFigli.UseVisualStyleBackColor = false;
                                                this.chkCopiaVersione.BackColor = System.Drawing.Color.Transparent;
            this.chkCopiaVersione.Location = new System.Drawing.Point(13, 111);
            this.chkCopiaVersione.Name = "chkCopiaVersione";
            this.chkCopiaVersione.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkCopiaVersione.Size = new System.Drawing.Size(203, 19);
            this.chkCopiaVersione.TabIndex = 13;
            this.chkCopiaVersione.Text = "Copia Versione";
            this.chkCopiaVersione.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkCopiaVersione.UseVisualStyleBackColor = false;
                                                this.chkCopiaUA.BackColor = System.Drawing.Color.Transparent;
            this.chkCopiaUA.Location = new System.Drawing.Point(13, 83);
            this.chkCopiaUA.Name = "chkCopiaUA";
            this.chkCopiaUA.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkCopiaUA.Size = new System.Drawing.Size(203, 19);
            this.chkCopiaUA.TabIndex = 12;
            this.chkCopiaUA.Text = "Copia relazione Unità Atomiche";
            this.chkCopiaUA.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkCopiaUA.UseVisualStyleBackColor = false;
                                                this.chkCopiaPadri.BackColor = System.Drawing.Color.Transparent;
            this.chkCopiaPadri.Location = new System.Drawing.Point(13, 33);
            this.chkCopiaPadri.Name = "chkCopiaPadri";
            this.chkCopiaPadri.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkCopiaPadri.Size = new System.Drawing.Size(203, 19);
            this.chkCopiaPadri.TabIndex = 9;
            this.chkCopiaPadri.Text = "Copia relazione Schede Padri";
            this.chkCopiaPadri.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkCopiaPadri.UseVisualStyleBackColor = false;
                                                this.ugVersioni.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugVersioni.DisplayLayout.Appearance = appearance1;
            this.ugVersioni.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugVersioni.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance2.BorderColor = System.Drawing.SystemColors.Window;
            this.ugVersioni.DisplayLayout.GroupByBox.Appearance = appearance2;
            appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugVersioni.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
            this.ugVersioni.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance4.BackColor2 = System.Drawing.SystemColors.Control;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugVersioni.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
            this.ugVersioni.DisplayLayout.MaxColScrollRegions = 1;
            this.ugVersioni.DisplayLayout.MaxRowScrollRegions = 1;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugVersioni.DisplayLayout.Override.ActiveCellAppearance = appearance5;
            appearance6.BackColor = System.Drawing.SystemColors.Highlight;
            appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugVersioni.DisplayLayout.Override.ActiveRowAppearance = appearance6;
            this.ugVersioni.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugVersioni.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            this.ugVersioni.DisplayLayout.Override.CardAreaAppearance = appearance7;
            appearance8.BorderColor = System.Drawing.Color.Silver;
            appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugVersioni.DisplayLayout.Override.CellAppearance = appearance8;
            this.ugVersioni.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.ugVersioni.DisplayLayout.Override.CellPadding = 0;
            appearance9.BackColor = System.Drawing.SystemColors.Control;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.ugVersioni.DisplayLayout.Override.GroupByRowAppearance = appearance9;
            appearance10.TextHAlignAsString = "Left";
            this.ugVersioni.DisplayLayout.Override.HeaderAppearance = appearance10;
            this.ugVersioni.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.ugVersioni.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            this.ugVersioni.DisplayLayout.Override.RowAppearance = appearance11;
            this.ugVersioni.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance12.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugVersioni.DisplayLayout.Override.TemplateAddRowAppearance = appearance12;
            this.ugVersioni.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugVersioni.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugVersioni.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugVersioni.Location = new System.Drawing.Point(52, 133);
            this.ugVersioni.Name = "ugVersioni";
            this.ugVersioni.Size = new System.Drawing.Size(674, 112);
            this.ugVersioni.TabIndex = 0;
            this.ugVersioni.Text = "ultraGrid1";
                                                this.uteDescrizione.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.uteDescrizione.Location = new System.Drawing.Point(87, 42);
            this.uteDescrizione.Name = "uteDescrizione";
            this.uteDescrizione.Size = new System.Drawing.Size(659, 22);
            this.uteDescrizione.TabIndex = 12;
                                                this.uteCodice.Location = new System.Drawing.Point(87, 14);
            this.uteCodice.Name = "uteCodice";
            this.uteCodice.Size = new System.Drawing.Size(101, 22);
            this.uteCodice.TabIndex = 11;
                                                this.lblDescrizione.BackColor = System.Drawing.Color.Transparent;
            this.lblDescrizione.Location = new System.Drawing.Point(11, 46);
            this.lblDescrizione.Name = "lblDescrizione";
            this.lblDescrizione.Size = new System.Drawing.Size(87, 20);
            this.lblDescrizione.TabIndex = 14;
            this.lblDescrizione.Text = "Descrizione";
                                                this.lblCodice.BackColor = System.Drawing.Color.Transparent;
            this.lblCodice.Location = new System.Drawing.Point(11, 18);
            this.lblCodice.Name = "lblCodice";
            this.lblCodice.Size = new System.Drawing.Size(87, 20);
            this.lblCodice.TabIndex = 13;
            this.lblCodice.Text = "Codice";
                                                this.ubConferma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubConferma.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubConferma.Location = new System.Drawing.Point(838, 392);
            this.ubConferma.Name = "ubConferma";
            this.ubConferma.Size = new System.Drawing.Size(75, 23);
            this.ubConferma.TabIndex = 4;
            this.ubConferma.Text = "&Conferma";
            this.ubConferma.Click += new System.EventHandler(this.ubConferma_Click);
                                                this.ubAnnulla.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ubAnnulla.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubAnnulla.Location = new System.Drawing.Point(6, 392);
            this.ubAnnulla.Name = "ubAnnulla";
            this.ubAnnulla.Size = new System.Drawing.Size(75, 23);
            this.ubAnnulla.TabIndex = 5;
            this.ubAnnulla.Text = "&Annulla";
            this.ubAnnulla.Click += new System.EventHandler(this.ubAnnulla_Click);
                                                this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.InitialResizeAreaExtent = 8;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 32);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.Name = "_frmPUSchedeCopia_Toolbars_Dock_Area_Left";
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(8, 421);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Left.ToolbarsManager = this.ultraToolbarsManagerForm;
                                                this.ultraToolbarsManagerForm.DesignerFlags = 0;
            this.ultraToolbarsManagerForm.DockWithinContainer = this;
            this.ultraToolbarsManagerForm.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
            this.ultraToolbarsManagerForm.FormDisplayStyle = Infragistics.Win.UltraWinToolbars.FormDisplayStyle.RoundedSizable;
            this.ultraToolbarsManagerForm.RuntimeCustomizationOptions = Infragistics.Win.UltraWinToolbars.RuntimeCustomizationOptions.None;
            this.ultraToolbarsManagerForm.Style = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
                                                this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.InitialResizeAreaExtent = 8;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(927, 32);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.Name = "_frmPUSchedeCopia_Toolbars_Dock_Area_Right";
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(8, 421);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Right.ToolbarsManager = this.ultraToolbarsManagerForm;
                                                this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.Name = "_frmPUSchedeCopia_Toolbars_Dock_Area_Top";
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(935, 32);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Top.ToolbarsManager = this.ultraToolbarsManagerForm;
                                                this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.InitialResizeAreaExtent = 8;
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 453);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.Name = "_frmPUSchedeCopia_Toolbars_Dock_Area_Bottom";
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(935, 8);
            this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.ultraToolbarsManagerForm;
                                                this.chkCopiaSchedeCopia.BackColor = System.Drawing.Color.Transparent;
            this.chkCopiaSchedeCopia.Location = new System.Drawing.Point(261, 33);
            this.chkCopiaSchedeCopia.Name = "chkCopiaSchedeCopia";
            this.chkCopiaSchedeCopia.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.chkCopiaSchedeCopia.Size = new System.Drawing.Size(203, 19);
            this.chkCopiaSchedeCopia.TabIndex = 10;
            this.chkCopiaSchedeCopia.Text = "Copia relazione Schede Copia da";
            this.chkCopiaSchedeCopia.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.chkCopiaSchedeCopia.UseVisualStyleBackColor = false;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(935, 461);
            this.Controls.Add(this.ultraGroupBox);
            this.Controls.Add(this._frmPUSchedeCopia_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmPUSchedeCopia_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmPUSchedeCopia_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmPUSchedeCopia_Toolbars_Dock_Area_Top);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "frmPUSchedeCopia";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmPUSchedeCopia";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmPUSchedeCopia_FormClosing);
            ((System.ComponentModel.ISupportInitialize)(this.ultraGroupBox)).EndInit();
            this.ultraGroupBox.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picView)).EndInit();
            this.pnlCopiaScheda.ResumeLayout(false);
            this.pnlCopiaScheda.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugbCopiaRelazioni)).EndInit();
            this.ugbCopiaRelazioni.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ugVersioni)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodice)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ultraToolbarsManagerForm)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.Misc.UltraGroupBox ultraGroupBox;
        private Infragistics.Win.Misc.UltraButton ubConferma;
        private Infragistics.Win.Misc.UltraButton ubAnnulla;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager ultraToolbarsManagerForm;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeCopia_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeCopia_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeCopia_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUSchedeCopia_Toolbars_Dock_Area_Top;
        internal System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        internal System.Windows.Forms.PictureBox picView;
        private System.Windows.Forms.Panel pnlCopiaScheda;
        private Infragistics.Win.UltraWinGrid.UltraGrid ugVersioni;
        private Infragistics.Win.Misc.UltraGroupBox ugbCopiaRelazioni;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteDescrizione;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteCodice;
        private System.Windows.Forms.Label lblDescrizione;
        private System.Windows.Forms.Label lblCodice;
        private System.Windows.Forms.CheckBox chkCopiaVersione;
        private System.Windows.Forms.CheckBox chkCopiaUA;
        private System.Windows.Forms.CheckBox chkCopiaPadri;
        private System.Windows.Forms.CheckBox chkCopiaFigli;
        private System.Windows.Forms.CheckBox chkCopiaSchedeCopia;
    }
}