namespace UnicodeSrl.ScciManagement
{
    partial class frmPUProtocolliPrescrizioni
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton1 = new Infragistics.Win.UltraWinEditors.EditorButton("puppa");
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinToolbars.UltraToolbar ultraToolbar1 = new Infragistics.Win.UltraWinToolbars.UltraToolbar("utbView");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool1 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Nuovo");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool3 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Elimina");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool5 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Stampa");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool6 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Aggiorna");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool7 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Esporta");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool8 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Nuovo");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool11 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Elimina");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool12 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Aggiorna");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool13 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Stampa");
            Infragistics.Win.UltraWinToolbars.ButtonTool buttonTool14 = new Infragistics.Win.UltraWinToolbars.ButtonTool("Esporta");
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab4 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab2 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab3 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.lblIcona = new System.Windows.Forms.Label();
            this.ucPictureSelectIcona = new UnicodeSrl.ScciCore.ucPictureSelect();
            this.lblColore = new System.Windows.Forms.Label();
            this.ucpColore = new Infragistics.Win.UltraWinEditors.UltraColorPicker();
            this.uteDescrizione = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.uteCodice = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblDescrizione = new System.Windows.Forms.Label();
            this.lblCodice = new System.Windows.Forms.Label();
            this.ultraTabPageControl4 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.PanelPrescrizioni = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGridPrescrizioni = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this._ClientArea_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.UltraToolbarManagerPrescrizioni = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._ClientArea_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._ClientArea_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._ClientArea_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.PicImage = new System.Windows.Forms.PictureBox();
            this.ultraTabPageControl2 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucMultiSelectUA = new UnicodeSrl.ScciCore.ucMultiSelect();
            this.ultraTabPageControl3 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.ucMultiSelectPlusRuoli = new UnicodeSrl.ScciManagement.ucMultiSelectPlus();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTableLayoutPanel1 = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this._frmPUView_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.UltraToolbarManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmPUView_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUView_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmPUView_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.frmPUProtocolliPrescrizioni_Fill_Panel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.UltraTabControl = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ubApplica = new Infragistics.Win.Misc.UltraButton();
            this.ubConferma = new Infragistics.Win.Misc.UltraButton();
            this.ubAnnulla = new Infragistics.Win.Misc.UltraButton();
            this.colorDialog = new System.Windows.Forms.ColorDialog();
            this.UltraGridExcelExporter = new Infragistics.Win.UltraWinGrid.ExcelExport.UltraGridExcelExporter(this.components);
            this.SaveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.ultraTabPageControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucpColore)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodice)).BeginInit();
            this.ultraTabPageControl4.SuspendLayout();
            this.PanelPrescrizioni.ClientArea.SuspendLayout();
            this.PanelPrescrizioni.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridPrescrizioni)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarManagerPrescrizioni)).BeginInit();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).BeginInit();
            this.ultraTabPageControl2.SuspendLayout();
            this.ultraTabPageControl3.SuspendLayout();
            this.ucMultiSelectPlusRuoli.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarManager)).BeginInit();
            this.frmPUProtocolliPrescrizioni_Fill_Panel.ClientArea.SuspendLayout();
            this.frmPUProtocolliPrescrizioni_Fill_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).BeginInit();
            this.UltraTabControl.SuspendLayout();
            this.ultraTabSharedControlsPage1.SuspendLayout();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.lblIcona);
            this.ultraTabPageControl1.Controls.Add(this.ucPictureSelectIcona);
            this.ultraTabPageControl1.Controls.Add(this.lblColore);
            this.ultraTabPageControl1.Controls.Add(this.ucpColore);
            this.ultraTabPageControl1.Controls.Add(this.uteDescrizione);
            this.ultraTabPageControl1.Controls.Add(this.uteCodice);
            this.ultraTabPageControl1.Controls.Add(this.lblDescrizione);
            this.ultraTabPageControl1.Controls.Add(this.lblCodice);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(770, 526);
                                                this.lblIcona.BackColor = System.Drawing.Color.Transparent;
            this.lblIcona.Location = new System.Drawing.Point(140, 90);
            this.lblIcona.Name = "lblIcona";
            this.lblIcona.Size = new System.Drawing.Size(120, 20);
            this.lblIcona.TabIndex = 7;
            this.lblIcona.Text = "Icona";
                                                this.ucPictureSelectIcona.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.ucPictureSelectIcona.BackColor = System.Drawing.Color.Transparent;
            this.ucPictureSelectIcona.Location = new System.Drawing.Point(286, 90);
            this.ucPictureSelectIcona.Name = "ucPictureSelectIcona";
            this.ucPictureSelectIcona.Size = new System.Drawing.Size(474, 433);
            this.ucPictureSelectIcona.TabIndex = 8;
            this.ucPictureSelectIcona.ViewCenterImage = false;
            this.ucPictureSelectIcona.ViewCheckSquareImage = true;
            this.ucPictureSelectIcona.ViewImage = null;
            this.ucPictureSelectIcona.ViewOpenFileDialogFilter = "png files (*.png)|*.png";
            this.ucPictureSelectIcona.ViewSaveFileDialogFilter = "png files (*.png)|*.png|jpg files (*.jpg)|*.jpg|bmp files (*.bmp)|*.bmp";
            this.ucPictureSelectIcona.ViewShowAddImage = true;
            this.ucPictureSelectIcona.ViewShowRemoveImage = true;
            this.ucPictureSelectIcona.ViewShowSaveImage = true;
            this.ucPictureSelectIcona.ViewShowToolbar = true;
            this.ucPictureSelectIcona.ViewToolbarStyle = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
            this.ucPictureSelectIcona.ViewUseLargeImages = false;
            this.ucPictureSelectIcona.ViewZoomFactor = UnicodeSrl.Scci.Enums.enumZoomfactor.zf100;
            this.ucPictureSelectIcona.PictureChange += new UnicodeSrl.ScciCore.ChangeEventHandler(this.ute_ValueChanged);
                                                this.lblColore.BackColor = System.Drawing.Color.Transparent;
            this.lblColore.Location = new System.Drawing.Point(140, 64);
            this.lblColore.Name = "lblColore";
            this.lblColore.Size = new System.Drawing.Size(140, 20);
            this.lblColore.TabIndex = 5;
            this.lblColore.Text = "Colore";
                                                editorButton1.Key = "puppa";
            editorButton1.Text = "...";
            this.ucpColore.ButtonsRight.Add(editorButton1);
            this.ucpColore.DropDownButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Never;
            this.ucpColore.Location = new System.Drawing.Point(286, 63);
            this.ucpColore.Name = "ucpColore";
            this.ucpColore.Size = new System.Drawing.Size(188, 21);
            this.ucpColore.TabIndex = 6;
            this.ucpColore.Text = "Control";
            this.ucpColore.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
            this.ucpColore.EditorButtonClick += new Infragistics.Win.UltraWinEditors.EditorButtonEventHandler(this.ucpColore_EditorButtonClick);
                                                this.uteDescrizione.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.uteDescrizione.Location = new System.Drawing.Point(286, 36);
            this.uteDescrizione.Name = "uteDescrizione";
            this.uteDescrizione.Size = new System.Drawing.Size(474, 21);
            this.uteDescrizione.TabIndex = 4;
            this.uteDescrizione.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.uteCodice.Location = new System.Drawing.Point(286, 8);
            this.uteCodice.Name = "uteCodice";
            this.uteCodice.Size = new System.Drawing.Size(101, 21);
            this.uteCodice.TabIndex = 2;
            this.uteCodice.ValueChanged += new System.EventHandler(this.ute_ValueChanged);
                                                this.lblDescrizione.BackColor = System.Drawing.Color.Transparent;
            this.lblDescrizione.Location = new System.Drawing.Point(140, 40);
            this.lblDescrizione.Name = "lblDescrizione";
            this.lblDescrizione.Size = new System.Drawing.Size(140, 20);
            this.lblDescrizione.TabIndex = 3;
            this.lblDescrizione.Text = "Descrizione";
                                                this.lblCodice.BackColor = System.Drawing.Color.Transparent;
            this.lblCodice.Location = new System.Drawing.Point(140, 12);
            this.lblCodice.Name = "lblCodice";
            this.lblCodice.Size = new System.Drawing.Size(140, 20);
            this.lblCodice.TabIndex = 1;
            this.lblCodice.Text = "Codice";
                                                this.ultraTabPageControl4.Controls.Add(this.PanelPrescrizioni);
            this.ultraTabPageControl4.Controls.Add(this.TableLayoutPanel);
            this.ultraTabPageControl4.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl4.Name = "ultraTabPageControl4";
            this.ultraTabPageControl4.Size = new System.Drawing.Size(770, 526);
                                                                                    this.PanelPrescrizioni.ClientArea.Controls.Add(this.UltraGridPrescrizioni);
            this.PanelPrescrizioni.ClientArea.Controls.Add(this._ClientArea_Toolbars_Dock_Area_Left);
            this.PanelPrescrizioni.ClientArea.Controls.Add(this._ClientArea_Toolbars_Dock_Area_Right);
            this.PanelPrescrizioni.ClientArea.Controls.Add(this._ClientArea_Toolbars_Dock_Area_Bottom);
            this.PanelPrescrizioni.ClientArea.Controls.Add(this._ClientArea_Toolbars_Dock_Area_Top);
            this.PanelPrescrizioni.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PanelPrescrizioni.Location = new System.Drawing.Point(134, 0);
            this.PanelPrescrizioni.Name = "PanelPrescrizioni";
            this.PanelPrescrizioni.Size = new System.Drawing.Size(636, 526);
            this.PanelPrescrizioni.TabIndex = 7;
                                                appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridPrescrizioni.DisplayLayout.Appearance = appearance1;
            this.UltraGridPrescrizioni.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridPrescrizioni.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance2.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridPrescrizioni.DisplayLayout.GroupByBox.Appearance = appearance2;
            appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridPrescrizioni.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
            this.UltraGridPrescrizioni.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance4.BackColor2 = System.Drawing.SystemColors.Control;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridPrescrizioni.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
            this.UltraGridPrescrizioni.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridPrescrizioni.DisplayLayout.MaxRowScrollRegions = 1;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridPrescrizioni.DisplayLayout.Override.ActiveCellAppearance = appearance5;
            appearance6.BackColor = System.Drawing.SystemColors.Highlight;
            appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridPrescrizioni.DisplayLayout.Override.ActiveRowAppearance = appearance6;
            this.UltraGridPrescrizioni.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridPrescrizioni.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridPrescrizioni.DisplayLayout.Override.CardAreaAppearance = appearance7;
            appearance8.BorderColor = System.Drawing.Color.Silver;
            appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridPrescrizioni.DisplayLayout.Override.CellAppearance = appearance8;
            this.UltraGridPrescrizioni.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.UltraGridPrescrizioni.DisplayLayout.Override.CellPadding = 0;
            appearance9.BackColor = System.Drawing.SystemColors.Control;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridPrescrizioni.DisplayLayout.Override.GroupByRowAppearance = appearance9;
            appearance10.TextHAlignAsString = "Left";
            this.UltraGridPrescrizioni.DisplayLayout.Override.HeaderAppearance = appearance10;
            this.UltraGridPrescrizioni.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.UltraGridPrescrizioni.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridPrescrizioni.DisplayLayout.Override.RowAppearance = appearance11;
            this.UltraGridPrescrizioni.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance12.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridPrescrizioni.DisplayLayout.Override.TemplateAddRowAppearance = appearance12;
            this.UltraGridPrescrizioni.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridPrescrizioni.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridPrescrizioni.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridPrescrizioni.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridPrescrizioni.Location = new System.Drawing.Point(0, 63);
            this.UltraGridPrescrizioni.Name = "UltraGridPrescrizioni";
            this.UltraGridPrescrizioni.Size = new System.Drawing.Size(636, 463);
            this.UltraGridPrescrizioni.TabIndex = 7;
            this.UltraGridPrescrizioni.Text = "Modelli Terapie Farmacologiche";
            this.UltraGridPrescrizioni.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGridPrescrizioni_InitializeLayout);
                                                this._ClientArea_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ClientArea_Toolbars_Dock_Area_Left.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._ClientArea_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._ClientArea_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ClientArea_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 63);
            this._ClientArea_Toolbars_Dock_Area_Left.Name = "_ClientArea_Toolbars_Dock_Area_Left";
            this._ClientArea_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 463);
            this._ClientArea_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarManagerPrescrizioni;
                                                this.UltraToolbarManagerPrescrizioni.DesignerFlags = 1;
            this.UltraToolbarManagerPrescrizioni.DockWithinContainer = this.PanelPrescrizioni.ClientArea;
            this.UltraToolbarManagerPrescrizioni.FormDisplayStyle = Infragistics.Win.UltraWinToolbars.FormDisplayStyle.RoundedSizable;
            this.UltraToolbarManagerPrescrizioni.MdiMergeable = false;
            this.UltraToolbarManagerPrescrizioni.RuntimeCustomizationOptions = Infragistics.Win.UltraWinToolbars.RuntimeCustomizationOptions.None;
            this.UltraToolbarManagerPrescrizioni.ShowFullMenusDelay = 500;
            this.UltraToolbarManagerPrescrizioni.Style = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
            ultraToolbar1.DockedColumn = 0;
            ultraToolbar1.DockedRow = 0;
            buttonTool6.InstanceProps.IsFirstInGroup = true;
            ultraToolbar1.NonInheritedTools.AddRange(new Infragistics.Win.UltraWinToolbars.ToolBase[] {
            buttonTool1,
            buttonTool3,
            buttonTool5,
            buttonTool6,
            buttonTool7});
            ultraToolbar1.Settings.AllowCustomize = Infragistics.Win.DefaultableBoolean.False;
            ultraToolbar1.Settings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            ultraToolbar1.Settings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            ultraToolbar1.Settings.AllowDockRight = Infragistics.Win.DefaultableBoolean.False;
            ultraToolbar1.Settings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            ultraToolbar1.Settings.AllowHiding = Infragistics.Win.DefaultableBoolean.False;
            ultraToolbar1.Settings.CaptionPlacement = Infragistics.Win.TextPlacement.BelowImage;
            ultraToolbar1.Settings.FillEntireRow = Infragistics.Win.DefaultableBoolean.True;
            ultraToolbar1.Settings.ToolDisplayStyle = Infragistics.Win.UltraWinToolbars.ToolDisplayStyle.ImageAndText;
            ultraToolbar1.Settings.UseLargeImages = Infragistics.Win.DefaultableBoolean.True;
            ultraToolbar1.ShowInToolbarList = false;
            ultraToolbar1.Text = "utbView";
            this.UltraToolbarManagerPrescrizioni.Toolbars.AddRange(new Infragistics.Win.UltraWinToolbars.UltraToolbar[] {
            ultraToolbar1});
            buttonTool8.SharedPropsInternal.Caption = "Nuovo";
            buttonTool11.SharedPropsInternal.Caption = "Elimina";
            buttonTool12.SharedPropsInternal.Caption = "Aggiorna";
            buttonTool13.SharedPropsInternal.Caption = "Stampa";
            buttonTool14.SharedPropsInternal.Caption = "Esporta";
            this.UltraToolbarManagerPrescrizioni.Tools.AddRange(new Infragistics.Win.UltraWinToolbars.ToolBase[] {
            buttonTool8,
            buttonTool11,
            buttonTool12,
            buttonTool13,
            buttonTool14});
            this.UltraToolbarManagerPrescrizioni.ToolClick += new Infragistics.Win.UltraWinToolbars.ToolClickEventHandler(this.UltraToolbarManagerPrescrizioni_ToolClick);
                                                this._ClientArea_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ClientArea_Toolbars_Dock_Area_Right.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._ClientArea_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._ClientArea_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ClientArea_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(636, 63);
            this._ClientArea_Toolbars_Dock_Area_Right.Name = "_ClientArea_Toolbars_Dock_Area_Right";
            this._ClientArea_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 463);
            this._ClientArea_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarManagerPrescrizioni;
                                                this._ClientArea_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ClientArea_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._ClientArea_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._ClientArea_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ClientArea_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 526);
            this._ClientArea_Toolbars_Dock_Area_Bottom.Name = "_ClientArea_Toolbars_Dock_Area_Bottom";
            this._ClientArea_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(636, 0);
            this._ClientArea_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarManagerPrescrizioni;
                                                this._ClientArea_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ClientArea_Toolbars_Dock_Area_Top.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._ClientArea_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._ClientArea_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ClientArea_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._ClientArea_Toolbars_Dock_Area_Top.Name = "_ClientArea_Toolbars_Dock_Area_Top";
            this._ClientArea_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(636, 63);
            this._ClientArea_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarManagerPrescrizioni;
                                                this.TableLayoutPanel.ColumnCount = 1;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TableLayoutPanel.Controls.Add(this.PicImage, 0, 1);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.TableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(134, 526);
            this.TableLayoutPanel.TabIndex = 1;
                                                this.PicImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PicImage.Location = new System.Drawing.Point(3, 202);
            this.PicImage.Name = "PicImage";
            this.PicImage.Size = new System.Drawing.Size(128, 122);
            this.PicImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PicImage.TabIndex = 0;
            this.PicImage.TabStop = false;
                                                this.ultraTabPageControl2.Controls.Add(this.ucMultiSelectUA);
            this.ultraTabPageControl2.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl2.Name = "ultraTabPageControl2";
            this.ultraTabPageControl2.Size = new System.Drawing.Size(770, 526);
                                                this.ucMultiSelectUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucMultiSelectUA.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ucMultiSelectUA.GridDXCaption = "";
            this.ucMultiSelectUA.GridDXCaptionColumnKey = "";
            this.ucMultiSelectUA.GridDXFilterColumnIndex = 1;
            this.ucMultiSelectUA.GridSXCaption = "";
            this.ucMultiSelectUA.GridSXCaptionColumnKey = "";
            this.ucMultiSelectUA.GridSXFilterColumnIndex = 1;
            this.ucMultiSelectUA.Location = new System.Drawing.Point(0, 0);
            this.ucMultiSelectUA.Name = "ucMultiSelectUA";
            this.ucMultiSelectUA.Size = new System.Drawing.Size(770, 526);
            this.ucMultiSelectUA.TabIndex = 1;
            this.ucMultiSelectUA.Tag = "DCL";
            this.ucMultiSelectUA.ViewDataSetDX = null;
            this.ucMultiSelectUA.ViewDataSetSX = null;
            this.ucMultiSelectUA.ViewDataViewDX = null;
            this.ucMultiSelectUA.ViewDataViewSX = null;
            this.ucMultiSelectUA.ViewShowAll = true;
            this.ucMultiSelectUA.ViewShowFind = true;
            this.ucMultiSelectUA.GridSXInitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucMultiSelect_GridSXInitializeLayout);
            this.ucMultiSelectUA.GridSXInitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucMultiSelect_GridDXInitializeRow);
            this.ucMultiSelectUA.GridDXInitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucMultiSelect_GridDXInitializeLayout);
            this.ucMultiSelectUA.GridDXInitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucMultiSelect_GridDXInitializeRow);
            this.ucMultiSelectUA.GridChange += new UnicodeSrl.ScciCore.ChangeEventHandler(this.ucMultiSelect_Change);
                                                this.ultraTabPageControl3.Controls.Add(this.ucMultiSelectPlusRuoli);
            this.ultraTabPageControl3.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl3.Name = "ultraTabPageControl3";
            this.ultraTabPageControl3.Size = new System.Drawing.Size(770, 526);
                                                this.ucMultiSelectPlusRuoli.Controls.Add(this.ucEasyTableLayoutPanel);
            this.ucMultiSelectPlusRuoli.Controls.Add(this.ucEasyTableLayoutPanel1);
            this.ucMultiSelectPlusRuoli.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucMultiSelectPlusRuoli.GridDXCaption = "";
            this.ucMultiSelectPlusRuoli.GridDXCaptionColumnKey = "";
            this.ucMultiSelectPlusRuoli.GridDXFilterColumnIndex = 1;
            this.ucMultiSelectPlusRuoli.GridSXCaption = "";
            this.ucMultiSelectPlusRuoli.GridSXCaptionColumnKey = "";
            this.ucMultiSelectPlusRuoli.GridSXFilterColumnIndex = 1;
            this.ucMultiSelectPlusRuoli.Location = new System.Drawing.Point(0, 0);
            this.ucMultiSelectPlusRuoli.Name = "ucMultiSelectPlusRuoli";
            this.ucMultiSelectPlusRuoli.Size = new System.Drawing.Size(770, 526);
            this.ucMultiSelectPlusRuoli.TabIndex = 1;
            this.ucMultiSelectPlusRuoli.ViewDataSetDX = null;
            this.ucMultiSelectPlusRuoli.ViewDataSetMaster = null;
            this.ucMultiSelectPlusRuoli.ViewDataSetSX = null;
            this.ucMultiSelectPlusRuoli.ViewShowAll = true;
            this.ucMultiSelectPlusRuoli.ViewShowFind = true;
            this.ucMultiSelectPlusRuoli.GridMasterInitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucMultiSelect_GridMasterInitializeLayout);
            this.ucMultiSelectPlusRuoli.GridMasterInitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucMultiSelect_GridMasterInitializeRow);
            this.ucMultiSelectPlusRuoli.GridSXInitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucMultiSelect_GridSXInitializeLayout);
            this.ucMultiSelectPlusRuoli.GridSXInitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucMultiSelect_GridSXInitializeRow);
            this.ucMultiSelectPlusRuoli.GridDXInitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ucMultiSelect_GridDXInitializeLayout);
            this.ucMultiSelectPlusRuoli.GridDXInitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ucMultiSelect_GridDXInitializeRow);
            this.ucMultiSelectPlusRuoli.GridChange += new UnicodeSrl.ScciCore.ChangeEventHandler(this.ucMultiSelect_Change);
                                                this.ucEasyTableLayoutPanel.ColumnCount = 2;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 1;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(770, 526);
            this.ucEasyTableLayoutPanel.TabIndex = 0;
                                                this.ucEasyTableLayoutPanel1.ColumnCount = 2;
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.ucEasyTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ucEasyTableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanel1.Name = "ucEasyTableLayoutPanel1";
            this.ucEasyTableLayoutPanel1.RowCount = 1;
            this.ucEasyTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanel1.Size = new System.Drawing.Size(770, 526);
            this.ucEasyTableLayoutPanel1.TabIndex = 0;
                                                this._frmPUView_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUView_Toolbars_Dock_Area_Top.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUView_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmPUView_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUView_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmPUView_Toolbars_Dock_Area_Top.Name = "_frmPUView_Toolbars_Dock_Area_Top";
            this._frmPUView_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(796, 0);
            this._frmPUView_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarManager;
                                                this.UltraToolbarManager.DesignerFlags = 1;
            this.UltraToolbarManager.DockWithinContainer = this;
            this.UltraToolbarManager.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
                                                this._frmPUView_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUView_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUView_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmPUView_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUView_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 602);
            this._frmPUView_Toolbars_Dock_Area_Bottom.Name = "_frmPUView_Toolbars_Dock_Area_Bottom";
            this._frmPUView_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(796, 0);
            this._frmPUView_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarManager;
                                                this._frmPUView_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUView_Toolbars_Dock_Area_Left.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUView_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmPUView_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUView_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._frmPUView_Toolbars_Dock_Area_Left.Name = "_frmPUView_Toolbars_Dock_Area_Left";
            this._frmPUView_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 602);
            this._frmPUView_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarManager;
                                                this._frmPUView_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmPUView_Toolbars_Dock_Area_Right.BackColor = System.Drawing.SystemColors.Control;
            this._frmPUView_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmPUView_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmPUView_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(796, 0);
            this._frmPUView_Toolbars_Dock_Area_Right.Name = "_frmPUView_Toolbars_Dock_Area_Right";
            this._frmPUView_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 602);
            this._frmPUView_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarManager;
                                                                                    this.frmPUProtocolliPrescrizioni_Fill_Panel.ClientArea.Controls.Add(this.UltraGroupBox);
            this.frmPUProtocolliPrescrizioni_Fill_Panel.Cursor = System.Windows.Forms.Cursors.Default;
            this.frmPUProtocolliPrescrizioni_Fill_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.frmPUProtocolliPrescrizioni_Fill_Panel.Location = new System.Drawing.Point(0, 0);
            this.frmPUProtocolliPrescrizioni_Fill_Panel.Name = "frmPUProtocolliPrescrizioni_Fill_Panel";
            this.frmPUProtocolliPrescrizioni_Fill_Panel.Size = new System.Drawing.Size(796, 602);
            this.frmPUProtocolliPrescrizioni_Fill_Panel.TabIndex = 8;
                                                this.UltraGroupBox.Controls.Add(this.UltraTabControl);
            this.UltraGroupBox.Controls.Add(this.ubApplica);
            this.UltraGroupBox.Controls.Add(this.ubConferma);
            this.UltraGroupBox.Controls.Add(this.ubAnnulla);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(796, 602);
            this.UltraGroupBox.TabIndex = 1;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.UltraTabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.UltraTabControl.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl4);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl2);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl3);
            this.UltraTabControl.Location = new System.Drawing.Point(12, 12);
            this.UltraTabControl.Name = "UltraTabControl";
            this.UltraTabControl.SharedControls.AddRange(new System.Windows.Forms.Control[] {
            this.TableLayoutPanel});
            this.UltraTabControl.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControl.Size = new System.Drawing.Size(772, 549);
            this.UltraTabControl.TabIndex = 0;
            ultraTab1.Key = "tab1";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Protocolli Prescrizioni";
            ultraTab4.Key = "tab2";
            ultraTab4.TabPage = this.ultraTabPageControl4;
            ultraTab4.Text = "Prescrizioni";
            ultraTab2.Key = "UA";
            ultraTab2.TabPage = this.ultraTabPageControl2;
            ultraTab2.Text = "Unità Atomiche";
            ultraTab3.Key = "Ruoli";
            ultraTab3.TabPage = this.ultraTabPageControl3;
            ultraTab3.Text = "Ruoli";
            this.UltraTabControl.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1,
            ultraTab4,
            ultraTab2,
            ultraTab3});
            this.UltraTabControl.TabStop = false;
            this.UltraTabControl.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.ultraTabSharedControlsPage1.Controls.Add(this.TableLayoutPanel);
            this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(770, 526);
                                                this.ubApplica.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.ubApplica.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubApplica.Location = new System.Drawing.Point(350, 567);
            this.ubApplica.Name = "ubApplica";
            this.ubApplica.Size = new System.Drawing.Size(75, 23);
            this.ubApplica.TabIndex = 2;
            this.ubApplica.Text = "Applica";
            this.ubApplica.Click += new System.EventHandler(this.ubApplica_Click);
                                                this.ubConferma.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubConferma.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubConferma.Location = new System.Drawing.Point(709, 567);
            this.ubConferma.Name = "ubConferma";
            this.ubConferma.Size = new System.Drawing.Size(75, 23);
            this.ubConferma.TabIndex = 3;
            this.ubConferma.Text = "&Conferma";
            this.ubConferma.Click += new System.EventHandler(this.ubConferma_Click);
                                                this.ubAnnulla.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.ubAnnulla.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubAnnulla.Location = new System.Drawing.Point(12, 567);
            this.ubAnnulla.Name = "ubAnnulla";
            this.ubAnnulla.Size = new System.Drawing.Size(75, 23);
            this.ubAnnulla.TabIndex = 1;
            this.ubAnnulla.Text = "&Annulla";
            this.ubAnnulla.Click += new System.EventHandler(this.ubAnnulla_Click);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(796, 602);
            this.Controls.Add(this.frmPUProtocolliPrescrizioni_Fill_Panel);
            this.Controls.Add(this._frmPUView_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmPUView_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmPUView_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmPUView_Toolbars_Dock_Area_Top);
            this.Name = "frmPUProtocolliPrescrizioni";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmPUProtocolliPrescrizioni";
            this.ultraTabPageControl1.ResumeLayout(false);
            this.ultraTabPageControl1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucpColore)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteDescrizione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodice)).EndInit();
            this.ultraTabPageControl4.ResumeLayout(false);
            this.PanelPrescrizioni.ClientArea.ResumeLayout(false);
            this.PanelPrescrizioni.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridPrescrizioni)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarManagerPrescrizioni)).EndInit();
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).EndInit();
            this.ultraTabPageControl2.ResumeLayout(false);
            this.ultraTabPageControl3.ResumeLayout(false);
            this.ucMultiSelectPlusRuoli.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarManager)).EndInit();
            this.frmPUProtocolliPrescrizioni_Fill_Panel.ClientArea.ResumeLayout(false);
            this.frmPUProtocolliPrescrizioni_Fill_Panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).EndInit();
            this.UltraTabControl.ResumeLayout(false);
            this.ultraTabSharedControlsPage1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarManager;
        private Infragistics.Win.Misc.UltraPanel frmPUProtocolliPrescrizioni_Fill_Panel;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUView_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUView_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUView_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmPUView_Toolbars_Dock_Area_Top;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControl;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private System.Windows.Forms.Label lblIcona;
        private ScciCore.ucPictureSelect ucPictureSelectIcona;
        private System.Windows.Forms.Label lblColore;
        private Infragistics.Win.UltraWinEditors.UltraColorPicker ucpColore;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteDescrizione;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteCodice;
        private System.Windows.Forms.Label lblDescrizione;
        private System.Windows.Forms.Label lblCodice;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl4;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl2;
        private ScciCore.ucMultiSelect ucMultiSelectUA;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl3;
        private ucMultiSelectPlus ucMultiSelectPlusRuoli;
        private ScciCore.ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ScciCore.ucEasyTableLayoutPanel ucEasyTableLayoutPanel1;
        private Infragistics.Win.Misc.UltraButton ubApplica;
        private Infragistics.Win.Misc.UltraButton ubConferma;
        private Infragistics.Win.Misc.UltraButton ubAnnulla;
        private System.Windows.Forms.ColorDialog colorDialog;
        private Infragistics.Win.UltraWinGrid.ExcelExport.UltraGridExcelExporter UltraGridExcelExporter;
        private System.Windows.Forms.SaveFileDialog SaveFileDialog;
        private Infragistics.Win.Misc.UltraPanel PanelPrescrizioni;
        private Infragistics.Win.UltraWinGrid.UltraGrid UltraGridPrescrizioni;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ClientArea_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarManagerPrescrizioni;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ClientArea_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ClientArea_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ClientArea_Toolbars_Dock_Area_Top;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        private System.Windows.Forms.PictureBox PicImage;
    }
}