namespace UnicodeSrl.ScciManagement
{
    partial class frmPUCDSSStrutturaCopia
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.UltraWinEditors.EditorButton editorButton1 = new Infragistics.Win.UltraWinEditors.EditorButton("Zoom");
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab2 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.tlpDestinazione = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.UltraGridOrigine = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.lblCodUADes = new System.Windows.Forms.Label();
            this.uteCodUA = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblCodUA = new System.Windows.Forms.Label();
            this.UltraSplitter = new Infragistics.Win.Misc.UltraSplitter();
            this.UltraTreeOrigine = new Infragistics.Win.UltraWinTree.UltraTree();
            this.ultraTabPageControl2 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.TableLayoutPanelDestinazione = new System.Windows.Forms.TableLayoutPanel();
            this.xmlParametri = new XmlEditor();
            this.UltraGridDestinazione = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.ubSalva = new Infragistics.Win.Misc.UltraButton();
            this._frmSchedeTreeView_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmSchedeTreeView_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmSchedeTreeView_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.frmSchedeTreeView_Fill_Panel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.picView = new System.Windows.Forms.PictureBox();
            this.UltraTabControl = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.ubChiudi = new Infragistics.Win.Misc.UltraButton();
            this.ubConferma = new Infragistics.Win.Misc.UltraButton();
            this.ultraTabPageControl1.SuspendLayout();
            this.tlpDestinazione.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridOrigine)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodUA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTreeOrigine)).BeginInit();
            this.ultraTabPageControl2.SuspendLayout();
            this.TableLayoutPanelDestinazione.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridDestinazione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.frmSchedeTreeView_Fill_Panel.ClientArea.SuspendLayout();
            this.frmSchedeTreeView_Fill_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            this.TableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picView)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).BeginInit();
            this.UltraTabControl.SuspendLayout();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.tlpDestinazione);
            this.ultraTabPageControl1.Controls.Add(this.UltraSplitter);
            this.ultraTabPageControl1.Controls.Add(this.UltraTreeOrigine);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(624, 485);
                                                this.tlpDestinazione.ColumnCount = 2;
            this.tlpDestinazione.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tlpDestinazione.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.tlpDestinazione.Controls.Add(this.UltraGridOrigine, 0, 2);
            this.tlpDestinazione.Controls.Add(this.lblCodUADes, 1, 1);
            this.tlpDestinazione.Controls.Add(this.uteCodUA, 0, 1);
            this.tlpDestinazione.Controls.Add(this.lblCodUA, 0, 0);
            this.tlpDestinazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpDestinazione.Location = new System.Drawing.Point(320, 0);
            this.tlpDestinazione.Name = "tlpDestinazione";
            this.tlpDestinazione.RowCount = 3;
            this.tlpDestinazione.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tlpDestinazione.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 28F));
            this.tlpDestinazione.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpDestinazione.Size = new System.Drawing.Size(304, 485);
            this.tlpDestinazione.TabIndex = 6;
                                                this.tlpDestinazione.SetColumnSpan(this.UltraGridOrigine, 2);
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridOrigine.DisplayLayout.Appearance = appearance1;
            this.UltraGridOrigine.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridOrigine.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridOrigine.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance2.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridOrigine.DisplayLayout.GroupByBox.Appearance = appearance2;
            appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridOrigine.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
            this.UltraGridOrigine.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridOrigine.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridOrigine.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance4.BackColor2 = System.Drawing.SystemColors.Control;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridOrigine.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
            this.UltraGridOrigine.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridOrigine.DisplayLayout.MaxRowScrollRegions = 1;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridOrigine.DisplayLayout.Override.ActiveCellAppearance = appearance5;
            appearance6.BackColor = System.Drawing.SystemColors.Highlight;
            appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridOrigine.DisplayLayout.Override.ActiveRowAppearance = appearance6;
            this.UltraGridOrigine.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridOrigine.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridOrigine.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridOrigine.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridOrigine.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridOrigine.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridOrigine.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridOrigine.DisplayLayout.Override.CardAreaAppearance = appearance7;
            appearance8.BorderColor = System.Drawing.Color.Silver;
            appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridOrigine.DisplayLayout.Override.CellAppearance = appearance8;
            this.UltraGridOrigine.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridOrigine.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridOrigine.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance9.BackColor = System.Drawing.SystemColors.Control;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridOrigine.DisplayLayout.Override.GroupByRowAppearance = appearance9;
            appearance10.FontData.BoldAsString = "True";
            appearance10.TextHAlignAsString = "Center";
            this.UltraGridOrigine.DisplayLayout.Override.HeaderAppearance = appearance10;
            this.UltraGridOrigine.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridOrigine.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance11.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance11.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridOrigine.DisplayLayout.Override.RowAlternateAppearance = appearance11;
            appearance12.BackColor = System.Drawing.SystemColors.Window;
            appearance12.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridOrigine.DisplayLayout.Override.RowAppearance = appearance12;
            this.UltraGridOrigine.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridOrigine.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridOrigine.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridOrigine.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance13.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridOrigine.DisplayLayout.Override.TemplateAddRowAppearance = appearance13;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridOrigine.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.UltraGridOrigine.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridOrigine.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridOrigine.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridOrigine.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridOrigine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridOrigine.Location = new System.Drawing.Point(3, 59);
            this.UltraGridOrigine.Name = "UltraGridOrigine";
            this.UltraGridOrigine.Size = new System.Drawing.Size(298, 423);
            this.UltraGridOrigine.TabIndex = 15;
            this.UltraGridOrigine.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridOrigine.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridOrigine.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGrid_InitializeLayout);
            this.UltraGridOrigine.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.UltraGridOrigine_InitializeRow);
                                                this.lblCodUADes.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.lblCodUADes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCodUADes.Location = new System.Drawing.Point(124, 28);
            this.lblCodUADes.Name = "lblCodUADes";
            this.lblCodUADes.Size = new System.Drawing.Size(177, 28);
            this.lblCodUADes.TabIndex = 14;
            this.lblCodUADes.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                editorButton1.Key = "Zoom";
            editorButton1.Text = "...";
            this.uteCodUA.ButtonsRight.Add(editorButton1);
            this.uteCodUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteCodUA.Location = new System.Drawing.Point(3, 31);
            this.uteCodUA.Name = "uteCodUA";
            this.uteCodUA.Size = new System.Drawing.Size(115, 22);
            this.uteCodUA.TabIndex = 13;
            this.uteCodUA.ValueChanged += new System.EventHandler(this.uteCodUA_ValueChanged);
            this.uteCodUA.EditorButtonClick += new Infragistics.Win.UltraWinEditors.EditorButtonEventHandler(this.uteCodUA_EditorButtonClick);
                                                this.lblCodUA.BackColor = System.Drawing.Color.Transparent;
            this.tlpDestinazione.SetColumnSpan(this.lblCodUA, 2);
            this.lblCodUA.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCodUA.Location = new System.Drawing.Point(3, 0);
            this.lblCodUA.Name = "lblCodUA";
            this.lblCodUA.Size = new System.Drawing.Size(298, 28);
            this.lblCodUA.TabIndex = 12;
            this.lblCodUA.Text = "UA Destinazione";
            this.lblCodUA.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
                                                this.UltraSplitter.BorderStyle = Infragistics.Win.UIElementBorderStyle.Default;
            this.UltraSplitter.CollapseUIType = Infragistics.Win.Misc.CollapseUIType.None;
            this.UltraSplitter.Location = new System.Drawing.Point(312, 0);
            this.UltraSplitter.Name = "UltraSplitter";
            this.UltraSplitter.RestoreExtent = 0;
            this.UltraSplitter.Size = new System.Drawing.Size(8, 485);
            this.UltraSplitter.TabIndex = 5;
                                                this.UltraTreeOrigine.Dock = System.Windows.Forms.DockStyle.Left;
            this.UltraTreeOrigine.Location = new System.Drawing.Point(0, 0);
            this.UltraTreeOrigine.Name = "UltraTreeOrigine";
            this.UltraTreeOrigine.NodeConnectorColor = System.Drawing.SystemColors.ControlDark;
            this.UltraTreeOrigine.Size = new System.Drawing.Size(312, 485);
            this.UltraTreeOrigine.TabIndex = 4;
            this.UltraTreeOrigine.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.UltraTreeOrigine_AfterCheck);
                                                this.ultraTabPageControl2.Controls.Add(this.TableLayoutPanelDestinazione);
            this.ultraTabPageControl2.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl2.Name = "ultraTabPageControl2";
            this.ultraTabPageControl2.Size = new System.Drawing.Size(848, 653);
                                                this.TableLayoutPanelDestinazione.ColumnCount = 2;
            this.TableLayoutPanelDestinazione.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelDestinazione.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 81F));
            this.TableLayoutPanelDestinazione.Controls.Add(this.ubConferma, 1, 0);
            this.TableLayoutPanelDestinazione.Controls.Add(this.xmlParametri, 0, 1);
            this.TableLayoutPanelDestinazione.Controls.Add(this.UltraGridDestinazione, 0, 0);
            this.TableLayoutPanelDestinazione.Controls.Add(this.ubSalva, 1, 1);
            this.TableLayoutPanelDestinazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelDestinazione.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanelDestinazione.Name = "TableLayoutPanelDestinazione";
            this.TableLayoutPanelDestinazione.RowCount = 2;
            this.TableLayoutPanelDestinazione.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 75F));
            this.TableLayoutPanelDestinazione.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.TableLayoutPanelDestinazione.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.TableLayoutPanelDestinazione.Size = new System.Drawing.Size(848, 653);
            this.TableLayoutPanelDestinazione.TabIndex = 1;
                                                this.xmlParametri.AllowAutoXmlValidate = true;
            this.xmlParametri.AllowUndo = true;
            this.xmlParametri.AllowXmlFormatting = true;
            this.xmlParametri.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.xmlParametri.AttributeColor = System.Drawing.Color.Red;
            this.xmlParametri.BackColor = System.Drawing.Color.Transparent;
            this.xmlParametri.CommentColor = System.Drawing.Color.DarkGreen;
            this.xmlParametri.EditorFont = new System.Drawing.Font("Courier New", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.xmlParametri.ElementColor = System.Drawing.Color.DarkRed;
            this.xmlParametri.EscapeColor = System.Drawing.Color.Orchid;
            this.xmlParametri.Location = new System.Drawing.Point(3, 492);
            this.xmlParametri.Name = "xmlParametri";
            this.xmlParametri.ReadOnly = false;
            this.xmlParametri.ScrollBars = System.Windows.Forms.RichTextBoxScrollBars.Both;
            this.xmlParametri.Size = new System.Drawing.Size(761, 158);
            this.xmlParametri.SpercialCharColor = System.Drawing.Color.Blue;
            this.xmlParametri.TabIndex = 10;
            this.xmlParametri.ValueColor = System.Drawing.Color.DarkBlue;
            this.xmlParametri.WordWrap = false;
            this.xmlParametri.XMLTextChanged += new System.EventHandler(this.xmlParametri_XMLTextChanged);
                                                appearance14.BackColor = System.Drawing.SystemColors.Window;
            appearance14.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGridDestinazione.DisplayLayout.Appearance = appearance14;
            this.UltraGridDestinazione.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.UltraGridDestinazione.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridDestinazione.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance15.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance15.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance15.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance15.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridDestinazione.DisplayLayout.GroupByBox.Appearance = appearance15;
            appearance16.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridDestinazione.DisplayLayout.GroupByBox.BandLabelAppearance = appearance16;
            this.UltraGridDestinazione.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGridDestinazione.DisplayLayout.GroupByBox.Hidden = true;
            this.UltraGridDestinazione.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance17.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance17.BackColor2 = System.Drawing.SystemColors.Control;
            appearance17.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance17.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGridDestinazione.DisplayLayout.GroupByBox.PromptAppearance = appearance17;
            this.UltraGridDestinazione.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGridDestinazione.DisplayLayout.MaxRowScrollRegions = 1;
            appearance18.BackColor = System.Drawing.SystemColors.Window;
            appearance18.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGridDestinazione.DisplayLayout.Override.ActiveCellAppearance = appearance18;
            appearance19.BackColor = System.Drawing.SystemColors.Highlight;
            appearance19.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGridDestinazione.DisplayLayout.Override.ActiveRowAppearance = appearance19;
            this.UltraGridDestinazione.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.UltraGridDestinazione.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.UltraGridDestinazione.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDestinazione.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDestinazione.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDestinazione.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGridDestinazione.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance20.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGridDestinazione.DisplayLayout.Override.CardAreaAppearance = appearance20;
            appearance21.BorderColor = System.Drawing.Color.Silver;
            appearance21.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGridDestinazione.DisplayLayout.Override.CellAppearance = appearance21;
            this.UltraGridDestinazione.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.UltraGridDestinazione.DisplayLayout.Override.CellPadding = 0;
            this.UltraGridDestinazione.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance22.BackColor = System.Drawing.SystemColors.Control;
            appearance22.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance22.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance22.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance22.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGridDestinazione.DisplayLayout.Override.GroupByRowAppearance = appearance22;
            appearance23.FontData.BoldAsString = "True";
            appearance23.TextHAlignAsString = "Center";
            this.UltraGridDestinazione.DisplayLayout.Override.HeaderAppearance = appearance23;
            this.UltraGridDestinazione.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.UltraGridDestinazione.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance24.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance24.ForeColor = System.Drawing.Color.DarkBlue;
            this.UltraGridDestinazione.DisplayLayout.Override.RowAlternateAppearance = appearance24;
            appearance25.BackColor = System.Drawing.SystemColors.Window;
            appearance25.BorderColor = System.Drawing.Color.Silver;
            this.UltraGridDestinazione.DisplayLayout.Override.RowAppearance = appearance25;
            this.UltraGridDestinazione.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDestinazione.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.UltraGridDestinazione.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.UltraGridDestinazione.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance26.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGridDestinazione.DisplayLayout.Override.TemplateAddRowAppearance = appearance26;
            scrollBarLook2.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.UltraGridDestinazione.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.UltraGridDestinazione.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGridDestinazione.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGridDestinazione.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.UltraGridDestinazione.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGridDestinazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGridDestinazione.Location = new System.Drawing.Point(3, 3);
            this.UltraGridDestinazione.Name = "UltraGridDestinazione";
            this.UltraGridDestinazione.Size = new System.Drawing.Size(761, 483);
            this.UltraGridDestinazione.TabIndex = 0;
            this.UltraGridDestinazione.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.UltraGridDestinazione.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraGridDestinazione.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGrid_InitializeLayout);
            this.UltraGridDestinazione.AfterRowActivate += new System.EventHandler(this.UltraGridDestinazione_AfterRowActivate);
                                                this.ubSalva.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.ubSalva.Enabled = false;
            this.ubSalva.Location = new System.Drawing.Point(770, 575);
            this.ubSalva.Name = "ubSalva";
            this.ubSalva.Size = new System.Drawing.Size(75, 75);
            this.ubSalva.TabIndex = 11;
            this.ubSalva.Text = "Salva Parametri";
            this.ubSalva.Click += new System.EventHandler(this.ubSalva_Click);
                                                this._frmSchedeTreeView_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Top.BackColor = System.Drawing.SystemColors.Control;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Top.Name = "_frmSchedeTreeView_Toolbars_Dock_Area_Top";
            this._frmSchedeTreeView_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(1008, 0);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
                                                this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.SystemColors.Control;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 729);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom.Name = "_frmSchedeTreeView_Toolbars_Dock_Area_Bottom";
            this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(1008, 0);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmSchedeTreeView_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Left.BackColor = System.Drawing.SystemColors.Control;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Left.Name = "_frmSchedeTreeView_Toolbars_Dock_Area_Left";
            this._frmSchedeTreeView_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 729);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmSchedeTreeView_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Right.BackColor = System.Drawing.SystemColors.Control;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmSchedeTreeView_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(1008, 0);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Right.Name = "_frmSchedeTreeView_Toolbars_Dock_Area_Right";
            this._frmSchedeTreeView_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 729);
            this._frmSchedeTreeView_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                                                    this.frmSchedeTreeView_Fill_Panel.ClientArea.Controls.Add(this.UltraGroupBox);
            this.frmSchedeTreeView_Fill_Panel.Cursor = System.Windows.Forms.Cursors.Default;
            this.frmSchedeTreeView_Fill_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.frmSchedeTreeView_Fill_Panel.Location = new System.Drawing.Point(0, 0);
            this.frmSchedeTreeView_Fill_Panel.Name = "frmSchedeTreeView_Fill_Panel";
            this.frmSchedeTreeView_Fill_Panel.Size = new System.Drawing.Size(1008, 729);
            this.frmSchedeTreeView_Fill_Panel.TabIndex = 5;
                                                this.UltraGroupBox.Controls.Add(this.TableLayoutPanel);
            this.UltraGroupBox.Controls.Add(this.ubChiudi);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(1008, 729);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.TableLayoutPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.TableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanel.ColumnCount = 2;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 140F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.Controls.Add(this.picView, 0, 1);
            this.TableLayoutPanel.Controls.Add(this.UltraTabControl, 1, 0);
            this.TableLayoutPanel.Location = new System.Drawing.Point(6, 12);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(996, 682);
            this.TableLayoutPanel.TabIndex = 1;
                                                this.picView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picView.Location = new System.Drawing.Point(3, 280);
            this.picView.Name = "picView";
            this.picView.Size = new System.Drawing.Size(134, 122);
            this.picView.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picView.TabIndex = 1;
            this.picView.TabStop = false;
                                                this.UltraTabControl.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControl.Controls.Add(this.ultraTabPageControl2);
            this.UltraTabControl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraTabControl.Location = new System.Drawing.Point(143, 3);
            this.UltraTabControl.Name = "UltraTabControl";
            this.TableLayoutPanel.SetRowSpan(this.UltraTabControl, 3);
            this.UltraTabControl.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControl.Size = new System.Drawing.Size(850, 676);
            this.UltraTabControl.TabIndex = 5;
            ultraTab1.Key = "tab1";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Selezione";
            ultraTab2.Key = "tab2";
            ultraTab2.TabPage = this.ultraTabPageControl2;
            ultraTab2.Text = "Configurazione";
            this.UltraTabControl.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1,
            ultraTab2});
            this.UltraTabControl.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
            this.UltraTabControl.SelectedTabChanging += new Infragistics.Win.UltraWinTabControl.SelectedTabChangingEventHandler(this.UltraTabControl_SelectedTabChanging);
            this.UltraTabControl.SelectedTabChanged += new Infragistics.Win.UltraWinTabControl.SelectedTabChangedEventHandler(this.UltraTabControl_SelectedTabChanged);
                                                this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(848, 653);
                                                this.ubChiudi.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.ubChiudi.ButtonStyle = Infragistics.Win.UIElementButtonStyle.WindowsVistaButton;
            this.ubChiudi.Location = new System.Drawing.Point(920, 700);
            this.ubChiudi.Name = "ubChiudi";
            this.ubChiudi.Size = new System.Drawing.Size(75, 23);
            this.ubChiudi.TabIndex = 0;
            this.ubChiudi.Text = "&Chiudi";
            this.ubChiudi.Click += new System.EventHandler(this.ubChiudi_Click);
                                                this.ubConferma.Dock = System.Windows.Forms.DockStyle.Top;
            this.ubConferma.Enabled = false;
            this.ubConferma.Location = new System.Drawing.Point(770, 3);
            this.ubConferma.Name = "ubConferma";
            this.ubConferma.Size = new System.Drawing.Size(75, 75);
            this.ubConferma.TabIndex = 12;
            this.ubConferma.Text = "Conferma Copia";
            this.ubConferma.Click += new System.EventHandler(this.ubConferma_Click);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1008, 729);
            this.Controls.Add(this.frmSchedeTreeView_Fill_Panel);
            this.Controls.Add(this._frmSchedeTreeView_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmSchedeTreeView_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmSchedeTreeView_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmSchedeTreeView_Toolbars_Dock_Area_Top);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MinimizeBox = false;
            this.Name = "frmPUCDSSStrutturaCopia";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmPUCDSSStrutturaCopia";
            this.ultraTabPageControl1.ResumeLayout(false);
            this.tlpDestinazione.ResumeLayout(false);
            this.tlpDestinazione.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridOrigine)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteCodUA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTreeOrigine)).EndInit();
            this.ultraTabPageControl2.ResumeLayout(false);
            this.TableLayoutPanelDestinazione.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGridDestinazione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.frmSchedeTreeView_Fill_Panel.ClientArea.ResumeLayout(false);
            this.frmSchedeTreeView_Fill_Panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            this.TableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picView)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControl)).EndInit();
            this.UltraTabControl.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.Misc.UltraPanel frmSchedeTreeView_Fill_Panel;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        internal System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        internal System.Windows.Forms.PictureBox picView;
        internal Infragistics.Win.Misc.UltraButton ubChiudi;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmSchedeTreeView_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmSchedeTreeView_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmSchedeTreeView_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmSchedeTreeView_Toolbars_Dock_Area_Top;
        private Infragistics.Win.UltraWinTree.UltraTree UltraTreeOrigine;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControl;
        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private Infragistics.Win.Misc.UltraSplitter UltraSplitter;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl2;
        private ScciCore.ucEasyTableLayoutPanel tlpDestinazione;
        private System.Windows.Forms.Label lblCodUA;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteCodUA;
        private System.Windows.Forms.Label lblCodUADes;
        private Infragistics.Win.UltraWinGrid.UltraGrid UltraGridDestinazione;
        private Infragistics.Win.UltraWinGrid.UltraGrid UltraGridOrigine;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanelDestinazione;
        private XmlEditor xmlParametri;
        private Infragistics.Win.Misc.UltraButton ubSalva;
        private Infragistics.Win.Misc.UltraButton ubConferma;
    }
}