namespace UnicodeSrl.ScciManagement
{
    partial class frmReportStoricizzati
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.UltraWinTabControl.UltraTab ultraTab1 = new Infragistics.Win.UltraWinTabControl.UltraTab();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            this.ultraTabPageControl1 = new Infragistics.Win.UltraWinTabControl.UltraTabPageControl();
            this.TableLayoutPanelEpi = new System.Windows.Forms.TableLayoutPanel();
            this.ubRicerca = new Infragistics.Win.Misc.UltraButton();
            this.uteCognome = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.uceFormatoReport = new Infragistics.Win.UltraWinEditors.UltraComboEditor();
            this.udteDataStampaFine = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.lblDataStampaFine = new System.Windows.Forms.Label();
            this.lblFormatoReport = new System.Windows.Forms.Label();
            this.lblDataStampaInizio = new System.Windows.Forms.Label();
            this.lblCognome = new System.Windows.Forms.Label();
            this.udteDataStampaInizio = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.ultraTabSharedControlsPage1 = new Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage();
            this.UltraTabControlFiltri = new Infragistics.Win.UltraWinTabControl.UltraTabControl();
            this.PicImage = new System.Windows.Forms.PictureBox();
            this.TableLayoutPanelDX = new System.Windows.Forms.TableLayoutPanel();
            this.UltraGrid = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.TableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
            this.frmDocumentiFirmati_Fill_Panel = new Infragistics.Win.Misc.UltraPanel();
            this.UltraGroupBox = new Infragistics.Win.Misc.UltraGroupBox();
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this._frmView_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmView_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmView_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._frmView_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.lblNome = new System.Windows.Forms.Label();
            this.uteNome = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblDataNascita = new System.Windows.Forms.Label();
            this.udteDataNascita = new Infragistics.Win.UltraWinEditors.UltraDateTimeEditor();
            this.lblNumeroCartella = new System.Windows.Forms.Label();
            this.uteNumeroCartella = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblUtente = new System.Windows.Forms.Label();
            this.uteUtente = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblNomePC = new System.Windows.Forms.Label();
            this.uteNomePC = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.ultraTabPageControl1.SuspendLayout();
            this.TableLayoutPanelEpi.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteCognome)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uceFormatoReport)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataStampaFine)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataStampaInizio)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControlFiltri)).BeginInit();
            this.UltraTabControlFiltri.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).BeginInit();
            this.TableLayoutPanelDX.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGrid)).BeginInit();
            this.TableLayoutPanel.SuspendLayout();
            this.frmDocumentiFirmati_Fill_Panel.ClientArea.SuspendLayout();
            this.frmDocumentiFirmati_Fill_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).BeginInit();
            this.UltraGroupBox.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteNome)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataNascita)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteNumeroCartella)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteUtente)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteNomePC)).BeginInit();
            this.SuspendLayout();
                                                this.ultraTabPageControl1.Controls.Add(this.TableLayoutPanelEpi);
            this.ultraTabPageControl1.Location = new System.Drawing.Point(1, 22);
            this.ultraTabPageControl1.Name = "ultraTabPageControl1";
            this.ultraTabPageControl1.Size = new System.Drawing.Size(588, 151);
                                                this.TableLayoutPanelEpi.ColumnCount = 5;
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.TableLayoutPanelEpi.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 76F));
            this.TableLayoutPanelEpi.Controls.Add(this.uteNomePC, 3, 3);
            this.TableLayoutPanelEpi.Controls.Add(this.lblNomePC, 2, 3);
            this.TableLayoutPanelEpi.Controls.Add(this.uteUtente, 1, 3);
            this.TableLayoutPanelEpi.Controls.Add(this.lblUtente, 0, 3);
            this.TableLayoutPanelEpi.Controls.Add(this.uteNumeroCartella, 3, 1);
            this.TableLayoutPanelEpi.Controls.Add(this.lblNumeroCartella, 2, 1);
            this.TableLayoutPanelEpi.Controls.Add(this.udteDataNascita, 1, 1);
            this.TableLayoutPanelEpi.Controls.Add(this.lblDataNascita, 0, 1);
            this.TableLayoutPanelEpi.Controls.Add(this.uteNome, 3, 0);
            this.TableLayoutPanelEpi.Controls.Add(this.lblNome, 2, 0);
            this.TableLayoutPanelEpi.Controls.Add(this.uceFormatoReport, 1, 4);
            this.TableLayoutPanelEpi.Controls.Add(this.udteDataStampaFine, 3, 2);
            this.TableLayoutPanelEpi.Controls.Add(this.lblDataStampaFine, 2, 2);
            this.TableLayoutPanelEpi.Controls.Add(this.lblFormatoReport, 0, 4);
            this.TableLayoutPanelEpi.Controls.Add(this.lblDataStampaInizio, 0, 2);
            this.TableLayoutPanelEpi.Controls.Add(this.ubRicerca, 4, 0);
            this.TableLayoutPanelEpi.Controls.Add(this.lblCognome, 0, 0);
            this.TableLayoutPanelEpi.Controls.Add(this.uteCognome, 1, 0);
            this.TableLayoutPanelEpi.Controls.Add(this.udteDataStampaInizio, 1, 2);
            this.TableLayoutPanelEpi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelEpi.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanelEpi.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanelEpi.Name = "TableLayoutPanelEpi";
            this.TableLayoutPanelEpi.RowCount = 5;
            this.TableLayoutPanelEpi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.TableLayoutPanelEpi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.TableLayoutPanelEpi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.TableLayoutPanelEpi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.TableLayoutPanelEpi.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.TableLayoutPanelEpi.Size = new System.Drawing.Size(588, 151);
            this.TableLayoutPanelEpi.TabIndex = 2;
                                                this.ubRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRicerca.Location = new System.Drawing.Point(513, 3);
            this.ubRicerca.Name = "ubRicerca";
            this.TableLayoutPanelEpi.SetRowSpan(this.ubRicerca, 3);
            this.ubRicerca.Size = new System.Drawing.Size(72, 84);
            this.ubRicerca.TabIndex = 9;
            this.ubRicerca.Text = "Ricerca";
            this.ubRicerca.Click += new System.EventHandler(this.ubRicerca_Click);
                                                this.uteCognome.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteCognome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteCognome.Location = new System.Drawing.Point(105, 3);
            this.uteCognome.Name = "uteCognome";
            this.uteCognome.Size = new System.Drawing.Size(147, 22);
            this.uteCognome.TabIndex = 0;
                                                this.uceFormatoReport.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.uceFormatoReport.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uceFormatoReport.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            this.uceFormatoReport.Location = new System.Drawing.Point(105, 123);
            this.uceFormatoReport.Name = "uceFormatoReport";
            this.uceFormatoReport.Size = new System.Drawing.Size(147, 22);
            this.uceFormatoReport.TabIndex = 8;
                                                this.udteDataStampaFine.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataStampaFine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.udteDataStampaFine.Location = new System.Drawing.Point(360, 63);
            this.udteDataStampaFine.MaskInput = "dd/mm/yyyy";
            this.udteDataStampaFine.Name = "udteDataStampaFine";
            this.udteDataStampaFine.Size = new System.Drawing.Size(147, 22);
            this.udteDataStampaFine.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataStampaFine.TabIndex = 5;
                                                this.lblDataStampaFine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataStampaFine.Location = new System.Drawing.Point(258, 60);
            this.lblDataStampaFine.Name = "lblDataStampaFine";
            this.lblDataStampaFine.Size = new System.Drawing.Size(96, 30);
            this.lblDataStampaFine.TabIndex = 8;
            this.lblDataStampaFine.Text = "Dt Stampa Fine";
            this.lblDataStampaFine.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.lblFormatoReport.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblFormatoReport.Location = new System.Drawing.Point(3, 120);
            this.lblFormatoReport.Name = "lblFormatoReport";
            this.lblFormatoReport.Size = new System.Drawing.Size(96, 31);
            this.lblFormatoReport.TabIndex = 7;
            this.lblFormatoReport.Text = "Formato Report";
            this.lblFormatoReport.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.lblDataStampaInizio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataStampaInizio.Location = new System.Drawing.Point(3, 60);
            this.lblDataStampaInizio.Name = "lblDataStampaInizio";
            this.lblDataStampaInizio.Size = new System.Drawing.Size(96, 30);
            this.lblDataStampaInizio.TabIndex = 4;
            this.lblDataStampaInizio.Text = "Dt. Stampa Inizio";
            this.lblDataStampaInizio.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.lblCognome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCognome.Location = new System.Drawing.Point(3, 0);
            this.lblCognome.Name = "lblCognome";
            this.lblCognome.Size = new System.Drawing.Size(96, 30);
            this.lblCognome.TabIndex = 0;
            this.lblCognome.Text = "Cognome";
            this.lblCognome.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.udteDataStampaInizio.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataStampaInizio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.udteDataStampaInizio.Location = new System.Drawing.Point(105, 63);
            this.udteDataStampaInizio.MaskInput = "dd/mm/yyyy";
            this.udteDataStampaInizio.Name = "udteDataStampaInizio";
            this.udteDataStampaInizio.Size = new System.Drawing.Size(147, 22);
            this.udteDataStampaInizio.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataStampaInizio.TabIndex = 4;
                                                this.ultraTabSharedControlsPage1.Location = new System.Drawing.Point(-10000, -10000);
            this.ultraTabSharedControlsPage1.Name = "ultraTabSharedControlsPage1";
            this.ultraTabSharedControlsPage1.Size = new System.Drawing.Size(588, 151);
                                                this.UltraTabControlFiltri.Controls.Add(this.ultraTabSharedControlsPage1);
            this.UltraTabControlFiltri.Controls.Add(this.ultraTabPageControl1);
            this.UltraTabControlFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraTabControlFiltri.Location = new System.Drawing.Point(3, 3);
            this.UltraTabControlFiltri.Name = "UltraTabControlFiltri";
            this.UltraTabControlFiltri.SharedControlsPage = this.ultraTabSharedControlsPage1;
            this.UltraTabControlFiltri.Size = new System.Drawing.Size(590, 174);
            this.UltraTabControlFiltri.TabIndex = 0;
            ultraTab1.Key = "Documenti";
            ultraTab1.TabPage = this.ultraTabPageControl1;
            ultraTab1.Text = "Documenti";
            this.UltraTabControlFiltri.Tabs.AddRange(new Infragistics.Win.UltraWinTabControl.UltraTab[] {
            ultraTab1});
            this.UltraTabControlFiltri.ViewStyle = Infragistics.Win.UltraWinTabControl.ViewStyle.Office2007;
                                                this.PicImage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PicImage.Location = new System.Drawing.Point(3, 158);
            this.PicImage.Name = "PicImage";
            this.PicImage.Size = new System.Drawing.Size(128, 122);
            this.PicImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.PicImage.TabIndex = 0;
            this.PicImage.TabStop = false;
                                                this.TableLayoutPanelDX.ColumnCount = 1;
            this.TableLayoutPanelDX.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelDX.Controls.Add(this.UltraTabControlFiltri, 0, 0);
            this.TableLayoutPanelDX.Controls.Add(this.UltraGrid, 0, 1);
            this.TableLayoutPanelDX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelDX.Location = new System.Drawing.Point(134, 0);
            this.TableLayoutPanelDX.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanelDX.Name = "TableLayoutPanelDX";
            this.TableLayoutPanelDX.RowCount = 2;
            this.TableLayoutPanel.SetRowSpan(this.TableLayoutPanelDX, 3);
            this.TableLayoutPanelDX.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 180F));
            this.TableLayoutPanelDX.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelDX.Size = new System.Drawing.Size(596, 438);
            this.TableLayoutPanelDX.TabIndex = 0;
                                                appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.UltraGrid.DisplayLayout.Appearance = appearance1;
            this.UltraGrid.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.UltraGrid.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance2.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.GroupByBox.Appearance = appearance2;
            appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGrid.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
            this.UltraGrid.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance4.BackColor2 = System.Drawing.SystemColors.Control;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.UltraGrid.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
            this.UltraGrid.DisplayLayout.MaxColScrollRegions = 1;
            this.UltraGrid.DisplayLayout.MaxRowScrollRegions = 1;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.UltraGrid.DisplayLayout.Override.ActiveCellAppearance = appearance5;
            appearance6.BackColor = System.Drawing.SystemColors.Highlight;
            appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.UltraGrid.DisplayLayout.Override.ActiveRowAppearance = appearance6;
            this.UltraGrid.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.UltraGrid.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.Override.CardAreaAppearance = appearance7;
            appearance8.BorderColor = System.Drawing.Color.Silver;
            appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.UltraGrid.DisplayLayout.Override.CellAppearance = appearance8;
            this.UltraGrid.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.UltraGrid.DisplayLayout.Override.CellPadding = 0;
            appearance9.BackColor = System.Drawing.SystemColors.Control;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.UltraGrid.DisplayLayout.Override.GroupByRowAppearance = appearance9;
            appearance10.TextHAlignAsString = "Left";
            this.UltraGrid.DisplayLayout.Override.HeaderAppearance = appearance10;
            this.UltraGrid.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.UltraGrid.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            this.UltraGrid.DisplayLayout.Override.RowAppearance = appearance11;
            this.UltraGrid.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance12.BackColor = System.Drawing.SystemColors.ControlLight;
            this.UltraGrid.DisplayLayout.Override.TemplateAddRowAppearance = appearance12;
            this.UltraGrid.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.UltraGrid.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.UltraGrid.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.UltraGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGrid.Location = new System.Drawing.Point(3, 183);
            this.UltraGrid.Name = "UltraGrid";
            this.UltraGrid.Size = new System.Drawing.Size(590, 252);
            this.UltraGrid.TabIndex = 0;
            this.UltraGrid.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.UltraGrid_InitializeLayout);
            this.UltraGrid.DoubleClickRow += new Infragistics.Win.UltraWinGrid.DoubleClickRowEventHandler(this.UltraGrid_DoubleClickRow);
                                                this.TableLayoutPanel.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanel.ColumnCount = 2;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 134F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanel.Controls.Add(this.PicImage, 0, 1);
            this.TableLayoutPanel.Controls.Add(this.TableLayoutPanelDX, 1, 0);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanel.Location = new System.Drawing.Point(3, 3);
            this.TableLayoutPanel.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 128F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(730, 438);
            this.TableLayoutPanel.TabIndex = 0;
                                                                                    this.frmDocumentiFirmati_Fill_Panel.ClientArea.Controls.Add(this.UltraGroupBox);
            this.frmDocumentiFirmati_Fill_Panel.Cursor = System.Windows.Forms.Cursors.Default;
            this.frmDocumentiFirmati_Fill_Panel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.frmDocumentiFirmati_Fill_Panel.Location = new System.Drawing.Point(8, 32);
            this.frmDocumentiFirmati_Fill_Panel.Name = "frmDocumentiFirmati_Fill_Panel";
            this.frmDocumentiFirmati_Fill_Panel.Size = new System.Drawing.Size(736, 444);
            this.frmDocumentiFirmati_Fill_Panel.TabIndex = 5;
                                                this.UltraGroupBox.Controls.Add(this.TableLayoutPanel);
            this.UltraGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraGroupBox.Location = new System.Drawing.Point(0, 0);
            this.UltraGroupBox.Name = "UltraGroupBox";
            this.UltraGroupBox.Size = new System.Drawing.Size(736, 444);
            this.UltraGroupBox.TabIndex = 0;
            this.UltraGroupBox.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.DockWithinContainerBaseType = typeof(System.Windows.Forms.Form);
            this.UltraToolbarsManager.FormDisplayStyle = Infragistics.Win.UltraWinToolbars.FormDisplayStyle.RoundedSizable;
            this.UltraToolbarsManager.MdiMergeable = false;
            this.UltraToolbarsManager.RuntimeCustomizationOptions = Infragistics.Win.UltraWinToolbars.RuntimeCustomizationOptions.None;
            this.UltraToolbarsManager.ShowFullMenusDelay = 500;
            this.UltraToolbarsManager.Style = Infragistics.Win.UltraWinToolbars.ToolbarStyle.Office2007;
                                                this._frmView_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmView_Toolbars_Dock_Area_Top.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmView_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._frmView_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmView_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._frmView_Toolbars_Dock_Area_Top.Name = "_frmView_Toolbars_Dock_Area_Top";
            this._frmView_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(752, 32);
            this._frmView_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmView_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmView_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmView_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._frmView_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmView_Toolbars_Dock_Area_Bottom.InitialResizeAreaExtent = 8;
            this._frmView_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 476);
            this._frmView_Toolbars_Dock_Area_Bottom.Name = "_frmView_Toolbars_Dock_Area_Bottom";
            this._frmView_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(752, 8);
            this._frmView_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmView_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmView_Toolbars_Dock_Area_Left.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmView_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._frmView_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmView_Toolbars_Dock_Area_Left.InitialResizeAreaExtent = 8;
            this._frmView_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 32);
            this._frmView_Toolbars_Dock_Area_Left.Name = "_frmView_Toolbars_Dock_Area_Left";
            this._frmView_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(8, 444);
            this._frmView_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._frmView_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._frmView_Toolbars_Dock_Area_Right.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(219)))), ((int)(((byte)(255)))));
            this._frmView_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._frmView_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._frmView_Toolbars_Dock_Area_Right.InitialResizeAreaExtent = 8;
            this._frmView_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(744, 32);
            this._frmView_Toolbars_Dock_Area_Right.Name = "_frmView_Toolbars_Dock_Area_Right";
            this._frmView_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(8, 444);
            this._frmView_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                this.lblNome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNome.Location = new System.Drawing.Point(258, 0);
            this.lblNome.Name = "lblNome";
            this.lblNome.Size = new System.Drawing.Size(96, 30);
            this.lblNome.TabIndex = 9;
            this.lblNome.Text = "Nome";
            this.lblNome.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.uteNome.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteNome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteNome.Location = new System.Drawing.Point(360, 3);
            this.uteNome.Name = "uteNome";
            this.uteNome.Size = new System.Drawing.Size(147, 22);
            this.uteNome.TabIndex = 1;
                                                this.lblDataNascita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataNascita.Location = new System.Drawing.Point(3, 30);
            this.lblDataNascita.Name = "lblDataNascita";
            this.lblDataNascita.Size = new System.Drawing.Size(96, 30);
            this.lblDataNascita.TabIndex = 11;
            this.lblDataNascita.Text = "Data di Nascita";
            this.lblDataNascita.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.udteDataNascita.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteDataNascita.Dock = System.Windows.Forms.DockStyle.Fill;
            this.udteDataNascita.Location = new System.Drawing.Point(105, 33);
            this.udteDataNascita.MaskInput = "dd/mm/yyyy";
            this.udteDataNascita.Name = "udteDataNascita";
            this.udteDataNascita.Size = new System.Drawing.Size(147, 22);
            this.udteDataNascita.SpinButtonDisplayStyle = Infragistics.Win.ButtonDisplayStyle.Always;
            this.udteDataNascita.TabIndex = 2;
                                                this.lblNumeroCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNumeroCartella.Location = new System.Drawing.Point(258, 30);
            this.lblNumeroCartella.Name = "lblNumeroCartella";
            this.lblNumeroCartella.Size = new System.Drawing.Size(96, 30);
            this.lblNumeroCartella.TabIndex = 13;
            this.lblNumeroCartella.Text = "Numero Cartella";
            this.lblNumeroCartella.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.uteNumeroCartella.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteNumeroCartella.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteNumeroCartella.Location = new System.Drawing.Point(360, 33);
            this.uteNumeroCartella.Name = "uteNumeroCartella";
            this.uteNumeroCartella.Size = new System.Drawing.Size(147, 22);
            this.uteNumeroCartella.TabIndex = 3;
                                                this.lblUtente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblUtente.Location = new System.Drawing.Point(3, 90);
            this.lblUtente.Name = "lblUtente";
            this.lblUtente.Size = new System.Drawing.Size(96, 30);
            this.lblUtente.TabIndex = 15;
            this.lblUtente.Text = "Utente";
            this.lblUtente.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.uteUtente.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteUtente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteUtente.Location = new System.Drawing.Point(105, 93);
            this.uteUtente.Name = "uteUtente";
            this.uteUtente.Size = new System.Drawing.Size(147, 22);
            this.uteUtente.TabIndex = 6;
                                                this.lblNomePC.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNomePC.Location = new System.Drawing.Point(258, 90);
            this.lblNomePC.Name = "lblNomePC";
            this.lblNomePC.Size = new System.Drawing.Size(96, 30);
            this.lblNomePC.TabIndex = 17;
            this.lblNomePC.Text = "Nome PC";
            this.lblNomePC.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.uteNomePC.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.uteNomePC.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteNomePC.Location = new System.Drawing.Point(360, 93);
            this.uteNomePC.Name = "uteNomePC";
            this.uteNomePC.Size = new System.Drawing.Size(147, 22);
            this.uteNomePC.TabIndex = 7;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(752, 484);
            this.Controls.Add(this.frmDocumentiFirmati_Fill_Panel);
            this.Controls.Add(this._frmView_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._frmView_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._frmView_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._frmView_Toolbars_Dock_Area_Top);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "frmReportStoricizzati";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frmReportStoricizzati";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmReportStoricizzati_FormClosing);
            this.ultraTabPageControl1.ResumeLayout(false);
            this.TableLayoutPanelEpi.ResumeLayout(false);
            this.TableLayoutPanelEpi.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteCognome)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uceFormatoReport)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataStampaFine)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataStampaInizio)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraTabControlFiltri)).EndInit();
            this.UltraTabControlFiltri.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.PicImage)).EndInit();
            this.TableLayoutPanelDX.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGrid)).EndInit();
            this.TableLayoutPanel.ResumeLayout(false);
            this.frmDocumentiFirmati_Fill_Panel.ClientArea.ResumeLayout(false);
            this.frmDocumentiFirmati_Fill_Panel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraGroupBox)).EndInit();
            this.UltraGroupBox.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteNome)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteDataNascita)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteNumeroCartella)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteUtente)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteNomePC)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Infragistics.Win.UltraWinTabControl.UltraTabSharedControlsPage ultraTabSharedControlsPage1;
        private Infragistics.Win.UltraWinEditors.UltraComboEditor uceFormatoReport;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor udteDataStampaFine;
        private System.Windows.Forms.Label lblDataStampaFine;
        private System.Windows.Forms.Label lblFormatoReport;
        private System.Windows.Forms.Label lblDataStampaInizio;
        private Infragistics.Win.Misc.UltraButton ubRicerca;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanelEpi;
        private System.Windows.Forms.Label lblCognome;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteCognome;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor udteDataStampaInizio;
        private Infragistics.Win.UltraWinTabControl.UltraTabControl UltraTabControlFiltri;
        private Infragistics.Win.UltraWinTabControl.UltraTabPageControl ultraTabPageControl1;
        private System.Windows.Forms.PictureBox PicImage;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanelDX;
        private Infragistics.Win.UltraWinGrid.UltraGrid UltraGrid;
        private System.Windows.Forms.TableLayoutPanel TableLayoutPanel;
        private Infragistics.Win.Misc.UltraPanel frmDocumentiFirmati_Fill_Panel;
        private Infragistics.Win.Misc.UltraGroupBox UltraGroupBox;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmView_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmView_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmView_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _frmView_Toolbars_Dock_Area_Top;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteNome;
        private System.Windows.Forms.Label lblNome;
        private Infragistics.Win.UltraWinEditors.UltraDateTimeEditor udteDataNascita;
        private System.Windows.Forms.Label lblDataNascita;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteNumeroCartella;
        private System.Windows.Forms.Label lblNumeroCartella;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteNomePC;
        private System.Windows.Forms.Label lblNomePC;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteUtente;
        private System.Windows.Forms.Label lblUtente;
    }
}