namespace UnicodeSrl.ScciCore
{
    partial class ucAgendaListaView
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinTree.Override _override1 = new Infragistics.Win.UltraWinTree.Override();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.ValueListItem valueListItem1 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem2 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem3 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem4 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem5 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem6 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem7 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem8 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.ValueListItem valueListItem9 = new Infragistics.Win.ValueListItem();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinDock.DockAreaPane dockAreaPane1 = new Infragistics.Win.UltraWinDock.DockAreaPane(Infragistics.Win.UltraWinDock.DockedLocation.DockedTop, new System.Guid("49a1fa4b-b3d1-4487-8ea7-feacdc8f54ec"));
            Infragistics.Win.UltraWinDock.DockableControlPane dockableControlPane1 = new Infragistics.Win.UltraWinDock.DockableControlPane(new System.Guid("0107bce1-06a1-4170-9b9d-00e62b2090b5"), new System.Guid("00000000-0000-0000-0000-000000000000"), -1, new System.Guid("49a1fa4b-b3d1-4487-8ea7-feacdc8f54ec"), -1);
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            this.pnlFiltri = new System.Windows.Forms.Panel();
            this.ucEasyTableLayoutPanelFiltri = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ucEasyTreeViewStato = new UnicodeSrl.ScciCore.ucEasyTreeView();
            this.udteFiltroA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.lblRange = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblDataFine = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.lblDataInizio = new UnicodeSrl.ScciCore.ucEasyLabel();
            this.udteFiltroDA = new UnicodeSrl.ScciCore.ucEasyDateTimeEditor();
            this.drFiltro = new UnicodeSrl.ScciCore.ucEasyDateRange();
            this.ubRefresh = new UnicodeSrl.ScciCore.ucEasyButton();
            this.UltraDockManager = new Infragistics.Win.UltraWinDock.UltraDockManager(this.components);
            this._ucAgendaListaViewUnpinnedTabAreaLeft = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucAgendaListaViewUnpinnedTabAreaRight = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucAgendaListaViewUnpinnedTabAreaTop = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucAgendaListaViewUnpinnedTabAreaBottom = new Infragistics.Win.UltraWinDock.UnpinnedTabArea();
            this._ucAgendaListaViewAutoHideControl = new Infragistics.Win.UltraWinDock.AutoHideControl();
            this.dockableWindow1 = new Infragistics.Win.UltraWinDock.DockableWindow();
            this.windowDockingArea1 = new Infragistics.Win.UltraWinDock.WindowDockingArea();
            this.ucEasyTableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.ugAppuntamenti = new UnicodeSrl.ScciCore.ucEasyGrid();
            this.UltraPopupControlContainer = new Infragistics.Win.Misc.UltraPopupControlContainer(this.components);
            this.pnlFiltri.SuspendLayout();
            this.ucEasyTableLayoutPanelFiltri.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewStato)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraDockManager)).BeginInit();
            this._ucAgendaListaViewAutoHideControl.SuspendLayout();
            this.dockableWindow1.SuspendLayout();
            this.ucEasyTableLayoutPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugAppuntamenti)).BeginInit();
            this.SuspendLayout();
                                                this.pnlFiltri.BackColor = System.Drawing.SystemColors.Control;
            this.pnlFiltri.Controls.Add(this.ucEasyTableLayoutPanelFiltri);
            this.pnlFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlFiltri.Location = new System.Drawing.Point(0, 18);
            this.pnlFiltri.Name = "pnlFiltri";
            this.pnlFiltri.Size = new System.Drawing.Size(600, 120);
            this.pnlFiltri.TabIndex = 2;
                                                this.ucEasyTableLayoutPanelFiltri.ColumnCount = 5;
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.ucEasyTableLayoutPanelFiltri.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 96F));
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ucEasyTreeViewStato, 2, 0);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.udteFiltroA, 1, 2);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.lblRange, 0, 0);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.lblDataFine, 0, 2);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.lblDataInizio, 0, 1);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.udteFiltroDA, 1, 1);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.drFiltro, 1, 0);
            this.ucEasyTableLayoutPanelFiltri.Controls.Add(this.ubRefresh, 4, 0);
            this.ucEasyTableLayoutPanelFiltri.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanelFiltri.Location = new System.Drawing.Point(0, 0);
            this.ucEasyTableLayoutPanelFiltri.Name = "ucEasyTableLayoutPanelFiltri";
            this.ucEasyTableLayoutPanelFiltri.RowCount = 3;
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.ucEasyTableLayoutPanelFiltri.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.ucEasyTableLayoutPanelFiltri.Size = new System.Drawing.Size(600, 120);
            this.ucEasyTableLayoutPanelFiltri.TabIndex = 1;
                                                appearance1.FontData.SizeInPoints = 12.1194F;
            this.ucEasyTreeViewStato.Appearance = appearance1;
            this.ucEasyTreeViewStato.BorderStyle = Infragistics.Win.UIElementBorderStyle.WindowsVista;
            this.ucEasyTableLayoutPanelFiltri.SetColumnSpan(this.ucEasyTreeViewStato, 2);
            this.ucEasyTreeViewStato.DisplayStyle = Infragistics.Win.UltraWinTree.UltraTreeDisplayStyle.WindowsVista;
            this.ucEasyTreeViewStato.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTreeViewStato.HideSelection = false;
            this.ucEasyTreeViewStato.Location = new System.Drawing.Point(255, 3);
            this.ucEasyTreeViewStato.Name = "ucEasyTreeViewStato";
            appearance2.BackColor = System.Drawing.Color.LightYellow;
            appearance2.BackColor2 = System.Drawing.Color.Orange;
            _override1.ActiveNodeAppearance = appearance2;
            _override1.SelectedNodeAppearance = appearance2;
            this.ucEasyTreeViewStato.Override = _override1;
            this.ucEasyTableLayoutPanelFiltri.SetRowSpan(this.ucEasyTreeViewStato, 3);
            this.ucEasyTreeViewStato.Size = new System.Drawing.Size(246, 114);
            this.ucEasyTreeViewStato.TabIndex = 17;
            this.ucEasyTreeViewStato.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.ucEasyTreeViewStato.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ucEasyTreeViewStato.AfterCheck += new Infragistics.Win.UltraWinTree.AfterNodeChangedEventHandler(this.ucEasyTreeViewStato_AfterCheck);
                                                appearance3.FontData.SizeInPoints = 12.1194F;
            this.udteFiltroA.Appearance = appearance3;
            this.udteFiltroA.AutoSize = false;
            this.udteFiltroA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance4.FontData.SizeInPoints = 12.1194F;
            this.udteFiltroA.DropDownAppearance = appearance4;
            this.udteFiltroA.Location = new System.Drawing.Point(129, 83);
            this.udteFiltroA.Name = "udteFiltroA";
            this.udteFiltroA.Size = new System.Drawing.Size(120, 34);
            this.udteFiltroA.TabIndex = 5;
            this.udteFiltroA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.udteFiltroA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance5.FontData.SizeInPoints = 12.1194F;
            appearance5.TextVAlignAsString = "Middle";
            this.lblRange.Appearance = appearance5;
            this.lblRange.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRange.Location = new System.Drawing.Point(3, 3);
            this.lblRange.Name = "lblRange";
            this.lblRange.ShortcutColor = System.Drawing.Color.Black;
            this.lblRange.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblRange.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblRange.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblRange.Size = new System.Drawing.Size(120, 34);
            this.lblRange.TabIndex = 4;
            this.lblRange.Text = "Periodo inserimento";
            this.lblRange.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
                                                appearance6.FontData.SizeInPoints = 12.1194F;
            appearance6.TextVAlignAsString = "Middle";
            this.lblDataFine.Appearance = appearance6;
            this.lblDataFine.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataFine.Location = new System.Drawing.Point(3, 83);
            this.lblDataFine.Name = "lblDataFine";
            this.lblDataFine.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataFine.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataFine.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataFine.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataFine.Size = new System.Drawing.Size(120, 34);
            this.lblDataFine.TabIndex = 1;
            this.lblDataFine.Text = "A";
            this.lblDataFine.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
                                                appearance7.FontData.SizeInPoints = 12.1194F;
            appearance7.TextVAlignAsString = "Middle";
            this.lblDataInizio.Appearance = appearance7;
            this.lblDataInizio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDataInizio.Location = new System.Drawing.Point(3, 43);
            this.lblDataInizio.Name = "lblDataInizio";
            this.lblDataInizio.ShortcutColor = System.Drawing.Color.Black;
            this.lblDataInizio.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.lblDataInizio.ShortcutKey = System.Windows.Forms.Keys.None;
            this.lblDataInizio.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.lblDataInizio.Size = new System.Drawing.Size(120, 34);
            this.lblDataInizio.TabIndex = 0;
            this.lblDataInizio.Text = "Da";
            this.lblDataInizio.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
                                                appearance8.FontData.SizeInPoints = 12.1194F;
            this.udteFiltroDA.Appearance = appearance8;
            this.udteFiltroDA.AutoSize = false;
            this.udteFiltroDA.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.udteFiltroDA.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance9.FontData.SizeInPoints = 12.1194F;
            this.udteFiltroDA.DropDownAppearance = appearance9;
            this.udteFiltroDA.Location = new System.Drawing.Point(129, 43);
            this.udteFiltroDA.Name = "udteFiltroDA";
            this.udteFiltroDA.Size = new System.Drawing.Size(120, 34);
            this.udteFiltroDA.TabIndex = 3;
            this.udteFiltroDA.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.udteFiltroDA.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
                                                appearance10.FontData.SizeInPoints = 12.1194F;
            this.drFiltro.Appearance = appearance10;
            this.drFiltro.AutoSize = false;
            this.drFiltro.DataEpisodio = new System.DateTime(((long)(0)));
            this.drFiltro.DateFuture = false;
            this.drFiltro.DisplayStyle = Infragistics.Win.EmbeddableElementDisplayStyle.Office2007;
            this.drFiltro.DisponibilitaAgende = false;
            this.drFiltro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.drFiltro.Domani = false;
            this.drFiltro.DropDownStyle = Infragistics.Win.DropDownStyle.DropDownList;
            valueListItem1.DisplayText = " ";
            valueListItem2.DataValue = "OGGI";
            valueListItem2.DisplayText = "Oggi";
            valueListItem3.DataValue = "24H";
            valueListItem3.DisplayText = "Ultime 24h";
            valueListItem4.DataValue = "48H";
            valueListItem4.DisplayText = "Ultime 48h";
            valueListItem5.DataValue = "7G";
            valueListItem5.DisplayText = "Ultimi 7gg";
            valueListItem6.DataValue = "30G";
            valueListItem6.DisplayText = "Ultimi 30gg";
            valueListItem7.DataValue = "60G";
            valueListItem7.DisplayText = "Ultimi 60gg";
            valueListItem8.DataValue = "90G";
            valueListItem8.DisplayText = "Ultimi 90gg";
            valueListItem9.DataValue = "6M";
            valueListItem9.DisplayText = "Ultimi 6 mesi";
            this.drFiltro.Items.AddRange(new Infragistics.Win.ValueListItem[] {
            valueListItem1,
            valueListItem2,
            valueListItem3,
            valueListItem4,
            valueListItem5,
            valueListItem6,
            valueListItem7,
            valueListItem8,
            valueListItem9});
            this.drFiltro.Location = new System.Drawing.Point(129, 3);
            this.drFiltro.Name = "drFiltro";
            this.drFiltro.Oggi = true;
            this.drFiltro.PassatoRemoto = false;
            this.drFiltro.Size = new System.Drawing.Size(120, 34);
            this.drFiltro.TabIndex = 6;
            this.drFiltro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.XSmall;
            this.drFiltro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.drFiltro.ValueChanged += new System.EventHandler(this.drFiltro_ValueChanged);
                                                appearance11.FontData.SizeInPoints = 15.58209F;
            appearance11.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance11.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance11.TextHAlignAsString = "Center";
            appearance11.TextVAlignAsString = "Bottom";
            this.ubRefresh.Appearance = appearance11;
            this.ubRefresh.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubRefresh.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRefresh.Location = new System.Drawing.Point(507, 3);
            this.ubRefresh.Name = "ubRefresh";
            this.ubRefresh.PercImageFill = 0.75F;
            this.ucEasyTableLayoutPanelFiltri.SetRowSpan(this.ubRefresh, 3);
            this.ubRefresh.ShortcutColor = System.Drawing.Color.Black;
            this.ubRefresh.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubRefresh.ShortcutKey = System.Windows.Forms.Keys.None;
            this.ubRefresh.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubRefresh.Size = new System.Drawing.Size(90, 114);
            this.ubRefresh.TabIndex = 8;
            this.ubRefresh.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubRefresh.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubRefresh.Click += new System.EventHandler(this.ubRefresh_Click);
                                                this.UltraDockManager.AnimationSpeed = Infragistics.Win.UltraWinDock.AnimationSpeed.StandardSpeedPlus5;
            this.UltraDockManager.CaptionButtonAlignment = Infragistics.Win.UltraWinDock.CaptionButtonAlignment.Near;
            this.UltraDockManager.CaptionStyle = Infragistics.Win.UltraWinDock.CaptionStyle.Office2007;
            this.UltraDockManager.DefaultPaneSettings.AllowClose = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.DefaultPaneSettings.AllowDockBottom = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.DefaultPaneSettings.AllowDockLeft = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.DefaultPaneSettings.AllowDockTop = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.DefaultPaneSettings.AllowFloating = Infragistics.Win.DefaultableBoolean.False;
            dockableControlPane1.Control = this.pnlFiltri;
            dockableControlPane1.FlyoutSize = new System.Drawing.Size(-1, 138);
            dockableControlPane1.OriginalControlBounds = new System.Drawing.Rectangle(54, 108, 503, 89);
            dockableControlPane1.Pinned = false;
            dockableControlPane1.Size = new System.Drawing.Size(100, 100);
            dockableControlPane1.Text = "FILTRO";
            dockAreaPane1.Panes.AddRange(new Infragistics.Win.UltraWinDock.DockablePaneBase[] {
            dockableControlPane1});
            dockAreaPane1.Size = new System.Drawing.Size(600, 138);
            this.UltraDockManager.DockAreas.AddRange(new Infragistics.Win.UltraWinDock.DockAreaPane[] {
            dockAreaPane1});
            this.UltraDockManager.HostControl = this;
            this.UltraDockManager.ShowCloseButton = false;
            this.UltraDockManager.UnpinnedTabStyle = Infragistics.Win.UltraWinTabs.TabStyle.Office2007Ribbon;
            this.UltraDockManager.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.UltraDockManager.WindowStyle = Infragistics.Win.UltraWinDock.WindowStyle.Office2007;
            this.UltraDockManager.InitializePane += new Infragistics.Win.UltraWinDock.InitializePaneEventHandler(this.UltraDockManager_InitializePane);
                                                this._ucAgendaListaViewUnpinnedTabAreaLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this._ucAgendaListaViewUnpinnedTabAreaLeft.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAgendaListaViewUnpinnedTabAreaLeft.Location = new System.Drawing.Point(0, 0);
            this._ucAgendaListaViewUnpinnedTabAreaLeft.Name = "_ucAgendaListaViewUnpinnedTabAreaLeft";
            this._ucAgendaListaViewUnpinnedTabAreaLeft.Owner = this.UltraDockManager;
            this._ucAgendaListaViewUnpinnedTabAreaLeft.Size = new System.Drawing.Size(0, 450);
            this._ucAgendaListaViewUnpinnedTabAreaLeft.TabIndex = 3;
                                                this._ucAgendaListaViewUnpinnedTabAreaRight.Dock = System.Windows.Forms.DockStyle.Right;
            this._ucAgendaListaViewUnpinnedTabAreaRight.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAgendaListaViewUnpinnedTabAreaRight.Location = new System.Drawing.Point(600, 0);
            this._ucAgendaListaViewUnpinnedTabAreaRight.Name = "_ucAgendaListaViewUnpinnedTabAreaRight";
            this._ucAgendaListaViewUnpinnedTabAreaRight.Owner = this.UltraDockManager;
            this._ucAgendaListaViewUnpinnedTabAreaRight.Size = new System.Drawing.Size(0, 450);
            this._ucAgendaListaViewUnpinnedTabAreaRight.TabIndex = 4;
                                                this._ucAgendaListaViewUnpinnedTabAreaTop.Dock = System.Windows.Forms.DockStyle.Top;
            this._ucAgendaListaViewUnpinnedTabAreaTop.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAgendaListaViewUnpinnedTabAreaTop.Location = new System.Drawing.Point(0, 0);
            this._ucAgendaListaViewUnpinnedTabAreaTop.Name = "_ucAgendaListaViewUnpinnedTabAreaTop";
            this._ucAgendaListaViewUnpinnedTabAreaTop.Owner = this.UltraDockManager;
            this._ucAgendaListaViewUnpinnedTabAreaTop.Size = new System.Drawing.Size(600, 23);
            this._ucAgendaListaViewUnpinnedTabAreaTop.TabIndex = 5;
                                                this._ucAgendaListaViewUnpinnedTabAreaBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this._ucAgendaListaViewUnpinnedTabAreaBottom.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAgendaListaViewUnpinnedTabAreaBottom.Location = new System.Drawing.Point(0, 450);
            this._ucAgendaListaViewUnpinnedTabAreaBottom.Name = "_ucAgendaListaViewUnpinnedTabAreaBottom";
            this._ucAgendaListaViewUnpinnedTabAreaBottom.Owner = this.UltraDockManager;
            this._ucAgendaListaViewUnpinnedTabAreaBottom.Size = new System.Drawing.Size(600, 0);
            this._ucAgendaListaViewUnpinnedTabAreaBottom.TabIndex = 6;
                                                this._ucAgendaListaViewAutoHideControl.Controls.Add(this.dockableWindow1);
            this._ucAgendaListaViewAutoHideControl.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._ucAgendaListaViewAutoHideControl.Location = new System.Drawing.Point(0, 23);
            this._ucAgendaListaViewAutoHideControl.Name = "_ucAgendaListaViewAutoHideControl";
            this._ucAgendaListaViewAutoHideControl.Owner = this.UltraDockManager;
            this._ucAgendaListaViewAutoHideControl.Size = new System.Drawing.Size(600, 143);
            this._ucAgendaListaViewAutoHideControl.TabIndex = 7;
                                                this.dockableWindow1.Controls.Add(this.pnlFiltri);
            this.dockableWindow1.Location = new System.Drawing.Point(0, 0);
            this.dockableWindow1.Name = "dockableWindow1";
            this.dockableWindow1.Owner = this.UltraDockManager;
            this.dockableWindow1.Size = new System.Drawing.Size(600, 138);
            this.dockableWindow1.TabIndex = 9;
                                                this.windowDockingArea1.Dock = System.Windows.Forms.DockStyle.Top;
            this.windowDockingArea1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.windowDockingArea1.Location = new System.Drawing.Point(0, 23);
            this.windowDockingArea1.Name = "windowDockingArea1";
            this.windowDockingArea1.Owner = this.UltraDockManager;
            this.windowDockingArea1.Size = new System.Drawing.Size(600, 143);
            this.windowDockingArea1.TabIndex = 8;
                                                this.ucEasyTableLayoutPanel.BackColor = System.Drawing.SystemColors.Control;
            this.ucEasyTableLayoutPanel.ColumnCount = 1;
            this.ucEasyTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanel.Controls.Add(this.ugAppuntamenti, 0, 0);
            this.ucEasyTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ucEasyTableLayoutPanel.Location = new System.Drawing.Point(0, 23);
            this.ucEasyTableLayoutPanel.Name = "ucEasyTableLayoutPanel";
            this.ucEasyTableLayoutPanel.RowCount = 1;
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ucEasyTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 307F));
            this.ucEasyTableLayoutPanel.Size = new System.Drawing.Size(600, 427);
            this.ucEasyTableLayoutPanel.TabIndex = 1;
                                                this.ugAppuntamenti.ColonnaRTFControlloContenuto = false;
            this.ugAppuntamenti.ColonnaRTFResize = "";
            this.ugAppuntamenti.DataRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ugAppuntamenti.DefaultAutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance12.BackColor = System.Drawing.SystemColors.Window;
            appearance12.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugAppuntamenti.DisplayLayout.Appearance = appearance12;
            this.ugAppuntamenti.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            this.ugAppuntamenti.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugAppuntamenti.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance13.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance13.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance13.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance13.BorderColor = System.Drawing.SystemColors.Window;
            this.ugAppuntamenti.DisplayLayout.GroupByBox.Appearance = appearance13;
            appearance14.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugAppuntamenti.DisplayLayout.GroupByBox.BandLabelAppearance = appearance14;
            this.ugAppuntamenti.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugAppuntamenti.DisplayLayout.GroupByBox.Hidden = true;
            this.ugAppuntamenti.DisplayLayout.GroupByBox.Prompt = "Trascina un\'intestazione della colonna qui per raggrupparla.";
            appearance15.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance15.BackColor2 = System.Drawing.SystemColors.Control;
            appearance15.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance15.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugAppuntamenti.DisplayLayout.GroupByBox.PromptAppearance = appearance15;
            this.ugAppuntamenti.DisplayLayout.MaxColScrollRegions = 1;
            this.ugAppuntamenti.DisplayLayout.MaxRowScrollRegions = 1;
            appearance16.BackColor = System.Drawing.SystemColors.Window;
            appearance16.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugAppuntamenti.DisplayLayout.Override.ActiveCellAppearance = appearance16;
            appearance17.BackColor = System.Drawing.SystemColors.Highlight;
            appearance17.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugAppuntamenti.DisplayLayout.Override.ActiveRowAppearance = appearance17;
            this.ugAppuntamenti.DisplayLayout.Override.AllowAddNew = Infragistics.Win.UltraWinGrid.AllowAddNew.No;
            this.ugAppuntamenti.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.ugAppuntamenti.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            this.ugAppuntamenti.DisplayLayout.Override.AllowRowFiltering = Infragistics.Win.DefaultableBoolean.False;
            this.ugAppuntamenti.DisplayLayout.Override.AllowUpdate = Infragistics.Win.DefaultableBoolean.False;
            this.ugAppuntamenti.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugAppuntamenti.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance18.BackColor = System.Drawing.SystemColors.Window;
            this.ugAppuntamenti.DisplayLayout.Override.CardAreaAppearance = appearance18;
            appearance19.BorderColor = System.Drawing.Color.Silver;
            appearance19.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugAppuntamenti.DisplayLayout.Override.CellAppearance = appearance19;
            this.ugAppuntamenti.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.ugAppuntamenti.DisplayLayout.Override.CellPadding = 0;
            this.ugAppuntamenti.DisplayLayout.Override.ColumnAutoSizeMode = Infragistics.Win.UltraWinGrid.ColumnAutoSizeMode.SiblingRowsOnly;
            appearance20.BackColor = System.Drawing.SystemColors.Control;
            appearance20.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance20.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance20.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance20.BorderColor = System.Drawing.SystemColors.Window;
            this.ugAppuntamenti.DisplayLayout.Override.GroupByRowAppearance = appearance20;
            appearance21.FontData.BoldAsString = "True";
            appearance21.TextHAlignAsString = "Center";
            this.ugAppuntamenti.DisplayLayout.Override.HeaderAppearance = appearance21;
            this.ugAppuntamenti.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortSingle;
            this.ugAppuntamenti.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsVista;
            appearance22.BackColor = System.Drawing.Color.WhiteSmoke;
            appearance22.ForeColor = System.Drawing.Color.DarkBlue;
            this.ugAppuntamenti.DisplayLayout.Override.RowAlternateAppearance = appearance22;
            appearance23.BackColor = System.Drawing.SystemColors.Window;
            appearance23.BorderColor = System.Drawing.Color.Silver;
            this.ugAppuntamenti.DisplayLayout.Override.RowAppearance = appearance23;
            this.ugAppuntamenti.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.ugAppuntamenti.DisplayLayout.Override.RowSizing = Infragistics.Win.UltraWinGrid.RowSizing.AutoFree;
            this.ugAppuntamenti.DisplayLayout.Override.SelectTypeCol = Infragistics.Win.UltraWinGrid.SelectType.None;
            this.ugAppuntamenti.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance24.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugAppuntamenti.DisplayLayout.Override.TemplateAddRowAppearance = appearance24;
            scrollBarLook1.ViewStyle = Infragistics.Win.UltraWinScrollBar.ScrollBarViewStyle.Office2010;
            this.ugAppuntamenti.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.ugAppuntamenti.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugAppuntamenti.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugAppuntamenti.DisplayLayout.TabNavigation = Infragistics.Win.UltraWinGrid.TabNavigation.NextControl;
            this.ugAppuntamenti.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugAppuntamenti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ugAppuntamenti.FattoreRidimensionamentoRTF = 21;
            this.ugAppuntamenti.FilterRowFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ugAppuntamenti.GridCaptionFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ugAppuntamenti.HeaderFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions._undefined;
            this.ugAppuntamenti.Location = new System.Drawing.Point(3, 3);
            this.ugAppuntamenti.Name = "ugAppuntamenti";
            this.ugAppuntamenti.ShowFilterRow = false;
            this.ugAppuntamenti.ShowGroupByBox = false;
            this.ugAppuntamenti.Size = new System.Drawing.Size(594, 421);
            this.ugAppuntamenti.TabIndex = 0;
            this.ugAppuntamenti.Text = "ucEasyGrid1";
            this.ugAppuntamenti.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.ugAppuntamenti.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ugAppuntamenti.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugAppuntamenti_InitializeLayout);
            this.ugAppuntamenti.InitializePrintPreview += new Infragistics.Win.UltraWinGrid.InitializePrintPreviewEventHandler(this.ugAppuntamenti_InitializePrintPreview);
            this.ugAppuntamenti.InitializeRow += new Infragistics.Win.UltraWinGrid.InitializeRowEventHandler(this.ugAppuntamenti_InitializeRow);
            this.ugAppuntamenti.AfterRowActivate += new System.EventHandler(this.ugAppuntamenti_AfterRowActivate);
            this.ugAppuntamenti.ClickCell += new Infragistics.Win.UltraWinGrid.ClickCellEventHandler(this.ugAppuntamenti_ClickCell);
                                                this.UltraPopupControlContainer.Opening += new System.ComponentModel.CancelEventHandler(this.UltraPopupControlContainer_Opening);
            this.UltraPopupControlContainer.Opened += new System.EventHandler(this.UltraPopupControlContainer_Opened);
            this.UltraPopupControlContainer.Closed += new System.EventHandler(this.UltraPopupControlContainer_Closed);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._ucAgendaListaViewAutoHideControl);
            this.Controls.Add(this.ucEasyTableLayoutPanel);
            this.Controls.Add(this.windowDockingArea1);
            this.Controls.Add(this._ucAgendaListaViewUnpinnedTabAreaBottom);
            this.Controls.Add(this._ucAgendaListaViewUnpinnedTabAreaTop);
            this.Controls.Add(this._ucAgendaListaViewUnpinnedTabAreaLeft);
            this.Controls.Add(this._ucAgendaListaViewUnpinnedTabAreaRight);
            this.Name = "ucAgendaListaView";
            this.Size = new System.Drawing.Size(600, 450);
            this.pnlFiltri.ResumeLayout(false);
            this.ucEasyTableLayoutPanelFiltri.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ucEasyTreeViewStato)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.udteFiltroDA)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.drFiltro)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraDockManager)).EndInit();
            this._ucAgendaListaViewAutoHideControl.ResumeLayout(false);
            this.dockableWindow1.ResumeLayout(false);
            this.ucEasyTableLayoutPanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ugAppuntamenti)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanel;
        private ucEasyTableLayoutPanel ucEasyTableLayoutPanelFiltri;
        private ucEasyLabel lblDataInizio;
        private ucEasyLabel lblDataFine;
        private ucEasyDateTimeEditor udteFiltroDA;
        private ucEasyLabel lblRange;
        private ucEasyDateTimeEditor udteFiltroA;
        private ucEasyDateRange drFiltro;
        private System.Windows.Forms.Panel pnlFiltri;
        private Infragistics.Win.UltraWinDock.UltraDockManager UltraDockManager;
        private Infragistics.Win.UltraWinDock.AutoHideControl _ucAgendaListaViewAutoHideControl;
        private Infragistics.Win.UltraWinDock.WindowDockingArea windowDockingArea1;
        private Infragistics.Win.UltraWinDock.DockableWindow dockableWindow1;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucAgendaListaViewUnpinnedTabAreaBottom;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucAgendaListaViewUnpinnedTabAreaTop;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucAgendaListaViewUnpinnedTabAreaRight;
        private Infragistics.Win.UltraWinDock.UnpinnedTabArea _ucAgendaListaViewUnpinnedTabAreaLeft;
        private ucEasyButton ubRefresh;
        public ucEasyGrid ugAppuntamenti;
        private ucEasyTreeView ucEasyTreeViewStato;
        private Infragistics.Win.Misc.UltraPopupControlContainer UltraPopupControlContainer;
    }
}
