namespace UnicodeSrl.ScciCore
{
    partial class ucBottom
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ucBottom));
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinToolbars.PopupMenuTool popupMenuTool1 = new Infragistics.Win.UltraWinToolbars.PopupMenuTool("MenuRight");
            this._ucBottom_Toolbars_Dock_Area_Left = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._ucBottom_Toolbars_Dock_Area_Right = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._ucBottom_Toolbars_Dock_Area_Top = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this._ucBottom_Toolbars_Dock_Area_Bottom = new Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea();
            this.TableLayoutPanel = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.TableLayoutPanelHome = new UnicodeSrl.ScciCore.ucEasyTableLayoutPanel(this.components);
            this.pbCartelleChiuse = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.pbHome = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.pbElencoPazienti = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.pbCartellaPaziente = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.pbStampe = new UnicodeSrl.ScciCore.ucEasyPictureBox();
            this.ubAvanti = new UnicodeSrl.ScciCore.ucEasyButton();
            this.ubIndietro = new UnicodeSrl.ScciCore.ucEasyButton();
            this.UltraToolbarsManager = new Infragistics.Win.UltraWinToolbars.UltraToolbarsManager(this.components);
            this.TableLayoutPanel.SuspendLayout();
            this.TableLayoutPanelHome.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbCartelleChiuse)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbHome)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbElencoPazienti)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbCartellaPaziente)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbStampe)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).BeginInit();
            this.SuspendLayout();
                                                this._ucBottom_Toolbars_Dock_Area_Left.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ucBottom_Toolbars_Dock_Area_Left.BackColor = System.Drawing.Color.SteelBlue;
            this._ucBottom_Toolbars_Dock_Area_Left.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Left;
            this._ucBottom_Toolbars_Dock_Area_Left.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ucBottom_Toolbars_Dock_Area_Left.Location = new System.Drawing.Point(0, 0);
            this._ucBottom_Toolbars_Dock_Area_Left.Name = "_ucBottom_Toolbars_Dock_Area_Left";
            this._ucBottom_Toolbars_Dock_Area_Left.Size = new System.Drawing.Size(0, 100);
            this._ucBottom_Toolbars_Dock_Area_Left.ToolbarsManager = this.UltraToolbarsManager;
                                                this._ucBottom_Toolbars_Dock_Area_Right.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ucBottom_Toolbars_Dock_Area_Right.BackColor = System.Drawing.Color.SteelBlue;
            this._ucBottom_Toolbars_Dock_Area_Right.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Right;
            this._ucBottom_Toolbars_Dock_Area_Right.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ucBottom_Toolbars_Dock_Area_Right.Location = new System.Drawing.Point(715, 0);
            this._ucBottom_Toolbars_Dock_Area_Right.Name = "_ucBottom_Toolbars_Dock_Area_Right";
            this._ucBottom_Toolbars_Dock_Area_Right.Size = new System.Drawing.Size(0, 100);
            this._ucBottom_Toolbars_Dock_Area_Right.ToolbarsManager = this.UltraToolbarsManager;
                                                this._ucBottom_Toolbars_Dock_Area_Top.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ucBottom_Toolbars_Dock_Area_Top.BackColor = System.Drawing.Color.SteelBlue;
            this._ucBottom_Toolbars_Dock_Area_Top.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Top;
            this._ucBottom_Toolbars_Dock_Area_Top.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ucBottom_Toolbars_Dock_Area_Top.Location = new System.Drawing.Point(0, 0);
            this._ucBottom_Toolbars_Dock_Area_Top.Name = "_ucBottom_Toolbars_Dock_Area_Top";
            this._ucBottom_Toolbars_Dock_Area_Top.Size = new System.Drawing.Size(715, 0);
            this._ucBottom_Toolbars_Dock_Area_Top.ToolbarsManager = this.UltraToolbarsManager;
                                                this._ucBottom_Toolbars_Dock_Area_Bottom.AccessibleRole = System.Windows.Forms.AccessibleRole.Grouping;
            this._ucBottom_Toolbars_Dock_Area_Bottom.BackColor = System.Drawing.Color.SteelBlue;
            this._ucBottom_Toolbars_Dock_Area_Bottom.DockedPosition = Infragistics.Win.UltraWinToolbars.DockedPosition.Bottom;
            this._ucBottom_Toolbars_Dock_Area_Bottom.ForeColor = System.Drawing.SystemColors.ControlText;
            this._ucBottom_Toolbars_Dock_Area_Bottom.Location = new System.Drawing.Point(0, 100);
            this._ucBottom_Toolbars_Dock_Area_Bottom.Name = "_ucBottom_Toolbars_Dock_Area_Bottom";
            this._ucBottom_Toolbars_Dock_Area_Bottom.Size = new System.Drawing.Size(715, 0);
            this._ucBottom_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.UltraToolbarsManager;
                                                this.TableLayoutPanel.ColumnCount = 7;
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 36F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 5F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.TableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2F));
            this.TableLayoutPanel.Controls.Add(this.TableLayoutPanelHome, 3, 1);
            this.TableLayoutPanel.Controls.Add(this.ubAvanti, 5, 1);
            this.TableLayoutPanel.Controls.Add(this.ubIndietro, 1, 1);
            this.TableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanel.Location = new System.Drawing.Point(0, 0);
            this.TableLayoutPanel.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanel.Name = "TableLayoutPanel";
            this.TableLayoutPanel.RowCount = 3;
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 80F));
            this.TableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 10F));
            this.TableLayoutPanel.Size = new System.Drawing.Size(715, 100);
            this.TableLayoutPanel.TabIndex = 0;
                                                this.TableLayoutPanelHome.BackColor = System.Drawing.Color.Transparent;
            this.TableLayoutPanelHome.ColumnCount = 7;
            this.TableLayoutPanelHome.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2.5F));
            this.TableLayoutPanelHome.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 19F));
            this.TableLayoutPanelHome.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 19F));
            this.TableLayoutPanelHome.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 19F));
            this.TableLayoutPanelHome.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 19F));
            this.TableLayoutPanelHome.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 19F));
            this.TableLayoutPanelHome.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2.5F));
            this.TableLayoutPanelHome.Controls.Add(this.pbCartelleChiuse, 5, 0);
            this.TableLayoutPanelHome.Controls.Add(this.pbHome, 1, 0);
            this.TableLayoutPanelHome.Controls.Add(this.pbElencoPazienti, 2, 0);
            this.TableLayoutPanelHome.Controls.Add(this.pbCartellaPaziente, 3, 0);
            this.TableLayoutPanelHome.Controls.Add(this.pbStampe, 4, 0);
            this.TableLayoutPanelHome.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TableLayoutPanelHome.Location = new System.Drawing.Point(227, 10);
            this.TableLayoutPanelHome.Margin = new System.Windows.Forms.Padding(0);
            this.TableLayoutPanelHome.Name = "TableLayoutPanelHome";
            this.TableLayoutPanelHome.RowCount = 1;
            this.TableLayoutPanelHome.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.TableLayoutPanelHome.Size = new System.Drawing.Size(257, 80);
            this.TableLayoutPanelHome.TabIndex = 2;
                                                this.pbCartelleChiuse.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.pbCartelleChiuse.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pbCartelleChiuse.BackgroundImage")));
            this.pbCartelleChiuse.Location = new System.Drawing.Point(198, 0);
            this.pbCartelleChiuse.Margin = new System.Windows.Forms.Padding(0);
            this.pbCartelleChiuse.Name = "pbCartelleChiuse";
            this.pbCartelleChiuse.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbCartelleChiuse.ShortcutKey = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.X)));
            this.pbCartelleChiuse.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbCartelleChiuse.Size = new System.Drawing.Size(48, 80);
            this.pbCartelleChiuse.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbCartelleChiuse.TabIndex = 4;
            this.pbCartelleChiuse.TabStop = false;
            this.pbCartelleChiuse.Click += new System.EventHandler(this.pbCartelleChiuse_Click);
                                                this.pbHome.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.pbHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pbHome.BackgroundImage")));
            this.pbHome.Location = new System.Drawing.Point(6, 0);
            this.pbHome.Margin = new System.Windows.Forms.Padding(0);
            this.pbHome.Name = "pbHome";
            this.pbHome.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbHome.ShortcutKey = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.H)));
            this.pbHome.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbHome.Size = new System.Drawing.Size(48, 80);
            this.pbHome.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbHome.TabIndex = 0;
            this.pbHome.TabStop = false;
            this.pbHome.Click += new System.EventHandler(this.pbHome_Click);
                                                this.pbElencoPazienti.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.pbElencoPazienti.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pbElencoPazienti.BackgroundImage")));
            this.pbElencoPazienti.Location = new System.Drawing.Point(54, 0);
            this.pbElencoPazienti.Margin = new System.Windows.Forms.Padding(0);
            this.pbElencoPazienti.Name = "pbElencoPazienti";
            this.pbElencoPazienti.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbElencoPazienti.ShortcutKey = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.P)));
            this.pbElencoPazienti.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbElencoPazienti.Size = new System.Drawing.Size(48, 80);
            this.pbElencoPazienti.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbElencoPazienti.TabIndex = 1;
            this.pbElencoPazienti.TabStop = false;
            this.pbElencoPazienti.Click += new System.EventHandler(this.pbElencoPazienti_Click);
                                                this.pbCartellaPaziente.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.pbCartellaPaziente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pbCartellaPaziente.BackgroundImage")));
            this.pbCartellaPaziente.Location = new System.Drawing.Point(102, 0);
            this.pbCartellaPaziente.Margin = new System.Windows.Forms.Padding(0);
            this.pbCartellaPaziente.Name = "pbCartellaPaziente";
            this.pbCartellaPaziente.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbCartellaPaziente.ShortcutKey = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.C)));
            this.pbCartellaPaziente.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.pbCartellaPaziente.Size = new System.Drawing.Size(48, 80);
            this.pbCartellaPaziente.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbCartellaPaziente.TabIndex = 2;
            this.pbCartellaPaziente.TabStop = false;
            this.pbCartellaPaziente.Click += new System.EventHandler(this.pbCartellaPaziente_Click);
                                                this.pbStampe.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)));
            this.pbStampe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pbStampe.BackgroundImage")));
            this.pbStampe.Location = new System.Drawing.Point(150, 0);
            this.pbStampe.Margin = new System.Windows.Forms.Padding(0);
            this.pbStampe.Name = "pbStampe";
            this.pbStampe.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.pbStampe.ShortcutKey = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Alt | System.Windows.Forms.Keys.S)));
            this.pbStampe.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_left;
            this.pbStampe.Size = new System.Drawing.Size(48, 80);
            this.pbStampe.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbStampe.TabIndex = 3;
            this.pbStampe.TabStop = false;
            this.pbStampe.Click += new System.EventHandler(this.pbStampe_Click);
                                                appearance1.FontData.SizeInPoints = 27.9403F;
            appearance1.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance1.ImageBackground")));
            appearance1.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance1.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance1.TextHAlignAsString = "Center";
            appearance1.TextVAlignAsString = "Middle";
            this.ubAvanti.Appearance = appearance1;
            this.ubAvanti.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.UltraToolbarsManager.SetContextMenuUltra(this.ubAvanti, "MenuRight");
            this.ubAvanti.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubAvanti.Location = new System.Drawing.Point(519, 10);
            this.ubAvanti.Margin = new System.Windows.Forms.Padding(0);
            this.ubAvanti.Name = "ubAvanti";
            this.ubAvanti.PercImageFill = 0.75F;
            this.ubAvanti.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubAvanti.ShortcutKey = System.Windows.Forms.Keys.F12;
            this.ubAvanti.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubAvanti.Size = new System.Drawing.Size(178, 80);
            this.ubAvanti.TabIndex = 3;
            this.ubAvanti.TabStop = false;
            this.ubAvanti.Text = "AVANTI";
            this.ubAvanti.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ubAvanti.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubAvanti.Click += new System.EventHandler(this.ubAvanti_Click);
                                                appearance2.FontData.SizeInPoints = 27.9403F;
            appearance2.ImageBackground = ((System.Drawing.Image)(resources.GetObject("appearance2.ImageBackground")));
            appearance2.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance2.ImageVAlign = Infragistics.Win.VAlign.Top;
            appearance2.TextHAlignAsString = "Center";
            appearance2.TextVAlignAsString = "Middle";
            this.ubIndietro.Appearance = appearance2;
            this.ubIndietro.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.ubIndietro.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubIndietro.Location = new System.Drawing.Point(14, 10);
            this.ubIndietro.Margin = new System.Windows.Forms.Padding(0);
            this.ubIndietro.Name = "ubIndietro";
            this.ubIndietro.PercImageFill = 0.75F;
            this.ubIndietro.ShortcutFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Small;
            this.ubIndietro.ShortcutKey = System.Windows.Forms.Keys.F1;
            this.ubIndietro.ShortcutPosition = UnicodeSrl.ScciCore.easyStatics.easyShortcutPosition.top_right;
            this.ubIndietro.Size = new System.Drawing.Size(178, 80);
            this.ubIndietro.TabIndex = 4;
            this.ubIndietro.TabStop = false;
            this.ubIndietro.Text = "INDIETRO";
            this.ubIndietro.TextFontRelativeDimension = UnicodeSrl.ScciCore.easyStatics.easyRelativeDimensions.Large;
            this.ubIndietro.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.ubIndietro.Click += new System.EventHandler(this.ubIndietro_Click);
                                                this.UltraToolbarsManager.DesignerFlags = 1;
            this.UltraToolbarsManager.DockWithinContainer = this;
            this.UltraToolbarsManager.ShowFullMenusDelay = 500;
            popupMenuTool1.SharedPropsInternal.Caption = "MenuRight";
            this.UltraToolbarsManager.Tools.AddRange(new Infragistics.Win.UltraWinToolbars.ToolBase[] {
            popupMenuTool1});
            this.UltraToolbarsManager.ToolClick += new Infragistics.Win.UltraWinToolbars.ToolClickEventHandler(this.UltraToolbarsManager_ToolClick);
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.SteelBlue;
            this.Controls.Add(this.TableLayoutPanel);
            this.Controls.Add(this._ucBottom_Toolbars_Dock_Area_Left);
            this.Controls.Add(this._ucBottom_Toolbars_Dock_Area_Right);
            this.Controls.Add(this._ucBottom_Toolbars_Dock_Area_Bottom);
            this.Controls.Add(this._ucBottom_Toolbars_Dock_Area_Top);
            this.Margin = new System.Windows.Forms.Padding(0);
            this.Name = "ucBottom";
            this.Size = new System.Drawing.Size(715, 100);
            this.TableLayoutPanel.ResumeLayout(false);
            this.TableLayoutPanelHome.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbCartelleChiuse)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbHome)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbElencoPazienti)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbCartellaPaziente)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbStampe)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.UltraToolbarsManager)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private ucEasyTableLayoutPanel TableLayoutPanel;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsManager UltraToolbarsManager;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ucBottom_Toolbars_Dock_Area_Left;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ucBottom_Toolbars_Dock_Area_Right;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ucBottom_Toolbars_Dock_Area_Bottom;
        private Infragistics.Win.UltraWinToolbars.UltraToolbarsDockArea _ucBottom_Toolbars_Dock_Area_Top;
        private ucEasyTableLayoutPanel TableLayoutPanelHome;
        public ucEasyButton ubAvanti;
        public ucEasyButton ubIndietro;
        private ucEasyPictureBox pbElencoPazienti;
        private ucEasyPictureBox pbHome;
        private ucEasyPictureBox pbCartellaPaziente;
        private ucEasyPictureBox pbStampe;
        private ucEasyPictureBox pbCartelleChiuse;
    }
}
