//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WsSCCI.net.asmn.sacconsensi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsensiSoap", Namespace="http://sac.org/Consensi")]
    public partial class Consensi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsensiCercaByIdPazienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsensiCercaByIdProvenienzaPazienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsensiCercaByCodiceFiscalePazienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsensiCercaByGeneralitaPazienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsensiCercaByTesseraPazienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsensiAggiungiOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsensiEliminaPerIdPazienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProvenienzaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RelazioniConMinoreCercaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Consensi() {
            this.Url = "https://ws-di-sac.asmn.net/ws-di-sac-2/consensi.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsensiCercaByIdPazienteCompletedEventHandler ConsensiCercaByIdPazienteCompleted;
        
        /// <remarks/>
        public event ConsensiCercaByIdProvenienzaPazienteCompletedEventHandler ConsensiCercaByIdProvenienzaPazienteCompleted;
        
        /// <remarks/>
        public event ConsensiCercaByCodiceFiscalePazienteCompletedEventHandler ConsensiCercaByCodiceFiscalePazienteCompleted;
        
        /// <remarks/>
        public event ConsensiCercaByGeneralitaPazienteCompletedEventHandler ConsensiCercaByGeneralitaPazienteCompleted;
        
        /// <remarks/>
        public event ConsensiCercaByTesseraPazienteCompletedEventHandler ConsensiCercaByTesseraPazienteCompleted;
        
        /// <remarks/>
        public event ConsensiAggiungiCompletedEventHandler ConsensiAggiungiCompleted;
        
        /// <remarks/>
        public event ConsensiEliminaPerIdPazienteCompletedEventHandler ConsensiEliminaPerIdPazienteCompleted;
        
        /// <remarks/>
        public event GetProvenienzaCompletedEventHandler GetProvenienzaCompleted;
        
        /// <remarks/>
        public event RelazioniConMinoreCercaCompletedEventHandler RelazioniConMinoreCercaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/ConsensiCercaByIdPaziente", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Consensi", IsNullable=false)]
        public ConsensiCercaByIdPazienteResponseConsensi[] ConsensiCercaByIdPaziente(string idPaziente) {
            object[] results = this.Invoke("ConsensiCercaByIdPaziente", new object[] {
                        idPaziente});
            return ((ConsensiCercaByIdPazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsensiCercaByIdPaziente(string idPaziente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsensiCercaByIdPaziente", new object[] {
                        idPaziente}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsensiCercaByIdPazienteResponseConsensi[] EndConsensiCercaByIdPaziente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsensiCercaByIdPazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsensiCercaByIdPazienteAsync(string idPaziente) {
            this.ConsensiCercaByIdPazienteAsync(idPaziente, null);
        }
        
        /// <remarks/>
        public void ConsensiCercaByIdPazienteAsync(string idPaziente, object userState) {
            if ((this.ConsensiCercaByIdPazienteOperationCompleted == null)) {
                this.ConsensiCercaByIdPazienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsensiCercaByIdPazienteOperationCompleted);
            }
            this.InvokeAsync("ConsensiCercaByIdPaziente", new object[] {
                        idPaziente}, this.ConsensiCercaByIdPazienteOperationCompleted, userState);
        }
        
        private void OnConsensiCercaByIdPazienteOperationCompleted(object arg) {
            if ((this.ConsensiCercaByIdPazienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsensiCercaByIdPazienteCompleted(this, new ConsensiCercaByIdPazienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/ConsensiCercaByIdProvenienzaPaziente", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Consensi", IsNullable=false)]
        public ConsensiCercaByIdProvenienzaPazienteResponseConsensi[] ConsensiCercaByIdProvenienzaPaziente(string provenienza, string idProvenienza) {
            object[] results = this.Invoke("ConsensiCercaByIdProvenienzaPaziente", new object[] {
                        provenienza,
                        idProvenienza});
            return ((ConsensiCercaByIdProvenienzaPazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsensiCercaByIdProvenienzaPaziente(string provenienza, string idProvenienza, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsensiCercaByIdProvenienzaPaziente", new object[] {
                        provenienza,
                        idProvenienza}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsensiCercaByIdProvenienzaPazienteResponseConsensi[] EndConsensiCercaByIdProvenienzaPaziente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsensiCercaByIdProvenienzaPazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsensiCercaByIdProvenienzaPazienteAsync(string provenienza, string idProvenienza) {
            this.ConsensiCercaByIdProvenienzaPazienteAsync(provenienza, idProvenienza, null);
        }
        
        /// <remarks/>
        public void ConsensiCercaByIdProvenienzaPazienteAsync(string provenienza, string idProvenienza, object userState) {
            if ((this.ConsensiCercaByIdProvenienzaPazienteOperationCompleted == null)) {
                this.ConsensiCercaByIdProvenienzaPazienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsensiCercaByIdProvenienzaPazienteOperationCompleted);
            }
            this.InvokeAsync("ConsensiCercaByIdProvenienzaPaziente", new object[] {
                        provenienza,
                        idProvenienza}, this.ConsensiCercaByIdProvenienzaPazienteOperationCompleted, userState);
        }
        
        private void OnConsensiCercaByIdProvenienzaPazienteOperationCompleted(object arg) {
            if ((this.ConsensiCercaByIdProvenienzaPazienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsensiCercaByIdProvenienzaPazienteCompleted(this, new ConsensiCercaByIdProvenienzaPazienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/ConsensiCercaByCodiceFiscalePaziente", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Consensi", IsNullable=false)]
        public ConsensiCercaByCodiceFiscalePazienteResponseConsensi[] ConsensiCercaByCodiceFiscalePaziente(string codiceFiscale) {
            object[] results = this.Invoke("ConsensiCercaByCodiceFiscalePaziente", new object[] {
                        codiceFiscale});
            return ((ConsensiCercaByCodiceFiscalePazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsensiCercaByCodiceFiscalePaziente(string codiceFiscale, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsensiCercaByCodiceFiscalePaziente", new object[] {
                        codiceFiscale}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsensiCercaByCodiceFiscalePazienteResponseConsensi[] EndConsensiCercaByCodiceFiscalePaziente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsensiCercaByCodiceFiscalePazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsensiCercaByCodiceFiscalePazienteAsync(string codiceFiscale) {
            this.ConsensiCercaByCodiceFiscalePazienteAsync(codiceFiscale, null);
        }
        
        /// <remarks/>
        public void ConsensiCercaByCodiceFiscalePazienteAsync(string codiceFiscale, object userState) {
            if ((this.ConsensiCercaByCodiceFiscalePazienteOperationCompleted == null)) {
                this.ConsensiCercaByCodiceFiscalePazienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsensiCercaByCodiceFiscalePazienteOperationCompleted);
            }
            this.InvokeAsync("ConsensiCercaByCodiceFiscalePaziente", new object[] {
                        codiceFiscale}, this.ConsensiCercaByCodiceFiscalePazienteOperationCompleted, userState);
        }
        
        private void OnConsensiCercaByCodiceFiscalePazienteOperationCompleted(object arg) {
            if ((this.ConsensiCercaByCodiceFiscalePazienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsensiCercaByCodiceFiscalePazienteCompleted(this, new ConsensiCercaByCodiceFiscalePazienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/ConsensiCercaByGeneralitaPaziente", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Consensi", IsNullable=false)]
        public ConsensiCercaByGeneralitaPazienteResponseConsensi[] ConsensiCercaByGeneralitaPaziente(string cognome, string nome, System.DateTime dataNascita, string comuneNascitaCodice) {
            object[] results = this.Invoke("ConsensiCercaByGeneralitaPaziente", new object[] {
                        cognome,
                        nome,
                        dataNascita,
                        comuneNascitaCodice});
            return ((ConsensiCercaByGeneralitaPazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsensiCercaByGeneralitaPaziente(string cognome, string nome, System.DateTime dataNascita, string comuneNascitaCodice, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsensiCercaByGeneralitaPaziente", new object[] {
                        cognome,
                        nome,
                        dataNascita,
                        comuneNascitaCodice}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsensiCercaByGeneralitaPazienteResponseConsensi[] EndConsensiCercaByGeneralitaPaziente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsensiCercaByGeneralitaPazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsensiCercaByGeneralitaPazienteAsync(string cognome, string nome, System.DateTime dataNascita, string comuneNascitaCodice) {
            this.ConsensiCercaByGeneralitaPazienteAsync(cognome, nome, dataNascita, comuneNascitaCodice, null);
        }
        
        /// <remarks/>
        public void ConsensiCercaByGeneralitaPazienteAsync(string cognome, string nome, System.DateTime dataNascita, string comuneNascitaCodice, object userState) {
            if ((this.ConsensiCercaByGeneralitaPazienteOperationCompleted == null)) {
                this.ConsensiCercaByGeneralitaPazienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsensiCercaByGeneralitaPazienteOperationCompleted);
            }
            this.InvokeAsync("ConsensiCercaByGeneralitaPaziente", new object[] {
                        cognome,
                        nome,
                        dataNascita,
                        comuneNascitaCodice}, this.ConsensiCercaByGeneralitaPazienteOperationCompleted, userState);
        }
        
        private void OnConsensiCercaByGeneralitaPazienteOperationCompleted(object arg) {
            if ((this.ConsensiCercaByGeneralitaPazienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsensiCercaByGeneralitaPazienteCompleted(this, new ConsensiCercaByGeneralitaPazienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/ConsensiCercaByTesseraPaziente", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Consensi", IsNullable=false)]
        public ConsensiCercaByTesseraPazienteResponseConsensi[] ConsensiCercaByTesseraPaziente(string tesseraSanitaria) {
            object[] results = this.Invoke("ConsensiCercaByTesseraPaziente", new object[] {
                        tesseraSanitaria});
            return ((ConsensiCercaByTesseraPazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsensiCercaByTesseraPaziente(string tesseraSanitaria, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsensiCercaByTesseraPaziente", new object[] {
                        tesseraSanitaria}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsensiCercaByTesseraPazienteResponseConsensi[] EndConsensiCercaByTesseraPaziente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsensiCercaByTesseraPazienteResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsensiCercaByTesseraPazienteAsync(string tesseraSanitaria) {
            this.ConsensiCercaByTesseraPazienteAsync(tesseraSanitaria, null);
        }
        
        /// <remarks/>
        public void ConsensiCercaByTesseraPazienteAsync(string tesseraSanitaria, object userState) {
            if ((this.ConsensiCercaByTesseraPazienteOperationCompleted == null)) {
                this.ConsensiCercaByTesseraPazienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsensiCercaByTesseraPazienteOperationCompleted);
            }
            this.InvokeAsync("ConsensiCercaByTesseraPaziente", new object[] {
                        tesseraSanitaria}, this.ConsensiCercaByTesseraPazienteOperationCompleted, userState);
        }
        
        private void OnConsensiCercaByTesseraPazienteOperationCompleted(object arg) {
            if ((this.ConsensiCercaByTesseraPazienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsensiCercaByTesseraPazienteCompleted(this, new ConsensiCercaByTesseraPazienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/ConsensiAggiungi", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Consensi", IsNullable=false)]
        public ConsensiAggiungiResponseConsensi[] ConsensiAggiungi(Consenso consenso) {
            object[] results = this.Invoke("ConsensiAggiungi", new object[] {
                        consenso});
            return ((ConsensiAggiungiResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsensiAggiungi(Consenso consenso, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsensiAggiungi", new object[] {
                        consenso}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsensiAggiungiResponseConsensi[] EndConsensiAggiungi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsensiAggiungiResponseConsensi[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsensiAggiungiAsync(Consenso consenso) {
            this.ConsensiAggiungiAsync(consenso, null);
        }
        
        /// <remarks/>
        public void ConsensiAggiungiAsync(Consenso consenso, object userState) {
            if ((this.ConsensiAggiungiOperationCompleted == null)) {
                this.ConsensiAggiungiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsensiAggiungiOperationCompleted);
            }
            this.InvokeAsync("ConsensiAggiungi", new object[] {
                        consenso}, this.ConsensiAggiungiOperationCompleted, userState);
        }
        
        private void OnConsensiAggiungiOperationCompleted(object arg) {
            if ((this.ConsensiAggiungiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsensiAggiungiCompleted(this, new ConsensiAggiungiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/ConsensiEliminaPerIdPaziente", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ConsensiEliminaPerIdPaziente(string IdPaziente, string UtenteOperazione) {
            object[] results = this.Invoke("ConsensiEliminaPerIdPaziente", new object[] {
                        IdPaziente,
                        UtenteOperazione});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsensiEliminaPerIdPaziente(string IdPaziente, string UtenteOperazione, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsensiEliminaPerIdPaziente", new object[] {
                        IdPaziente,
                        UtenteOperazione}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndConsensiEliminaPerIdPaziente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ConsensiEliminaPerIdPazienteAsync(string IdPaziente, string UtenteOperazione) {
            this.ConsensiEliminaPerIdPazienteAsync(IdPaziente, UtenteOperazione, null);
        }
        
        /// <remarks/>
        public void ConsensiEliminaPerIdPazienteAsync(string IdPaziente, string UtenteOperazione, object userState) {
            if ((this.ConsensiEliminaPerIdPazienteOperationCompleted == null)) {
                this.ConsensiEliminaPerIdPazienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsensiEliminaPerIdPazienteOperationCompleted);
            }
            this.InvokeAsync("ConsensiEliminaPerIdPaziente", new object[] {
                        IdPaziente,
                        UtenteOperazione}, this.ConsensiEliminaPerIdPazienteOperationCompleted, userState);
        }
        
        private void OnConsensiEliminaPerIdPazienteOperationCompleted(object arg) {
            if ((this.ConsensiEliminaPerIdPazienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsensiEliminaPerIdPazienteCompleted(this, new ConsensiEliminaPerIdPazienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/GetProvenienza", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProvenienza() {
            object[] results = this.Invoke("GetProvenienza", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProvenienza(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProvenienza", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetProvenienza(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProvenienzaAsync() {
            this.GetProvenienzaAsync(null);
        }
        
        /// <remarks/>
        public void GetProvenienzaAsync(object userState) {
            if ((this.GetProvenienzaOperationCompleted == null)) {
                this.GetProvenienzaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProvenienzaOperationCompleted);
            }
            this.InvokeAsync("GetProvenienza", new object[0], this.GetProvenienzaOperationCompleted, userState);
        }
        
        private void OnGetProvenienzaOperationCompleted(object arg) {
            if ((this.GetProvenienzaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProvenienzaCompleted(this, new GetProvenienzaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sac.org/Consensi/RelazioniConMinoreCerca", RequestNamespace="http://sac.org/Consensi", ResponseNamespace="http://sac.org/Consensi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("RelazioniConMinore", Namespace="http://sac.org/Types")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("RelazioneConMinore", IsNullable=false)]
        public RelazioneConMinoreType[] RelazioniConMinoreCerca() {
            object[] results = this.Invoke("RelazioniConMinoreCerca", new object[0]);
            return ((RelazioneConMinoreType[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRelazioniConMinoreCerca(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RelazioniConMinoreCerca", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public RelazioneConMinoreType[] EndRelazioniConMinoreCerca(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RelazioneConMinoreType[])(results[0]));
        }
        
        /// <remarks/>
        public void RelazioniConMinoreCercaAsync() {
            this.RelazioniConMinoreCercaAsync(null);
        }
        
        /// <remarks/>
        public void RelazioniConMinoreCercaAsync(object userState) {
            if ((this.RelazioniConMinoreCercaOperationCompleted == null)) {
                this.RelazioniConMinoreCercaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRelazioniConMinoreCercaOperationCompleted);
            }
            this.InvokeAsync("RelazioniConMinoreCerca", new object[0], this.RelazioniConMinoreCercaOperationCompleted, userState);
        }
        
        private void OnRelazioniConMinoreCercaOperationCompleted(object arg) {
            if ((this.RelazioniConMinoreCercaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RelazioniConMinoreCercaCompleted(this, new RelazioniConMinoreCercaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sac.org/Consensi")]
    public partial class ConsensiCercaByIdPazienteResponseConsensi {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Provenienza;
        
        /// <remarks/>
        public string IdProvenienza;
        
        /// <remarks/>
        public string IdPaziente;
        
        /// <remarks/>
        public string Tipo;
        
        /// <remarks/>
        public System.DateTime DataStato;
        
        /// <remarks/>
        public bool Stato;
        
        /// <remarks/>
        public string OperatoreId;
        
        /// <remarks/>
        public string OperatoreCognome;
        
        /// <remarks/>
        public string OperatoreNome;
        
        /// <remarks/>
        public string OperatoreComputer;
        
        /// <remarks/>
        public string PazienteCognome;
        
        /// <remarks/>
        public string PazienteNome;
        
        /// <remarks/>
        public string PazienteTessera;
        
        /// <remarks/>
        public string PazienteCodiceFiscale;
        
        /// <remarks/>
        public System.DateTime PazienteDataNascita;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PazienteDataNascitaSpecified;
        
        /// <remarks/>
        public string PazienteComuneNascitaCodice;
        
        /// <remarks/>
        public string PazienteComuneNascitaNome;
        
        /// <remarks/>
        public string PazienteNazionalitaCodice;
        
        /// <remarks/>
        public string PazienteNazionalitaNome;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace="http://sac.org/Types", IsNullable=false)]
        public AttributoType[] Attributi;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sac.org/Types")]
    public partial class AttributoType {
        
        /// <remarks/>
        public string Nome;
        
        /// <remarks/>
        public string Valore;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sac.org/Types")]
    public partial class RelazioneConMinoreType {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Descrizione;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sac.org/Consensi")]
    public partial class Consenso {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public TipoConsenso Tipo;
        
        /// <remarks/>
        public System.DateTime DataStato;
        
        /// <remarks/>
        public bool Stato;
        
        /// <remarks/>
        public string OperatoreId;
        
        /// <remarks/>
        public string OperatoreCognome;
        
        /// <remarks/>
        public string OperatoreNome;
        
        /// <remarks/>
        public string OperatoreComputer;
        
        /// <remarks/>
        public string PazienteProvenienza;
        
        /// <remarks/>
        public string PazienteIdProvenienza;
        
        /// <remarks/>
        public string PazienteCognome;
        
        /// <remarks/>
        public string PazienteNome;
        
        /// <remarks/>
        public string PazienteCodiceFiscale;
        
        /// <remarks/>
        public System.DateTime PazienteDataNascita;
        
        /// <remarks/>
        public string PazienteComuneNascitaCodice;
        
        /// <remarks/>
        public string PazienteNazionalitaCodice;
        
        /// <remarks/>
        public string PazienteTesseraSanitaria;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace="http://sac.org/Types", IsNullable=false)]
        public AttributoType[] Attributi;
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sac.org/Consensi")]
    public enum TipoConsenso {
        
        /// <remarks/>
        Generico = 1,
        
        /// <remarks/>
        Dossier = 2,
        
        /// <remarks/>
        DossierStorico = 4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sac.org/Consensi")]
    public partial class ConsensiCercaByIdProvenienzaPazienteResponseConsensi {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Provenienza;
        
        /// <remarks/>
        public string IdProvenienza;
        
        /// <remarks/>
        public string IdPaziente;
        
        /// <remarks/>
        public string Tipo;
        
        /// <remarks/>
        public System.DateTime DataStato;
        
        /// <remarks/>
        public bool Stato;
        
        /// <remarks/>
        public string OperatoreId;
        
        /// <remarks/>
        public string OperatoreCognome;
        
        /// <remarks/>
        public string OperatoreNome;
        
        /// <remarks/>
        public string OperatoreComputer;
        
        /// <remarks/>
        public string PazienteCognome;
        
        /// <remarks/>
        public string PazienteNome;
        
        /// <remarks/>
        public string PazienteTessera;
        
        /// <remarks/>
        public string PazienteCodiceFiscale;
        
        /// <remarks/>
        public System.DateTime PazienteDataNascita;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PazienteDataNascitaSpecified;
        
        /// <remarks/>
        public string PazienteComuneNascitaCodice;
        
        /// <remarks/>
        public string PazienteComuneNascitaNome;
        
        /// <remarks/>
        public string PazienteNazionalitaCodice;
        
        /// <remarks/>
        public string PazienteNazionalitaNome;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace="http://sac.org/Types", IsNullable=false)]
        public AttributoType[] Attributi;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sac.org/Consensi")]
    public partial class ConsensiCercaByCodiceFiscalePazienteResponseConsensi {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Provenienza;
        
        /// <remarks/>
        public string IdProvenienza;
        
        /// <remarks/>
        public string IdPaziente;
        
        /// <remarks/>
        public string Tipo;
        
        /// <remarks/>
        public System.DateTime DataStato;
        
        /// <remarks/>
        public bool Stato;
        
        /// <remarks/>
        public string OperatoreId;
        
        /// <remarks/>
        public string OperatoreCognome;
        
        /// <remarks/>
        public string OperatoreNome;
        
        /// <remarks/>
        public string OperatoreComputer;
        
        /// <remarks/>
        public string PazienteCognome;
        
        /// <remarks/>
        public string PazienteNome;
        
        /// <remarks/>
        public string PazienteTessera;
        
        /// <remarks/>
        public string PazienteCodiceFiscale;
        
        /// <remarks/>
        public System.DateTime PazienteDataNascita;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PazienteDataNascitaSpecified;
        
        /// <remarks/>
        public string PazienteComuneNascitaCodice;
        
        /// <remarks/>
        public string PazienteComuneNascitaNome;
        
        /// <remarks/>
        public string PazienteNazionalitaCodice;
        
        /// <remarks/>
        public string PazienteNazionalitaNome;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace="http://sac.org/Types", IsNullable=false)]
        public AttributoType[] Attributi;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sac.org/Consensi")]
    public partial class ConsensiCercaByGeneralitaPazienteResponseConsensi {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Provenienza;
        
        /// <remarks/>
        public string IdProvenienza;
        
        /// <remarks/>
        public string IdPaziente;
        
        /// <remarks/>
        public string Tipo;
        
        /// <remarks/>
        public System.DateTime DataStato;
        
        /// <remarks/>
        public bool Stato;
        
        /// <remarks/>
        public string OperatoreId;
        
        /// <remarks/>
        public string OperatoreCognome;
        
        /// <remarks/>
        public string OperatoreNome;
        
        /// <remarks/>
        public string OperatoreComputer;
        
        /// <remarks/>
        public string PazienteCognome;
        
        /// <remarks/>
        public string PazienteNome;
        
        /// <remarks/>
        public string PazienteTessera;
        
        /// <remarks/>
        public string PazienteCodiceFiscale;
        
        /// <remarks/>
        public System.DateTime PazienteDataNascita;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PazienteDataNascitaSpecified;
        
        /// <remarks/>
        public string PazienteComuneNascitaCodice;
        
        /// <remarks/>
        public string PazienteComuneNascitaNome;
        
        /// <remarks/>
        public string PazienteNazionalitaCodice;
        
        /// <remarks/>
        public string PazienteNazionalitaNome;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace="http://sac.org/Types", IsNullable=false)]
        public AttributoType[] Attributi;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sac.org/Consensi")]
    public partial class ConsensiCercaByTesseraPazienteResponseConsensi {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Provenienza;
        
        /// <remarks/>
        public string IdProvenienza;
        
        /// <remarks/>
        public string IdPaziente;
        
        /// <remarks/>
        public string Tipo;
        
        /// <remarks/>
        public System.DateTime DataStato;
        
        /// <remarks/>
        public bool Stato;
        
        /// <remarks/>
        public string OperatoreId;
        
        /// <remarks/>
        public string OperatoreCognome;
        
        /// <remarks/>
        public string OperatoreNome;
        
        /// <remarks/>
        public string OperatoreComputer;
        
        /// <remarks/>
        public string PazienteCognome;
        
        /// <remarks/>
        public string PazienteNome;
        
        /// <remarks/>
        public string PazienteTessera;
        
        /// <remarks/>
        public string PazienteCodiceFiscale;
        
        /// <remarks/>
        public System.DateTime PazienteDataNascita;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PazienteDataNascitaSpecified;
        
        /// <remarks/>
        public string PazienteComuneNascitaCodice;
        
        /// <remarks/>
        public string PazienteComuneNascitaNome;
        
        /// <remarks/>
        public string PazienteNazionalitaCodice;
        
        /// <remarks/>
        public string PazienteNazionalitaNome;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace="http://sac.org/Types", IsNullable=false)]
        public AttributoType[] Attributi;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sac.org/Consensi")]
    public partial class ConsensiAggiungiResponseConsensi {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string Provenienza;
        
        /// <remarks/>
        public string IdProvenienza;
        
        /// <remarks/>
        public string IdPaziente;
        
        /// <remarks/>
        public string Tipo;
        
        /// <remarks/>
        public System.DateTime DataStato;
        
        /// <remarks/>
        public bool Stato;
        
        /// <remarks/>
        public string OperatoreId;
        
        /// <remarks/>
        public string OperatoreCognome;
        
        /// <remarks/>
        public string OperatoreNome;
        
        /// <remarks/>
        public string OperatoreComputer;
        
        /// <remarks/>
        public string PazienteCognome;
        
        /// <remarks/>
        public string PazienteNome;
        
        /// <remarks/>
        public string PazienteTessera;
        
        /// <remarks/>
        public string PazienteCodiceFiscale;
        
        /// <remarks/>
        public System.DateTime PazienteDataNascita;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PazienteDataNascitaSpecified;
        
        /// <remarks/>
        public string PazienteComuneNascitaCodice;
        
        /// <remarks/>
        public string PazienteComuneNascitaNome;
        
        /// <remarks/>
        public string PazienteNazionalitaCodice;
        
        /// <remarks/>
        public string PazienteNazionalitaNome;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo", Namespace="http://sac.org/Types", IsNullable=false)]
        public AttributoType[] Attributi;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsensiCercaByIdPazienteCompletedEventHandler(object sender, ConsensiCercaByIdPazienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsensiCercaByIdPazienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsensiCercaByIdPazienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsensiCercaByIdPazienteResponseConsensi[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsensiCercaByIdPazienteResponseConsensi[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsensiCercaByIdProvenienzaPazienteCompletedEventHandler(object sender, ConsensiCercaByIdProvenienzaPazienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsensiCercaByIdProvenienzaPazienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsensiCercaByIdProvenienzaPazienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsensiCercaByIdProvenienzaPazienteResponseConsensi[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsensiCercaByIdProvenienzaPazienteResponseConsensi[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsensiCercaByCodiceFiscalePazienteCompletedEventHandler(object sender, ConsensiCercaByCodiceFiscalePazienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsensiCercaByCodiceFiscalePazienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsensiCercaByCodiceFiscalePazienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsensiCercaByCodiceFiscalePazienteResponseConsensi[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsensiCercaByCodiceFiscalePazienteResponseConsensi[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsensiCercaByGeneralitaPazienteCompletedEventHandler(object sender, ConsensiCercaByGeneralitaPazienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsensiCercaByGeneralitaPazienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsensiCercaByGeneralitaPazienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsensiCercaByGeneralitaPazienteResponseConsensi[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsensiCercaByGeneralitaPazienteResponseConsensi[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsensiCercaByTesseraPazienteCompletedEventHandler(object sender, ConsensiCercaByTesseraPazienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsensiCercaByTesseraPazienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsensiCercaByTesseraPazienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsensiCercaByTesseraPazienteResponseConsensi[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsensiCercaByTesseraPazienteResponseConsensi[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsensiAggiungiCompletedEventHandler(object sender, ConsensiAggiungiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsensiAggiungiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsensiAggiungiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsensiAggiungiResponseConsensi[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsensiAggiungiResponseConsensi[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsensiEliminaPerIdPazienteCompletedEventHandler(object sender, ConsensiEliminaPerIdPazienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsensiEliminaPerIdPazienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsensiEliminaPerIdPazienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetProvenienzaCompletedEventHandler(object sender, GetProvenienzaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProvenienzaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProvenienzaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RelazioniConMinoreCercaCompletedEventHandler(object sender, RelazioniConMinoreCercaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RelazioniConMinoreCercaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RelazioniConMinoreCercaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RelazioneConMinoreType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RelazioneConMinoreType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591