//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace UnicodeSrl.ASMN.WebNotificationService.SAC
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_IService", Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public interface IBasicHttpBinding_NorificaPaziente
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0/IService/ListenData", RequestNamespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0", ResponseNamespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        void ListenData([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] SoapPazienteType value);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class SoapPazienteType
    {

        private string idMessaggioField;

        private System.DateTime dataSequenzaField;

        private int azioneField;

        private PazienteType pazienteField;

        private PazienteFusoType fusioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdMessaggio
        {
            get
            {
                return this.idMessaggioField;
            }
            set
            {
                this.idMessaggioField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataSequenza
        {
            get
            {
                return this.dataSequenzaField;
            }
            set
            {
                this.dataSequenzaField = value;
            }
        }

        /// <remarks/>
        public int Azione
        {
            get
            {
                return this.azioneField;
            }
            set
            {
                this.azioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PazienteType Paziente
        {
            get
            {
                return this.pazienteField;
            }
            set
            {
                this.pazienteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PazienteFusoType Fusione
        {
            get
            {
                return this.fusioneField;
            }
            set
            {
                this.fusioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class PazienteType
    {

        private string idSacField;

        private string provenienzaField;

        private string idProvenienzaField;

        private long livelloAttendibilitaField;

        private CodiceDescrizioneType terminazioneField;

        private GeneralitaType generalitaField;

        private IndirizzoType residenzaField;

        private IndirizzoType domicilioField;

        private RecapitoType recapitoField;

        private AssistitoType assistitoField;

        private UslType uslResidenzaField;

        private UslType uslAssistenzaField;

        private MedicoDiBaseType medicoDiBaseField;

        private StpType sTPField;

        private AttributoType[] attributiField;

        private EsenzioneType[] esenzioniField;

        private ConsensoType[] consensiField;

        private SinonimoType[] sinonimiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdSac
        {
            get
            {
                return this.idSacField;
            }
            set
            {
                this.idSacField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Provenienza
        {
            get
            {
                return this.provenienzaField;
            }
            set
            {
                this.provenienzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdProvenienza
        {
            get
            {
                return this.idProvenienzaField;
            }
            set
            {
                this.idProvenienzaField = value;
            }
        }

        /// <remarks/>
        public long LivelloAttendibilita
        {
            get
            {
                return this.livelloAttendibilitaField;
            }
            set
            {
                this.livelloAttendibilitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType Terminazione
        {
            get
            {
                return this.terminazioneField;
            }
            set
            {
                this.terminazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public GeneralitaType Generalita
        {
            get
            {
                return this.generalitaField;
            }
            set
            {
                this.generalitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public IndirizzoType Residenza
        {
            get
            {
                return this.residenzaField;
            }
            set
            {
                this.residenzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public IndirizzoType Domicilio
        {
            get
            {
                return this.domicilioField;
            }
            set
            {
                this.domicilioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public RecapitoType Recapito
        {
            get
            {
                return this.recapitoField;
            }
            set
            {
                this.recapitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public AssistitoType Assistito
        {
            get
            {
                return this.assistitoField;
            }
            set
            {
                this.assistitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public UslType UslResidenza
        {
            get
            {
                return this.uslResidenzaField;
            }
            set
            {
                this.uslResidenzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public UslType UslAssistenza
        {
            get
            {
                return this.uslAssistenzaField;
            }
            set
            {
                this.uslAssistenzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public MedicoDiBaseType MedicoDiBase
        {
            get
            {
                return this.medicoDiBaseField;
            }
            set
            {
                this.medicoDiBaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public StpType STP
        {
            get
            {
                return this.sTPField;
            }
            set
            {
                this.sTPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo")]
        public AttributoType[] Attributi
        {
            get
            {
                return this.attributiField;
            }
            set
            {
                this.attributiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Esenzione")]
        public EsenzioneType[] Esenzioni
        {
            get
            {
                return this.esenzioniField;
            }
            set
            {
                this.esenzioniField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Consenso")]
        public ConsensoType[] Consensi
        {
            get
            {
                return this.consensiField;
            }
            set
            {
                this.consensiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Sinonimo")]
        public SinonimoType[] Sinonimi
        {
            get
            {
                return this.sinonimiField;
            }
            set
            {
                this.sinonimiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class CodiceDescrizioneType
    {

        private string codiceField;

        private string descrizioneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Descrizione
        {
            get
            {
                return this.descrizioneField;
            }
            set
            {
                this.descrizioneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class PazienteFusoType
    {

        private string idSacField;

        private string provenienzaField;

        private string idProvenienzaField;

        private GeneralitaType generalitaField;

        private AttributoType[] attributiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdSac
        {
            get
            {
                return this.idSacField;
            }
            set
            {
                this.idSacField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Provenienza
        {
            get
            {
                return this.provenienzaField;
            }
            set
            {
                this.provenienzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdProvenienza
        {
            get
            {
                return this.idProvenienzaField;
            }
            set
            {
                this.idProvenienzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public GeneralitaType Generalita
        {
            get
            {
                return this.generalitaField;
            }
            set
            {
                this.generalitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attributo")]
        public AttributoType[] Attributi
        {
            get
            {
                return this.attributiField;
            }
            set
            {
                this.attributiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class GeneralitaType
    {

        private string codiceFiscaleField;

        private string cognomeField;

        private string nomeField;

        private System.Nullable<System.DateTime> dataNascitaField;

        private bool dataNascitaFieldSpecified;

        private string sessoField;

        private string codiceSanitarioField;

        private string comuneNascitaCodiceField;

        private string comuneNascitaNomeField;

        private string nazionalitaCodiceField;

        private string nazionalitaNomeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Cognome
        {
            get
            {
                return this.cognomeField;
            }
            set
            {
                this.cognomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataNascita
        {
            get
            {
                return this.dataNascitaField;
            }
            set
            {
                this.dataNascitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataNascitaSpecified
        {
            get
            {
                return this.dataNascitaFieldSpecified;
            }
            set
            {
                this.dataNascitaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Sesso
        {
            get
            {
                return this.sessoField;
            }
            set
            {
                this.sessoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CodiceSanitario
        {
            get
            {
                return this.codiceSanitarioField;
            }
            set
            {
                this.codiceSanitarioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ComuneNascitaCodice
        {
            get
            {
                return this.comuneNascitaCodiceField;
            }
            set
            {
                this.comuneNascitaCodiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ComuneNascitaNome
        {
            get
            {
                return this.comuneNascitaNomeField;
            }
            set
            {
                this.comuneNascitaNomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NazionalitaCodice
        {
            get
            {
                return this.nazionalitaCodiceField;
            }
            set
            {
                this.nazionalitaCodiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NazionalitaNome
        {
            get
            {
                return this.nazionalitaNomeField;
            }
            set
            {
                this.nazionalitaNomeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class AttributoType
    {

        private string nomeField;

        private string valoreField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Valore
        {
            get
            {
                return this.valoreField;
            }
            set
            {
                this.valoreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class SinonimoType
    {

        private string provenienzaField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Provenienza
        {
            get
            {
                return this.provenienzaField;
            }
            set
            {
                this.provenienzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class OperatoreType
    {

        private string idField;

        private string cognomeField;

        private string nomeField;

        private string computerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Cognome
        {
            get
            {
                return this.cognomeField;
            }
            set
            {
                this.cognomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Computer
        {
            get
            {
                return this.computerField;
            }
            set
            {
                this.computerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class ConsensoType
    {

        private string provenienzaField;

        private string idProvenienzaField;

        private string tipoField;

        private bool statoField;

        private System.DateTime dataStatoField;

        private OperatoreType operatoreField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Provenienza
        {
            get
            {
                return this.provenienzaField;
            }
            set
            {
                this.provenienzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string IdProvenienza
        {
            get
            {
                return this.idProvenienzaField;
            }
            set
            {
                this.idProvenienzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }

        /// <remarks/>
        public bool Stato
        {
            get
            {
                return this.statoField;
            }
            set
            {
                this.statoField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DataStato
        {
            get
            {
                return this.dataStatoField;
            }
            set
            {
                this.dataStatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public OperatoreType Operatore
        {
            get
            {
                return this.operatoreField;
            }
            set
            {
                this.operatoreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class EsenzioneType
    {

        private string codiceEsenzioneField;

        private string codiceDiagnosiField;

        private bool patologicaField;

        private System.Nullable<System.DateTime> dataInizioValiditaField;

        private System.Nullable<System.DateTime> dataFineValiditaField;

        private bool dataFineValiditaFieldSpecified;

        private string numeroAutorizzazioneEsenzioneField;

        private string noteAggiuntiveField;

        private CodiceDescrizioneType testoEsenzioneField;

        private string decodificaEsenzioneDiagnosiField;

        private string attributoEsenzioneDiagnosiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CodiceEsenzione
        {
            get
            {
                return this.codiceEsenzioneField;
            }
            set
            {
                this.codiceEsenzioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CodiceDiagnosi
        {
            get
            {
                return this.codiceDiagnosiField;
            }
            set
            {
                this.codiceDiagnosiField = value;
            }
        }

        /// <remarks/>
        public bool Patologica
        {
            get
            {
                return this.patologicaField;
            }
            set
            {
                this.patologicaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataInizioValidita
        {
            get
            {
                return this.dataInizioValiditaField;
            }
            set
            {
                this.dataInizioValiditaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataFineValidita
        {
            get
            {
                return this.dataFineValiditaField;
            }
            set
            {
                this.dataFineValiditaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataFineValiditaSpecified
        {
            get
            {
                return this.dataFineValiditaFieldSpecified;
            }
            set
            {
                this.dataFineValiditaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NumeroAutorizzazioneEsenzione
        {
            get
            {
                return this.numeroAutorizzazioneEsenzioneField;
            }
            set
            {
                this.numeroAutorizzazioneEsenzioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string NoteAggiuntive
        {
            get
            {
                return this.noteAggiuntiveField;
            }
            set
            {
                this.noteAggiuntiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CodiceDescrizioneType TestoEsenzione
        {
            get
            {
                return this.testoEsenzioneField;
            }
            set
            {
                this.testoEsenzioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string DecodificaEsenzioneDiagnosi
        {
            get
            {
                return this.decodificaEsenzioneDiagnosiField;
            }
            set
            {
                this.decodificaEsenzioneDiagnosiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AttributoEsenzioneDiagnosi
        {
            get
            {
                return this.attributoEsenzioneDiagnosiField;
            }
            set
            {
                this.attributoEsenzioneDiagnosiField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class StpType
    {

        private string codiceField;

        private System.Nullable<System.DateTime> dataInizioField;

        private bool dataInizioFieldSpecified;

        private System.Nullable<System.DateTime> dataFineField;

        private bool dataFineFieldSpecified;

        private string motivoAnnulloField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataInizio
        {
            get
            {
                return this.dataInizioField;
            }
            set
            {
                this.dataInizioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataInizioSpecified
        {
            get
            {
                return this.dataInizioFieldSpecified;
            }
            set
            {
                this.dataInizioFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataFine
        {
            get
            {
                return this.dataFineField;
            }
            set
            {
                this.dataFineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataFineSpecified
        {
            get
            {
                return this.dataFineFieldSpecified;
            }
            set
            {
                this.dataFineFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string MotivoAnnullo
        {
            get
            {
                return this.motivoAnnulloField;
            }
            set
            {
                this.motivoAnnulloField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class MedicoDiBaseType
    {

        private string codiceField;

        private string codiceFiscaleField;

        private string cognomeNomeField;

        private string distrettoField;

        private System.Nullable<System.DateTime> dataSceltaField;

        private bool dataSceltaFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CodiceFiscale
        {
            get
            {
                return this.codiceFiscaleField;
            }
            set
            {
                this.codiceFiscaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CognomeNome
        {
            get
            {
                return this.cognomeNomeField;
            }
            set
            {
                this.cognomeNomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Distretto
        {
            get
            {
                return this.distrettoField;
            }
            set
            {
                this.distrettoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataScelta
        {
            get
            {
                return this.dataSceltaField;
            }
            set
            {
                this.dataSceltaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSceltaSpecified
        {
            get
            {
                return this.dataSceltaFieldSpecified;
            }
            set
            {
                this.dataSceltaFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class UslType
    {

        private string codiceField;

        private string regioneCodiceField;

        private string comuneCodiceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Codice
        {
            get
            {
                return this.codiceField;
            }
            set
            {
                this.codiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RegioneCodice
        {
            get
            {
                return this.regioneCodiceField;
            }
            set
            {
                this.regioneCodiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ComuneCodice
        {
            get
            {
                return this.comuneCodiceField;
            }
            set
            {
                this.comuneCodiceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class AssistitoType
    {

        private System.Nullable<byte> posizioneField;

        private System.Nullable<System.DateTime> dataInizioField;

        private bool dataInizioFieldSpecified;

        private System.Nullable<System.DateTime> dataScadenzaField;

        private bool dataScadenzaFieldSpecified;

        private System.Nullable<System.DateTime> dataTerminazioneField;

        private bool dataTerminazioneFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<byte> Posizione
        {
            get
            {
                return this.posizioneField;
            }
            set
            {
                this.posizioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataInizio
        {
            get
            {
                return this.dataInizioField;
            }
            set
            {
                this.dataInizioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataInizioSpecified
        {
            get
            {
                return this.dataInizioFieldSpecified;
            }
            set
            {
                this.dataInizioFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataScadenza
        {
            get
            {
                return this.dataScadenzaField;
            }
            set
            {
                this.dataScadenzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataScadenzaSpecified
        {
            get
            {
                return this.dataScadenzaFieldSpecified;
            }
            set
            {
                this.dataScadenzaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataTerminazione
        {
            get
            {
                return this.dataTerminazioneField;
            }
            set
            {
                this.dataTerminazioneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataTerminazioneSpecified
        {
            get
            {
                return this.dataTerminazioneFieldSpecified;
            }
            set
            {
                this.dataTerminazioneFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class RecapitoType
    {

        private string comuneCodiceField;

        private string comuneNomeField;

        private string indirizzoField;

        private string localitaField;

        private string cAPField;

        private string telefono1Field;

        private string telefono2Field;

        private string telefono3Field;

        private string emailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ComuneCodice
        {
            get
            {
                return this.comuneCodiceField;
            }
            set
            {
                this.comuneCodiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ComuneNome
        {
            get
            {
                return this.comuneNomeField;
            }
            set
            {
                this.comuneNomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Indirizzo
        {
            get
            {
                return this.indirizzoField;
            }
            set
            {
                this.indirizzoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Localita
        {
            get
            {
                return this.localitaField;
            }
            set
            {
                this.localitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CAP
        {
            get
            {
                return this.cAPField;
            }
            set
            {
                this.cAPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Telefono1
        {
            get
            {
                return this.telefono1Field;
            }
            set
            {
                this.telefono1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Telefono2
        {
            get
            {
                return this.telefono2Field;
            }
            set
            {
                this.telefono2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Telefono3
        {
            get
            {
                return this.telefono3Field;
            }
            set
            {
                this.telefono3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.progel.it/WCF/Sac/NotificaPazienteType/2.0")]
    public partial class IndirizzoType
    {

        private string comuneCodiceField;

        private string comuneNomeField;

        private string indirizzoField;

        private string localitaField;

        private string cAPField;

        private System.Nullable<System.DateTime> dataDecorrenzaField;

        private bool dataDecorrenzaFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ComuneCodice
        {
            get
            {
                return this.comuneCodiceField;
            }
            set
            {
                this.comuneCodiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ComuneNome
        {
            get
            {
                return this.comuneNomeField;
            }
            set
            {
                this.comuneNomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Indirizzo
        {
            get
            {
                return this.indirizzoField;
            }
            set
            {
                this.indirizzoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Localita
        {
            get
            {
                return this.localitaField;
            }
            set
            {
                this.localitaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CAP
        {
            get
            {
                return this.cAPField;
            }
            set
            {
                this.cAPField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> DataDecorrenza
        {
            get
            {
                return this.dataDecorrenzaField;
            }
            set
            {
                this.dataDecorrenzaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataDecorrenzaSpecified
        {
            get
            {
                return this.dataDecorrenzaFieldSpecified;
            }
            set
            {
                this.dataDecorrenzaFieldSpecified = value;
            }
        }
    }

}
