//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService", Namespace="http://schemas.progel.it/WCF/OE/StatoRichiedenteGenerico/1.0")]
public interface IBasicHttpBinding_IServiceNS {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.progel.it/WCF/OE/StatoRichiedenteGenerico/1.0/IService/ListenData", RequestNamespace="http://schemas.progel.it/WCF/OE/StatoRichiedenteGenerico/1.0", ResponseNamespace="http://schemas.progel.it/WCF/OE/StatoRichiedenteGenerico/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    void ListenData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] StatoType value);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class StatoType {
    
    private string idRichiestaOrderEntryField;
    
    private string statoOrderEntryField;
    
    private string idRichiestaRichiedenteField;
    
    private SistemaType sistemaRichiedenteField;
    
    private string idRichiestaEroganteField;
    
    private SistemaType sistemaEroganteField;
    
    private System.Nullable<System.DateTime> dataVersioneField;
    
    private bool dataVersioneFieldSpecified;
    
    private System.Nullable<System.DateTime> dataPrenotazioneField;
    
    private bool dataPrenotazioneFieldSpecified;
    
    private OperatoreType operatoreField;
    
    private PazienteType pazienteField;
    
    private string noteField;
    
    private ConsensoType[] consensiField;
    
    private DatoNomeValoreType[] datiAggiuntiviField;
    
    private DatoNomeValoreType[] datiPersistentiField;
    
    private RigaErogataType[] righeErogateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IdRichiestaOrderEntry {
        get {
            return this.idRichiestaOrderEntryField;
        }
        set {
            this.idRichiestaOrderEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string StatoOrderEntry {
        get {
            return this.statoOrderEntryField;
        }
        set {
            this.statoOrderEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IdRichiestaRichiedente {
        get {
            return this.idRichiestaRichiedenteField;
        }
        set {
            this.idRichiestaRichiedenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SistemaType SistemaRichiedente {
        get {
            return this.sistemaRichiedenteField;
        }
        set {
            this.sistemaRichiedenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IdRichiestaErogante {
        get {
            return this.idRichiestaEroganteField;
        }
        set {
            this.idRichiestaEroganteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SistemaType SistemaErogante {
        get {
            return this.sistemaEroganteField;
        }
        set {
            this.sistemaEroganteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DataVersione {
        get {
            return this.dataVersioneField;
        }
        set {
            this.dataVersioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataVersioneSpecified {
        get {
            return this.dataVersioneFieldSpecified;
        }
        set {
            this.dataVersioneFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DataPrenotazione {
        get {
            return this.dataPrenotazioneField;
        }
        set {
            this.dataPrenotazioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataPrenotazioneSpecified {
        get {
            return this.dataPrenotazioneFieldSpecified;
        }
        set {
            this.dataPrenotazioneFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperatoreType Operatore {
        get {
            return this.operatoreField;
        }
        set {
            this.operatoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PazienteType Paziente {
        get {
            return this.pazienteField;
        }
        set {
            this.pazienteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Consenso")]
    public ConsensoType[] Consensi {
        get {
            return this.consensiField;
        }
        set {
            this.consensiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DatoAggiuntivo")]
    public DatoNomeValoreType[] DatiAggiuntivi {
        get {
            return this.datiAggiuntiviField;
        }
        set {
            this.datiAggiuntiviField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DatoPersistente")]
    public DatoNomeValoreType[] DatiPersistenti {
        get {
            return this.datiPersistentiField;
        }
        set {
            this.datiPersistentiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("RigaErogata")]
    public RigaErogataType[] RigheErogate {
        get {
            return this.righeErogateField;
        }
        set {
            this.righeErogateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class SistemaType {
    
    private CodiceDescrizioneType aziendaField;
    
    private CodiceDescrizioneType sistemaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CodiceDescrizioneType Azienda {
        get {
            return this.aziendaField;
        }
        set {
            this.aziendaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CodiceDescrizioneType Sistema {
        get {
            return this.sistemaField;
        }
        set {
            this.sistemaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class CodiceDescrizioneType {
    
    private string codiceField;
    
    private string descrizioneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Codice {
        get {
            return this.codiceField;
        }
        set {
            this.codiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Descrizione {
        get {
            return this.descrizioneField;
        }
        set {
            this.descrizioneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class VersioneType {
    
    private System.DateTime dataSequenzaField;
    
    private bool dataSequenzaFieldSpecified;
    
    private int numeroSequenzaField;
    
    private bool numeroSequenzaFieldSpecified;
    
    /// <remarks/>
    public System.DateTime DataSequenza {
        get {
            return this.dataSequenzaField;
        }
        set {
            this.dataSequenzaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataSequenzaSpecified {
        get {
            return this.dataSequenzaFieldSpecified;
        }
        set {
            this.dataSequenzaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int NumeroSequenza {
        get {
            return this.numeroSequenzaField;
        }
        set {
            this.numeroSequenzaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumeroSequenzaSpecified {
        get {
            return this.numeroSequenzaFieldSpecified;
        }
        set {
            this.numeroSequenzaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class PrestazioneType {
    
    private string codiceField;
    
    private string descrizioneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Codice {
        get {
            return this.codiceField;
        }
        set {
            this.codiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Descrizione {
        get {
            return this.descrizioneField;
        }
        set {
            this.descrizioneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class RigaErogataType {
    
    private string idRigaOrderEntryField;
    
    private string statoOrderEntryField;
    
    private string idRigaRichiedenteField;
    
    private string idRigaEroganteField;
    
    private System.Nullable<System.DateTime> dataField;
    
    private bool dataFieldSpecified;
    
    private OperatoreType operatoreField;
    
    private PrestazioneType prestazioneField;
    
    private ConsensoType[] consensiField;
    
    private DatoNomeValoreType[] datiAggiuntiviField;
    
    private VersioneType versioneField;
    
    private TipoRigaOperazioneType tipoOperazioneField;
    
    private bool tipoOperazioneFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IdRigaOrderEntry {
        get {
            return this.idRigaOrderEntryField;
        }
        set {
            this.idRigaOrderEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string StatoOrderEntry {
        get {
            return this.statoOrderEntryField;
        }
        set {
            this.statoOrderEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IdRigaRichiedente {
        get {
            return this.idRigaRichiedenteField;
        }
        set {
            this.idRigaRichiedenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IdRigaErogante {
        get {
            return this.idRigaEroganteField;
        }
        set {
            this.idRigaEroganteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataSpecified {
        get {
            return this.dataFieldSpecified;
        }
        set {
            this.dataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperatoreType Operatore {
        get {
            return this.operatoreField;
        }
        set {
            this.operatoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PrestazioneType Prestazione {
        get {
            return this.prestazioneField;
        }
        set {
            this.prestazioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Consenso")]
    public ConsensoType[] Consensi {
        get {
            return this.consensiField;
        }
        set {
            this.consensiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DatoAggiuntivo")]
    public DatoNomeValoreType[] DatiAggiuntivi {
        get {
            return this.datiAggiuntiviField;
        }
        set {
            this.datiAggiuntiviField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public VersioneType Versione {
        get {
            return this.versioneField;
        }
        set {
            this.versioneField = value;
        }
    }
    
    /// <remarks/>
    public TipoRigaOperazioneType TipoOperazione {
        get {
            return this.tipoOperazioneField;
        }
        set {
            this.tipoOperazioneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TipoOperazioneSpecified {
        get {
            return this.tipoOperazioneFieldSpecified;
        }
        set {
            this.tipoOperazioneFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class OperatoreType {
    
    private string idField;
    
    private string cognomeField;
    
    private string nomeField;
    
    private string codiceFiscaleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cognome {
        get {
            return this.cognomeField;
        }
        set {
            this.cognomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CodiceFiscale {
        get {
            return this.codiceFiscaleField;
        }
        set {
            this.codiceFiscaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class ConsensoType {
    
    private string tipoField;
    
    private bool valoreField;
    
    private System.DateTime dataField;
    
    private bool dataFieldSpecified;
    
    private OperatoreType operatoreField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Tipo {
        get {
            return this.tipoField;
        }
        set {
            this.tipoField = value;
        }
    }
    
    /// <remarks/>
    public bool Valore {
        get {
            return this.valoreField;
        }
        set {
            this.valoreField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataSpecified {
        get {
            return this.dataFieldSpecified;
        }
        set {
            this.dataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperatoreType Operatore {
        get {
            return this.operatoreField;
        }
        set {
            this.operatoreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class DatoNomeValoreType {
    
    private string nomeField;
    
    private string tipoDatoField;
    
    private string tipoContenutoField;
    
    private string valoreDatoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TipoDato {
        get {
            return this.tipoDatoField;
        }
        set {
            this.tipoDatoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TipoContenuto {
        get {
            return this.tipoContenutoField;
        }
        set {
            this.tipoContenutoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ValoreDato {
        get {
            return this.valoreDatoField;
        }
        set {
            this.valoreDatoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public enum TipoRigaOperazioneType {
    
    /// <remarks/>
    Inserisce,
    
    /// <remarks/>
    Modifica,
    
    /// <remarks/>
    Rimuove,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.progel.it/WCF/OE/RichiedenteGenericoTypes/1.1")]
public partial class PazienteType {
    
    private string idRichiedenteField;
    
    private string idSacField;
    
    private string anagraficaCodiceField;
    
    private string anagraficaNomeField;
    
    private string codiceFiscaleField;
    
    private string cognomeField;
    
    private string nomeField;
    
    private System.Nullable<System.DateTime> dataNascitaField;
    
    private bool dataNascitaFieldSpecified;
    
    private string comuneNascitaField;
    
    private string codiceIstatComuneNascitaField;
    
    private string sessoField;
    
    private string indirizzoResidenzaField;
    
    private string comuneResidenzaField;
    
    private string codiceIstatComuneResidenzaField;
    
    private string capResidenzaField;
    
    private string nazionalitaField;
    
    private string codiceIstatNazionalitaField;
    
    private string cittadinanzaField;
    
    private string codiceIstatCittadinanzaField;
    
    private System.DateTime dataModificaField;
    
    private bool dataModificaFieldSpecified;
    
    private string tesseraSanitariaField;
    
    private string codiceUslField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IdRichiedente {
        get {
            return this.idRichiedenteField;
        }
        set {
            this.idRichiedenteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IdSac {
        get {
            return this.idSacField;
        }
        set {
            this.idSacField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AnagraficaCodice {
        get {
            return this.anagraficaCodiceField;
        }
        set {
            this.anagraficaCodiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AnagraficaNome {
        get {
            return this.anagraficaNomeField;
        }
        set {
            this.anagraficaNomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CodiceFiscale {
        get {
            return this.codiceFiscaleField;
        }
        set {
            this.codiceFiscaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cognome {
        get {
            return this.cognomeField;
        }
        set {
            this.cognomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Nome {
        get {
            return this.nomeField;
        }
        set {
            this.nomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DataNascita {
        get {
            return this.dataNascitaField;
        }
        set {
            this.dataNascitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataNascitaSpecified {
        get {
            return this.dataNascitaFieldSpecified;
        }
        set {
            this.dataNascitaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ComuneNascita {
        get {
            return this.comuneNascitaField;
        }
        set {
            this.comuneNascitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CodiceIstatComuneNascita {
        get {
            return this.codiceIstatComuneNascitaField;
        }
        set {
            this.codiceIstatComuneNascitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Sesso {
        get {
            return this.sessoField;
        }
        set {
            this.sessoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string IndirizzoResidenza {
        get {
            return this.indirizzoResidenzaField;
        }
        set {
            this.indirizzoResidenzaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ComuneResidenza {
        get {
            return this.comuneResidenzaField;
        }
        set {
            this.comuneResidenzaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CodiceIstatComuneResidenza {
        get {
            return this.codiceIstatComuneResidenzaField;
        }
        set {
            this.codiceIstatComuneResidenzaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CapResidenza {
        get {
            return this.capResidenzaField;
        }
        set {
            this.capResidenzaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Nazionalita {
        get {
            return this.nazionalitaField;
        }
        set {
            this.nazionalitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CodiceIstatNazionalita {
        get {
            return this.codiceIstatNazionalitaField;
        }
        set {
            this.codiceIstatNazionalitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cittadinanza {
        get {
            return this.cittadinanzaField;
        }
        set {
            this.cittadinanzaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CodiceIstatCittadinanza {
        get {
            return this.codiceIstatCittadinanzaField;
        }
        set {
            this.codiceIstatCittadinanzaField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DataModifica {
        get {
            return this.dataModificaField;
        }
        set {
            this.dataModificaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataModificaSpecified {
        get {
            return this.dataModificaFieldSpecified;
        }
        set {
            this.dataModificaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string TesseraSanitaria {
        get {
            return this.tesseraSanitariaField;
        }
        set {
            this.tesseraSanitariaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CodiceUsl {
        get {
            return this.codiceUslField;
        }
        set {
            this.codiceUslField = value;
        }
    }
}
