//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicodeSrl.ScciCore.SvcRicercaSAC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRicercaSAC.IScciRicercaSAC")]
    public interface IScciRicercaSAC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRicercaSAC/RicercaPazientiSAC", ReplyAction="http://tempuri.org/IScciRicercaSAC/RicercaPazientiSACResponse")]
        UnicodeSrl.Scci.DataContracts.PazienteSac[] RicercaPazientiSAC(string cognome, string nome, System.DateTime datanascita, string luogonascita, string codfiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRicercaSAC/RicercaPazientiSACByID", ReplyAction="http://tempuri.org/IScciRicercaSAC/RicercaPazientiSACByIDResponse")]
        UnicodeSrl.Scci.DataContracts.PazienteSac RicercaPazientiSACByID(string idsac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciRicercaSAC/PazienteSacDatiAggiuntiviByID", ReplyAction="http://tempuri.org/IScciRicercaSAC/PazienteSacDatiAggiuntiviByIDResponse")]
        UnicodeSrl.Scci.DataContracts.PazienteSacDatiAggiuntivi PazienteSacDatiAggiuntiviByID(string idsac);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScciRicercaSACChannel : UnicodeSrl.ScciCore.SvcRicercaSAC.IScciRicercaSAC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScciRicercaSACClient : System.ServiceModel.ClientBase<UnicodeSrl.ScciCore.SvcRicercaSAC.IScciRicercaSAC>, UnicodeSrl.ScciCore.SvcRicercaSAC.IScciRicercaSAC {
        
        public ScciRicercaSACClient() {
        }
        
        public ScciRicercaSACClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScciRicercaSACClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScciRicercaSACClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScciRicercaSACClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnicodeSrl.Scci.DataContracts.PazienteSac[] RicercaPazientiSAC(string cognome, string nome, System.DateTime datanascita, string luogonascita, string codfiscale) {
            return base.Channel.RicercaPazientiSAC(cognome, nome, datanascita, luogonascita, codfiscale);
        }
        
        public UnicodeSrl.Scci.DataContracts.PazienteSac RicercaPazientiSACByID(string idsac) {
            return base.Channel.RicercaPazientiSACByID(idsac);
        }
        
        public UnicodeSrl.Scci.DataContracts.PazienteSacDatiAggiuntivi PazienteSacDatiAggiuntiviByID(string idsac) {
            return base.Channel.PazienteSacDatiAggiuntiviByID(idsac);
        }
    }
}
