//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicodeSrl.ScciCore.SvcOrderEntry {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RigaRichiestaType", Namespace="http://schemas.progel.it/WCF/OE/WsTypes/1.2")]
    [System.SerializableAttribute()]
    public partial class RigaRichiestaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdGuidOrderEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRigaOrderEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnicodeSrl.ScciCore.SvcOrderEntry.OperazioneRigaRichiestaOrderEntryEnum OperazioneOrderEntryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRigaRichiedenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRigaEroganteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnicodeSrl.ScciCore.SvcOrderEntry.CodiceDescrizioneType OperazioneRichiedenteField;
        
        private UnicodeSrl.ScciCore.SvcOrderEntry.SistemaType SistemaEroganteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRichiestaEroganteField;
        
        private UnicodeSrl.ScciCore.SvcOrderEntry.PrestazioneType PrestazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnicodeSrl.ScciCore.SvcOrderEntry.TipoPrestazioneErogabileEnum PrestazioneTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnicodeSrl.ScciCore.SvcOrderEntry.ConsensiType ConsensiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnicodeSrl.ScciCore.SvcOrderEntry.DatiAggiuntiviType DatiAggiuntiviField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdGuidOrderEntry {
            get {
                return this.IdGuidOrderEntryField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGuidOrderEntryField, value) != true)) {
                    this.IdGuidOrderEntryField = value;
                    this.RaisePropertyChanged("IdGuidOrderEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IdRigaOrderEntry {
            get {
                return this.IdRigaOrderEntryField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRigaOrderEntryField, value) != true)) {
                    this.IdRigaOrderEntryField = value;
                    this.RaisePropertyChanged("IdRigaOrderEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnicodeSrl.ScciCore.SvcOrderEntry.OperazioneRigaRichiestaOrderEntryEnum OperazioneOrderEntry {
            get {
                return this.OperazioneOrderEntryField;
            }
            set {
                if ((this.OperazioneOrderEntryField.Equals(value) != true)) {
                    this.OperazioneOrderEntryField = value;
                    this.RaisePropertyChanged("OperazioneOrderEntry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IdRigaRichiedente {
            get {
                return this.IdRigaRichiedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRigaRichiedenteField, value) != true)) {
                    this.IdRigaRichiedenteField = value;
                    this.RaisePropertyChanged("IdRigaRichiedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IdRigaErogante {
            get {
                return this.IdRigaEroganteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRigaEroganteField, value) != true)) {
                    this.IdRigaEroganteField = value;
                    this.RaisePropertyChanged("IdRigaErogante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.CodiceDescrizioneType OperazioneRichiedente {
            get {
                return this.OperazioneRichiedenteField;
            }
            set {
                if ((object.ReferenceEquals(this.OperazioneRichiedenteField, value) != true)) {
                    this.OperazioneRichiedenteField = value;
                    this.RaisePropertyChanged("OperazioneRichiedente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.SistemaType SistemaErogante {
            get {
                return this.SistemaEroganteField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaEroganteField, value) != true)) {
                    this.SistemaEroganteField = value;
                    this.RaisePropertyChanged("SistemaErogante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string IdRichiestaErogante {
            get {
                return this.IdRichiestaEroganteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRichiestaEroganteField, value) != true)) {
                    this.IdRichiestaEroganteField = value;
                    this.RaisePropertyChanged("IdRichiestaErogante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.PrestazioneType Prestazione {
            get {
                return this.PrestazioneField;
            }
            set {
                if ((object.ReferenceEquals(this.PrestazioneField, value) != true)) {
                    this.PrestazioneField = value;
                    this.RaisePropertyChanged("Prestazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.TipoPrestazioneErogabileEnum PrestazioneTipo {
            get {
                return this.PrestazioneTipoField;
            }
            set {
                if ((this.PrestazioneTipoField.Equals(value) != true)) {
                    this.PrestazioneTipoField = value;
                    this.RaisePropertyChanged("PrestazioneTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.ConsensiType Consensi {
            get {
                return this.ConsensiField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsensiField, value) != true)) {
                    this.ConsensiField = value;
                    this.RaisePropertyChanged("Consensi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.DatiAggiuntiviType DatiAggiuntivi {
            get {
                return this.DatiAggiuntiviField;
            }
            set {
                if ((object.ReferenceEquals(this.DatiAggiuntiviField, value) != true)) {
                    this.DatiAggiuntiviField = value;
                    this.RaisePropertyChanged("DatiAggiuntivi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodiceDescrizioneType", Namespace="http://schemas.progel.it/OE/Types/1.2")]
    [System.SerializableAttribute()]
    public partial class CodiceDescrizioneType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceField, value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SistemaType", Namespace="http://schemas.progel.it/OE/Types/1.2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnicodeSrl.ScciCore.SvcOrderEntry.SistemaErogante))]
    public partial class SistemaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private UnicodeSrl.ScciCore.SvcOrderEntry.CodiceDescrizioneType AziendaField;
        
        private UnicodeSrl.ScciCore.SvcOrderEntry.CodiceDescrizioneType SistemaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.CodiceDescrizioneType Azienda {
            get {
                return this.AziendaField;
            }
            set {
                if ((object.ReferenceEquals(this.AziendaField, value) != true)) {
                    this.AziendaField = value;
                    this.RaisePropertyChanged("Azienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.CodiceDescrizioneType Sistema {
            get {
                return this.SistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.SistemaField, value) != true)) {
                    this.SistemaField = value;
                    this.RaisePropertyChanged("Sistema");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrestazioneType", Namespace="http://schemas.progel.it/OE/Types/1.2")]
    [System.SerializableAttribute()]
    public partial class PrestazioneType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        private string CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceField, value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperazioneRigaRichiestaOrderEntryEnum", Namespace="http://schemas.progel.it/OE/Types/1.2")]
    public enum OperazioneRigaRichiestaOrderEntryEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MD = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CA = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPrestazioneErogabileEnum", Namespace="http://schemas.progel.it/WCF/OE/WsTypes/1.2")]
    public enum TipoPrestazioneErogabileEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prestazione = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProfiloBlindato = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProfiloScomponibile = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProfiloUtente = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ConsensiType", Namespace="http://schemas.progel.it/OE/Types/1.2", ItemName="Consenso")]
    [System.SerializableAttribute()]
    public class ConsensiType : System.Collections.Generic.List<UnicodeSrl.ScciCore.SvcOrderEntry.ConsensoType> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DatiAggiuntiviType", Namespace="http://schemas.progel.it/WCF/OE/WsTypes/1.2", ItemName="DatoAggiuntivo")]
    [System.SerializableAttribute()]
    public class DatiAggiuntiviType : System.Collections.Generic.List<UnicodeSrl.ScciCore.SvcOrderEntry.DatoNomeValoreType> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SistemaErogante", Namespace="http://schemas.progel.it/WCF/OE/WsTypes/1.2")]
    [System.SerializableAttribute()]
    public partial class SistemaErogante : UnicodeSrl.ScciCore.SvcOrderEntry.SistemaType {
        
        private bool AccessoLetturaField;
        
        private bool AccessoInserimentoField;
        
        private bool AccessoInoltroField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool AccessoLettura {
            get {
                return this.AccessoLetturaField;
            }
            set {
                if ((this.AccessoLetturaField.Equals(value) != true)) {
                    this.AccessoLetturaField = value;
                    this.RaisePropertyChanged("AccessoLettura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool AccessoInserimento {
            get {
                return this.AccessoInserimentoField;
            }
            set {
                if ((this.AccessoInserimentoField.Equals(value) != true)) {
                    this.AccessoInserimentoField = value;
                    this.RaisePropertyChanged("AccessoInserimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool AccessoInoltro {
            get {
                return this.AccessoInoltroField;
            }
            set {
                if ((this.AccessoInoltroField.Equals(value) != true)) {
                    this.AccessoInoltroField = value;
                    this.RaisePropertyChanged("AccessoInoltro");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsensoType", Namespace="http://schemas.progel.it/OE/Types/1.2")]
    [System.SerializableAttribute()]
    public partial class ConsensoType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TipoField;
        
        private bool ValoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnicodeSrl.ScciCore.SvcOrderEntry.OperatoreType OperatoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Valore {
            get {
                return this.ValoreField;
            }
            set {
                if ((this.ValoreField.Equals(value) != true)) {
                    this.ValoreField = value;
                    this.RaisePropertyChanged("Valore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.OperatoreType Operatore {
            get {
                return this.OperatoreField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatoreField, value) != true)) {
                    this.OperatoreField = value;
                    this.RaisePropertyChanged("Operatore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperatoreType", Namespace="http://schemas.progel.it/OE/Types/1.2")]
    [System.SerializableAttribute()]
    public partial class OperatoreType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CognomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodiceFiscaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cognome {
            get {
                return this.CognomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CognomeField, value) != true)) {
                    this.CognomeField = value;
                    this.RaisePropertyChanged("Cognome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CodiceFiscale {
            get {
                return this.CodiceFiscaleField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceFiscaleField, value) != true)) {
                    this.CodiceFiscaleField = value;
                    this.RaisePropertyChanged("CodiceFiscale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatoNomeValoreType", Namespace="http://schemas.progel.it/WCF/OE/WsTypes/1.2")]
    [System.SerializableAttribute()]
    public partial class DatoNomeValoreType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        private string NomeField;
        
        private string TipoDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoContenutoField;
        
        private string ValoreDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnicodeSrl.ScciCore.SvcOrderEntry.DatoAccessorioType DatoAccessorioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TipoDato {
            get {
                return this.TipoDatoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDatoField, value) != true)) {
                    this.TipoDatoField = value;
                    this.RaisePropertyChanged("TipoDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoContenuto {
            get {
                return this.TipoContenutoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoContenutoField, value) != true)) {
                    this.TipoContenutoField = value;
                    this.RaisePropertyChanged("TipoContenuto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string ValoreDato {
            get {
                return this.ValoreDatoField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoreDatoField, value) != true)) {
                    this.ValoreDatoField = value;
                    this.RaisePropertyChanged("ValoreDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.DatoAccessorioType DatoAccessorio {
            get {
                return this.DatoAccessorioField;
            }
            set {
                if ((object.ReferenceEquals(this.DatoAccessorioField, value) != true)) {
                    this.DatoAccessorioField = value;
                    this.RaisePropertyChanged("DatoAccessorio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatoAccessorioType", Namespace="http://schemas.progel.it/WCF/OE/WsTypes/1.2")]
    [System.SerializableAttribute()]
    public partial class DatoAccessorioType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        private string EtichettaField;
        
        private UnicodeSrl.ScciCore.SvcOrderEntry.TipoDatoAccessorioEnum TipoField;
        
        private bool ObbligatorioField;
        
        private bool RipetibileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdinamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GruppoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidazioneRegexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidazioneMessaggioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Codice {
            get {
                return this.CodiceField;
            }
            set {
                if ((object.ReferenceEquals(this.CodiceField, value) != true)) {
                    this.CodiceField = value;
                    this.RaisePropertyChanged("Codice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Etichetta {
            get {
                return this.EtichettaField;
            }
            set {
                if ((object.ReferenceEquals(this.EtichettaField, value) != true)) {
                    this.EtichettaField = value;
                    this.RaisePropertyChanged("Etichetta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public UnicodeSrl.ScciCore.SvcOrderEntry.TipoDatoAccessorioEnum Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Obbligatorio {
            get {
                return this.ObbligatorioField;
            }
            set {
                if ((this.ObbligatorioField.Equals(value) != true)) {
                    this.ObbligatorioField = value;
                    this.RaisePropertyChanged("Obbligatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool Ripetibile {
            get {
                return this.RipetibileField;
            }
            set {
                if ((this.RipetibileField.Equals(value) != true)) {
                    this.RipetibileField = value;
                    this.RaisePropertyChanged("Ripetibile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Valori {
            get {
                return this.ValoriField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoriField, value) != true)) {
                    this.ValoriField = value;
                    this.RaisePropertyChanged("Valori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int Ordinamento {
            get {
                return this.OrdinamentoField;
            }
            set {
                if ((this.OrdinamentoField.Equals(value) != true)) {
                    this.OrdinamentoField = value;
                    this.RaisePropertyChanged("Ordinamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Gruppo {
            get {
                return this.GruppoField;
            }
            set {
                if ((object.ReferenceEquals(this.GruppoField, value) != true)) {
                    this.GruppoField = value;
                    this.RaisePropertyChanged("Gruppo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ValidazioneRegex {
            get {
                return this.ValidazioneRegexField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidazioneRegexField, value) != true)) {
                    this.ValidazioneRegexField = value;
                    this.RaisePropertyChanged("ValidazioneRegex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ValidazioneMessaggio {
            get {
                return this.ValidazioneMessaggioField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidazioneMessaggioField, value) != true)) {
                    this.ValidazioneMessaggioField = value;
                    this.RaisePropertyChanged("ValidazioneMessaggio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDatoAccessorioEnum", Namespace="http://schemas.progel.it/WCF/OE/WsTypes/1.2")]
    public enum TipoDatoAccessorioEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TextBox = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComboBox = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NumberBox = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FloatBox = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateBox = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTimeBox = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeBox = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ListBox = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ListMultiBox = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Titolo = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcOrderEntry.IScciOrderEntry")]
    public interface IScciOrderEntry {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetEroganti", ReplyAction="http://tempuri.org/IScciOrderEntry/GetErogantiResponse")]
        UnicodeSrl.Scci.DataContracts.OESistemaErogante[] GetEroganti(string s_user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetEroganti2", ReplyAction="http://tempuri.org/IScciOrderEntry/GetEroganti2Response")]
        UnicodeSrl.Scci.DataContracts.OESistemaErogante[] GetEroganti2(string s_user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetPrestazioni", ReplyAction="http://tempuri.org/IScciOrderEntry/GetPrestazioniResponse")]
        UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetPrestazioni(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaErogante, string codiceSistemaErogante, string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetProfili", ReplyAction="http://tempuri.org/IScciOrderEntry/GetProfiliResponse")]
        UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetProfili(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaErogante, string codiceSistemaErogante, string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetProfiliUtente", ReplyAction="http://tempuri.org/IScciOrderEntry/GetProfiliUtenteResponse")]
        UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetProfiliUtente(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaErogante, string codiceSistemaErogante, string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetPrestazioniInProfilo", ReplyAction="http://tempuri.org/IScciOrderEntry/GetPrestazioniInProfiloResponse")]
        UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetPrestazioniInProfilo(string s_user, UnicodeSrl.Scci.DataContracts.OEPrestazione prestazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CreaOrdine", ReplyAction="http://tempuri.org/IScciOrderEntry/CreaOrdineResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineTestata CreaOrdine(
                    string s_user, 
                    string s_nome, 
                    string s_cognome, 
                    string idOrdine, 
                    string nosologico, 
                    string s_listaattesa, 
                    string regime, 
                    UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, 
                    string codiceFiscale, 
                    string idPaziente, 
                    string cognome, 
                    string nome, 
                    System.DateTime dataNascita, 
                    string codiceAzienda, 
                    string codiceUnitaOperativa, 
                    string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CreaOrdineEsteso", ReplyAction="http://tempuri.org/IScciOrderEntry/CreaOrdineEstesoResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio CreaOrdineEsteso(
                    string s_user, 
                    string s_nome, 
                    string s_cognome, 
                    string idOrdine, 
                    string nosologico, 
                    string s_listaattesa, 
                    string regime, 
                    UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, 
                    string codiceFiscale, 
                    string idPaziente, 
                    string cognome, 
                    string nome, 
                    System.DateTime dataNascita, 
                    string codiceAzienda, 
                    string codiceUnitaOperativa, 
                    string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/SalvaOrdine", ReplyAction="http://tempuri.org/IScciOrderEntry/SalvaOrdineResponse")]
        bool SalvaOrdine(string s_user, string s_nome, string s_cognome, string idOrdine, string nosologico, string s_listaattesa, string regime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, System.Nullable<System.DateTime> dataPrenotazione, string codiceAzienda, string codiceUnitaOperativa, string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/SalvaOrdineEsteso", ReplyAction="http://tempuri.org/IScciOrderEntry/SalvaOrdineEstesoResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio SalvaOrdineEsteso(string s_user, string s_nome, string s_cognome, string idOrdine, string nosologico, string s_listaattesa, string regime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, System.Nullable<System.DateTime> dataPrenotazione, string codiceAzienda, string codiceUnitaOperativa, string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/getLastException", ReplyAction="http://tempuri.org/IScciOrderEntry/getLastExceptionResponse")]
        string getLastException();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CreaOrdineCopia", ReplyAction="http://tempuri.org/IScciOrderEntry/CreaOrdineCopiaResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineTestata CreaOrdineCopia(string s_user, string idOEorigine, string idOrdineNuovo, string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CreaOrdineCopia2", ReplyAction="http://tempuri.org/IScciOrderEntry/CreaOrdineCopia2Response")]
        UnicodeSrl.Scci.DataContracts.OEOrdineTestata CreaOrdineCopia2(string s_user, string s_nome, string s_cognome, string idOEorigine, string idOrdineNuovo, string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CreaOrdineCopia3", ReplyAction="http://tempuri.org/IScciOrderEntry/CreaOrdineCopia3Response")]
        UnicodeSrl.Scci.DataContracts.OEOrdineTestata CreaOrdineCopia3(string s_user, string idOEorigine, string idOrdineNuovo, string s_nosologiconuovo, string s_aziendauo, string s_codiceuo, bool b_copiadatiaccessori, string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CancellaOrdine", ReplyAction="http://tempuri.org/IScciOrderEntry/CancellaOrdineResponse")]
        bool CancellaOrdine(string s_user, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetOrdineTestata", ReplyAction="http://tempuri.org/IScciOrderEntry/GetOrdineTestataResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineTestata GetOrdineTestata(string s_user, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetOrdineDettaglioPerTestata", ReplyAction="http://tempuri.org/IScciOrderEntry/GetOrdineDettaglioPerTestataResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio GetOrdineDettaglioPerTestata(string s_user, UnicodeSrl.Scci.DataContracts.OEOrdineTestata o_testata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetOrdineDettaglio", ReplyAction="http://tempuri.org/IScciOrderEntry/GetOrdineDettaglioResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio GetOrdineDettaglio(string s_user, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CercaOrdiniPerPaziente", ReplyAction="http://tempuri.org/IScciOrderEntry/CercaOrdiniPerPazienteResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineTestata[] CercaOrdiniPerPaziente(string s_user, System.DateTime dataInizio, System.DateTime dataFine, string idSacPaziente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CercaOrdiniPerNosologico", ReplyAction="http://tempuri.org/IScciOrderEntry/CercaOrdiniPerNosologicoResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineTestata[] CercaOrdiniPerNosologico(string s_user, System.DateTime dataInizio, System.DateTime dataFine, string nosologico, string s_listaattesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/InoltraOrdine", ReplyAction="http://tempuri.org/IScciOrderEntry/InoltraOrdineResponse")]
        bool InoltraOrdine(string s_user, string s_nome, string s_cognome, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/InoltraOrdineDaWorkstation", ReplyAction="http://tempuri.org/IScciOrderEntry/InoltraOrdineDaWorkstationResponse")]
        bool InoltraOrdineDaWorkstation(string s_user, string s_nome, string s_cognome, string idOE, string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/InoltraOrdineDaWorkstationEsteso", ReplyAction="http://tempuri.org/IScciOrderEntry/InoltraOrdineDaWorkstationEstesoResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio InoltraOrdineDaWorkstationEsteso(string s_user, string s_nome, string s_cognome, string idOE, string s_workstation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetGruppiPreferenziali", ReplyAction="http://tempuri.org/IScciOrderEntry/GetGruppiPreferenzialiResponse")]
        UnicodeSrl.Scci.DataContracts.OEGruppoPrestazione[] GetGruppiPreferenziali(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaRichiedente, string codiceSistemaRichiedente, string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetPrestazioniInGruppo", ReplyAction="http://tempuri.org/IScciOrderEntry/GetPrestazioniInGruppoResponse")]
        UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetPrestazioniInGruppo(string s_user, string idgruppo, string filtroprestazioni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetPrestazioniInGruppo2", ReplyAction="http://tempuri.org/IScciOrderEntry/GetPrestazioniInGruppo2Response")]
        UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetPrestazioniInGruppo2(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaRichiedente, string codiceSistemaRichiedente, string idgruppo, string filtroprestazioni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CercaOrdiniPerStatoPianificato", ReplyAction="http://tempuri.org/IScciOrderEntry/CercaOrdiniPerStatoPianificatoResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineTestata[] CercaOrdiniPerStatoPianificato(string s_user, System.DateTime dataInizio, System.DateTime dataFine, string CodAziendaSistemaErogante, string CodSistemaErogante, System.Collections.Generic.KeyValuePair<string, string>[] unitaoperative, string nosologico, string cognome, string nome, System.Nullable<System.DateTime> datanascita, int maxrecord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/InserisciPrestazioni", ReplyAction="http://tempuri.org/IScciOrderEntry/InserisciPrestazioniResponse")]
        bool InserisciPrestazioni(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione[] prestazioni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/InserisciPrestazione", ReplyAction="http://tempuri.org/IScciOrderEntry/InserisciPrestazioneResponse")]
        bool InserisciPrestazione(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione prestazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CancellaPrestazioni", ReplyAction="http://tempuri.org/IScciOrderEntry/CancellaPrestazioniResponse")]
        bool CancellaPrestazioni(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione[] prestazioni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CancellaPrestazione", ReplyAction="http://tempuri.org/IScciOrderEntry/CancellaPrestazioneResponse")]
        bool CancellaPrestazione(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione prestazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/EsplodiProfilo", ReplyAction="http://tempuri.org/IScciOrderEntry/EsplodiProfiloResponse")]
        bool EsplodiProfilo(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione prestazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/PrestazioniRecenti", ReplyAction="http://tempuri.org/IScciOrderEntry/PrestazioniRecentiResponse")]
        UnicodeSrl.Scci.DataContracts.OEPrestazione[] PrestazioniRecenti(string s_user, string regime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codAzienda, string codUnita, string conAziendaRichiedente, string codSistRichiedente, string codAziendaSistErogante, string codSistErogante, string idSacPaziente, string filtroCodiceDescrizione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/TranslatePrioritaDescFromOE", ReplyAction="http://tempuri.org/IScciOrderEntry/TranslatePrioritaDescFromOEResponse")]
        string TranslatePrioritaDescFromOE(UnicodeSrl.Scci.Enums.OEPrioritaOrdine oepri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/CreaProfilo", ReplyAction="http://tempuri.org/IScciOrderEntry/CreaProfiloResponse")]
        bool CreaProfilo(string s_user, string descrizione, UnicodeSrl.Scci.DataContracts.OEPrestazione[] prestazioni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/EliminaProfilo", ReplyAction="http://tempuri.org/IScciOrderEntry/EliminaProfiloResponse")]
        bool EliminaProfilo(string s_user, string CodiceProfilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessorNecessari", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessorNecessariResponse")]
        UnicodeSrl.Scci.DataContracts.OEDatiAccessoriDescrittore[] GetDatiAccessorNecessari(string s_user, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriOld", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriOldResponse")]
        UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriOld(string s_user, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessori", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriResponse")]
        UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessori(string s_user, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/FillDatiAccessori", ReplyAction="http://tempuri.org/IScciOrderEntry/FillDatiAccessoriResponse")]
        bool FillDatiAccessori(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] datiAggiuntivi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/FillDatiAccessoriEsteso", ReplyAction="http://tempuri.org/IScciOrderEntry/FillDatiAccessoriEstesoResponse")]
        UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio FillDatiAccessoriEsteso(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] datiAggiuntivi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriTestata", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriTestataResponse")]
        UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriTestata(string s_user, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriPrestazione", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriPrestazioneResponse")]
        UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriPrestazione(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione o_prestazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriErogante", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriEroganteResponse")]
        UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriErogante(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OESistemaErogante o_erogante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriErogante2", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriErogante2Response")]
        UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriErogante2(string s_user, string idOE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriEroganteTestata", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriEroganteTestataResponse")]
        UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriEroganteTestata(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OESistemaErogante o_erogante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriErogantePrestazione", ReplyAction="http://tempuri.org/IScciOrderEntry/GetDatiAccessoriErogantePrestazioneResponse")]
        UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriErogantePrestazione(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione o_prestazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciOrderEntry/ComparePrestazione", ReplyAction="http://tempuri.org/IScciOrderEntry/ComparePrestazioneResponse")]
        bool ComparePrestazione(UnicodeSrl.Scci.DataContracts.OEPrestazione o_prestazione, UnicodeSrl.ScciCore.SvcOrderEntry.RigaRichiestaType o_prestazione_oe);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScciOrderEntryChannel : UnicodeSrl.ScciCore.SvcOrderEntry.IScciOrderEntry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScciOrderEntryClient : System.ServiceModel.ClientBase<UnicodeSrl.ScciCore.SvcOrderEntry.IScciOrderEntry>, UnicodeSrl.ScciCore.SvcOrderEntry.IScciOrderEntry {
        
        public ScciOrderEntryClient() {
        }
        
        public ScciOrderEntryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScciOrderEntryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScciOrderEntryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScciOrderEntryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnicodeSrl.Scci.DataContracts.OESistemaErogante[] GetEroganti(string s_user) {
            return base.Channel.GetEroganti(s_user);
        }
        
        public UnicodeSrl.Scci.DataContracts.OESistemaErogante[] GetEroganti2(string s_user) {
            return base.Channel.GetEroganti2(s_user);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetPrestazioni(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaErogante, string codiceSistemaErogante, string filtro) {
            return base.Channel.GetPrestazioni(s_user, codiceregime, priorita, codiceAzienda, codiceUnita, codiceAziendaSistemaErogante, codiceSistemaErogante, filtro);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetProfili(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaErogante, string codiceSistemaErogante, string filtro) {
            return base.Channel.GetProfili(s_user, codiceregime, priorita, codiceAzienda, codiceUnita, codiceAziendaSistemaErogante, codiceSistemaErogante, filtro);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetProfiliUtente(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaErogante, string codiceSistemaErogante, string filtro) {
            return base.Channel.GetProfiliUtente(s_user, codiceregime, priorita, codiceAzienda, codiceUnita, codiceAziendaSistemaErogante, codiceSistemaErogante, filtro);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetPrestazioniInProfilo(string s_user, UnicodeSrl.Scci.DataContracts.OEPrestazione prestazione) {
            return base.Channel.GetPrestazioniInProfilo(s_user, prestazione);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineTestata CreaOrdine(
                    string s_user, 
                    string s_nome, 
                    string s_cognome, 
                    string idOrdine, 
                    string nosologico, 
                    string s_listaattesa, 
                    string regime, 
                    UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, 
                    string codiceFiscale, 
                    string idPaziente, 
                    string cognome, 
                    string nome, 
                    System.DateTime dataNascita, 
                    string codiceAzienda, 
                    string codiceUnitaOperativa, 
                    string s_workstation) {
            return base.Channel.CreaOrdine(s_user, s_nome, s_cognome, idOrdine, nosologico, s_listaattesa, regime, priorita, codiceFiscale, idPaziente, cognome, nome, dataNascita, codiceAzienda, codiceUnitaOperativa, s_workstation);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio CreaOrdineEsteso(
                    string s_user, 
                    string s_nome, 
                    string s_cognome, 
                    string idOrdine, 
                    string nosologico, 
                    string s_listaattesa, 
                    string regime, 
                    UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, 
                    string codiceFiscale, 
                    string idPaziente, 
                    string cognome, 
                    string nome, 
                    System.DateTime dataNascita, 
                    string codiceAzienda, 
                    string codiceUnitaOperativa, 
                    string s_workstation) {
            return base.Channel.CreaOrdineEsteso(s_user, s_nome, s_cognome, idOrdine, nosologico, s_listaattesa, regime, priorita, codiceFiscale, idPaziente, cognome, nome, dataNascita, codiceAzienda, codiceUnitaOperativa, s_workstation);
        }
        
        public bool SalvaOrdine(string s_user, string s_nome, string s_cognome, string idOrdine, string nosologico, string s_listaattesa, string regime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, System.Nullable<System.DateTime> dataPrenotazione, string codiceAzienda, string codiceUnitaOperativa, string s_workstation) {
            return base.Channel.SalvaOrdine(s_user, s_nome, s_cognome, idOrdine, nosologico, s_listaattesa, regime, priorita, dataPrenotazione, codiceAzienda, codiceUnitaOperativa, s_workstation);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio SalvaOrdineEsteso(string s_user, string s_nome, string s_cognome, string idOrdine, string nosologico, string s_listaattesa, string regime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, System.Nullable<System.DateTime> dataPrenotazione, string codiceAzienda, string codiceUnitaOperativa, string s_workstation) {
            return base.Channel.SalvaOrdineEsteso(s_user, s_nome, s_cognome, idOrdine, nosologico, s_listaattesa, regime, priorita, dataPrenotazione, codiceAzienda, codiceUnitaOperativa, s_workstation);
        }
        
        public string getLastException() {
            return base.Channel.getLastException();
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineTestata CreaOrdineCopia(string s_user, string idOEorigine, string idOrdineNuovo, string s_workstation) {
            return base.Channel.CreaOrdineCopia(s_user, idOEorigine, idOrdineNuovo, s_workstation);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineTestata CreaOrdineCopia2(string s_user, string s_nome, string s_cognome, string idOEorigine, string idOrdineNuovo, string s_workstation) {
            return base.Channel.CreaOrdineCopia2(s_user, s_nome, s_cognome, idOEorigine, idOrdineNuovo, s_workstation);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineTestata CreaOrdineCopia3(string s_user, string idOEorigine, string idOrdineNuovo, string s_nosologiconuovo, string s_aziendauo, string s_codiceuo, bool b_copiadatiaccessori, string s_workstation) {
            return base.Channel.CreaOrdineCopia3(s_user, idOEorigine, idOrdineNuovo, s_nosologiconuovo, s_aziendauo, s_codiceuo, b_copiadatiaccessori, s_workstation);
        }
        
        public bool CancellaOrdine(string s_user, string idOE) {
            return base.Channel.CancellaOrdine(s_user, idOE);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineTestata GetOrdineTestata(string s_user, string idOE) {
            return base.Channel.GetOrdineTestata(s_user, idOE);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio GetOrdineDettaglioPerTestata(string s_user, UnicodeSrl.Scci.DataContracts.OEOrdineTestata o_testata) {
            return base.Channel.GetOrdineDettaglioPerTestata(s_user, o_testata);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio GetOrdineDettaglio(string s_user, string idOE) {
            return base.Channel.GetOrdineDettaglio(s_user, idOE);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineTestata[] CercaOrdiniPerPaziente(string s_user, System.DateTime dataInizio, System.DateTime dataFine, string idSacPaziente) {
            return base.Channel.CercaOrdiniPerPaziente(s_user, dataInizio, dataFine, idSacPaziente);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineTestata[] CercaOrdiniPerNosologico(string s_user, System.DateTime dataInizio, System.DateTime dataFine, string nosologico, string s_listaattesa) {
            return base.Channel.CercaOrdiniPerNosologico(s_user, dataInizio, dataFine, nosologico, s_listaattesa);
        }
        
        public bool InoltraOrdine(string s_user, string s_nome, string s_cognome, string idOE) {
            return base.Channel.InoltraOrdine(s_user, s_nome, s_cognome, idOE);
        }
        
        public bool InoltraOrdineDaWorkstation(string s_user, string s_nome, string s_cognome, string idOE, string s_workstation) {
            return base.Channel.InoltraOrdineDaWorkstation(s_user, s_nome, s_cognome, idOE, s_workstation);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio InoltraOrdineDaWorkstationEsteso(string s_user, string s_nome, string s_cognome, string idOE, string s_workstation) {
            return base.Channel.InoltraOrdineDaWorkstationEsteso(s_user, s_nome, s_cognome, idOE, s_workstation);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEGruppoPrestazione[] GetGruppiPreferenziali(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaRichiedente, string codiceSistemaRichiedente, string filtro) {
            return base.Channel.GetGruppiPreferenziali(s_user, codiceregime, priorita, codiceAzienda, codiceUnita, codiceAziendaSistemaRichiedente, codiceSistemaRichiedente, filtro);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetPrestazioniInGruppo(string s_user, string idgruppo, string filtroprestazioni) {
            return base.Channel.GetPrestazioniInGruppo(s_user, idgruppo, filtroprestazioni);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEPrestazione[] GetPrestazioniInGruppo2(string s_user, string codiceregime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codiceAzienda, string codiceUnita, string codiceAziendaSistemaRichiedente, string codiceSistemaRichiedente, string idgruppo, string filtroprestazioni) {
            return base.Channel.GetPrestazioniInGruppo2(s_user, codiceregime, priorita, codiceAzienda, codiceUnita, codiceAziendaSistemaRichiedente, codiceSistemaRichiedente, idgruppo, filtroprestazioni);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineTestata[] CercaOrdiniPerStatoPianificato(string s_user, System.DateTime dataInizio, System.DateTime dataFine, string CodAziendaSistemaErogante, string CodSistemaErogante, System.Collections.Generic.KeyValuePair<string, string>[] unitaoperative, string nosologico, string cognome, string nome, System.Nullable<System.DateTime> datanascita, int maxrecord) {
            return base.Channel.CercaOrdiniPerStatoPianificato(s_user, dataInizio, dataFine, CodAziendaSistemaErogante, CodSistemaErogante, unitaoperative, nosologico, cognome, nome, datanascita, maxrecord);
        }
        
        public bool InserisciPrestazioni(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione[] prestazioni) {
            return base.Channel.InserisciPrestazioni(s_user, idOE, prestazioni);
        }
        
        public bool InserisciPrestazione(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione prestazione) {
            return base.Channel.InserisciPrestazione(s_user, idOE, prestazione);
        }
        
        public bool CancellaPrestazioni(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione[] prestazioni) {
            return base.Channel.CancellaPrestazioni(s_user, idOE, prestazioni);
        }
        
        public bool CancellaPrestazione(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione prestazione) {
            return base.Channel.CancellaPrestazione(s_user, idOE, prestazione);
        }
        
        public bool EsplodiProfilo(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione prestazione) {
            return base.Channel.EsplodiProfilo(s_user, idOE, prestazione);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEPrestazione[] PrestazioniRecenti(string s_user, string regime, UnicodeSrl.Scci.Enums.OEPrioritaOrdine priorita, string codAzienda, string codUnita, string conAziendaRichiedente, string codSistRichiedente, string codAziendaSistErogante, string codSistErogante, string idSacPaziente, string filtroCodiceDescrizione) {
            return base.Channel.PrestazioniRecenti(s_user, regime, priorita, codAzienda, codUnita, conAziendaRichiedente, codSistRichiedente, codAziendaSistErogante, codSistErogante, idSacPaziente, filtroCodiceDescrizione);
        }
        
        public string TranslatePrioritaDescFromOE(UnicodeSrl.Scci.Enums.OEPrioritaOrdine oepri) {
            return base.Channel.TranslatePrioritaDescFromOE(oepri);
        }
        
        public bool CreaProfilo(string s_user, string descrizione, UnicodeSrl.Scci.DataContracts.OEPrestazione[] prestazioni) {
            return base.Channel.CreaProfilo(s_user, descrizione, prestazioni);
        }
        
        public bool EliminaProfilo(string s_user, string CodiceProfilo) {
            return base.Channel.EliminaProfilo(s_user, CodiceProfilo);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatiAccessoriDescrittore[] GetDatiAccessorNecessari(string s_user, string idOE) {
            return base.Channel.GetDatiAccessorNecessari(s_user, idOE);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriOld(string s_user, string idOE) {
            return base.Channel.GetDatiAccessoriOld(s_user, idOE);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessori(string s_user, string idOE) {
            return base.Channel.GetDatiAccessori(s_user, idOE);
        }
        
        public bool FillDatiAccessori(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] datiAggiuntivi) {
            return base.Channel.FillDatiAccessori(s_user, idOE, datiAggiuntivi);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEOrdineDettaglio FillDatiAccessoriEsteso(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] datiAggiuntivi) {
            return base.Channel.FillDatiAccessoriEsteso(s_user, idOE, datiAggiuntivi);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriTestata(string s_user, string idOE) {
            return base.Channel.GetDatiAccessoriTestata(s_user, idOE);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriPrestazione(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione o_prestazione) {
            return base.Channel.GetDatiAccessoriPrestazione(s_user, idOE, o_prestazione);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriErogante(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OESistemaErogante o_erogante) {
            return base.Channel.GetDatiAccessoriErogante(s_user, idOE, o_erogante);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriErogante2(string s_user, string idOE) {
            return base.Channel.GetDatiAccessoriErogante2(s_user, idOE);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriEroganteTestata(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OESistemaErogante o_erogante) {
            return base.Channel.GetDatiAccessoriEroganteTestata(s_user, idOE, o_erogante);
        }
        
        public UnicodeSrl.Scci.DataContracts.OEDatoAccessorio[] GetDatiAccessoriErogantePrestazione(string s_user, string idOE, UnicodeSrl.Scci.DataContracts.OEPrestazione o_prestazione) {
            return base.Channel.GetDatiAccessoriErogantePrestazione(s_user, idOE, o_prestazione);
        }
        
        public bool ComparePrestazione(UnicodeSrl.Scci.DataContracts.OEPrestazione o_prestazione, UnicodeSrl.ScciCore.SvcOrderEntry.RigaRichiestaType o_prestazione_oe) {
            return base.Channel.ComparePrestazione(o_prestazione, o_prestazione_oe);
        }
    }
}
