//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicodeSrl.ScciCore.SvcPrescrizioni {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcPrescrizioni.IScciPrescrizioni")]
    public interface IScciPrescrizioni {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciPrescrizioni/GeneraTaskDaPrescrizione", ReplyAction="http://tempuri.org/IScciPrescrizioni/GeneraTaskDaPrescrizioneResponse")]
        bool GeneraTaskDaPrescrizione(string connectionString, string idPrescrizione, string idPrescrizionetempi, UnicodeSrl.Scci.Enums.EnumCodSistema sistema, string codtipotaskinfermieristico, UnicodeSrl.Scci.DataContracts.ScciAmbiente amb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScciPrescrizioni/Test", ReplyAction="http://tempuri.org/IScciPrescrizioni/TestResponse")]
        string Test(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScciPrescrizioniChannel : UnicodeSrl.ScciCore.SvcPrescrizioni.IScciPrescrizioni, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScciPrescrizioniClient : System.ServiceModel.ClientBase<UnicodeSrl.ScciCore.SvcPrescrizioni.IScciPrescrizioni>, UnicodeSrl.ScciCore.SvcPrescrizioni.IScciPrescrizioni {
        
        public ScciPrescrizioniClient() {
        }
        
        public ScciPrescrizioniClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScciPrescrizioniClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScciPrescrizioniClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScciPrescrizioniClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GeneraTaskDaPrescrizione(string connectionString, string idPrescrizione, string idPrescrizionetempi, UnicodeSrl.Scci.Enums.EnumCodSistema sistema, string codtipotaskinfermieristico, UnicodeSrl.Scci.DataContracts.ScciAmbiente amb) {
            return base.Channel.GeneraTaskDaPrescrizione(connectionString, idPrescrizione, idPrescrizionetempi, sistema, codtipotaskinfermieristico, amb);
        }
        
        public string Test(int value) {
            return base.Channel.Test(value);
        }
    }
}
