
namespace UnicodeSrl.ScciManagement.UserControls
{
    partial class ucAllineaADT
    {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

                                        private void InitializeComponent()
        {
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance68 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance65 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance66 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance67 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance69 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance82 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance70 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance71 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance72 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance73 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance74 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance75 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance76 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance77 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance78 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance79 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance80 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance81 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance95 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance83 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance84 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance85 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance86 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance87 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance88 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance89 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance90 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance91 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance92 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance93 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance94 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance96 = new Infragistics.Win.Appearance();
            this.tlpRicerca = new System.Windows.Forms.TableLayoutPanel();
            this.ubCorreggi = new Infragistics.Win.Misc.UltraButton();
            this.ubSimula = new Infragistics.Win.Misc.UltraButton();
            this.lblPaziente = new System.Windows.Forms.Label();
            this.uteListaAttesa = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblListaAttesa = new System.Windows.Forms.Label();
            this.ubCheck = new Infragistics.Win.Misc.UltraButton();
            this.lblNosologico = new System.Windows.Forms.Label();
            this.uteNosologico = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.lblIDEpisodio = new System.Windows.Forms.Label();
            this.uteIDEpisodio = new Infragistics.Win.UltraWinEditors.UltraTextEditor();
            this.ugEpisodi = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.ubRicerca = new Infragistics.Win.Misc.UltraButton();
            this.ugEpisodioMatilde = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.ugTrasferimentiMatilde = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.ugbRicerca = new Infragistics.Win.Misc.UltraGroupBox();
            this.UltraSplitterRicerca = new Infragistics.Win.Misc.UltraSplitter();
            this.ugbDati = new Infragistics.Win.Misc.UltraGroupBox();
            this.UltraPanelDX = new Infragistics.Win.Misc.UltraPanel();
            this.ugTrasferimentiDWH = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.ultraSplitter1 = new Infragistics.Win.Misc.UltraSplitter();
            this.ugEpisodioDWH = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.UltraSplitterDati = new Infragistics.Win.Misc.UltraSplitter();
            this.UltraPanelSX = new Infragistics.Win.Misc.UltraPanel();
            this.ultraSplitter4 = new Infragistics.Win.Misc.UltraSplitter();
            this.UltraSplitterCorrezione = new Infragistics.Win.Misc.UltraSplitter();
            this.ugbCorrezione = new Infragistics.Win.Misc.UltraGroupBox();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.ugCorrezione = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.ugbSimulazione = new Infragistics.Win.Misc.UltraGroupBox();
            this.tlpSimulazione = new System.Windows.Forms.TableLayoutPanel();
            this.ugSimulazione = new Infragistics.Win.UltraWinGrid.UltraGrid();
            this.UltraSplitterSimulazione = new Infragistics.Win.Misc.UltraSplitter();
            this.tlpRicerca.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteListaAttesa)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteNosologico)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteIDEpisodio)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugEpisodi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugEpisodioMatilde)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugTrasferimentiMatilde)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugbRicerca)).BeginInit();
            this.ugbRicerca.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugbDati)).BeginInit();
            this.ugbDati.SuspendLayout();
            this.UltraPanelDX.ClientArea.SuspendLayout();
            this.UltraPanelDX.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugTrasferimentiDWH)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugEpisodioDWH)).BeginInit();
            this.UltraPanelSX.ClientArea.SuspendLayout();
            this.UltraPanelSX.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugbCorrezione)).BeginInit();
            this.ugbCorrezione.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugCorrezione)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugbSimulazione)).BeginInit();
            this.ugbSimulazione.SuspendLayout();
            this.tlpSimulazione.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ugSimulazione)).BeginInit();
            this.SuspendLayout();
                                                this.tlpRicerca.BackColor = System.Drawing.Color.Transparent;
            this.tlpRicerca.ColumnCount = 9;
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 10F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 60F));
            this.tlpRicerca.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 64F));
            this.tlpRicerca.Controls.Add(this.ubCorreggi, 8, 0);
            this.tlpRicerca.Controls.Add(this.ubSimula, 7, 0);
            this.tlpRicerca.Controls.Add(this.lblPaziente, 0, 1);
            this.tlpRicerca.Controls.Add(this.uteListaAttesa, 4, 1);
            this.tlpRicerca.Controls.Add(this.lblListaAttesa, 3, 1);
            this.tlpRicerca.Controls.Add(this.ubCheck, 6, 0);
            this.tlpRicerca.Controls.Add(this.lblNosologico, 3, 0);
            this.tlpRicerca.Controls.Add(this.uteNosologico, 4, 0);
            this.tlpRicerca.Controls.Add(this.lblIDEpisodio, 0, 0);
            this.tlpRicerca.Controls.Add(this.uteIDEpisodio, 1, 0);
            this.tlpRicerca.Controls.Add(this.ugEpisodi, 0, 2);
            this.tlpRicerca.Controls.Add(this.ubRicerca, 5, 0);
            this.tlpRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpRicerca.Location = new System.Drawing.Point(3, 17);
            this.tlpRicerca.Name = "tlpRicerca";
            this.tlpRicerca.RowCount = 3;
            this.tlpRicerca.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tlpRicerca.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.tlpRicerca.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpRicerca.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tlpRicerca.Size = new System.Drawing.Size(1018, 160);
            this.tlpRicerca.TabIndex = 0;
                                                this.ubCorreggi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCorreggi.Location = new System.Drawing.Point(955, 3);
            this.ubCorreggi.Name = "ubCorreggi";
            this.tlpRicerca.SetRowSpan(this.ubCorreggi, 2);
            this.ubCorreggi.Size = new System.Drawing.Size(60, 54);
            this.ubCorreggi.TabIndex = 10;
            this.ubCorreggi.Text = "Correggi";
            this.ubCorreggi.Click += new System.EventHandler(this.ubCorreggi_Click);
                                                this.ubSimula.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubSimula.Location = new System.Drawing.Point(895, 3);
            this.ubSimula.Name = "ubSimula";
            this.tlpRicerca.SetRowSpan(this.ubSimula, 2);
            this.ubSimula.Size = new System.Drawing.Size(54, 54);
            this.ubSimula.TabIndex = 9;
            this.ubSimula.Text = "Simula";
            this.ubSimula.Click += new System.EventHandler(this.ubSimula_Click);
                                                this.tlpRicerca.SetColumnSpan(this.lblPaziente, 3);
            this.lblPaziente.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPaziente.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPaziente.Location = new System.Drawing.Point(3, 30);
            this.lblPaziente.Name = "lblPaziente";
            this.lblPaziente.Size = new System.Drawing.Size(385, 30);
            this.lblPaziente.TabIndex = 8;
            this.lblPaziente.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.uteListaAttesa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteListaAttesa.Location = new System.Drawing.Point(546, 33);
            this.uteListaAttesa.Name = "uteListaAttesa";
            this.uteListaAttesa.Size = new System.Drawing.Size(223, 22);
            this.uteListaAttesa.TabIndex = 2;
            this.uteListaAttesa.Tag = "I14038886";
                                                this.lblListaAttesa.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblListaAttesa.Location = new System.Drawing.Point(394, 30);
            this.lblListaAttesa.Name = "lblListaAttesa";
            this.lblListaAttesa.Size = new System.Drawing.Size(146, 30);
            this.lblListaAttesa.TabIndex = 7;
            this.lblListaAttesa.Text = "Lista Attesa";
            this.lblListaAttesa.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
                                                this.ubCheck.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubCheck.Location = new System.Drawing.Point(835, 3);
            this.ubCheck.Name = "ubCheck";
            this.tlpRicerca.SetRowSpan(this.ubCheck, 2);
            this.ubCheck.Size = new System.Drawing.Size(54, 54);
            this.ubCheck.TabIndex = 4;
            this.ubCheck.Text = "Check";
            this.ubCheck.Click += new System.EventHandler(this.ubCheck_Click);
                                                this.lblNosologico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblNosologico.Location = new System.Drawing.Point(394, 0);
            this.lblNosologico.Name = "lblNosologico";
            this.lblNosologico.Size = new System.Drawing.Size(146, 30);
            this.lblNosologico.TabIndex = 3;
            this.lblNosologico.Text = "Nosologico";
            this.lblNosologico.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
                                                this.uteNosologico.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteNosologico.Location = new System.Drawing.Point(546, 3);
            this.uteNosologico.Name = "uteNosologico";
            this.uteNosologico.Size = new System.Drawing.Size(223, 22);
            this.uteNosologico.TabIndex = 1;
            this.uteNosologico.Tag = "I14038886";
                                                this.lblIDEpisodio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblIDEpisodio.Location = new System.Drawing.Point(3, 0);
            this.lblIDEpisodio.Name = "lblIDEpisodio";
            this.lblIDEpisodio.Size = new System.Drawing.Size(146, 30);
            this.lblIDEpisodio.TabIndex = 0;
            this.lblIDEpisodio.Text = "IDEpisodio";
            this.lblIDEpisodio.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
                                                this.uteIDEpisodio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.uteIDEpisodio.Location = new System.Drawing.Point(155, 3);
            this.uteIDEpisodio.Name = "uteIDEpisodio";
            this.uteIDEpisodio.Size = new System.Drawing.Size(223, 22);
            this.uteIDEpisodio.TabIndex = 0;
            this.uteIDEpisodio.Tag = "e178c654-85a3-4ab6-baca-f5fd8575959a";
                                                this.tlpRicerca.SetColumnSpan(this.ugEpisodi, 9);
            appearance1.BackColor = System.Drawing.SystemColors.Window;
            appearance1.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugEpisodi.DisplayLayout.Appearance = appearance1;
            this.ugEpisodi.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugEpisodi.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance2.BorderColor = System.Drawing.SystemColors.Window;
            this.ugEpisodi.DisplayLayout.GroupByBox.Appearance = appearance2;
            appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugEpisodi.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
            this.ugEpisodi.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance4.BackColor2 = System.Drawing.SystemColors.Control;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugEpisodi.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
            this.ugEpisodi.DisplayLayout.MaxColScrollRegions = 1;
            this.ugEpisodi.DisplayLayout.MaxRowScrollRegions = 1;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugEpisodi.DisplayLayout.Override.ActiveCellAppearance = appearance5;
            appearance6.BackColor = System.Drawing.SystemColors.Highlight;
            appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugEpisodi.DisplayLayout.Override.ActiveRowAppearance = appearance6;
            this.ugEpisodi.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugEpisodi.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            this.ugEpisodi.DisplayLayout.Override.CardAreaAppearance = appearance7;
            appearance8.BorderColor = System.Drawing.Color.Silver;
            appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugEpisodi.DisplayLayout.Override.CellAppearance = appearance8;
            this.ugEpisodi.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.ugEpisodi.DisplayLayout.Override.CellPadding = 0;
            appearance9.BackColor = System.Drawing.SystemColors.Control;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.ugEpisodi.DisplayLayout.Override.GroupByRowAppearance = appearance9;
            appearance10.TextHAlignAsString = "Left";
            this.ugEpisodi.DisplayLayout.Override.HeaderAppearance = appearance10;
            this.ugEpisodi.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.ugEpisodi.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.BorderColor = System.Drawing.Color.Silver;
            this.ugEpisodi.DisplayLayout.Override.RowAppearance = appearance11;
            this.ugEpisodi.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance12.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugEpisodi.DisplayLayout.Override.TemplateAddRowAppearance = appearance12;
            this.ugEpisodi.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugEpisodi.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugEpisodi.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugEpisodi.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ugEpisodi.Location = new System.Drawing.Point(3, 63);
            this.ugEpisodi.Name = "ugEpisodi";
            this.ugEpisodi.Size = new System.Drawing.Size(1012, 94);
            this.ugEpisodi.TabIndex = 2;
            this.ugEpisodi.Text = "ultraGrid1";
            this.ugEpisodi.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugEpisodi_InitializeLayout);
            this.ugEpisodi.AfterRowActivate += new System.EventHandler(this.ugEpisodi_AfterRowActivate);
                                                this.ubRicerca.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ubRicerca.Location = new System.Drawing.Point(775, 3);
            this.ubRicerca.Name = "ubRicerca";
            this.tlpRicerca.SetRowSpan(this.ubRicerca, 2);
            this.ubRicerca.Size = new System.Drawing.Size(54, 54);
            this.ubRicerca.TabIndex = 3;
            this.ubRicerca.Text = "Ricerca";
            this.ubRicerca.Click += new System.EventHandler(this.ubRicerca_Click);
                                                appearance13.BackColor = System.Drawing.SystemColors.Window;
            appearance13.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugEpisodioMatilde.DisplayLayout.Appearance = appearance13;
            this.ugEpisodioMatilde.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugEpisodioMatilde.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance14.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance14.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance14.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance14.BorderColor = System.Drawing.SystemColors.Window;
            this.ugEpisodioMatilde.DisplayLayout.GroupByBox.Appearance = appearance14;
            appearance15.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugEpisodioMatilde.DisplayLayout.GroupByBox.BandLabelAppearance = appearance15;
            this.ugEpisodioMatilde.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance16.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance16.BackColor2 = System.Drawing.SystemColors.Control;
            appearance16.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance16.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugEpisodioMatilde.DisplayLayout.GroupByBox.PromptAppearance = appearance16;
            this.ugEpisodioMatilde.DisplayLayout.MaxColScrollRegions = 1;
            this.ugEpisodioMatilde.DisplayLayout.MaxRowScrollRegions = 1;
            appearance17.BackColor = System.Drawing.SystemColors.Window;
            appearance17.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugEpisodioMatilde.DisplayLayout.Override.ActiveCellAppearance = appearance17;
            appearance18.BackColor = System.Drawing.SystemColors.Highlight;
            appearance18.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugEpisodioMatilde.DisplayLayout.Override.ActiveRowAppearance = appearance18;
            this.ugEpisodioMatilde.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugEpisodioMatilde.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance19.BackColor = System.Drawing.SystemColors.Window;
            this.ugEpisodioMatilde.DisplayLayout.Override.CardAreaAppearance = appearance19;
            appearance20.BorderColor = System.Drawing.Color.Silver;
            appearance20.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugEpisodioMatilde.DisplayLayout.Override.CellAppearance = appearance20;
            this.ugEpisodioMatilde.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.ugEpisodioMatilde.DisplayLayout.Override.CellPadding = 0;
            appearance21.BackColor = System.Drawing.SystemColors.Control;
            appearance21.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance21.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance21.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance21.BorderColor = System.Drawing.SystemColors.Window;
            this.ugEpisodioMatilde.DisplayLayout.Override.GroupByRowAppearance = appearance21;
            appearance22.TextHAlignAsString = "Left";
            this.ugEpisodioMatilde.DisplayLayout.Override.HeaderAppearance = appearance22;
            this.ugEpisodioMatilde.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.ugEpisodioMatilde.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance23.BackColor = System.Drawing.SystemColors.Window;
            appearance23.BorderColor = System.Drawing.Color.Silver;
            this.ugEpisodioMatilde.DisplayLayout.Override.RowAppearance = appearance23;
            this.ugEpisodioMatilde.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance24.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugEpisodioMatilde.DisplayLayout.Override.TemplateAddRowAppearance = appearance24;
            this.ugEpisodioMatilde.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugEpisodioMatilde.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugEpisodioMatilde.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugEpisodioMatilde.Dock = System.Windows.Forms.DockStyle.Top;
            this.ugEpisodioMatilde.Location = new System.Drawing.Point(0, 0);
            this.ugEpisodioMatilde.Name = "ugEpisodioMatilde";
            this.ugEpisodioMatilde.Size = new System.Drawing.Size(504, 128);
            this.ugEpisodioMatilde.TabIndex = 0;
            this.ugEpisodioMatilde.Text = "ultraGrid1";
            this.ugEpisodioMatilde.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugEpisodioMatilde_InitializeLayout);
                                                appearance25.BackColor = System.Drawing.SystemColors.Window;
            appearance25.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugTrasferimentiMatilde.DisplayLayout.Appearance = appearance25;
            this.ugTrasferimentiMatilde.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugTrasferimentiMatilde.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance26.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance26.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance26.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance26.BorderColor = System.Drawing.SystemColors.Window;
            this.ugTrasferimentiMatilde.DisplayLayout.GroupByBox.Appearance = appearance26;
            appearance27.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugTrasferimentiMatilde.DisplayLayout.GroupByBox.BandLabelAppearance = appearance27;
            this.ugTrasferimentiMatilde.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance28.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance28.BackColor2 = System.Drawing.SystemColors.Control;
            appearance28.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance28.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugTrasferimentiMatilde.DisplayLayout.GroupByBox.PromptAppearance = appearance28;
            this.ugTrasferimentiMatilde.DisplayLayout.MaxColScrollRegions = 1;
            this.ugTrasferimentiMatilde.DisplayLayout.MaxRowScrollRegions = 1;
            appearance29.BackColor = System.Drawing.SystemColors.Window;
            appearance29.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.ActiveCellAppearance = appearance29;
            appearance30.BackColor = System.Drawing.SystemColors.Highlight;
            appearance30.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.ActiveRowAppearance = appearance30;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance31.BackColor = System.Drawing.SystemColors.Window;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.CardAreaAppearance = appearance31;
            appearance32.BorderColor = System.Drawing.Color.Silver;
            appearance32.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.CellAppearance = appearance32;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.CellPadding = 0;
            appearance33.BackColor = System.Drawing.SystemColors.Control;
            appearance33.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance33.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance33.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance33.BorderColor = System.Drawing.SystemColors.Window;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.GroupByRowAppearance = appearance33;
            appearance34.TextHAlignAsString = "Left";
            this.ugTrasferimentiMatilde.DisplayLayout.Override.HeaderAppearance = appearance34;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance35.BackColor = System.Drawing.SystemColors.Window;
            appearance35.BorderColor = System.Drawing.Color.Silver;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.RowAppearance = appearance35;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance36.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugTrasferimentiMatilde.DisplayLayout.Override.TemplateAddRowAppearance = appearance36;
            this.ugTrasferimentiMatilde.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugTrasferimentiMatilde.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugTrasferimentiMatilde.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugTrasferimentiMatilde.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ugTrasferimentiMatilde.Location = new System.Drawing.Point(0, 140);
            this.ugTrasferimentiMatilde.Name = "ugTrasferimentiMatilde";
            this.ugTrasferimentiMatilde.Size = new System.Drawing.Size(504, 392);
            this.ugTrasferimentiMatilde.TabIndex = 0;
            this.ugTrasferimentiMatilde.Text = "ultraGrid1";
            this.ugTrasferimentiMatilde.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugTrasferimentiMatilde_InitializeLayout);
                                                this.ugbRicerca.Controls.Add(this.tlpRicerca);
            this.ugbRicerca.Dock = System.Windows.Forms.DockStyle.Top;
            appearance37.FontData.BoldAsString = "True";
            this.ugbRicerca.HeaderAppearance = appearance37;
            this.ugbRicerca.Location = new System.Drawing.Point(0, 0);
            this.ugbRicerca.Name = "ugbRicerca";
            this.ugbRicerca.Size = new System.Drawing.Size(1024, 180);
            this.ugbRicerca.TabIndex = 0;
            this.ugbRicerca.Text = "Parametri di ricerca";
            this.ugbRicerca.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.UltraSplitterRicerca.BackColor = System.Drawing.SystemColors.Control;
            appearance38.BackColor = System.Drawing.Color.Lime;
            this.UltraSplitterRicerca.ButtonAppearance = appearance38;
            this.UltraSplitterRicerca.Dock = System.Windows.Forms.DockStyle.Top;
            this.UltraSplitterRicerca.Location = new System.Drawing.Point(0, 180);
            this.UltraSplitterRicerca.Name = "UltraSplitterRicerca";
            this.UltraSplitterRicerca.RestoreExtent = 185;
            this.UltraSplitterRicerca.Size = new System.Drawing.Size(1024, 12);
            this.UltraSplitterRicerca.TabIndex = 7;
                                                this.ugbDati.Controls.Add(this.UltraPanelDX);
            this.ugbDati.Controls.Add(this.UltraSplitterDati);
            this.ugbDati.Controls.Add(this.UltraPanelSX);
            this.ugbDati.Dock = System.Windows.Forms.DockStyle.Fill;
            appearance68.FontData.BoldAsString = "True";
            this.ugbDati.HeaderAppearance = appearance68;
            this.ugbDati.Location = new System.Drawing.Point(0, 192);
            this.ugbDati.Name = "ugbDati";
            this.ugbDati.Size = new System.Drawing.Size(1024, 552);
            this.ugbDati.TabIndex = 1;
            this.ugbDati.Text = "Dati";
            this.ugbDati.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                appearance39.BackColor = System.Drawing.Color.Transparent;
            this.UltraPanelDX.Appearance = appearance39;
                                                this.UltraPanelDX.ClientArea.Controls.Add(this.ugTrasferimentiDWH);
            this.UltraPanelDX.ClientArea.Controls.Add(this.ultraSplitter1);
            this.UltraPanelDX.ClientArea.Controls.Add(this.ugEpisodioDWH);
            this.UltraPanelDX.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UltraPanelDX.Location = new System.Drawing.Point(519, 17);
            this.UltraPanelDX.Name = "UltraPanelDX";
            this.UltraPanelDX.Size = new System.Drawing.Size(502, 532);
            this.UltraPanelDX.TabIndex = 3;
                                                appearance40.BackColor = System.Drawing.SystemColors.Window;
            appearance40.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugTrasferimentiDWH.DisplayLayout.Appearance = appearance40;
            this.ugTrasferimentiDWH.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugTrasferimentiDWH.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance41.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance41.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance41.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance41.BorderColor = System.Drawing.SystemColors.Window;
            this.ugTrasferimentiDWH.DisplayLayout.GroupByBox.Appearance = appearance41;
            appearance42.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugTrasferimentiDWH.DisplayLayout.GroupByBox.BandLabelAppearance = appearance42;
            this.ugTrasferimentiDWH.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance43.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance43.BackColor2 = System.Drawing.SystemColors.Control;
            appearance43.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance43.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugTrasferimentiDWH.DisplayLayout.GroupByBox.PromptAppearance = appearance43;
            this.ugTrasferimentiDWH.DisplayLayout.MaxColScrollRegions = 1;
            this.ugTrasferimentiDWH.DisplayLayout.MaxRowScrollRegions = 1;
            appearance44.BackColor = System.Drawing.SystemColors.Window;
            appearance44.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugTrasferimentiDWH.DisplayLayout.Override.ActiveCellAppearance = appearance44;
            appearance45.BackColor = System.Drawing.SystemColors.Highlight;
            appearance45.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugTrasferimentiDWH.DisplayLayout.Override.ActiveRowAppearance = appearance45;
            this.ugTrasferimentiDWH.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugTrasferimentiDWH.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance46.BackColor = System.Drawing.SystemColors.Window;
            this.ugTrasferimentiDWH.DisplayLayout.Override.CardAreaAppearance = appearance46;
            appearance47.BorderColor = System.Drawing.Color.Silver;
            appearance47.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugTrasferimentiDWH.DisplayLayout.Override.CellAppearance = appearance47;
            this.ugTrasferimentiDWH.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.ugTrasferimentiDWH.DisplayLayout.Override.CellPadding = 0;
            appearance48.BackColor = System.Drawing.SystemColors.Control;
            appearance48.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance48.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance48.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance48.BorderColor = System.Drawing.SystemColors.Window;
            this.ugTrasferimentiDWH.DisplayLayout.Override.GroupByRowAppearance = appearance48;
            appearance49.TextHAlignAsString = "Left";
            this.ugTrasferimentiDWH.DisplayLayout.Override.HeaderAppearance = appearance49;
            this.ugTrasferimentiDWH.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.ugTrasferimentiDWH.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance50.BackColor = System.Drawing.SystemColors.Window;
            appearance50.BorderColor = System.Drawing.Color.Silver;
            this.ugTrasferimentiDWH.DisplayLayout.Override.RowAppearance = appearance50;
            this.ugTrasferimentiDWH.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance51.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugTrasferimentiDWH.DisplayLayout.Override.TemplateAddRowAppearance = appearance51;
            this.ugTrasferimentiDWH.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugTrasferimentiDWH.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugTrasferimentiDWH.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugTrasferimentiDWH.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ugTrasferimentiDWH.Location = new System.Drawing.Point(0, 140);
            this.ugTrasferimentiDWH.Name = "ugTrasferimentiDWH";
            this.ugTrasferimentiDWH.Size = new System.Drawing.Size(502, 392);
            this.ugTrasferimentiDWH.TabIndex = 0;
            this.ugTrasferimentiDWH.Text = "ultraGrid1";
            this.ugTrasferimentiDWH.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugTrasferimentiDWH_InitializeLayout);
                                                this.ultraSplitter1.BackColor = System.Drawing.SystemColors.Control;
            appearance52.BackColor = System.Drawing.Color.Lime;
            this.ultraSplitter1.ButtonAppearance = appearance52;
            this.ultraSplitter1.Dock = System.Windows.Forms.DockStyle.Top;
            this.ultraSplitter1.Location = new System.Drawing.Point(0, 128);
            this.ultraSplitter1.Name = "ultraSplitter1";
            this.ultraSplitter1.RestoreExtent = 289;
            this.ultraSplitter1.Size = new System.Drawing.Size(502, 12);
            this.ultraSplitter1.TabIndex = 10;
                                                appearance53.BackColor = System.Drawing.SystemColors.Window;
            appearance53.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugEpisodioDWH.DisplayLayout.Appearance = appearance53;
            this.ugEpisodioDWH.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugEpisodioDWH.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance54.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance54.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance54.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance54.BorderColor = System.Drawing.SystemColors.Window;
            this.ugEpisodioDWH.DisplayLayout.GroupByBox.Appearance = appearance54;
            appearance55.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugEpisodioDWH.DisplayLayout.GroupByBox.BandLabelAppearance = appearance55;
            this.ugEpisodioDWH.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance56.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance56.BackColor2 = System.Drawing.SystemColors.Control;
            appearance56.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance56.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugEpisodioDWH.DisplayLayout.GroupByBox.PromptAppearance = appearance56;
            this.ugEpisodioDWH.DisplayLayout.MaxColScrollRegions = 1;
            this.ugEpisodioDWH.DisplayLayout.MaxRowScrollRegions = 1;
            appearance57.BackColor = System.Drawing.SystemColors.Window;
            appearance57.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugEpisodioDWH.DisplayLayout.Override.ActiveCellAppearance = appearance57;
            appearance58.BackColor = System.Drawing.SystemColors.Highlight;
            appearance58.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugEpisodioDWH.DisplayLayout.Override.ActiveRowAppearance = appearance58;
            this.ugEpisodioDWH.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugEpisodioDWH.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance59.BackColor = System.Drawing.SystemColors.Window;
            this.ugEpisodioDWH.DisplayLayout.Override.CardAreaAppearance = appearance59;
            appearance60.BorderColor = System.Drawing.Color.Silver;
            appearance60.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugEpisodioDWH.DisplayLayout.Override.CellAppearance = appearance60;
            this.ugEpisodioDWH.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.ugEpisodioDWH.DisplayLayout.Override.CellPadding = 0;
            appearance61.BackColor = System.Drawing.SystemColors.Control;
            appearance61.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance61.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance61.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance61.BorderColor = System.Drawing.SystemColors.Window;
            this.ugEpisodioDWH.DisplayLayout.Override.GroupByRowAppearance = appearance61;
            appearance62.TextHAlignAsString = "Left";
            this.ugEpisodioDWH.DisplayLayout.Override.HeaderAppearance = appearance62;
            this.ugEpisodioDWH.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.ugEpisodioDWH.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance63.BackColor = System.Drawing.SystemColors.Window;
            appearance63.BorderColor = System.Drawing.Color.Silver;
            this.ugEpisodioDWH.DisplayLayout.Override.RowAppearance = appearance63;
            this.ugEpisodioDWH.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance64.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugEpisodioDWH.DisplayLayout.Override.TemplateAddRowAppearance = appearance64;
            this.ugEpisodioDWH.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugEpisodioDWH.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugEpisodioDWH.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugEpisodioDWH.Dock = System.Windows.Forms.DockStyle.Top;
            this.ugEpisodioDWH.Location = new System.Drawing.Point(0, 0);
            this.ugEpisodioDWH.Name = "ugEpisodioDWH";
            this.ugEpisodioDWH.Size = new System.Drawing.Size(502, 128);
            this.ugEpisodioDWH.TabIndex = 0;
            this.ugEpisodioDWH.Text = "ultraGrid1";
            this.ugEpisodioDWH.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugEpisodioDWH_InitializeLayout);
                                                this.UltraSplitterDati.BackColor = System.Drawing.SystemColors.Control;
            appearance65.BackColor = System.Drawing.Color.Lime;
            this.UltraSplitterDati.ButtonAppearance = appearance65;
            this.UltraSplitterDati.Location = new System.Drawing.Point(507, 17);
            this.UltraSplitterDati.Name = "UltraSplitterDati";
            this.UltraSplitterDati.RestoreExtent = 0;
            this.UltraSplitterDati.Size = new System.Drawing.Size(12, 532);
            this.UltraSplitterDati.TabIndex = 1;
                                                appearance66.BackColor = System.Drawing.Color.Transparent;
            this.UltraPanelSX.Appearance = appearance66;
                                                this.UltraPanelSX.ClientArea.Controls.Add(this.ugTrasferimentiMatilde);
            this.UltraPanelSX.ClientArea.Controls.Add(this.ultraSplitter4);
            this.UltraPanelSX.ClientArea.Controls.Add(this.ugEpisodioMatilde);
            this.UltraPanelSX.Dock = System.Windows.Forms.DockStyle.Left;
            this.UltraPanelSX.Location = new System.Drawing.Point(3, 17);
            this.UltraPanelSX.Name = "UltraPanelSX";
            this.UltraPanelSX.Size = new System.Drawing.Size(504, 532);
            this.UltraPanelSX.TabIndex = 2;
                                                this.ultraSplitter4.BackColor = System.Drawing.SystemColors.Control;
            appearance67.BackColor = System.Drawing.Color.Lime;
            this.ultraSplitter4.ButtonAppearance = appearance67;
            this.ultraSplitter4.Dock = System.Windows.Forms.DockStyle.Top;
            this.ultraSplitter4.Location = new System.Drawing.Point(0, 128);
            this.ultraSplitter4.Name = "ultraSplitter4";
            this.ultraSplitter4.RestoreExtent = 289;
            this.ultraSplitter4.Size = new System.Drawing.Size(504, 12);
            this.ultraSplitter4.TabIndex = 10;
                                                this.UltraSplitterCorrezione.BackColor = System.Drawing.SystemColors.Control;
            appearance69.BackColor = System.Drawing.Color.Lime;
            this.UltraSplitterCorrezione.ButtonAppearance = appearance69;
            this.UltraSplitterCorrezione.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.UltraSplitterCorrezione.Location = new System.Drawing.Point(0, 756);
            this.UltraSplitterCorrezione.Name = "UltraSplitterCorrezione";
            this.UltraSplitterCorrezione.RestoreExtent = 200;
            this.UltraSplitterCorrezione.Size = new System.Drawing.Size(1024, 12);
            this.UltraSplitterCorrezione.TabIndex = 12;
                                                this.ugbCorrezione.Controls.Add(this.tableLayoutPanel1);
            this.ugbCorrezione.Dock = System.Windows.Forms.DockStyle.Bottom;
            appearance82.FontData.BoldAsString = "True";
            this.ugbCorrezione.HeaderAppearance = appearance82;
            this.ugbCorrezione.Location = new System.Drawing.Point(0, 768);
            this.ugbCorrezione.Name = "ugbCorrezione";
            this.ugbCorrezione.Size = new System.Drawing.Size(1024, 0);
            this.ugbCorrezione.TabIndex = 13;
            this.ugbCorrezione.Text = "Correzione";
            this.ugbCorrezione.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.tableLayoutPanel1.BackColor = System.Drawing.Color.Transparent;
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.ugCorrezione, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(3, 17);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1018, 0);
            this.tableLayoutPanel1.TabIndex = 6;
                                                appearance70.BackColor = System.Drawing.SystemColors.Window;
            appearance70.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugCorrezione.DisplayLayout.Appearance = appearance70;
            this.ugCorrezione.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugCorrezione.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance71.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance71.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance71.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance71.BorderColor = System.Drawing.SystemColors.Window;
            this.ugCorrezione.DisplayLayout.GroupByBox.Appearance = appearance71;
            appearance72.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugCorrezione.DisplayLayout.GroupByBox.BandLabelAppearance = appearance72;
            this.ugCorrezione.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance73.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance73.BackColor2 = System.Drawing.SystemColors.Control;
            appearance73.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance73.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugCorrezione.DisplayLayout.GroupByBox.PromptAppearance = appearance73;
            this.ugCorrezione.DisplayLayout.MaxColScrollRegions = 1;
            this.ugCorrezione.DisplayLayout.MaxRowScrollRegions = 1;
            appearance74.BackColor = System.Drawing.SystemColors.Window;
            appearance74.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugCorrezione.DisplayLayout.Override.ActiveCellAppearance = appearance74;
            appearance75.BackColor = System.Drawing.SystemColors.Highlight;
            appearance75.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugCorrezione.DisplayLayout.Override.ActiveRowAppearance = appearance75;
            this.ugCorrezione.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugCorrezione.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance76.BackColor = System.Drawing.SystemColors.Window;
            this.ugCorrezione.DisplayLayout.Override.CardAreaAppearance = appearance76;
            appearance77.BorderColor = System.Drawing.Color.Silver;
            appearance77.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugCorrezione.DisplayLayout.Override.CellAppearance = appearance77;
            this.ugCorrezione.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.ugCorrezione.DisplayLayout.Override.CellPadding = 0;
            appearance78.BackColor = System.Drawing.SystemColors.Control;
            appearance78.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance78.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance78.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance78.BorderColor = System.Drawing.SystemColors.Window;
            this.ugCorrezione.DisplayLayout.Override.GroupByRowAppearance = appearance78;
            appearance79.TextHAlignAsString = "Left";
            this.ugCorrezione.DisplayLayout.Override.HeaderAppearance = appearance79;
            this.ugCorrezione.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.ugCorrezione.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance80.BackColor = System.Drawing.SystemColors.Window;
            appearance80.BorderColor = System.Drawing.Color.Silver;
            this.ugCorrezione.DisplayLayout.Override.RowAppearance = appearance80;
            this.ugCorrezione.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance81.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugCorrezione.DisplayLayout.Override.TemplateAddRowAppearance = appearance81;
            this.ugCorrezione.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugCorrezione.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugCorrezione.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugCorrezione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ugCorrezione.Location = new System.Drawing.Point(3, 3);
            this.ugCorrezione.Name = "ugCorrezione";
            this.ugCorrezione.Size = new System.Drawing.Size(1012, 1);
            this.ugCorrezione.TabIndex = 0;
            this.ugCorrezione.Text = "ultraGrid1";
            this.ugCorrezione.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugCorrezione_InitializeLayout);
            this.ugCorrezione.BeforeRowsDeleted += new Infragistics.Win.UltraWinGrid.BeforeRowsDeletedEventHandler(this.ugCorrezione_BeforeRowsDeleted);
            this.ugCorrezione.DragDrop += new System.Windows.Forms.DragEventHandler(this.ugCorrezione_DragDrop);
            this.ugCorrezione.DragOver += new System.Windows.Forms.DragEventHandler(this.ugCorrezione_DragOver);
                                                this.ugbSimulazione.Controls.Add(this.tlpSimulazione);
            this.ugbSimulazione.Dock = System.Windows.Forms.DockStyle.Bottom;
            appearance95.FontData.BoldAsString = "True";
            this.ugbSimulazione.HeaderAppearance = appearance95;
            this.ugbSimulazione.Location = new System.Drawing.Point(0, 756);
            this.ugbSimulazione.Name = "ugbSimulazione";
            this.ugbSimulazione.Size = new System.Drawing.Size(1024, 0);
            this.ugbSimulazione.TabIndex = 14;
            this.ugbSimulazione.Text = "Simulazione";
            this.ugbSimulazione.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2007;
                                                this.tlpSimulazione.BackColor = System.Drawing.Color.Transparent;
            this.tlpSimulazione.ColumnCount = 1;
            this.tlpSimulazione.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpSimulazione.Controls.Add(this.ugSimulazione, 0, 0);
            this.tlpSimulazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpSimulazione.Location = new System.Drawing.Point(3, 17);
            this.tlpSimulazione.Name = "tlpSimulazione";
            this.tlpSimulazione.RowCount = 1;
            this.tlpSimulazione.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpSimulazione.Size = new System.Drawing.Size(1018, 0);
            this.tlpSimulazione.TabIndex = 6;
                                                appearance83.BackColor = System.Drawing.SystemColors.Window;
            appearance83.BorderColor = System.Drawing.SystemColors.InactiveCaption;
            this.ugSimulazione.DisplayLayout.Appearance = appearance83;
            this.ugSimulazione.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.ugSimulazione.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            appearance84.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance84.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance84.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance84.BorderColor = System.Drawing.SystemColors.Window;
            this.ugSimulazione.DisplayLayout.GroupByBox.Appearance = appearance84;
            appearance85.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugSimulazione.DisplayLayout.GroupByBox.BandLabelAppearance = appearance85;
            this.ugSimulazione.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance86.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance86.BackColor2 = System.Drawing.SystemColors.Control;
            appearance86.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance86.ForeColor = System.Drawing.SystemColors.GrayText;
            this.ugSimulazione.DisplayLayout.GroupByBox.PromptAppearance = appearance86;
            this.ugSimulazione.DisplayLayout.MaxColScrollRegions = 1;
            this.ugSimulazione.DisplayLayout.MaxRowScrollRegions = 1;
            appearance87.BackColor = System.Drawing.SystemColors.Window;
            appearance87.ForeColor = System.Drawing.SystemColors.ControlText;
            this.ugSimulazione.DisplayLayout.Override.ActiveCellAppearance = appearance87;
            appearance88.BackColor = System.Drawing.SystemColors.Highlight;
            appearance88.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.ugSimulazione.DisplayLayout.Override.ActiveRowAppearance = appearance88;
            this.ugSimulazione.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Dotted;
            this.ugSimulazione.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Dotted;
            appearance89.BackColor = System.Drawing.SystemColors.Window;
            this.ugSimulazione.DisplayLayout.Override.CardAreaAppearance = appearance89;
            appearance90.BorderColor = System.Drawing.Color.Silver;
            appearance90.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.ugSimulazione.DisplayLayout.Override.CellAppearance = appearance90;
            this.ugSimulazione.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.EditAndSelectText;
            this.ugSimulazione.DisplayLayout.Override.CellPadding = 0;
            appearance91.BackColor = System.Drawing.SystemColors.Control;
            appearance91.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance91.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance91.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance91.BorderColor = System.Drawing.SystemColors.Window;
            this.ugSimulazione.DisplayLayout.Override.GroupByRowAppearance = appearance91;
            appearance92.TextHAlignAsString = "Left";
            this.ugSimulazione.DisplayLayout.Override.HeaderAppearance = appearance92;
            this.ugSimulazione.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.ugSimulazione.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.WindowsXPCommand;
            appearance93.BackColor = System.Drawing.SystemColors.Window;
            appearance93.BorderColor = System.Drawing.Color.Silver;
            this.ugSimulazione.DisplayLayout.Override.RowAppearance = appearance93;
            this.ugSimulazione.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            appearance94.BackColor = System.Drawing.SystemColors.ControlLight;
            this.ugSimulazione.DisplayLayout.Override.TemplateAddRowAppearance = appearance94;
            this.ugSimulazione.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.ugSimulazione.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.ugSimulazione.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.ugSimulazione.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ugSimulazione.Location = new System.Drawing.Point(3, 3);
            this.ugSimulazione.Name = "ugSimulazione";
            this.ugSimulazione.Size = new System.Drawing.Size(1012, 1);
            this.ugSimulazione.TabIndex = 0;
            this.ugSimulazione.Text = "ultraGrid1";
            this.ugSimulazione.InitializeLayout += new Infragistics.Win.UltraWinGrid.InitializeLayoutEventHandler(this.ugSimulazione_InitializeLayout);
            this.ugSimulazione.SelectionDrag += new System.ComponentModel.CancelEventHandler(this.ugSimulazione_SelectionDrag);
                                                this.UltraSplitterSimulazione.BackColor = System.Drawing.SystemColors.Control;
            appearance96.BackColor = System.Drawing.Color.Lime;
            this.UltraSplitterSimulazione.ButtonAppearance = appearance96;
            this.UltraSplitterSimulazione.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.UltraSplitterSimulazione.Location = new System.Drawing.Point(0, 744);
            this.UltraSplitterSimulazione.Name = "UltraSplitterSimulazione";
            this.UltraSplitterSimulazione.RestoreExtent = 250;
            this.UltraSplitterSimulazione.Size = new System.Drawing.Size(1024, 12);
            this.UltraSplitterSimulazione.TabIndex = 15;
                                                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.ugbDati);
            this.Controls.Add(this.UltraSplitterSimulazione);
            this.Controls.Add(this.ugbSimulazione);
            this.Controls.Add(this.UltraSplitterCorrezione);
            this.Controls.Add(this.UltraSplitterRicerca);
            this.Controls.Add(this.ugbRicerca);
            this.Controls.Add(this.ugbCorrezione);
            this.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "ucAllineaADT";
            this.Size = new System.Drawing.Size(1024, 768);
            this.tlpRicerca.ResumeLayout(false);
            this.tlpRicerca.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.uteListaAttesa)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteNosologico)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.uteIDEpisodio)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugEpisodi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugEpisodioMatilde)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugTrasferimentiMatilde)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugbRicerca)).EndInit();
            this.ugbRicerca.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ugbDati)).EndInit();
            this.ugbDati.ResumeLayout(false);
            this.UltraPanelDX.ClientArea.ResumeLayout(false);
            this.UltraPanelDX.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ugTrasferimentiDWH)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugEpisodioDWH)).EndInit();
            this.UltraPanelSX.ClientArea.ResumeLayout(false);
            this.UltraPanelSX.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ugbCorrezione)).EndInit();
            this.ugbCorrezione.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ugCorrezione)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ugbSimulazione)).EndInit();
            this.ugbSimulazione.ResumeLayout(false);
            this.tlpSimulazione.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ugSimulazione)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.TableLayoutPanel tlpRicerca;
        private System.Windows.Forms.Label lblIDEpisodio;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteIDEpisodio;
        private System.Windows.Forms.Label lblNosologico;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteNosologico;
        private Infragistics.Win.UltraWinGrid.UltraGrid ugEpisodi;
        private Infragistics.Win.Misc.UltraButton ubRicerca;
        private Infragistics.Win.UltraWinGrid.UltraGrid ugEpisodioMatilde;
        private Infragistics.Win.UltraWinGrid.UltraGrid ugTrasferimentiMatilde;
        private Infragistics.Win.Misc.UltraGroupBox ugbRicerca;
        private Infragistics.Win.Misc.UltraSplitter UltraSplitterRicerca;
        private Infragistics.Win.Misc.UltraGroupBox ugbDati;
        private Infragistics.Win.Misc.UltraSplitter UltraSplitterDati;
        private Infragistics.Win.Misc.UltraPanel UltraPanelSX;
        private Infragistics.Win.Misc.UltraSplitter ultraSplitter4;
        private Infragistics.Win.Misc.UltraPanel UltraPanelDX;
        private Infragistics.Win.UltraWinGrid.UltraGrid ugTrasferimentiDWH;
        private Infragistics.Win.Misc.UltraSplitter ultraSplitter1;
        private Infragistics.Win.UltraWinGrid.UltraGrid ugEpisodioDWH;
        private Infragistics.Win.Misc.UltraButton ubCheck;
        private Infragistics.Win.UltraWinEditors.UltraTextEditor uteListaAttesa;
        private System.Windows.Forms.Label lblListaAttesa;
        private System.Windows.Forms.Label lblPaziente;
        private Infragistics.Win.Misc.UltraButton ubSimula;
        private Infragistics.Win.Misc.UltraSplitter UltraSplitterCorrezione;
        private Infragistics.Win.Misc.UltraGroupBox ugbCorrezione;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private Infragistics.Win.UltraWinGrid.UltraGrid ugCorrezione;
        private Infragistics.Win.Misc.UltraGroupBox ugbSimulazione;
        private System.Windows.Forms.TableLayoutPanel tlpSimulazione;
        private Infragistics.Win.UltraWinGrid.UltraGrid ugSimulazione;
        private Infragistics.Win.Misc.UltraSplitter UltraSplitterSimulazione;
        private Infragistics.Win.Misc.UltraButton ubCorreggi;
    }
}
